### ISSUE TITLE
graphql-server-lambda - graphiql not compatible with nodejs8.10 runtime

### ISSUE THREAD

**Issue by nenti** [apollographql/apollo-server#1042]
graphiql handler is failing with no error message thrown when changing lambda runtime to nodejs8.10

**Comment by dhm116** [comment]
We're running graphiql with the nodejs8.10 runtime without any issues that we're aware of - are you able to provide any snippets demonstrating the issue?

Aside from the serverless configuration, this is all we needed to enable graphiql to work with serverless and serverless-offline:

```js
// Avoid using async/promises until apollo-server-lambda/apollo-server-core
// are updated to support async/await
exports.graphiqlHandler = (event, context, callback) => {
  const graphqlHandler = graphiqlLambda({ endpointURL: '/graphql' });
  return graphqlHandler(event, context, callback);
};
```

**Comment by nenti** [comment]
My failing handler looks like this. Node6 workd node8 fails. Interesting.
``` js
return server.graphiqlLambda({
    endpointURL: GRAPHQL_ENDPOINT,
    passHeader: event.queryStringParameters && event.queryStringParameters.auth,
})(event, context, callback)
```

**Comment by evans** [comment]
I'm going to close this, since it seems we've figured out the issue and #1125 is out!

**Comment by khaledosman** [comment]
Is it possible to use graphiql with apollo-server2 or only playground?

I get TypeError: server.graphiqlLambda is not a function
