### ISSUE TITLE
How to custom route in apollo-server 2 beta ?

### ISSUE THREAD

**Issue by silkyland** [apollographql/apollo-server#1043]
Hello, I'm using Apollo Server 2 beta and every request redirect to / , can anyone tell me how to custom route eg. http://localhost:4000/auth/login ?

**Comment by carlbarrdahl** [comment]
Did you manage to solve this?

**Comment by AmitBhoyarGit** [comment]
import express from 'express';
import {
	ApolloServer
} from 'apollo-server-express';

const GRAPHQL_PORT = 4000;
const path = '/auth/login';
const app = express();
const server = new ApolloServer({
	schema
});

server.applyMiddleware({
	app,
	path
});
app.listen({
		port: GRAPHQL_PORT
	}, () =>
	console.log(`🚀 Server ready at http://localhost:${GRAPHQL_PORT}/${server.graphqlPath}`)
)

**Comment by jayliew** [comment]
`server.applyMiddleware({
app: app,
path: path
})`

worked for me
