### ISSUE TITLE
Error: Must provide typeDefs - apollo-server: 2.0.0-beta.1

### ISSUE THREAD

**Issue by damianthekreeeytor** [apollographql/apollo-server#1044]
Using:

"apollo-server": "^2.0.0-beta.1",
"apollo-server-express": "^2.0.0-beta.0",

With the following code to initialize the server:

```javascript
const server = new ApolloServer(req => ({
  typeDefs,
  resolvers,
  engine: true,
  context: async () => ({
    mongo: await connectMongo(),
    user: req.user
  })
}))

registerServer({ server, app })

// normal ApolloServer listen call but url will contain /graphql
const PORT = process.env.PORT || 3000
server.listen({ port: PORT }).then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`)
})
```

I receive the follow error in my console:

```
bash
        throw new SchemaError('Must provide typeDefs');
        ^

Error: Must provide typeDefs
```

If just provide and object with instead of a function into the constructor is works, but I am integrating this with an express app which provides authentication.

Any help will be much appreciated.

**Comment by silkyland** [comment]
I think it should be 
`const server = new ApolloServer({
  typeDefs,
  resolvers,
  engine: true,
  context: async () => ({
    mongo: await connectMongo(),
    user: req.user
  })
})
`
without req => ({ ...

**Comment by damianthekreeeytor** [comment]
That worked out thank you!

**Comment by gtwright** [comment]
I tried this solution. It solves the 'Must provide typeDefs' error, but now I'm getting 'req is not defined'

**Comment by silkyland** [comment]
@gtwright  I think you have not defined a "req" variable. Maybe you need to remove it from the context like this : 
 ```javascript   
const server = new ApolloServer({
  typeDefs,
  resolvers,
  engine: true,
  context: async () => ({
    mongo: await connectMongo(),
  })
})
 ```
This was remove from code : 
~~user: req.user~~
