### ISSUE TITLE
Cache full query responses

### ISSUE THREAD

**Issue by damogallagher** [apollographql/apollo-server#1050]
Hi

I have taken over a project that uses the apollo-server-lambda.
For some of these schema models, I want to store the response in redis to minimize on traffic.

What is the best approach for doing this?

Regards
Damien

**Comment by richardwillars** [comment]
Trying to do something similar (Apollo Engine isn't right for our infrastructure). Feels like https://github.com/apollographql/apollo-server/issues/657 is the best way of doing it, but unfortunately you can't add custom extensions at the moment. Bit of a deal breaker at this point!

**Comment by evans** [comment]
@damogallagher This is on the roadmap for Apollo Server 2. If you'd like to help with the implementation of the Redis cache, I'd be happy to discuss the API we are thinking about.

**Comment by evans** [comment]
@damogallagher The best way to do this now is to use partial query caching with [Data Source](https://www.apollographql.com/docs/apollo-server/v2/features/data-sources.html). You can use Redis or memcache depending on your backend. Right now the lambda edition of AS is being worked on #1188. If you want to join the development effort, we'd love some help with a dedicated deployment guide next to https://www.apollographql.com/docs/apollo-server/v2/deployment/heroku.html

**Comment by jbaxleyiii** [comment]
@damogallagher this is possible using the built in caching of Apollo Server! https://www.apollographql.com/docs/apollo-server/features/caching/
