### ISSUE TITLE
not able to catch errors

### ISSUE THREAD

**Issue by alidcastano** [apollographql/apollo-server#1053]
For testing, I'm trying to test that a resolver throws an error. However, I'm not able to catch the error.

e.g. `request(apolloData).catch(err => console.log(err)` never gets called but I can still acess the error via `errors` property that is returned as a succesful request.

I was able to silence the error by putting `dedug: false` in the apollo server options. But disabling debugging during testing seems like a suboptimal solution.

So I wanted to ask: is it intended that errors get returned as succesful responses and is disabling debugging the only way to silence them?

Thanks

**Comment by Tyler-Churchill** [comment]
Errors get sent as a successful response, that is the GraphQL way from what I know.
Its a lot different from REST in that you can get back data, null errors. data and some errors, or no data and errors. 

A request will only get sent back let's say 500 errors if the transportation fails from client to server.

Take a look at
https://github.com/apollographql/graphql-tools/issues/291

**Comment by evans** [comment]
Thanks @Tyler-Churchill !

To add, when there is no data and errors, then apollo-server will return a 400 error. Otherwise it will return a 200 response, even if some of the resolvers error
