### ISSUE TITLE
Errors thrown by a remote graphql engine should be passed through by default

### ISSUE THREAD

**Issue by jdubray** [apollographql/apollo-server#1077]
We are developing a graphql server that exposes "remote schemas". When a remote engine throws an exceptions the proxy engine rethrows a new exception which embeds the remote exception. I believe it would be more desirable to have a behavior where the remote exceptions are simply passed through. 
It's not difficult to implement that behavior (we have done it with formatError by extracting and returning the embedded error), but it'd be more logical if it was the default behavior.

**Comment by evans** [comment]
This is fixed with #1113 and will be a part of Apollo Server 2 🎉
