### ISSUE TITLE
Creating apollo server with http.createServer without any libraries

### ISSUE THREAD

**Issue by yuraxdrumz** [apollographql/apollo-server#1078]
- [ ] has-reproduction
- [x] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

Hey, I am building a web server framework and I wanted to incorporate a declarative wrapper around graphql with apollo server, I searched the docs and everywhere on Github on how to add it to http.createServer and I only found examples with express.
I saw in the source code this piece of code with express, It would work great in my framework, the problem is I do not have next, so i get an error, otherwise, it works if I mock next.

![screenshot_3](https://user-images.githubusercontent.com/17418978/40334129-b2b6b698-5d64-11e8-8f68-938ff738dc37.png)

Is it possible to create something similar without next and all the extra dependencies ?
Thanks in advance, love your project!

**Comment by evans** [comment]
@yuraxdrumz That's possible with the new Apollo Server 2 beta. Check out [the tests](https://github.com/apollographql/apollo-server/pull/1063/files#diff-4793189b9a83e7b56e97bd024540b79f) for the core library, which uses a regular httpServer.

If you would like to contribute to the main line of apollo server integrations, #1088 is a great place to start
