### ISSUE TITLE
Apollo Server 2: Integrations (Adonis, Micro, Restify, Koa)

### ISSUE THREAD

**Issue by evans** [apollographql/apollo-server#1088]
Currently Apollo Server 2.0 contains implementations for express and hapi. The api is generally stable, so there is now an opportunity to implement the new Apollo Server functionality for the other server variants.

This issue tracks the progress on other integrations, which should reach feature parity with the other variants. Currently, the express and hapi integrations each provide a `registerServer` function that adds a fully functional graphql endpoint at the specified `path` with a collocated instance of graphql-playground that runs if a request from [the browser is detected](https://github.com/apollographql/apollo-server/blob/1f784636d9c0a0576fb80191425e5d67fb09cd5f/packages/apollo-server-express/src/ApolloServer.ts#L66-L71). The new server variants also provide the ability to configure a [healthcheck endpoint](https://github.com/apollographql/apollo-server/blob/1f784636d9c0a0576fb80191425e5d67fb09cd5f/packages/apollo-server-express/src/ApolloServer.ts#L32-L50).

To get started, take a look at the ApolloServer.ts file for [express](https://github.com/apollographql/apollo-server/blob/version-2/packages/apollo-server-express/src/ApolloServer.ts) and for [hapi](https://github.com/apollographql/apollo-server/blob/version-2/packages/apollo-server-hapi/src/ApolloServer.ts) on the [version-2 branch](https://github.com/apollographql/apollo-server/tree/version-2). 

**Integrations**

- [x] Koa @Esemesek 
- [ ] Adonis
- [x] Micro @hwillson
- [ ] Restify
- [x] Lambda @adnsio 
- [ ] Azure Functions

**Comment by Esemesek** [comment]
Can I claim this issue?

**Comment by evans** [comment]
@Esemesek Absolutely! Which would you like to start with?

Here's a [graph of popularity](https://npm-stat.com/charts.html?package=apollo-server-koa&package=apollo-server-adonis&package=apollo-server-micro&package=apollo-server-restify) if that helps you choose! 

Let me know if you have any questions, I'm @evans on the [Apollo slack](https://www.apollographql.com/slack)

**Comment by hwillson** [comment]
Sign me up - I'll tackle Mirco to start. Thanks!

**Comment by adnsio** [comment]
Hi guys, I wrote an integration for native http, https and http2 of nodejs.
Would it be useful to include it in this monorepo?

https://github.com/adnsio/apollo-server-native

**Comment by adnsio** [comment]
I'm working on `apollo-server-lambda` for Apollo Server 2: https://github.com/adnsio/apollo-server/tree/version-2/packages/apollo-server-lambda

**Comment by mikeclymer** [comment]
Not sure if this is the correct issue for my request, but I would like to see [apollo-server-azure-functions](https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-azure-functions) added to the list. I am assuming that an updated Azure Functions integration will need to factor in the current development of v2.0 of their runtime - [Azure Functions runtime 2.0 known issues](https://github.com/Azure/azure-functions-host/wiki/Azure-Functions-runtime-2.0-known-issues)

I don't currently have the bandwidth, or comfort level, to take on this integration myself. But I can test and provide feedback. Let me know if I need to create a separate issue for this integration.

**Comment by evans** [comment]
@mikeclymer Thanks for bringing azure functions up and pointing at the known issues! I've added it to the list. I'd imagine the package turns out similar to #1188

**Comment by hwillson** [comment]
We'll track new future integrations in separate issues. Thanks everyone!

**Comment by jpcbarros** [comment]
Is Apollo Server 2 support for Adonis coming?

**Comment by enniel** [comment]
Support for Adonis Framework added in PR #1937.
