### ISSUE TITLE
[question] graphql playground in production

### ISSUE THREAD

**Issue by francoisromain** [apollographql/apollo-server#1089]
In graphql-server 2 beta, when `NODE_ENV` is set to `production`, graphql-playground is not available anymore. 

Is there an option to keep it working in production? 

Thank you

**Comment by evans** [comment]
@francoisromain Thanks for opening the issue! With the newest beta, you can set `introspection` to true. [Here](https://github.com/apollographql/apollo-server/pull/1063/files#diff-3467ccc78fbd796513acd747ff2110a5R94) is where that behavior is defined.

If you are up for it and want to help other people coming to the repository by adding a segment to the [what's new section](https://github.com/apollographql/apollo-server/blob/version-2/docs/source/whats-new.md) about GraphQL playground in dev vs production, that would be incredible!
