### ISSUE TITLE
How to use typed resolver arguments?

### ISSUE THREAD

**Issue by marceloverdijk** [apollographql/apollo-server#1092]
The resolver function signature in the documentation (https://www.apollographql.com/docs/graphql-tools/resolvers) looks like: 

`fieldName(obj, args, context, info) { result }`

If we want to type the arguments what should be used?
I believe the `info` argument is a `GraphQLResolveInfo` but what to use for the others?

**Comment by evans** [comment]
(Here)[https://github.com/apollographql/graphql-tools/blob/master/src/Interfaces.ts#L72] is the signature of the resolvers. It's up to you how to type the `parent` and `context` objects. Be careful, since the `parent` can change depending on the query.
