### ISSUE TITLE
Input Type Coercion seems wrong

### ISSUE THREAD

**Issue by astanciu** [apollographql/apollo-server#1106]
Trying to understand if this is expected behavior:

Schema defines an input type:
```graphql
input ExampleInput {
  a: String
  b: Boolean
}
```

If client sends:
```json
{
 "a": {"something": "bad"},
 "b": "whatever"
}
```
This is accepted by the server and the resolver receives:
```json
{
  "a": "[object Object]",
  "b": true
}
```

This seems very wrong to me. At the very least there should be an option to not coerce the input type to the schema type and instead throw an error. 

Also, if I read the spec correctly here: http://facebook.github.io/graphql/October2016/
under the String type it states:

>When expected as an input type, only valid UTF‐8 string input values are accepted. All other input values must raise a query error indicating an incorrect type.

**Comment by astanciu** [comment]
After a little more digging, issue is related to this: https://github.com/graphql/graphql-js/issues/1324

**Comment by abernix** [comment]
Thanks to https://github.com/graphql/graphql-js/issues/1324, this should be fixed by upgrading the `graphql` peer dependency to `graphql@14` — but please keep in mind that's a breaking change!
