### ISSUE TITLE
Modular schema apolloserver v2- help!

### ISSUE THREAD

**Issue by daniele-zurico** [apollographql/apollo-server#1127]
Hi guys I’m having a tough problem. I’m using apolloserver v2 and I would like to understand how I can modularise my schema. This is the repro is setup: http://github.com/daniele-zurico… ? The doc looks like is more for v1...can I have some help please?

**Comment by daniele-zurico** [comment]
I'm trying to use mergeSchemas
```const typeDefs: any = mergeSchemas({
	schemas: [helloSchema, userSchema]
});

export default typeDefs;```

and
```
const server = new ApolloServer({
	typeDefs,
	resolvers
});
```

but now is complaining about: 
`Error: typeDefs must be a string, array or schema AST, got object`

any idea?

**Comment by damianthekreeeytor** [comment]
if you console.log your typeDefs what are the results?
