### ISSUE TITLE
apollo server azure functions example does not work

### ISSUE THREAD

**Issue by andyce1010** [apollographql/apollo-server#1135]
I have followed these steps to try and get an azure function working:
1. Created an new azure function
2. Pasted in the example code from:
 https://www.apollographql.com/docs/apollo-server/servers/azure-functions.html#GraphQL
3. Used the Kudu control to install the npm dependancies for apollo-server-azure-functions and graphql-tools.

I have Run the function with the following as the post body:
{
      rands {
        id
        rand
      }
}

But the function throws a 500 error with the following:
2018-06-04T14:19:49.373 [Error] Exception while executing function: Functions.HttpTriggerJS1. mscorlib: SyntaxError: Unexpected token r in JSON at position 9
    at Object.parse (native)
    at graphqlHandler (D:\home\site\wwwroot\node_modules\apollo-server-azure-functions\dist\azureFunctionsApollo.js:20:39)
    at run (D:\home\site\wwwroot\HttpTriggerJS1\index.js:31:36)
    at D:\Program Files (x86)\SiteExtensions\Functions\1.0.11702\bin\azurefunctions\functions.js:106:24.

Have I missed a step, or is something broken in the example?

**Comment by evans** [comment]
@andyce1010 did you end up resolving the issue? We're working towards AS2, so I'm curious your status and how we'll have to update for #1088

**Comment by evans** [comment]
I'm going to close this, since it hasn't had any updates and the example doesn't seem to be broken

**Comment by evans** [comment]
@simonaco Thanks for pointing that out! https://www.apollographql.com/docs/apollo-server/v1/servers/azure-functions.html#GraphQL is where you'll find the version 1 documentation. That's odd, I see a package at https://www.npmjs.com/package/apollo-server-azure-functions at version 1.4.0. `npm show apollo-server-azure-functions versions` appears to agree. If you run into more issues, please feel free to open another issue

**Comment by simonaco** [comment]
thanks @evans! on the npm package page if you try to navigate to the repository it will take you to this link https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-azure-functions which returns a 404.

**Comment by eric-kimbrel** [comment]
Agreed,   if you look at https://github.com/apollographql/apollo-server/tree/master/packages there is no package for azure functions.  Is it on another branch or just didn't get committed?
