### ISSUE TITLE
Response inspection in after-middleware

### ISSUE THREAD

**Issue by davewasmer** [apollographql/apollo-server#1139]
I'm trying to add some Koa middleware that inspects the result of the GraphQL query and performs some work based on what it finds.

The way I'm doing this is via a middleware roughly like this:

```js
async function(ctx, next) {
  await next();
  checkResult(ctx);
}
```

The problem I'm encountering is that by the time my `checkResult` method runs, apollo has _already_ stringified the response object. This means that, in order to inspect the result, I need to re-parse the JSON string that was just generated and inspect the structure. This stringify + reparse step is obviously not ideal.

Is there any way to extract the actual result object (not the JSON string) from the Koa context or response object? If not, is that something worth a PR?

**Comment by eugene1g** [comment]
Looks like the core method responsible for the query (`runHttpQuery`) - is narrowly defined to return JSON'fied strings https://github.com/apollographql/apollo-server/blob/version-2/packages/apollo-server-core/src/runHttpQuery.ts

Maybe there is a way to capture errors with a custom extension in V2 already (/cc @glasser who's working on this)

**Comment by davewasmer** [comment]
Sorry, I edited the title to reflect my broader goal here. While my specific use case in the moment is error handling, I think there's plenty of valid use cases, even on successful requests, to be able inspect the result in a later-stage middleware.

Off the top of my head, I think `runHttpQuery` should be modified to return the actual object, and then the framework shim (i.e. `apollo-koa-server`) could invoke a method to serialize (i.e. `options.serializeResponse(ctx, result)`), which by default would just `JSON.stringify` but users could override.

This would allow me to override the `serializeResponse(ctx, result)` to do the same `JSON.stringify` but also to save a copy of the `result` onto the `ctx` object.

**Comment by glasser** [comment]
The new version of graphql-extensions will have a willSendResponse hook which will let you access the unserialized response in a web framework agnostic way. I hope this can serve that goal?

**Comment by glasser** [comment]
There's also the pre-existing formatResponse hook, which we're not planning to break.

**Comment by davewasmer** [comment]
@glasser I think the only potential problem is that for this to work, I need access to the web framework's request-level scope (in Koa terms, I need Koa's `ctx` object for that request) so I can save off a copy of the query result for later inspection.

The docs on `formatResponse` are pretty sparse, but after looking through the source code, I suppose I could do something like this?

```js
route.post(graphqlKoa((koaContext) => {
  return {
    schema,
	formatResponse(result, options) {
      options.context.koaContext.mySavedCopyOfResult = result;
    },
    context: { koaContext }
  };
}));
```

I hadn't realized that there was a second argument to `formatResponse`. It's a little convoluted, but if that works, I think it'll cover my use case. I'll give it a shot.

**Comment by davewasmer** [comment]
FWIW, I'd still argue that the core library shouldn't be doing the `JSON.stringify` - I don't need it personally right now, but moving `JSON.stringify` to the framework shims and allowing it to be overridden would allow things like streaming JSON stringifiers.

**Comment by glasser** [comment]
I'm not sure if options.koaContext is what you want, but in your example there you can also just refer directly to the closed-over `koaContext`.

**Comment by davewasmer** [comment]
🤦‍♂️ derp. The coffee must not be kicking in today ...

**Comment by davewasmer** [comment]
That seems to do the trick - closing this since there's an existing solution
