### ISSUE TITLE
Network error: Network request failed with status 200 - "OK"

### ISSUE THREAD

**Issue by hereisjai** [apollographql/apollo-server#1154]
![graphql error](https://user-images.githubusercontent.com/24327854/41151721-3cde213a-6b2f-11e8-9b8a-10e7616f8865.png)

I get this error when connecting to graphQl server which is hosted at "https://graphqlserver-graphqlserver.a3c1.starter-us-west-1.openshiftapps.com/graphiql"

the code for the Server is in here  "https://github.com/hereisjai/graphqlserver"

My client app is hosted in here  "https://graphql-5c6b1.firebaseapp.com/ "

And this is how i try to connect to my server 

import { ApolloClient, createNetworkInterface } from 'apollo-client';

// Polyfill fetch
import 'whatwg-fetch';

const networkInterface = createNetworkInterface('https://graphqlserver-graphqlserver.a3c1.starter-us-west-1.openshiftapps.com/graphiql');

export const client = new ApolloClient({ networkInterface });

**Comment by evans** [comment]
It appears that the network interface code uses the graphiql endpoint as opposed to the graphql endpoint. Apollo Server 2 avoids this confusion by making them the same and returning one over the other depending on which you use. I would recommend upgrading to the latest rc `npm install apollo-server@rc`. 

Also if you use Apollo 2, you'll be able to use Apollo Link, which has a firebase adapter https://github.com/Canner/apollo-link-firebase
