### ISSUE TITLE
How to set up HTTPS with ApolloServer 2?

### ISSUE THREAD

**Issue by johnreynoldsventure** [apollographql/apollo-server#1155]
I'm probably missing something very obvious, but I cannot figure out how to configure HTTPS with ApolloServer…

With vanilla express, I do the following:
var https_options = {
    key: key,
    cert: cert
};
server = https.createServer(https_options, app).listen(PORT, HOST);

With ApolloServer, I don't seem to have the 
option to configure the key and cert:

const app = express()
const server = new ApolloServer({ typeDefs, resolvers })
registerServer({ server, app })
server.listen().then(({ url }) => {
  console.log(`🚀  Server ready at ${url}`)
})

**Comment by johnreynoldsventure** [comment]
I tried this, and it "appears" to work, but I'd like a sanity check if possible:

const app = express()
const server = new ApolloServer({ typeDefs, resolvers })
registerServer({ server, app })
// This is just a test to see if I create the HTTPS server for the app,
// will it magically work?
https.createServer(
  {
    key: fs.readFileSync('server.key'),
    cert: fs.readFileSync('server.cert')
  }, app).listen(443)
console.log('Server might be ready at 443')

**Comment by evans** [comment]
That works great! `registerServer` is really just an applyMiddleware call that sets up the middlewares and then you're able to call `app.listen` instead of `server.listen`. Currently it's not documented completely, so I'll leave this open for now

**Comment by johnreynoldsventure** [comment]
Thanks Evan... now I'm off to setting up the Subscription Server. I'll open another issue for that.

It's clear that Server 2.0 is a huge improvement. Thanks for all you do.

**Comment by evans** [comment]
It's now documented and in the latest release!

In the beta.11, we moved to an `applyMiddleware` architecture, so the new flow looks something like: https://www.apollographql.com/docs/apollo-server/v2/essentials/server.html#middleware

Subscriptions are now created in this manner: https://glitch.com/edit/#!/mountainous-suggestion?path=index.js:49:0

**Comment by jlubeck** [comment]
When trying to follow the latest docs, I'm getting this error: 

`Error: To use Apollo Server with an existing express application, please use apollo-server-express`

I believe this ticket should be reopened as there is no documentation on how to enable HTTPS on an ApolloServer

**Comment by jamiehill** [comment]
I thought one of the matras of AP2, is that it dramatically simplifies necessary dependencies and configuration? `https` should be added as a config param, imo.  As setting the server up for something as fundamental as this requires additional dependencies and additional configuration.

**Comment by jamiehill** [comment]
Ahh, have just noticed, that you need to use `apollo-server-express` NOT `apollo-server`!!!  So we're saying `apollo-server` basically doesn't support `ssl`?  I think this is a massive ommission

**Comment by smolinari** [comment]
Apollo server (apollo-server) itself uses apollo-server-express. And as such, it support SSL/TLS. 

https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server/package.json

https://www.apollographql.com/docs/apollo-server/essentials/server.html#ssl

Scott

**Comment by bionicles** [comment]
@smolinari how do you set this up?

**Comment by ranjan-purbey** [comment]
@bionicles You can follow the example here: https://www.apollographql.com/docs/apollo-server/security/terminating-ssl/ to setup an apollo server over HTTPS. However it uses `apollo-server-express` instead of `apollo-server`.

**Comment by RoelRoel** [comment]
I want to run apollo via https locally to use cookies with Secure attribute or SameSite attribute set to None.
When I change my code to the example given in https://www.apollographql.com/docs/apollo-server/security/terminating-ssl/ it does not work. It still only runs in http.
Aren't we suppost to do something with the httpServer object?

**Comment by RoelRoel** [comment]
I have fixed it! I do have to use server.listen instead of app.listen. The v2 example seems to be incorrect. In case of production I now still use app.listen. (server is the https.createServer response)

**Comment by MertHaddad** [comment]
Source : https://www.apollographql.com/docs/apollo-server/security/terminating-ssl/
this might help :

```
import { ApolloServer } from '@apollo/server';
import { expressMiddleware } from '@apollo/server/express4';

import typeDefs from './graphql/schema';
import resolvers from './graphql/resolvers';
import cors from 'cors';
import bodyParser from 'body-parser';
import express from 'express';
import http from 'http';
import https from 'https';
import fs from 'fs';

const configurations = {
  // Note: You may need sudo to run on port 443
  production: { ssl: true, port: 443, hostname: 'example.com' },
  development: { ssl: false, port: 4000, hostname: 'localhost' },
};

const environment = process.env.NODE_ENV || 'production';
const config = configurations[environment];

const server = new ApolloServer({
  typeDefs,
  resolvers,
});
await server.start();

const app = express();
// our express server is mounted at /graphql
app.use('/graphql', cors(), bodyParser.json(), expressMiddleware(server));

// Create the HTTPS or HTTP server, per configuration
let httpServer;
if (config.ssl) {
  // Assumes certificates are in a .ssl folder off of the package root.
  // Make sure these files are secured.
  httpServer = https.createServer(
    {
      key: fs.readFileSync(`./ssl/${environment}/server.key`),
      cert: fs.readFileSync(`./ssl/${environment}/server.crt`),
    },

    app,
  );
} else {
  httpServer = http.createServer(app);
}

await new Promise((resolve) => httpServer.listen({ port: config.port }, resolve));

console.log('🚀 Server ready at', `http${config.ssl ? 's' : ''}://${config.hostname}:${config.port}/graphql`);
```
