### ISSUE TITLE
new ApolloServer not working in 2.0.0-beta.5

### ISSUE THREAD

**Issue by fizan2904** [apollographql/apollo-server#1162]
<img width="762" alt="screen shot 2018-06-12 at 2 50 34 pm" src="https://user-images.githubusercontent.com/10195552/41281802-008d8fe4-6e50-11e8-94bc-955c8a09a39e.png">

**Comment by ostrgard** [comment]
To reproduce, follow these steps: https://www.apollographql.com/docs/apollo-server/v2/essentials/server.html.

**Comment by bdvllrs** [comment]
Installing version `2.0.0-beta.7` solved it for me.
```
npm install apollo-server@2.0.0-beta.7
```

**Comment by Ken123777** [comment]
@bdvllrs Thanks 😃

**Comment by fizan2904** [comment]
@bdvllrs Thanks 😃
