### ISSUE TITLE
dist-tags for latest in NPM is registered as a beta 

### ISSUE THREAD

**Issue by appsolutegeek** [apollographql/apollo-server#1168]
Hi,

The dist-tags pushed to npm for LATEST are registered as a beta, is this correct ? 

```
npm view apollo-server-express dist-tags

{ latest: '2.0.0-beta.7',
  tracing: '1.0.3-tracing.3',
  next: '1.3.5',
  beta: '2.0.0-beta.8' }
```

Surely the latest should be the latest stable ?

When I update my packages with https://github.com/tjunnone/npm-check-updates , it pulls in the latest tag which happens to be @beta 

Thanks in advance

**Comment by abernix** [comment]
Definitely a mistake and it should be fixed now.  Thanks for raising the flag!
