### ISSUE TITLE
2.0 as middleware with Meteor WebApp

### ISSUE THREAD

**Issue by mattblackdev** [apollographql/apollo-server#1172]
I'm having trouble using the middleware option to integrate with Meteor's WebApp.

The below is my attempt and I don't get any server errors... but I also don't get any playground at ```localhost:3000/graphql```. Pointing the macOS GraphiQL app at it gets a "couldn't communicate with the GraphQL server" error.

```
meteor create --minimal --release 1.7.0.1 meteor-apollo-2
cd meteor-apollo-2
meteor npm i apollo-server@beta apollo-server-express@beta graphql graphql-tag
```

```/server/main.js```
```
import { Meteor } from "meteor/meteor";
import { WebApp } from 'meteor/webapp'

import { ApolloServer } from 'apollo-server'
import { gql, registerServer } from 'apollo-server-express'

// The GraphQL schema
const typeDefs = gql`
  type Query {
    "A simple type for getting started!"
    hello: String
  }
`;

// A map of functions which return data for the schema.
const resolvers = {
  Query: {
    hello: () => 'world'
  }
};

Meteor.startup(() => {
  const server = new ApolloServer({
    // These will be defined for both new or existing servers
    typeDefs,
    resolvers,
  });
  
  registerServer({ server, app: WebApp.connectApp }) // <- Is this right?
});
```

I tried to debug and follow the rabbit hole but damn that config is confusing!!
```ApolloServer.ts```
```
export const registerServer = async ({
...
/* line 123 */ server.use({
    path,
    getHttp: () => createServer(app),
  });
...
```
I see this ```createServer``` is coming from the 'http' package. And I'm passing it Meteor's WebApp.connectApp. So I feel like this could be the issue since it's not an express app but a connect app. However, I don't get any errors and not sure how to debug any further. So.. I'm stumped.

Thanks in advance for any advice.
--Matt

**Comment by evans** [comment]
Internally, our diff looked like this. You'll also want to upgrade to the latest release, so `npm install apollo-server-express@rc`. Unfortunately, I'm not sure the difference between connectHandlers and connectApp. With the apollo-server-express rc, you can import the `ApolloServer` class without the dependency on apollo-sever

```js
+    // cors is currently open to all
+    server.applyMiddleware({
+      app: WebApp.connectHandlers,
+      server,
+      path: endpointPath
+    });
```

**Comment by evans** [comment]
Since ^ worked with a Meteor app, I'm going to close the issue

**Comment by evans** [comment]
@mattblackdev That would be a great addition. https://github.com/apollographql/apollo-server/tree/version-2/packages/apollo-server-express#connect is probably the right place

**Comment by mattblackdev** [comment]
I’ve seen that before. It also happens with yoga. I think it is coming from the playground?

Thanks,
Matthew

**Comment by theodorDiaconu** [comment]
Weird stuff, this seems to work without graphql-server-express. Works with:

```import { ApolloServer } from 'apollo-server';``` too

**Comment by theodorDiaconu** [comment]
So... even if we get that error on `GET /graphql`. The GraphQL works flawlessly and I get the full playground. There is no other issue with it, I think Playground sends headers when other middlewares are there. I think this is related to the way GRaphQL playground sets headers. @evans help please!

**Comment by theodorDiaconu** [comment]
This is not an issue of apollo-server. It's an issue of Meteor, going to tackle it there.

**Comment by evans** [comment]
@theodorDiaconu I think the best course of action PR a fix for or comment on https://github.com/prismagraphql/graphql-playground/issues/752 or https://github.com/prismagraphql/graphql-playground/issues/557, since the validateHeaders error is a playground issue.
