### ISSUE TITLE
Subscription field must return Async Iterable. Received: undefined

### ISSUE THREAD

**Issue by johnreynoldsventure** [apollographql/apollo-server#1176]
Using Apollo Server 2-beta, I am unable to get Subscriptions working.
When I start my Client, the <Subscription> component renders and I get this message from the ApolloLink error handler:
[Network error]: {"message":"Subscription field must return Async Iterable. Received: undefined"}
On the Server I never see the debugging messages that I inserted in the Subscription.

Google locates similar issues from Apollo Server 1 that are fixed by server setups that no longer seem to apply - I'd appreciate any pointers.

==============================================================

On the server I have defined my subscription resolver:
```
Subscription: {
      bookAdded: {
        subscribe: withFilter(
          () => { 
            console.log('REGISTER TOPIC bookAdded')  // eslint-disable-line no-console
            return pubsub.asyncIterator('bookAdded') 
          },
          (payload, variables) => {
            console.log(`Check if filter satisfied ${payload} ${variables}`) // eslint-disable-line no-console
            return true
          }
        )}},
```

On the client, I am using the <Subscription> component:
```
const BOOKS_SUBSCRIPTION = gql`
  subscription onBookAdded($filter: String!) {
    bookAdded(filter: $filter) {
      title
      author
    }
  }
`

const BookAddedSubscription = ({ filter }) => (
  <Subscription
    subscription={BOOKS_SUBSCRIPTION}
    variables={{ filter }}
    shouldResubscribe={true}
  >
    {({ data, loading, error }) => {
      return(
        <div>
          { data && (
            <h4>Data:</h4>
          )}
          { loading && (
            <h4>Loading:</h4>
          )}
          { data && (
            <h4>Error:</h4>
          )}
        </div>
      )
    }
    }
  </Subscription>
)
```

**Comment by evans** [comment]
@johnreynoldsventure Can you point me towards the solutions you found for apollo server 1? What sorts of changes do you have to make?

For now something like https://glitch.com/edit/#!/import/github/evans/as2-express-sandbox should work

**Comment by johnreynoldsventure** [comment]
As almost always happens when I open and issue, it's entirely due to "pilot error" on my part...
The **schema** that I was passing (created by makeExecutableSchema) in the following was _not_ the same as what I passed to ApolloServer. Here is the working code:

`const app = express()
const schema = makeExecutableSchema({typeDefs, resolvers})
const server = new ApolloServer({ schema })
registerServer({ server, app })

// Set up https and wss (secure web socket) support to ApolloServer 2
const PORT = 443
const ws =  createServer(
    {
      key: readFileSync('server.key'),
      cert: readFileSync('server.cert')
    }, app)

ws.listen(PORT, () => {
  console.log(`Apollo Server is now running on http://localhost:${PORT}`)
  // Set up the WebSocket for handling GraphQL subscriptions
  new SubscriptionServer({
    execute,
    subscribe,
    schema
  }, {
    server: ws,
    path: '/subscriptions',
  })
})
`
