### ISSUE TITLE
Unable to install latest version of apollo-server

### ISSUE THREAD

**Issue by matthall88** [apollographql/apollo-server#1177]
Unable to run npm install apollo-server@beta successfully

npm i apollo-server@beta
npm ERR! code ETARGET
npm ERR! notarget No matching version found for apollo-server-express@^2.0.0-beta.11
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'apollo-server'
npm ERR! notarget

**Comment by evans** [comment]
Odd, maybe npm had to catch up. I was able to install it locally and on glitch. Check out https://glitch.com/edit/#!/apollo-launchpad?path=package.json:10:0

**Comment by evans** [comment]
I may have closed this prematurely, so if you @matthall88 are still running into the issue, please let me know

**Comment by matthall88** [comment]
@evans seems you were right about npm, works this morning!
