### ISSUE TITLE
Return only Error instead of partial response and Error

### ISSUE THREAD

**Issue by yogesh-kamble** [apollographql/apollo-server#1200]
In my application if field throw the error then I want to return only error to Client and Ignore the partial data. (Basically once User login successful then we are adding one more field in the response through extend Type, but if resolver for that field throw error then just want to return the error and server should not send the partial data of user. is it possible to achieve this ?)

**Comment by evans** [comment]
Totally! You can strip them out in `formatResponse`, which is an argument to `ApolloServer` in v2 and the middleware in v1.
