### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by batarian71** [apollographql/apollo-server#1215]
Hello. I am a graphic designer. I want to volunteer support for open source projects. If you want, I can design a logo for you. What do you say? Also tell me if you want something. I can design.

**Comment by batarian71** [comment]
I sent pr.

**Comment by evans** [comment]
@batarian71 That would be incredible! @itsjessmarina is our designer and definitely has some ideas. Does anything in particular stand out to you that warrants a logo? If you have any initial thought, we'd love to hear them

**Comment by itsjessmarina** [comment]
@batarian71 Thanks so much for your generous offer! To echo @evans, if you have anything in particular in mind that you'd like to work on, let us know. I can send you our brand palette and specs. If you have any interest in designing diagrams, and come across any flows or functions that would lend themselves to a diagram, that's something that would be very helpful for our users. Thanks again and let us know!

**Comment by batarian71** [comment]
Would you like me to be a contributor?

**Comment by batarian71** [comment]
I changed the color of the first design. I made a design like you said. Which one did you like? I will send pr.


![sss](https://user-images.githubusercontent.com/36008612/41808943-2b109620-76ee-11e8-8e30-85ba37704083.jpg)

**Comment by evans** [comment]
@batarian71 Yeah a pull request would be awesome. A logo for Apollo Server or Apollo Client is a great place to start! You can see our current imagery https://www.apollographql.com/docs/apollo-server/v2/. @itsjessmarina is it possible zip up our brand palette/specs and attach it to another comment?

Or if you would like to digram the flow of a request through a CDN, which is detailed in [this section](https://www.apollographql.com/docs/apollo-server/v2/features/cdn.html), that would be extremely helpful.

**Comment by batarian71** [comment]
I sent pr but I think there was a setback.

**Comment by hwillson** [comment]
Thanks for your interest in helping out @batarian71. At this point, we're working on a more cohesive and integrated design approach that will encompass all of our projects. The design direction your headed in (and as natural outcome of monetizing that work via [steemit](https://steemit.com/@batarian71/) / [Utopian.io](https://join.utopian.io)) isn't likely to align with our design vision. Thanks again!
