### ISSUE TITLE
Documentation for apollo-server-express@2.0.0-rc.0 is wrong

### ISSUE THREAD

**Issue by tpetry** [apollographql/apollo-server#1216]
The documentation for apollo-server-express@2.0.0-rc.0 is wrong as it's not possible to create a server because both (different) documentations are incorrect:
* [apollo-server README.md](https://github.com/apollographql/apollo-server/blob/v2.0.0-rc.0/README.md): The functions `graphqlExpress` and `graphiqlExpress`are no longer exported from `apollo-server-express`
* [apollo-server-express README.md](https://github.com/apollographql/apollo-server/blob/v2.0.0-rc.0/packages/apollo-server-express/README.md): The function `registerServer` is throwing an error that `server.applyMiddleware` should be used. But this message can only be found when digging into the source because it's declared with zero parameters preventing compilation.

**Comment by unicodeveloper** [comment]
@tpetry The README files are yet to be updated to the latest versions. Please check the updated documentation for [apollo-server and apollo-server-express here.](https://www.apollographql.com/docs/apollo-server/v2/essentials/server.html).

Please rely on the [documentation site](https://www.apollographql.com/docs) for any functionality you need from these tools. I'll work on getting the READMEs updated to the latest version.

**Comment by evans** [comment]
@tpetry Thank you for letting us know! We're removing the `registerServer` function in this release and will add it to the documentation. It was just in there for people upgrading from the beta.

**Comment by evans** [comment]
We've fixed the readme's and they will be out for the next release. @tpetry if you find any additional documentation issues, please feel free to open more issues
