### ISSUE TITLE
Apollo Server 2: Return an array from Data Sources

### ISSUE THREAD

**Issue by evans** [apollographql/apollo-server#1218]
Data sources should accept an array returned from the rest backend without having to call JSON.parse. Here is a reproduction: https://glitch.com/edit/#!/as2-subscriptions-datasources?path=index.js:44:6

**Comment by martijnwalraven** [comment]
It seems the response from the REST endpoint is served as `Content-Type: text/plain`, so that explains why it isn't parsed.
