### ISSUE TITLE
Apollo Server 2: Data Sources baseUrl's end gets stripped

### ISSUE THREAD

**Issue by evans** [apollographql/apollo-server#1219]
It seems like the `baseUrl` is not used on properly. In the following example we have set the `baseUrl` to `localhost:5000/api` and the data source's get request pull from `people`. 

The rest server as data at `localhost:5000/people` and works, but when we move the endpoint to `localhost:5000/api/people`, it fails

`baseUrl`: https://glitch.com/edit/#!/as2-subscriptions-datasources?path=datasource.js:8:36
`api`: https://glitch.com/edit/#!/as2-subscriptions-datasources?path=rest-server.js:5:0
`get` call: https://glitch.com/edit/#!/as2-subscriptions-datasources?path=datasource.js:12:21

**Comment by martijnwalraven** [comment]
Ah, that's definitely a gotcha we should mention! It's how relative URLs work though. The `baseURL` should be set to `http://localhost:5000/api/` (note the trailing slash).

**Comment by martijnwalraven** [comment]
This has been addressed in https://github.com/apollographql/apollo-server/commit/4d7a34f6f57ac3517732a23e436638050fe8d421.
