### ISSUE TITLE
Missing apollo-upload-server dependency

### ISSUE THREAD

**Issue by olistic** [apollographql/apollo-server#1220]
**Intended outcome:**

`apollo-server-lambda@rc` can be used.

**Actual outcome:**

Failure due to missing `apollo-upload-server` dependency. Actual error is: `"Cannot find module 'apollo-upload-server'"`. **I see that `apollo-upload-server` is referenced by `apollo-server-core` [here](https://github.com/apollographql/apollo-server/blob/742fb41bc37294717cd0a9a52f2cf5658abdba7e/packages/apollo-server-core/src/ApolloServer.ts#L17), but it's not included in the core's [dependencies](https://github.com/apollographql/apollo-server/blob/742fb41bc37294717cd0a9a52f2cf5658abdba7e/packages/apollo-server-core/package.json#L51-L69). Could that be the issue?** 

Adding `apollo-upload-server` to the dependencies of `apollo-server-core` should fix this issue. Let me know if you agree, and I'll be happy to submit a PR.

**More info:**

* Node version: v8.10.
* Using `serverless` framework.
* `graphql`'s lambda handler:

```js
const { ApolloServer } = require('apollo-server-lambda');

const resolvers = require('./data/resolvers');
const typeDefs = require('./data/typeDefs');

const server = new ApolloServer({
  typeDefs,
  resolvers,
});

exports.handler = server.createHandler();
```

**Comment by evans** [comment]
Thank you published in rc.2!
