### ISSUE TITLE
Apollo Server 2: Is graphql dependency needed in integrations?

### ISSUE THREAD

**Issue by olistic** [apollographql/apollo-server#1225]
After installing `apollo-server-lambda`, I saw warnings about a missing peer dependency: `graphql`. I haven’t seen anywhere in the `apollo-server-lambda` docs that `graphql` needs to be installed along with it, so I took a look at the code. **I see that `apollo-server-core` has `graphql` In its [peer dependencies](https://github.com/apollographql/apollo-server/blob/ebacd8fcda15c10bc4b950e894ad1815577fc072/packages/apollo-server-core/package.json#L65), but none of the apollo server variants that depend on the core (express, hapi, lambda, etc.) install `graphql` along with it. Should `graphql` be a dependency of `apollo-server-<variant>`? Or should it be installed by the end user, along with `apollo-server-<variant>`?** (If it’s the latter, then maybe `graphql` should be a peer dependency of the variant packages, as it's the case for `apollo-server`).

Thanks, and please accept my apologies if I missed something!

**Comment by evans** [comment]
@olistic Absolutely, graphql needs to be installed next to all the `apollo-server-<integration>`. We'll add them straight away. 

Thank you so much for reporting the issue!

**Comment by evans** [comment]
Thanks to #1232, #1244, and 84f13ba this can be closed. Thank you so much @olistic!
