### ISSUE TITLE
Apollo Server 2: Throwing from context function returns 400 for GraphQL errors

### ISSUE THREAD

**Issue by olistic** [apollographql/apollo-server#1231]
I'm doing JWT validation when constructing the context, and I'd like to be able to throw an `AuthenticationError` if the token is expired, for example, to be able to re-authenticate from the client. However, throwing this (and any other kind of error) from within the context function results in a 500 error:

```js
const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: ({ event }) => {
    throw new AuthenticationError();
  },
});
```

```json
{
  "error": "Response not successful: Received status code 500"
}
```

Is there a better way of achieving what I'm trying to achieve? Should the context resolution be modified not to mask errors?

**Comment by evans** [comment]
@olistic Throwing in your context method works great! The response body has a GraphQL result that contains the AuthenticationError. Currently Playground doesn't show it, so you'll have to take a look at the network tab. If you [open an issue on Playground](https://github.com/prismagraphql/graphql-playground/issues/new), we should be able to get it fixed

**Comment by evans** [comment]
I'm going to close this for now. prismagraphql/graphql-playground#652 is the relevant issue

**Comment by evans** [comment]
Though the actionable portion of this is to have the error code be a 400 when a GraphQL error is thrown from the context creation function.

**Comment by evans** [comment]
This is now in RC.6, the issue of displaying in Playground will have to be resolved in that repository

Thank you for raising the concern!

**Comment by briosheje** [comment]
For anyone wondering whether you can handle an error from the context, you can do that.

I've found the answer by looking at this: https://github.com/graphql/graphql-js/blob/main/src/error/GraphQLError.ts#L66-L74

If you need to throw an error and you are using, for example, `formatError`, you can combine those together like this:

```js
// in the context, assuming ApplicationError is a custom class defined by you.
throw new GraphQLError('', void 0, void 0, void 0, void 0, new ApplicationError('ERR_INVALID_TOKEN'));
```

```js
   formatError: (err) => {
        if (err.originalError instanceof ApplicationError) {
          const applicationError = err.originalError as ApplicationError;
          return {
            code: applicationError.code,
            message: applicationError.message
          }
        }

        return err;
      }
```
