### ISSUE TITLE
Apollo Datasource Rest: Allow Default Request Params

### ISSUE THREAD

**Issue by Saeris** [apollographql/apollo-server#1238]
I couldn't figure out a way to do this with the existing setup. Basically, the REST API I'm trying to wrap with `apollo-datasource-rest` requires all requests to have a query string parameter for the API key in every request, ie: `http://www.someapi.com/v1/endpoint?api_key=123xyz&${<insert other params here>}`. The API I'm working with doesn't allow me to set the API key as a header value, and I imagine other people will run into this problem working with older APIs they have no control over.

Right now in order to do that, I'd need to pass `api_key` as a property of every call to `this.get()` (or any of the similar methods). This is unnecessarily repeated code, so what I'd like to have is a property I can set similar to `baseURL` called `defaultParams` which will be used in `RESTDataSouce.fetch()`. Example:

[line 99 in RESTDataSource.ts:](https://github.com/apollographql/apollo-server/blob/acedc2690bbd2731d47b834aedd4ada7cc10638e/packages/apollo-datasource-rest/src/RESTDataSource.ts#L99)
```typescript
if (this.defaultParams || params) {
      // Append params to existing params in the path
      for (const [name, value] of new URLSearchParams(Object.Assign(this.defaultParams || {}, params))) {
        url.searchParams.append(name, value);
      }
    }
```

This way users can set default query string parameters to be sent along with every request in one place and they can still be overridden on a per-endpoint basis.

**Comment by martijnwalraven** [comment]
@Saeris I experimented some and came up with https://github.com/apollographql/apollo-server/commit/2e6073dc52c15f181662b7e4bf6408d8272a3755#diff-94c74c4c5e5f1e69b942b0b56a962852R195.

It gives you access to the request options (if you only want to add params for GET requests for example), and it also allows you to resolve the params asynchronously. I added this because it was suggested for `baseURL` in https://github.com/apollographql/apollo-server/issues/1181. 

Not sure if it is worth the complexity, but curious what you think.

**Comment by Saeris** [comment]
I think that's going in the right direction. Left a comment where I thought there was a bug in the implementation. Basically, any params passed to `this.fetch` (or `this.get`, etc) should override any of the `defaultParams`.

Maybe a good example is say I have a default user ID I want to include in every request, but on a case-by-case basis I may want to use a different user ID (perhaps passed as an argument to a query). That would be more common I think than changing up an API key.

**Comment by abernix** [comment]
@Saeris Are you satisfied with the result of #1277, at least in terms of the original request?  If so, please close this issue!

**Comment by Saeris** [comment]
Yeah that PR solved my issue! Thanks!
