### ISSUE TITLE
Enabling Apollo-Server Extension options overwrite remote executable schema extensions.

### ISSUE THREAD

**Issue by hollsteinm** [apollographql/apollo-server#1253]
# Issue

apollo-server-core overwrites remote schema extensions returned. There is no way to configure a custom extensions array as the culprit is a locally scoped array in the `doRunQuery` function.

# Reproduce

To reproduce, create a simple apollo graphql server. While this was found in express, it is in the core package so may be reproducible as other server middleware. Then create another server with a simple query that returns an extension in the graphql response. Add the second server as a remote query endpoint to the first graphql server. This could be done similar to how stitching is done. Finally, on the first apollo graphql server, enable any of the tracing or cacheControl extensions in the options. Run a graphql query against the stitching graphql service. Observe that any extensions returned by the stitched or remote graphql server are not returned. Now, disable the tracing or cacheControl extensions. View similar results.

The offending line seems to be found here:

https://github.com/apollographql/apollo-server/blob/c51d4c7af0e2c7c191ceaa950481cfb5b65e5e75/packages/apollo-server-core/src/runQuery.ts#L221

https://github.com/apollographql/apollo-server/blob/c51d4c7af0e2c7c191ceaa950481cfb5b65e5e75/packages/apollo-server-core/src/runQuery.ts#L207

# Resolution

The resolution would be that all possible returned properties of a graphql response are returned by the implementation. Another possible solution is the allow a user defined list of extension interface implementations in the options object.

The reason this is reported as a bug as opposed to a simple PR is to discuss the two options outlined above.

**Comment by hollsteinm** [comment]
The use case is returning schema version information or performance metrics from the remote schema service. The later is mostly used for at-a-glance debugging of any performance issues. With the examples, I am curious how multiple remote schemas in a stitched service will handle collisions if just object spreading is used.

**Comment by jbaxleyiii** [comment]
@hollsteinm this is definitely a problem with the `mergeSchema` method of doing stitching. Merging of extensions is on the roadmap for federation now that we have deprecated schema stitching. I'm going to close this issue in favor of the federation and Apollo Server 3 roadmap
