### ISSUE TITLE
HUGE querystring in GraphiQL

### ISSUE THREAD

**Issue by tlgimenes** [apollographql/apollo-server#1261]
# Issue
`resolveGraphiQLString` from `apollo-server-module-graphiql` automatically populates the browser's querystring with the typed graphql query. This is really good for rapidly sharing queries, but sets a limit to its size. 

# Possible solution
Expose `onEditQuery/onEditVariables` so one could programmatically choose the intended behavior for its use case

**Comment by evans** [comment]
@tlgimenes Right now we're moving to GraphQL Playground for AS2, which enables you to share without modifying the url. Do you feel that there needs to be more functionality?

**Comment by tlgimenes** [comment]
Cool ! No, I've just had this issue where I had to send a huge query through GraphiQL and my browser couldn't handle the url. Thanks !

**Comment by evans** [comment]
@tlgimenes Sweet! I'm going to close this for now, since Playground will solve the issue
