### ISSUE TITLE
Merge two REST API into one type

### ISSUE THREAD

**Issue by linonetwo** [apollographql/apollo-server#1268]
I have a type that its data comes from two different REST APIs:

```graphql
type GlobalStatus {
  # These comes from API 1
  maxBlockNetUsage: Int
  targetBlockNetUsagePct: Int
  maxTransactionNetUsage: Int
  basePerTransactionNetUsage: Int
  netUsageLeeway: Int
  contextFreeDiscountNetUsageNum: Int
  contextFreeDiscountNetUsageDen: Int
  maxBlockCpuUsage: Int
  targetBlockCpuUsagePct: Int
  maxTransactionCpuUsage: Int
  minTransactionCpuUsage: Int
  maxTransactionLifetime: Int
  deferredTrxExpirationWindow: Int
  maxTransactionDelay: Int
  maxInlineActionSize: Int
  maxInlineActionDepth: Int
  maxAuthorityDepth: Int
  maxRamSize: Int
  totalRamBytesReserved: Int
  totalRamStake: Int
  lastProducerScheduleUpdate: String
  lastPervoteBucketFill: String
  pervoteBucket: Int
  perblockBucket: Int
  totalUnpaidBlocks: Int
  totalActivatedStake: Int
  threshActivatedStakeTime: String
  lastProducerScheduleSize: Int
  totalProducerVoteWeight: Float
  lastNameClose: String

  # And these comes from API 2
  blockNumber: Int
  transactionNumber: Int
  accountNumber: Int
  actionNumber: Int
}
```

I'm getting two APIs' data so no fields will be null:
```js
status() {
    return Promise.all([
      get('/api1'),
      get('/api2'),
    ]).then(([dataapi1, dataapi2]) => ({ ...dataapi1, ...dataapi2 }));
  },
```

But how can I only `get('/api2)` if a user only query blockNumber,  transactionNumber, accountNumber, and actionNumber?

I know using `apollo-datasource-rest` is a way, but that requires calling it in every GlobalStatus's fields, and there are so many fields in api1.

**Comment by evans** [comment]
@linonetwo You could use the info parameter to your resolvers, which contains information about the schema and the incoming query.

```js
{
  Query: {
    hello: (_p, _a, _c, info) => {
      console.log(
        info.operation.selectionSet.selections.map(
          selection => selection.name.value,
        ),
      );
      ...
    }
  }
}
```

The above prints out [ hello ].

Depending on where you are in your resolver map, the selection set might be nested. It's definitely a non-ideal api, since the info object isn't currently documented and really a whole lot of implementation details from graphql.js

**Comment by linonetwo** [comment]
Yeah, but traverse AST in every Type that is composed of several REST API...I think that is a tough job. Hoping there can be a declarative way!

**Comment by abernix** [comment]
Hopefully this is greatly improved through a combination of `RESTDataSources` and [Apollo Federation](https://www.apollographql.com/docs/apollo-server/federation/introduction/)!
