### ISSUE TITLE
Passthrough of options to graphql playground disabled

### ISSUE THREAD

**Issue by ashtonsix** [apollographql/apollo-server#1290]
This commit [https://github.com/apollographql/apollo-server/commit/84233d2010af673dc3d54f0f322c9bf0a660b6e5](https://github.com/apollographql/apollo-server/commit/84233d2010af673dc3d54f0f322c9bf0a660b6e5) broke my code, so I'm staying at `rc.5` until fixed:

```js
const graphqlConfigPath = path.resolve(__dirname, '../.graphqlconfig')
const graphqlConfig = JSON.parse(fs.readFileSync(graphqlConfigPath, 'utf8'))
server.applyMiddleware({app, gui: {config: graphqlConfig}})
```

The graphql config is very important for me because it lets me work with multiple APIs & environments simulaneously.

**Comment by evans** [comment]
@ashtonsix Thank you for opening the issue! We're most likely going to place the code in #1297 inside of the `ApolloServer` constructor, so that `apollo-server` can update them. If you have any feedback, please feel free to weight in

**Comment by evans** [comment]
With #1297, we can now specify a `playground.config`
