### ISSUE TITLE
Please add Documentaion for enabling SSL with apollo Server

### ISSUE THREAD

**Issue by riginoommen** [apollographql/apollo-server#1291]

**Comment by evans** [comment]
Thank you for the issue! Can you be more specific for what you're looking for here? Https, WSS, or something else?

Does https://www.apollographql.com/docs/guides/security.html or https://www.apollographql.com/docs/guides/access-control.html provide you enough information? Or is there a logical place you would like that information?

**Comment by mcmar** [comment]
SSL (or technically TLS) would include both `https` and `wss`. Is there a parameter when calling apollo-server to add an SSL/TLS certificate and bind to 2 ports? Bind to 80 for http/ws and bind to 443 for https/wss. This would help people run apollo-server without a reverse proxy like nginx. I'm not sure how many people in the world care to even do that, but I'm pretty sure that's what he's asking.

@riginoommen I think your best bet would be to set up a reverse proxy (ie nginx) in front of the node process you're using to run apollo-server. That's probably best practice anyways. Lots of people use Docker to containerize that. Also most cloud providers will run a reverse proxy for you just by default.

**Comment by riginoommen** [comment]
@mcmar , @evans 

Hello I had enabled the SSL in a different way can you please check this gist
https://gist.githubusercontent.com/riginoommen/62cfec9459f9f2a8260d9f503ffcf7ff/raw/63dbc118121a7d96aeca1a9d78c878361a9daee9/graphql-server.ts

I need to know that does this structure support the mutations, subscriptions and querys in SSL

**Comment by zakmandhro** [comment]
Pull request submitted with documentation for SSL. Pull request: #1565 

See my solution on issue #1338.

**Comment by spyshower** [comment]
@zakmandhro dead link

**Comment by abernix** [comment]
@spyshower It lives in a more complete document now https://www.apollographql.com/docs/apollo-server/security/terminating-ssl/

**Comment by zakmandhro** [comment]
> @spyshower It lives in a more complete document now https://www.apollographql.com/docs/apollo-server/security/terminating-ssl/

Thanks for the updating link!
