### ISSUE TITLE
ApolloServer 2.0 - create custom error class

### ISSUE THREAD

**Issue by abhishek199-dhn** [apollographql/apollo-server#1304]
Hey guys, I'm using   `apollo-server@2.0.0-rc.5` and wanted to create custom error classes.

I followed `UserInputError` implementation from [`apollo-server-errors`](https://github.com/apollographql/apollo-server/blob/c2e4dfb26557e2ef5e9a7ad823e2c4edc7336c72/packages/apollo-server-errors/src/index.ts#L205-L211) package but it throws errors 
`TypeError: Class constructor ApolloError cannot be invoked without 'new' at new BadReportingFilter`

```js
// @flow

import {ApolloError} from "apollo-server";

export class BadReportingFilter extends ApolloError {
    constructor(message: string, properties?: { [key: string]: any }) {
        super(message, "BAD_REPORTING_FILTER", properties);
        Object.defineProperty(this, "name", {value: 'BadReportingFilter'});
    }
}
```

Using custom error class in this way
```js
  throw new BadReportingFilter(
        "Some error", {
              invalidArgs: Object.keys(reportFilter),
        }
    );
```

package.json - build script
```
"scripts": {
    "build-prod": "cross-env NODE_ENV=production babel src --out-dir dist --source-maps --copy-files",
  "start-prod": "cross-env NODE_ENV=production  node ./dist/app.js",
  },
 "dependencies": {
    "@types/graphql": "0.13.1",
    "apollo-engine": "1.1.2",
    "apollo-fetch": "^0.7.0",
    "apollo-link-context": "^1.0.8",
    "apollo-link-http": "1.5.4",
    "apollo-server": "2.0.0-rc.5",
    "apollo-server-express": "2.0.0-rc.5",
    ...
}
```

**Comment by evans** [comment]
It seems that Babel struggles with native implementations of classes https://github.com/babel/babel/issues/4269. Is it possible to increase your target output to es2016? That might solve the issue

**Comment by abhishek199-dhn** [comment]
thanks @evans !!
After setting `babel env target` to `node`, it seems to work.

```
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "node": "current"
        }
      }
    ],
    "stage-0",
    "flow"
  ]
  ...
}
```

**Comment by jameygleason** [comment]
@abhishek199-dhn Say you put an "errors" object on `invalidArgs`, how would you access that client side. 

I'm aiming to access errors by the unique input field.

Thanks!
