### ISSUE TITLE
Apollo Server 2.0 - How to inject objects into Resolver Context

### ISSUE THREAD

**Issue by jclarkk** [apollographql/apollo-server#1315]
Hey everyone,

Hopefully I didn't miss something in the documentation but I wasn't able to find anything regarding to resolver context injection.
There is documentation regarding how to add middleware but after I've added my user object into the request there seems no real way of adding it to the resolver context.

In Apollo Server v1 it used be this way:

app.use(
  '/graphql',
  bodyParser.json(),
  graphqlExpress(req => {
    // Some sort of auth function
    const userForThisRequest = getUserFromRequest(req);

    return {
      schema: myGraphQLSchema,
      context: {
        user: userForThisRequest,
      },
      // other options here
    };
  }),
);

However since graphqlExpress is no longer exposed in Apollo Server v2 I can't use the same method.

Any help would be greatly appreciated.
Thanks!

**Comment by kyledetella** [comment]
@jclarkk you can solve this by declaring a `context` function when you [instantiate the client](https://www.apollographql.com/docs/apollo-server/v2/api/apollo-server.html#constructor-options-lt-ApolloServer-gt).

That function will be called with the current request and you can choose what to return from there. So in your case it may look something like this:

```js
new ApolloServer({
  schema: myGraphQLSchema,
  context: ({ req }) => {
    // Look at the request to run custom user logic
   return { user:  userForThisRequest }
  },
})

**Comment by jclarkk** [comment]
@kyledetella Worked perfectly, thanks!
