### ISSUE TITLE
onDisconnect not working properly in Apollo Server 2 subscription.

### ISSUE THREAD

**Issue by DavidOnGitHub** [apollographql/apollo-server#1321]
I'm implementing subscriptions with apollo server express 2.0.0-rc.1. Following is the code:
```
const http = require('http');
const { ApolloServer } = require('apollo-server-express');
const app = require('express')();
const { makeExecutableSchema } = require('graphql-tools');
const { schema, resolver } = require('./models');
const rest = require('./rest');

const server = new ApolloServer({
  schema: makeExecutableSchema({
    typeDefs: schema,
    resolvers: resolver
  }),
  subscriptions: {
    onConnect: (connectionParams, webSocket, context) => {
      console.log('connect...');
    },
    onDisconnect: (webSocket, context) => {
      console.log('disconnect...');
    },
  },
});

app.use(require('cors')());
app.use(require('body-parser').json());
app.use('/rest', rest);
server.applyMiddleware({ app });

const httpServer = http.createServer(app);
server.installSubscriptionHandlers(httpServer);

httpServer.listen(4000, () => console.log('server ready at port 4000'));
```
I'm using the Playground tool of apollo server 2 at http://localhost:4000/graphql. When I click start (the triangle) for a subscription, it output 'connect...' which is expected, but when I click stop (the square) nothing was output while it should have output 'disconnected...'. Anyone having the same issue?

**Comment by marvinkome** [comment]
Same issues here.

**Comment by ruohki** [comment]
https://www.apollographql.com/docs/apollo-server/v2/features/subscriptions.html#Lifecycle-Events

the Client does not Disconnect when you stop a Subscription

**Comment by marvinkome** [comment]
Yeah, I realized. It actually disconnects if you reload the page or in react native, when you close the app.

**Comment by jbaxleyiii** [comment]
I realize it's been quite some time since you opened this, but if you haven't already figured this out, I'd recommend taking this question to the [Apollo Server channel within the Apollo community on Spectrum.chat](https://spectrum.chat/apollo/apollo-server) to discuss it further.  Thanks!
