### ISSUE TITLE
Apollo Server 2.0 and restify?

### ISSUE THREAD

**Issue by nanandn** [apollographql/apollo-server#1330]
Does Apollo server 2.0 work with restify? I have an existing restify app. Now I am using apollo-server-restify. I don't see any packages for restify in 2.0 or any documentation on how to use apollo server 2.0 with restify. 

Thanks
Anand

**Comment by evans** [comment]
@nanandn right now we don't have an implementation yet. If you would like to take part in the creation, please check out #1088. I'd love to see an implementation similar to #1282.

**Comment by wjsc** [comment]
I wrote a tiny module that provides support for Automatic Persisted Queries when using apollo-server-restify: 
[https://www.npmjs.com/package/apollo-server-restify-persisted-queries](url)

**Comment by nanandn** [comment]
@evans  Sorry didn't have the time to look into writing the restify middleware before. Did someone write one already? Where can I find it? If not, how do I go about writing one. I looked at the two links  you pointed to. Still a little confused about how to do it.

Should I create this in a separate github repository or put it it apollo's git hub repo?
