### ISSUE TITLE
Stitched schema removes support for file uploads

### ISSUE THREAD

**Issue by rafalp** [apollographql/apollo-server#1333]
Our services are exposing GraphQL API's implemented using python-graphene framework. In past those services talked to `Apollo-Client` directly, but we wanted to have single GraphQL endpoint for our React.js to connect.

We are using Apollo-Server 2 schema stitching feature to achieve that, but we have found that file uploads have ceased to work. Apollo Server 2 validates correctly if uploaded file was part of `multipart/form-data`, but request from Apollo Server 2 to service is always `application/json` and doesn't contain any files.

**Comment by OlivierCuyp** [comment]
@rafalp Did you put any workaround in place. I'm in a similar case ...

**Comment by jbaxleyiii** [comment]
Hey @rafalp I'm going to close this on this repo since it is an issue with `graphql-tools` and schema stitching. I'll also add it to the feature requests for federation which is the replacement for stitching going forward from us!
