### ISSUE TITLE
NPM version 2.0.0-sashko.0 gets prioritized over all RC versions

### ISSUE THREAD

**Issue by Tehnix** [apollographql/apollo-server#1340]
NPM doesn't handle `-beta`, `-rc` or similar in any special way, meaning that because `s` comes after `r` in the alphabet, `2.0.0-sashko.0` is interpreted as a newer version than `2.0.0-rc.7`, which is the latest version.

The list here https://www.npmjs.com/package/apollo-server-lambda lists the versions by date, but in NPM/Yarn it will fetch it by version number.

So, if you have a version pinning of `^2.0.0-rc.7` you will currently get `2.0.0-sashko.0` instead of the RCs.

Running `yarn upgrade apollo-server@bla` (to force the list of versions) will get you the following list,

```
❯ 2.0.0-sashko.0
  2.0.0-rc.7
  2.0.0-rc.6
  2.0.0-rc.5
  2.0.0-rc.4
  2.0.0-rc.3
  2.0.0-rc.2.1
  2.0.0-rc.2
  2.0.0-rc.1
  2.0.0-beta.9
  2.0.0-beta.8
```

**Solution:** You should probably delete `2.0.0-sashko.0` to avoid others getting their builds broken.

**Comment by evans** [comment]
@Tehnix Ah that's an unexpected behavior for sure. Thank you for pointing it out! We'll be sure to make the next release work alphabetically

**Comment by evans** [comment]
@Tehnix Thanks we've fixed this by publishing `apollo-server-lambda@2.0.0-xrc.8`
