### ISSUE TITLE
A way to pass a keepAlive timeout to graphiqlExpress

### ISSUE THREAD

**Issue by alexpovh** [apollographql/apollo-server#1341]
Currently the only supported option for `SubscriptionsTransportWs.SubscriptionClient` is [connectionParams](https://github.com/apollographql/apollo-server/blob/ba43643d1d5d3d54c55ff90d654ab4c3bc5e14cd/packages/apollo-server-module-graphiql/src/renderGraphiQL.ts#L146). Would be nice to have a way for passing [timeout](https://github.com/apollographql/subscriptions-transport-ws/tree/67c50165dc2a6394db46f1ae32b92169948242e9#constructorurl-options-websocketimpl) option as well.

The default timeout on apollo-server-express@1.3.6(subscriptions-transport-ws@0.8.2) is only 10s.

**Comment by abernix** [comment]
We're planning on re-designing the way that subscriptions are implemented in Apollo Server 3.  I'll add this to a project so it can be reviewed in the future, during the design of those updates.  Thanks!

(Also, if you're able to look into adding this, we'd gladly re-open with a proposal for what that change might look like for the current Apollo Server API, and even a PR if the change seems simple enough!)
