### ISSUE TITLE
apollo-server-lambda assumes http is being used to trigger the lambda

### ISSUE THREAD

**Issue by garyhollandxyz** [apollographql/apollo-server#1373]
The handler function returned by `graphqlLambda` from the `apollo-server-lambda` package assumes that the event you pass into it is an http event. This is demonstrated by the code for that handler requiring an `httpMethod` property on the event.

However, it's possible to trigger a lambda without using http at all. E.g. (this is my use case, and how I came across this issue) using the `aws-sdk` npm package to trigger a lambda directly, passing a custom `payload` object which will be used as the `event` for the triggered lambda.

My current solution is to use a custom `apollo-link` to trigger the lambda and pass it the relevant graphQL query, but this means I also have to manually add the `httpMethod` property to my payload object, despite the fact that I'm not using http. This seems weird!

Is there a way around this that I'm missing?

Alternatively, could `apollo-server-lambda` be made less opinionated? 

There is a clear use case for not triggering lambdas by http as it allows you to totally avoid using the AWS API Gateway for them, which both brings its own complications and has a hard limit for the number of APIs you're allowed (a limit which our team is fast approaching with our microservice infrastructure).

Thanks in advance.

**Comment by alfaproject** [comment]
I've just stumbled upon this issue myself and my workaround was to emulate the `APIGatewayProxy` event in the manual lambda invocation, but I do agree that would be nice to have something a bit better.

I'm also passing state from upstream like the authentication header, so it would also be nice if it supported passing state natively.

**Comment by haruska** [comment]
I agree. There should be an `apollo-link` type that can call a direct lambda backed by `apollo-server-lambda`. Little reason to go through the API gateway for internal microservices.

**Comment by jhampton** [comment]
Thank you so much for the suggestion!  There is similar [work being considered](https://github.com/apollographql/apollo-server/issues/2360#issuecomment-500039675) in the [Apollo Server 3 Roadmap](https://github.com/apollographql/apollo-server/issues/2360).

We won't be directly maintaining integrations with specific frameworks in Apollo Server 3, so we're closing this issue for now.
