### ISSUE TITLE
Playground config doesn't work

### ISSUE THREAD

**Issue by DavidOnGitHub** [apollographql/apollo-server#1376]
Following is my code:
```
import express from 'express'
import { ApolloServer } from 'apollo-server'
import { makeExecutableSchema } from 'graphql-tools'
import cors from 'cors'
import { typeDefs, resolvers, schemaDirectives } from './models'

const server = new ApolloServer({
  schema: makeExecutableSchema({
    typeDefs, resolvers, schemaDirectives
  }),
  playground: {
    endpoint: 'http://someurl/abc/graphql',
    settings: {
      'editor.theme': 'light'
    }
  }
})
const app = express()

app.use(cors())

server.applyMiddleware({ app })

app.listen(3000, () =>
  console.log(`The app is listening on ${server.graphqlPath}!`)
)

```
Playground is supposed to send requests to http://someurl/abc/graphql but it's still sending to http://localhost:3000/graphql. In fact the settings don't work either coz the theme doesn't change to 'light'.

apollo-server version is 2.0.0-rc.12. apollo-server-express version is 2.0.0-rc.12.

**Comment by DavidOnGitHub** [comment]
Dug into source code of apollo-server-express and found that the config should be passed as 'gui' in applyMiddleware:
```
import express from 'express'
import { ApolloServer } from 'apollo-server'
import { makeExecutableSchema } from 'graphql-tools'
import cors from 'cors'
import { typeDefs, resolvers, schemaDirectives } from './models'

const server = new ApolloServer({
  schema: makeExecutableSchema({
    typeDefs, resolvers, schemaDirectives
  })
})
const app = express()

app.use(cors())

server.applyMiddleware({ app, gui:  {
  endpoint: 'http://someurl/abc/graphql',
  settings: {
    'editor.theme': 'light'
  }
}})

app.listen(3000, () =>
  console.log(`The app is listening on ${server.graphqlPath}!`)
)
```
Please note this is not in documentation.

**Comment by DavidOnGitHub** [comment]
@unicodeveloper, thanks for your reply. I copied your exact code but the settings still don't work. What's the version of the packages you are using?

**Comment by unicodeveloper** [comment]
Hello @DavidOnGitHub I'm using:

* apollo-server-express: 2.0.0
* express: 4.16.3

**Comment by unicodeveloper** [comment]
This is me using the standalone `apollo-server` and also `apollo-server-express`.

```
const { ApolloServer, gql } = require('apollo-server');

// Construct a schema, using GraphQL schema language
const typeDefs = gql`
  type Query {
    hello: String
  }
`;

// Provide resolver functions for your schema fields
const resolvers = {
  Query: {
    hello: () => 'Hello world!',
  },
};

const server = new ApolloServer({
  typeDefs,
  resolvers,
  path: '/graphl',
  playground: {
    endpoint: '/playground',
    settings: {
      'editor.theme': 'light'
    }
  }
});
server.listen().then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`);
});

**Comment by DavidOnGitHub** [comment]
Yea it works. Thanks @unicodeveloper . I think it might be my cache.

**Comment by mpatelatIBM** [comment]
What are the other option that we can add inside settings,

playground: {
    endpoint: '/server/playground',
    settings: {
      'editor.theme': 'light'
    }
  }

share playground is not working, is there any doc that I can refere?

**Comment by langpavel** [comment]
It does not work for me. All packages at last version.

**Comment by jrhite** [comment]
It does not work for me as well:

```
apolloServer = new ApolloServer{
    typeDefs,
    resolvers,
    playground: {
        endpoint: '/graphiql',
        settings: {
             'editor.theme': 'light'
        }
    }
});
```

The GraphQL loads in the browser at: `http://localhost:3000/graphql` and in the UI tab I see `http://localhost:3000/graphiql`

But then I get a series of 404s: `POST http:/localhost:3000/graphiql 404 (Not Found)`

If I remove the playground settings from the config above everything works, but both the browser URL and the URL in the tab point to `http:/localhost:3000/graphql`

**Comment by mrdulin** [comment]
@jrhite same issue with yours

**Comment by lyudad** [comment]
same issue
