### ISSUE TITLE
What are version 2.x changes

### ISSUE THREAD

**Issue by landau** [apollographql/apollo-server#1380]
I see that `apollo-server-koa` has reached version `2.x`. However, the changelog only reflects a list of changes for release candidates. What are the changes that occurred from 1.x to 2.x? Most importantly, what are the breaking changes. Thanks!

**Comment by juank11memphis** [comment]
+1
Also, please instructions on how to setup graphiql.

Thanks

**Comment by martijnwalraven** [comment]
We do have a [guide for migrating to Apollo Server 2.0](https://www.apollographql.com/docs/apollo-server/v2/migration-two-dot.html).

**Comment by landau** [comment]
@juank11memphis The docs have been updated for using 2.x

• https://www.apollographql.com/docs/apollo-server/v2/getting-started.html
• https://www.apollographql.com/docs/apollo-server/api/apollo-server.html

---

However, I'd really like to see what all the changes, improvements, etc are. :)

I didn't notice the migrate link at the bottom of the API ref. Thanks, @martijnwalraven. Have a wonderful day. 😄

**Comment by juank11memphis** [comment]
Thanks a lot!
