### ISSUE TITLE
Apollo Server 2 Hapi response toolkit is undefined

### ISSUE THREAD

**Issue by avirdz** [apollographql/apollo-server#1382]
I'm trying to include a cookie in the response but the response toolkit is undefined when accessed in the context method.

```js
new ApolloServer({
  typeDefs,
  resolvers,
  context: async ({ request, h }) => {
    return { ... };
  },
})
```
https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-hapi

`h` is undefined

My current server configuration

```js
const server = new ApolloServer({
    typeDefs,
    resolvers,
    schemaDirectives,
    context: async ({ request, h }) => {
      console.log('h', h);
      return {
        request,
          h,
      };
    },
    formatError: (error) => formatError(error, app),
    tracing: true,
  });
```

Am I doing something wrong here?

**Comment by maxnachlinger** [comment]
@avirdz I'm seeing this issue as well in `2.0.0-rc.10`

**Comment by maxnachlinger** [comment]
Looks like adding `h` to the `[request]` array here: https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-hapi/src/hapiApollo.ts#L44 fixes the issue.

**Comment by avirdz** [comment]
nice, thanks for the fix

**Comment by wesselvdv** [comment]
Anyone wanna cut a new version? I really need this fix. :-)
