### ISSUE TITLE
API Playground does not display cursor and response to settings changing

### ISSUE THREAD

**Issue by rankun203** [apollographql/apollo-server#1383]
I'm reporting an issue I encountered with `apollo-server@2.0.0`, cursors does not show up in the Playground, also switching between `light` / `dark` theme mode is not work.

- I've restarted my laptop and the issue persists, so it seems not a GPU issue. 
- Browser's developer tools reported no error, both Safari and Chrome did not work.
- I've tried incognito window, no luck.
- I've tried `apollo-server@ 2.0.0-rc.4`, it was working, now it is not, I think the possibility of hardware issue has increased.

Hardware info:

- macOS 10.13.5 (17F77)
- Mid 2014 Macbook Pro with NVIDIA GeForce GT 750M

[📹View this screencast to give it a closer look (and repro steps).](https://jmp.sh/v/mn0bjyHNwyxT6Hln9yuj)

**Comment by avirdz** [comment]
I have the same problem in mac 10.13.5 (Intel Iris Graphics 540 1536 MB)

**Comment by rankun203** [comment]
@mikeclymer Thanks.

Let's move to that issue instead.

**Comment by localnet** [comment]
Can somebody add `editor.cursorShape': 'line'` to default playground configuration, to solve this?

File: apollo-server/packages/apollo-server-core/src/playground.ts
```
export const defaultPlaygroundOptions = {
  version: playgroundVersion,
  settings: {
    'general.betaUpdates': false,
    'editor.theme': 'dark' as Theme,
    'editor.reuseHeaders': true,
    'tracing.hideTracingResponse': true,
    'editor.fontSize': 14,
    'editor.fontFamily': `'Source Code Pro', 'Consolas', 'Inconsolata', 'Droid Sans Mono', 'Monaco', monospace`,
    'request.credentials': 'omit',
  },
};
```

**Comment by abernix** [comment]
As an update, this is fixed in the latest versions of Apollo Server thanks to #1586.
