### ISSUE TITLE
Overriding playground options turns playground off in production (2.0.0-rc.11)

### ISSUE THREAD

**Issue by thinkjson** [apollographql/apollo-server#1386]
We need to expose a public GraphQL endpoint, as well as an authenticated playground instance at another url. I have created two instances of ApolloServer, one with playground disabled and caching turned on for our clients to use, and one with caching disabled and playground options configured so that cookies will be used on same-origin:

    const server = new ApolloServer({
        ...
        cacheControl: true,
        playground: false,
    });
    server.applyMiddleware({ app, cors: true, path: "/graphql" });
    
    const playground = new ApolloServer({
        ...
        cacheControl: false,
        playground: {
            settings: {
                ...
                "request.credentials": "same-origin",
            },
        },
    });
    playground.applyMiddleware({ app, cors: true, path: "/graphiql" });

I noticed that when I ran this locally, it worked fine, but when I deployed this configuration to production, the playground would not fire.

In digging into [the code](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/playground.ts#L41), I found that when NODE_ENV=production, a PlaygroundRenderPageOptions object is treated as false, disabling the playground altogether:

    const isDev = process.env.NODE_ENV !== 'production';
    const enabled: boolean = typeof playground === 'boolean' ? playground : isDev;

Setting playground: true turns on the playground, but does not enable cookies, causing authentication errors. I would think this logic should treat any truthy playground setting as enabling the playground:

    const isDev = process.env.NODE_ENV !== 'production';
    const enabled: boolean = playground !== undefined ? !! playground : isDev;

**Comment by abernix** [comment]
Fixed via https://github.com/apollographql/apollo-server/pull/1495.
