### ISSUE TITLE
How to pass koa context to graphql?

### ISSUE THREAD

**Issue by Stolenko** [apollographql/apollo-server#1392]
Hello, I use koa and koa-passport for authorization via steam.
But koa and graphql have different contexts.

**How to pass koa context to graphql?**

```javascript
router.get('/', (ctx) => {
  console.log(ctx.state);
  ctx.body = ''
})
```
in console:
```javascript
{ _passport:
   { instance:
      Authenticator {
        _key: 'passport',
        _strategies: [Object],
        _serializers: [Array],
        _deserializers: [Array],
        _infoTransformers: [],
        _framework: [Object],
        _userProperty: 'user',
        _sm: [SessionManager],
        Authenticator: [Function: Authenticator],
        Passport: [Function: Authenticator],
        Strategy: [Function],
        strategies: [Object],
        KoaPassport: [Function: KoaPassport] },
     session: { user: [Object] } },
  user:
   { steamid: '76561198002188570',
     name: 'Stolen',
     avatar:
      'https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/10/10986ae508588c55768d9d68697cb1391e398537.jpg' } }
```

Apollo server:
```javascript
const apollo = new ApolloServer({
  schema,
  context: ({ ctx }) => ({ ctx })
})

...

apollo.applyMiddleware({ app })
```

my test resolver:
```javascript
  Query: {
    test: (parent, args, ctx, info) => {
      console.log(ctx.state);
      return "testsQ"
    }
  }
```

in console:
```javascript
undefined
```

**Comment by cdebotton** [comment]
Correct me if I'm wrong about this, but it doesn't seem like `ContextFunction<T>` passes koa's context value, just query information from `ApolloServer`.

**Comment by Louis-T** [comment]
Hi,


The source code is somewhat hard to read, but it seems that in the
apollo-graphql-koa packages, the Koa context is passed as an argument for
the method *createGraphQLServerOptions* when creating the apollo-server.
See file
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-koa/src/ApolloServer.ts,
line 66.

I also made a quick project to see if it worked and I was able to pass Koa
context state to the resolvers.
See code below.

Bye




*package.json code :*


> {
>   "name": "koaql",
>   "version": "1.0.0",
>   "main": "index.js",
>   "license": "MIT",
>   "dependencies": {
>     "apollo-server-koa": "^2.0.0",
>     "graphql": "^0.13.2"
>   },
>   "scripts": {
>     "start": "node index.js"
>   }
> }
>



*index.js code :*

const koa = require('koa');
> const { ApolloServer } = require('apollo-server-koa');
> const { GraphQLSchema, GraphQLObjectType, GraphQLString } =
> require('graphql');
>
>
> const schema = new GraphQLSchema({
>   query: new GraphQLObjectType({
>     name: 'Query',
>     fields: {
>       test: {
>         type: GraphQLString,
>         resolve: (parentValue, args, context, info) => {
>           return context.state.test;
>         }
>       }
>     }
>   })
> });
>
>
> const PORT = 3000;
> const app = new koa();
>
> app.use(async (ctx, next) => {
>   ctx.state.test = 'hello world';
>   await next();
> });
>
> const server = new ApolloServer({
>   schema,
>   context: ({ ctx }) => {
>     return ctx;
>   }
> });
>
> server.applyMiddleware({ app });
>
> app.listen({ port: PORT }, () =>
>   console.log(`🚀 Server ready at http://localhost:
> ${PORT}${server.graphqlPath}`),
> );
>



2018-07-24 1:55 GMT+02:00 Christian de Botton <notifications@github.com>:

**Comment by martijnwalraven** [comment]
It seems this has been resolved.
