### ISSUE TITLE
Response not successful: Received status code 500

### ISSUE THREAD

**Issue by deathg0d** [apollographql/apollo-server#1398]
I am trying to migrate to version 2. I am using the following code to send user information inside jwt token to the context.
```
const server = new ApolloServer({
    typeDefs: gql`${typeDefs}`,
    resolvers,
    context: ({ req, res }) => {
        const username = validateJWT(req.headers)
        return { username }
    }
})
```

`validateJWT` is a function which throws error if jwt is invalid. If the jwt is empty, it returns null and if jwt is valid it returns a username.

This is working fine when jwt is empty or valid. But when jwt is invalid, it throws an error which is visible **momentarily** in playground and then the playground switches to:
```
{
  "error": "Response not successful: Received status code 500"
}
```
Looks like response is not triggered?

**Comment by martijnwalraven** [comment]
Do you get the whole error when making the call though `curl` or another HTTP client? I believe the disappearing error is a Playground issue, so you should probably open an issue [there](https://github.com/prismagraphql/graphql-playground).

**Comment by abernix** [comment]
Closing due to a lack of response.  I agree the disappearing error is a (frustrating) GraphQL Playground issue, but thank you for opening that issue on the other repository.

Happy to re-open this if you can provide a reproduction of the problem with the actual error — via `curl` as suggested (you can generate and copy/paste the command from GraphQL Playground into a terminal).  Thanks!

**Comment by mrdulin** [comment]
I hit this issue when run `apollo service:push` command

```bash
> apollo service:push

  ✔ Loading Apollo Project
  ✖ Uploading service to Engine
    → Response not successful: Received status code 500
ServerError: Response not successful: Received status code 500
    at Object.exports.throwServerError (~/workspace/github.com/mrdulin/apollo-graphql-tutorial/node_modules/apollo-link-http-common/lib/index.js:23:17)
    at ~/workspace/github.com/mrdulin/apollo-graphql-tutorial/node_modules/apollo-link-http-common/lib/index.js:48:21
    at <anonymous>
```

**Comment by solipsis** [comment]
I am still getting the error when running the example as listed in the docs
```

**Comment by glasser** [comment]
@solipsis Are you using Apollo Server 3? We made all hooks async in AS3; only some were previously.

**Comment by solipsis** [comment]
You are correct. I was accidentally testing against the previous version. Thanks

**Comment by ni-ma6593** [comment]
1
