### ISSUE TITLE
Serverless with Google Cloud Function

### ISSUE THREAD

**Issue by iaarab** [apollographql/apollo-server#1402]
Is it possible to implement apollo-server 2 with cloud function? 

The documentation only shows the implementation for AWS Lambda.

Snippet that worked with apollo-server 1 and express:
![Image of Yaktocat](https://image.ibb.co/dwN1yd/Screenshot_12.png)

**Comment by develomark** [comment]
I'd like to see this also!

**Comment by unicodeveloper** [comment]
PRs are welcome from anyone that wants to take that as a challenge! You can follow this [issue #1088 on how to get started](https://github.com/apollographql/apollo-server/issues/1088)
