### ISSUE TITLE
Is this package compatible with the serverless framework?

### ISSUE THREAD

**Issue by AyoubEd** [apollographql/apollo-server#1403]

**Comment by abernix** [comment]
Serverless supports deploying to AWS Lambda and Google Cloud Functions — both of which are so-called _serverless_ Node.js environments.  If you deploy an app utilizing `apollo-server-lambda` or `apollo-server-cloud-functions` (both integration packages which Apollo Server offers) with the `serverless` tool, we expect it to work!

I'll close this, but if you have anything more specific, don't hesitate to ask!
