### ISSUE TITLE
formatParams replacement and GraphQLExtension

### ISSUE THREAD

**Issue by richgilbank** [apollographql/apollo-server#1404]
Hi folks! 

It looks like the [removal of `formatParams`](https://github.com/apollographql/apollo-server/pull/1331) from the ApolloServer constructor options eliminates the approach some have taken to omit `__typename` from mutations derived from query results. 
See here: https://github.com/apollographql/apollo-client/issues/1564
This may be a bit of an edge case, but there seems to be a number of issues relating to the following situation: 
- Query for a data set from Apollo Server, using Apollo Client.
- [`__typename` is added to the query result] 
- Locally modify the data set and send it back as a mutation. 
- Rejection due to `__typename` not being defined in the typedefs.

One workaround to this has historically been using `formatParams` to omit the __typename key from any incoming variables, so it doesn't have to happen on the client side (and consequently doesn't have to be implemented in every consumer). 
@evans mentioned ["The experimental, non-public `graphql-extensions` provides a more structured and flexible way of instrumenting Apollo Server"](https://github.com/apollographql/apollo-server/pull/1331/files#diff-3948ca675834eeb95a70b3ec6725a6a2R248), though I haven't seen any implementations or docs that might help to do so. 

So, I suppose any of the following would really help to clarify usage with the new approach:
- Add a demo or docs for [`graphql-extensions`](https://github.com/apollographql/apollo-server/tree/master/packages/graphql-extensions)
- Add tests for `graphql-extensions`
- Document extensions publicly with the ApolloServer docs

Or is it a short-term workaround that shouldn't be documented yet? 
Thanks!

**Comment by martijnwalraven** [comment]
The reason we removed `formatParams` is that it depended on implementation details of Apollo Server that we don't want to be bound to. `graphql-extensions` is not an API we're committed to either, but it could be used as a short term workaround. We're working on a more flexible extension API for the next version of Apollo Server, so hopefully we'll have a more permanent solution in a few weeks.

To make sure that covers your use case, do I get it right you want to modify variables for an incoming GraphQL request?

**Comment by richgilbank** [comment]
Ah, ok so it probably doesn't make sense to document it for now then. 
Yes, exactly...walking through the variables on an incoming request to omit any nested `__typename` keys.

**Comment by terion-name** [comment]
No solution yet? My entire app can't work without this

**Comment by jbaxleyiii** [comment]
Hey @richgilbank @terion-name this is something that can be done using the new request pipeline that is supported now and will be getting a lot more support (and docs) in the future!
