### ISSUE TITLE
Default rest data source cache key should include method

### ISSUE THREAD

**Issue by mattsjones** [apollographql/apollo-server#1408]
The default cache key used for `RESTDataSource` is the full request URL. 
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts#L64
I think it should also include the method (eg. GET, PUT, POST, etc...). 

The current behaviour can cause a strange situation when a mutation updates a resource and gets that resource in the same query. In my case, the result of a PUT was memoized and returned for my GET query which makes no sense. I can't foresee any situations where this would be the desired behaviour. 

Thanks for the great work btw. 👏 🍻

**Comment by martijnwalraven** [comment]
I think the right thing to do is probably to disable caching altogether for non-GET requests. Someone recently opened [a PR](https://github.com/apollographql/apollo-server/pull/1399) for this (which needs some work, but I agree with the fix). Other HTTP caches, including CDNs, also seem to do this and use the request URL without method as the cache key by default.

One addition to consider is automatically invalidating cached GET requests when a PUT/POST/DELETE is performed against the same URL. That also matches standard HTTP cache behavior.

**Comment by mattsjones** [comment]
Both options sound reasonable to me. 👍

**Comment by martijnwalraven** [comment]
This should be fixed in `apollo-datasource-rest` 0.1.1.
