### ISSUE TITLE
Apollo specific error codes not propagating to user

### ISSUE THREAD

**Issue by DylanOrsh** [apollographql/apollo-server#1412]
(First time contributing to Git so apologies for any awkward explanations / lack of information)

So, we've written error handling code in one of our resolvers to throw a new UserInputError, as outlined in the docs, but the error code in the output's errors.extensions.code is showing as INTERNAL_SERVER_ERROR instead of BAD_USER_INPUT.

When I dig into the resolution with the debugger, I can see that when my error object is passed from my resolver to graphql-tools/dist/stiching/delegateToSchema.js 's __awaiter function, its 'extensions' value is undefined. At the same time, inside the error object's 'originalError' object, I can see the 'extensions' value of the GraphQL error contained inside 'originalError' has the expected "BAD_USER_INPUT" code.

The result of the main 'extensions' value being undefined is that when this error arrives down the chain in apollo-server-error's enrichError function, lines 73...81 which build the final Apollo Error object always gives the INTERNAL_SERVER_ERROR code. This is true in our case for both UserInputError and ForbiddenError.

We're not sure at this point if this is a bug, or occurring because of something in the rest of our structure? Any help would be greatly appreciated.

**Resolver**
```
const myObjectsResolvers = {
  Query: {
    myObject: (obj, args, context, info) => myFunction(args).then( doSomeOtherStuff() )
  },
  ....
  // other resolvers
}
...
const myFunction = args => {
   // do some stuff
   return getObjectFromBackEnd
   .then(...)
   .catch( error => {
        if (error.message === 'Not Found') {
            throw new UserInputError('Object with id ' + error.body._id.toString() + ' not found.');
        }
   });
```

**Comment by martijnwalraven** [comment]
I think this is a limitation specific to schema stitching, so you may want to open an issue on [`graphql-tools`](https://github.com/apollographql/graphql-tools) instead.

**Comment by DylanOrsh** [comment]
Thanks @martijnwalraven. Have opened a new issue there at this link: https://github.com/apollographql/graphql-tools/issues/906.

**Comment by unicodeveloper** [comment]
Awesomem @DylanOrsh I'll close this issue now.
