### ISSUE TITLE
email message with attachment not working following the apollo-server upload docs

### ISSUE THREAD

**Issue by dohomi** [apollographql/apollo-server#1416]
The docs are missing an important piece how to upload a message with attachments for email massaging with apollo-server 2.

I followed the upload examples but I was not able to get it right:
```gql
input SendMailMessageInput{
    tag: String
    from: String
    to: [String!]!
    cc: [String!]
    bcc: [String!]
    subject: String!
    text: String
    html:String
}

type SendMailPayload{
    data:JSON
}

type Mutation{
    sendMail(message:SendMailMessageInput, attachments:[Upload!]) : SendMailPayload
}
```
```js
module.exports = {
  Mutation: {
    sendMail: async (parent, {message, attachments}) => {
     // attachments is not a type File
    }
}
```
I have console log on my client and its an array of valid `File` objects inside of my variables. But in the network panel the `attachments` field is an array of empty objects and and the gql request is also not shown as a multipart form request but only JSON. Any idea what I am missing? Thanks

**Comment by dohomi** [comment]
I missed the correct apollo link. was not an issue on apollo-server

**Comment by hanmant83** [comment]
> The docs are missing an important piece how to upload a message with attachments for email massaging with apollo-server 2.
> 
> I followed the upload examples but I was not able to get it right:
> 
> ```graphql
> input SendMailMessageInput{
>     tag: String
>     from: String
>     to: [String!]!
>     cc: [String!]
>     bcc: [String!]
>     subject: String!
>     text: String
>     html:String
> }
> 
> type SendMailPayload{
>     data:JSON
> }
> 
> type Mutation{
>     sendMail(message:SendMailMessageInput, attachments:[Upload!]) : SendMailPayload
> }
> ```
> 
> ```js
> module.exports = {
>   Mutation: {
>     sendMail: async (parent, {message, attachments}) => {
>      // attachments is not a type File
>     }
> }
> ```
> 
> I have console log on my client and its an array of valid `File` objects inside of my variables. But in the network panel the `attachments` field is an array of empty objects and and the gql request is also not shown as a multipart form request but only JSON. Any idea what I am missing? Thanks
