### ISSUE TITLE
File uploads using apollo-server-lambda

### ISSUE THREAD

**Issue by taikn** [apollographql/apollo-server#1419]
Hi,
Could not find any mention, whether apollo-server-lambda supports the GraphQL multipart request specification for uploading files as mutation arguments (like apollo-server does)

**Comment by unicodeveloper** [comment]
Hello @taikn `apollo-server-lambda` supports uploading files as mutation arguments like `apollo-server` does!

**Comment by taikn** [comment]
Hmmm, I am getting following error, when trying to upload a file using `apollo-server-lambda`, while uploading a file using `apollo-server` with same config, works without problems.

```
SyntaxError: Unexpected number in JSON at position 1
at JSON.parse (<anonymous>)
at graphqlHandler (/var/task/node_modules/apollo-server-lambda/dist/lambdaApollo.js:24:24)
at /var/task/node_modules/apollo-server-lambda/dist/ApolloServer.js:87:85
```

**Comment by tomyitav** [comment]
@taikn +1, getting the same error on simple graphql query execution:
![erroroncloudswatch](https://user-images.githubusercontent.com/16193919/44298560-071c2000-a2ee-11e8-8ace-88cbaf6dfe51.PNG)

**Comment by AlpacaGoesCrazy** [comment]
I think that this error is due to apollo-server-lambda tries to parse `event.body` as JSON when apollo-upload sends uploading request with `multipart/form-data` content type
Here it is: https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-lambda/src/lambdaApollo.ts#L46

**Comment by sunny-knowre** [comment]
any updates on this? having the same issue as well.

**Comment by javiermanzano** [comment]
Having the same issue here. Any solutions?

**Comment by henrinormak** [comment]
> Hello @taikn apollo-server-lambda supports uploading files as mutation arguments like apollo-server does!

I don't believe that's true, going over the source code of `apollo-server-lambda`, there are no references to `apollo-server-upload`, compare that to the koa and express variants, which both explicitly call `processRequest` from `apollo-upload-server` as middleware that runs before the actual query is run. Could you explain how the file upload is supposed to work in `apollo-server-lambda`?

**Comment by stanleycyang** [comment]
Seeing this error as well.

**Comment by gorillatron** [comment]
Im also getting this error using `apollo-server-lambda`

**Comment by Knowledge91** [comment]
Anybody able to fix this?

**Comment by craigcartmell** [comment]
I'd be keen for an update on this too. Or an alternative solution?

This looks like it could potentially be useful: https://github.com/myshenin/aws-lambda-multipart-parser#readme

**Comment by jakebenn** [comment]
+1

**Comment by NHebrard** [comment]
Same need here

**Comment by bluedusk** [comment]
same issue here

**Comment by eliliam** [comment]
This still is an issue, does anyone have any updates on this?

**Comment by nemmarramos** [comment]
Any updates?

**Comment by jbaxleyiii** [comment]
Thanks very much for reporting this! We think this is a great idea, and would definitely review a PR. If you (or anyone else) is interested in working on this, that would be great - thanks!

**Comment by mrfoster** [comment]
@jbaxleyiii Why was this issue closed? There is an open pull request here: https://github.com/apollographql/apollo-server/pull/1739

**Comment by totteire** [comment]
@jbaxleyiii Still waiting for the file upload to work in apollo-server-lambda ...
Any update ?
Meanwhile I use another lambda to handle my file uploads :( but it makes me so sad ;(

**Comment by proficiat** [comment]
the same error at JSON parse

**Comment by totteire** [comment]
yes

**Comment by dcai-icfi** [comment]
This works! But there seems to be the limit of file size. I got this error when I tried to upload a large file like ~30M:
```
error: "Request Entity Too Large"
message: "Payload content length greater than maximum allowed: 10485760"
statusCode: 413
```
It's similar to this issue: https://github.com/apollographql/apollo-server/issues/3354
But in that case, it uses apollo-server-express. I cannot do the suggestion that @abernix provided:
```
serverApollo.applyMiddleware({
  app,
  route: {
    payload: {
      maxBytes: 52428800,
    },
  },
});
```
I also tried:
```
const options = {
  uploadsConfig: {
    maxFieldSize: 52428800, // bytes = 50MB
    maxFileSize: 52428800,
    maxFiles: 10
  }
};
ApolloServer.createHandler(options);
```
But it does not take uploadsConfig. Any ideas?

Thanks!

**Comment by Santhosh222** [comment]
This is not working. I got a new error in apollo server lambda but works fine in apollo server.
Exception -----------------------------------------------
 
  [
    [Error: Missing Content-Type] {
      locations: undefined,
      path: undefined,
      extensions: { code: 'INTERNAL_SERVER_ERROR' }
    }
  ]

**Comment by mathix420** [comment]
@dcai-icfi it seems you are facing to a hard limit of AWS Lambda (`Invocation payload | 6 MB`) https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html#w603aac11c66c15

**Comment by GolivetsAndreu** [comment]
@Santhosh222 Did you resolve your solution?

**Comment by GolivetsAndreu** [comment]
@it-crafter see https://github.com/apollographql/apollo-server/issues/5093, I think it can help you

**Comment by donalatorre** [comment]
I also faced this issue, and found no decent solution to implementing file uploads in `apollo-server-lambda`.
So I decided to abandon `apollo-server-lambda` completely, since it doesn't seem to be getting much attention or maintenance. 

I found that what I needed was totally achievable with `apollo-server-express`, `graphql-upload`, and `serverless-http`.

`src/index.ts`
```
import {
  ApolloServer
} from "apollo-server-express";
import express from "express";
import {
  graphqlUploadExpress, // The Express middleware.
  GraphQLUpload, // The GraphQL "Upload" Scalar
} from "graphql-upload";
import serverless from "serverless-http";

const typeDefs = gql`
  scalar Upload
  ... your schema ...
`

const resolvers = {
  Upload: GraphQLUpload as any,
  //... your resolvers ...
}

const server = new ApolloServer({
  typeDefs,
  resolvers,
  introspection: true,
  uploads: false, // Cancel the default apollo upload option
});

const app = express();
app.use(graphqlUploadExpress()); // Apply the express upload middleware
server.applyMiddleware({ app });

exports.handler = serverless(app);

```

**Comment by skeep-exogee** [comment]
This is worked for me in the end:

```
exports.handler = server.createHandler({
	expressGetMiddlewareOptions: { bodyParserConfig: { limit: '50mb' } },
});
```

**Comment by amiklosi** [comment]
Thanks @skeep-exogee , that was a day saver!

**Comment by mateo2181** [comment]
@skeep-exogee can you share the configuration you use? I'm using apollo-server-lambda with graphqlUploadExpress but it is not working. I testing it from Firecamp to send the file.
