### ISSUE TITLE
Express: When playground is enabled, it still passes `GET graphql`

### ISSUE THREAD

**Issue by wmertens** [apollographql/apollo-server#1420]
When going to `/graphql`, it loads the playground in the browser, but in the meantime, the server is doing SSR for `/graphql`, even though that route is later

Shouldn't `GET /graphql` stop propagating?

v2.0

**Comment by unicodeveloper** [comment]
@wmertens Please can you shed more light on this scenario?

**Comment by wmertens** [comment]
My express stack is set up like this:

* stuff: logging, sessions etc
* apollo-server v2.0: mounted with `server.applyMiddleware({app})`
* SSR: anything else is interpreted as a SPA URL and rendered on the server, sent to the client

When I visit `/graphql` to go to the playground, my SSR middleware still fires and pre-renders `/graphql` and then gets errors for sending headers after they're sent.

I think this line shouldn't be there?

https://github.com/apollographql/apollo-server/blob/fa6c973f3685fceea905acf259824005e0e0ffe2/packages/apollo-server-express/src/ApolloServer.ts#L169

**Comment by mikebm** [comment]
Experiencing the same issue. Was just about to log a bug when I found this one.  The issue as @wmertens pointed out, is that next is being called after res.end() is called. This causes SSR rendering routes which use the route of '*' to be hit.
