### ISSUE TITLE
Graphql playground doesn't load when offline

### ISSUE THREAD

**Issue by wmertens** [apollographql/apollo-server#1421]
You can't use the playground to test the graphql API while offline (e.g. when working on a train)

**Comment by unicodeveloper** [comment]
@wmertens Do you mean using playground in production? Or is this about using playground locally?

**Comment by wmertens** [comment]
using the playground locally, while developing your app. It is served from a CDN. It would be nice if the assets were local instead.

**Comment by penx** [comment]
Same issue here, I need to be able to use GraphQL Playground without an internet connection. Happy to look in to this issue if anyone has any pointers.

Some more details:

Following the [introduction tutorial](https://www.apollographql.com/docs/apollo-server/getting-started.html) and loading http://localhost:4000 returns an html response. The top of the html response contains:

```html
...
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/graphql-playground-react@1.7.4/build/static/css/index.css" />
  | <link rel="shortcut icon" href="//cdn.jsdelivr.net/npm/graphql-playground-react@1.7.4/build/favicon.png" />
  | <script src="//cdn.jsdelivr.net/npm/graphql-playground-react@1.7.4/build/static/js/middleware.js"></script>
```

It would be good to have the option to include graphql-playground-react as a devDependency and serve these files from localhost rather than cdn.jsdelivr.net.

**Comment by penx** [comment]
Related:

https://github.com/apollographql/apollo-server/blob/8347511db8e5f9ae6026833af17d266ec165e8dc/packages/apollo-server-micro/src/ApolloServer.ts#L127

https://www.npmjs.com/package/@apollographql/graphql-playground-html

https://github.com/apollographql/graphql-playground/tree/master/packages/graphql-playground-html

**Comment by penx** [comment]
I guess having the option to override `//cdn.jsdelivr.net/npm/` in `@apollographql/graphql-playground-html` with a config option set on playgroundOptions in apollo server would be a good first step. It would rely on the developer setting up another URL where they can host graphql-playground-react assets, e.g. on another port on localhost.

Either that or serving the assets on Express and using the running apollo server url.

**Comment by penx** [comment]
@anodynos https://github.com/prisma/graphql-playground/pull/845 was merged in today and will be in the next release of graphql-playground.

However, Apollo Server uses a fork - @apollographql/graphql-playground-html

I need someone from the Apollo team to let me know where this fork lives so I can open a PR for this fix, or for them to let me know what the process will be for including this in their fork.

Once this is done, offline support can be done as per this project:

https://github.com/penx/graphql-server-example

Or someone from the Apollo team could feed in to my comments on this WIP PR:

https://github.com/apollographql/apollo-server/pull/1734

**Comment by penx** [comment]
For reference, the scoped graphql-playground-html was added in 8ea36d80 by @martijnwalraven 

`@apollographql/graphql-playground-html` is almost identical to 1.6.0 of `graphql-playground-html`, the only difference being in render-playground-page.d.ts:
```
    config?: GraphQLConfigData;
```js

was changed to

```js
    config?: any;
```

(and the associated import removed)

@martijnwalraven was the use of scoped graphql-playground-html meant to be temporary? Does this fork live anywhere? How do we go about getting changes in to it?

**Comment by martijnwalraven** [comment]
I don't think it's temporary, because upstream has a dependency on `graphql-config`, which brings in a number of other dependencies we don't want (like `graphql-import`). We want Apollo Server to stay lean and be able to run in edge environments.

The fork currently lives at https://github.com/apollographql/graphql-playground/tree/remove-graphql-config. Rebasing those changes on top of the upstream `master` shouldn't lead to too much trouble.

**Comment by JonPaz** [comment]
Hi @martijnwalraven - Just wondering when the change to support offline playground resources will be merged in?  Many thanks!

**Comment by OlivierJM** [comment]
Any progress with this issue, I have never noticed the need until now and it’s quite annoying.
Any workarounds ?

**Comment by JonPaz** [comment]
@OlivierJM - I've now got this working by implementing the following:

- Create an HTTP(S) endpoint to serve the graphql-playground-react static content.  I grabbed the following:

https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.10/build/static/css/index.css
https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.10/build/static/js/middleware.js
https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.10/build/favicon.png

to:

./favicon.png
./static
./static/css
./static/css/index.css
./static/js
./static/js/middleware.js

And used used http-server to server them.

- When creating a new ApolloServer, set the playground CDN url:
```
const server = new ApolloServer({
  playground: {
    cdnUrl: "http://127.0.0.1:8080"
  },
  typeDefs,
  resolvers,
  dataSources: () => ({
    launchAPI: new LaunchAPI()
  })
});
```

**Comment by OlivierJM** [comment]
> @OlivierJM - I've now got this working by implementing the following:
> 
> * Create an HTTP(S) endpoint to serve the graphql-playground-react static content.  I grabbed the following:
> 
> https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.10/build/static/css/index.css
> https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.10/build/static/js/middleware.js
> https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.10/build/favicon.png
> 
> to:
> 
> ./favicon.png
> ./static
> ./static/css
> ./static/css/index.css
> ./static/js
> ./static/js/middleware.js
> 
> And used used http-server to server them.
> 
> * When creating a new ApolloServer, set the playground CDN url:
> 
> ```
> const server = new ApolloServer({
>   playground: {
>     cdnUrl: "http://127.0.0.1:8080"
>   },
>   typeDefs,
>   resolvers,
>   dataSources: () => ({
>     launchAPI: new LaunchAPI()
>   })
> });
> ```

Thanks for pointing this out, I will set this up in advance in case. 
Thank you

**Comment by jbaxleyiii** [comment]
The latest Apollo Server is rebased on the latest from the upstream project which should support this!

**Comment by mrdulin** [comment]
Need Graphql playground work offline/slow network for Apollo Server 2.x which means work without the static resources from CDN.

**Comment by mrdulin** [comment]
I try to use playground offline like this:

```ts
import { gql, IResolvers } from 'apollo-server';
import express from 'express';
import path from 'path';
import { ApolloServer } from 'apollo-server-express';

const typeDefs = gql`
  type Query {
    name: String
  }
`;

const resolvers: IResolvers = {
  Query: {
    name: () => 'name',
  },
};

const PORT = process.env.PORT || 3000;
const app = express();
const staticRoot = path.resolve(__dirname, '../../node_modules');
app.use('/node_modules', express.static(staticRoot));
const server = new ApolloServer({ typeDefs, resolvers, playground: { cdnUrl: './node_modules' } });
server.applyMiddleware({ app });

app.listen(PORT, () => {
  console.log(`🚀 Server ready at http://localhost:${PORT}${server.graphqlPath}`);
});
```

But it doesn't working. The browser try to request `middleware.js`, but got 404:

```
Request URL: http://localhost:3000/node_modules/graphql-playground-react@1.7.31/build/static/js/middleware.js
Request Method: GET
Status Code: 404 Not Found
Remote Address: [::1]:3000
Referrer Policy: no-referrer-when-downgrade
```

**Comment by rahularyan** [comment]
A simple and very elegant solution is to use Resource Override extension for chrome browser. Replace CDN URL to local file.

![Annotation 2019-12-15 154445](https://user-images.githubusercontent.com/916764/70861296-ec919f80-1f51-11ea-8d03-0d1db92ae8dc.jpg)

**Comment by TalShperling** [comment]
There is another solution I came up with.

If you are working on other network/locally you can clone this project:
https://github.com/TalShperling/graphql-playground-offline

and run the CDN locally for your/your environment's needs.

**Comment by francois-gsk** [comment]
All this looks useless since the playground load google fonts in its static HTML…  🧐🤨😭
