### ISSUE TITLE
Apollo-Server 2 does not support cookie authentication. This is huge.

### ISSUE THREAD

**Issue by tanekim77** [apollographql/apollo-server#1423]
I have two issues:

1 . I believe this one is an issue for Apollo-Server 2 as well, not just for Apollo-Server-koa 2, because I came across some people having the same issue with Apollo-Server 2, without anyone able to help.
I am using Koa-passport and Koa-session, along with Apollo-Server-Koa
 Apollo-Server-Koa 1.* let's koa-session to set cookie without an issue. 
In version 2.0, it no longer lets koa-session to sets cookie. I.e., in google chrome's inspecter pane-> Application -> Cookies are not filled up

how to reproduce:
I have 2 repositories:
https://github.com/tanekim77/apollo-server-koa-1.4-setting-cookies
https://github.com/tanekim77/apollo-server-koa-2-not-setting-cookies

How to test:

=> open the repo in vs code, 
0. in the terminal=> yarn install
1.  press F5 to debug,
2. open the chrome browser,
and go to localhost:4000/graphql for
https://github.com/tanekim77/apollo-server-koa-2-not-setting-cookies
and go to localhost:3000/graphiql for 
https://github.com/tanekim77/apollo-server-koa-1.4-setting-cookies

=>Please note the extra "i" in localhost:3000/graphiql compared to  localhost:4000/graphql 

 get into inspector pane in chrome by pressing F12 on windows, go to Application tab, and go to "Cookies" in the left pane, and inspect if cookies are filled up when making this query 
{
   hi
}

Then, you will see one repo filling up 2 cookies, while the other do not.
Since they are both localhost, even if one repo fills up cookies, the cookies will be shown to the other localhost address as well. So, please clear up cookies before sending each query.

2. Also, it seems that to get ctx from the resolver, I need to get as a child {ctx}, instead of ctx directly. Is this intentional? If so, what's the reasoning behind making it a little bit harder to get ctx? (I am aware of the workaround) Thanks!

**Comment by ScreamZ** [comment]
Same question about this, can we just expect some kind of cookie parser so we can make a cookie based auth ? Thanks
