### ISSUE TITLE
Apollo Server Returns Error called Cannot find name 'AsyncIterator'. even after adding 'esnext' to lib in tsconfig.json

### ISSUE THREAD

**Issue by riginoommen** [apollographql/apollo-server#1426]
<!--**Issue Labels**
- [x] has-reproduction

**Comment by riginoommen** [comment]
tsconfig.tson
<img width="425" alt="screen shot 2018-07-26 at 9 32 45 pm" src="https://user-images.githubusercontent.com/3840244/43273982-809df834-911b-11e8-9711-19074f0723c1.png">

package.json
![screen shot 2018-07-26 at 9 33 37 pm](https://user-images.githubusercontent.com/3840244/43274015-960b4e4c-911b-11e8-882f-3c4436d69f11.png)

Error log is

--Using tsc v2.6.2
node_modules/@types/graphql/subscription/subscribe.d.ts(36,13): error TS2304: Cannot find name 'AsyncIterator'.
node_modules/@types/graphql/subscription/subscribe.d.ts(47,12): error TS2304: Cannot find name 'AsyncIterator'.
node_modules/@types/graphql/subscription/subscribe.d.ts(75,12): error TS2304: Cannot find name 'AsyncIterable'.

**Comment by riginoommen** [comment]
Hey @martijnwalraven 

I tried the same also but didn't worked

**Comment by martijnwalraven** [comment]
Weird, our code uses `"lib": ["es2017", "esnext.asynciterable"]` and that works. Maybe it's because you're using an older version of TypeScript? (The current version is 2.9.2.)

**Comment by riginoommen** [comment]
Well. I am using the current Version of typescript 2.9.2

**Comment by riginoommen** [comment]
Hi @martijnwalraven 

Even I tried upgrading and downgrading the version of apollo-server-express but did n't result in any change

**Comment by martijnwalraven** [comment]
Oh, I was confused because your output shows `Using tsc v2.6.2`.

**Comment by riginoommen** [comment]
@martijnwalraven My VSCode showed 2.9.2 yes you are correct its 2.6.2

**Comment by JacksonKearl** [comment]
This looks to be resolved by upgrading TS, so I'll go ahead and close it for now. If anyone else encounters this with modern TS we'll take another look!
