### ISSUE TITLE
apollo-datasource-rest post, put, patch lost ability to pass URLSearchParams

### ISSUE THREAD

**Issue by mikebm** [apollographql/apollo-server#1438]
The post, put and patch methods used to require the body to be passed via options rather than as an argument. When this was changed, the options type was changed to RequestInit which doesn't allow you to pass the params for the query string. It now has to be fully written out into the path, which is inconvenient. 

This is a request to allow params to be passed to post, put and patch either via options or how it is passed to get and delete. (which is how it used to be).

https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts#L153

**Comment by jspears** [comment]
Having chased this down the typings are wrong, but you can pass params in the init object.

`
post('path', body, {params:{key:1}});
`

However the RequestInit does not have the 
` RequestInit & { params?:URLSearchParamsInit} `
definition that get/delete have, even though it probably should.

**Comment by jbaxleyiii** [comment]
Thanks very much for reporting this! We think this is a great idea, and would definitely review a PR. If you (or anyone else) is interested in working on this, that would be great - thanks!

**Comment by ahctangU** [comment]
?This is markeed as done, but it's still not fixed as of 2.9.3

**Comment by natepriddy** [comment]
Also ran into this today. Would it be better to reopen or recreate the issue? Is there a way to patch this definition locally for now?
