### ISSUE TITLE
apollo-server-core formatError never called

### ISSUE THREAD

**Issue by ak99372** [apollographql/apollo-server#1439]
We're using [**runHttpQuery**] from apollo-server-core on lambda and passing **formatError** as one of the options.
However this handler never gets called back when exception is raised in resolver...

`resolve = (source, args, context, info) => {
    throw new Error("This is generic error");
  }
`

Is this meant for other types of errors?

Notes: I had a look at runHttpQuery which passes the formatError to runQuery but it looks like runQuery never uses this handler (I'm also using [formatResponse] which gets called without issues)

**Comment by robrichard** [comment]
I've been looking into this more and I can see that `formatError` is called only when passed to the `ApolloServer` constructor (via https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/formatters.ts#L22)

It is ignored when you use `runHttpQuery` or `runQuery` directly.

Unfortunately you cannot access the express `req` object in `formatError` when you pass it to the `ApolloServer` constructor.

**Comment by tgriesser** [comment]
Just opened a PR to fix this in #1662

**Comment by abernix** [comment]
I'll close this for the reasons I explained in https://github.com/apollographql/apollo-server/pull/1662#issuecomment-439481350.

The `formatError` method aligns with the underlying `graphql-js`'s `formatError` which doesn't have access to the context either.  If you're looking to access the context and errors at the same time, check out the #2719 hook, which would allow you to augment an error with additional properties, based on the `requestContext` (which `didEncounterErrors` does receive!) and respond accordingly in `formatError`.  (You could also just manipulate the error within the `didEncounterErrors` bit, but your usage may vary.)
