### ISSUE TITLE
2.0 Please make expose uploadsConfig

### ISSUE THREAD

**Issue by mikebm** [apollographql/apollo-server#1440]
I am using apollo-server-express which supports uploads, and unfortunately uploadsConfig is marked protected which means the only way to set things like the max file size is by creating a new server that extends the ApolloServer.

**Comment by unicodeveloper** [comment]
Please can you shed more light on this @mikebm ? What do you mean the only way to set max file size is by extending Apollo server? You can pass max file size as an option to the constructor.

**Comment by mikebm** [comment]
Please ignore. It appears Config is now the input to ApolloServer. It used to be GraphQLOptions, which did not expose that property. You can close this.
