### ISSUE TITLE
MySQL DataSource

### ISSUE THREAD

**Issue by jlubeck** [apollographql/apollo-server#1458]
Are there any plans to create a MySQL DataSource just like we have the REST DataSource?

If not, can you give any pointers on what would be the best way to connect to a MySQL DB directly, withou using a REST Server in the middle?

Thank you

**Comment by tab00** [comment]
There should be more and better documentation with examples of using Data Sources with databases, as apps have more of a need to connect with databases than REST sources.

A simple starter kit would be good.

That "fullstack-workshop-server" example still seems outdated as it refers to Facebook's dataloader, and may not be easy to start with for those who didn't attend the workshop.

**Comment by bennypowers** [comment]
The example moved to https://github.com/apollographql/fullstack-workshop-server/blob/9f8a566edb9b6908aef88348d1f7f28456901131/src/data-sources/likes.js#L1

**Comment by cvburgess** [comment]
I left some sample code on https://github.com/tgriesser/knex/issues/2787 - its a bit hacky but it shows how to make a SQL datasource using Knex

See: https://github.com/tgriesser/knex/issues/2787#issuecomment-417765925

**Comment by lorensr** [comment]
https://github.com/cvburgess/SQLDataSource/

**Comment by trevorblades** [comment]
There are a couple of good examples in here, and some more information about connecting a database [in our docs](https://www.apollographql.com/docs/tutorial/data-source/#connect-a-database). Closing this issue now!
