### ISSUE TITLE
Option like 'useQuerystring' in RequestPromise for RestDataSource

### ISSUE THREAD

**Issue by JesseZomer** [apollographql/apollo-server#1461]
The 'useQuerystring' option in RequestPromise allows me to send a query param array as follows: `&additional=test1&additional=test2`
```
useQuerystring - if true, use querystring to stringify and parse querystrings, otherwise use qs (default: false). Set this option to true if you need arrays to be serialized as foo=bar&foo=baz instead of the default foo[0]=bar&foo[1]=baz.
```
[source](https://github.com/request/request#requestoptions-callback)

When I try to use RestDataSource I can't seem to get the url right. Is there an option to make something like this;
```
this.get(`/rest/v1/test`, {
            additional: ['test1', 'test2', 'test3']
});
```
to come up with a url like: `http://localhost:8080/rest/v1/test?additional=test1&additional=test2&additional=test3` ?

**Comment by martijnwalraven** [comment]
Query parameter handling in `RESTDataSource` is based on the [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).

That offers various ways of constructing params. You could pass a query string for example:
```typescript
this.get(`/rest/v1/test`, new URLSearchParams('additional=test1&additional=test2&additional=test3'));
```

You can also pass in a sequence:
```typescript
this.get(`/rest/v1/test`, new URLSearchParams([['additional', 'test1'],['additional', 'test2'], ['additional', 'test3']]));
```

But I prefer constructing params programmatically. That would give you something like:
```typescript
const params = new URLSearchParams();
params.append('additional', 'test1');
params.append('additional', 'test2');
params.append('additional', 'test3');
this.get(`/rest/v1/test`, params);
```

Note that you don't have to set this per-request, you can also use the `willSendRequest` lifecycle method to modify every request:
```typescript
  willSendRequest(request: RequestOptions) {
    request.params.append('additional', 'test1');
    request.params.append('additional', 'test2');
    request.params.append('additional', 'test3');
  }
```

**Comment by JesseZomer** [comment]
Thank you. I'll try these methods.

**Comment by jamesonhill** [comment]
For anyone else still stumbling across this issue, this is how I solved @JesseZomer original issue.
`willSendRequest(request) {
    [...request.params.entries()].forEach(([key, value]) => {
      if (value.split(',').length > 1) {
        request.params.delete(key);

        value.split(',').forEach((val) => {
          request.params.append(key, val);
        });
      }
    });
  }`
