### ISSUE TITLE
Apollo-server-koa 2 working example of subscription needed.

### ISSUE THREAD

**Issue by tanekim77** [apollographql/apollo-server#1462]
I am having trouble getting Apollo-server-koa 2's subscription feature to work, but I cannot find any working example for Apollo-server-koa 2. I see some instructions here and there, but they do not seem to work. Only Apollo-server-koa 1 seems to have working Subscription example.

**Comment by kamilchm** [comment]
@tanekim77 did you find a way to setup subscriptions with apollo-server-koa?

**Comment by mthomasuk** [comment]
I'm also interested in this - worked fine for v1

**Comment by kamilchm** [comment]
This worked for me:
```javascript
const app = new Koa();
const httpServer = app.listen(app.port, () => console.log(`app is listening on port ${app.port}`));
const server = new ApolloServer({ typeDefs, resolvers });
server.applyMiddleware({ app });
server.installSubscriptionHandlers(httpServer);
```

**Comment by mthomasuk** [comment]
@kamilchm you rule 👍

**Comment by egucciar** [comment]
can this be added to docs somewhere?

**Comment by stevonjugush** [comment]
@kamilchm You saved me big time.

**Comment by darknesszy** [comment]
> 
> 
> This worked for me:
> 
> ```js
> const app = new Koa();
> const httpServer = app.listen(app.port, () => console.log(`app is listening on port ${app.port}`));
> const server = new ApolloServer({ typeDefs, resolvers });
> server.applyMiddleware({ app });
> server.installSubscriptionHandlers(httpServer);
> ```

This needs to go into the Documentation. It's been 2 yrs, I'd be completely helpless without this comment.
