### ISSUE TITLE
Mutation guide link missing

### ISSUE THREAD

**Issue by jimmymcpeter** [apollographql/apollo-server#1464]
Hi, I'm reading through the [Schema types](https://www.apollographql.com/docs/apollo-server/v2/schemas/types.html) and at the bottom of the `Mutation type` section, there is the sentence,

> To implement your first mutation, follow the … guide.

The ... hyperlink just links to the same page. Is there a Mutation guide hiding somewhere?

**Comment by justinanastos** [comment]
This file doesn't exist anymore :) The schema types docs have been revamped also https://www.apollographql.com/docs/apollo-server/essentials/schema#mutation. 

Thank you for the issue report @jimmymcpeter !
