### ISSUE TITLE
Apollo-Server-Koa 2 Subscription not working

### ISSUE THREAD

**Issue by tanekim88** [apollographql/apollo-server#1465]
I have repo setup just like in the documentation:
https://github.com/tanekim77/apollo-server-koa-2-subscription-not-working
Yarn start will start the server.
if I query 
"subscription{
  postAdded{
    author
  }
}"
it says "Could not connect to websocket endpoint ws://localhost:4000/graphql. Please check if the endpoint url is correct."
What am I doing wrong?
Thanks in advance

**Comment by wZi** [comment]
the same to me

**Comment by wZi** [comment]
+1
