### ISSUE TITLE
Broken link in the docs

### ISSUE THREAD

**Issue by mks11** [apollographql/apollo-server#1467]
On https://www.apollographql.com/docs/graphql-tools/
under "Hello world example"
"To get started with graphql-tools right away, run the example from the Apollo Server docs."

the example link is broken.

**Comment by hriziya** [comment]
This has already been fixed. 
Text under the "Hello world example" says
> To get started with `graphql-tools` right away, [see this complete live example in Apollo Launchpad](https://launchpad.graphql.com/1jzxrj179?_ga=2.66839528.716184338.1546971165-2135357220.1546971165)..

**Comment by hchuff** [comment]
Deleted the example as we have sunsetted Launchpad.
