### ISSUE TITLE
cannot disable apollo server gui in browser

### ISSUE THREAD

**Issue by monkingame** [apollographql/apollo-server#1472]
- [x ] feature

I cannot disable apollo server gui in browser.  

here codes:  
```
const { ApolloServer } = require('apollo-server-express');     
const schema = require('./graphql');      
const server = new ApolloServer({ schema });  
server.applyMiddleware({  
  app,  
  path: '/gql',  
  bodyParserConfig: bodyParser.json(),  
  gui: null,  
});
```

I donot want users to find my backgroud graphql list or he will use to hack/analyze my server.  
I config with {gui:null} but when access http://localhost:4000/gql,  the gui shows again.

How can I remove/disable the browser gui?  
(The purpose is to access apollo server only with get/post query string)

**Comment by monkingame** [comment]
Sorry ,please close the issue.   
I found the solution:   
https://www.apollographql.com/docs/apollo-server/features/graphql-playground.html

```
const server = new ApolloServer({
  schema, 
  introspection: false,
  playground: false,
});
```
will disable playground gui

**Comment by thisiskianoush** [comment]
To disable the Apollo GUI page or what they say: (Landing Page), you can use the [**ApolloServerPluginLandingPageDisabled**] plugin from **'@apollo/server/plugin/disabled'** and use it in the ApolloServer instance as a parameter:

`import { ApolloServer } from '@apollo/server';
import { ApolloServerPluginLandingPageDisabled } from '@apollo/server/plugin/disabled';

const server = new ApolloServer({
  typeDefs,
  resolvers,
  plugins: [ApolloServerPluginLandingPageDisabled()],
});`

**Comment by glasser** [comment]
Correct @thisiskianoush , the API has changed since 2018 and you have the approach from AS3/AS4.
