### ISSUE TITLE
Datasource Caching HTTP Errors

### ISSUE THREAD

**Issue by delianides** [apollographql/apollo-server#1481]
I'm using a services API and they don't have a `Cache-Control` header so I'm manually setting the TTL on each of the requests. They have a concurrent API limit of 5 so I get 429 errors if I use DataSourceREST to query more than 5 and the Redis cache will cache the error response and return that until the TTL expires. 

Is this expected behavior? any way to control the keys if the request isn't successful? 

cc: @martijnwalraven

**Comment by martijnwalraven** [comment]
This should be fixed in `apollo-datasource-rest` 0.1.4.
