### ISSUE TITLE
Is there a way to change the graphql endpoint name?

### ISSUE THREAD

**Issue by frederikhors** [apollographql/apollo-server#1485]
I'm using `apollo-server-hapi` with default configuration like the Readme's example.

Is there a way to change the `graphql` endpoint name?

**Comment by tux-tn** [comment]
You can pass a path parameter to applyMiddleware 
```javascript
const server = new ApolloServer({
  typeDefs,
  resolvers,
});

server.applyMiddleware({
  app, 
  path: '/api'
});
```
