### ISSUE TITLE
new Apolloserver(args) fails typescript validation

### ISSUE THREAD

**Issue by jfcieslak** [apollographql/apollo-server#1486]
`/label bug`

I am instantiating `apollo-server-express` to run it on firebase function (using typescript).
While the server with bellow config runs correctly, typescript is signaling error for `new ApolloServer({ typeDefs, resolvers })` – Expected 0 arguments, but got 1.

reproduction below:
```
import * as functions from 'firebase-functions'
import {ApolloServer, gql} from 'apollo-server-express'
import * as express from 'express'

// Construct a schema, using GraphQL schema language
const typeDefs = gql`
  type Query {
    hello: String
  }
`

// Provide resolver functions for your schema fields
const resolvers = {
	Query: {
		hello: () => 'Hello world!',
	},
};

const server = new ApolloServer({ typeDefs, resolvers })

const app = express()
server.applyMiddleware({ app })

export const api = functions.https.onRequest( app )
```

**Comment by jfcieslak** [comment]
false alarm, all fine after project was reloaded in vscode.

**Comment by debugferro** [comment]
I have the same problem 4 years later. Funny thing is that I already reloaded the editor, and the server works perfectly fine. Probably this problem is not related to Apollo.

**Comment by vbersano** [comment]
I'm still dealing with this problem, even after reloading the code editor. Has anyone found a fix?

**Comment by trevor-scheer** [comment]
@debugferro @vbersano this issue was opened in 2018 (and subsequently closed), and a lot has changed in the Apollo Server project since then. If you're facing an issue in the year of 2023 I'd welcome you to open a new one and please provide a reproduction so we can help you!
