### ISSUE TITLE
@defer directive not working with `apollo-server-koa`

### ISSUE THREAD

**Issue by rplute** [apollographql/apollo-server#1488]
First and foremost, I'm really excited for the `@defer` feature. Thank you! 

**Intended outcome:**

When using the alpha releases of `apollo-server` and `apollo-server-koa`, the @defer directive should work out of the box, per the documentation. 

**Actual outcome:**

It does not. Instead, I get the following error when adding `@defer` to a query:

```
ValidationError: Unknown directive "defer".
```

**How to reproduce the issue:**

These are my server-side dependencies:

```
"apollo-server": "^2.1.0-alpha.8"
"apollo-server-koa": "^2.1.0-alpha.8"
"graphql": "^14.0.0-rc.2"
"graphql-tag": "^2.9.1"
```

And my client-side dependencies:
```
"apollo-boost": "^0.2.0-alpha.13"
"react-apollo": "^2.2.0-alpha.1"
```

And what my query looks like with `@defer`:

```
const viewerQuery = gql`
  query viewer {
    viewer {
      name
      posts @defer {
        title
      }
    }
  }
```

I'm also just passing in an existing `schema` when constructing the Apollo Server, and not passing in `typeDefs` and `resolvers`.

**NOTE:** Setting `validationErrors` to null [here](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/runQuery.ts#L188) in `apollo-server-core` makes it all work, which is not ideal as validation no longer happens.

Once it starts to work with the above hack, however, the server logs an `Error: Cannot set headers after they are sent to the client`. This actually makes sense and am curious how to prevent this error? Do you need to configure sockets?

**UPDATE**: Just reading through the code and it looks like the @defer directive is added [here](https://github.com/apollographql/apollo-server/blob/0250b3007e74aee3c0c5e36ad4a2e6fcb513e7e3/packages/apollo-server-core/src/ApolloServer.ts#L175) to the schema, but only when `typeDefs` and `resolvers` are passed. If just an existing schema is passed, it doesn't look like the @defer directive is added. You can see that [here](https://github.com/apollographql/apollo-server/blob/0250b3007e74aee3c0c5e36ad4a2e6fcb513e7e3/packages/apollo-server-core/src/ApolloServer.ts#L160). Assuming this may be by design? @clarencenpy.

**Comment by rplute** [comment]
**UPDATE**: For my implementation, the work-around right now is to create the @defer directive manually and everything seems to work. This said, I still get the `Cannot set headers after they are sent to the client` error once the deferred requests are resolved.

`./directive.js` file:

```javascript
import {  
  DirectiveLocation,
  GraphQLDirective, 
  GraphQLBoolean
} from 'graphql'

export const GraphQLDeferDirective = new GraphQLDirective({
   // register the directive name
   name: 'defer',
   // register a description  
   description: 'Directs the executor to defer this field when the if argument is true.',
   // register where this directive can be used
   locations: [
     DirectiveLocation.FIELD,     
   ],
   // what arguments can we take, when its @defer it is `if`
   args: {
    if: {
      // we only accept boolean as a param
      type: GraphQLBoolean,
      description: "Deferred when true"
    } 
   }
})
```

And when creating the schema:

`./schema.js` file:

```javascript
import {
  GraphQLSchema,
} from 'graphql'

import { GraphQLDeferDirective } from './directives'

export default new GraphQLSchema({
  directives: [
    GraphQLDeferDirective,
  ],
  query,
  mutation
})
```

And what the server file may look like (wherever the Apollo Server is initiated):

`./server.js`

```javascript
import Koa from 'koa'
import { ApolloServer, gql } from 'apollo-server-koa'

import schema from './schema'

const app = new Koa()

const server = new ApolloServer({ 
  schema,
}) 

server.applyMiddleware({ app })

app.listen()
```

**Comment by clarencenpy** [comment]
Hi @rplute! Thanks for raising this issue! In the next alpha release, what do you feel about Apollo Server automatically adding `GraphQLDeferDirective` directly into the `schema` object you pass in? As you rightly pointed out, that is already being done when you pass in `typeDefs` and `resolvers`.

**Comment by clarencenpy** [comment]
> Once it starts to work with the above hack, however, the server logs an Error: Cannot set headers after they are sent to the client. This actually makes sense and am curious how to prevent this error? Do you need to configure sockets?

Could you share a repro, as I was not able to reproduce this issue. I'm not sure why it would be so, since the headers are set before sending the rest of the multipart chunks. You can see this [here](https://github.com/apollographql/apollo-server/blob/0250b3007e74aee3c0c5e36ad4a2e6fcb513e7e3/packages/apollo-server-koa/src/koaApollo.ts#L52).

**Comment by clarencenpy** [comment]
Hi @rplute, following up on the `Unknown directive "defer"` error you faced, the latest alpha release of  `apollo-server` or `apollo-server-koa` now declares the `@defer` directive for you by default.

**Comment by rplute** [comment]
Hi, @clarencenpy, sorry for the delayed response. And that's great news!! 

Re: "the cannot set headers error", I am curious if it's just my own Koa configurations that is causing the issue. I'll look into it more, but you can close this ticket and if I have good repro steps, I'll open another ticket.

Thanks again!
