### ISSUE TITLE
how to enable cors on hapi 17

### ISSUE THREAD

**Issue by kdong007** [apollographql/apollo-server#1493]
I have tried putting `cors:true` everywhere
```
{
        plugin: graphqlHapi,
        options: {
           // .....
            route:{cors:true}
            cors:true,
        },
        cors:true,
    },
```

But i'm still getting 
```
Failed to load http://localhost:8000/graphql: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by abernix** [comment]
The error message indicates that the `OPTIONS` request (a browser-initiated request that takes place prior to other HTTP methods (e.g. `GET`, `PUT`) is failing.

A brief investigation leads me to believe that you're not doing anything wrong but that the [`apollo-server-hapi/src/ApolloServer.ts`](https://github.com/apollographql/apollo-server/blob/9c563fae5048f5e77ca2716e3aa3d47044861abf/packages/apollo-server-hapi/src/ApolloServer.ts) is missing the bit that would make this happen!

For example, in Koa, we have:

https://github.com/apollographql/apollo-server/blob/4149a97d134f96be17a34b78e9e262cf35b49700/packages/apollo-server-koa/src/ApolloServer.ts#L174-L178

And in Lambda:

https://github.com/apollographql/apollo-server/blob/5b46e44451094c4daae3022f40347e234225a7de/packages/apollo-server-lambda/src/ApolloServer.ts#L152-L161

And in Express, where we lean on [`cors`](https://npm.im/cors):

https://github.com/apollographql/apollo-server/blob/4149a97d134f96be17a34b78e9e262cf35b49700/packages/apollo-server-express/src/ApolloServer.ts#L198-L204

That's all to say, PR very much welcome to fill this gap in functionality for Hapi!

**Comment by jbaxleyiii** [comment]
Thanks very much for reporting this! We think this is a great idea, and would definitely review a PR. If you (or anyone else) is interested in working on this, that would be great - thanks!
