### ISSUE TITLE
How to use it with express app like SailsJS (Sails)?

### ISSUE THREAD

**Issue by frederikhors** [apollographql/apollo-server#1503]
I don't understand how to use it with app like `SailsJS` (sails) (`Express` based).

In Readme (https://github.com/apollographql/apollo-server#express) I see that for an `Express` app I need to use:

```js
const server = new ApolloServer({ typeDefs, resolvers });
const app = express();
server.applyMiddleware({ app });
```

But **why**? And **how** in `SailsJS`?

Why we can't use this?

```js
let apollo = require('apollo-server').ApolloMiddleware
app.use( '/graphql', apollo({ typeDefs, resolvers }) );
```

I'm not the only one: https://stackoverflow.com/questions/51716013/why-isnt-apollo-server-a-middleware-for-express-rather-than-being-a-server-tha

**Comment by abhisheksoni27** [comment]
Any news on this?

**Comment by jbaxleyiii** [comment]
We won't be directly maintaining integrations with specific frameworks in Apollo Server 3, so closing this issue.
