### ISSUE TITLE
apollo-datasource-rest URL not defined

### ISSUE THREAD

**Issue by seanli3** [apollographql/apollo-server#1508]
Hi, I'm trying to wrap around existing REST endpoints with datasource-rest `2.0.0-rc.5`.

I got he following error
```
 "ReferenceError: URL is not defined",
node_modules/apollo-datasource-rest/src/RESTDataSource.ts:102:17)
```

I looked at line 102 of `RESTDataSource.ts` and it looks like URL has not been imported correctly from `apollo-server-env`.

And here is my code
```js
class IngestApi extends RESTDataSource {
  constructor() {
    super();
    this.baseURL = 'http://localhost/api';
  }

  async getDogs() {
    return this.get(`dogs`);
  }
}
```

I'm using babel7 with node 8.9.4

**Comment by sbrichardson** [comment]
did you try with a forward slash in front of `dogs`?

```js
async getDogs() {
  return this.get(`/dogs`);
}
```

**Comment by seanli3** [comment]
Hi @sbrichardson thanks for getting back.

I suspect it is Babel that is messing with the imports. I created a repo [here](https://github.com/seanli3/apoll-datasource-rest-bug-report) to reproduce the issue. 
Just run `yarn` to install dependencies and `yarn start`. Try to query `dogs` in the playground and you'll see the issue in the graphql request response.

**Comment by sbrichardson** [comment]
I fixed it and created a pull request

https://github.com/seanli3/apoll-datasource-rest-bug-report/pull/1

There were a few issues

1. Libraries were out of date, especially the rest package
2. Incorrect dataSources usage
3. Incorrect express usage with apollo-server

**Comment by sbrichardson** [comment]
This issue can be closed

**Comment by seanli3** [comment]
Thanks you very much @sbrichardson The PR did fix my issue. I didn't realize `0.1.1` is actually newer than `2.0.0-rc5`, it is a bit confusing.
