### ISSUE TITLE
No documentation on graphqlHapi and graphiqlHapi plugins from 'apollo-server-hapi'

### ISSUE THREAD

**Issue by wmlutz** [apollographql/apollo-server#1524]
I'm looking for some API ref documentation on options when registering graphqlHapi and graphiqlHapi. I'm trying to sort out some auth issues and can't find the api. Any help?

**Comment by wmlutz** [comment]
I'm now realizing that I am using the v1.0 of Apollo. (Based off of this [tutorial](https://medium.freecodecamp.org/how-to-setup-a-powerful-api-with-nodejs-graphql-mongodb-hapi-and-swagger-e251ac189649).) I'd like to fix my current issue - getting things stable and then worrying about migrating. Anyone have good documentation from v1.0? Specifically about how to use context?

**Comment by lokoArt** [comment]
@wmlutz  did you find anything related? I'm facing the same issue.

**Comment by wmlutz** [comment]
@lokoArt  - I ended up refactoring using hapijs' and apollo's current documentation. The tutorial is based off on an outdated version of the libraries and should be updated.

At the end of the day it's easier to use the current versions.
