### ISSUE TITLE
Shouldn't load apollo-upload-server if uploads are disabled

### ISSUE THREAD

**Issue by Akryum** [apollographql/apollo-server#1536]
If `uploads` option is false on `ApolloServer` constructor options, the `apollo-upload-server` module is still loaded. On some node versions, this causes issues like `core-js` not being found.

This would help close https://github.com/vuejs/vue-cli/issues/2215 (we don't need file uploads for vue cli ui).

**Comment by Akryum** [comment]
I believe https://github.com/jaydenseric/apollo-upload-server/releases/tag/v6.0.0-alpha.1 would fix the issue but it's still in alpha.

**Comment by yofriadi** [comment]
how to work around this ?
its blocking me

**Comment by yofriadi** [comment]
#1542

**Comment by abernix** [comment]
@Akryum It does seem wise to avoid loading `apollo-upload-server` if uploads are disabled, but I think the overall issue with `core-js` has been fixed now, as explained in https://github.com/apollographql/apollo-server/issues/1542#issuecomment-414641541.

Should we keep this open?  (I think a PR that conditionally `require`s `apollo-upload-server` would welcome, but it seems less urgent without the `core-js` issue at play.)

**Comment by martijnwalraven** [comment]
I actually [already did this](https://github.com/apollographql/apollo-server/commit/ef678519973f3eae5dbe5c6513d56bb4a0e06511) as part of a PR for running Apollo Server on edge. I'll pick that work up later, but I've just merged those commits to get this in and avoid the PR from getting out of sync.
