### ISSUE TITLE
playground: History and Headers aren't persisted

### ISSUE THREAD

**Issue by mwilliammyers** [apollographql/apollo-server#1549]
I am updated on all my dependencies:
```
├─┬ apollo-server-express@2.0.3
│ ├── @apollographql/graphql-playground-html@1.6.0
│ ├─┬ apollo-server-core@2.0.3
│ │ ├─┬ apollo-cache-control@0.2.2
│ │ │ ├── apollo-server-env@2.0.2 deduped
│ │ ├─┬ apollo-datasource@0.1.2
│ │ │ ├── apollo-server-caching@0.1.2 deduped
│ │ │ └── apollo-server-env@2.0.2 deduped
│ │ ├─┬ apollo-engine-reporting@0.0.2
│ │ │ ├─┬ apollo-engine-reporting-protobuf@0.0.1
│ │ │ ├── apollo-server-env@2.0.2 deduped
│ │ ├─┬ apollo-server-caching@0.1.2
│ │ ├─┬ apollo-server-env@2.0.2
│ │ ├── apollo-server-errors@2.0.2
│ │ ├─┬ apollo-tracing@0.2.2
│ │ │ ├── apollo-server-env@2.0.2 deduped
│ │ ├── apollo-upload-server@5.0.0 deduped
│ │ │ └── apollo-server-env@2.0.2 deduped
│ │ │ ├── apollo-link@1.2.2 deduped
│ │ │ ├── apollo-utilities@1.0.18 deduped
│ ├─┬ apollo-upload-server@5.0.0
│ │ ├── apollo-link@1.2.2 deduped
│ │ ├── apollo-utilities@1.0.18 deduped
│ ├─┬ apollo-link@1.2.2
│ │ ├── apollo-utilities@1.0.18 deduped
│ ├─┬ apollo-utilities@1.0.18
```

but I am still running into prisma/graphql-playground#317, and since there aren't any issues open on prisma's side after 1.3.10, it leads me to believe it is an issue with `apollo-server`/`apollo-server-express` or `@apollographql/graphql-playground-html@1.6.0` or `graphql-playground-html@1.6.0`?

I would love to be able to use the playground built in to `apollo-server-express` (and use 2.0 because it has some really awesome improvements!) so that I can use the `graphql` path for both my API and playground (and it is slightly easier than using playground as a separate package)...

**Comment by devtanc** [comment]
I'm seeing this issue as well. Every time I hit the route, I'm greeted with a fresh UI, rather than having any of my previously built queries/variables persisted.

**Comment by abernix** [comment]
We may not have been running the latest version of GraphQL Playground at that time, but we're currently completely up to date.  Please try the latest version of Apollo Server (v2.6.8, as of this writing) and if this problem persists, please open an issue on the [GraphQL Playground repository](https://github.com/prisma/graphql-playground/issues). Thanks!
