### ISSUE TITLE
Class constructor RESTDataSource cannot be invoked without 'new' using Babel

### ISSUE THREAD

**Issue by danlunde** [apollographql/apollo-server#1550]
Very similar in nature to https://github.com/apollographql/apollo-server/issues/1388, but I'm using Babel, not TypeScript

When using babel with `apollo-datasource-rest` I am getting the `Class constructor RESTDataSource cannot be invoked without 'new'`.  Here's a simplified version of my code.

```
// myapi.js
import { RESTDataSource } from "apollo-datasource-rest";

export default class extends RESTDataSource {
  constructor() {
    super();
    this.baseURL = "http://example.com";
  }

  hello() {
    return "Hello World!";
  }
}
```

```
// server.js
import express from "express";
import { ApolloServer } from "apollo-server-express";
import schema from "./data/schema";
import MyAPI from "./data/api/myapi";

const app = express();

const server = new ApolloServer({
  schema,
  dataSources: () => ({ MyAPI: new MyAPI() }),
});

server.applyMiddleware({ app, path: "/graphql" });

app.listen(8080, () => console.log(`Server is now running`));
```

```
// schema.js
import { makeExecutableSchema, gql } from "apollo-server-express";

const typeDefs = gql`
  type Query {
    hello: String
  }
`;

const resolvers = {
  Query: {
    hello: (_, __, { dataSources: { MyAPI } }) => MyAPI.hello(),
  },
};

const schema = makeExecutableSchema({ typeDefs, resolvers });

export default schema;
```

Is there any way that I can utilize `apollo-datasource-rest` with babel?

**Comment by sbrichardson** [comment]
Can you verify that you are using version 0.1.4 apollo-datasource-rest?

I saw this error when using an older version, and it was fixed by upgrading the package. If you are, I would delete the npm modules/reinstall etc to ensure it's not using the old version, just to confirm before diagnosing further.

https://github.com/seanli3/apoll-datasource-rest-bug-report/pull/1/files

**Comment by danlunde** [comment]
Yes, currently using version 0.1.4 of apollo-datasource-rest according to my yarn.lock file and I removed my node_modules folder and re-installed my packages just to be sure.  I am still getting the same error.

**Comment by sbrichardson** [comment]
No problem! Could this issue be closed?

**Comment by danlunde** [comment]
Yes, and thank you again!
