### ISSUE TITLE
[appllo-server-koa]resolver function can not get context 

### ISSUE THREAD

**Issue by limerickgds** [apollographql/apollo-server#1551]
Query: {
    user(root, { id }, ctx) {
      console.log(ctx);
    },
 }

ctx is ： 
![image](https://user-images.githubusercontent.com/9961514/44297942-90424f80-a30c-11e8-8064-ae91434e85dd.png)

not koa.context

**Comment by limerickgds** [comment]
@evans

**Comment by duckywang1** [comment]
Related to #1392 
// Please notice the following param -> 'context'
const server: ApolloServer = new ApolloServer({
    typeDefs: xx,
    resolvers: xx,
    context: ({ ctx }) => ctx, // this is the key part
});

**Comment by limerickgds** [comment]
@duckywang1 ths
