### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by rtalexk** [apollographql/apollo-server#1557]
I'm trying to make a Query where a type has an array of its own type.

This is part of the schema:

```
type Post {
    post_id: String
    resource_id: String
    comment: String
    parent_post: Post
    replies(limit: Int = 20, offset: Int = 0): [ Post ]
    created_at: String
    updated_at: String
}
```

As you can see, both `parent_post` and `replies` are the same type.

And this is my resolver:

```
{
  Query: {
    posts: (root, { resource_id, limit, offset }) => 
      Post.getByResourceId({ resource_id, limit, offset })
  },
  Post: {
    replies: ({ resource_id, post_id: parent_post_id }, { limit, offset }) => 
      Post.getByResourceId({ resource_id, parent_post_id, limit, offset })
  }
}
```

With that, I'm got the following error:

```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at prettyJSONStringify (/Users/user/Documents/Node Projects/service-forum/node/node_modules/apollo-server-core/dist/runHttpQuery.js:18:17)
    at Object.<anonymous> (/Users/user/Documents/Node Projects/service-forum/node/node_modules/apollo-server-core/dist/runHttpQuery.js:292:33)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/user/Documents/Node Projects/service-forum/node/node_modules/apollo-server-core/dist/runHttpQuery.js:4:58)
    at propagateAslWrapper (/Users/user/Documents/Node Projects/service-forum/node/node_modules/lib-cbt-async-listener/index.js:468:25)
    at /Users/user/Documents/Node Projects/service-forum/node/node_modules/lib-cbt-async-listener/glue.js:188:31
    at /Users/user/Documents/Node Projects/service-forum/node/node_modules/lib-cbt-async-listener/index.js:506:72
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I'm thinking that maybe is because both `posts` query and `replies` field calls the same method: `Post.getByResourceId`.

If I change the resolver to just return an empty array it works, that's because I'm thinking is the method call.

EDIT: doing some test I realized that is not because calling `Post.getByResourceId`. Now I have no idea why this is happening.

**Comment by arivera-tiempodev** [comment]
This is shameful, actually was my wrong. Method `Post.getByResourceId` returns an object with the following signature:

```
{
  items: [],
  paging: {},
  summary: {}
}
```

The query `posts` returns a type with that signature, but the `replies` field returns an array of posts and I was using the same method to resolve that field. Was my wrong. What I did was modify the `replies` field to return a type with the above signature and that solves my problem.

**Comment by rtalexk** [comment]
This is shameful, actually was my wrong. Method Post.getByResourceId returns an object with the following signature:

```
{
  items: [],
  paging: {},
  summary: {}
}
```

The query posts returns a type with that signature, but the replies field returns an array of posts and I was using the same method to resolve that field. Was my wrong. What I did was modify the replies field to return a type with the above signature and that solves my problem.
