### ISSUE TITLE
[Express] Event Emitter did not fired inside resolver

### ISSUE THREAD

**Issue by dhamanutd** [apollographql/apollo-server#1559]
NODE version: 9.11.x
Express version: 4.16.x
Apollo version: 2

Event Emitter not running inside resolver.

### Let me explain the long story

One of my mutation should be trigger an event emitter, i code it inside resolver, but i won't fire the event.

**Before** i had using event emitter, i did directly to send email using `nodemailer`, but it didn't work in anyway. I tried to log the process before nodemailer line and also after that. Seems it only log before the nodemailer line and after that it like skipped.

Then i think if i use eventemitter it will work. But still it didn't work either.
This is my resolver code:

```
Mutation: {
  updateStatusJournalDetails: async (root, params) => {
      const { id } = params;
      try {
        const updateStatus = await JournalDetail.update(params, {
          where: { id }
        });
        if (updateStatus > 0) {
          const result = await JournalDetail.findOne({
            where: { id },
            include: {
              model: Employee,
              include: { model: User },
              attributes: ['id', 'user_id']
            }
          });

          const withdrawDate = new Date(result.created_at);
          await sendMail({
            userId: result.employee.user.id,
            userEmail: result.employee.user.email,
            employeeId: result.employee.id,
            withdrawId: result.id,
            withdrawNet: result.total_nett,
            withdrawCreated: `${withdrawDate.getFullYear()}-${(
              '0' +
              (withdrawDate.getMonth() + 1)
            ).slice(-2)}-${withdrawDate.getDate()}`
          });

          return result;
        }
        throw new Error(`Error update status team with id ${id}`);
      } catch (error) {
        dbError(error);
      }
    }
  }

const sendMail = data => {
  observe.emit(EVENT.WITHDRAW_REJECTED, {
    userId: data.userId,
    userEmail: data.userEmail,
    employeeId: data.employeeId,
    withdrawId: data.withdrawId,
    withdrawNet: data.withdrawNet,
    withdrawCreated: data.withdrawCreated
  });
  return true;
};
```

I'm new in apollo graphql. This problem really disturbing my work.

**Comment by captDaylight** [comment]
Is this all the code? Where is observe defined?

**Comment by dhamanutd** [comment]
Sorry it's too long to answer, since they have already changed in my working apps(not using graphql for specific task like send email and send notification), i tried to copy some old codes, but it's all the same end like my issue post.

```
// emitter/member-late.js
class MemberLatePresence {
  constructor(observable) {
    this.observable = observable;
  }

  listenMemberLate() {
    this.observable.addListener(EVENT.MEMBER_LATE_PRESENCE, async data => {
        //process here
    }
}

module.exports = MemberLatePresence;
```
```
// emitter/index.js
let observe = new EventEmitter();

const events = {
  MemberLatePresence: new MemberLatePresence(observe)
}

module.exports = { observe, events };
```
```
// app.js -> event listener registered here
events.MemberLatePresence.listenMemberLate();
```
```
// presence.resolver.js
// here the trigger
Mutation: {
    insertPresence: async (root, params) => {
      // insert process...
      try {
            observe.emit(EVENT.MEMBER_LATE_PRESENCE, {
                userId: user_id,
                companyId: employeeData.company.id,
                presenceDate,
                presenceOverdue: presence_overdue
            });
      }
      // catch...
}
```

**Comment by jbaxleyiii** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
