### ISSUE TITLE
Key order of input parameters is not preserved

### ISSUE THREAD

**Issue by sirianni** [apollographql/apollo-server#1564]
With an input graphql query such as:
```
foo(param1: {
  field1: value1
  field2: value2
})
```

The ordering of the keys in `param1` are not preserved when my GraphQL resolver is invoked.  In particular
```
Object.keys(param1)
```
yields
```
[ 'field2', 'field1' ]
```

I realize that JSON and GraphQL do not treat keys as ordered.  However, this is [strongly encouraged](http://facebook.github.io/graphql/draft/#sec-Serialized-Map-Ordering) by the GraphQL spec for Response data and it would be helpful to apply the same logic to request params.

**Comment by zionts** [comment]
Hi @sirianni, can you provide a reproduction of the issue? I definitely agree that the order of keys for input arguments should be preserved.

**Comment by jbaxleyiii** [comment]
Thanks very much for reporting this! We think this is a great idea, and would definitely review a PR. If you (or anyone else) is interested in working on this, that would be great - thanks!
