### ISSUE TITLE
In production with apollo-server-express 2.0.4 Playground is visible, with 2.0.0 is not.

### ISSUE THREAD

**Issue by frederikhors** [apollographql/apollo-server#1571]
### REPRODUCTION HERE: https://brainy-spaghetti.glitch.me

With `"apollo-server-express": "2.0.4"` and `NODE_ENV=production` the Playground is visible.

With `"apollo-server-express": "2.0.0"` and `NODE_ENV=production` I have this: `GET query missing`.

Something is wrong?

**Comment by frederikhors** [comment]
cc @nderscore @evans

**Comment by nderscore** [comment]
The default behavior of apollo-server's integrated graphql-playground is for it to be disabled (along with introspection queries) when `NODE_ENV=production`.

This behavior can be over-ridden when you set the `playground` option in config.

In 2.0.0, the graphql playground could be enabled when `NODE_ENV=production` if you explicitly set the `playground` option to `true`, but provided no way to enable the playground with a custom config object.

[In 2.0.2, this was adjusted to allow a custom config to enable the playground in production](https://github.com/apollographql/apollo-server/blob/master/CHANGELOG.md#v202). Now, a truthy value will enable the playground, while a falsey value will disable it. 

------

If you want to disable the `playground` in production while using a custom config in your local/development environment, you could do something like this:

```js
const GRAPHQL_PLAYGROUND_CONFIG = {
  folderName: 'Foo',
  settings: {
    'editor.cursorShape': 'line',
    'editor.fontSize': 14,
    'editor.reuseHeaders': true,
    'editor.theme': 'dark'
  }
};

const server = new ApolloServer({
  playground: process.env.NODE_ENV === 'production' ? false : GRAPHQL_PLAYGROUND_CONFIG,
  schema: mySchema
});
```

**Comment by frederikhors** [comment]
I'm not using any custom config as you can see. I think it is bad if playground is enabled by default in production. Isn't it?

**Comment by frederikhors** [comment]
@nderscore I'm sorry, I think glitch doesn't show the value of .env file keys to the public internet.

It is `NODE_ENV=production`, I can assure this to you. In fact it doesn't work the introspection.

Can you try on your PC downloading the file from glitch?

**Comment by nderscore** [comment]
Confirmed the issue. Sorry for the confusion.

https://github.com/apollographql/apollo-server/blob/412be208c1b60c2f77333eec2840b64990ea7935/packages/apollo-server-core/src/playground.ts#L39

It's likely due to the default value of `{}` for the playground config here.

**Comment by frederikhors** [comment]
Is there a test for this?

**Comment by kachkaev** [comment]
@tsvetann `playground: null` disables playground in development as well. My workaround:

```js
const server = new ApolloServer({
  typeDefs,
  resolvers,
  playground: process.env.NODE_ENV !== "production",
});
```

**Comment by abernix** [comment]
I believe this is resolved, but I realize it's been quite some time since you opened this, so if you haven't already figured this out, I'd recommend taking this question to the [Apollo community on Spectrum.chat](https://spectrum.chat/apollo) to discuss it further.  Feel free to comment here as well! Thanks!
