### ISSUE TITLE
[apollo-server-core] clarify toApolloError use cases

### ISSUE THREAD

**Issue by otbe** [apollographql/apollo-server#1576]
Hi,

in my application I have several custom exceptions that get thrown by services. When I connect these services to my graphql implementation I want to map these exceptions to `ApolloError`s. A basic example would be:

```typescript
try {
  await service.getUser('1');
} catch(e) {
  if(e instanceof UserNotFoundException) {
    throw new ApolloError('user not found', 'USER_NOT_FOUND', {userId: e.userId})
  }
}
```
Note: this is just an example, in my application exceptions will be mapped differently.

This works fine so far, but I lose the stacktrace from `UserNotFoundException`. I recently discovered `toApolloError` which is exported from `apollo-server-core`.  The example above would look like this

```typescript
try {
  await service.getUser('1');
} catch(e) {
  if(e instanceof UserNotFoundException) {
    throw toApolloError('USER_NOT_FOUND', e);
  }
}
```
This works fine and in this way I keep my stacktraces, but If I look at the current implementation of `toApolloError` it does not return an instance of `ApolloError` and the types say `Error & { extensions: Record<string, any> }` too. But it is sucessfully recognized by apollo-server as an `ApolloError`

So my questions are: 
Is this a valid use case for `toApolloError` ?
Is there an easier way to achieve the same results?

Thanks 👍

**Comment by mshwery** [comment]
I believe the current type signature for `toApolloError` would have those properties switched – 
```js
try {
  throw new Error('whatever')
} catch (error) {
  throw toApolloError(error, 'SOME_CODE') 
}
```

`toApolloError` will keep your existing error object (including stacktrace, etc) and enrich it with a `extensions.code` path: 
https://github.com/apollographql/apollo-server/blob/ae9da10e625cf283568ba6d29cea8c3e69a7a03f/packages/apollo-server-errors/src/index.ts#L108-L112

**Comment by otbe** [comment]
Mh, super strange. It seems to work now. Thanks for your feedback!

**Comment by the-vampiire** [comment]
@mshwery can you point me to where in the code it determines that the enriched object is treated as an ApolloError? i cant see where `toApolloError` is used anywhere besides in the package exports
