### ISSUE TITLE
Schema Stitching and workaround for Root Type (_: Boolean)

### ISSUE THREAD

**Issue by frederikhors** [apollographql/apollo-server#1577]
I'm starting to use Schema Stitching with Apollo Server.

I'm using a file like this:

_rootTypes.js:_

```js
const { gql } = require('apollo-server')

const UserType = require('./user')

const RootType = gql`
  type Query {
    _: Boolean
  }

  type Mutation {
    _: Boolean
  }
`

module.exports = [RootType, UserType]
```

and a _types/user.js:_

```js
const { gql } = require('apollo-server')

const type = gql`
  extend type Query {
    me: User
  }

  type User {
    id: ID!
    email: String!
  }
`

module.exports = type
```

Is there a way to avoid the use of: `_: Boolean` for the Root Type?

It is not elegant and I think error prone.

Is there a way to extend without using it?

**Comment by jasonpaulos** [comment]
Hi @frederikhors, thanks for reporting this issue originally. Schema stitching is now deprecated in favor of federation, which you can learn more about here: https://www.apollographql.com/docs/apollo-server/federation/migrating-from-stitching/

Federation is a much more natural way for schemas to work together, which does not involve any dummy root types. Please reach out to the _Apollo Federation_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) if you have any further questions. Thanks!
