### ISSUE TITLE
Customise GraphQL query validation (graphql/validation specifiedRules)

### ISSUE THREAD

**Issue by elnygren** [apollographql/apollo-server#1580]
I'd like to be able to customise GraphQL's query validation by customising the `specifiedRules` given to `validate` (see: https://github.com/graphql/graphql-js/blob/046400602f871b2c89ac7f63a1382f6f99e5c69f/src/validation/specifiedRules.js#L96 and https://github.com/graphql/graphql-js/blob/046400602f871b2c89ac7f63a1382f6f99e5c69f/src/validation/validate.js#L40)

It seems that `apollo-server-core` is hardcoding the `specifiedRules` in with the ability to pass additional validators: https://github.com/apollographql/apollo-server/blob/2657e9b25bc0d22336ce2b3b06784325830da6df/packages/apollo-server-core/src/runQuery.ts#L181

**Why would I like to customise GraphQL's validation?**

I'm getting errors from mobile clients about unused fragments (`NoUnusedFragments`) due to lazy frontend coding. Then I upgraded Apollo Server and GraphQL at some point and now my perfectly working queries are not passing validation anymore...

Other people might have other requirements why to customise or override the validation.

The official GraphQL JS implementation allows customising it easily by passing `specifiedRules` as a param to validate.

**Proposed solution**

Add `specifiedRules` array with the right type type from `graphql` into `interface GraphQLServerOptions` in https://github.com/apollographql/apollo-server/blob/2657e9b25bc0d22336ce2b3b06784325830da6df/packages/apollo-server-core/src/graphqlOptions.ts#L25 and some minor changes to `runQuery.ts`

I was trying to get a PR done but ran into some issues outlined at https://github.com/apollographql/apollo-server/issues/1575

Cheers!

**Comment by ganeshcse2991** [comment]
I have created an [npm module](https://www.npmjs.com/package/validate-graphql) for handling validations in GraphQL in a better way. Please check the [validate-graphql ](https://www.npmjs.com/package/validate-graphql)npm package.

**Comment by circlle** [comment]
Same issue here.

It's there any plan for this feature??

**Comment by glasser** [comment]
I think it's safe to say we don't plan to add a feature to let you easily spec-defined GraphQL validation rules when running operations. Note that `graphql-js`'s execution code generally assumes that it is executing a valid operation, so removing rules would make it too easy to introduce security issues into your server.
