### ISSUE TITLE
Micro server not handling Network errors

### ISSUE THREAD

**Issue by glenarama** [apollographql/apollo-server#1581]
**Updated below to issue with micro server *

When a mutation error occurs a JSON reponse with an error object is returned - the client can parse and handle this.
{data: {requestToken: null},errors: [{message: "Unknown User"}]

However, when a schema error or request error occurs, I get a string response which cannot be parsed client side. 
HttpQueryError: {"errors":[{"message":"Variable.....}

This is using apollo-server-micro how should I catch these errors and provide a graceful message back to the client which could aide in debugging?

- [X] has-reproduction

**Comment by glenarama** [comment]
When I use a vanilla apollo-server, my client recieves query errors (as documented) in the following manner: 

[GraphQL error]: Message: Schema is not configured for mutations.
[Network error]: Error: Response not successful: Received status code 400

When using Micro server, instead of the two errors, a string is returned and is not understood by Apollo Client: 
HttpQueryError: {"errors":[{"message":"Variable.....}

To reproduce this - use the micro example and send an incorrect request.

**Comment by DriesVandermeulen** [comment]
Had the same problem. 
Going through the source code I suspect the problem is in the top level micro error handling and supsquent response.

```javascript
} catch (error) {
    if ('HttpQueryError' === error.name && error.headers) {
        setHeaders(res, error.headers);
    }

    if (!error.statusCode) {
        error.statusCode = 500;
    }

    throw error;
}
```

Instead of throwing an error, we should return the result of the message. The message contains the correct json to be return as the response body.

```javascript
} catch (error) {
    if ('HttpQueryError' === error.name && error.headers) {
        setHeaders(res, error.headers);
    }

    if (!error.statusCode) {
        error.statusCode = 500;
    }

    send(res, error.statusCode, error.message);
}
```
