### ISSUE TITLE
RESTDataSource - Enable support voor ssl options for fetch

### ISSUE THREAD

**Issue by pietervandereems** [apollographql/apollo-server#1596]
The server we connect to with our graphql backend only supports TLS. For normal requests we add the following options to the request: 
{
   secureProtocol: 'TLSv1_2_method',
    securityOptions: 'SSL_OP_NO_SSLv3',
    requestOCSP: false,
    ecdhCurve: 'auto'
}

When using RESTDatasource these options are added as the third parameter to the .get request but we still get an error 

--
message: 'request to https://<SERVER URI> , reason: write EPROTO 139773434263360:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:\n',
  locations: [ { line: 2, column: 3 } ],
  path: [ '<PATH>' ],
  extensions: 
   { code: 'INTERNAL_SERVER_ERROR',
     exception: 
      { message: 'request to <SERVER URI> failed, reason: write EPROTO 139773434263360:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:\n',
        type: 'system',
        errno: 'EPROTO',
        code: 'EPROTO',
        stacktrace: [Array] } } } { context: '<CONTEXT>' }
--

It seems that sslv3 is used.

**Comment by abernix** [comment]
You should be able to configure all the options related to `node-fetch` by passing the third positional parameter argument to `get`.  That parameter is passed to `node-fetch` as its _options_ ([which are documented here](https://github.com/bitinn/node-fetch#options)), and includes an `agent` attribute which can be set to a [Node.js `https.Agent`](https://nodejs.org/api/https.html#https_class_https_agent), which should provide the maximum permitted Node.js configuration at the most core level possible.

That said, I wouldn't be surprised if you were affected by https://github.com/nodejs/node/issues/16196, which I believe was a bug in the Node.js 8 series that is now resolved (in recent Node.js v8 releases, at least).
