### ISSUE TITLE
Guide to integrate with connect middleware has bit mistake at using qs middleware

### ISSUE THREAD

**Issue by xshadowlegendx** [apollographql/apollo-server#1598]
- [x] docs

The guide on how to integrate with ``connect`` middleware has bit mistake where it should be:

    // the correct one

    const app = connect();
    app.use(query());

Instead of:

    // the mistake one

    const server = new ApolloServer({ typeDefs, resolvers });
    const app = connect();

    server.use(query());

**Comment by jasonpaulos** [comment]
Hi @xshadowlegendx, thanks for originally reporting this issue! This has been fixed by #1973, so I will now close this.
