### ISSUE TITLE
Add `graphql-middleware` support

### ISSUE THREAD

**Issue by maticzav** [apollographql/apollo-server#1603]
Add out of the box support for GraphQL Middleware plugins. 

http://github.com/prismagraphql/graphql-middleware

**Comment by notrab** [comment]
@maticzav do you have an example of the "workaround" for this?

**Comment by notrab** [comment]
Awesome thanks @maticzav - it's been a while since I looked at graphql-middleware. Great to see it's taking shape!

**Comment by maticzav** [comment]
Hey @Alvyre 👋 

Since we still haven't implemented this, you could use the alternative approach we mentioned above. Instead of supplying `resolvers` and `typeDefs` to `server` directly you can provide a schema that you build upfront. Something like this;

```ts
const schema = makeExecutableSchema({ typeDefs, resolvers })

const schemaWithMiddleware = applyMiddleware(
  schema,
  metricsMiddleware,
  authMiddleware,
  beepMiddleware,
)

const server = new ApolloServer({
  mocks: false,
  schema: schemaWithMiddleware,,
});
```

You can find even more information about it in the link below. I hope this helps you solve the problem; I will try to make a PR by the end of the week 🤞 

https://github.com/prisma/graphql-middleware#standalone-usage

**Comment by Alvyre** [comment]
Thank you for you reply and for the example. It works!

I'm waiting for your PR :+1: 

Thank you for your work by the way!

**Comment by martijnwalraven** [comment]
Closing this, see https://github.com/apollographql/apollo-server/pull/1799#issuecomment-448545801.

**Comment by chavakane** [comment]
I am having an issue with makeExecutableSchema, where I get "Error: Unknown directive "@cacheControl". This is a built in directive from apollo.

**Comment by maticzav** [comment]
Check this out https://twitter.com/maticzav/status/1418221177877663758 😎

**Comment by glasser** [comment]
Link doesn't work for me.
