### ISSUE TITLE
Add nesting validation feature

### ISSUE THREAD

**Issue by borisowsky** [apollographql/apollo-server#1612]
- [x] feature

What do you think about adding query depth validator in `apollo-server` library. It's common problem, it has few third-party solutions (e.g. [graphql-depth-limit](https://github.com/stems/graphql-depth-limit), [graphql-cost-analysis](https://github.com/pa-bru/graphql-cost-analysis)), but isn't clear from the beginning. How do you think, what approach should be most useful and/or more GraphQL-friendly way: somehow limit query cost or limit query depth or something else?

**Comment by hwillson** [comment]
Thanks for suggesting this feature. Integrating this into the AS core isn't something we're considering at this time. Using one of the third party solutions should help for now. If you're looking for a query restriction approach that is a little more all encompassing, you might want to consider [Apollo Platform's operation safe listing feature](https://www.apollographql.com/docs/platform/operation-registry/). Thanks!
