### ISSUE TITLE
Toggle to remove errors from traces sent to Engine Servers

### ISSUE THREAD

**Issue by evans** [apollographql/apollo-server#1613]
We need the ability to prevent error messages and locations from being sent to the Engine Servers.

This is a feature in the [engine proxy](https://www.apollographql.com/docs/engine/data-privacy.html#response), so I would consider the lack of toggle to be a regression. 

The [documentation](https://www.apollographql.com/docs/apollo-server/api/apollo-server#EngineReportingOptions) for `reportErrorFunction` doesn't quite seem clear due to the overloading of error, representing reported errors in traces and those that occur when sending a trace to the engine backend.

**Comment by daniman** [comment]
Please update this article in the Engine docs when disabling error reporting becomes available: https://www.apollographql.com/docs/engine/data-privacy.html.
