### ISSUE TITLE
Handling of nonexistent resovlers

### ISSUE THREAD

**Issue by RuBAN-GT** [apollographql/apollo-server#1622]
- [x] feature

For example, I have the next schema:

```graphql
type User {
  email: String!
}

type Query {
  users: [User]
}
```

Client request:

```graphql
query MyQuery {
  users{
    email
  }
}
```

If the apollo-server hasn't got `users` resolver, I want to call my custom univeral callback for all queries where I can try to return data from external system. It's possible? 
Or can I build top-level middleware for handling all resolvers before calling them?

**Comment by trevor-scheer** [comment]
@RuBAN-GT, thanks for submitting an issue. This option is already exposed via `ApolloServer`, see:https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/types.ts#L61
