### ISSUE TITLE
[RESTDataSource] Unable to run tests with Jest

### ISSUE THREAD

**Issue by melkir** [apollographql/apollo-server#1628]
Whenever I'm trying to run a test using a class that extends RESTDataSource and call the `this.get(...)` method, I have the following error `TypeError: Cannot read property 'fetch' of undefined`
The thing is I want to test the real output of the request, so mocking the fetch method doesn't seems to be an appropriate solution. 

Some related files are:
https://github.com/apollographql/apollo-server/blob/master/__mocks__/apollo-server-env.ts
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/HTTPCache.ts#L11

How can I get ride of this error ? Is there any example that could show me how test a rest data source ?

**Comment by Borales** [comment]
@melkir try to call it like

```
const gApi = new GoogleAPI() ;
gApi.initialize({ context:{} }):

// your tests go below 
gApi.getGroups();

```

**Comment by melkir** [comment]
Thank you @Borales ! Everything work as expected !!
Typescript is complaining
```
[ts]
Argument of type '{ context: {}; }' is not assignable to parameter of type 'DataSourceConfig<any>'.
  Property 'cache' is missing in type '{ context: {}; }'.
```
but I can ignore this warning using `@ts-ignore`

**Comment by captDaylight** [comment]
@melkir can you close this if you figured it out?

**Comment by veeramarni** [comment]
@melkir 

You can just set the second param as `undefined`

```
gApi.initialize({ context:{} }, undefined):
```

**Comment by iamam34** [comment]
I had the same issue. This line makes it compile with no typescript warnings: 
```
import { KeyValueCache } from 'apollo-server-caching';
...
gApi.initialize({ context:{ }, cache: {} as KeyValueCache });
```

**Comment by reywright** [comment]
@melkir how are you mocking the actual request?

**Comment by reywright** [comment]
@melkir would you know how to mock the fetch method in this instance?

**Comment by timReynolds** [comment]
So far the best way I've done this is mocking RESTDataSource like so;

```js
jest.mock('apollo-datasource-rest', () => {
  class MockRESTDataSource {
    baseUrl = '';
    get = getMock;
  }

  return {
    RESTDataSource: MockRESTDataSource,
  };
});

const getMock = jest.fn();
```

Originally posted [here](https://spectrum.chat/apollo/testing/apollo-datasource-rest-typescript-jest~d7e88d14-d8e8-4ff7-a95d-b2fba993388e)
