### ISSUE TITLE
Apollo Server Micro has `graphqlPath` set to "/graphql" instead of "/"

### ISSUE THREAD

**Issue by brikou** [apollographql/apollo-server#1630]
In order to be consistent with other servers (like express) default graphqlPath should be set to "/" and `subscriptionsPath` as no default value (should be the same as express).

**Issue Labels**

- [ ] has-reproduction
- [ ] feature
- [ ] docs
- [ ] blocking
- [x] good first issue

**Comment by captDaylight** [comment]
It looks like both [express](https://github.com/apollographql/apollo-server/blob/e49e17295f758893dd34ecd88346ba8f4e298ce8/packages/apollo-server-express/src/ApolloServer.ts#L95) and [micro](https://github.com/apollographql/apollo-server/blob/e49e17295f758893dd34ecd88346ba8f4e298ce8/packages/apollo-server-micro/src/ApolloServer.ts#L34) set the path to `/graphql` if it's not set elsewhere.

**Comment by abernix** [comment]
As noted above, I do believe the functionality in `micro` is identical to that of Express, Koa, Fastify, and likely all the others.  If it's not set, it defaults to `/graphql`:

https://github.com/apollographql/apollo-server/blob/bcabbb7785d966a85e3df41240d0411aa694e16e/packages/apollo-server-micro/src/ApolloServer.ts#L38

**Comment by abernix** [comment]
Hmm, perhaps I've misspoke here and this is specifically referring to subscriptions?  A more clear explanation would be really appreciated here, and I'm happy to re-open if it's still a problem.

**Comment by abernix** [comment]
If this is specific to subscriptions across all integrations, let's track this in #1638?
