### ISSUE TITLE
ID cannot represent value: {_bsontype: \"ObjectID\" I get this error when I want to get a response 

### ISSUE THREAD

**Issue by lagmanzaza** [apollographql/apollo-server#1633]

**Comment by sachithkadamba** [comment]
Even I am getting same error

**Comment by lagmanzaza** [comment]
I found a solution, you must convert _id to String by using .toString() before return it

**Comment by sachithkadamba** [comment]
@lagmanzaza at many places I am returning entire object returned by mongoose. How to do it in generic way?

**Comment by lagmanzaza** [comment]
I'm not sure. I alter those object then I convert _id from ObjectId() to string by using .toString() instead. It does work.

**Comment by Lanfei** [comment]
GraphQL have used [a new method](https://github.com/graphql/graphql-js/commit/3521e1429eec7eabeee4da65c93306b51308727b#diff-87c5e74dd1f7d923143e0eee611f598eR183) to serialize ID, the new method doesn't support ID in object type anymore, but following codes will help on this:

```js
ObjectId.prototype.valueOf = function () {
	return this.toString();
};
```

**Comment by kgroat** [comment]
You can also create a scalar type, as shown here: https://github.com/apollographql/apollo-server/issues/1649#issuecomment-420840287

**Comment by williamli** [comment]
@Lanfei how can i use what you proposed to get ID working again on a 3rd party package?

```
ObjectId.prototype.valueOf = function () {
	return this.toString();
};
```

**Comment by Lanfei** [comment]
@williamli Which package? `mongoose`?

**Comment by phao5814** [comment]
@Lanfei I tried this by including the following and the result is that I get [object Object] in the id field.

```
const { ObjectId } = mongoose.Types;
ObjectId.prototype.valueOf = () => {
	return this.toString();
};
```

![image](https://user-images.githubusercontent.com/23574714/46254278-ff948d00-c4cf-11e8-8318-b8b94444ed4b.png)

**Comment by kgroat** [comment]
@phao5814 that's because inside of a lambda function (one denoted by `() =>`) the `this` reference is copied from the outer closure scope.  If you define it in the root scope, `this` ends up being the same as the [global scope](https://www.w3schools.com/js/js_scope.asp), i.e. `process` in node or `window` in the browser.

If you want this to work you need to say:
```
const { ObjectId } = mongoose.Types;
ObjectId.prototype.valueOf = function () {
  return this.toString()
}
```

**Comment by davae1an** [comment]
```
TheSchema.virtual('id').get(function () {
  return this._id.toString();
});

```

**Comment by vctormb** [comment]
@davae1an great solution!

**Comment by arvi** [comment]
@williamli ,

I tried your example but still getting same error. Where do you put this code snippet? :sweat_smile: Thanks.

**Comment by phao5814** [comment]
@arvi  I placed that snippet of code above my schema definitions.

```
// ... Some more imports here...
const {
	GraphQLObjectType,
	GraphQLID,
	GraphQLString,
	GraphQLSchema,
	GraphQLInt,
	GraphQLList,
	GraphQLFloat,
	GraphQLBoolean,
} = graphql;

const { GraphQLDateTime } = graphqlDateTime;

const { ObjectId } = mongoose.Types;
ObjectId.prototype.valueOf = function () {
	return this.toString();
};

const ImageType = new GraphQLObjectType({
	name: "Image",
	fields: () => ({
		...
	}),
});

// ... Some more definitions here
```

**Comment by arvi** [comment]
@phao5814, thank you so much for the hint :smile: 

I put it just before the apollo server and it worked finally.

```js
const { ObjectId } = mongoose.Types;
ObjectId.prototype.valueOf = function () {
  return this.toString();
};

const apolloServer = new ApolloServer({
  typeDefs,
  resolvers,
  context: ({ req }) => ({
    SECRET: config.secret,
  }),
  formatError(error) {
    return {
      message: error.message,
      code: error.originalError && error.originalError.code,
      locations: error.locations,
      path: error.path,
    };
  },
});

apolloServer.applyMiddleware({ app, path: '/graphql' });
app.use('/graphql', () => {});
```

**Comment by fireydude** [comment]
I think that it is better to put the `toString()` inside of the _spread operator_.  This would allow anyone who reads the code to know what is happening.

For an `event` model in Mongoose:
```
            return event
                .save()
                .then(r => {
                    console.log('mongo event saved', r._doc);
                    return { ...r._doc, _id: event._doc._id.toString() };
                })
                .catch(err => {
                    console.error(err);
                    throw err;
                });
```
This is less _generic_ but more readable.

**Comment by enriqueao** [comment]
i'm solved the error with `toString()` i put the `toString()` inside of the schema definition 

```javascript
addMarket: (root, { marketName, marketLogo }) => {
            return new Promise((resolve, reject) => {
                const newMarket = new Market({
                    id: (new mongoose.Types.ObjectId()).toString(),
                    marketName,
                    marketLogo,
                });
                newMarket.save((err, res) => {
                    err ? reject(err) : resolve(res);
                });
            });
        }
```

**Comment by acidoxee** [comment]
I'm going to ask the same question than on #1649:

Has this problem been fixed in the meantime?
 
We used to do stuff like `id: obj => obj._id.toHexString()` in all our resolvers that handled MongoDB ObjectIds, but now it seems `id: obj => obj._id` alone is working perfectly fine.

**Comment by EmiyaYang** [comment]
I get  trapped in this error while populate, and the solutions above can't work for me.

**Comment by Karem1986** [comment]
> Just create a virtual attribute ID convert it to string to be parse by the graphql server
> 
> Put this below in your schema file and just query for 'id'
> 
> ```
> TheSchema.virtual('id').get(function () {
>   return this._id.toString();
> });
> ```

Where exactly in the schema file? please let me know :)
