### ISSUE TITLE
Subscriptions default path

### ISSUE THREAD

**Issue by lekterable** [apollographql/apollo-server#1638]
Hey guys, is there any reason why default path for graphql is '/' and for subscriptions it is '/graphql'?
It seems pretty inconsistent to me.
This might not look like a big deal but for example sending subscriptions with GraphQL Playground wouldn't work untill I've changed the subscriptions path manually to '/' because it was detecting the graphql running on path  '/' .

**Comment by lekterable** [comment]
@captDaylight yeah that's true, I thought that micro is a separate module.

**Comment by captDaylight** [comment]
Ya it is, I was looking at it though and after a quick glance it looks [like express's path](https://github.com/apollographql/apollo-server/blob/e49e17295f758893dd34ecd88346ba8f4e298ce8/packages/apollo-server-express/src/ApolloServer.ts#L95) is set to `/graphql`.

**Comment by dylanbhughes** [comment]
We were also just having problems with this, +1

**Comment by glasser** [comment]
Integrated subscription support was removed from Apollo Server last year in v3.
Path parsing will be removed from Apollo Server shortly in v4 (currently a Release Candidate).
