### ISSUE TITLE
Apollo Network Request Failed With Status 405

### ISSUE THREAD

**Issue by personapp** [apollographql/apollo-server#1642]
Thank you for your excellent package "apollo-server-lambda".

I tried to use "apollo-server-lambda@2.0.6" to create a graphql server with node.js and deploy it as a lambda function to AWS.

My server’s code was with and without cors like that:

```
const { ApolloServer } = require("apollo-server-lambda");

const typeDefs = require("./data/schema");

const resolvers = require("./data/resolvers");


const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: ({ event, context }) => ({
    headers: event.headers,
    functionName: context.functionName,
    event,
    context,
  }),
});

// without CORS enabled
exports.handler = server.createHandler();

// with CORS enabled
exports.handler = server.createHandler({
  cors: {
    origin: '*',
    methods: ['POST', 'GET', 'OPTIONS',],
    allowedHeaders: ['Content-Type', 'Authorization'],
    credentials: true,
  },
});
```

and the API Gateway configuration has 
- METHOD REQUEST => Auth: NONE
- INTEGRATION REQUEST => Type: Lambda Proxy
- METHOD RESPONSE => Http Status: Proxy

properties.

In each situation when I test the API;
- from the API Gateway Console: I got "Apollo Server supports only GET/POST requests" error,
- from the Apollo Client: I got "Network Request Failed With Status 405" error.

Probably I have been tried all the ways that I found lots of time googling to solve the problem but none of them worked.

I'm ready to provide any information is needed to reproduce the issue.

Any help would be greatly appreciated.

**Comment by TimothyDalbey** [comment]
Any information about how you resoled this issue?

**Comment by personapp** [comment]
I did not have time to create a pull request for the issue, sorry about that. 

I made a little change the code which in apollo-server-lambda/lambdaApollo.js directory
```
...
...
...
.then(({ graphqlResponse, responseInit }) => {
    return callback(null, {
        //body: graphqlResponse,
        body: JSON.stringify(graphqlResponse),
        statusCode: 200,
        headers: responseInit.headers,
        isBase64Encoded: false,
    });
}, (error) => {
    if ('HttpQueryError' !== error.name)
        return callback(error);
    return callback(null, {
        //body: error.message,
        body: JSON.stringify(error.message),
        statusCode: error.statusCode,
        headers: error.headers,
        isBase64Encoded: false,
    });
});
...
...
...
```
this is how I resolve the issue.
