### ISSUE TITLE
Apollo Server ignores toJSON methods when serializing

### ISSUE THREAD

**Issue by kgroat** [apollographql/apollo-server#1649]
I'm using `apollo-server@2.0.7`.  I'm using classes to define my models, and some of them have a `toJSON()` function defined to ensure that things are transformed appropriately, [as per the `JSON.stringify()` specification](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description).

`apollo-server` ignores the supplied function.

### Simple reproduction case
```js
import { ApolloServer, makeExecutableSchema } from 'apollo-server'

const schema = makeExecutableSchema({
  typeDefs: `
    type Query {
      myData: Data
    }

    type Data {
      foo: String!
    }
  `,
  resolvers: {
    Query: {
      myData () {
        return {
          foo: 'This should not show up',
          toJSON () {
            return {
              foo: 'This *should* show up',
            }
          },
        }
      },
    },
  },
})

const server = new ApolloServer({ schema })
server.listen(3000)
```

Executing the following query:
```
query {
  myData {
    foo
  }
}
```

Yields:
```js
{
  "data": {
    "myData": {
      "foo": "This should not show up"
    }
  }
}
```

Instead, I would expect it to show:
```js
{
  "data": {
    "myData": {
      "foo": "This *should* show up"
    }
  }
}
```

### My scenario
My use case is specifically involving `ObjectID` from `mongodb`, where trying to serialize directly gives the following error:
```
ID cannot represent value: { _bsontype: \"ObjectID\", id: <Buffer 5b 97 b1 13 09 41 c7 a3 ef 5c 40 ad> }
```
I should be able to write a single `toJSON()` that transforms the id to a string, so that I don't get this error.  As it stands, I have to write a specific resolver for each id field in each to ensure that this gets handled correctly.

**Comment by muei** [comment]
> I'm using `apollo-server@2.0.7`. I'm using classes to define my models, and some of them have a `toJSON()` function defined to ensure that things are transformed appropriately, [as per the `JSON.stringify()` specification](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description).
> 
> `apollo-server` ignores the supplied function.
> 
> ### Simple reproduction case
> ```js
> import { ApolloServer, makeExecutableSchema } from 'apollo-server'
> 
> const schema = makeExecutableSchema({
>   typeDefs: `
>     type Query {
>       myData: Data
>     }
> 
>     type Data {
>       foo: String!
>     }
>   `,
>   resolvers: {
>     Query: {
>       myData () {
>         return {
>           foo: 'This should not show up',
>           toJSON () {
>             return {
>               foo: 'This *should* show up',
>             }
>           },
>         }
>       },
>     },
>   },
> })
> 
> const server = new ApolloServer({ schema })
> server.listen(3000)
> ```
> 
> Executing the following query:
> 
> ```
> query {
>   myData {
>     foo
>   }
> }
> ```
> Yields:
> 
> ```js
> {
>   "data": {
>     "myData": {
>       "foo": "This should not show up"
>     }
>   }
> }
> ```
> 
> Instead, I would expect it to show:
> 
> ```js
> {
>   "data": {
>     "myData": {
>       "foo": "This *should* show up"
>     }
>   }
> }
> ```
> 
> ### My scenario
> My use case is specifically involving `ObjectID` from `mongodb`, where trying to serialize directly gives the following error:
> 
> ```
> ID cannot represent value: { _bsontype: \"ObjectID\", id: <Buffer 5b 97 b1 13 09 41 c7 a3 ef 5c 40 ad> }
> ```
> I should be able to write a single `toJSON()` that transforms the id to a string, so that I don't get this error. As it stands, I have to write a specific resolver for each id field in each to ensure that this gets handled correctly.

https://github.com/apollographql/apollo-server/issues/1633#issuecomment-419916875

**Comment by kgroat** [comment]
I actually ended up creating a new scalar type.
### typeDef:
```graphql
scalar ObjectID
```

### resolver:
```typescript
const resolvers: IResolvers<Document, Context> = {
  ObjectID: new GraphQLScalarType({
    name: 'ObjectID',
    description: 'The `ObjectID` scalar type represents a [`BSON`](https://en.wikipedia.org/wiki/BSON) ID commonly used in `mongodb`.',
    serialize (_id): string {
      if (_id instanceof ObjectID) {
        return _id.toHexString()
      } else if (typeof _id === 'string') {
        return _id
      } else {
        throw new Error(`${Object.getPrototypeOf(_id).constructor.name} not convertible to `)
      }
    },
    parseValue (_id): ObjectID {
      if (typeof _id === 'string') {
        return ObjectID.createFromHexString(_id)
      } else {
        throw new Error(`${typeof _id} not convertible to ObjectID`)
      }
    },
    parseLiteral (ast): ObjectID {
      if (ast.kind === Kind.STRING) {
        return ObjectID.createFromHexString(ast.value)
      } else {
        throw new Error(`${ast.kind} not convertible to ObjectID`)
      }
    },
  }),
}
```

**Comment by axe-z** [comment]
this is not user friendly at all.

**Comment by tuanhuu** [comment]
> I actually ended up creating a new scalar type.
> 
> ### typeDef:
> ```graphql
> scalar ObjectID
> ```
> 
> ### resolver:
> ```js
> import { GraphQLScalarType } from 'graphql'
> import { Kind } from 'graphql/language'
> import { ObjectID } from 'mongodb'
> 
> export const resolvers = {
>   ObjectID: new GraphQLScalarType({
>     name: 'ObjectID',
>     description: 'The `ObjectID` scalar type represents a [`BSON`](https://en.wikipedia.org/wiki/BSON) ID commonly used in `mongodb`.',
>     serialize (_id) {
>       if (_id instanceof ObjectID) {
>         return _id.toHexString()
>       } else if (typeof _id === 'string') {
>         return _id
>       } else {
>         throw new Error(`${Object.getPrototypeOf(_id).constructor.name} not convertible to `)
>       }
>     },
>     parseValue (_id) {
>       if (typeof _id === 'string') {
>         return ObjectID.createFromHexString(_id)
>       } else {
>         throw new Error(`${typeof _id} not convertible to ObjectID`)
>       }
>     },
>     parseLiteral (ast) {
>       if (ast.kind === Kind.STRING) {
>         return ObjectID.createFromHexString(ast.value)
>       } else {
>         throw new Error(`${ast.kind} not convertible to ObjectID`)
>       }
>     },
>   }),
> }
> ```

how to import it?

**Comment by tuanhuu** [comment]
> I actually ended up creating a new scalar type.
> 
> ### typeDef:
> ```graphql
> scalar ObjectID
> ```
> 
> ### resolver:
> ```js
> import { GraphQLScalarType } from 'graphql'
> import { Kind } from 'graphql/language'
> import { ObjectID } from 'mongodb'
> 
> export const resolvers = {
>   ObjectID: new GraphQLScalarType({
>     name: 'ObjectID',
>     description: 'The `ObjectID` scalar type represents a [`BSON`](https://en.wikipedia.org/wiki/BSON) ID commonly used in `mongodb`.',
>     serialize (_id) {
>       if (_id instanceof ObjectID) {
>         return _id.toHexString()
>       } else if (typeof _id === 'string') {
>         return _id
>       } else {
>         throw new Error(`${Object.getPrototypeOf(_id).constructor.name} not convertible to `)
>       }
>     },
>     parseValue (_id) {
>       if (typeof _id === 'string') {
>         return ObjectID.createFromHexString(_id)
>       } else {
>         throw new Error(`${typeof _id} not convertible to ObjectID`)
>       }
>     },
>     parseLiteral (ast) {
>       if (ast.kind === Kind.STRING) {
>         return ObjectID.createFromHexString(ast.value)
>       } else {
>         throw new Error(`${ast.kind} not convertible to ObjectID`)
>       }
>     },
>   }),
> }
> ```

Hi, so how to use this scalar on client side. Because file _id in server defined with ObjectId, so in client side, it must me ObjectId too, but i cant find any way to defind scalar in client, just have String, or boolean,...

**Comment by acidoxee** [comment]
Has this problem been fixed in the meantime?

We used to do stuff like `id: obj => obj._id.toHexString()` in all our resolvers that handled MongoDB ObjectIds, but now it seems `id: obj => obj._id` alone is working perfectly fine.
