### ISSUE TITLE
Support async schema

### ISSUE THREAD

**Issue by moimael** [apollographql/apollo-server#1661]
- [x] has-reproduction
- [ ] feature
- [ ] docs
- [x] blocking
- [ ] good first issue

Hi,

I tried to migrate our graphql proxy to apollo-server v2 and got an issue reported by TS. We are creating the schema manually (for schema stitching) and make use of the `makeRemoteExecutableSchema` function. We chose to introspect the schema at runtime so our returned schema is async. It used to work perfectly fine with v1 but now the ApolloServer schema option is not accepting it anymore.

It does work if I wait for my schema to resolve first and then setup the server but it's not very nice.

Could we add support for async schema back ?

Thanks !

**Comment by sbrichardson** [comment]
One option is to extend the ApolloServer class, I had done that to add that support back in,

See an example in this comment:

https://github.com/apollographql/apollo-server/issues/1308#issuecomment-411643390

You can't see async/await in that example, but it is resolving a promise behind the scenes.

**Comment by sbrichardson** [comment]
Here's a more complete example with the playground code included.
I omitted a few details from my own logic, noted below.

It's basically building a custom schema on each request from a cache, instead of just passing the schema from the ApolloServer class instance when it started initially. This isn't using subscriptions currently, I haven't needed/tested with that yet.

```js
import { renderPlaygroundPage } from '@apollographql/graphql-playground-html'
import accepts from 'accepts'
import { ApolloServer, makeExecutableSchema } from 'apollo-server-express'
import { graphqlExpress } from 'apollo-server-express/dist/expressApollo'

class CustomServer extends ApolloServer {
  applyMiddleware({ app, path }) {
    app.use(path, async (req, res, next) => {
      if (process.env.NODE_ENV === 'development') {
        if (this.playgroundOptions && req.method === 'GET') {
          // perform more expensive content-type check only if necessary
          // XXX We could potentially move this logic into the GuiOptions lambda,
          // but I don't think it needs any overriding
          const accept = accepts(req)
          const types = accept.types()
          const prefersHTML =
            types.find(x => x === 'text/html' || x === 'application/json') ===
            'text/html'

          if (prefersHTML) {
            const playgroundRenderPageOptions = {
              endpoint: path,
              subscriptionEndpoint: this.subscriptionsPath,
              ...this.playgroundOptions,
            }
            res.setHeader('Content-Type', 'text/html')
            const playground = renderPlaygroundPage(playgroundRenderPageOptions)
            res.write(playground)
            res.end()
            return
          }
        }
      }

      const {
        // ...omitted for example
      } = req.body

      const { schema: _remove, context: _context, ...serverObj } = this

      return graphqlExpress(
        super.createGraphQLServerOptions.bind({
          ...serverObj,
          graphqlPath: path,
          schema: await makeExecutableSchema(
            // ...omitted for example
          ),
          context: {
            // ...omitted for example
            request: req,
          },
        })
      )(req, res, next)
    })
  }
}

export default CustomServer

```

**Comment by sbrichardson** [comment]
You can test it by passing a simple example schema when you initially create the server, then send some  requests, and the schema will be different based on details of each request.

**Comment by moimael** [comment]
Would love to have that, it is currently making the upgrade painful

**Comment by a613** [comment]
Yep, it must be embarrassing for contributors that things like this weren't taken into consideration with v2.

**Comment by jbaxleyiii** [comment]
@moimael initial support this is in progress and will also be part of Apollo Server 3.0!
