### ISSUE TITLE
When I add "context " to server, the server response HTTP 500

### ISSUE THREAD

**Issue by lagmanzaza** [apollographql/apollo-server#1663]
- [ ] has-reproduction
- [ ] feature
- [ ] docs
- [ ] blocking
- [x] good first issue

<img width="1440" alt="screen shot 2561-09-14 at 01 04 56" src="https://user-images.githubusercontent.com/5283709/45506766-6e78a300-b7ba-11e8-9716-392375f96718.png">
<img width="1440" alt="screen shot 2561-09-14 at 01 05 24" src="https://user-images.githubusercontent.com/5283709/45506767-6f113980-b7ba-11e8-9b89-5e505dc0d908.png">
<img width="925" alt="screen shot 2561-09-14 at 01 06 08" src="https://user-images.githubusercontent.com/5283709/45506768-6f113980-b7ba-11e8-9db8-96699d14f7d9.png">

**Comment by trevor-scheer** [comment]
Hey @lagmanzaza , thanks for submitting this. If you don't mind, could you please provide a runnable reproduction for this? Thanks!
