### ISSUE TITLE
Merge schemas and resolvers

### ISSUE THREAD

**Issue by hasusozam** [apollographql/apollo-server#1664]
I want to separate my schemas and resolvers to separated files as it's kinda big right now in one single file.

I found a library called `merge-graphql-schemas` but I think that it's redundant with Apollo Server 2 and `graphql-tools`, the thing is that Apollo Server 2 does already what `graphql-yoga` does and I don't need to call `makeExecutableSchema` in the version 1 as I needed before as it's now wrapped inside the `new ApolloServer` ([see here](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/ApolloServer.ts#L195) so now I'm wondering, how can I use `graphql-tools` and `mergeSchema` with Apollo Server 2?
I don't even know if this approach, I guess called  schema stitching is only for remote schemas or it's suited for local ones as well, like having an schema for user, another one for posts, and so on...

How can I accomplish this?

**Comment by strickc** [comment]
@hasusozam You would then take the schema object from sbrichardson's example and pass it to ```new ApolloServer({ schema })```.  The [documentation for the ApolloServer constructor](https://www.apollographql.com/docs/apollo-server/api/apollo-server.html) says that ```typeDefs``` and ```resolvers``` are required, but appears to omit that they are not required if schema is supplied.

**Comment by havinhthai** [comment]
I use [graphql-import](https://github.com/prisma/graphql-import) to merge schemas and [graphql-merge-resolvers](https://github.com/havinhthai/graphql-merge-resolvers) to merge my resolvers. Hope can help you.

**Comment by martijnwalraven** [comment]
Closing this because we have experimental `modules` support that should support this use case.

**Comment by elrussord1** [comment]
`` 🐙 > > ``

**Comment by techyaura** [comment]
What i think, that there is no need for some more dependency for now for merging the types, as **_graphql-tools_** are fine for them.
Have a look https://github.com/techyaura/graphqlNodeMongodb-server/tree/master/src/gql, if it helps.

**Comment by justinmwarner** [comment]
@martijnwalraven where are these experimental modules?
