### ISSUE TITLE
Incorrect example in docs?

### ISSUE THREAD

**Issue by hasusozam** [apollographql/apollo-server#1672]
I was reading the docs and I saw this example: https://github.com/apollographql/apollo-server/blob/master/docs/source/best-practices/authentication.md

I noticed that it's using the `apollo-server` and passing the `app` to the `ApolloServer` instance but the instance doesn't have this argument, and also `applyMiddleware` doesn't work either. Internally [here](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server/src/index.ts#L83) is where the express app instance is located.

**Comment by rlancer** [comment]
The website under the drop down menu for Apollo Server -> Subscriptions, links to the older version of  Apollo Server, not realizing this has caused a lot of frustration, not sure where to post issues regarding the website.

**Comment by justinanastos** [comment]
Thanks for filing this issue @hasusozam and @rlancer ! It seems as though the docs have been updated since this writing so I'm going to close this for now. If there is still and issue and I missed it please respond and `@` me and I'll re-open it!
