### ISSUE TITLE
Add whether Apollo Server 2 supports Content-Type 'application/graphql' to the documentation

### ISSUE THREAD

**Issue by matthew1534** [apollographql/apollo-server#1676]
Add whether Apollo Server 2 supports Content-Type 'application/graphql' to the documentation - can't find a definitive answer as to whether it is supported or not.

**Comment by jsegaran** [comment]
Thanks for logging this concern originally. It looks like this is mentioned in the [official guide](https://graphql.org/learn/serving-over-http/#post-request). Feel free to make a PR adding more documentation to the repo.
