### ISSUE TITLE
any way to run 2.0.0 as middleware?

### ISSUE THREAD

**Issue by capaj** [apollographql/apollo-server#1688]
We have multiple schemas that need to be served on a single endpoint. Each schema is for a different role of a user. With apollo-server-koa 1.x we just do:
```js
graphQLRouter.post('/graphql', koaBody(), (ctx, next) => {
  const { session } = ctx.req

  return graphqlKoa({
    schema: ctx.schema,
    context: session,
    validationRules: [depthLimit(15)],
    tracing: true,
    cacheControl: true
  })(ctx, next)
})
```

is there a way to have multiple schemas on a single endpoint with apollo-server 2.0.0?

All the examples just show a trivial example with a single schema.

**Comment by razor-x** [comment]
I've noticed there are a lot of similar requests coming in for the missing middleware in v2. I'm wondering if we should consolidate them in one issue and close the others.

This one seems like the best candidate: https://github.com/apollographql/apollo-server/issues/1308

**Comment by capaj** [comment]
closing as a duplicate of #1308
