### ISSUE TITLE
Use Apollo Server internally within a function

### ISSUE THREAD

**Issue by matthew1534** [apollographql/apollo-server#1705]
Is it possible to run Apollo Server 2 within a function so that other logic code in the same function can 'post' queries/mutations to the Apollo Server part of the function?

**Use case:** We use Google Cloud Functions and have a function that needs to run some logic and periodically make requests to Apollo Server (we don't want to give it direct access to our database and this enforces set API logic). We don't want to split Apollo Server into its own function as then every time we make a request from the logic function to the Apollo Server function we would effectively be paying ~double and we would have to add extra authentication.

**Comment by sbrichardson** [comment]
Check out [this solution from StackOverflow](https://stackoverflow.com/questions/41424728/how-to-execute-graphql-query-from-server):


> GraphQL.js itself does not require a http server to run. express-graphql is just a helper to mount the query resolver to a http endpoint. 

> You can pass your schema and the query to graphql, it'll return a Promise that'll resolve the query to the data.

```js
graphql(schema, query).then(result => {
  console.log(result);
});
```

Does this help?

**Comment by matthew1534** [comment]
@sbrichardson couldn't get this working with Apollo Server but appreciate the response

**Comment by mlwigdahl** [comment]
You can use executeOperation() to do this, passing an object containing your query and variables.

**Comment by hwillson** [comment]
Hopefully one of the solutions mentioned in this thread helped out. Closing - thanks!

**Comment by itsezc** [comment]
@hwillson None of the solutions have worked so far, would you be able to reopen the issue thanks

**Comment by benjaminpearson** [comment]
@itsezc hopefully you got it working. Below are some code examples if you didn't or for next person.

Given you have `./server.js` such as:
```
import { ApolloServer, gql, makeExecutableSchema } from 'apollo-server'

const typeDefs = gql`
  type Query {
    users: [User!]!
  }
  type User {
    name: String
    username: String
  }
`;

const resolvers = {
  Query: {
    users() {
      return [{ name: 'Test', username: 'test' }];
    },
  },
};

export const schema = makeExecutableSchema({ typeDefs, resolvers });
export default new ApolloServer({ schema });
```

Then in `./consumer.js`
```
import { graphql } from 'graphql';
import { schema } from './server.js';

const query = `
  query {
    users {
      name
      username
    }
  }
`;

graphql({ schema, source: query }).then(console.log);
```

You can pass in more options to `graphql` as sbrichardson describes above (such as variables) or visit latest docs at https://graphql.org/graphql-js/graphql/#graphql

Thanks to other contributors to this issue as it helped me to resolve my issue when wanting to consume a local graphql schema to build a static Next.js website.
