### ISSUE TITLE
"gui" option for server.applyMiddleware does not exist

### ISSUE THREAD

**Issue by omgrief** [apollographql/apollo-server#1717]
www.apollographql.com/docs/apollo-server/migration-two-dot.html#graphiql

The documentation here says that you can supply this "gui" option in order to further configure graphql playground (i.e. if you wanted to still use `/graphiql` as a separate route), but looking through code, this option seems to have been removed, and if you want to utilize the UI you have to access it through the same path no matter what.

**Comment by danieljuhl** [comment]
@omgrief I had the same issue, and found the following PR #1297 

You have to move the config to `new ApolloServer({ ... })` and replace `gui` with `playground`

**Comment by omgrief** [comment]
@danieljuhl yeah I figured that out, but still think that the documentation should be updated

**Comment by danieljuhl** [comment]
@omgrief agree - my comment was mainly to help others with the same issue.
