### ISSUE TITLE
Server works locally but not on Heroku after following all given steps

### ISSUE THREAD

**Issue by Naman-Goyal** [apollographql/apollo-server#1718]
Intended Outcome:

I made a server using GraphQL and Apollo that works locally, and would expect that when I add the needed changes (a Procfile, Environment variables, etc), and try to deploy it to Heroku, it would work.

Actual Outcome: 

The server code works locally, for example, on localhost:4000, but when on Heroku, it deploys successfully but then the GraphQL Playground says that the Server cannot be reached, and in the right hand, results side of the page, it shows "error": "Failed to fetch schema. Please check your connection"

How to Reproduce the Issue:

You can see the problem here-  http://vr-test-server.herokuapp.com/
If you want to pull the code itself, for local and for production, the repository can be cloned by
`git clone https://github.com/Naman-Goyal/VRUncannyValleyServer.git`

The project can be built by running `npm install`, and run by `npm start`

The local version of the server is on the "Local" branch
The production version of the server that is set up to push to heroku is on the "Production" branch

**Comment by bs1180** [comment]
By default, both the playground and introspection queries are [disabled in production](https://www.apollographql.com/docs/apollo-server/api/apollo-server.html#constructor-options-lt-ApolloServer-gt). You've manually enabled the playground but not the introspection query, which results in the error you see, but your API is working fine already. You can actually make queries in the playground if you ignore the error:

![image](https://user-images.githubusercontent.com/5904336/46001285-353e0e00-c0ab-11e8-8e84-1ae4df389eda.png)

The solution will be to add `introspection: true` to your config.

**Comment by Naman-Goyal** [comment]
Thank you so much! It's working now.

**Comment by Sakthivelgovindan** [comment]
It's really working.

**Comment by surajkrishan** [comment]
i tried passing both values to true not working for me :(

**Comment by sarthakagsa** [comment]
I did the same as @surajkrishan  But still it is not working
