### ISSUE TITLE
Enums with internal values aren't converted in output

### ISSUE THREAD

**Issue by bs1180** [apollographql/apollo-server#1721]
I'm trying to use enums with an internal value, as described [in the documentation](https://www.apollographql.com/docs/graphql-tools/scalars.html#enums).

### Expected outcome
If a resolver returns the internal representation of an enum (eg. `#f00`), the actual output should be the corresponding enum value (eg. `RED`).

### Actual outcome
The output is the internal value, which results in a graphql error.

![enum_error](https://user-images.githubusercontent.com/5904336/46000240-46395000-c0a8-11e8-8cd1-c55609ba6cf8.PNG)

An enum used as an input is available in the resolver in it's internal value, so that part works correctly. But the output enum is not converted correctly.

### How to reproduce the issue
 I have a simple reproduction [here](https://big-glazer.glitch.me/) ([source code](https://glitch.com/edit/#!/big-glazer)) based closely on the example code in the documentation.

Thanks for your help!

**Comment by dncrews** [comment]
Looks like it's only an issue with `graphql@14`. This does not error out with `graphql@0.13`

**Comment by regisbsb** [comment]
I've also reproduced here https://apollo-enum-bug.now.sh/_src and can view here 
https://apollo-enum-bug.now.sh/

**Comment by bs1180** [comment]
This bug has been fixed - thanks @tgriesser!
