### ISSUE TITLE
[v2] Any plans to export graphqlExpress as well from apollo-server-express

### ISSUE THREAD

**Issue by subeeshcbabu** [apollographql/apollo-server#1726]
`applyMiddleware` really helps to add the middleware existing app.
```
const server = new ApolloServer({
  // These will be defined for both new or existing servers
  typeDefs,
  resolvers,
});

server.applyMiddleware({ app }); // app is from an existing express app
```

However it would be really awesome, if the `graphqlExpress` is also exposed to users. 

Any possible way to access [graphqlExpress](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-express/src/expressApollo.ts.) directly from `ApolloServer` or the `apollo-server-express` module?

This will really help anyone want to pass the middleware function to lets say a router module that would take of applying the middleware.

**Comment by sbrichardson** [comment]
Kind of a hack, but you can import it currently from here:

```js
import { graphqlExpress } from 'apollo-server-express/dist/expressApollo'
```

I'm using it to extend ApolloServer with a custom async schema ([example](https://github.com/apollographql/apollo-server/issues/1661#issuecomment-421502954))

**Comment by subeeshcbabu** [comment]
Thanks @sbrichardson. That is exactly what i am also doing right now. Thought i could avoid the `/dist` reference. :-)

Thanks for sharing the example code.

**Comment by mjasnikovs** [comment]
Any clue where to acquire "graphiqlExpress" ?

**Comment by razor-x** [comment]
@mjasnikovs See my related comment here: https://github.com/apollographql/apollo-server/issues/1308#issuecomment-431121686

**Comment by razor-x** [comment]
I've noticed there are a lot of similar requests coming in for the missing middleware in v2. I'm wondering if we should consolidate them in one issue and close the others.

This one seems like the best candidate: https://github.com/apollographql/apollo-server/issues/1308

**Comment by abernix** [comment]
Thank you for your help triaging, @razor-x!  Agree on consolidating, and definitely something we're aware of.  The workaround above can be utilized in a pinch, but we do intend to address this.

Let's take any further discussion to #1308.  Thanks!
