### ISSUE TITLE
Anyway to user apollo-server-hapi with serverless such as lambda, azure function

### ISSUE THREAD

**Issue by maimike** [apollographql/apollo-server#1738]
Now, i'm using apollo-server-hapi 2.1 in a vps, and it works pretty well. However, now I have an idea to run it with serverless service such as Lamba, Azure function. I just saw some document mention about stand alone Apollo with serverless such as apollo-server-azure-functions. However, in this case, i still need to have hapi.

So is it possible for using  apollo-server-hapi with serverless services

**Comment by dncrews** [comment]
Not sure about azure, but I know with Lambda, there's this: https://www.npmjs.com/package/hapi-lambda

**Comment by jsegaran** [comment]
Thanks for reporting this issue originally!

`apollo-server-hapi` does not support server-less. There are specific serverless implementations at the moment such as `apollo-server-lambda`, but these are going to be changed with Apollo Server 3.0, which are documented in [the roadmap](https://github.com/apollographql/apollo-server/issues/2360).
