### ISSUE TITLE
using async in formatError hook, error message will be no complete

### ISSUE THREAD

**Issue by anymost** [apollographql/apollo-server#1747]
when I use async function in formatError hook, for example:
`
formatError:async (error) => {
		// some other async code
		console.log(error);
		return error;
	}
`
the error message sent to client don't contain error detail, just like this:
`
{
    "data":null,
    "errors":[{}]
}
`
if I remove async , the error message sent to client will be complete, wish some body help me, thanks a lot

**Comment by anymost** [comment]
`
export class UserInputError extends ApolloError {
  constructor(message: string, properties?: Record<string, any>) {
    super(message, 'BAD_USER_INPUT', properties);

    Object.defineProperty(this, 'name', { value: 'UserInputError' });
  }
}

export function formatApolloErrors(
  errors: Array<Error>,
  options?: {
    formatter?: Function;
    debug?: boolean;
  },
): Array<ApolloError> {
  if (!options) {
    return errors.map(error => enrichError(error));
  }
  const { formatter, debug } = options;

  // Errors that occur in graphql-tools can contain an errors array that contains the errors thrown in a merged schema
  // https://github.com/apollographql/graphql-tools/blob/3d53986ca/src/stitching/errors.ts#L104-L107
  //
  // They are are wrapped in an extra GraphQL error
  // https://github.com/apollographql/graphql-tools/blob/3d53986ca/src/stitching/errors.ts#L109-L113
  // which calls:
  // https://github.com/graphql/graphql-js/blob/0a30b62964/src/error/locatedError.js#L18-L37
  // Some processing for these nested errors could be done here:
  //
  // if (Array.isArray((error as any).errors)) {
  //   (error as any).errors.forEach(e => flattenedErrors.push(e));
  // } else if (
  //   (error as any).originalError &&
  //   Array.isArray((error as any).originalError.errors)
  // ) {
  //   (error as any).originalError.errors.forEach(e => flattenedErrors.push(e));
  // } else {
  //   flattenedErrors.push(error);
  // }

  const enrichedErrors = errors.map(error => enrichError(error, debug));

  if (!formatter) {
    return enrichedErrors;
  }

  return enrichedErrors.map(error => {
    try {
      return formatter(error);
    } catch (err) {
      if (debug) {
        return enrichError(err, debug);
      } else {
        // obscure error
        const newError = fromGraphQLError(
          new GraphQLError('Internal server error'),
        );
        return enrichError(newError, debug);
      }
    }
  }) as Array<ApolloError>;
}
`
I found calling the formatError function without async when I searched the source code

**Comment by cheapsteak** [comment]
Hi there  
Closing this issue because `formatError` does not support async functions   
Curious if you could share your use-case? Perhaps you might benefit from the `didEncounterErrors` lifecycle that was recently added - https://github.com/apollographql/apollo-server/pull/2719

**Comment by marlonfsolis** [comment]
Hi @cheapsteak,
Do you think is a valid scenario call an async method that log the error on a DB?
I think would be simpler than inplement didEncounterErrors. But I am not sure how hard would be to convert formatError to async function.
It was very hard to find out how to implement didEncounterErrors. The documentation is not good at all for this event lifecycle.
The formatError is more intuitive and simpler.

```
const formatError = async (formattedError:GraphQLFormattedError, error:unknown): GraphQLFormattedError => 
{
   const errorLogId = await logError(LogLevel.ERROR, formattedError.message);
   formattedError.message =+ ` - ErrorNo.: ${errorLogId }`;
   return formattedError;
}
```

**Comment by trevor-scheer** [comment]
@marlonfsolis `didEncounterErrors` is the correct approach for async logging. It looks like we have some examples for other hooks but not this one. TypeScript also makes working with our libraries easier. Tests are often a good place to look for examples (there are a few in our repo).

Here's the skeleton of a plugin which implements `didEncounterErrors`. Hope you find this helpful.
```ts
plugins: [{
  async requestDidStart() {
    return {
      async didEncounterErrors(requestContext) {
        // log to service
      }
    };
  } 
}]
```
