### ISSUE TITLE
RESTDataSource cache - Redis cluster support

### ISSUE THREAD

**Issue by shinyaohira** [apollographql/apollo-server#1750]
I would like to use RESTDataSource in production with Redis cache cluster. `apollo-server-cache-redis` uses `redis` module, but [it doesn't support cluster feature](https://github.com/NodeRedis/node_redis/issues/574).

There is an alternative module, [ioredis](https://github.com/luin/ioredis) which supports Cluster, Sentinel and Pipelining features. I found an issue @eberhara opened for [sentinel support]( #1725 ). So maybe we should migrate to it?

**Comment by eberhara** [comment]
@shinyaohira just created a [PR #1770](https://github.com/apollographql/apollo-server/pull/1770) with an implementation for that.
Would you mind to review and share your thoughts?

**Comment by shinyaohira** [comment]
@eberhara Sure!

**Comment by benoitemile** [comment]
we can close this
