### ISSUE TITLE
Problem with passing websocket connectionParams between a few endpoints.

### ISSUE THREAD

**Issue by Devlin556** [apollographql/apollo-server#1759]
I have troubles with passing a connectionParams for graphql-subscriptions between two or more endpoints. I use Apollo-Server 2 and Apollo-Link-WS 1.0.9. I use a microservice architecture with apollo stack and schema stitching. I have a few graphql-endpoints and a gateway for all requests and I'm stuck with passing connectionParams for subscriptions from gateway-endpoint to graphql-endpoint.
How can I pass connectionParams or subscription-context per each subscription execution to endpoint which is connected with gateway by the apollo-link? It's needed for access control and authentication in subscriptions. 
Below I attached code with a gateway connecting to an endpoint.

```
const hasSubscriptionOperation = args => args.query.definitions.some(
  ({ kind, operation }) => kind === 'OperationDefinition'
      && operation === 'subscription',
);

const httpLink = new HttpLink({ uri, fetch });
  const wsLink = new WebSocketLink({
    uri: `${uri}${'/subscriptions'}`,
    options: {
      timeout: 30000,
      reconnect: true,
    },
    webSocketImpl: ws,
  });

const splittedLink = ApolloLink.split(hasSubscriptionOperation, wsLink, httpLink);

const schema = await introspectSchema(splittedLink)
```

**Comment by micksi** [comment]
I'm having the exact same problem and have tried different approaches. Most recently this https://gist.github.com/josephktcheung/cd1b65b321736a520ae9d822ae5a951b but managing websockets like that with multiple endpoints doesn't seem like the most appropriate way.

**Comment by glasser** [comment]
Direct subscriptions integration was removed from Apollo Server in v3 last year.
