### ISSUE TITLE
Auth Example is out of date and does not work

### ISSUE THREAD

**Issue by mvriel** [apollographql/apollo-server#1774]
- [x] has-reproduction
- [ ] feature
- [x] docs
- [ ] blocking

The page https://github.com/apollographql/apollo-server/blob/master/docs/source/best-practices/authentication.md#auth-example contains outdated information. Following this example yields a non-functional application because `apollo-server-express` should now be used and the `listen` method of express called instead of `apollo-server`.

(the reproduction scenario here is implementing the source mentioned in the documentation).

As a side note: for newcomers, it is not clear if this should be put into separate files or whether the code should just be pasted in one file :)

**Comment by jasonpaulos** [comment]
Hi @mvriel, thank you for originally reporting this issue. We have reorganized our docs since the opening of this issue, and at the moment our [section of authentication](https://www.apollographql.com/docs/apollo-server/features/authentication/) is up-to-date. Thanks!
