### ISSUE TITLE
Type error in config of ApolloServer. 'resolvers' should accept an array of resolvers

### ISSUE THREAD

**Issue by DimaMukhin** [apollographql/apollo-server#1775]
I believe that there is a bug with the type definitions of the ["config"](https://github.com/apollographql/apollo-server/blob/0ebf8900a048a962e4a3e0d64366d4bc871478ef/packages/apollo-server-core/src/types.ts#L38) interface passed to ["ApolloServer"](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/ApolloServer.ts).
According to the type definitions of the [config interface](https://github.com/apollographql/apollo-server/blob/0ebf8900a048a962e4a3e0d64366d4bc871478ef/packages/apollo-server-core/src/types.ts#L38), the field "resolvers" must be of type "IResolvers". However, an array of resolvers can also be passed, and the server will simply stitch all of the resolvers in the array.
When using JavaScript, this is not a problem since by default there is no type checking. However, when using TypeScript, we will get an error complaining about type miss-match and we won't be able to compile. A quick fix for this bug is to add `// @ts-ignore`.

### Intended outcome

I want to be able to use an array of resolvers when creating an ApolloServer instance with TypeScript.

### Actual outcome

ApolloServer does not accept an array of resolvers. As a result, TypeScript will complain about this and will not compile. More information and an error message can be found below.

### How to reproduce the issue

Simply pass an array of resolvers when creating an instance of ApolloServer when using TypeScript. See code example below for more details.

### Code Example

```
import * as Koa from 'koa';
import { ApolloServer, gql, IResolvers } from 'apollo-server-koa';
import { DocumentNode } from 'graphql';

const app: Koa = new Koa();

const schema: DocumentNode = gql`
  type Query {
    me: User
    user: User
  }

  type User {
    username: String!
  }
`;

const resolvers: Array<IResolvers> = [{
    Query: {
        me: () => {
            return {
                username: 'Dima Mukhin',
            };
        },
    },
},
{
    Query: {
        user: () => {
            return {
                username: 'I love apollo-server',
            };
        },
    }
}];

// @ts-ignore: 'resolvers' should accept 'Array<IResolvers>'
const server: ApolloServer = new ApolloServer({
    typeDefs: schema,
    resolvers,
});

server.applyMiddleware({ app, path: '/graphql' });
app.listen(3000);
console.log('Server running on port 3000');
```

The above code will work perfectly fine because we ignore the type checking of the config. However, if we remove `// @ts-ignore`, the application will no longer compile, and we will get the following error:

```
[ts]
Argument of type '{ typeDefs: DocumentNode; resolvers: IResolvers<any, any>[]; }' is not assignable to parameter of type 'Config'. Types of property 'resolvers' are incompatible. Type 'IResolvers<any, any>[]' is not assignable to type 'IResolvers<any, any>'. Index signature is missing in type 'IResolvers<any, any>[]'.
```

### Potential Solution

First, in [types.ts](https://github.com/apollographql/apollo-server/blob/0ebf8900a048a962e4a3e0d64366d4bc871478ef/packages/apollo-server-core/src/types.ts#L53) we change the following line
`resolvers?: IResolvers;`
becomes:
`resolvers?: IResolvers | Array<IResolvers>;` 
Second, in [ApolloServer.ts](https://github.com/apollographql/apollo-server/blob/0ebf8900a048a962e4a3e0d64366d4bc871478ef/packages/apollo-server-core/src/ApolloServer.ts#L182) we change the following line
`if (resolvers && !resolvers.Upload) {`
becomes:
`if (resolvers && !(resolvers instanceof Array) && !resolvers.Upload) {`

**Comment by cctv1237** [comment]
Yea, same issue as well

**Comment by javiercornejo** [comment]
Hello. Same issue here.

**Comment by alex996** [comment]
Any chance this could get fixed?

**Comment by keesvanlierop** [comment]
This used to work for version 1.. Not sure why they dropped support for this?
