### ISSUE TITLE
How to whitelist persisted queries and disallow arbitrary queries?

### ISSUE THREAD

**Issue by joonhocho** [apollographql/apollo-server#1793]
I want disallow arbitrary queries from client to prevent abusive queries.
How do I extract and compute query hashes and save it as a query white list file and use load it on apollo server to whitelist them?
I've tried apollo-cli apollo queries:extract, but its hashed value does not match the one created by apollo-link-persisted-queries.

 https://github.com/apollographql/apollo-link-persisted-queries/issues/28

- [x] feature

- [x] docs

- [x] blocking

**Comment by jbaxleyiii** [comment]
@joonhocho you can do this today! https://www.apollographql.com/docs/platform/operation-registry/

**Comment by PrimarchAlpharius** [comment]
@jbaxleyiii I do understand you also have to make money somehow :) Still, is there a way of doing this manually and not relying on the apollo graph manager service? For some smaller/pet projects, paying just for the whitelist funcionality is not worth it.

**Comment by glasser** [comment]
The operation registry/safelist feature of Apollo GraphOS is no longer enabled for graphs that have not yet used it. If you're interested in this kind of functionality, I encourage you to contact support@apollographql.com, and we'd be happy to talk to you about whether or not this older feature is a good fit for your use case, or whether some alternatives we are currently working on would work better.

**Comment by maclockard** [comment]
Okay, I'm probably just going to roll my own plugin for right now. Thanks though!
