### ISSUE TITLE
Subscriptions - context not extended

### ISSUE THREAD

**Issue by marcel-devdude** [apollographql/apollo-server#1796]
Hey,

we have upgraded to apollo server 2 and now have trouble with the GraphQL context in the subscription resolvers. We have an ApolloServer and will extend the GraphQL context with some data the client sent during the first connect. In the docs is [an example](https://www.apollographql.com/docs/apollo-server/features/subscriptions.html#Authentication-Over-WebSocket). 

We've implemeted the `onConnect` and return some data: 

```
...
subscriptions: {
  onConnect: (connectionParams: ConnectionParams) => {
    // do sth. with the connection params
    return { some: 'data' };
  }
}
...
```

The documentation says the return value of the `onConnect` function extends the GraphQL context. The `onConnect` gets executed when a new client connects.

In our resolver we want to do some filtering based on the extended context:

```
...
subscribe: withFilter(
  () => this.pubSub.subscribe('xxx'),
  (payload, _, ctx: IGraphQLContext) => {
    // do sth. with `ctx.some`
    return true;
  },
),
```

But the context in the resolver is always empty.

We are on the latest version of apollo-server-express and subscriptions-transport-ws.

Thank you very much for your help!

**Comment by marcel-devdude** [comment]
The return value of the `onConnect` callback is available in the `context` function. So you can return it if you build the context for subscriptions.

```
...
subscriptions: {
  onConnect: async (connectionParams) => {
    // Do some stuff with connectionParams like auth
    
    return { extended: 'context' };
  },
},
context: async ({ req, connection }) => {
  // If we build the context for subscriptions, return the context generated in the onConnect callback.
  // In this example `connection.context` is `{ extended: 'context' }`
  if (!req || !req.headers) {
    return connection.context;
  }

  // Build context for normal requests
  return { regular: 'context' };
},
...
```

**Comment by gustawdaniel** [comment]
This example could be added to docs. It is awesome in comparison to official documentation.

**Comment by exaucae** [comment]
> The return value of the `onConnect` callback is available in the `context` function. So you can return it if you build the context for subscriptions.
> 
> ```
> ...
> subscriptions: {
>   onConnect: async (connectionParams) => {
>     // Do some stuff with connectionParams like auth
>     
>     return { extended: 'context' };
>   },
> },
> context: async ({ req, connection }) => {
>   // If we build the context for subscriptions, return the context generated in the onConnect callback.
>   // In this example `connection.context` is `{ extended: 'context' }`
>   if (!req || !req.headers) {
>     return connection.context;
>   }
> 
>   // Build context for normal requests
>   return { regular: 'context' };
> },
> ...
> ```

Is therre any Appolo v3 equivalent of this? The `subscriptions `field seems to have been removed.

**Comment by glasser** [comment]
Apollo Server v3 does not have built-in support for subscriptions (we felt that the superficial integration with the unmaintained `subscriptions-transport-ws` package was not up to our standards). https://www.apollographql.com/docs/apollo-server/data/subscriptions/ documents how to integrate Apollo Server with the newer `graphql-ws` package, including a whole section on the context value.  There's a link at the bottom to the previous version of the docs which explains how to integrate AS with the unmaintained `subscriptions-transport-ws` package too if you need to.

**Comment by exaucae** [comment]
> Apollo Server v3 does not have built-in support for subscriptions (we felt that the superficial integration with the unmaintained `subscriptions-transport-ws` package was not up to our standards). https://www.apollographql.com/docs/apollo-server/data/subscriptions/ documents how to integrate Apollo Server with the newer `graphql-ws` package, including a whole section on the context value. There's a link at the bottom to the previous version of the docs which explains how to integrate AS with the unmaintained `subscriptions-transport-ws` package too if you need to.

[It's all good](https://www.apollographql.com/docs/apollo-server/data/subscriptions/#operation-context). Thanks for the updated documenation.
