### ISSUE TITLE
Object should know about sub-objects in a query

### ISSUE THREAD

**Issue by RobertStigsson** [apollographql/apollo-server#1803]
So, I've thought about this a few times since I started using GraphQL. I'm surprised that I couldn't find any feature-requests then, and I'm surprised I can't find any now (might be that I'm not the best at searching).

When we have a structure of objects, it would be not only great, but sometimes essential to know if the user are requesting sub-objects (see Example 1 below). I have been able to design around this issue earlier, but now I can't seem to do it easily anymore.

Example 1

```
type A {
  history: [HistoryAB]
}

type HistoryAB {
  bookingDate: Date!
  dataA: String
  dataB: String
}

query() {
  history {
    bookingDate
    dataA
    dataB
  }
}

```

In this example, dataA and dataB is from two different data sources. Both returns bookingDate which will join them. The problem is that in order to know which bookingDates that exists, I need to do a query of A and B, even though the user might only be interested of A's bookingDates.

What i want:
```
A: {
  async history (context) {
    let result = []
    if(context.subrequest.dataA) {
      result = dataloader.getA()
   }
   if(context.subrequest.dataB) {
      result.join(dataloader.getB())
   }
   return result
  }
}
```

How I need to do it now:
```
A: {
  async history (context) {
    return dataloader.getA().join(dataloader.getB())
  }
}
```

The other way to do it is to not join the HIstory of A and B, but that would both duplicate bookingDates and make the query a lot harder (it isn't only 2 data-points that should be merged).

**Comment by jbaxleyiii** [comment]
This is currently possible using the `info` portion of the resolver arguments
