### ISSUE TITLE
apollo-server-env: app is not defined

### ISSUE THREAD

**Issue by Multiply** [apollographql/apollo-server#1804]
We're using `apollo-datasource-rest`, which in turn is using `apollo-server-env`, and when we try to import our package for a react project that runs in the browser, we're hit by `app is not defined` from this commit: https://github.com/apollographql/apollo-server/commit/3f595eb3dee06021ca5fe5994bc8500844230286

Could we check if it's defined before using it, in another way?

It's blocking us from releasing to our production, without adding a `window.app = { env: 'x' }` to our `index.html` which is not pretty.

**Comment by mortenko** [comment]
+1 I have similiar problem @Multiply  thanks for temporary solving the problem. Did you find any solution ?

**Comment by Multiply** [comment]
Thanks a lot @martijnwalraven.
