### ISSUE TITLE
apollo-datasource-rest generates "TypeError: Right-hand side of 'instanceof' is not an object" when deployed to AWS lambda

### ISSUE THREAD

**Issue by sneyed** [apollographql/apollo-server#1828]
apollo-datasource-rest generates a `TypeError: Right-hand side of 'instanceof' is not an object` when it is deployed to lambda using this repository:
[https://github.com/sneyed/apollo-datasource-rest-issue](https://github.com/sneyed/apollo-datasource-rest-issue)

Issue only occurs once deployed to lambda
The response is succesful if you run the solution locally

### Steps to reproduce

1. [clone repository](https://github.com/sneyed/apollo-datasource-rest-issue)
2.  yarn install
3.  replace aws credentials with your own in .env-cmdrc
4.  yarn deploy:prod (serverless will deploy solution to AWS lambda)
5.  take note of endpoint quoted by serverless in console output
6.  hit deployed graphql endpoint with following query:
          `{characters{url}}`
7.  observe following error in response from endpoint
          `TypeError: Right-hand side of 'instanceof' is not an object`

### Suspect code

The error seems to point to this section of code.
line 117 (in javascript as seen via node_modules) / line 196 (in typescript as seen on github) of [`/node_modules/apollo-datasource-rest/dist/RESTDataSource.js`](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts):

```
return __awaiter(this, void 0, void 0, function* () {
    if (!(init.params instanceof apollo_server_env_1.URLSearchParams)) {
        init.params = new apollo_server_env_1.URLSearchParams(init.params);
    }
    if (!(init.headers && init.headers instanceof apollo_server_env_1.Headers)) {
        init.headers = new apollo_server_env_1.Headers(init.headers);
    }
    const options = init;
    if (this.willSendRequest) {
        yield this.willSendRequest(options);
    }
```

### Solutions attempted

* Putting webpack in development mode via `webpack.config.js` `mode` option.
```
mode: slsw.lib.webpack.isLocal ? "development": "development",
```
still results in same error.

**Comment by sneyed** [comment]
Workaround I am using for now is to just use [axios](https://github.com/axios/axios) calls instead of apollo-

**Comment by abernix** [comment]
If it's only happening when deployed, perhaps you need to use a newer version of the Node.js Lambda Runtime than the Node.js 6.x version you were using?  I think 8 or 10 would likely solve this as perhaps it was related to `RESTDataSource`s using native ECMAScript `class`es which were not supported in early versions of Node.js 6 (like the one that Amazon offered 
 at the time — now deprecated — and it appears to be the runtime you had configured?).

Anyhow, I'll close this as it's quite old.  Thank you for providing a reproduction initially, and apologies it took so long to triage this.  If it's still happening, could you please update the reproduction with the latest AWS Runtime and we'll be happy to take a look again?

Thanks!
