### ISSUE TITLE
npm install in apollo-server-express folder ends up with "error cb() never called!"

### ISSUE THREAD

**Issue by capaj** [apollographql/apollo-server#1842]
- [x] docs

This guide is not working on my machine:
https://github.com/apollographql/apollo-server#apollo-server-development

whenever I go to link `apollo-server-express` I get this npm error:
https://gist.github.com/capaj/6cd2b1b4fd8fc4edc6a48fa3a0458773

I know this is probably npm issue, but until they fix it-is there any workaround I can do to make it work?

I use node 8.11.4 and npm 6.4.1 on ubuntu 18.04

**Comment by trevorblades** [comment]
I'm not able to repro this issue using npm 6.10.0. Closing the issue, but please reopen if you run into it again using updated tools.
