### ISSUE TITLE
make the API lower level-allow to wrap runHttpQuery() in an objection.js transaction

### ISSUE THREAD

**Issue by capaj** [apollographql/apollo-server#1845]
- [x] feature

I use objection.js ORM on my server-side for DB models and with the current API of apollo-server I cannot use objection.js transactions as I would like to to-apollo-server is too high level.

I want to use this style of transactions: http://vincit.github.io/objection.js/#binding-models-to-a-transaction
to basically force every graphQL POST request to be handled inside a single transaction. This involves wrapping a `runHttpQuery()` [call](https://github.com/apollographql/apollo-server/blob/a619a8cd288cb46364dd6285469717b79ca939ba/packages/apollo-server-express/src/expressApollo.ts#L34)  inside a `transaction()` and passing all my models to it.
Inside the transaction I need to put all my models onto a context.

I know that this is probably a lot to ask, but we have a hard choice-either we sacrifice on ease of development in our own app and we make transaction in each of our resolvers manually or we drop apollo-engine and we use just raw `graphql(schema, query)` in our app.
Currently in our app we just make all transactions manually, but it would be nice if we could wrap our apollo-server resolver function in an objection.js transaction. As it is today, it's really impossible to do.

**Comment by p-jaya** [comment]
We have a similar problem, and equally I know it's a lot to ask!  In our case, API requests aren't _necessarily_ coming in via HTTP so mapping those requests to `runHttpQuery` ends up being a hack.

With Apollo 1.x we were able to wrap our required functionality around [runQuery](https://github.com/apollographql/apollo-server/blob/v1.4.0/packages/apollo-server-core/src/runQuery.ts)

I think we could probably use `requestPipeline` instead but that isn't exported so I assume is intended to remain private.

**Comment by mschinis** [comment]
having a similar problem also, where i need to do some set-up work before invoking the handler

**Comment by jbaxleyiii** [comment]
The work being done for Apollo Server 3.0 (#2360) will expose the requestPipeline in a formal and documented way to allow this! I'm going to close this individual issue in favor of the overall reworking
