### ISSUE TITLE
Upgrade to Apollo 2 (using apollo-server-express) breaks mutator for Firestore call

### ISSUE THREAD

**Issue by calidiHawk** [apollographql/apollo-server#1851]
I am unclear whether this is a Firestore or Apollo issue, but have been banging my head for two days and am submitting it to both. Thank you in advance! 

### Overview
- Upgraded from Apollo Server 1 to Apollo Server 2 
- Running with Express middleware 
- Executing on Firebase's Functions (serverless/lambda) 
- Using a mutator to create a document in Firebase's Firestore 

### Old Behavior / Expected Behavior 
- Assigning null to a field (x in the provided code bellow) should create that field in the Firestore document with the value of null 

### Observed Behavior 
- Upon creating/setting the field with a null value a TypeError occurs: 
`TypeError: Cannot read property 'NULL_VALUE' of undefined
    at Serializer.encodeValue (/Users/josh/Sites/Calidi/lymera_API/functions/node_modules/@google-cloud/firestore/build/src/serializer.js:105:76)
    at Serializer.encodeFields (/Users/josh/Sites/Calidi/lymera_API/functions/node_modules/@google-cloud/firestore/build/src/serializer.js:54:34)
    at Function.fromObject (/Users/josh/Sites/Calidi/lymera_API/functions/node_modules/@google-cloud/firestore/build/src/document.js:77:53)
    at WriteBatch.set (/Users/josh/Sites/Calidi/lymera_API/functions/node_modules/@google-cloud/firestore/build/src/write-batch.js:245:54)
    at DocumentReference.set (/Users/josh/Sites/Calidi/lymera_API/functions/node_modules/@google-cloud/firestore/build/src/reference.js:349:27)
    at /Users/josh/Sites/Calidi/lymera_API/functions/dist/data/mutations/m_consumer.js:30:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/josh/Sites/Calidi/lymera_API/functions/dist/data/mutations/m_consumer.js:12:103)
    at _next (/Users/josh/Sites/Calidi/lymera_API/functions/dist/data/mutations/m_consumer.js:14:194)
    at /Users/josh/Sites/Calidi/lymera_API/functions/dist/data/mutations/m_consumer.js:14:364`

I know the specific error is coming out of the Firestore module, but the only variable between my Apollo 1 execution and Apollo 2 execution is just that (Apollo 1 vs Apollo 2). 

### Providing
- Server setup code 
- Mutator code 
- Specific point of failure in Firestore module 

### Hoping 
- I am hoping there is simply something new with how Apollo 2 is handling mutator execution (but I really have absolutely no idea what could be going wrong) 

Thank you Again!! 

### Server Setup 
```

const express = require("express");
const { ApolloServer, gql } = require("apollo-server-express");
const cors = require("cors");

import { schema } from "./data/schema.js"
import { formatError } from 'apollo-errors';

function configureServer() {
    const app = express();

    app.use(cors()); // use middleware

    //const server = new ApolloServer({ formatError, schema }); // todo formatError doesn't seem to work now 
    const server = new ApolloServer({ schema });

    server.applyMiddleware({ app, path: '/' });

    return app;
}

module.exports = configureServer;
```

### Mutator
(Note: I have removed almost everything from this mutator and just left exactly where the error is originating (maybe)) 
```

		async newConsumer(root, args) {

			// db is a firestore client reference 
			let ref = db.collection("a_collection").doc("a_document");
			var tempObj = {x: null};
			
			try{
				ref.set(tempObj);
			}
			catch(error){
				console.log(error); 
			}

			return "string";
		},
```

(Note: if I pass anything else for the x field besides null, it works perfectly fine)

When this mutator is called through Graphql Playground I receive the error posted above in Observed Behavior. 

### Digging
- Inside of @google-cloud/firestore/build/src/serializer.js there is a null check and we have found this to be true: 
```
// Works with Apollo 1
            return {
                nullValue: firestore_proto_api_1.google.protobuf.NullValue.NULL_VALUE,
            };

            // Works with Apollo 1 AND 2
            return {
                nullValue: firestore_proto_api_1.google.protobuf.NullValue ? firestore_proto_api_1.google.protobuf.NullValue.NULL_VALUE : null,
            };   
```

- NullValue is literally null, causing an undefined error on `NULL_VALUE`

Again, I am posting here because the only thing that is variable in the execution is Apollo 1 vs Apollo 2

Thank you for your time!!

**Comment by martijnwalraven** [comment]
I realize it's been quite some time since you opened this, but if you haven't already figured this out, I'd recommend taking this question to the [Apollo Server channel within the Apollo community on Spectrum.chat](https://spectrum.chat/apollo/apollo-server) to discuss it further.  Thanks!
