### ISSUE TITLE
Support deprecated directive on input fields

### ISSUE THREAD

**Issue by tomasaschan** [apollographql/apollo-server#1881]
- [x] feature

There is an RFC and reference implementation for supporting `@deprecated` on input fields; see facebook/graphql#525 and graphql/graphql-js#1560. It would be awesome if Apollo could support that too :)

**Comment by jbaxleyiii** [comment]
@tomasaschan as soon as that comes into graphql-js, it will be supported here as well!

**Comment by glasser** [comment]
@eMerzh What aspect of the system is currently not supporting deprecated input fields (when you are using the latest graphql-js)? It's definitely possible for me to believe that the entire Apollo platform doesn't consistently support this new feature but it's easier to answer if you tell me what you tried that didn't work. I'd expect that Apollo Server specifically should just support it out of the box once you upgrade graphql-js.

**Comment by apiel51** [comment]
The graphql-js fix was bundled in the 16.0.0 release [here](https://github.com/graphql/graphql-js/releases/tag/v16.0.0) so until Apollo server can upgrade to v16 this won't get picked up. Upgrading graphql-js to 16 breaks with apollo-server at the moment (3.9.0 is latest)

**Comment by glasser** [comment]
AS3 is supposed to work with graphql-js 16. Are you sure it doesn't? Could there be another dependency that you're using that doesn't support v16?
