### ISSUE TITLE
subscription & apollo-server-express

### ISSUE THREAD

**Issue by mathroc** [apollographql/apollo-server#1893]
when using "apollo-server-express" I have to manually call `installSubscriptionHandlers` to enable subscriptions

it was handled automatically when using "apollo-express"

is this expected ? if that's the case something should probably be added to the doc

**Comment by ksrb** [comment]
It is in the docs on the site but kind of deep:
https://www.apollographql.com/docs/apollo-server/features/subscriptions.html#middleware

Those docs come from a separate package though specifically https://github.com/apollographql/subscriptions-transport-ws:
https://github.com/apollographql/subscriptions-transport-ws/blob/7f2aa27a02789e572aa678ccc98f915b093a5c2e/docs/source/express.md

**Comment by mathroc** [comment]
indeed, closing this then

**Comment by mathroc** [comment]
thx @ksrb
