### ISSUE TITLE
Support a different URL for playground

### ISSUE THREAD

**Issue by mondaychen** [apollographql/apollo-server#1908]
- [ ] feature

I know I can provide parameter `path` when calling `server.applyMiddleware({ app, path });`. But it looks like this path will be used for both the GraphQL API endpoint (when using XHR) and also for the playground (when visiting in a browser). Is it possible to use different URLs for them? e.g. `/api/graphql` for the endpoint and `/graphql-playground` for the playground

**Comment by mondaychen** [comment]
I found https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-express/src/ApolloServer.ts

It does not look like it's supported.

If this sounds like a valid feature request, I can work on this and submit a merge request next week.

**Comment by cs-miller** [comment]
Def interested in this.

**Comment by mondaychen** [comment]
My plan is to add a new option `playgroundPath` in the argument of `applyMiddleware`. If not specified, it will be the same as `path` and everything will stay the same; when it is different from `path`, it will be used as the URL for the playground instead, but the endpoint will still be `path`. Meanwhile, a property `playgroundPath` is added to the server instance so people can read it from outside easily.

**Usage:**
```
server.applyMiddleware({ app, path: '/graphql', playgroundPath: '/graphql-playground' });
```

Let me know if it looks good. Thanks!

**Comment by pratiknikam** [comment]
Any update on this @mondaychen ?

**Comment by mondaychen** [comment]
A little too busy recently :(

Hopefully I can submit the MR by the end of this week

**Comment by abernix** [comment]
Out of curiosity, why isn't it acceptable to use the same path since they shouldn't interfere with each other? (Unless I'm missing something?)

**Comment by mondaychen** [comment]
Hi @abernix 

In my case, I need to protect my graphql API with authentication rules via some nginx/gateway configuration. But for the playground in development mode, I want to get rid of them.

Also, people mentioned a few different use cases and concerns in #1974

**Comment by evenfrost** [comment]
Same for me, faced same authorization problem as well and want to differentiate API route from Playground one.

**Comment by Pocket-titan** [comment]
If I'm not mistaken, the `playground` key accepts an `endpoint` parameter like so:

```javascript
import { ApolloServer } from 'apollo-server'

const server = new ApolloServer({
    playground: {
        endpoint: 'http://localhost:4000/graphql', // I think this is the default one
    },
})
```

So in your case, I believe you could do this (using express here as an example)
```javascript
import express from 'express'
import { ApolloServer } from 'apollo-server-express'

const app = express()

const server = new ApolloServer({
    playground: {
        endpoint: `http://${your_domain_here}:${your_port_here}/graphql-playground`,
    },
})

server.applyMiddleware({
    app,
    path: '/api/graphql',
})

app.listen(your_port_here, () => {
    console.log(`Serving graphql api on /api/graphql and playground on /graphql-playground!`)
})
```
where you'd replace `your_domain_here` and `your_port_here` with your own variables, naturally.
The shape of `endpoint` can be found here: https://github.com/prisma/graphql-playground#properties.

**Comment by Pocket-titan** [comment]
Also, `playground` accepts a `config` key which lets you do more advanced things like set custom headers (seeing from your messages I think maybe you'd like to supply an Authorization token during development that gets you through your API security so you can easily access the playground):
```javascript
const config = {
  projects: {
    prisma: {
      schemaPath: 'src/generated/prisma.graphql',
      includes: ['database/seed.graphql'],
      extensions: {
        prisma: 'database/prisma.yml',
        'prepare-binding': {
          output: 'src/generated/prisma.ts',
          generator: 'prisma-ts',
        },
        endpoints: {
          dev2: {
            url: 'https://eu1.prisma.sh/public-asdf/session65/dev',
            headers: {
              Authorization:
                'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNlcnZpY2UiOiJhc2RmQGRldiIsInJvbGVzIjpbImFkbWluIl19LCJpYXQiOjE1MjM1MTg3NTYsImV4cCI6MTUyNDEyMzU1Nn0.fzKhXa1JpN9M1UGTbS6p2KMUWDrKLxYD3i3a9eVfOQQ',
            },
          },
        },
      },
    },
    app: {
      schemaPath: 'src/schema.graphql',
      includes: ['queries/{booking,queries}.graphql'],
      extensions: {
        endpoints: {
          default: 'http://localhost:4000',
        },
      },
    },
  },
}
```
(taken from https://github.com/prisma/graphql-playground/blob/master/packages/graphql-playground-react/src/localDevIndex.tsx#L47)

Is this enough customisation for you or do you need something else?

**Comment by yukw777** [comment]
Any updates on this? I need this precisely b/c of the scenario @mondaychen described.

btw, @Pocket-titan, what you describe doesn't work as the `endpoint` config variable refers to the graphql api endpoint playground hits, rather than the endpoint at which playground is served.

**Comment by Pocket-titan** [comment]
Ah, thank you @yukw777, I was misinterpreting the issue.

I think you might be better off forking the specific package that you need and modifying it yourself. For example, glancing at [packages/apollo-server-express/src/ApolloServer.ts](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-express/src/ApolloServer.ts) in the express implementation, all you'd have to add is something like

```typescript
...
export interface ServerRegistration {
    ...
    playgroundPath?: string;
}
...
public applyMiddleware({
    ...
    playgroundPath,
  }: ServerRegistration) {
    ...
    if (!playgroundPath) playgroundPath = path;
    ...
    app.use(Array.from(new Set([path, playgroundPath])), (req, res, next) => {
        if (req.path === playgroundPath && this.playgroundOptions && req.method === 'GET') {
            ...
        } else if (req.path === path) {
            return graphqlExpress(() => {
                return this.createGraphQLServerOptions(req, res);
            })(req, res, next);
        }
    });
}
```
b/c a PR will probably only be accepted if it includes _all_ apollo-server packages, leaving you to do more work than necessary for you own situation.

**Comment by carlosbaraza** [comment]
Not sure if this would be useful to anyone, but I solved the problem like this:

```js
  // Allow GET (Playground)
  // Authenticate other GraphQL queries
  app.use(path, (req, res, next) => {
    if (req.method === "GET") {
      return next();
    }
    authJwt(req, res, next);
  });
```

**Comment by thardy** [comment]
I'm really needing this functionality.  Any word on this?  I'm monitoring #1974 and it seems to be stalled.

**Comment by swac** [comment]
We found a workaround for this, by essentially serving GraphQL Playground manually on a separate endpoint, as explained in the examples [here](https://github.com/prisma-labs/graphql-playground#as-server-middleware). It'd be nice if Apollo offered flexibility here though!

**Comment by tychay** [comment]
I used @swac workaround, but ran into an issue in that you have to turn on `introspection` in production (a security no-no).

The fix I found is to enable it in production, but then create an [Apollo plugin](https://www.apollographql.com/docs/apollo-server/integrations/plugins/#installing-a-plugin) to intercept it and have it block response execution if user isn't authenticated. This way you can go create an Authorization bearer token in the HTTP Headers in the playground to enable things.

Here is some pseudocode for the plugin…
```
{
  requestDidStart() {
  return {
    /**
     * Look at query and return error if query is an introspection but
     * not on dev or bearer token is not authenticated super user.
     * @param requestContext
     */
    async responseForOperation(requestContext) {
      // If it is not introspection, then pass it on through
      if ( !requestContext.request.query.includes('__schema') ) {
        return null;
      }

      // Do authentication here `requestContext.context` has context. Return `null` if authenticated.

      // Return error
      throw new AuthenticationError('GraphQL introspection is not allowed by Apollo Server, but the query contained __schema or __type. To enable introspection, pass introspection: true to ApolloServer in production');
      return {};
    }, //of responseForOperation
  }; // of return
}
'''

Note that looking at the Apollo codebase, it also traps `__type` queries. Also I doubt `AuthenticationError` and `GraphQLError` are identical since they are different parts of the tree. I'm open to any improvements to the above.

**Comment by savtwo** [comment]
The following makes the endpoints `/playground` and `/voyager` available in `development` only and keeps two endpoints `/api` and `/graphql` protected with authentication/authorization.

```javascript
const server = new ApolloServer({
  schema,
  context: async ({ req }) => {
    return getContext(req.user);
  },
  introspection: process.env.NODE_ENV !== 'production',
  playground: process.env.NODE_ENV !== 'production',
});

app.use(
  ['/api', '/graphql'], // paths to support authentication/authorization
  checkJwt, // auth middleware
  require('./routes')
);

// add public route to access `/playground`
server.applyMiddleware({ app, path: ['/graphql', '/playground'] });

// make available only for development
if (process.env.NODE_ENV === 'development') {
  app.use('/voyager', voyagerMiddleware({ endpointUrl: '/playground' }));
}
```

**Comment by savtwo** [comment]
The following should allow you to have Playground and Voyager available in a `development` environment. This will keep the `/graphql` endpoint protected by auth.

```javascript
const server = new ApolloServer({
  schema,
  context: async ({ req }) => {
    return getContext(req.user);
  },
  introspection: process.env.NODE_ENV !== 'production',
  playground: process.env.NODE_ENV !== 'production',
});

app.use(
  ['/api', '/graphql'], // protected endpoints
  checkJwt, // middlware for authentication
  checkPermissions, // middleware for authorization
  require('./routes')
);

// only make `/playground` available in `development` environment
const path =
  process.env.NODE_ENV === 'development'
    ? ['/graphql', '/playground']
    : ['/graphql'];
server.applyMiddleware({ app, path });

// point voyager to `/playground` instead of `/graphql`
if (process.env.NODE_ENV === 'development') {
  app.use('/voyager', voyagerMiddleware({ endpointUrl: '/playground' }));
}
```

**Comment by marktheunissen** [comment]
Ideally we would be able to have the playground running with introspection on a separate endpoint e.g. `/graphql-playground`, but no introspection allowed on the primary world-facing `/graphql`. Then we could protect the playground API path so that it's just accessible by internal developers, and keep introspection running for only that path.

**Comment by thardy** [comment]
The separate endpoint is critical.  I got it working myself, mainly from threads like these, but it was a major pain in the butt.  I really wish the maintainers would see the need and do something about it.

**Comment by DarkLite1** [comment]
@thardy how did you solve it to have the playground on another uri than the graphql server?

**Comment by thardy** [comment]
I created two separate Apollo servers with two separate Express apps.  A very rough pseudo-code is below...

 ```
const playgroundApolloServer = createApolloServer();
    // main server app
    const main = express();
    playgroundApolloServer.applyGraphQlPlaygroundMiddleware({
        app: main,
        path: '/graphql',
    });

    const apiApolloServer = createApolloServer();    
    const siteApp = express();
    apiApolloServer.applyGraphQlApiMiddleware({
        app: siteApp,
        path: '/graphql-api',
        db: db,
    });
```

**Comment by JosiasAurel** [comment]
I don't know if this helps but doing this worked for me

```javascript
const server = new ApolloServer({
        typeDefs,
        resolvers,
        playground: {
               cdnUrl: "http://127.0.0.1:7000/"
         }
})
````
Here just replace `cdnUrl` by the Uri that you have setup to serve the static assets.

> I still had to follow a specific directory structure (structure in CDN URL in script tags) to get this done correctly

**Comment by jarvisuser90** [comment]
I'm also in need of this feature. Any update on this?

**Comment by glasser** [comment]
In Apollo Server 3, playground won't be as hardcoded into Apollo Server as it is in v2. We have a simple landing page plugin API that will make it easy to build your own very basic landing page plugin that works with all the Apollo Server web framework integrations.  Alternate landing page features can be prototyped as separate plugins.

The flipside is that the fundamental model of how Apollo Server integrates into lots of frameworks makes "serve GraphQL in one place and landing page in another place" challenging, because Apollo Server (other than the `apollo-server` batteries-included package) is kind of "just another middleware".  Making a single middleware that serves distinct data on two different paths is actually a bit of a challenge to do portably. Installing UI and API middlewares separately seems like a more understandable model.
