### ISSUE TITLE
Custom scalar type's resolver methods are not getting invoked 

### ISSUE THREAD

**Issue by hiteshbal91** [apollographql/apollo-server#1917]
I am using apollo-server with required parameters of typeDefs and resolvers. Still my custom scalar type "ISODate" is not being invoked.

```
Type 
`scalar ISODate`

Resolver 

new GraphQLScalarType({
    name: 'Date',
    description: 'ISODate String used for date data type.',
    serialize: (value: string): any => {
        console.log("ISODateValidate : ", value);
        if (!ISODateRegex.test(value))
            throw new Error('Invalid ISODate provided.');
        return value;
    },
    parseValue: (value: string): any => {
        console.log("ISODateValidate : ", value);
        if (!ISODateRegex.test(value))
            throw new Error('Invalid ISODate provided.');
        return value;
    },
    parseLiteral: (ast) => {
        console.log("parseLiteral : ", ast);
        if (ast.kind === Kind.STRING) {
            return new Date(ast.value);
        }
        return null;
    }
})
```

I have set the ISODate resolvers on root level only, also ISODate data type is being called on other data type but I am not able to see any consoles of ISODate scalar type.

**Comment by trevor-scheer** [comment]
Hey @hiteshbal91, thanks for opening an issue. At first glance, it looks like your snippet has a name mismatch (`ISODate` <> `Date`). If this isn't the root of your issue, could you please provide a reproduction?

**Comment by hiteshbal91** [comment]
@trevor-scheer Looks like that was from my end, thanks for checking.
