### ISSUE TITLE
Add Context to Constructor as optional, generic argument

### ISSUE THREAD

**Issue by floric** [apollographql/apollo-server#1918]
Hey,
I have a small feature request (and could create a MR if you agree).
`new ApolloServer()` is the current constructor with support for context modifications using context functions. The context function is currently always any-typed as `Context<any>` overrides the function types. I would like to extend the constructor to include optional typings and passing them to `Config<Context = any>`. This would not break anything AFAIK but make contexts more typesafe.

Example:

```
type MyCustomContext = { test: number };

VALID: const server = new ApolloServer<MyCustomContext>({context: c => ({test: 0}});
INVALID: const server = new ApolloServer<MyCustomContext>({context: c => ({abc: 0}});
```

What do you think?

**Comment by floric** [comment]
No ideas? I would be happy to propose a MR.

**Comment by trevor-scheer** [comment]
Hey @floric, thanks for submitting this (and offering to make the fix!). This seems like a reasonable request - if you'd like to submit a PR for this, we can take a look. Thanks!
