### ISSUE TITLE
Latest release: Apollo server fails to install due to missing graphql-extensions@0.3.0

### ISSUE THREAD

**Issue by GlennMatthys** [apollographql/apollo-server#1930]
- [X ] blocking

On an empty directory:

```
>npm install apollo-server -S
npm ERR! code ETARGET
npm ERR! notarget No matching version found for graphql-extensions@0.3.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'apollo-server-core'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\glenn.matthys\AppData\Roaming\npm-cache\_logs\2018-11-07T17_37_52_980Z-debug.log

>
```

Debug logfile from npm: [2018-11-07T17_37_52_980Z-debug.log](https://github.com/apollographql/apollo-server/files/2558535/2018-11-07T17_37_52_980Z-debug.log)

**Comment by petetnt** [comment]
Have you tried removing `package-lock.json`, seems to work on https://codesandbox.io/s/q9pwvyomo6 and locally for me 🤔

**Comment by GlennMatthys** [comment]
This was done on an empty directory. I did try removing package-lock.json and node_modules on an existing node project, same issue.

**Comment by petetnt** [comment]
Ah, missed the empty directory line. Sorry about that.

**Comment by GlennMatthys** [comment]
As discussed on Slack, looks to be fixed now. It was an npm registry caching problem.
