### ISSUE TITLE
A bunch of your docs are 404ing 

### ISSUE THREAD

**Issue by stephenhandley** [apollographql/apollo-server#1932]
Here's a couple linked to from the sidebar here that are 404ing.. I'm guessing there are more
https://www.apollographql.com/docs/apollo-server/v2/

Both 404: 
https://www.apollographql.com/docs/guides/security.html
https://www.apollographql.com/docs/guides/access-control.html

**Comment by JoviDeCroock** [comment]
I've tried looking into this issue, when inspecting the documentation I can see these files located at docs/best-practices but they seem empty.

**Comment by abernix** [comment]
Some documentation was shuffled with the release of the new platform documentation. 

We believe these are now fixed via redirects to the content's new location.  Thanks for reporting this!
