### ISSUE TITLE
Requiring auth header for introspection queries 

### ISSUE THREAD

**Issue by stephenhandley** [apollographql/apollo-server#1933]
I'm wondering if there's a way to allow introspection queries only when a valid authorization header is passed. 

I have introspection disabled outside development, but our client app needs to fetch the schema to be used in code generation for the iOS Apollo client as described here:
https://www.apollographql.com/docs/ios/downloading-schema.html

Currently it looks like I can only enable or disable configuration via a boolean `introspection` option passed in the config to the `ApolloServer` constructor. 

I'd like to allow the client developer access to that introspection query if they include a valid internal token in the auth header. Is that possible?

**Comment by the-noob** [comment]
It is not possible at the moment but I'm also looking for something similar.
Ideally `introspection` should be changed to be a `bool` or `function that receives the request as `context` and returns `true/false`.

**Comment by ftatzky** [comment]
@stephenhandley you could use `formatResponse`

**Comment by stephenhandley** [comment]
@ftatzky I don't follow. I'm familiar with `formatResponse` but as I understand it that gets called after the request cycle, and if `intrsopection`is false, it'll never reach that point. Maybe I'm missing something though, could you please elaborate?

**Comment by stephenhandley** [comment]
@ftatzky ok, understood. the issue there is then that we have the performance overhead of introspection on every session query, regardless of whether they are an internal user (i.e for whom introspection would be appropriate)

**Comment by KATT** [comment]
> [..] the issue there is then that we have the performance overhead of introspection on every session query

And the reverse is true too. We execute the query even if we can know before that it will fail. 

Note: In graphql-yoga you can make validation rules that are aware of express' `req` object [like this](https://github.com/prisma/graphql-yoga/blob/master/examples/query-complexity/index.js#L45).

**Comment by nether-cat** [comment]
I really like @the-noob's suggestion! 

> It is not possible at the moment but I'm also looking for something similar.
> Ideally `introspection` should be changed to be a `bool` or `function that receives the request as `context`and returns`true/false`.

**Comment by trevor-scheer** [comment]
Hey @stephenhandley, this can be accomplished via the request pipeline. The docs aren't published yet, but you can take a look here: https://github.com/apollographql/apollo-server/pull/2008

**Comment by richardscarrott** [comment]
Does anybody know if this is possible today?

**Comment by danielmahon** [comment]
@nether-cat  Would this be a valid way of protecting JUST the introspection query? I still want certain unauthorized queries to pass, like a `login`.

This plugin is currently checking for 3 things:
1. If the query includes `__schema`.
2. If the query includes `__type`.
3. Requires an authorization header if `__schema` or `__type` is found in the query.

Am I missing any obvious loopholes? Is there a better way to do this now?

```ts
const secureIntrospection = {
  requestDidStart: ({ request, context }) => {
    if (
      (request.query.includes('__schema') ||
        request.query.includes('__type')) &&
      !context.req.get('authorization')
    ) {
      throw new AuthenticationError('GraphQL introspection not authorized!');
    }
  },
};

const graphQLServer = new ApolloServer({
  schema: schemaWithMiddleware,
  context: contextMiddleware,
  engine: { apiKey: CONFIG.ENGINE_API_KEY },
  subscriptions: { path: '/' },
  plugins: [secureIntrospection],
  introspection: true,
  // Development only
  playground: CONFIG.IS_DEVELOPMENT,
  debug: CONFIG.IS_DEVELOPMENT,
  tracing: CONFIG.IS_DEVELOPMENT,
});
```

**Comment by rheaditi** [comment]
> @nether-cat Would this be a valid way of protecting JUST the introspection query? I still want certain unauthorized queries to pass, like a `login`.
> 
> This plugin is currently checking for 3 things:
> 
> 1. If the query includes `__schema`.
> 2. If the query includes `__type`.
> 3. Requires an authorization header if `__schema` or `__type` is found in the query.
> 
> Am I missing any obvious loopholes? Is there a better way to do this now?
> 
> NOTE: Invalid authorization headers may pass this check but are caught in my context middleware, where if there is an authorization header, it is validated.
> 
> ```ts
> const secureIntrospection = {
>   requestDidStart: ({ request, context }) => {
>     if (
>       (request.query.includes('__schema') ||
>         request.query.includes('__type')) &&
>       !context.req.get('authorization')
>     ) {
>       throw new AuthenticationError('GraphQL introspection not authorized!');
>     }
>   },
> };
> 
> const graphQLServer = new ApolloServer({
>   schema: schemaWithMiddleware,
>   context: contextMiddleware,
>   engine: { apiKey: CONFIG.ENGINE_API_KEY },
>   subscriptions: { path: '/' },
>   plugins: [secureIntrospection],
>   introspection: true,
>   // Development only
>   playground: CONFIG.IS_DEVELOPMENT,
>   debug: CONFIG.IS_DEVELOPMENT,
>   tracing: CONFIG.IS_DEVELOPMENT,
> });
> ```

@danielmahon Thanks for this example!

We used something like this in our codebase and released it as a package for usage across our products; referenced this comment in the package. 

If anyone is interested:-
https://github.com/ClearTax/apollo-server-plugin-introspection-auth

**Comment by scherroman** [comment]
We wanted only authenticated backend clients to be able to introspect in production, and the [apollo-server-plugin-introspection-auth](https://github.com/ClearTax/apollo-server-plugin-introspection-auth) plugin doesn't really check what we need,  so we wrote our own basic plugin for this like @danielmahon mentioned above. 

Note though that using `request.query.includes('__schema') || request.query.includes('__type'))`  would also reject any queries asking for `__typename` like those that Apollo Client makes, so better to use a regex with word breaks like the [apollo-server-plugin-introspection-auth](https://github.com/ClearTax/apollo-server-plugin-introspection-auth) plugin does:

```
const INTROSPECTION_QUERY_REGEX = /\b(__schema|__type)\b/

const restrictIntrospectionPlugin = {
    requestDidStart: ({ request, context }) => {
        if (
            INTROSPECTION_QUERY_REGEX.test(request.query)
        ) {
            let isIntrospectionAuthorized = process.env.NODE_ENV === 'production' ? isBackendClient(context) : true

            if (!isIntrospectionAuthorized) {
                throw new AuthenticationError(
                    'GraphQL introspection not authorized!'
                )
            }
        }
    }
}

module.exports = { restrictIntrospectionPlugin }
```

**Comment by andyrichardson** [comment]
I noticed a lot of the suggestions here use approaches like regex which could be easily bypassed - and in some cases introduce a security vulnerability.

```gql
# Fake introspection query to bypass auth
query IntrospectionQuery {
  __schema {
    __typename
  }
}

# Some mutation that no longer requires auth 
mutation MaliciousMutation {
  deleteThing(id: 1234)
}
```

I've [made a gist here](https://gist.github.com/andyrichardson/0f9c7580c38d0fefa904046aa893131c) which checks that the query is actually an introspection query and not just a query containing introspection.

**Comment by tbrannam** [comment]
@andyrichardson approach is great - but could be better suited to pair with the PluginDefinition callback for `didResolveOperation` which has the advantage of not having to scan or parse all documents twice.  Reducing the runtime overhead of the check.

**Comment by andyrichardson** [comment]
Cheers @tbrannam yeah you're right!

I guess my main point is that the suggestions prior could lead to security vulnerabilities

**Comment by elier-lg** [comment]
@trevor-scheer 
I have been following up the question posted  by @stephenhandley since I have currently the same issue. I read the post on [#2008](https://github.com/apollographql/apollo-server/pull/2008) 

Buts still not able to understand how to avoid that the Introspection call made from Gateway to federated service to get broken for not having Auth Header.

The only way I can bypass that issue is by adding a hardcoded Auth header like:
```
const gateway = new ApolloGateway({
  serviceList: config.serviceList,
  introspectionHeaders: (p: any) => 

> {

      return { Authorization:  'Bearer someValid token  };  // <------- Hardcoding here
  },
  
 buildService: ({ url }) => {
    return new RemoteGraphQLDataSource({
      url,
      willSendRequest: ({ request, context }: { request: GraphQLRequest; context: any }) => {
        request?.http?.headers.set('Authorization', context.auth);
      }
    });
  },
});

const server = new ApolloServer({
  context: {auth: 'some Valid token'} ,
  gateway
});

```

And this is because during first time call to federated service ('Introspection call')  the context is received in **willSendRequest** params is empty.

But this is not a valid solution since the hardcoded token expires and then the pipeline gets broken again and throws error: _An error occurred during Apollo ..... 400: Bad Request.

**Comment by glasser** [comment]
It would be nice if the same mechanism that we use to implement `introspection: false` could be used here. That's a validation rule passed to the `graphql-js` validate mechanism. However, graphql-js validation rules don't have access to any request-specific context, and apollo-server doesn't provide a way for context-specific validation rules.

Perhaps we could give the `validationDidStart` plugin hook the ability to return/provide more validation rules? And also export `NoIntrospection` so it's easy to return from your own plugin hook?  (Since it already returns an end hook, we either need to refactor it so that it can return a hook or an object with rules and a hook, or add a new callback, or something.)

@elier-lg In general it is a bad idea if your subgraph servers are directly accessible to end users, so locking down introspection there shouldn't be that relevant. That said, we generally recommend the use of managed federation rather than doing composition inside your graph for production work.

**Comment by uripre** [comment]
> 

@andyrichardson Could you clarify how this introduces a security vulnerability? How does the introspection "bypass" authentication?

**Comment by thekip** [comment]
Using validation + plugin. 

```ts
import { ApolloServerPlugin, GraphQLRequestListener } from 'apollo-server-plugin-base';
import { GraphQLRequestContext, GraphQLRequest } from 'apollo-server-types';
import { NoSchemaIntrospectionCustomRule, validate } from 'graphql';

const isDevelopment = process.env.NODE_ENV === 'development';

export class ConditionalIntrospectionGraphqlPlugin implements ApolloServerPlugin {
  constructor(private checkFn: (request: GraphQLRequest) => boolean) {
  }

  public async requestDidStart(_requestContext: GraphQLRequestContext<any>): Promise<GraphQLRequestListener> {
    return {
      didResolveOperation: async (ctx) => {
        if (isDevelopment) {
          return;
        }

        if (this.checkFn(_requestContext.request)) {
          return;
        }

        const errors = validate(ctx.schema, ctx.document, [NoSchemaIntrospectionCustomRule]);

        if (errors.length) {
          throw errors;
        }
      },
    };
  }
}
```

Then in apollo server config: 

```ts
     // Introspection is controlled by ConditionalIntrospectionGraphqlPlugin
      introspection: true,
      plugins: [
        new ConditionalIntrospectionGraphqlPlugin((request) => {
          const key = request.http.headers.get(INTROSPECTION_HEADER);

          if (key) {
            return key === INTROSPECTION_KEY;
          }
        }),
      ],
```

Note, this `NoSchemaIntrospectionCustomRule` officially provided by `graphql-js`, and AFAIK used in the apollo server when `introspection: false`

**Comment by AaronMoat** [comment]
If anyone wants a drop-in package for this, I've put something on npm: https://www.npmjs.com/package/apollo-server-plugin-conditional-introspection

**Comment by sb-onoffice-de** [comment]
> Using validation + plugin.
This works for us! Thank you!
