### ISSUE TITLE
Optional non nullable fields

### ISSUE THREAD

**Issue by matthew1534** [apollographql/apollo-server#1942]
Currently, it seems that nullable fields that have had a null value passed in bypass the custom scalars. When updating our API we have fields that are not required however if they are passed in they cannot have a null value. I was hoping to block these null values for specific fields using custom scalars but this doesn't seem possible. Full details RE the issue here: https://stackoverflow.com/questions/53194116/optional-but-non-nullable-fields-in-graphql/53200665

I have also tried to use validationRules however it seems this doesn't deal with variables and I've tried visitInputFieldDefinition directives but there doesn't seem to be a resolve function that can be called - see this issue: https://github.com/apollographql/graphql-tools/issues/858

This is quite a large issue for us as null values effectively attempt to delete data from the database, which shouldn't be possible on every field without a `!` on an update. Is there any way to work around this or any plan to route null values though custom scalars / add a resolve function to input directives?

**Comment by JakeDawkins** [comment]
Since this isn't something that's really supported by the GraphQL language, there's not much we can do here. We'd suggest doing the work in the resolvers to strip any erroneous `null` values that are passed in.
