### ISSUE TITLE
apollo-server-koa: Please upgrade to dependencies that have graphql 14.0.0 to peerDependencies

### ISSUE THREAD

**Issue by jonaskello** [apollographql/apollo-server#1946]
apollo-server-koa as of 2.2 has graphql 14.0.0 as peerDependency which is great! However some of the related dependencies do not have graphql 14.0.0 as peerDependency at the version apollo-server-koa is using them.

```
apollo-server-koa > @apollographql/apollo-upload-server@5.0.3" has incorrect peer dependency "graphql@^0.13.1".
apollo-server-koa > apollo-server-core > graphql-tag@2.9.2" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
```

I think the latest versions of graphql-tag and @apollographql/apollo-upload-server supports graphql 14.0.0 so if apollo-server-koa and apollo-server-core could upgrade its dependencies to the latest version it would be solved.

**Comment by ellipticaldoor** [comment]
bump

**Comment by grantwwu** [comment]
Appears to be a partial dupe of https://github.com/apollographql/apollo-server/issues/1854 - I think it would be pretty easy for someone to make a PR to bump `graphql-tag` though?

**Comment by jonaskello** [comment]
@abernix  I did a test run. It solves one warning but the one for `graphql-tag` still exits:

With `apollo-server-koa@^2.2.0`:

```
apollo-server-koa > @apollographql/apollo-upload-server@5.0.3" has incorrect peer dependency "graphql@^0.13.1".
apollo-server-koa > apollo-server-core > graphql-tag@2.9.2" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
```


With `apollo-server-koa@2.3.0-alpha.0`:

```
apollo-server-koa > apollo-server-core > graphql-tag@2.9.2" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
```

**Comment by abernix** [comment]
Thanks for the feedback.  I'll get that fixed.

**Comment by abernix** [comment]
@jonaskello Hmm, I'm surprised you're running into this since I don't have this problem myself and the semver range on `apollo-server-core` definitely accommodates `graphql-tag@2.10.0`, which has the [correct semver `peerDependencies` for `graphql`](https://github.com/apollographql/graphql-tag/blob/5f9dc1727b187f4ac7fe974684ec3ef1dae197d2/package.json#L34).

```sh
$ npm view apollo-server-core dependencies | grep graphql-tag
  'graphql-tag': '^2.9.2',
```

and `npm ls graphql-tag` in a brand new package with only `apollo-server` installed:

```
$ npm ls graphql-tag
tmp.kMNChq4L@1.0.0 /private/var/folders/mq/s5hmqjmx7djftqd_2fqjfn0w0000gn/T/tmp.kMNChq4L
└─┬ apollo-server@2.2.6
  └─┬ apollo-server-core@2.2.6
    └── graphql-tag@2.10.0
```

**Comment by jonaskello** [comment]
@abernix You are correct, this is fixed. I ran `yarn add apollo-server-koa@2.3.0-alpha.0` and after that I still saw the warning. However I realised now that yarn.lock actually locked down the version of `graphql-tag`. After running `yarn upgrade` all apollo-server warnings are gone! Sorry for wasting your time!

**Comment by abernix** [comment]
No harm, no waste.  Thanks for checking and reporting back.  Much appreciated! (And glad to hear this is all fixed up.)

**Comment by abernix** [comment]
The `alpha` releases didn't identify any problems so I've graduated this to the official `apollo-server-*@2.3.0` releases.
