### ISSUE TITLE
Typescript Compile fails for 2.2.1 -ERROR

### ISSUE THREAD

**Issue by danielgary** [apollographql/apollo-server#1951]
When running tsc, the following error occurs.  

Definitions of the following identifiers conflict with those in another file: RequestInfo, Headers, HeadersInit, Body, Request, RequestInit, RequestMode, RequestCredentials, RequestCache, RequestRedirect, ReferrerPolicy, Response, ResponseInit, BodyInit, URLSearchParams

**Comment by czystyl** [comment]
I faced the same problem, happens just after importing module:
```
import { ApolloServer } from 'apollo-server-express';
```

full error message: 


```$ tsc --noEmit
node_modules/apollo-env/lib/global-fetch.d.ts:1:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: RequestInfo, Headers, HeadersInit, Body, Request, RequestInit, RequestMode, RequestCredentials, RequestCache, RequestRedirect, ReferrerPolicy, Response, ResponseInit, BodyInit, URLSearchParams

1 declare function fetch(
  ~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:25:1
    25 interface Account {
       ~~~~~~~~~
    Conflicts are in this file.

node_modules/typescript/lib/lib.dom.d.ts:25:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: RequestInfo, Headers, HeadersInit, Body, Request, RequestInit, RequestMode, RequestCredentials, RequestCache, RequestRedirect, ReferrerPolicy, Response, ResponseInit, BodyInit, URLSearchParams

25 interface Account {
   ~~~~~~~~~

  node_modules/apollo-env/lib/global-fetch.d.ts:1:1
    1 declare function fetch(
      ~~~~~~~
    Conflicts are in this file.

node_modules/typescript/lib/lib.dom.d.ts:16316:11 - error TS2320: Interface 'Window' cannot simultaneously extend types 'GlobalFetch' and 'WindowOrWorkerGlobalScope'.
  Named property 'fetch' of types 'GlobalFetch' and 'WindowOrWorkerGlobalScope' are not identical.

16316 interface Window extends EventTarget, WindowTimers, WindowSessionStorage, WindowLocalStorage, WindowConsole, GlobalEventHandlers, IDBEnvironment, WindowBase64, GlobalFetch, WindowOrWorkerGlobalScope, WindowEventHandlers {
                ~~~~~~
```

**Comment by lemol** [comment]
I solved this issue setting `"esModuleInterop": true` on `tsconfig.json`.

Reference: #1189#issuecomment-398847024

**Comment by ssube** [comment]
Setting `"esModuleInterop": true` as suggested here, in #1182, and #1189, did not fix the apollo-server/http `no default export` errors for me either. It did introduce import errors with other modules (which were not fixed by replacing `* as` imports). My [attempted changes are here](https://github.com/ssube/isolex/commit/8cb8cfe9277e579b5457e7b313699cb7437aa7ec).

**Comment by RockNHawk** [comment]
maybe your project have a sub folder and the sub fodler also has an `node_modules` folder, delete it may works.

**Comment by trevor-scheer** [comment]
Hey @RockNHawk, thank you for trying to be helpful. This issue is closed and about 5 years old, so it's highly unlikely that it's still relevant.
