### ISSUE TITLE
Facing a delay when trying to authenticate a user

### ISSUE THREAD

**Issue by juanpablogdl** [apollographql/apollo-server#1952]
Trying to authenticate users via JWT, at the moment everything is fine except for one really weird issue

in my ApolloClient  i have this code:

```
const client = new ApolloClient({
  uri: "http://localhost:4000/graphql",
  // sends token to the backend
  fetchOptions: {
    credentials: 'include'
  }, 
  request: operation => {
    const token = localStorage.getItem('token');
    operation.setContext({
      headers: {
        authorization: token
      }
    });
  },
  cache: new InMemoryCache({
    addTypename: false
  }),
  onError: ({ networkError, graphQLErrors }) => {
    console.log('graphQLErrors', graphQLErrors);
    console.log('networkError', networkError);
  }
});
```

in this request i'm sending the token that i have from localstorage to the backend:

```
  request: operation => {
    const token = localStorage.getItem('token');
    operation.setContext({
      headers: {
        authorization: token
      }
    });
  },
```

when i submit the form i can see the Token in LocalStorage tab :

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiYSIsImlhdCI6MTU0MjA3MjUyNiwiZXhwIjoxNTQyMDc2MTI2fQ.rG_5ReXY0ImRx9h7NhJLEX5cEL2dhA3OnwQxbwaNLLs

in my server (i'm using apollo-server-express) i'm reading the value via context

```
const server = new ApolloServer({ 
  typeDefs, 
  resolvers,
  context:  ({req}) => {
      // obtener token de header
      const token = req.headers['authorization'];

      console.log(token);
  }
});
```

i'm sending the token to the console

the weird thing is:
when the storage is clean, i get in my console:
null

but, when i have something in the storage, the console is printing the  previous token, not the current token, so my guess is that between ApolloClient and ApolloServer is a small delay or both are running at the same time even before storage is created , how to fix this??

i tried this snippet (and other simillars)
```
if (token) {
try {
return await jwt.verify(token, process.env.SECRET);
} catch (e) {
throw new AuthenticationError(
'Your session expired. Sign in again.',
);
}
```

but it didn't help, i'm getting the 'Your session expired. Sign in again.' message all the time

**Comment by martijnwalraven** [comment]
Closing this because the issue seems resolved.
