### ISSUE TITLE
Support/help for AWS API gateway to lambda integration type `LAMBDA`

### ISSUE THREAD

**Issue by terencenero007** [apollographql/apollo-server#1964]
I was using the **graphql-server-lambda@1.0.4** to create a graphql server with node.js and deploy it as a lambda function to AWS with the help of serverless framework. 

The handler function returned by graphqlLambda from the `graphql-server-lambda` package assumes that the event you pass into it is an `http` event.

I have configured  API gateway to lambda integration as `LAMBDA`, due to which the lambda event has the key `method` rather than `httpMethod`. As a workaround to this, I used to modify the incoming event object and set the `httpMethod ` key's value manually. This was possible becaues the package would export the `graphqlLambda` object. This is not the case in the **apollo-server-lambda@latest** package

Is there any way to solve this either by:
1. Directly using the `graphqlLambda` object which is used [here](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-lambda/src/ApolloServer.ts#L164) but not exported
2. Update the package to support integration type `LAMBDA`

Here is my code of the old that uses the old package and the new code that I am trying to run.

**graphql-server-lambda@1.0.4**
```javascript
// handler.js

import {
  graphqlLambda,
} from 'graphql-server-lambda';

exports.graphql = (event, context, callback) => {
  const handler = graphqlLambda((innerEvent, innerContext) => {

    return {
      schema,
      context: {
        ...innerEvent,
        ...innerContext,
      },
    };
  });

  return handler({
    ...event,
    httpMethod: event.method
  }, context, callbackFilter);
};
```

**apollo-server-lambda@latest**
```javascript
const { ApolloServer, gql } = require('apollo-server-lambda');

// Construct a schema, using GraphQL schema language
const typeDefs = gql`
  type Query {
    hello: String
  }
`;

// Provide resolver functions for your schema fields
const resolvers = {
  Query: {
    hello: () => 'Hello world!',
  },
};

const server = new ApolloServer({ typeDefs, resolvers });

exports.graphqlHandler = server.createHandler();
```

and the API Gateway configuration has

METHOD REQUEST => Auth: authorizer
INTEGRATION REQUEST => Type: LAMBDA
properties.

**serverless.yml**

```yml
service: apollo-lambda-test
provider:
  name: aws
  runtime: nodejs8.10
functions:
  graphql:
    handler: handler.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
        integration: lambda
plugins:
  - serverless-offline
```

I have gone through the entire package, documentation and all the issues. But there seems to be no lead on how to utilize integration type `LAMBDA`
 
I'm ready to provide any information is needed to reproduce the issue.

Any help would be greatly appreciated.

**Comment by abernix** [comment]
I'll close this as it's quite old at this point.  Apologies we hadn't been able to get to this _much_ sooner.  If you're still struggling with it, please try the newer `apollo-server-lambda` and hop on over to the [Apollo community on Spectrum.chat](https://spectrum.chat/apollo) for any questions.  Thanks!
