### ISSUE TITLE
Breakpoints do not get hit if there is an error in the resolver

### ISSUE THREAD

**Issue by cesarvarela** [apollographql/apollo-server#1975]
HI, I'm not sure if this is a bug or a feature request, but when developing , if there is an error in a resolver, breakpoints do not get hit. This is in vscode btw.
  
edit:
It doesn't matter if I wrap all resolver the code in a try/catch block either, it's just bad DX

**Comment by magicmark** [comment]
@cesarvarela if you could add some sample code (ideally a [minimum reproducible example](https://stackoverflow.com/help/mcve)), that would allow us to help you better. It's not clear from your current post where the error lies :)

**Comment by trevorblades** [comment]
@cesarvarela if your breakpoints are after the erroring line of code, I believe it would be expected behaviour for those breakpoints to not be hit. I'm closing this issue for now, but if I've misunderstood, please reopen with a reproducible example as @magicmark suggested
