### ISSUE TITLE
MySQL/SQL Connector and Models

### ISSUE THREAD

**Issue by manuelfink** [apollographql/apollo-server#198]
## Is there any best practise recommendation or sample implementation for sql models and connectors yet?

The [connector and models design description](https://github.com/apollostack/graphql-tools/blob/master/connectors.md) describe how to provide connectors and contexts. Issue #118 is discussing how to implement context and models as well. Thus I'm curious that is the best approach.

### GraphQL MySQL Connector - directly use knex db layer?

[sql connector in the githunt-api](https://github.com/apollostack/GitHunt-API/blob/master/api/sql/connector.js) sample just returns knex directly not bringing in any additional connector logic for sql. I expect knex already having enough logic not making it necessary to extend the connector? Thereas for an rest api we would have to implement a lot of logic for query optimization and caching our selves? Or do you plan to implement additional logic on top of a db abstraction layer?

### Knex vs Sequelize
Is there any reason why you prefer knex over sequelize?

**Comment by HriBB** [comment]
I am trying to figure out the same thing.

Using Sequelize with GraphQL is a little bit tricky. If you don't load your data correctly, you can end up running lots of queries in certain situations. I found two great modules that wrap Sequelize with a [dataloader](https://github.com/facebook/dataloader): [dataloader-sequelize](https://github.com/mickhansen/dataloader-sequelize) and [dataloader-sequelize-wrapper](https://github.com/mattecapu/dataloader-sequelize-wrapper). In most cases, this should be enough.

I'm posting my solution, in hope that someone can improve it :) This is basically just a test, not yet ready for production!

I keep all Model loaders in memory. I know this is dangerous, so I might switch to request-based loader instances. Anywah, with Sequelize, I only load IDs. I load objects with loaders.

To illustrate ... imagine a query like this:
```
{
  countries {
    id name
    locations {
      id name url
      image { id name url }
      types { id name }
    }
  }
}
```

If I did `Country.findAll()` then `country.getLocations()` then `location.getImage()` and `location.getTypes()` in each of Location resolvers, I would end up with a lot of queries. So what I do is, I parse query [info](http://dev.apollodata.com/tools/graphql-tools/resolvers.html#Resolver-function-signature) in the root resolver, preload all required data and apply it to the return value. So each child resolver already has all the data it needs, or it loads it from the loader, not the db.
```
const resolveFunctions = {
  RootQuery: {
    countries(_, args, { user }, info) {
      const req = parseRequest(info.operation.selectionSet.selections[0])
      return prefetchCountries(req)
    },
  },
}
```

`parseRequest`
```
export function parseRequest(ast, data) {
  const { selections } = ast.selectionSet;
  data = data || {}
  selections.forEach(selection => {
    if (selection.kind === 'Field') {
      if (selection.selectionSet) {
        data[selection.name.value] = parseRequest(selection)
      } else {
        data[selection.name.value] = true
      }
    }
  })
  return data
}
```

`prefetchCountries` and `prefetchLocations`
```
import loader from './loader'
import db from './db'

export async function prefetchCountries(req) {
  const countries = await db.Country.findAll()
  const countriesById = indexBy(countries, 'id')
  if (req.locations) {
    const locations = await prefetchLocations(req.locations)
    const locationsByCountry = groupBy(locations, 'country_id')
    countries.forEach(country => {
      if (locationsByCountry[country.id]) {
        country.locations = locationsByCountry[country.id]
      }
    })
  }
  return countries
}

export async function prefetchLocations(req) {

  // load locations
  const ids = await db.Location.findAll({
    attributes: ['id'],
    where: {
      parent_id: { $eq: null },
    },
  })
  const locations = await loader.Location.loadMany(ids.map(l => l.id))

  // load images
  if (req.image) {
    const imageIds = await db.Location.findAll({
      attributes: ['image_id'],
      where: {
        parent_id: { $eq: null },
        image_id: { $ne: null },
      },
    })
    const images = await loader.Image.loadMany(imageIds.map(i => i.image_id))
  }

  // and so on ...
}
```

So in `resolvers` I can simply do:
```
Location: {
  country(location, args, { user }) {
    return location.country || location.country_id && loader.Country.load(location.country_id) || location.getCountry()
  },
  image(location, args, { user }) {
    return location.image || location.image_id && loader.Image.load(location.image_id) || location.getImage()
  },
  types(location, args, { user }) {
    return location.types || location.getTypes()
  },
},
```

**Comment by HriBB** [comment]
Resolvers should use Connectors, not Models. But with Sequelize this is hard. You can't use magic getters if you want to load your data efficiently. You need to wrap it somehow.

**Comment by stubailo** [comment]
Hi, I don't think this is the right place to have this discussion. This package is just about how to connect a GraphQL schema to an http server. It might be more relevant in graphql-tools: https://github.com/apollostack/graphql-tools

Currently, we don't have any specific recommendations about how to connect to a database other than the example app, which uses Knex mainly for simplicity.

However, if you are interested in submitting a PR to convert the example to Sequelize, that could be good since it seems a lot of people prefer that approach.

**Comment by jlubeck** [comment]
I was wondering the exact same thing... How can I access MySQL without a REST API?

**Comment by stubailo** [comment]
I'd suggest opening a new issue now that data sources are a thing, having a discussion on a closed issue probably won't be very visible.

**Comment by jlubeck** [comment]
Sounds good, just opened https://github.com/apollographql/apollo-server/issues/1458
