### ISSUE TITLE
[AER] Support more complex privacy settings for obfuscating Tracing Information

### ISSUE THREAD

**Issue by zionts** [apollographql/apollo-server#1994]
Currently, there exist two "knobs" for hiding [PII](https://en.wikipedia.org/wiki/Personally_identifiable_information) from Apollo Engine: `privateVariables` and `privateHeaders`. The former of these looks specifically at the GraphQL variables, as in the map sent along with the Query Document as the value to the `variables` JSON key. However, for security purposes, the label of the input argument has a more important function for a security sake due to its static nature. For instance, if you "blacklist" the `password` variable, a request like
```
query: query Login(password: $password),
variables: {
  password: "foobar"
}
```
would not forward the "foobar" String along to the Trace warehouse, but a slight modification to that request would end up exposing the secret "foobar" String

```
query: query Login(password: $secret),
variables: {
  secret: "foobar"
}
```

One solution that has been advised is to add a `@sensitive` directive that could be used to annotate the schema to indicate the privacy settings of input arguments. I believe this would leave out direct arguments (those that aren't contained within a separate `input type`), so this directive could also be applied to fields.

It is also possible to add a setting to the Apollo Engine Reporting module directly, but I believe this information is best kept in the schema directly as it may be useful to other consumers as well

**Comment by glasser** [comment]
This is a nice idea but can now be implemented as a `transform` hook.  We'd consider evaluating a well-done PR to add built-in support for something like this, but I don't think its absence qualifies as an open issue any more.
