### ISSUE TITLE
Remote schema invalid queries

### ISSUE THREAD

**Issue by peteyycz** [apollographql/apollo-server#1995]
When I create a schema with `makeRemoteExecutableSchema`, and try to use it, when it encounters string variables, if they are not provided, they will be set to `__EMPTY__`

**Comment by martijnwalraven** [comment]
`makeRemoteExecutableSchema` is part of `graphql-tools`, so you may want to open an issue there. Note that schema stitching is being deprecated and the recommendation is to migrate to federation however.
