### ISSUE TITLE
Documentation for ES6 class resolvers methods?

### ISSUE THREAD

**Issue by magicmark** [apollographql/apollo-server#1996]
graphql-js documents that we can use ES6 classes to represent GraphQL types and add resolver methods on.

https://graphql.org/graphql-js/object-types/

e.g. (taken from the docs linked above)

```js
var express = require('express');
var graphqlHTTP = require('express-graphql');
var { buildSchema } = require('graphql');

// Construct a schema, using GraphQL schema language
var schema = buildSchema(`
  type RandomDie {
    numSides: Int!
    rollOnce: Int!
    roll(numRolls: Int!): [Int]
  }

  type Query {
    getDie(numSides: Int): RandomDie
  }
`);

// This class implements the RandomDie GraphQL type
class RandomDie {
  constructor(numSides) {
    this.numSides = numSides;
  }

  rollOnce() {
    return 1 + Math.floor(Math.random() * this.numSides);
  }

  roll({numRolls}) {
    var output = [];
    for (var i = 0; i < numRolls; i++) {
      output.push(this.rollOnce());
    }
    return output;
  }
}

// The root provides the top-level API endpoints
var root = {
  getDie: function ({numSides}) {
    return new RandomDie(numSides || 6);
  }
}

var app = express();
app.use('/graphql', graphqlHTTP({
  schema: schema,
  rootValue: root,
  graphiql: true,
}));
app.listen(4000);
console.log('Running a GraphQL API server at localhost:4000/graphql');
```

This also works when used with apollo-server.

A notable difference here is that the arguments that the resolver methods get passed appear to be different than what is [documented here](https://www.apollographql.com/docs/graphql-tools/resolvers.html#Resolver-function-signature).

For es6 class methods, the resolver function signature _appears_ to be

```
fieldName(args, context, info) { result }
```

(curiously missing `obj`? Not sure how this works?)

Is this pattern not recommended or something? Maybe I'm missing something but I can't see any documentation in the apollo docs to suggest that this is actually supported - but it is a useful pattern imo.

If so, would we be open to adding docs to show support for this? Thanks!

**Comment by sachindshinde** [comment]
Apollo-server supports ES6 class methods through default resolvers. When you define a resolver function through an ES6 class, you don't include the function in the resolver map. This causes apollo-server to use the default resolver, which will check whether the GraphQL field name is a property of `obj`, and if so, whether it is also a function. In the case of ES6 class methods, `obj` is an instance of the class and the field name is the method, so the GraphQL field will be resolved using
```
obj[info.fieldName](args, context, info) { result }
```
The `obj` here will be accessible via `this`.

If you're still interested, you're more than welcome to contribute to the docs to show that this pattern is supported!
