### ISSUE TITLE
Unable to set Authorization headers in Response [apollo-server-koa]

### ISSUE THREAD

**Issue by ashokvishwakarma** [apollographql/apollo-server#1997]
Hey there,

I am using `apollo-server-koa@2.2.2` and unable to set `authorization` headers from the resolver.

```js
// auth resolver

.....

login(root, args, ctx) {
  // after successfull login
  // I am adding the token in the response headers the same way I was using in other Koa projects
  ctx.response.set('Authorization', token)
}

....
```

In response, there are no authorization headers being added to the client.

**Comment by ViableClanMember** [comment]
I think you're supposed to send the token to the client via Cookies

**Comment by Xample** [comment]
@ashokvishwakarma Did you find a way?

**Comment by ashokvishwakarma** [comment]
> @ashokvishwakarma Did you find a way?

Yes, using the `formatResponse` method
```
const server = new ApolloServer({
formatResponse: (response, options) => {

    if(response.errors) {
      logger.error(response.errors);
    }
    
    if(options.context._token) {
      options.context.ctx.response.set('Authorization', options.context._token);
    }

    return response;
  }
});
```
Hope this helps.

**Comment by martijnwalraven** [comment]
We won't be directly maintaining integrations with specific frameworks in Apollo Server 3, so closing this issue.
