### ISSUE TITLE
Custom trace?

### ISSUE THREAD

**Issue by magnusottosson** [apollographql/apollo-server#2018]
Is it possible to add custom trace steps in the trace view of apollo engine?

Its great that you can drill down to which resolver or field that is taking time but I want to be able to dig further. What is slow, is it the db call, the json parsing, or some other complex task that is performed to return the data needed for the resolver...

Is this possible?

![](https://www.apollographql.com/docs/engine/img/trace.png)

**Comment by JakeDawkins** [comment]
Hi! This is something that we would maybe want to support further in the future, but we don't really have a way (or plan) to do that right now. If you'd like to open a support ticket on Engine to ask about future support for this format, you can do that at the bottom right of [this page](https://engine.apollographql.com/login).
