### ISSUE TITLE
apollo-server-lambda "body size is too long" ( body parser limit )

### ISSUE THREAD

**Issue by sve-odoo** [apollographql/apollo-server#2019]
Hello,

I am converting a working graphql app from apollo-server-express to apollo-server-lambda.

Some of my queries work, but one of them seems to be too big and does not work. It works when I restrict the resolver to return only the first 3 records. ( out of 18k )

When I don't limit the result size:
- The lambda logs display "body size is too long"
- Funnily enough the front-end displays a CORS error..

This is something that I can work around with express using 
app.use(bodyParser.json({limit: '50mb'}));

But I don't know how to apply that in apollo-server-lambda

Thanks in advance for your help

**Comment by iPwnPancakes** [comment]
I also had this issue on "apollo-server": "2.2.4"

This threw me for a loop!

Is there any word on a fix yet, or why the CORS error occurred?

**Comment by ddehghan** [comment]
I was also getting CORS issue. for me the issue was caused by the Kubernetes ingress limiting the request size and rejecting it. 

>     nginx.ingress.kubernetes.io/proxy-body-size: 20m

that fixed it.
