### ISSUE TITLE
where do I add request header validations?

### ISSUE THREAD

**Issue by kdong007** [apollographql/apollo-server#2021]
assume I have some validation logics that grabs values from request headers and the reject any request that fails validations.

for example: 
```
// run for each request reaches /graphql
   const {sig, val} = headers;
   if(hash(val+SECRET) !== sig) 
       throw Error("Access denied")
```

where do I put this logic?

I found there is validationRules in apollo serve options, but I only get a SchemaValidationContext in validation functions, no headers.

**Comment by ctretyak** [comment]
+1

**Comment by JakeDawkins** [comment]
This can be done in the `context` function on the `ApolloServer` constructor. More info for this can be found [in our authentication guide](https://www.apollographql.com/docs/apollo-server/features/authentication/)
