### ISSUE TITLE
Cannot return null for non-nullable field User.username.

### ISSUE THREAD

**Issue by lephenix1234** [apollographql/apollo-server#2023]
//typedef
type Query {
  getPosts: [Post]
  createdBy: [User!]!
}

type User {
  _id: ID
  username: String! @unique
  email: String! @unique
  password: String
  avatar: String
  joindate: String
  favorites: [Post]
}

type Post {
  _id: ID
  title: String!
  imageUrl: String
  categories: [String]!
  description: String!
  createdDate: String!
  likes: Int
  createdBy: User!
  messages: [Message]
}

type Message {
  _id: ID
  messageBody: String!
  messageDate: String!
  messageUser: User!
}

type Mutation {
  addPost(
    title: String!
    imageUrl: String!
    categories: [String]!
    description: String!
    creatorId: ID!
  ): Post!
  signupUser(username: String!, email: String!, password: String!): User!
}
//resolver
module.exports = {
    Query: {
        getPosts: async (_, args, {
            Post
        }) => {
            const posts = await Post.find({})
                .sort({
                    createdDate: "desc"
                })
                .populate({
                    path: "createdBy",
                    model: "User"
                });
            return posts;
        }
    },
    Mutation: {
        signupUser: async (_, {
            username,
            email,
            password
        }, {
            User
        }) => {
            const user = await User.findOne({
                username
            });

            if (user) {
                throw new Error("username already exist");
            }

            const newUser = await new User({
                username,
                email,
                password
            }).save();
            return newUser;
        },

        addPost: async (
            _, {
                title,
                imageUrl,
                categories,
                description,
                createdBy
            }, {
                Post
            }
        ) => {
            const newPost = await new Post({
                title,
                imageUrl,
                categories,
                description,
                createdBy
            }).save();
            return newPost;
        }
    }
};

**Comment by trevor-scheer** [comment]
Hey @lephenix1234, can you please provide more information and a reproduction of the issue? I'm not sure how to help at this point. Thanks!
