### ISSUE TITLE
Partially private schema (hide types and  from introspection)

### ISSUE THREAD

**Issue by christianrondeau** [apollographql/apollo-server#2028]
I'm not sure if this belongs here or upstream, but in both cases it's something that could be part of Apollo.

I have parts of my schema I'd like to hide from the "general public". As an example, I might have ways to get an order, product information, etc. but I'd like to also have order-specific error logs only available to users with an admin authentication level.

Actually making the schema "aware" of the user authentication would probably be too complex, but generally hiding a part of it would make using the introspection feature easier for users.

Here's a GitHub conversation specifically about this: https://github.com/graphql/graphql-js/issues/113

My suggestion would be to simply provide Apollo Server developers a "hook" where they can transform the schema before returning it to users, effectively allowing them to remove parts of it. Something like:

```
const function schemaFilter(schema) {
    delete schema.logs;
    delete schema.order.logs;
}

new ApolloServer({ schemaFilter });
```

This would not involve much new complexity while allowing complex use cases, if needed by the developer.

I quickly looked at where such a filter could be hooked into and couldn't find anything obvious, so if there is interest, pointers would also be appreciated.

**Comment by DominusVilicus** [comment]
There needs to be a `@private` directive resolver that hides stuff from the introspecter

**Comment by apalazzin** [comment]
> There needs to be a `@private` directive resolver that hides stuff from the introspecter

UP!

**Comment by jdrydn** [comment]
Something as straightforward as this would be incredible:

```graphql
directive @hidden(reason: String = "Private resource") on FIELD_DEFINITION | OBJECT | INPUT_OBJECT

type Query {
  ping: String! @hidden
}
```

I just [attempted with `graphql-tools`](https://www.apollographql.com/docs/graphql-tools/schema-directives/#implementing-schema-directives) but adding to the `field` variable doesn't matter since the Introspection query isn't trying to return a `isHidden` field so my modifications don't get picked up 🤦‍♂

**Comment by jdrydn** [comment]
@ftatzky:

> Our team also has a need for such functionality. We also want to enable account-based introspection capabilities.

I assume you mean in a similar fashion to how [graphcms.com](https://graphcms.com) operates? My guess is these guys (a) don't use Apollo-Server and (b) they just match the GraphQL API specification to their own tech, and therefore depending on API keys / headers / hostname they're able to return a unique GraphQL parser & introspection results per account.

**Comment by abrkn** [comment]
Here's a way to do it @christianrondeau: https://gist.github.com/abrkn/2edb028da330a875c1598250a1a8d8e5

We're using it for https://sideshift.ai/graphql to hide internal types. I might publish this as an npm module in the future.

**Comment by christianrondeau** [comment]
@abrkn that's a very nice (and simple) solution, to simply overwrite the introspection query in express! Thanks for sharing it!

**Comment by abrkn** [comment]
> @abrkn that's a very nice (and simple) solution, to simply overwrite the introspection query in express! Thanks for sharing it!

It should be reasonably simple to allow compiled typeDefs as input and use directives.

**Comment by abrkn** [comment]
@christianrondeau I've published a version that uses directives: https://github.com/sideshift/apollo-server-restrict-introspection

It's a pretty rough first version, open to PRs.

**Comment by glasser** [comment]
I don't think we're likely to implement this directly in Apollo Server. If [the linked `graphql-js` issue is resolved](https://github.com/graphql/graphql-js/issues/113) then it would be good for Apollo Server to make it easy to use whatever feature is added to `graphql-js`, but we can open an issue for that when that shows up.

(Additionally, if the goal is more around actually stopping fields from running and not just introspection, I'd recommend using some sort of system that allows you to expose multiple servers for your multiple schema subsets, such as [contracts](https://www.apollographql.com/docs/studio/contracts/).)
