### ISSUE TITLE
Need to send JWT token on every request made to apollo server

### ISSUE THREAD

**Issue by AnkurSaini07** [apollographql/apollo-server#2031]
I need to send JWT token on every request made to Apollo server, one way I can do by using formatResponse but I cannot access context or request, response object in  formatResponse  function.

**Comment by AnkurSaini07** [comment]
I need to send a token from the server side, not from the client side.

**Comment by ostrebler** [comment]
Add it to the resolvers' response ?

**Comment by AnkurSaini07** [comment]
Ya, but then I need to add token in every resolver and also I need to add token in schema, and If I need to send token every time then there is no point to add it in schema, it would be best if some how I could access req or resp object in format response method.

**Comment by ftatzky** [comment]
> I need to send JWT token on every request made to Apollo server, one way I can do by using formatResponse but I cannot access context or request, response object in formatResponse function.

You have access to your context in `formatResponse`. Take a look at:
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/requestPipeline.ts#L261

`formatResponse(response, { context }) { ... }`

**Comment by AnkurSaini07** [comment]
@ftatzky thanx it worked. This is not mentioned in Apollo server documentation.
