### ISSUE TITLE
Server crashes on every calls when extension returns a promise

### ISSUE THREAD

**Issue by nick-keller** [apollographql/apollo-server#2038]
# Intended outcome
Returning a promise in the method `willSendResponse` of an extension should be supported

# Actual outcome
If the method `willSendResponse` returns a promise or is `async` the server crashes on every calls and the client receives the errors: `[{"message": "Cannot read property 'errors' of undefined"}]`

# How to reproduce the issue
Create a simple logging extension for an Apollo server 2:

```js
const apolloServer = new ApolloServer({
  //...
  extensions: [ () => new Logger(), ],
})
```

And the logger:
```js
export class Logger {
  async willSendResponse() {
    //...
  }
}
```

I'm assuming this is unintended and this sould be an easy fix ;)

**Comment by nick-keller** [comment]
Am I the only one in need of async actions in extensions?

**Comment by pierreericgarcia** [comment]
✋🏻In need too

**Comment by anton-kabysh** [comment]
Yes, facing the same issue.

**Comment by anton-kabysh** [comment]
Actually this bug prevents us to use Apollo Server. We have the following case: for some queries we want to have export files that contains the same data as result of the query. To send export file `id` we use `extensions` field in the response. But to create and publish file we need to do async actions during the construction of the `extensions` field. But making `willSendResponse` as `async` crashes the server. 

I spent entire day to find workaround but failed. Any suggestions?

**Comment by ruizmarc** [comment]
✋🏻 it would be very useful for us also! We have a use case in which we need to do some async post procesing in willSendResponse. Is there any workaround?

**Comment by paumartin** [comment]
✋🏻 Same here

**Comment by abernix** [comment]
This is supported by the new request pipeline plugin API.  The `graphql-extensions` API is not being actively maintained anymore and is being replaced by in favor of the new request pipeline which first surfaced in https://github.com/apollographql/apollo-server/pull/1795 and aims to cover a wider range of functionality than `graphql-extensions` which was never documented nor intended to be public API.

The new API (which can be utilized by providing `plugins` to the `ApolloServer` constructor) supports more integration points (e.g. server startup, where as extensions were only ever per-request), and in the future will support schema generation hooks and more, all with a strongly-typed API.

While the new API is still growing, the documentation is taking form in https://github.com/apollographql/apollo-server/pull/2008 (there's a preview link on that PR so you can view them in a more glorious form than the raw markdown) and building out the API further is on our roadmap for Apollo Server 3.0, as noted in #2360.

I'll close this, but if you take a look at the documentation and [the source types in `apollo-server-plugin-base`](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-plugin-base/src/index.ts) (used by package authors to implement plugins, for example), you should be able to get an idea, and we intend on supporting this longer-term.

In the case of `willSendResponse`, you'll find it _does_ support returning a `Promise` and can be used _today_:

https://github.com/apollographql/apollo-server/blob/d1a0d16065d915e10859934aec808c1fbe3ff9d1/packages/apollo-server-plugin-base/src/index.ts#L62-L67

I didn't finish writing the text blurb for `willSendResponse` in those docs previews, but I [think you'll get the idea](https://deploy-preview-2008--apollo-server-docs.netlify.com/docs/apollo-server/features/plugins#willsendresponse).  Let me know if you have any questions.
