### ISSUE TITLE
Defer usage

### ISSUE THREAD

**Issue by janhartmann** [apollographql/apollo-server#2052]
On my Apollo Server I am running: 

```
"apollo-server": "^2.2.5",
"express": "^4.16.4",
"graphql": "^14.0.2",
"graphql-tools": "^4.0.3",
```

But I am unable to try out the `defer` directive, as my server is returning: `Unknown directive "defer".`

I am unsure how to enable this feature. I have read all information I could find on `defer`, but no matter what I do I can not enable it. On my client I am also running latest version of React Apollo.

How do I enable `defer`? :-)

**Comment by jaschaio** [comment]
I got the same issue using `apollo-server` and `apollo-server-express`.

`package.json`:

```
"apollo-server": "^2.4.0-alpha.0",
"apollo-server-express": "^2.4.0-alpha.0"
```

Within the defer support doc [it says that I have to explicit enable the support ](https://github.com/apollographql/apollo-server/blob/defer-support/docs/source/defer-support.md#apollo-server-variants) when using `apollo-server-express` but without actually explaining how to add my custom handler.

**Comment by rlech** [comment]
can you please give a hint on the docs that `@defer` is currently not working and a upcoming feature?

**Comment by michaelshiel** [comment]
I'm curious if there is a reason to not release the client-side support on it's own, especially given that `graphql-java` just merged defer support.

**Comment by hwillson** [comment]
We're tracking new `@defer` / `@stream` work in https://github.com/apollographql/apollo-server/issues/5893. Thanks!
