### ISSUE TITLE
Asynchronous handlers in Request Pipeline 

### ISSUE THREAD

**Issue by AndreyChechel** [apollographql/apollo-server#2062]
Is there any value in supporting asynchronous handlers in Request Pipeline events?

Currently, some handlers are called asynchronously, the others - synchronously, e.g.:

- Async sample:
https://github.com/apollographql/apollo-server/blob/8b918e5bb6dcd24d33bd8cc664c663aa6917f691/packages/apollo-server-core/src/requestPipeline.ts#L224-L230

- Sync sample (don't be confused with `await` - `invokeDidStartHook` is [synchronous](https://github.com/apollographql/apollo-server/blob/db8fdc8d9d067dfab7ec42f5d8b6debc96d7db8a/packages/apollo-server-core/src/utils/dispatcher.ts#L30-L60)):
https://github.com/apollographql/apollo-server/blob/8b918e5bb6dcd24d33bd8cc664c663aa6917f691/packages/apollo-server-core/src/requestPipeline.ts#L232-L238

The scenario we've faced is, we'd like to use a plugin to start a DB transaction before [`execute`](https://github.com/apollographql/apollo-server/blob/8b918e5bb6dcd24d33bd8cc664c663aa6917f691/packages/apollo-server-core/src/requestPipeline.ts#L243-L247) function is called, and commit or rollback the transaction depending on whether the execution was successful or not. 

The [`executionDidStart`](https://github.com/apollographql/apollo-server/blob/8b918e5bb6dcd24d33bd8cc664c663aa6917f691/packages/apollo-server-core/src/requestPipeline.ts#L232-L238) / [`executionDidEnd`](https://github.com/apollographql/apollo-server/blob/8b918e5bb6dcd24d33bd8cc664c663aa6917f691/packages/apollo-server-core/src/requestPipeline.ts#L248-L250) events look as good places where that logic could be implemented. The problem is handlers for the both events are invoked synchronously, thus, making us unable to await transaction actions to complete.

**Comment by ruizmarc** [comment]
We also have a use case in which we need to check the rate limit asynchronously based on the request of the user before executing the query. And at this moment, we cannot do it with the request pipeline as it is synchronous. 

It would be great to have an asynchronous handler in the request pipeline :D

**Comment by abernix** [comment]
@ruizmarc 	The request pipeline is not all synchronous; this statement is untrue.  Some life-cycle events are synchronous because they absolutely must be.  Which request pipeline life-cycle method are you trying to use?  I might suggest checking out `didResolveOperation`:

https://github.com/apollographql/apollo-server/blob/b3cbb42dfd37d5dc4e14da043292489c4dc10451/packages/apollo-server-plugin-base/src/index.ts#L39-L45

If you were to return a `Promise` (or identically, implement that handler as an `async` function) you could prevent execution, if necessary, by `throw`ing.

**Comment by ruizmarc** [comment]
Oh! didResolveOperation definetly resolves our use case! We were looking at the wrong hook! 

Thanks for the info! 🥇

**Comment by abernix** [comment]
I suspect most of this will be covered by the new request pipeline API, which is mostly `async` (whenever possible!).   Please do take a look at https://github.com/apollographql/apollo-server/pull/2008, which starts to document these new life-cycle hooks, and let us know if you don't find a hook that meets your needs.  Thanks!
