### ISSUE TITLE
where did subscriptions onOperation go?

### ISSUE THREAD

**Issue by tdfairbrother** [apollographql/apollo-server#2064]
I am using it to create fresh `DataLoader` instances on each request. In the previous version of `apollo-server-express`, when using subscriptions, it enabled you to listen to an `onOpteration` callback via the `subscriptions-transport-ws`s `SubscriptionServer.create` method.

How do I create a new context on every operation using the new `apollo-server`?

**Comment by tdfairbrother** [comment]
I found that you can use the `context` callback in the `ApolloServer` options.

**Comment by chelliwell** [comment]
@tdfairbrother - Hi, could you give a quick example to elaborate please?

**Comment by tdfairbrother** [comment]
```
  new ApolloServer({
    typeDefs,
    resolvers,
    schema,
    context: (params) => {
      if (params.connection) {
        // websocket
      } else if (params.req) {
        // http
      }
    }
  });
  
```
