### ISSUE TITLE
undefined variables in args parameter in formatResponse function

### ISSUE THREAD

**Issue by disyam** [apollographql/apollo-server#2068]
server : apollo-server-koa v2.2.6

when i upgrade apollo-server-koa from 2.0.7 to 2.2.6 some variables in "args" parameter in "formatResponse" function got undefined
before i can get variables like "queryString", "variables", "operationName", etc..
now inside "args" i only found context

demo : https://codesandbox.io/s/pw4knpl0rj

**Comment by mikestaub** [comment]
For anyone coming to this issue, you can use the 'graphql-middleware' package to do anything that you were doing in the formatResponse function.

https://github.com/apollographql/apollo-server/issues/1603#issuecomment-422035502

**Comment by martijnwalraven** [comment]
The `args` parameter in `formatResponse` exposed implementation details that aren't part of the new request pipeline. You should be able to use the `willSendResponse` hook in the plugin API to get access to the same information however.
