### ISSUE TITLE
Auto generated RESTDataSource from API Docs

### ISSUE THREAD

**Issue by ChristianOezelt** [apollographql/apollo-server#2069]
Hello there!

Looking at the caching features of `RESTDataSource` I thought "how amazing would it be if I could just generate these from my Swagger/OpenAPI spec files!".

Sadly there is no such option yet and I am considering writing such a template for myself.
I opened this issue to start a discussion about this topic and maybe find other alternatives I have not thought about yet. 
This would obviously not be a feature of apollo-server, yet I opened the issue here because I believe that it is most relevant to apollo-server users.

There are a few points that came to my mind when thinking about a general solution:
- the language to generate the Data Sources in (JS, TS, Flow, ...)
- how should the generated RESTDataSource look like
- how generic would it be (e.g. a generic type for the GraphQL Context)
- how should the API look like for customization (e.g. generic headers that have to be forwarded, transformed or set)

**Comment by sbrichardson** [comment]
Hi Christian--I've worked on auto-generating features myself but had a quick question to clarify before detailing more.

Were you talking about auto-generating GraphQL types/schema code from the Swagger/OpenAPI spec files?

Or are you referring to generating the resolvers using Swagger/OpenAPI spec etc?

Or are you referring to generating both specifically?

Could you briefly detail the ideal outcome/generated output or process flow? That would help clarify what bits I could share that may be relevant.

**Comment by ChristianOezelt** [comment]
ApolloServer 2 allows us to register dataSources (that will be available in the context after registration)

```ts
const server = new ApolloServer({
    typeDefs,
    resolvers,
    dataSources: () => ({
        product: new MyAutoGeneratedProductAPI(),
    })
});
```
I would like to create an OpenAPI Generator Template that creates data sources which can be used like that directly / extended with minor customizations & then be used

**Comment by sbrichardson** [comment]
I found a few similar projects specific to Swagger/OpenAPI that may be worth reviewing or discussing here.

1. https://strongloop.com/strongblog/announcing-oasgraph/
2. https://github.com/yarax/swagger-to-graphql

Some of my code is around generating the entire lifecycle (types/inputs/filter inputs, queries/mutations, along with the resolvers. (or parts, one time, or as needed).

My thinking is if you are auto-generating the dataSources, you would still need to manually create all of the resolvers, then all of the types/inputs etc. Would there be a reason for not generating those pieces also? Or are you using the dataSources in a different way than I'm understanding?

**Comment by ChristianOezelt** [comment]
I understand your point, for some use cases it might be interesting to generate the whole graphql schema.

Personally, I want to define the graphql schema myself, as it consolidates, omits, cherry picks, tranaforms, .. what my clients really require. Spending time on integration with other services is what I would like to reduce. 
Auto generated dataSources are going to allow me to take advantage of all benefits of the RESTDataSource, while spending minimal effort on integration with other services.

**Comment by sbrichardson** [comment]
I agree with those points, thanks for clarifying. 

For generating the datasources, are you thinking static code generation that you would copy into a project, or more of an installed module with dynamic generation continuously/as needed?

**Comment by fabien0102** [comment]
I have this idea in mind since 6 months but never took the time 😅 But now, I have an amazing openapi/swagger to restful-react typed component generator [here](https://github.com/contiamo/restful-react/blob/master/src/scripts/import-open-api.ts), so it should be quite "easy" to convert this to an apollo datasource generator (80% of the logic is there and it's typesafe 💯 )

My only question is about the API/CLI that we want, do you prefer have this in a separate package or part of `apollo-server/packages/apollo-datasource-rest`?

**Comment by ChristianOezelt** [comment]
Sorry for my late response, I got busy over X-Mas and new years :see_no_evil:

@fabien0102 I am going to look at your code and see if I can adapt it to generate the DataSources.
I suppose it should be a plugin for the `apollo` cli and a package [there](https://github.com/apollographql/apollo-tooling/tree/master/packages)?

**Comment by willerup** [comment]
Love this idea. Did this ever get off the ground? I'd be interesting in contributing if I can. My RESTDataSource is incredible repetitive and would love to just point it to a Swagger/OpenAPI spec and call it good!

**Comment by JakeDawkins** [comment]
Hi! This seems like something that could be useful, but we don't intend on supporting it as a part of the DataSource itself, since the maintenance burden could be quite high. If this gets finished, we'd love to have a guest post on the Apollo blog or share it, though!

Since this isn't an issue specifically with the DataSource, I'm going to close this issue, but this looks like something that could be a great thing to discuss further in the [spectrum community](https://spectrum.chat/apollo) if you want to collaborate further on it!
