### ISSUE TITLE
Circular reference links in documentation page /schemas/types

### ISSUE THREAD

**Issue by brianbancroft** [apollographql/apollo-server#2070]
Hi there, 

I'm currently trying to learn the ropes for apollo-server using express. [For this page of documentation](https://github.com/apollographql/apollo-server/blob/master/docs/source/schemas/types.md), you have promising links ("To write your first Query go here.", and "To implement your first mutation, follow the ... guide."). Both of the links go to the top of the same page – something I found frustrating.

Is this an accident, and are these links meant to go to somewhere else? I'd be happy to open a PR, if I knew the intent.

![image](https://user-images.githubusercontent.com/6225122/49618365-544bfc80-f986-11e8-8f5d-fb8ad43d5cbb.png)

**Comment by trevorblades** [comment]
Thanks for filing this @brianbancroft! This page no longer exists, but the new documentation closest to this one is here: https://www.apollographql.com/docs/apollo-server/essentials/schema/#the-query-type

It appears like this issue doesn't apply to the new content.
