### ISSUE TITLE
Extensions hooks don't run on nested resolvers

### ISSUE THREAD

**Issue by aliok** [apollographql/apollo-server#2074]
Imagine this schema:
```
const typeDefs = gql`
  type Query {
    par: User 
  }

  type User {
    name: String
    car: Car
  }

  type Car {
    make: String
  }
`
```

and the resolvers:
```
const resolvers = {
  Query: {
    par: (obj, args, context, info) => {
      return {name: 'Oleg'}
    }
  },
  User:{
    car: (obj, args, context, info) => {
      return {make: 'Audi'}
    }
  }
}
```

`executionDidStart` of my Graphql extension will only execute once when I make this query:
```
query hello {
  par{name, car{make}}
}
```

`User.car` is a separate resolver and I would expect `executionDidStart` to run twice.

**Comment by martijnwalraven** [comment]
That's not how `executionDidStart` works, it represents the execution of an entire GraphQL request, not individual resolvers.

What are you trying to accomplish here?

**Comment by aliok** [comment]
I was trying to log how much each resolver took.

I now understand `executionDidStart` is called per request and `willResolveField` is called per resolver.

However, `willResolveField` is called for every single field in a type. Is there a way to make it called only for the fields that has a nested resolver?

For example, in the original example, I don't want to record the time it takes to resolve `user.name`

**Comment by sbrichardson** [comment]
Here's an example to explain what I mean above.

In a resolver, the 4th argument has the GraphQL info

```js

const userResolver = (root, { id }, context, info) => {
  const { fieldName, prev, key, parentType } = info.path
  // fieldName is User
  // prev is undefined
  // key is 'User'
  // parentType is Query
}

const carResolver = (root, { id }, context, info) => {
  // if invoked as nested resolver
  const { fieldName, prev, key, parentType } = info.path
    // fieldName is car
    // prev is { prev: undefined, key: 'User' }
    // key is 'car'
    // parentType is User
}
```

**Comment by abernix** [comment]
I realize it's been quite some time since you opened this, but if you haven't already figured this out, I'd recommend taking this question to the [Apollo community on Spectrum.chat](https://spectrum.chat/apollo) to discuss it further.  Thanks!
