### ISSUE TITLE
Annoying scrollbars in playground - Firefox

### ISSUE THREAD

**Issue by gepd** [apollographql/apollo-server#2075]
This behavior is happening in firefox and it's a little annoying:

![firefox](https://user-images.githubusercontent.com/7091609/49676817-20420b80-fa5a-11e8-8626-217a64131dbc.gif)

`apollo-server-express: 2.2.6`

**Comment by abernix** [comment]
I'll close this as I can't seem to reproduce this in Firefox, even at different zoom levels.  Happy to re-open if you're still experiencing this on recent versions of `apollo-server`.
