### ISSUE TITLE
ApolloServer localStorage

### ISSUE THREAD

**Issue by mrjoseph** [apollographql/apollo-server#2077]
I'm building a isomorphic react app with Apollo Server. I'm using localStorage but obviously window is not defined so I don't have access to localStorage. Has anyone had this issue or come across this? I've searched the internet for answers but can't seem to find anything

**Comment by ifndefdeadmau5** [comment]
What do you mean? `window` object only lives in browser, as you know.

**Comment by mrjoseph** [comment]
Stand down!.. I've sorted it.
When you set up your express backend you have to remember order your express app and apollo server correctly else you will get localStorage undefined..
