### ISSUE TITLE
Cannot find module 'apollo-server-core/dist/requestPipelineAPI' when compiling

### ISSUE THREAD

**Issue by artemzakharov** [apollographql/apollo-server#2079]
When I attempt to compile my typescript code, I get the following series of errors:

```
node_modules/apollo-engine-reporting/dist/agent.d.ts:5:62 - error TS2307: Cannot find module 'apollo-server-core/dist/requestPipelineAPI'.

5 import { GraphQLRequestContext, GraphQLServiceContext } from 'apollo-server-core/dist/requestPipelineAPI';
                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/apollo-engine-reporting/dist/extension.d.ts:6:39 - error TS2307: Cannot find module 'apollo-server-core/dist/requestPipelineAPI'.

6 import { GraphQLRequestContext } from 'apollo-server-core/dist/requestPipelineAPI';
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/apollo-server-plugin-base/dist/index.d.ts:1:95 - error TS2307: Cannot find module 'apollo-server-core/dist/requestPipelineAPI'.

1 import { GraphQLServiceContext, GraphQLRequestContext, GraphQLRequest, GraphQLResponse } from 'apollo-server-core/dist/requestPipelineAPI';
                                                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I'm using version 2.2.6 of `apollo-server`.

**Comment by sushilbansal** [comment]
Did you find any solution @artemzakharov ? I am facing the same issue.

**Comment by DonaldWebb** [comment]
Likely a missing dependency in Apollo-Server can manually add it as a dep until fixed:
npm install --save apollo-server-core

I had an issue with ws as well. Same fix.
npm install --save ws

**Comment by cheapsteak** [comment]
I believe this should have been fixed by https://github.com/apollographql/apollo-server/pull/2248 ?

**Comment by cheapsteak** [comment]
Apologies this took a while, should be fixed by #2248 which adds apollo-server-core to apollo-engine-reporting's dependency
Will close this issue, please let me know if we need to reopen :)

**Comment by JClackett** [comment]
I seem to be having this again:

`@apollo/server @4.5.0`

`Error: Cannot find module 'apollo-server-core'`

**Comment by glasser** [comment]
`@apollo/server` (new in v4) should not require `apollo-server-core` (v2 and v3).
