### ISSUE TITLE
httpOnly-based auth

### ISSUE THREAD

**Issue by andres-valdes** [apollographql/apollo-server#2082]
Is there no way to do proper httpOnly authentication through Apollo? I'm trying to keep my users safe from XSS attacks, but I can't seem to find any information on doing this with Apollo. 

Can I not set the cookies on a graphql mutation/query through Apollo? What are my options?

**Comment by choudlet** [comment]
@andres-valdes I just asked this same question on the official apollo-server slack since I am running into the same issue! I will let you know if I get a response there!

**Comment by YetiSpaghetti** [comment]
@andres-valdes @choudlet Dealing with this same issue. I've been completely unable to find a workaround or solution. I will also follow up if I find any information.

**Comment by nghitrum** [comment]
Hi @nitzano, did you actually try your code? I have tried it but did not work for me. From the network, I can see the cookie is set under Response Headers -> set-cookie. However, when I check the Application Tab on Chrom dev tool, there was nothing. Seems like somehow apollo client losses the cookie.

**Comment by nitzano** [comment]
@nghitrum : Yes I did, if you are using apollo playground you might encounter this: [#748](https://github.com/prisma/graphql-playground/issues/748) which can be solved by adding `'request.credentials': 'include'`.

**Comment by abernix** [comment]
Apollo Server shouldn't be different than any other server in this regard, and the usual XSS and CSRF practices should apply.  If you have any other questions or you're still having problems with this, feel free to ask in the [Apollo community on Spectrum.chat](https://spectrum.chat/apollo).
