### ISSUE TITLE
[apollo-server-koa] Set custom response header

### ISSUE THREAD

**Issue by ifndefdeadmau5** [apollographql/apollo-server#2084]
I tried below to set response header in my server

```javascript
app.use(async (ctx, next) => {
  ctx.set('Content-Type', 'text/html; charset=utf-8');
  ctx.set('My-Header', 'custom');
  await next();
});

server.applyMiddleware({ app });
```

and then, what I see in chrome dev tools are 'My-header' added and 'Content-type' is not changed(still remained as default value - 'application/json')

How do I overwrite 'Content-type' headers with `apollo-server-koa` ?

**Comment by bahaa-al-deen** [comment]
same question here

**Comment by martijnwalraven** [comment]
It isn't currently possible to set `Content-Type` manually, because this will be overwritten by Apollo Server. Since the output will always be JSON however, I'm not sure I understand the use case for this.
