### ISSUE TITLE
New Relic transaction throwing error when apollo tries to send an error response

### ISSUE THREAD

**Issue by Sornii** [apollographql/apollo-server#2086]
I don't know why, but when a error occurrs when sending a response to client the newrelic transaction is lost and then my application starts being crazy. This is causing a memory leak in my application too, anyone can give a help here?

Dec 10 09:11:06pm info app web 1 TypeError: this.segment.transaction.isActive is not a function
Dec 10 09:11:06pm info app web 1 at Tracer.getTransaction (/app/node_modules/newrelic/lib/transaction/tracer/index.js:53:76)
Dec 10 09:11:06pm info app web 1 at Agent.getTransaction (/app/node_modules/newrelic/lib/agent.js:716:22)
Dec 10 09:11:06pm info app web 1 at AsyncHook.initHook (/app/node_modules/newrelic/lib/instrumentation/core/async_hooks.js:53:31)
Dec 10 09:11:06pm info app web 1 at emitInitNative (internal/async_hooks.js:137:43)
Dec 10 09:11:06pm info app web 1 at emitInitScript (internal/async_hooks.js:336:3)
Dec 10 09:11:06pm info app web 1 at new TickObject (internal/process/next_tick.js:86:9)
Dec 10 09:11:06pm info app web 1 at nextTick (internal/process/next_tick.js:117:16)
Dec 10 09:11:06pm info app web 1 at onwrite (/app/node_modules/readable-stream/lib/_stream_writable.js:480:7)
Dec 10 09:11:06pm info app web 1 at WritableState.onwrite (/app/node_modules/readable-stream/lib/_stream_writable.js:180:5)
Dec 10 09:11:06pm info app web 1 at DerivedLogger.afterTransform (/app/node_modules/readable-stream/lib/_stream_transform.js:93:3)
Dec 10 09:11:06pm info app web 1 at DerivedLogger._transform (/app/node_modules/winston/lib/winston/logger.js:240:7)
Dec 10 09:11:06pm info app web 1 at DerivedLogger.Transform._read (/app/node_modules/readable-stream/lib/_stream_transform.js:184:10)
Dec 10 09:11:06pm info app web 1 at DerivedLogger.Transform._write (/app/node_modules/readable-stream/lib/_stream_transform.js:172:83)
Dec 10 09:11:06pm info app web 1 at doWrite (/app/node_modules/readable-stream/lib/_stream_writable.js:428:64)
Dec 10 09:11:06pm info app web 1 at writeOrBuffer (/app/node_modules/readable-stream/lib/_stream_writable.js:417:5)
Dec 10 09:11:06pm info app web 1 at DerivedLogger.Writable.write (/app/node_modules/readable-stream/lib/_stream_writable.js:334:11)
Dec 10 09:11:06pm info app web 1 at DerivedLogger.(anonymous function).args [as error] (/app/node_modules/winston/lib/winston/create-logger.js:54:16)
Dec 10 09:11:06pm info app web 1 at formatError (/app/dist/logger.js:73:10)
Dec 10 09:11:06pm info app web 1 at enrichedErrors.map.error (/app/node_modules/apollo-server-errors/dist/index.js:157:20)
Dec 10 09:11:06pm info app web 1 at Array.map (<anonymous>)
Dec 10 09:11:06pm info app web 1 at Object.formatApolloErrors (/app/node_modules/apollo-server-errors/dist/index.js:155:27)
Dec 10 09:11:06pm info app web 1 at FormatErrorExtension.willSendResponse (/app/node_modules/apollo-server-core/dist/formatters.js:13:130)
Dec 10 09:11:06pm info app web 1 at reverse.forEach.extension (/app/node_modules/graphql-extensions/dist/index.js:32:42)
Dec 10 09:11:06pm info app web 1 at Array.forEach (<anonymous>)
Dec 10 09:11:06pm info app web 1 at GraphQLExtensionStack.willSendResponse (/app/node_modules/graphql-extensions/dist/index.js:30:40)
Dec 10 09:11:06pm info app web 1 at /app/node_modules/apollo-server-core/dist/requestPipeline.js:204:58
Dec 10 09:11:06pm info app web 1 at Generator.next (<anonymous>)
Dec 10 09:11:06pm info app web 1 at /app/node_modules/apollo-server-core/dist/requestPipeline.js:7:71

**Comment by vbtelus** [comment]
I've got same problem: when HTTP error happened code is trying to call NewRelic `agent.noticeError(error, {details});` and `agent.recordCustomEvent('MyAppName',{details});`  we get error below, application crashes and pod (app deployed in OpenShift) gets recycled.
```2019-04-12T20:07:40.483Z info: Outgoing PUT request ... 
TypeError: segment.transaction.isActive is not a function
    at Shim.getActiveSegment (/app/node_modules/newrelic/lib/shim/shim.js:1301:61)
    at AsyncHook.afterHook (/app/node_modules/newrelic/lib/instrumentation/core/async_hooks.js:88:31)
    at emitAfterNative (internal/async_hooks.js:164:40)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
    at process.wrappedProcess (/app/node_modules/newrelic/lib/instrumentation/core/timers.js:15:21)```

Can you please advise how this can be fixed? Did I missed some configuration?
Regards,
VB

**Comment by Sornii** [comment]
The new relic was hiding the real problem and we decided to not use new relic anymore on node projects. We moved to another solution.

**Comment by wszgxa** [comment]
😢

I meet the same problem. Anyone have any idea?
