### ISSUE TITLE
[apollo-datasource-rest] memoizedResults cache rules

### ISSUE THREAD

**Issue by edmundas-ramanauskas** [apollographql/apollo-server#2089]
In RESTDataSource class every GET response is stored inside map and retrieved next time the same GET request is performed and cleared only when different type of request (POST, PUT, DELETE, etc.) is performed. and there are no configuration for this cache, not even a proper way to disabled it:
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts#L254-L265
so in our case it's a problem, because in same cases we use different data source for data changes, so we don't get back new data. and we solved this problem overriding `initialize` method where we replace memoizedResults with some dummy map implementation. so I would like to have here an easy way to change caching rules here (like even providing cache implementation like it's done with httpCache) or at least to be able to disable it per data resource or per specific request.

**Comment by martijnwalraven** [comment]
Can you show how you're initializing your data sources? They are meant to be created per request, so memoized results are only cached for the duration of a request.

**Comment by edmundas-ramanauskas** [comment]
ok, so probably that's the problem. our code looks like this:
`
// these classes extend RESTDataSource 
const projectApi = new ProjectApi();
const userApi = new UserApi();

const server = new ApolloServer({
  typeDefs,
  resolvers,
  dataSources: () => ({
    projectApi,
    userApi,
  }),
  context: async ({req, connection}) => {
    // ...
  },
});
`

so I assume that I should initialize those datasources inside `dataSources` callback?

**Comment by martijnwalraven** [comment]
Yep, that's the intention!

**Comment by edmundas-ramanauskas** [comment]
ok, thanks for your help!

**Comment by ronit-mukherjee** [comment]
> Can you show how you're initializing your data sources? They are meant to be created per request, so memoized results are only cached for the duration of a request.

It really helped me. I was madly looking for a solution. Thanks a lot
