### ISSUE TITLE
apollo-server 2.3.0 instrospection=true in PROD not working

### ISSUE THREAD

**Issue by ricardo-lopes** [apollographql/apollo-server#2100]
In apollo-server 2.2.2, we set introspection:true in NODE_ENV=production to have instrospection in production (Docker + Rancher)
When we upgraded to 2.3.0, this doesn't work and instrospection is not working. We get:

{
    "errors": [
        {
            "message": "GraphQL introspection is not allowed by Apollo Server, but the query contained __schema or __type. To enable introspection, pass introspection: true to ApolloServer in production",
            "type": "Error",
            "identifier": null,
            "stack": "GraphQL introspection is not allowed by Apollo Server, but the query contained __schema or __type. To enable introspection, pass introspection: true to ApolloServer in production\n\nGraphQL request (2:3)\n1: {\n2:   __schema {\n     ^\n3:     types {\n\n    at Object.Field (/app/node_modules/apollo-server-core/src/ApolloServer.ts:62:9)\n    at Object.enter (/app/node_modules/graphql/language/visitor.js:324:29)\n    at Object.enter (/app/node_modules/graphql/language/visitor.js:366:25)\n    at visit (/app/node_modules/graphql/language/visitor.js:254:26)\n    at visitUsingRules (/app/node_modules/graphql/validation/validate.js:77:22)\n    at Object.validate (/app/node_modules/graphql/validation/validate.js:62:10)\n    at validate (/app/node_modules/apollo-server-core/src/requestPipeline.ts:293:22)\n    at Object.<anonymous> (/app/node_modules/apollo-server-core/src/requestPipeline.ts:198:30)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/apollo-server-core/dist/requestPipeline.js:4:58)"
        }
    ]
}

**Comment by ricardo-lopes** [comment]
closing the issue: our rancher was caching old docker images and not updating

**Comment by an-nkur** [comment]
query={__schema{types{name,fields{name}}}}

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
[](url)

**Comment by an-nkur** [comment]
__
