### ISSUE TITLE
[Docs] Deploy to Netlify instructions

### ISSUE THREAD

**Issue by sw-yx** [apollographql/apollo-server#2104]
Hi friends,

I work at Netlify and am looking to help better document how to deploy apollo-server serverless-ly. Would this be a welcome contribution? Any other things I should be aware of/anything that's been on your wishlist?

Currently you have docs for Heroku, Serverless, and Now (https://github.com/apollographql/apollo-server/tree/master/docs/source/deployment). I suppose it'd just be adding another doc in there? any other places this would be welcome?

thank you for your great work!

**Comment by sbrichardson** [comment]
I saw this link, not sure if it was relevant.

https://github.com/apollographql/apollo-server/pull/1733

**Comment by sw-yx** [comment]
oh, wonderful! I'll close and watch that one
