### ISSUE TITLE
Async Lambda Deploy Problems

### ISSUE THREAD

**Issue by BrianSHenderson** [apollographql/apollo-server#2106]
I am attempting to take the code example at:
https://www.apollographql.com/docs/apollo-server/deployment/lambda.html#Modifying-the-Lambda-response-Enable-CORS

And make it work with my asynchronous connections to MongoDB

So far my code looks like:

const createHandler = async () => {
	let client = await MongoClient.connect(uri);
	const server = new ApolloServer({
		typeDefs,  
		resolvers,
	});
	return server.createHandler({
		cors: {
			origin: '*',
			credentials: true,
		},
	})
}

module.exports.graphqlHandler = (event, context) => {
    return createHandler().then(handler => {
		handler(event, context)
	});
}

My serverless.yml file looks like:
service: apollo-graphql
provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: dev
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true

Looking at the logs on CloudWatch I don’t see any errors although doing a POST gives an Internal server error.  Any ideas what I’m doing wrong?

**Comment by braidn** [comment]
@BrianSHenderson I have a very similar setup to yours (code below) and am running into the same issue. Is yours hitting the timeout limit set in your CloudFormation template? No matter how much timeout I give the handler, it will consume all of it and throw this internal server error. 

Wondering if you found a fix for your issue?

```javascript
exports.handler = (event, context, callback) => {
  console.log("remaining time =", context.getRemainingTimeInMillis());
  console.log("functionName =", context.functionName);
  console.log("AWSrequestID =", context.awsRequestId);
  console.log("logGroupName =", context.logGroupName);
  console.log("logStreamName =", context.logStreamName);
  console.log("clientContext =", context.clientContext);

  context.callbackWaitsForEmptyEventLoop = false;

  startServer(event, context)
    .then(handler => {
      return handler(event, context, callback);
    })
    .catch(err =>
      callback(null, {
        statusCode: err.statusCode || 500,
        headers: { "Content-Type": "text/plain" },
        body: "Handlers Failed to Start"
      })
    );
};
```

**Comment by BrianSHenderson** [comment]
I failed to track down any solution to this but I'm still interested if you can resolve this one. I didn't have any timeouts with Cloudformation just callbacks from the functions

**Comment by rockingelevator** [comment]
same problem

**Comment by abernix** [comment]
I realize it's been quite some time since you opened this, but if you haven't already figured this out, I'd recommend taking this question to the [Apollo community on Spectrum.chat](https://spectrum.chat/apollo) to discuss it further.  Thanks!
