### ISSUE TITLE
apollo-server not reporting SSR queries to dashboard apollo engine

### ISSUE THREAD

**Issue by maapteh** [apollographql/apollo-server#2127]
Hi Team. We first used the apollo-engine with apollo-server setup because it offered cacheControl. Then we found out it didn't for full queries and also our clients stayed unnamed. So we ditched the apollo-engine and moving to apollo-server alone.

But now it seems the SSR operations are totally not logged while with the engine it did. Is there something we miss in the documentation? Only the client side operations are now visible in our dashboard.

**Comment by JakeDawkins** [comment]
Hi @maapteh, this issue looks a little old, so I'm not sure if you're still having issues with this. 

We did add whole-query caching to Apollo-server recently, so you shouldn't need to use the engine proxy like you used to. If this is still an issue with a newer version of apollo-server let me know.
