### ISSUE TITLE
Why not to make selections of selectionSet an object?

### ISSUE THREAD

**Issue by Gentlee** [apollographql/apollo-server#2128]
I need to know should I query field from db or not in my resolver, and I use `info` argument to determine that:

```
user(_, __, { db, user }, info) {
    const userField = info.fieldNodes[0].selectionSet.selections.find(x => x.name.value === 'user');
    const hasChatBlacklist = userField.selectionSet.selections.some(x => x.name.value === 
'chatBlacklist');
    // query db
}
```

As you see i make two array iterations (_find_ and _some_) and create two functions for them, but if `selections` is an object i could do it much simpler and faster.

```
const userField = info.fieldNodes[0].selectionSet.selections['user];
const chatBlacklist = userField.selectionSet.selections['chatBlacklist'];
```

**Comment by sbrichardson** [comment]
This design/code isn't part of Apollo, it's from the Facebook `graphql` library. 

Here's a link to the source or similar.
https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js

**Comment by Gentlee** [comment]
@sbrichardson yeah thanks, i'll write there. I use pure mongodb.

**Comment by sbrichardson** [comment]
I some recursive example code

**Comment by Gentlee** [comment]
@sbrichardson i'll try to use it, thanks!
