### ISSUE TITLE
Add azure functions examples to docs v2

### ISSUE THREAD

**Issue by ErickWendel** [apollographql/apollo-server#2130]
At the deployment section the azure examples was only at the v1. Now we need to create the new docs at v2 adding azure code samples. 

I’m working now at this, I’ll put here my pull request later

**Comment by galvesribeiro** [comment]
Hello @ErickWendel 

I've saw your PR on the docs and I've followed it. It looks similar to what is explained on the package's README.md https://www.npmjs.com/package/apollo-server-azure-functions

So far I have it running, but when I try to set the context object like this:

```
const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: ({ req }) => {
    const token = req.headers.authorization || '';

    const user = { token: token }; //Just being dumb

    return { user };
  }
});
export default server.createHandler({
  cors: {
    origin: true,
    credentials: true,
  }
});
```

I get that `req` is `undefined`. Can you update your PRs to elaborate on how are we supposed to get the function parameters?

Thank you!

**Comment by galvesribeiro** [comment]
Sorry... I think I think I've created the issue before dig further... if I change from `({ req }) => ...` to `({ request }) => ...` it works!

Perhaps you could add it to the docs. 

Thanks anyway!

**Comment by trevorblades** [comment]
Our docs now have some instructions around deploying a server to Azure Functions: https://www.apollographql.com/docs/apollo-server/deployment/azure-functions/
