### ISSUE TITLE
Missing npm page for apollo-server-env

### ISSUE THREAD

**Issue by dandv** [apollographql/apollo-server#2132]
At https://www.npmjs.com/package/apollo-server-env I see 

![image](https://user-images.githubusercontent.com/33569/50389432-14ec1280-06df-11e9-8183-76e4a8bb12c1.png)

What does this package do? Its [package.json](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-env/package.json) could use a "description" field.

**Comment by sbrichardson** [comment]
It's used internally by a few of the apollo packages, such as the rest datasource package. I think it's main point is to re-export some common utilities with types.

**Comment by dandv** [comment]
Any chance that package might not set up dependencies [the way Node does](https://github.com/pnpm/pnpm/issues/801)? It can't be found when trying to launch a server with pnpm - see #2151.

**Comment by dandv** [comment]
Any chance that package might not set up dependencies [the way Node does](https://github.com/pnpm/pnpm/issues/801)? It can't be found when trying to launch a server with pnpm - see #2151.

**Comment by abernix** [comment]
Fixed via b236cf5c3ef9779d76fb9d6f942658cf20302dac, but won't appear on npm until the next publish.  As noted in your https://github.com/apollographql/apollo-server/issues/2151, it's possible this was not working with `pnpm` before #3012, but hopefully this is now resolved.
