### ISSUE TITLE
why error locations is an array 

### ISSUE THREAD

**Issue by ph55** [apollographql/apollo-server#2138]
```json
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ]
```

why not 
```json
      "location": {
          "line": 5,
          "column": 5
        }
```

Never seen more than one object in locations.
Also errors always split. So for every errored field you have separate error with it's locations.

Jus wonder is there actually some case when `locations` have more than one object.

**Comment by abernix** [comment]
This is to be expected.  Please consult [the GraphQL Specification section on _Errors_ (subsection _Error result format_)](https://graphql.github.io/graphql-spec/June2018/#sec-Errors) for more information.
