### ISSUE TITLE
graphql returning 404 after express middleware

### ISSUE THREAD

**Issue by rehat101** [apollographql/apollo-server#2141]
I'm trying to add basic auth process before accessing the graphql end point. However, I get a 401 unauthorized access.

```
app.use('*', basicAuth({
	users: { 'admin' : 'admin'},
	challenge: true
}));

QLServer.applyMiddleware({ app, path: '/api/graphql' });
```

When I remove the express middleware the end point works fine and returns json.

**Comment by sbrichardson** [comment]
Could you share the `basicAuth` code? You may need to review how express middleware is called.

`basicAuth` will be invoked with (req, res, next).

The way you are calling it there, it should return a function that accepts (req, res, next). You would need to call next() in the middleware to proceed with the route flow.

**Comment by rehat101** [comment]
I'm using this library with express for basic auth: https://github.com/LionC/express-basic-auth

**Comment by sbrichardson** [comment]
Not sure, I would probably start with something simpler to make sure you have the middleware flow correct.

```js
// Test basic
const auth = async (req, res, next) => {
  console.log('auth v1', req.headers)
  next()
}
```

If that works, move onto adding the identifyUser function.

Can you include your full express/apollo server setup, and show where you are adding middleware code etc? I would also remove the res.status code and focus on calling next() if valid or throwing an error if not, until the routing flow is working.

**Comment by rehat101** [comment]
The above test you pasted does work. 

Here is my full server code:


```javascript
import c from 'template-colors';
import express from 'express';
import { ApolloServer } from 'apollo-server-express';
import {typeDefs, resolvers} from './resolvers';
import { queryOne, queryAll, updateOne } from './datasources/database';
import Promise from 'bluebird';

const app = express();
const HTTP_PORT = 4000;

const QLServer = new ApolloServer({
	typeDefs,
	resolvers,
	dataSources: () => {
		return {
			db: {
				queryOne,
				queryAll,
				updateOne
			}
		}
	}
});

const identifyUser = (req, res) => {

	const b64auth = (req.headers.authorization || '').split(' ')[1] || '';
	const [login, password] = Buffer.from(b64auth, 'base64').toString().split(':');

	if(login == 'admin' && password == 'admin') {
		res.status(200);
		return;
	}

	res.status(401);
	res.set({ 'WWW-Authenticate': 'Basic realm="401"' });
};

const auth = async (req, res, next) => {

	identifyUser(req, res);
	next();
};

app.use('*', auth);
QLServer.applyMiddleware({ app, path: '/api/graphql' });
app.listen(HTTP_PORT, () => console.log(c`🚀 http server started on port ${HTTP_PORT}.bold.green`.green));
```

**Comment by rehat101** [comment]
I think I know what's happening, graphql makes two calls:

1. GET interface (html)
2. POST data (JSON)

on the first call I do get 200 and the flow continues however when the second POST call happens there are no credentials supplied and this yields to a 401
