### ISSUE TITLE
Please allow multiple operations in one test using apollo-server-testing.

### ISSUE THREAD

**Issue by brunoreis** [apollographql/apollo-server#2144]
When running two mutations sequentially in one test this error is thrown: 

```js
 Error: Please use the dataSources config option instead of putting dataSources on the context yourself.
```

That's because `initializeDataSources` is being called at every mutation with this check:

```js
if ('dataSources' in context) {
    throw new Error('Please use the dataSources config option instead of putting dataSources on the context yourself.');
} 
```

Having a global ref to the context and deleting it works for now:

```js
delete context.dataSources;
```

But sure is a hack. So, my suggestion is to clean up things so that two mutations can be called in a single test. Maybe adding this extra step is a performance issue so it could be an optional call. Since deleting `context.dataSources` worked for me, that might be the only needed step.

**Comment by trevor-scheer** [comment]
Hey @brunoreis, thanks very much for reporting this! We think this is a great idea, and would definitely review a PR. If you (or anyone else) are interested in working on this, that would be great - thanks! Otherwise, a reproduction would be great if you choose not to implement this.

**Comment by glasser** [comment]
We removed `apollo-server-testing` in Apollo Server 3 and removed the `dataSources` option in Apollo Server 4. (Additionally, the `executeOperation` method (the equivalent of `apollo-server-testing`) now takes a context value directly instead of calling the context function.)
