### ISSUE TITLE
Use command 'npx apollo service:push --endpoint=http://localhost:4000' error !

### ISSUE THREAD

**Issue by LPink777** [apollographql/apollo-server#2145]
I started fullstack-toturial, when i push service to engine, Whether use VPN or not it have some problems when i use command 'npx apollo service:push --endpoint=http://localhost:4000' ,  what shou i do?

![image](https://user-images.githubusercontent.com/19523872/50539247-29854a80-0bb8-11e9-950d-7dd97a7270e6.png)

ps(use vpn)

**Comment by trevor-scheer** [comment]
Hey @LPink777, thanks for submitting an issue. Can you please provide more information to reproduce the issue? Please see the issue template if you're unsure. Thanks!
