### ISSUE TITLE
Incompatible with pnpm

### ISSUE THREAD

**Issue by dandv** [apollographql/apollo-server#2151]
If I try to launch the [basic server example](https://www.apollographql.com/docs/apollo-server/getting-started.html), I get `Error: Cannot find module 'apollo-server-env'`:

```
$ pnpm init -y
$ pnpm install --save apollo-server graphql
$ node index.js
```

**Comment by zkochan** [comment]
This was reported again in the pnpm repo: https://github.com/pnpm/pnpm/issues/1715

apollo-server-env should be either a regular prod dependency of graphql-extensions or it should be a peer dependency in graphql-extensions.

This might currently work with npm/yarn (and with pnpm, when used with the `shamefully-flatten=true` config) but it is a bug that may even allow graphql-extensions to require non-compatible versions of apollo-server-env
