### ISSUE TITLE
Azure Functions context.log function

### ISSUE THREAD

**Issue by deman4ik** [apollographql/apollo-server#2165]
How can I use context.log function from my resolvers with apollo-server-azure-functions?

**Comment by deman4ik** [comment]
Found solution.

`const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: ctx => ({
    context: ctx.context
  })
});`

and in resolver

`(_,  __, { context }) => {
    context.log("Log message!");
}`

**Comment by AccsoSG** [comment]
How can I use context.log within formatResponse, formatError oder plugin functions?
