### ISSUE TITLE
Apollo server for koa passes wrong argument to context function?

### ISSUE THREAD

**Issue by samuelgozi** [apollographql/apollo-server#2167]
Im using `apollo-server-koa@2.3.1`, In the documentation for authentication here:
https://www.apollographql.com/docs/apollo-server/features/authentication.html
The code example shows that the context function receives an object with the property `req` inside of it, however, the object passed to it looks like this:
```js
{
  ctx: {
    req,
    ...etc
  }
}
```

So either the example is wrong, or most likely the argument passed to the context is.

**Comment by chenglabs** [comment]
.... or both are correct ;-)
It's just object destructuring. The code example only wants the req property of the passed object.

**Comment by samuelgozi** [comment]
@chenglabs i think you didn’t understand the issue.
The examples are wrong because the object doesn’t have a ‘req’ property. It has a ‘ctx’ property thane has a ‘req’ prop, or ‘ctx.req’, so the object destruction won’t work like in the examples.

**Comment by chenglabs** [comment]
Ah.. ok. I understand your issue.
I only know apollo-server-express, the object passed is
{ req,
  ..etc
}

**Comment by daerion** [comment]
Correct, documentation seems to not be in sync with implementation of `apollo-server-koa`. I can verify that this implementation passes an object with a `ctx` property to the context function, as opposed to the `ctx` object itself.
I think this is a good thing too, and anyway couldn't be changed without breaking existing code, but it should probably be mentioned in the docs.

**Comment by japrogramer** [comment]
I notice this too, it doesn't bother me.
However i noticed that for subscriptions the ctx object
is not passed at all .. which is problematic for me .. since i use it
to attach my db connection.

```
const apollo = new ApolloServer({
  typeDefs,
  resolvers,
  mocks,
  //optional parameter
  context: async ({ connection, ctx }) => {
    debugger;
    let context = {}
    if (ctx){
      const { req } = ctx;
      //const { req } = ctx;
      context.db = ctx.app.context.db;
      if (connection) {
        // check connection for metadata
        return connection.context;
      } else {
        // check from req
        const token = req.headers.authorization || "";
        context.token = token;
      }
    }
    return context
  },
  onHealthCheck: () =>
    new Promise((resolve, reject) => {
      //database check or other asynchronous action
    }),
});

```

**Comment by martijnwalraven** [comment]
We won't be directly maintaining integrations with specific frameworks in Apollo Server 3, so closing this issue.
