### ISSUE TITLE
Docs: Broken link for Performance Guide in many place

### ISSUE THREAD

**Issue by hriziya** [apollographql/apollo-server#2171]
I am looking at [What's New](https://www.apollographql.com/docs/apollo-server/whats-new.html) page and found that few links which refers as "Performance Guide" are broken and pointed non-existed url.
e.g. Under **CDN integration** the "Peformance Guide" is pointed to https://www.apollographql.com/docs/guides/performance.html#cdn

Under **Automatic Persisted Queries** the link "APQ section of the performance guide" is pointed to https://www.apollographql.com/docs/guides/performance.html#automatic-persisted-queries

**Comment by brantchoate** [comment]
Seems they are waiting until whole query caching is ready to put it back up? - https://github.com/apollographql/apollo-server/pull/1967#discussion_r233884937

**Comment by jvivs** [comment]
Any clue as to when this documentation might land? I'd like to be able to make the case for CDN-level caching of read-only queries that is called out in short form [here](https://www.apollographql.com/docs/apollo-server/whats-new.html#CDN-integration), but I don't have any detailed documentation to back it up.

A raw version of the content would be enough. @abernix are you or anyone else able to fill in the broader community here?

**Comment by abernix** [comment]
@hriziya 	Thank you for reporting this.   While this gets sorted out, I believe the content in [this blog post](https://blog.apollographql.com/automatic-persisted-queries-and-cdn-caching-with-apollo-server-2-0-bf42b3a313de is identical to that which was once in the guide.  The raw content can also be found (still in the `apollographql/apollo` repository, but just in an `old` directory) at https://github.com/apollographql/apollo/blob/master/docs/source/old/performance.md.

Hope this helps in the short-term, and we'll try to get it fixed up soon.

**Comment by techyrajeev** [comment]
Please fix the broken links its has been really painful to land on 404 page when you are really stuck and scrolling hours and hours to find something very urgent.

**Comment by fangjj** [comment]
how to use createPersistedQueryLink in apollo-boost for Automatic Persisted Queries.
https://github.com/apollographql/apollo-client/issues/4674

**Comment by JakeDawkins** [comment]
I think this has been resolved now. We've also implemented a link-checking system in CI for our docs, so hopefully this kind of issue won't resurface. Thanks!
