### ISSUE TITLE
[apollo-datasource-rest] caching when using custom resolver

### ISSUE THREAD

**Issue by sarkistlt** [apollographql/apollo-server#2180]
As I understood cache will work only if I will use one of the following build in methods `this.get, this.patch, etc` correct?

In my case REST-API build with feathersjs, so queries will contains array, boolean types etc, and for some reason build in methods transform  all properties in the query to string. is there any workaround for this? for example be able to pass you `fetch` function when creating class from `RESTDataSource`, or any other suggestions?

**Comment by martijnwalraven** [comment]
Can you explain in more detail what issue you're running into here? The built-in convenience methods like `this.get` all result in an HTTP fetch that will respect caching headers set on the response. It shouldn't matter how the underlying REST API is implemented, as long as it sets those headers.
