### ISSUE TITLE
RESTDataSource put method doesn't seem to stringfy arrays

### ISSUE THREAD

**Issue by arthurepc** [apollographql/apollo-server#2186]
I built an apollo server to communicate with a REST API and implemented a RESTDataSource in order to do it. I use methods with post, put and delete and all of them work just fine. The following implementation illustrates how I'm using the inherited methods:
`putMethod = async (array) => {
      return await this.put("/foo", JSON.stringify(array))
    }`

However, if I don't use JSON.stringify, the parse doesn't seem to work. I receive a bad request, as if I had not sent the correct data type. Is this the expected behavior for the HTTP put method implemented in RESTDataSources?

**Comment by arthurepc** [comment]
Should this issue be closed since the PR with the solution is merged?

**Comment by abernix** [comment]
Yes, thank you for the reminder, @arthurepc!  Fixed in 2.4.0 thanks to @aireyc1 in #2219.
