### ISSUE TITLE
Feature: @live and @defer

### ISSUE THREAD

**Issue by faisalhasnain** [apollographql/apollo-server#2189]
I see it's mentioned in the [roadmap](https://github.com/apollographql/apollo-server/blob/master/ROADMAP.md), any plans about how it's coming along in future?

**Comment by yorrd** [comment]
very interesting to us too, not sure what has happened since January 2018 in this direction. We're ready to switch as soon as we have live data support without polling

**Comment by literalpie** [comment]
[this](https://github.com/apollographql/apollo-server/issues/2360#issuecomment-467531848) should help:
> we definitely want to support those directives [@live, @defer, @stream] as part of this work. In fact, the 3.0 roadmap is inspired by our first spike on defer last year which helped us to find the gaps in execution and transport configuration that the 3.0 looks to solve

**Comment by literalpie** [comment]
Based on the [latest roadmap](https://github.com/apollographql/apollo-client/blob/master/ROADMAP.md), it seems like defer and stream are planned for “after 3”

**Comment by itsezc** [comment]
@literalpie Don't see no `@live` mentioned on the roadmap anymore, is it still planned?

**Comment by jessecravens** [comment]
curious as well .. can you just provide a simple update , so folks have a basic understanding of future plans.

**Comment by jakesyl** [comment]
@itsezc it's still in the roadmap. Last part of this [page](https://github.com/apollographql/apollo-client/blob/master/ROADMAP.md#after-apollo-client-30).

**Comment by itsezc** [comment]
I believe `@live` has been renamed to `@stream`

**Comment by itsezc** [comment]
@jakesyl just reviewed it again but it looks to be removed.

**Comment by dmitry** [comment]
Any page with a description what is `@live` about?

**Comment by jakesyl** [comment]
@itsezc huh - looks that way.

@dmitry - https://youtu.be/ViXL0YQnioU?t=1090 this is from react europe, I've skipped to the part where they show `@live`

**Comment by johnculviner** [comment]
Please please please consider keeping going on this....

This solves one of my biggest gripes with GQL - your response performance is limited to the performance characteristics of the slowest resolver dependency unless you issue multiple queries which really limits the ability of GQL to serve as a near perfect abstraction over legacy APIs etc.

I have 3 queries to paint a page now to keep things performing and it's a real mess... they are aptly named `fastQuery` `mediumQuery` and `slowQuery` 😦

**Comment by glasser** [comment]
The implementation of `@defer` in `graphql-js` is close to done, though there are still some tweaks being made. We are hoping to support it in Apollo Server this year!

**Comment by hwillson** [comment]
We'll be tracking `@defer` / `@stream` work in https://github.com/apollographql/apollo-server/issues/5893. Thanks!
