### ISSUE TITLE
RESTDataSource - POST body as array

### ISSUE THREAD

**Issue by bartverbruggen** [apollographql/apollo-server#2196]
There seems to be a problem when trying to send an array as body with the RESTDataSource post call.

When trying to execute following function, the endpoint receives an empty body in the request.

```javascript
async addMultipleItems({ input = [{...}, {...}, ...] }: any) {
  return this.post('/items', input)
}
```

The `res.body` of the endpoint should contain `[{...}, {...}, ...]` but contains `{}`.

Any help?

**Comment by bartverbruggen** [comment]
I've temporary fixed this by setting the content type header in de post:

```javascript
  async addMultipleItems({ input = [{...}, {...}, ...] }: any) {
    return this.post('/items', JSON.stringify(input), {
      headers: {
        'Content-Type': 'application/json',
      },
    })
  }
```

But if this is done in `RESTDataSource.ts` for objects, I think the same should be true for arrays.

**Comment by trevorblades** [comment]
This appears to be resolved by https://github.com/apollographql/apollo-server/pull/2219
