### ISSUE TITLE
[apollo-datasource-rest] - "TypeError cannot read property of 'fetch' of undefined" 

### ISSUE THREAD

**Issue by markcdev** [apollographql/apollo-server#2240]
Node - 10.15.0
Typescript - 3.1.2
apollo-datasource-rest - 0.1.5

I have a very simple data source class that extends the RESTDataSource class and makes a GET call to the star wars api. However at run time I'm getting the following error - "TypeError cannot read property fetch of undefined" which is located from line 148 in the RESTDataSource.js file on the following line - 

`const response = yield this.httpCache.fetch(...`

**Comment by markcdev** [comment]
AH! I for some reason node-fetch wasn't included as a dependency! please close, sorry.

**Comment by cgatian** [comment]
Shouldnt this be a peer-dependency of the package?

**Comment by cgatian** [comment]
Im having the same issue. Im calling the built-in get methods to `RESTDatatSource` and it's also throwing an exception 

```
"Cannot read property 'fetch' of undefined",
```

**Comment by jplock** [comment]
I just ran into this and had to call `initialize(config)` in the constructor to initialize the `HTTPCache`:

```
class MyAPI extends RESTDataSource {
  constructor(config) {
    super();
    this.initialize(config);
  }
}
```

**Comment by abernix** [comment]
@jplock What version of Apollo Server were you using that Data Source with?  Did you have that data source declared in the `dataSources` property of the `ApolloServer` constructor?  The `initialize` function is called automatically, so you shouldn't need to call it explicitly:

https://github.com/apollographql/apollo-server/blob/8850e0f7ed368b06952318a9d0d4fd34ae34d711/packages/apollo-server-core/src/requestPipeline.ts#L450-L464

**Comment by jplock** [comment]
@abernix we're using `apollo-server-lambda` `v2.4.3`

**Comment by abernix** [comment]
Aha, that makes sense.  Since `DataSource`s intentionally don't call `initialize` and, as I demonstrated above, are only initialized by the server itself, you would need to call `initialize` manually in your case.  I would advise calling `.initialize` directly, not adding it to the constructor as you've done above, but I would strongly recommend testing the datasources using [`createTestClient`](https://www.apollographql.com/docs/apollo-server/features/testing.html#createTestClient) as seen in that guide on testing from the server docs, which actually has an example for testing `RESTDataSource`s.

I'll close this, but happy to assist further if I can be of help.

**Comment by mrdulin** [comment]
Hit this issue.

After reading @abernix 's explain. Here is my case:

I don't inject my application datasource to `ApolloServer` directly. Because I think `dataSource` like `DAO`.  Instead of injecting to `ApolloServer` `dataSources`, I inject my datasources to service layer, the business logic layer.  The code like this: 

```ts
  const context = {} as ApplicationContext;
  const cache = new InMemoryLRUCache();
  const httpDataSourceConfig: DataSourceConfig<ApplicationContext> = { context, cache };

  const customerDataSource = new CustomerDataSourceImpl(googleAdwordsDataSourceOptions);
  customerDataSource.initialize(httpDataSourceConfig);
  const managedCustomerDataSource = new ManagedCustomerDataSourceImpl({
    baseURL: `https://us-central1-${process.env.GOOGLE_CLOUD_PROJECT}.cloudfunctions.net/`,
  });
  managedCustomerDataSource.initialize(httpDataSourceConfig);


const managedCustomerService = new ManagedCustomerService({
          managedCustomerDataSource,
          googleAccountDataSource,
          userDataSource,
          googleAdwordsDataSource,
        }),
```

And, I inject these serivces to Apollo context.

**Comment by gingerizer** [comment]
I was also having this issue and for me the solution was 
`
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = "0";
`

**Comment by mImranAziz** [comment]
In my case error was in ~\node_modules\apollo-datasource-rest\src\RESTDataSource.ts, 

line await this.httpCache.fetch(request

I resolved this by initializing httpCache as:

constructor() {
    super();
    this.baseURL = v6url;
    this.httpCache = new HTTPCache()
  }

So it's not null.

**Comment by abernix** [comment]
@mImranAziz DataSources have their `initialize` method called automatically by Apollo Server if they are declared in the `dataSources` Array of the `ApolloServer` constructor options:

https://github.com/apollographql/apollo-server/blob/1948d2411ea590c0e49db01032da6b4183b110c1/packages/apollo-server-core/src/requestPipeline.ts#L580-L587

The default `cache` should be set to an `InMemoryLRUCache` if you haven't specified a top-level `cache` yourself:

https://github.com/apollographql/apollo-server/blob/489cbb42cd6cd5c50c60cfaca93060912c44d20e/packages/apollo-server-core/src/ApolloServer.ts#L212-L214

Do any of these things sound possible?  Your workaround shouldn't be necessary.

**Comment by esemeniuc** [comment]
@abernix I also needed to use @mImranAziz fix. Running Recent apollo server 2.8.0 as well.

**Comment by linteck** [comment]
@abernix Why does "DataSources have their initialize method called automatically by Apollo Server"? Is it necessary? Why not put the initializer() into the constructor? Or at least write this trick into document.

**Comment by wzup** [comment]
@abernix 
Somehow this is not true.
If you do not call `initialize` directly, it is never set auto-magically.

**Comment by wzup** [comment]
@markcdev 
> AH! I for some reason node-fetch wasn't included as a dependency! please close, sorry.

And what does it mean? What actions are you expecting from us after your AH!-answer?

**Comment by robe007** [comment]
I had the same problem with `apollo-datasource-rest` combined with `graphql-yoga`, but I can make it work.

You can see my comments about it [here](https://github.com/apollographql/apollo-server/issues/3882#issuecomment-693954273)
