### ISSUE TITLE
503 and 504 errors

### ISSUE THREAD

**Issue by elie222** [apollographql/apollo-server#2243]
Any idea where 503 and 504 errors on Apollo Server may be coming from?

Did a recent update to my server, while leaving the client as is and a lot of our users getting this error in our logs.

**Comment by jsegaran** [comment]
I realize it's been quite some time since you opened this, but if you haven't already figured this out, I'd recommend taking this question to the [Apollo Server channel within the Apollo community on Spectrum.chat](https://spectrum.chat/apollo/apollo-server) to discuss it further.  Thanks!

**Comment by sagun786** [comment]
I also getting '503 Service Temporarily Unavailable' discretely for Apollo GraphQL Federated Gateway error every now and then after hosting it on AWS ECS Fargate Containers via Dockerhub

I also found this: 
https://stackoverflow.com/questions/60956235/apollo-server-responding-with-503-error-after-deploying-to-heroku

**Comment by NTonani** [comment]
@sagun786 were you able to find a reason for the 503s? had you fronted fargate with a load balancer? I'm encountering the same issue.
