### ISSUE TITLE
ApolloServer.applyMiddleware doesn't support OPTIONS requests

### ISSUE THREAD

**Issue by rgtk** [apollographql/apollo-server#2253]
*As far as I know, it only applies to Koa integration. Could be for other integrations, too.*

`ApolloServer.applyMiddleware` only add middleware to support GET and POST requests. It should also support OPTIONS. Otherwise it will break setup when client and server are on different hosts.

**Why does it matter?** Given you want to access GraphQL server (at `graphql.local`) on web client (at `frontend.local`) browser will [send OPTIONS request](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Functional_overview) before any user request to make sure `graphql.local` accepts requests made from `frontend.local` (via `Access-Control-Allow-Origin` header).

**Comment by abernix** [comment]
I would happily review a PR which adds this!  There are implementations of this in other integrations (it is missing from `-express`, `-koa`, and probably others) which can be used as prior art.

For example, the Azure Functions integration :

https://github.com/apollographql/apollo-server/blob/6c87cbc291a8bb0eaf2a1a038f9f97087ce1035b/packages/apollo-server-azure-functions/src/ApolloServer.ts#L116-L124

...and in the Google Cloud Functions implementation as well:

https://github.com/apollographql/apollo-server/blob/b61dee310bbf6299fe6ed184029fb475bfb23aa2/packages/apollo-server-cloud-functions/src/ApolloServer.ts#L118-L122

**Comment by rgtk** [comment]
I am trying to test the implementation but I cannot find a straightforward way to test the Koa integration. There is `jest` config and test files but I see no straightforward way to run it.

Can you give me a hand here?

**Comment by cheapsteak** [comment]
It looks like OPTIONS is working for -express (I just checked against fullstack-tutorial)
![image](https://user-images.githubusercontent.com/743976/53028593-2b8bbd00-3435-11e9-9855-e3f43a2df392.png)

I would guess the cors middleware is handling OPTIONS automatically
https://github.com/apollographql/apollo-server/blob/2f773625c0c608ea91fa1d184ed13d149044f545/packages/apollo-server-express/src/ApolloServer.ts#L148-L152

**Comment by abernix** [comment]
Ah, that makes sense.  I guess some integrations handle it at another level.  Thanks for pointing this out, @cheapsteak 1
