### ISSUE TITLE
Fresh install fail on Mac: Cannot find module 'core-js/proposals/array-flat-and-flat-map'  

### ISSUE THREAD

**Issue by ulucaydin** [apollographql/apollo-server#2263]
A fresh install fails as follows after including `const { ApolloServer, gql } = require('apollo-server');`:
```
nodemon server.js
[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/ulucaydin/repos/myproject/backend/node_modules/apollo-env/lib/polyfills/array.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[nodemon] app crashed - waiting for file changes before starting...
```

Here is my `package.json`:

```
{
  "name": "backend",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@babel/polyfill": "^7.2.5",
    "babel": "^6.23.0",
    "core-js": "^2.6.3",
    "mongodb": "^3.1.13"
  },
  "devDependencies": {
    "apollo-server": "^2.3.3",
    "apollo-server-express": "^2.3.3",
    "express": "^4.16.4",
    "graphql": "^14.1.1",
    "install": "^0.12.2",
    "mongoose": "^5.4.9",
    "node-zillow": "^2.0.0",
    "nodemon": "^1.18.9",
    "npm": "^6.7.0"
  }
}
```

**Comment by Kivol** [comment]
I was experiencing the exact same problem here. I temporarily fixed it by setting `"core-js": "3.0.0-beta.11"` on `package.json`.

**Comment by franquis** [comment]
Related to https://github.com/apollographql/apollo-tooling/issues/962

**Comment by cd2tom** [comment]
> I was experiencing the exact same problem here. I temporarily fixed it by setting `"core-js": "3.0.0-beta.11"` on `package.json`.

thanks for that! my workaround was to downgrade my apollo-server version. 😬

**Comment by KevinKelbie** [comment]
I'm so relieved I'm not the only one having this issue.

I'm not sure if this helps but I'm on a Mac using express and `apollo-server-express`/`apollo-server` throws the same error OP has.

**Comment by zainulabidin302** [comment]
finally copied core-js "core-js": "3.0.0-beta.11" to 
`cp -rf node_modules/core-js  /usr/local/lib/node_modules/apollo/node_modules/`
phew that's not a good solution but it works for me.

**Comment by kassiomaia** [comment]
The last night I spent some hours investigating this and I was able to solve by installing this version apollo-server@2.0.5 and apollo-server-express@2.0.5.

**Comment by robhicks** [comment]
I have had apollo-server-express (2.3.1) deployed for months on heroku running against express 4.16.4. As of this morning I cannot restart the server successfully because of this error. 

I have tried all of the workaround suggested above. Nothing has worked.

**Comment by guyellis** [comment]
I'm hitting this as well inasmuch as a previously working installation is now no longer working after a new `npm install`. I'm guessing that there's an optimistic dependency in the chain that's been upgraded that's missing a reference to this module as its dependency. <== In case anybody is investigating this.

**Comment by ayhamk94** [comment]
I also had the same problem by just setting up a simple server like in the docs with no extra code

**Comment by eliezer-souza** [comment]
A PR was submitted https://github.com/apollographql/apollo-tooling/pull/961

For hour a solution is installing the "core-js": "3.0.0-beta.3" in application, until o PR to be accepted, but it is not recommended.

**Comment by Gn0ume** [comment]
> For hour a solution is installing the "core-js": "3.0.0-beta.3" in application, but it is not recommended.

It may be any version between 3 and 11, issue is known since 12

**Comment by BrenoMazieiro** [comment]
Thanks @shalkam! This wa worked just fine!

**Comment by abernix** [comment]
Thank you to all those that reported this and supplied the appropriate work-arounds.  This should be fixed, by the fix supplied in `apollo-tooling`'s https://github.com/apollographql/apollo-tooling/pull/961.

There were no changes to `apollo-server` necessary to fix it.

**Comment by stevez86** [comment]
@abernix I'm experience this issue. My comment here: https://github.com/apollographql/apollo-tooling/issues/962#issuecomment-523711520 and my issue here: https://github.com/apollographql/apollo-tooling/issues/1481
