### ISSUE TITLE
apollo-server-core v 2.3.4 with apollo-server-express causes typescript error

### ISSUE THREAD

**Issue by feinoujc** [apollographql/apollo-server#2266]
apollo-server-core v 2.3.4 is causing a build error for me. Downgrading to 2.3.3 fixes the issue. 

I also noticed apollo-server-express 2.3.3 seems to have a pinned dependency on apollo-server-core 2.3.3

```
tsc -b

node_modules/apollo-server-core/src/types/graphql-upload.d.ts(4,16): error TS2451: Cannot redeclare block-scoped variable 'GraphQLUpload'.
node_modules/apollo-server-core/src/types/graphql-upload.d.ts(21,15): error TS2300: Duplicate identifier 'Request'.
node_modules/apollo-server-core/src/types/graphql-upload.d.ts(23,15): error TS2300: Duplicate identifier 'Response'.
node_modules/apollo-server-express/node_modules/apollo-server-core/src/types/graphql-upload.d.ts(4,16): error TS2451: Cannot redeclare block-scoped variable 'GraphQLUpload'.
node_modules/apollo-server-express/node_modules/apollo-server-core/src/types/graphql-upload.d.ts(21,15): error TS2300: Duplicate identifier 'Request'.
node_modules/apollo-server-express/node_modules/apollo-server-core/src/types/graphql-upload.d.ts(23,15): error TS2300: Duplicate identifier 'Response'.
```

**Comment by feinoujc** [comment]
closing since 2.4.0 released

**Comment by rstpv** [comment]
@feinoujc Hello, I'm having this same issue with this setup:
`{
  "name": "some",
  "scripts": {
    "start": "dotenv -- nodemon -e ts,graphql -x ts-node src/index.ts",
    "debug": "dotenv -- nodemon -e ts,graphql -x ts-node --inspect src/index.ts",
    "graphqlcopy": "copyfiles -u 1 src/**/*.graphql dist/",
    "build": "rimraf dist && tsc && npm run graphqlcopy"
  },
  "dependencies": {
    "@apollo/gateway": "^0.6.1",
    "apollo-server": "^2.5.1",
    "bcryptjs": "2.4.3",
    "graphql": "^14.3.1",
    "jsonwebtoken": "8.5.1"
  },
  "devDependencies": {
    "@types/bcryptjs": "2.4.2",
    "@types/bluebird": "^3.5.27",
    "@types/cors": "^2.8.5",
    "@types/express": "^4.16.1",
    "@types/graphql": "^14.2.0",
    "@types/node": "10.14.7",
    "copyfiles": "^2.1.0",
    "dotenv-cli": "1.4.0",
    "nodemon": "1.19.1",
    "rimraf": "2.6.3",
    "ts-node": "7.0.1",
    "typescript": "3.2.2"
  }
}

`

Could you please tell me what did you install or do to solve this issue?

Thank you.
