### ISSUE TITLE
[feature] async formatResponse and formatError

### ISSUE THREAD

**Issue by vinicius73** [apollographql/apollo-server#2274]
Hooks formatResponse and formatError do not accept async operations.
Tools that report errors are difficult to use because formatError does not support async operations.
I particularly need to perform some operations with each graphql response, I can not because formatResponse is not async.

I'm doing tests and adjustments and I intend to send a PR soon, before I'm starting a dialogue about it.

Related #1748

**Comment by dunika** [comment]
I'm running into an issue with with `AWS Lambda`. I am sending my error to `sentry` inside `formatError` but this is an asynchronous operation so there is a chance that the function will close before the message is sent.

**Comment by tanduong** [comment]
Same!

**Comment by BrenoMazieiro** [comment]
Same

**Comment by KyleAWang** [comment]
Same. I need some data from cache or db to decorate response. How can I do it without async support?!

**Comment by Renaud009** [comment]
Any workaround for this? I need to make an http call (apollo-rest-datasource) under certain conditions before returning response. 

Couldn't find any other Apollo Server function that executes after all resolvers are resolved.

**Comment by bertero** [comment]
@vinicius73 any news here? I am facing the same issue...

@dunika My problem is exactly the same, using a very similar stack. Were you able to solve it?

**Comment by martijnwalraven** [comment]
This should be possible by using the new request pipeline plugin API. `willSendResponse` can be async and will allow you to modify the response. For error reporting, `didEncounterErrors` (https://github.com/apollographql/apollo-server/pull/2719) is the hook to use.

**Comment by dunika** [comment]
@martijnwalraven I can't find anything in the docs any of this. Has this been released?

Do you have an example of where/how the `didEncounterErrors` hook is used?


@bertero Sorry for the late response I havn't implemented any solution for this but you could use graphql-middleware](https://github.com/prisma/graphql-middleware) to do I I'd say

**Comment by taikn** [comment]
@dunika Docs seem to be still WIP, I found a preview here:
https://github.com/apollographql/apollo-server/blob/abernix/docs-plugins/docs/source/features/plugins.md
and here is the example of using the `hook`:
https://github.com/apollographql/apollo-server/issues/1709#issuecomment-495793375
