### ISSUE TITLE
Playground not working with apollo-server-express

### ISSUE THREAD

**Issue by DominikMueller64** [apollographql/apollo-server#2279]
### Intended outcome

Show Playground in browser.

### Actual outcome

`Cannot GET /` is shown

### How to reproduce the issue

Run the following sample code from the documentation file

    const express = require('express');
    const { ApolloServer, gql } = require('apollo-server-express');

    // Construct a schema, using GraphQL schema language
    const typeDefs = gql`
      type Query {
        hello: String
      }
    `;

    // Provide resolver functions for your schema fields
    const resolvers = {
      Query: {
        hello: () => 'Hello world!',
      },
    };

    const server = new ApolloServer({ typeDefs, resolvers });

    const app = express();
    server.applyMiddleware({ app });

    const port = 4000;

    app.listen({ port }, () =>
      console.log(`🚀 Server ready at http://localhost:${port}${server.graphqlPath}`),
    );

**Comment by marcellobarile** [comment]
hi @DominikMueller64, can you try adding "playground: true" to the options object you pass when creating the instance of the ApolloServer?

I also suggest you enable it only in dev/test envs.

Further hints: https://www.apollographql.com/docs/apollo-server/features/graphql-playground.html

**Comment by robinelvin** [comment]
I have the same issue even with this:

```typescript
const apolloServer = new ApolloServer({
    typeDefs: gql(typeDefs),
    resolvers: resolvers as any,
    introspection: true,
    playground: true,
    context
});

apolloServer.applyMiddleware({ app });

const server = app.listen(Config.server.port, () => {
    console.log(`GraphQL available at ${apolloServer.graphqlPath}`);
    console.log('CTRL-C to exit');
});
```
Output:
```console
GraphQL available at /graphql
CTRL-C to exit
```
GraphQL requests to /graphql from my app work fine so Apollo Server is running however accessing /graphql from a browser just serves my `webpack-dev-middleware` generated bundle. Removing wdm from my config results in the browser saying:

```
Cannot GET /graphql
```

**Comment by gotexis** [comment]
Perhaps the sequence of how you apply middleware matters.

In this case, `fallback-history` is a middleware although I don't know what it does, but , so if you put it after

```ts
server.applyMiddleware({ app });
``` 

It should work as expected

**Comment by abernix** [comment]
I believe everything here is working properly, but it's worth pointing out that GraphQL Playground is disabled when `NODE_ENV` is set to `production`.  As noted above, it can be explicitly enabled, even in production by passing `playground: true`.

If you have any other questions or you're still having problems with this, feel free to ask in the [Apollo Server channel on the Apollo Spectrum.chat](https://spectrum.chat/apollo/apollo-server).

**Comment by pumuckelo** [comment]
for me it was an issue with the port I used or the bug was caused by chrome.

I cleared cookies and changed the port.

Also before I had another Graphql Server running on port 5000.
If I switched my new application to port 5000 it worked immediately.
On port 4000,8000 etc it didn't work. After I cleared cookies as I got on the website, I changed the port to 12000 and it worked

**Comment by avshetty1980** [comment]
adding options: 
```
introspection: true,
    playground: true,
```
to the ApolloServer intance got the Graphql playground working for me. Thank you.
