### ISSUE TITLE
TypeScript definition missing for error passed to formatError

### ISSUE THREAD

**Issue by dandrei** [apollographql/apollo-server#2294]
Hey everyone,

The `error` parameter sent to the `formatError` function (from the config of `ApolloServer`) is missing TypeScript definitions.

**Comment by abernix** [comment]
It seems possible that we need to specify a more specific type signature here:

https://github.com/apollographql/apollo-server/blob/b89de2675bd795f6f2ec0b606f6bde49e0f9d482/packages/apollo-server-core/src/graphqlOptions.ts#L34

Thoughts?

**Comment by JacksonKearl** [comment]
This was closed in #2343.
https://github.com/apollographql/apollo-server/blob/ca8763e3164db123b178edb134a00c90629e1c84/packages/apollo-server-core/src/graphqlOptions.ts#L38
