### ISSUE TITLE
Security: Subscriptions onConnect not called when client connectionParams throws error

### ISSUE THREAD

**Issue by peterjuras** [apollographql/apollo-server#2296]
The [official documentation](https://www.apollographql.com/docs/apollo-server/features/subscriptions.html#Authentication-Over-WebSocket) states that the `onConnect` callback should be used to protect subscriptions. However, this is not sufficient, since there is a way to bypass the onConnect callback for clients, which will lead to the clients receiving subscription data without going through any validation that might be in `onConnect`.

To reproduce the issue:

1. Clone this [sample repository](https://github.com/peterjuras/graphql-sub-auth-test)
2. Run `yarn install` in both the `client` and `server` folders
3. Run `node server/server`
4. Run `cd client && yarn start`

->
The `onConnect` method in server.js would throw an error if the `authentication` connection paramtter is not "YES". However, since the client is unable to retrieve the `connectionParams` because the method throws an immediate error. The connection from the client is started using a "connection_error" message and the subscription will start to work normally without an invocation of the `onConnect` callback on the server.

If the `throw new Error("Aredos");` line is removed from the client, the `onConnect` error works as expected.

**Expected behavior:**
I expected the `onConnect` callback to have been called in every case before a subscription is set.

**Workaround:**
Return a context object in the `onConnect` callback and validate this context object before subscribing clients to topics in the `subscribe` methods.

**Comment by jedwards1211** [comment]
@peterjuras I think you meant to file this in [apollographql/subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws), right?

**Comment by glasser** [comment]
Direct subscriptions integration was removed from Apollo Server in v3 last year.
