### ISSUE TITLE
JSON parse error on Firebase functions

### ISSUE THREAD

**Issue by skflowne** [apollographql/apollo-server#2331]
I'm trying to host Apollo on Firebase functions and it's mostly working, but the playground is getting a JSON parsing error.

This is what shows up in the response part of the playground, even without making a request : 
`{
  "error": "Unexpected token < in JSON at position 0"
}`

In the browser console I get two errors : 

`POST https://europe-west1-graphql-firestore-fb828.cloudfunctions.net/graphql 404`
coming from httpLink.js line 83

`SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at index.js:40`
coming from Playground.tsx line 268

The server does work as expected if I send a request through curl : 
`
curl "https://europe-west1-graphql-firestore-fb828.cloudfunctions.net/graphql/graphql/?query=query%20%7B%0A%09me%20%7B%20username%20%7D%0A%7D"
{"data":{"me":{"username":"Geoffrey Hug"}}}
`

But the playground gets the JSON parse error and POST 404 and also shows the message 

> Server cannot be reached

In the playground's address bar

Here is my setup : 

In 'functions/graphql/server.js' :
```
const { ApolloServer, gql } = require('apollo-server-express')
const express = require('express')
const cors = require('cors')

const spawnServer = () => {
  const schema = gql`
    type Query {
      me: User
    }

    type User {
      username: String!
    }
  `

  const resolvers = {
    Query: {
      me: () => {
        return {
          username: 'Geoffrey Hug'
        }
      }
    }
  }

  const app = express()

  app.use(cors())

  const server = new ApolloServer({
    typeDefs: schema,
    resolvers,
    uploads: false,
    introspection: true,
    playground: true,
  })

  server.applyMiddleware({ app })

  return app
}

module.exports = spawnServer
```

In 'functions/index.js' : 
```
const functions = require('firebase-functions');

const spawnServer = require('./graphql/server')
const graphqlServer = spawnServer()

exports.graphql = functions.region('europe-west1').https.onRequest(graphqlServer)`
```

I also added a local server to test, 'functions/graphql/localServer.js' : 
``` 
const spawnServer = require('./server')

const server = spawnServer()

server.listen({ port: 8000 }, () => {
  console.log('Running at http://localhost:8000/graphql')
})
```

And there the playground is working properly

I have tried the 'apollo-server-cloud-functions' package as well, following the example of the readme, but this one didn't work at all on Firebase

**Comment by skflowne** [comment]
I found a way to make it work, the issue seems to be that the url in the playground page is wrong.

For example, if I change this code : 
`server.applyMiddleware({ app })`
to
`server.applyMiddleware({ app, path: "/" })`

If I use the firebase emulator, it will host on `http://localhost:5000/graphql-firestore-fb828/us-central1/graphql`
but the address bar in the playground shows `http://localhost:5000/`
And as soon as I change it, it works

The same thing happens when deployed, but then I just need to add the function's name (the real endpoint)

It looks like the address that's set in the playground just concatenates `hostname + graphqlPath`, which in this case doesn't work.

Is there anything that can be done about that ?

**Comment by jbaxleyiii** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
