### ISSUE TITLE
Hello, please, I beg you earlier the new version apollo-server-adonis support apollo-server 2  

### ISSUE THREAD

**Issue by msadeghifard1989** [apollographql/apollo-server#2337]
Hello, please, I beg you earlier the new version apollo-server-adonis support apollo-server

**Comment by trevor-scheer** [comment]
We won't be directly maintaining integrations with specific frameworks in Apollo Server 3, so I'm closing this issue. Please feel free to fork Apollo Server for your own needs, though!
