### ISSUE TITLE
[apollo-server-fastify] NPM url

### ISSUE THREAD

**Issue by zekth** [apollographql/apollo-server#2341]
Just to notify that the github url on the npm repository is wrong: https://www.npmjs.com/package/apollo-server-fastify

It redirects to : https://github.com/w3cmarket/apollo-server-fastify

**Comment by abernix** [comment]
@zekth Do you mind opening a PR to fix this?

**Comment by zekth** [comment]
I wish i could be as i've checked in:
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-fastify/package.json

Everything seems correct. So i deduce it may be in the npm config of the publisher. No ?

**Comment by abernix** [comment]
Hmm, I think the npmjs.com page is just entirely stale because the result when querying the registry directly is certainly correct:

```
$ npm view apollo-server-fastify homepage
https://github.com/apollographql/apollo-server#readme
```

**Comment by abernix** [comment]
I fixed this by switching a different version into and out of the `latest` dist-tag position, which seems to have caused the page to be re-generated.

Thanks for reporting this!
