### ISSUE TITLE
[OpenWhisk] New integration

### ISSUE THREAD

**Issue by JoseCapela** [apollographql/apollo-server#2342]
Hello,
In our current project we are using an architecture based on Adobe I/O and Apache Openwhisk (OW).
We now want enable to GraphQL functionality for our project but there appears to be no current integration with Openwhisk. We tried adapting the existing AWS configuration to Openwhisk but we were not successful.
Is this integration in your roadmap? 
If so, will a package like the apollo-server-lambda be released?
Thanks and best regards

**Comment by martijnwalraven** [comment]
We won't be directly maintaining integrations with specific frameworks in Apollo Server 3, so closing this issue.
