### ISSUE TITLE
aws-lambda used in ApolloServer.d.ts not referenced in package.json

### ISSUE THREAD

**Issue by carlmanaster** [apollographql/apollo-server#2351]
When I run `tsc` on my project which includes apollo-server-lambda 2.4.2 but not aws-lambda, this error is returned:

> node_modules/apollo-server-lambda/dist/ApolloServer.d.ts:1:20 - error TS2307: Cannot find module 'aws-lambda'.
> 
> 1 import lambda from 'aws-lambda';

I can resolve it by 
`yarn add @types/aws-lambda aws-lambda`

but believe that this should be done at the library level.

**Comment by carlmanaster** [comment]
Problem remains on apollo-server-lambda 2.4.3.

**Comment by abernix** [comment]
Should be fixed in 2.9.3!
