### ISSUE TITLE
Integration with uWebSockets.js

### ISSUE THREAD

**Issue by timkendall** [apollographql/apollo-server#2353]
uWebSockets.js looks like an extremely promising HTTP server alternative that provides both an incredibly fast native `http` module replacement and nice JS interface. `apollo-server-uwebsockets` anyone? 

GitHub: https://github.com/uNetworking/uWebSockets.js
Introduction: https://levelup.gitconnected.com/will-node-js-forever-be-the-sluggish-golang-f632130e5c7a

**Comment by martijnwalraven** [comment]
We won't be directly maintaining integrations with specific frameworks in Apollo Server 3, so closing this issue.

**Comment by maxpain** [comment]
I've done integration [here](https://github.com/enisdenjo/graphql-ws/pull/89)
