### ISSUE TITLE
Need context access in formatError

### ISSUE THREAD

**Issue by barry-dutton-ck** [apollographql/apollo-server#2355]
Applies to: `apollo-server-hapi` (and probably more)

The `formatError` function which you can pass into `ApolloServer` when starting has no way to gain access to `context` (or `request`). In previous versions (the old `graphql-server-hapi`), we had access to this. In our workflows, this is necessary because we log these errors using the request log (which we have access to in `context`) and then mask the errors going back to the client them depending on the environment. Is there any way you could add the capability to access `context` as an argument to this function?

**Comment by vincentdesmares** [comment]
We have the same issue with express. We use the context to know in which language the error should be translated.

It would be awesome to have it as a second argument.

**Comment by BigMaster** [comment]
I have solved this problem!
[https://github.com/BigMaster/graphql-format-error-context-extension](https://github.com/BigMaster/graphql-format-error-context-extension)

**Comment by barry-dutton-ck** [comment]
@BigMaster Awesome! That's definitely a helpful workaround to get a usable error formatter. I would still love to see it be a part of the actual exposed function from apollo-server though. Doubly so because I believe the one apollo exposes is actually created the same way that the one you created is!

**Comment by martijnwalraven** [comment]
`formatError` isn't the right place to report errors from, but we've recently exposed a `didEncounterErrors` function as part of the new request pipeline API: https://github.com/apollographql/apollo-server/pull/2719

**Comment by arizonatribe** [comment]
Awfully light on documentation on that one, lol

**Comment by Sytten** [comment]
@martijnwalraven The errors of this hook are readonly, what if you need to modify errors with information from the context?
