### ISSUE TITLE
File upload receiving buffer instead of promise with createTestClient

### ISSUE THREAD

**Issue by JonathanRoyGagnon** [apollographql/apollo-server#2372]
Calling a resolver using createTestClient and a file gives a buffer instead of a promise like you would normally receiving from a client.

```js
// test.js
it('UPLOAD', async () => {
  const file = fs.readFileSync(path.join(__dirname, './test.txt'))

  const UPLOAD = gql`
    mutation upload($files: [Upload!]!) {
      upload(files: $files) {
        location
      }
    }
  `

  const { mutate } = createTestClient(server)

  const res = await mutate({ query: UPLOAD, variables: { files: [file] } })
})
```

```js
// resolver.js
  Mutation: {
    async upload (root, { files }) {
      console.log('Files', files)
      const medias = await Promise.all(files.map(async file => {
        const { stream, mimetype } = await file
        console.log('Info', stream, mimetype)
        // ...
      })).catch(console.error)
      return medias
    }
  }
```

```
console.log resolver.js
  Files [ <Buffer 49 20 61 6d 20 61 20 74 65 73 74 20 66 69 6c 65> ]
  Info undefined undefined
```

Is the Upload scalar supported by createTestClient?

**Comment by WoLfulus** [comment]
I'm also receiving `undefined` in stream. Did you solve this?

**Comment by JonathanRoyGagnon** [comment]
No, I had to leave it out until this is fixed

**Comment by joemckie** [comment]
It feels a little hacky, but I got this to work by doing the following:

```ts
variables: {
  file: {
    createReadStream: () => createReadStream(fileName),
    fileName: 'image.jpg',
    mimetype: 'image/jpeg',
  },
},
```

Instead of using `readFileSync`, pass your own `createReadStream` function that creates a stream with the path to the file you want.

**Comment by loremaps** [comment]
@joemckie does this still works for you?

I am getting the following error:
```
 Received: [[GraphQLError: Variable "$file" got invalid value { createReadStream: [function createReadStream], filename: "image.jpg", mimetype: "image/jpeg" }; Expected type Upload. Upload value invalid.]]
```
Any ideas?

**Comment by joemckie** [comment]
@loremaps I think I removed this code in a refactor when I moved to NestJS unfortunately so I wouldn't be able to test it out any more 😞

**Comment by Nabrok** [comment]
@loremaps I am getting the same error as you, did you find a solution?

**Comment by glasser** [comment]
We are [removing the built-in `graphql-upload` integration in Apollo Server 3](https://www.apollographql.com/docs/apollo-server/data/file-uploads/#uploads-in-node-14-and-later) and are also considering [removing `apollo-server-testing` as a standalone package](https://github.com/apollographql/apollo-server/issues/4952) so I am going to close this issue.

`createTestClient` is a very thin wrapper around `server.executeOperation`, a function that lets you hook directly in to the Apollo Server request pipeline bypassing all HTTP-based processing. This does make doing things like `graphql-upload` which involve a pre-processing step in the HTTP process challenging. I think we should keep executeOperation around as a simple hook for running operations when we don't care about HTTP stuff, but also make it easier (through better documentation or improvements) to test your full HTTP server.

**Comment by electerious** [comment]
The solution of @Nabrok still works. Even when using `server.executeOperation`.

It's also possible to make testing easier by not using a real file. Simply create a variable and a Readable from an iterable and pass it to `server.executeOperation`.

```js
import { Readable } from 'stream'
import Upload from 'graphql-upload/Upload.mjs'

const file = new Upload()
file.promise = Promise.resolve({
    createReadStream: () => Readable.from(['Content']),
    filename: 'file.txt',
    mimetype: 'text/plain',
})

server.executeOperation(
    {
        query: QUERY,
        variables: { file },
    },
)
```

**Comment by allestaire** [comment]
Tried the solutions commented on this thread but still no luck,

`graphql-upload@11.0.0`
