### ISSUE TITLE
Schema Introspection Hiding

### ISSUE THREAD

**Issue by MoonTahoe** [apollographql/apollo-server#2374]
Thank you for making an already awesome server even more awesomer! 

I wonder if it would be possible to improve the `SchemaDirectiveVisitor` class to include something like `visitIntrospectionSchema` that allows you use directives to hide parts of a schema when the introspection query happens?  For Example:

```graphql
type Mutation {
   checkout(cartID: ID!): PurchasePayload!
   removeProduct(id: ID!): RemoveProductPayload! @admin
}
```

It would be nice to hide the `removeProduct` mutation from users who are not logged in as administrators.

Is there already a way to do this? I couldn't figure it out so our solution is to just use two schemas: one for the public and one for administrators.

**Comment by JakeDawkins** [comment]
I don't think we plan on supporting this kind of behavior for now. One of our design principles in [Principled GraphQL](https://principledgraphql.com/integrity#1-one-graph) is to use a single graph for an organization, and not "hide" anything from a specific group.
