### ISSUE TITLE
GraphQL introspection disable is not working

### ISSUE THREAD

**Issue by renceabishek** [apollographql/apollo-server#2380]
It does works using [graphql-disabled-introspection](https://github.com/helfer/graphql-disable-introspection). But I want to do it in Middle Layer. for that i used [this ](https://github.com/graphql-java-kickstart/graphql-spring-boot#graphql-java-tools) in my application .yml file. No Luck yet!
No Exception found. Is there any other way or how to resolve this?

**Comment by zionts** [comment]
Hi @renceabishek, if the `NODE_ENV` is set to `'production'`, then introspection will be turned off by default :) You can see some more details about how this works and how to override that behaviour [here](https://www.apollographql.com/docs/apollo-server/features/graphql-playground/)

**Comment by ollydixon** [comment]
@zionts It's not clear how to enable introspection from that link.

**Comment by glasser** [comment]
Does this help? https://www.apollographql.com/docs/apollo-server/api/apollo-server/#introspection

**Comment by ollydixon** [comment]
@glasser yes, so it looks like this:

```
const server = new ApolloServer({
	typeDefs,
	resolvers,
        introspection: true,
});

```
