### ISSUE TITLE
Lambda ALB Support

### ISSUE THREAD

**Issue by aarongundel** [apollographql/apollo-server#2386]
Hello!  I've observed troubles when trying to get Apollo Server working with AWS Lambda when trying to target the function from an Application Load Balancer (as opposed to API Gateway).  It appears that the HTTP request is delivered to the function differently from the ALB than if it had come through API Gateway, and as a result, Apollo can't find information about the request.  

Using an ALB (instead of API Gateway) is an important thing for our use case because it's easier to support internal VPC traffic.  Has anyone else observed this?

**Comment by abernix** [comment]
The `apollo-server-lambda` integration does expect to work from API Gateway right now.  It may be easier to support internal VPC traffic from an APC, but as an alternative, perhaps the [AWS API Gateway Private Endpoints](https://aws.amazon.com/blogs/compute/introducing-amazon-api-gateway-private-endpoints/) are an option?  Either way, it's unlikely we'll be able to fix this in the current version, but hopefully this will be improved in the future.  

If you think it's possible to concurrently support both (by checking the input, perhaps?), then please do open a pull request!
