### ISSUE TITLE
Is there any way to get the fields what we set in a query?

### ISSUE THREAD

**Issue by cctv1237** [apollographql/apollo-server#2392]
like I want to query
```gql
{
  hero {
    name
    appearsIn
  }
}
```
Is there any way I can get `name` and `appearsIn` in `hero`'s resolver?

**Comment by psaxde** [comment]
@cctv1237 You can get them when using info from the Resolver function signature: https://www.apollographql.com/docs/graphql-tools/resolvers#Resolver-function-signature

Inside info.fieldNodes[0].selectionSet.selections you'll find an array of fields used by that query, just give it a try and output what info has for you.

It's not described well and maybe there is a more convenient way...

**Comment by cctv1237** [comment]
Thanks mate @psaxde. Yea, it works, and I found we can use this lib to extract the fields, https://github.com/robrichard/graphql-fields . Then we don't need to write it by ourselves
