### ISSUE TITLE
fastify 2 deprecation beforeHandler

### ISSUE THREAD

**Issue by mhf-ir** [apollographql/apollo-server#2397]
```bash
(node:16764) Warning: The route option `beforeHandler` has been deprecated, use `preHandler` instead
```

using fastify 2.0.0 with apollo-server-fastify 2.4.8

Deprecation:
https://github.com/fastify/fastify/blob/master/fastify.js#L669

Source:
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-fastify/src/ApolloServer.ts#L120

**Comment by mhf-ir** [comment]
@abernix @rkorrelboom Any update for this ?

**Comment by abernix** [comment]
Closing in favor of #2391.
