### ISSUE TITLE
apollo-server-plugin-base is missing dependency apollo-server-core

### ISSUE THREAD

**Issue by elliottsj** [apollographql/apollo-server#2398]
Similar to #1963, the `apollo-server-plugin-base` package does not declare a dependency on `apollo-server-core` in its package.json, so an error occurs when using strict package managers such as yarn pnp or pnpm, e.g.

```
ERROR in /Users/spencerelliott/Dev/path/to/node_modules/.registry.npmjs.org/apollo-server-plugin-base/0.3.4/graphql@14.1.1/node_modules/apollo-server-plugin-base/dist/index.d.ts(1,95):
TS2307: Cannot find module 'apollo-server-core/dist/requestPipelineAPI'.
```

**Comment by abernix** [comment]
Hopefully fixed with 2.7.0 via #2990!  Thanks for reporting this originally.
