### ISSUE TITLE
[apollo-datasource-rest]- Request headers not coming through to data sources

### ISSUE THREAD

**Issue by ghost** [apollographql/apollo-server#2405]
**Intended outcome**:
I was trying to dynamically resolve my custom RESTDataSource url based on a header being sent through on the request. I implemented the resolveURL method in the class and tried to access the request headers on the request parameter that resolveURL expects. I am able to see that the header is set on the request, when I try add it to the context.

_src/data-sources/Accounts.API.js_

    class AccountsApi extends RESTDataSource {
        async resolveURL(request) {
            super.baseURL = request.headers.has('foo') ? 'mock_url' : 'production_url';
            super.resolveURL();
        }
        // api related methods and constructor removed for brevity
    }

_src/resolvers/Accounts.Resolvers.js_

    export default {
        Query: {
            getAccount: async (_source, { userId, productId }, {dataSources }) => {
                const account = await dataSources.AccountsApi.getAccount(userId, productId);
                return account ? account.core : {};
            },
        }
    }

_server.js_

    const server = new ApolloServer({
        typeDefs: schema,
        resolvers,
        dataSources: () => { return new AccountsApi() },
    });
    
**Actual outcome:** 
The headers property of the request had no headers in it.
![untitled](https://user-images.githubusercontent.com/46593261/53810746-447d8d80-3f60-11e9-8267-a6c721bf3dc8.png)

**Comment by tarun29061990** [comment]
Any success on this??

**Comment by martijnwalraven** [comment]
The `request` object received by `resolveURL` is not the request sent to the GraphQL server, but a newly constructed object that represents a request to the REST API. If you want to access information from the GraphQL request, you should put it on the `context`.
