### ISSUE TITLE
Partial mocking schema broken

### ISSUE THREAD

**Issue by mschipperheyn** [apollographql/apollo-server#2421]
I have a schema that I want to partially override in certain situations. E.g. I'm implementing a resolver, and I want to make sure the frontend team can already use the interface. The already implemented resolver endpoints should function normally.

This seems impossible or perhaps I'm doing something wrong.

Here's my setup:

```
const apolloMiddleware = (app, httpServer, path = '/graphql') => {
	const schema = makeExecutableSchema({
		typeDefs: typeDefs(),
		resolvers: resolvers(),
		schemaDirectives: directives,
	});
	const mockObj = mocks();
	if (mockObj) {
		addMockFunctionsToSchema({
			schema,
			mocks: mockObj,
			preserveResolvers: true,
		});
	}
	addResolveFunctionsToSchema(schema, typeResolvers);
	const apolloOptions = {
		schema,
		dataSources: restAPIs,
		subscriptions: {
			path,
		},
                [...]
	};
	const apollo = new ApolloServer(apolloOptions);
	apollo.applyMiddleware({ app, path });
	apollo.installSubscriptionHandlers(httpServer);
```

The `mocks` function returns an object with this shape:
```
         const Query = () => ({
		...loadMocks.queries,
	});
	return (
		mocks.length && {
			Date: () => new Date(),
			DateTime: () => new Date(),
			Int: () => parseInt(Math.random() * 100, 10),
			String: () => 'It works!',
			...loadMocks.types,
			Query,
		}
	);
```

Example
*type* 
```
	interface Group {
		id: ID!
		subType: GroupType
		label: String!
		members: [GroupMember!]!
	}
	type WallGroup implements Node & Group{
		id: ID!
		subType: GroupType!
		label: String!
		members: [GroupMember!]!
	}
```

*resolver*
```
const resolvers = {
	types: {
		Group: {
			__resolveType: group => {
				switch (group.subType) {
				case 'event':
					return 'WallEvent';
				default:
					return 'WallGroup';
				}
			},
		},
      }
      [...]
```

*mock*
```
types: {
	WallGroup: WallGroup = () => ({
	     id: faker.random.number(),
             label: faker.lorem.words(2),
             members: () => new MockList(100),
        }),
},
queries: {
     const queries = {
	    groups: () => new MockList(100),
    };
}
```

*preserveResolvers: false*
- Base types return mock values always, for all resolvers, mocked or unmocked. E.g. All strings are "Hello World!"
- non mocked types combined with mock query resolvers seem to be ignored: `__resolveType` not called or overwritten *even if the mock doesn't provide an alternative*
- type resolvers `__resolveType` functions are not called even when not overwritten for mock data

*preserveResolvers: true*
- Base types return mock values always, for all resolvers, mocked or unmocked. E.g. All strings are "Hello World!"
- It's impossible to overwrite existing resolvers with mock resolvers by simply supplying a mock resolver

I'm not really sure what the thinking is behind the `mock` functionality, but I'm not succeeding in implementing any of the use cases I want to use it for. 

It seems to me that trying to partially mocking front end data can only be achieved by not implementing mocks and merging the mock data with the normal resolver structure. Haven't tried that yet, but that's prob the way to go?

**Comment by JQrdan** [comment]
I've run into a similar issue, I used to be able to do: 

```
const server = new ApolloServer({
  typeDefs,
  mocks: graphqlMocks,
  resolvers: queryResolver,
});
```

but now the mocks part of the server completely overwrites the resolvers part and this wasn't an issue previously

**Comment by mschipperheyn** [comment]
@JQrdan this has no effect on my config. Perhaps because I use `addMockFunctionsToSchema`. I will have another look at the apollo source code and see if I can identify the issue

**Comment by JakeDawkins** [comment]
@mschipperheyn Yeah, it looks like you've stumbled upon a rather strange behavior with `addMockFunctionsToSchema`. Since we just re-export that functionality from graphql-tools, I'm not sure we can do anything about that here. I'm going to close this issue here, but if you want to look into what's going on with the implementation there, that may be helpful if you're still having issues with this.

I will note that we're not as active in that project right now, so a workaround may be more hopeful than a true _fix_ to the issue.
