### ISSUE TITLE
apollo server is not successfully deployed to lambda

### ISSUE THREAD

**Issue by gohulk** [apollographql/apollo-server#2422]
Hello , 

I am not able to deploy the apollo server to lambda. I am following the instructions from this link:
https://www.apollographql.com/docs/apollo-server/deployment/lambda.html

I am noticing the following error
START RequestId: 29754a42-b1af-433d-870f-6e8913194119 Version: $LATEST
**Unable to import module 'graphql': Error**
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
END RequestId: 29754a42-b1af-433d-870f-6e8913194119
REPORT RequestId: 29754a42-b1af-433d-870f-6e8913194119	Duration: 7.20 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 65 MB

And also , my graphql.js file looks like this:

const { ApolloServer , gql} = require('apollo-server-lambda');
const typeDefs = require('./schema');
const resolvers = require('./resolvers');
const VideoAPI = require('./datasources/video');

const server = new ApolloServer({ 
    typeDefs, 
    resolvers,
    dataSources: () => ({
      videoAPI: new VideoAPI()
    }),
    context: ({ event, context }) => ({
      headers: event.headers,
      functionName: context.functionName,
      event,
      context,
    })
});

exports.graphqlHandler = server.createHandler();

Can you please kindly help me on this? Am i missing any configuration? 

And also , i did chmod 777 on node modules.

**Comment by kyledetella** [comment]
By chance, did you add `GraphQL` as a dependency to your project?

**Comment by gohulk** [comment]
Yes, please find it below:

  "dependencies": {
    "apollo-datasource-rest": "^0.3.2",
    "apollo-server": "^2.4.8",
    "apollo-server-lambda": "^2.4.8",
    "graphql": "^14.1.1"
  }

**Comment by kyledetella** [comment]
How are you deploying this to AWS?

**Comment by gohulk** [comment]
I am using serverless. Please find my serverless.yml file below:
# serverless.yml

service: apollo-lambda
provider:
  name: aws
  runtime: nodejs6.10
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true

**Comment by kyledetella** [comment]
The issue here was that the `handler` was misconfigured in the `serverless.yml`. It should have been: `handler: src/graphql.graphqlHandler`.

See [spectrum thread](https://spectrum.chat/apollo/apollo-server/need-help-with-deploying-apollo-server-to-lambda~0e719885-a39e-4ed6-b6c3-9a7e827a50cf).

**Comment by gohulk** [comment]
Thanks Kyle for your help. Really appreciate it.
