### ISSUE TITLE
upload : RangeError Maximum stack...

### ISSUE THREAD

**Issue by slicejunk** [apollographql/apollo-server#2425]
as explained here https://github.com/graphql/graphql-js/issues/1783

any error in the payload of a mutation with a file to upload will cause a RangeError

graphql: 14.1.1
apollo-server: 2.4.8
apollo-upload-client: 10.0.0

a solution could be to provide a custom inspect function to the file object in a property named: ```Symbol.for('nodejs.util.inspect.custom')```

**Comment by trevor-scheer** [comment]
Thanks for reporting, @slicejunk. Is this still an issue or is it resolved by the fix in `graphql-js`? If not, can you please provide a runnable reproduction? Thanks!
