### ISSUE TITLE
[apollo-datasource-rest] Error thrown when parsing 204 response

### ISSUE THREAD

**Issue by EspadaV8** [apollographql/apollo-server#2434]
We have a number of endpoints that return the `204` HTTP status code when handling `DELETE` requests. These are currently throwing an error because of the attempt to parse the body (https://github.com/apollographql/apollo-server/blob/c908fac9176fb6ea7b24be83a03121a03040a2d4/packages/apollo-datasource-rest/src/RESTDataSource.ts#L94), however, for these responses there isn't a body. To handle this I think that `didReceiveResponse` should check the status code before attempting to parse the body.

**Comment by EspadaV8** [comment]
(more than happy to open a small PR to handle this if you're okay with it the suggestion, wanted to get feedback beforehand)

**Comment by abernix** [comment]
Fixed via https://github.com/apollographql/apollo-server/pull/2446!  Thanks for reporting this originally.
