### ISSUE TITLE
Apollo Server Express with stitched schema swallows errors

### ISSUE THREAD

**Issue by GarethSharpe** [apollographql/apollo-server#2448]
## Intended outcome

When using a GraphQL gateway to schema stitch GraphQL µservices, the error messages thrown by the µservices should bubble up to the gateway and should be presented unaltered.

## Actual outcome

A generic `INTERNAL_SERVER_ERROR` error code is displayed to the gateway client along with a message containing an `[object Object] which cannot be extracted. The µservice throws the correct error.

µservice error:

```
{ [GraphQLError: Session expired or invalid]
  message: 'Session expired or invalid',
  locations: [ { line: x, column: x } ],
  path: [ 'xxx' ],
  extensions: 
   { code: 'INTERNAL_SERVER_ERROR',
     exception: 
      { name: 'INVALID_SESSION_ID',
        errorCode: 'INVALID_SESSION_ID',
        stacktrace: [Array] } } }
```

gateway error:

```
{ [GraphQLError: [object Object]]
  message: '[object Object]',
  locations: [ { line: x, column: x } ],
  path: [ 'xxx' ],
  extensions: 
   { code: 'INTERNAL_SERVER_ERROR',
     exception: { errors: [Array], stacktrace: [Array] } } }
```

## How to reproduce the issue

Stitch two schemas together. Force one to throw a specific error (`AutenticationError`, etc). Observe response from the Apollo Server that stitched the schemas. 

## Potential fix

Move to `graphql-tools@next (5.0.0-rc.0)`. Here is the [ongoing discussion](https://github.com/apollographql/graphql-tools/pull/1074).

**Comment by martijnwalraven** [comment]
Closing this because it will have to be resolved in `graphql-tools`, but note that schema stitching is being deprecated in favor of federation.
