### ISSUE TITLE
micro: CORS' OPTIONS not implemented.

### ISSUE THREAD

**Issue by guidolodetti** [apollographql/apollo-server#2473]
In the [apollo-server-micro](https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-micro) package, the [CORS example](https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-micro#cors-example) is incorrect because Apollo Server will respond with status code `405` for `OPTIONS` requests. To avoid this, a simple fix is to use the following code instead:

```
module.exports = cors((req, res) => {
  if (req.method === 'OPTIONS') {
    res.end()
    return
  }
  return server.createHandler()(req, res)
})
```

**Comment by steida** [comment]
I believe this is a proper solution: https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-micro#cors-example

**Comment by JakeDawkins** [comment]
I think this would be better fixed in the implementation rather than a docs change. This was fixed in the lambda implementation here: 

https://github.com/apollographql/apollo-server/blob/5b46e44451094c4daae3022f40347e234225a7de/packages/apollo-server-lambda/src/ApolloServer.ts#L151-L161

**Comment by jackrobertscott** [comment]
Just a heads up for anyone else who stumbles across this problem. Here is the code that worked for my server.

```ts
import micro from 'micro';
import cors from 'micro-cors';
import { ApolloServer } from 'apollo-server-micro';

const server = new ApolloServer({/* config */});

const optionsHandler = (req: IncomingMessage, res: ServerResponse) => {
  if (req.method === 'OPTIONS') {
    res.end();
    return;
  }
  return server.createHandler()(req, res);
};
const microserver = micro(cors()(optionsHandler));
if (!config.production) {
  microserver.listen({ port: config.port }, () => {
    const plaground = server.graphqlPath;
    console.log(`👉  Server: http://localhost:${config.port}${plaground}`);
    console.log(`👉  Environment: ${config.environment}`);
    console.log(`👉  Production: ${config.production}`);
  });
}
export default microserver; // return micro server so lambda can use i.e. Zeit Now
```

Hope it helps!

**Comment by donedgardo** [comment]
maybe implement here?
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-micro/src/ApolloServer.ts#L155 @abernix ?

**Comment by abernix** [comment]
PR welcome!
