### ISSUE TITLE
apollo-server-lambda parse event.body error

### ISSUE THREAD

**Issue by bluedusk** [apollographql/apollo-server#2475]
Hi Guys,

I'm getting this parse error when I use apollo-server-lambda with file upload. The content-type is application/multi-part. So my event.body is not a json string. it looks like:

```
body: '------WebKitFormBoundaryZAUndAKIJ6usT0rV\r\nContent-Disposition: form-data; name="operations"\r\n\r\n{"operationName":"uploadFiles","variables":{"files":[null]},"query":"mutation uploadFiles($files: [Upload!]!) {\\n  uploadFiles(files: $files)\\n}\\n"}\r\n------WebKitFormBoundaryZAUndAKIJ6usT0rV\r\nContent-Disposition: form-data; name="map"\r\n\r\n{"1":["variables.files.0"]}\r\n------WebKitFormBoundaryZAUndAKIJ6usT0rV\r\nContent-Disposition: form-data; name="1"; filename="test copy 3.csv"\r\nContent-Type: text/csv\r\n\r\nthis is a test file\r\n------WebKitFormBoundaryZAUndAKIJ6usT0rV--\r\n',
```

So I got parse error from this JSON.parse(event.body)

```
    runHttpQuery([event, context], {
      method: event.httpMethod,
      options: options,
      query:
        event.httpMethod === 'POST' && event.body
          ? JSON.parse(event.body)
          : event.queryStringParameters,
```

Any idea how to solve this ?
Thanks.

**Comment by Jefreesujit** [comment]
Facing the same issue, @bluedusk did you find any workaround?

**Comment by bluedusk** [comment]
@Jefreesujit  please have a look: 
https://github.com/bluedusk/apollo-server-lambda-fileupload

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Lambda integration. Check out the [`@as-integrations/aws-lambda`](https://www.npmjs.com/package/@as-integrations/aws-lambda) package; this new package is maintained by Lambda users and implements support for the API Gateway v1 and v2 protocols. If you need to work with different AWS projects, you may be able to add that support to that package, or take another approach such as combining the [`@vendia/serverless-express`](https://www.npmjs.com/package/@vendia/serverless-express) package with Apollo Server 4's built-in `expressMiddleware` (this is the same approach that `apollo-server-lambda` takes in AS3). Sorry for the delay!
