### ISSUE TITLE
Support thenable objects as resolver results

### ISSUE THREAD

**Issue by prk3** [apollographql/apollo-server#2501]
In our project, we've been returning objection.js QueryBuilders from resolvers:
```javascript
resolvers: {
   abc: (obj, { id }, { knex }) => SomeModel.query(knex).findById(id),
}
```
After migrationg from apollo-server 1.4 to 2.0 we found that these queries were always executed twice. It turns out that calling .then multiple times on QueryBuilder object executes query multiple times - that's because [QueryBuilder is thenable](https://vincit.github.io/objection.js/#querybuilder), not a regular promise. In order to make Builders work as before, apollo-server would have to call then on last returned promise.

```javascript
// wrong
const resolved = Some.query(knex);
resolved.then(()=> console.log('first execution'));
resolved.then(() => console.log('second execution'));

// ok
const resolved = Some.query(knex)
    .then(() => console.log('first execution')
    .then(() => console.log('no more executions!');

// or
let resolved = Some.query(knex);
resolved = resolved.then(() => console.log('first execution');
resolved = resolved.then(() => console.log('no more executions!');
```

All versions work with regular promises, but only only second and third can handle thenable objects, like objection's QueryBuilder.

References to places where then is called, but it's result isn't stored anywhere:
https://github.com/apollographql/apollo-server/blob/master/packages/graphql-extensions/src/index.ts#L273
https://github.com/apollographql/apollo-server/blob/master/packages/graphql-extensions/src/index.ts#L297

**Comment by martijnwalraven** [comment]
We only support returning spec-compliant promises from resolvers, but you should be able to coerce your thenable using `Promise.resolve(thenable)`.
