### ISSUE TITLE
RedisCache: Uncaught Ready Check Exception

### ISSUE THREAD

**Issue by hollsteinm** [apollographql/apollo-server#2530]
When given default configuration values for RedisCache against a Redis server requiring auth, the NOAUTH error event results in an unhandled exception after an INFO check (done internally by the library). 

There is no event subscriber in the RedisCache class to enable a graceful handler for this error check.

The current workaround is to set the redis configuration for `no_ready_check` to true. Then wrap all cache methods in try catch blocks to handle NOAUTH errors.

**Comment by abernix** [comment]
We've recently updated the Redis package in https://github.com/apollographql/apollo-server/pull/1770, which replaced the underlying Redis library with a more versatile option.  If this is still a problem with the new package, please open a new issue with a runnable reproduction — either on CodeSandbox or a GitHub repository that can be cloned and `npm start`ed.
