### ISSUE TITLE
KeyValueCache ttl units

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-server#2531]
From [this line](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-caching/src/InMemoryLRUCache.ts#L38) and the fact that `lru-cache`'s `maxAge` is in ms, I take it that `ttl` is meant to be **seconds**.

1. **Should it be changed to ms?** I'm used to time being in ms, and I imagine the average JS dev also assumes a time param will be in ms. (And`SQLDataSource` [documents it incorrectly as ms](https://github.com/cvburgess/SQLDataSource#usage).) OTOH, maybe no one caches things for less than a second, in which case using seconds saves them the trouble of multiplying by 1000.
2. **Document it.** Normally I'd suggest renaming with units, but `ttlInseconds` is hard to read with the lowercase L and uppercase I. So maybe just noting here:

https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-caching#implementing-your-own-cache

**Comment by glasser** [comment]
I'm also generally a fan of names that use units. This convention was chosen a while back for consistency with HTTP caching headers that use seconds without units, and I don't think we're likely to change it at this point. The JSDoc on the options type (https://github.com/apollographql/apollo-utils/blob/main/packages/keyValueCache/src/KeyValueCache.ts) does specify the units, as does our [docs on implementing your own cache backend](https://www.apollographql.com/docs/apollo-server/performance/cache-backends/#implementing-your-own-cache-backend).
