### ISSUE TITLE
RESTDataSource not setting url on 404 errors that are thrown

### ISSUE THREAD

**Issue by timcosta** [apollographql/apollo-server#2533]
Hey all. Currently tracing some errors in our app and I noticed that for 401/403/5XX errors there is a `errors[].extensions.response.url` property that is set to the URL that is erroring. For 404 errors, this `url` property is unset. Here's an example response we get back:

```
{
    "errors": [
        {
            "message": "404: Not Found",
            "locations": [
                {
                    "line": 6,
                    "column": 7
                }
            ],
            "path": [
                "queryName",
                0,
                "parent",
                "child"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "response": {
                    "status": 404,
                    "statusText": "Not Found",
                    "body": {
                        "errors": [
                            {
                                "status": 404,
                                "detail": "Record Not Found"
                            }
                        ]
                    }
                },
                "exception": {
                    "stacktrace": [
                        <snip>
                    ]
                }
            }
        }
    ],
    "data": {
        "queryName": [
            null
        ]
    }
}
```

unfortunately this is leading to some issues determining exactly _where_ the error is being sourced from. Is it possible for the URL property to be added on 404s as well? Looking at https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts#L117 it looks like it should be, but it just isnt.

**Comment by trevor-scheer** [comment]
Hey @timcosta, thanks for submitting an issue! Can you please provide a runnable reproduction? Thanks!
