### ISSUE TITLE
TypeError: Cannot read property 'use' of undefined

### ISSUE THREAD

**Issue by dualitysol** [apollographql/apollo-server#2553]
My apollo-server-express all the time throws 

> /node_modules/apollo-server-express/dist/ApolloServer.js:66
        app.use(path, (_req, _res, next) => {
            ^

TypeError: Cannot read property 'use' of undefined

This was solved once by npm rebuild. But now nothing helps me.
My specs:
Nodejs v10.15.3
apollo-server ^2.4.8
apollo-server-express ^2.4.8
graphql ^0.13.2
MacOS 10.14.4

**Comment by dualitysol** [comment]
Sorry for usless thread, issue was related to runned server in other terminal...

**Comment by andrewtian** [comment]
For those sleep deprived:

Do this:
`graphqlServer.applyMiddleware({ app });`

Not this:
`graphqlServer.applyMiddleware(app);`
