### ISSUE TITLE
POST body missing. Did you forget use body-parser middleware?

### ISSUE THREAD

**Issue by BengBu-YueZhang** [apollographql/apollo-server#2598]
I used graphql and koa2. 

```js

const Koa = require('koa')
const json = require('koa-json')
const bodyparser = require('koa-bodyparser')
const config = require('./config')
const port = config.URL.port
const cors = require('@koa/cors')
const UserRoute = require('./routes/user.router')
const { ApolloServer, gql } = require('apollo-server-koa')
const app = new Koa()

const typeDefs = gql`
  type Book {
    title: String
    author: String
  }
  type Query {
    books: [Book]
  }
`

const resolvers = {
  Query: {
    books: () => books,
  },
}

app.use(cors({
  origin: '*',
  credentials: true,
  methods: ['PUT', 'POST', 'GET', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Content-Length', 'Authorization', 'Accept', 'X-Requested-With', 'x-access-token']
}))
app.use(UserRoute.routes(), UserRoute.allowedMethods())
app.use(bodyparser())
app.use(json())

const server = new ApolloServer({ typeDefs, resolvers })

server.applyMiddleware({
  app,
  path: config.URL.graphql,
})

module.exports = app.listen(port)
```

I just want to use graphql on some of the interfaces.

![image](https://i.loli.net/2019/04/21/5cbc896338596.png)

![image](https://i.loli.net/2019/04/21/5cbc8963a27cf.png)

 I use postman for debugging. Any good suggestions?

**Comment by yvanwangl** [comment]
@BengBu-YueZhang All you need is a custom middleware:
```
...
const Koa = require('koa')
const raw = require('raw-body');
const inflate = require('inflation');
const app = new Koa();
...
app.use(async (ctx, next) => {
  if (ctx.req.headers['content-type'] === 'application/graphql') {
    const str = await raw(inflate(ctx.req), { encoding: 'utf8' });
    ctx.request.body = { query: str };
  }
  await next();
});

```
By this middleware, the content-type `application/graphql` will work in expectation.

**Comment by yvanwangl** [comment]
Or you can use the package [`koa-bodyparser-graphql`](https://github.com/yvanwangl/koa-bodyparser-graphql) directly.

**Comment by BengBu-YueZhang** [comment]
@yvanwangl  非常感谢您的帮助，我已经解决了这个问题。之前在dva的开源社区里就见过您的作品，没想到能在这里遇见你。再次感觉，已经对您的项目star和fork了

----

Koa-bodyparser-graphql solves my problem, very cool

**Comment by kemicofa** [comment]
Can we get the [docs](https://graphql.org/learn/serving-over-http/) updated that this is not handled by default?

Quite misleading and I would have saved time instead of trying to get it to work.

> If the "application/graphql" Content-Type header is present, treat the HTTP POST body contents as the GraphQL query string.

**Comment by akashelhance** [comment]
For express what should i use

**Comment by abernix** [comment]
@akashelhance You don't need to do anything if you use `apollo-server-express` (Unless you disable body parsing by passing options to `applyMiddleware`).  By default, it will use [`body-parser`](https://www.npmjs.com/package/body-parser)

**Comment by akashelhance** [comment]
@abernix 
![image](https://user-images.githubusercontent.com/16331227/119807178-865bcb00-bf00-11eb-9e32-e67622d41742.png)

is what I am using. but still I am getting the error

**Comment by abernix** [comment]
@akashelhance Looks like you're not using `apollo-server-express`, but rather `apollo-server`.  Please [take  a look at this documentation](https://www.apollographql.com/docs/apollo-server/integrations/middleware/#applying-middleware).

**Comment by akashelhance** [comment]
@abernix Really thanks for your help but now I getting this error:

![image](https://user-images.githubusercontent.com/16331227/119813422-dfc6f880-bf06-11eb-9655-37e7f0c69e44.png)

**Comment by abernix** [comment]
I'm glad you got it fixed!

You have `uploads: false` in your configuration that you shared above — which removes the `Upload` scalar from your schema, but you're trying to do uploads, so it's not working.

**Comment by akashelhance** [comment]
@abernix no, now I am using this

![image](https://user-images.githubusercontent.com/16331227/119823412-6b925200-bf12-11eb-902a-e2fd82f46376.png)

**Comment by abernix** [comment]
Ok.  This isn't the right issue to continue to debug this in as it's no longer likely related to body-parsing.

Please create a runnable reproduction of the struggle (something anyone can can open and run themselves) and [open a "Help" issue on the Apollo Community board](https://community.apollographql.com/new-topic?category=Help&tags=server).  [This is a good starting template for creating a reproduction](https://codesandbox.io/s/github/abernix/apollo-server-typescript-express?file=/src/server.ts), even if it's TypeScript.  For example, it's very difficult to determine what's happening here without knowing the versions of packages, etc. (Btw, make sure you're using Apollo Server 2.x and not 3.x.  (If you're using 3.x, that's fine, but you should note that uploads and the `Upload` scalar are no longer added by default in Apollo Server 3.x.)

I hope you understand! Thanks!

**Comment by akashelhance** [comment]
ok, thanks for the help

**Comment by kemaldemirgil** [comment]
```js
const express = require("express");
const { ApolloServer } = require("apollo-server-express");
const path = require("path");
const cors = require("cors");

const { typeDefs, resolvers } = require("./schemas");
const { authMiddleware } = require("./utils/auth");
const db = require("./config/connection");
const { graphqlUploadExpress } = require("graphql-upload");

const PORT = process.env.PORT || 3001;
const app = express();
const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: authMiddleware,
  uploads: false,
});

server.applyMiddleware({ app });

app.use(express.urlencoded({ extended: false }));
// app.use(express.json());

app.use(cors("#"));
const dir = path.join(process.cwd(), "images");
app.use("/images", express.static(dir));
app.use(graphqlUploadExpress({ maxFileSize: 1000000000, maxFiles: 10 }));

// Serve up static assets
// ..
// app.use('/images', express.static(path.join(__dirname, '../client/images')));

if (process.env.NODE_ENV === "production") {
  app.use(express.static(path.join(__dirname, "../client/build")));
}

app.get("*", (req, res) => {
  res.sendFile(path.join(__dirname, "../client/build/index.html"));
});

db.once("open", () => {
  app.listen(PORT, () => {
    console.log(`API server running on port ${PORT}!`);
    console.log(`Use GraphQL at http://localhost:${PORT}${server.graphqlPath}`);
  });
});

```

**Comment by kemaldemirgil** [comment]
`POST body missing. Did you forget use body-parser middleware?` I've tried everything above and some other stuff as well, none of them worked...

**Comment by abernix** [comment]
@kemaldemirgil A clone-able reproduction that works or something like a Code Sandbox link would be really great starting points to make helping you out easier.  Also, [the community forums](https://community.apollographql.com/) would be a better place to ask for help since this issue is now closed.  Thanks!

**Comment by glasser** [comment]
@kemaldemirgil I'd suggest upgrading to Apollo Server 3 (I can tell you haven't because the error you quote was reworded in AS3) which [fixes several related issues](https://www.apollographql.com/docs/apollo-server/migration/#bad-request-errors-more-consistently-return-4xx).
