### ISSUE TITLE
apollo-server-lambda: JSON.parse errors when lambda event.isBase64Encoded=true

### ISSUE THREAD

**Issue by gobengo** [apollographql/apollo-server#2599]
Today I just started using apollo-server-lambda. It works pretty well, and my GET request resulted in the GraphiQL playground showing. However, the POST method requests were all failing due to an error in the backend. I could see in Cloudwatch that there was an error when apollo-server-lambda/src/lambdaApollo does `JSON.parse(event.body)`.

For one reason or another, my event had `event.isBase64Encoded === true`, and the `event.body` was a long base64 encoded string (that decoded to JSON), not a JSON string.

I was able to work around this error by rewriting all base64-encoed events upstream using [this 'middleware'](https://github.com/fanout/apollo-demo/pull/2/files#diff-940ba35c9f37183c28c0fe37293b0e01R33) before passing the event into the apollo-lambda-server ApolloServer handler.

PR: https://github.com/apollographql/apollo-server/pull/2600

**Comment by gobengo** [comment]
PR: https://github.com/apollographql/apollo-server/pull/2600

**Comment by abernix** [comment]
Interesting!

> For one reason or another, my event had `event.isBase64Encoded === true`, and the `event`.body was a long base64 encoded string (that decoded to JSON), not a JSON string.

Do you have any idea how or why this is the case?  Not to say that we can't accept the PR, but the need seems be a bit unsubstantiated / not fully understood.  I'd like just like to understand the reasoning so we can make sure we account for it property going forward.

**Comment by gobengo** [comment]
It’s the case because that’s the event AWS handed to the lambda function. The http request itself originated from the GraphiQL playground that Apollo server renders.

As for a how or why, I think AWS just reserves the right to decide arbitrarily how it translates incoming requests to lambda events.

**Comment by jlarmstrongiv** [comment]
Here’s one case I ran into:  lambda@edge provides the [Request Body](https://aws.amazon.com/about-aws/whats-new/2018/08/lambda-edge-now-provides-you-access-to-the-request-body-for-http/) as a base64 encoded [string](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-examples.html#lambda-examples-access-request-body-examples).

**Comment by hsimah** [comment]
This issue stung me this weekend. I am building my first Apollo server app and want to stick it on a lambda. I followed [the guide](https://www.apollographql.com/docs/apollo-server/deployment/lambda/) to the letter. When it deploys the `IntrospectionQuery` fires from the playground and the payload comes through as base64 encoded. I haven't looked into how or why, but applying this fix works, at least with the sample schema in the guide.

**Comment by 2color** [comment]
I experienced the same problem and can confirm the associated PR https://github.com/apollographql/apollo-server/pull/2600 resolves the problem.

**Comment by abernix** [comment]
Should hopefully be fixed in `apollo-server-lambda@2.16.0` by #4311, which should be effectively the same as #2600.
