### ISSUE TITLE
Masking and logging errors

### ISSUE THREAD

**Issue by venkateshKadali** [apollographql/apollo-server#2603]
We are using apollo-server-express. Masking the errors in this example: https://www.apollographql.com/docs/apollo-server/features/errors#masking-and-logging-errors
is not working properly. It is said that we can delete the error.extensions.exception (in the comments), but it has read-only access, so, we cannot delete them. Is there any best approach to mask the errors?

**Comment by JacksonKearl** [comment]
You can create a new object:
```
formatError(err) {
  return {message: err.message }
}
```

Closing for now, let me know if this doesn't solve your problem!
