### ISSUE TITLE
apollo server mutation resolver not called

### ISSUE THREAD

**Issue by BengBu-YueZhang** [apollographql/apollo-server#2610]
This is my schema

```js

const typeDefs = gql`
  type Query {
    users(pagestart: Int = 1, pagesize: Int = 10): UsersResponse
    user(id: ID!): User!
    me: User
  }

  type Mutation {
    addUser(user: UserRequest): UserResponse
    updateUser(user: UserRequest): UserResponse
    login(user: UserRequest): UserResponse
    logout: UserResponse
  }

```

This is my resolvers

```js

module.exports = {
  Query: {
    // ...
  },
  Mutation: {
    addUser (_, { user }, { dataSources }) {
      return dataSources.UserDatasource.addUser(user)
    }
  }
}

```

When I sent a mutation, the resolvers mutation was not invoked. I added consoon.log in resolvers Mutation, which did not print on the console. Resolvers' Query is all right. Any good Suggestions?

![image](https://i.loli.net/2019/04/26/5cc1de9978b00.png)

![image](https://i.loli.net/2019/04/26/5cc1deb6cc84f.png)

**Comment by yurist38** [comment]
@BengBu-YueZhang Do you remember what was the issue?

**Comment by yurist38** [comment]
Okay, I think I know the answer now. Maybe it will be useful to others who ended up here.
First of all, my problem was related to client-side resolver. I expected the resolver function to be called when I do a mutation on the frontend side, but according to [Apollo Docs](https://www.apollographql.com/docs/react/essentials/local-state/) it seems to be working only with local queries/mutations (using directive `@client`). In my case, I do a "remote" mutation.
By the way, I'm still curious why we can't use local resolvers in this case... What is the best way to transform incoming data from the apollo server then? 🤔

**Comment by dakshshah96** [comment]
@BengBu-YueZhang I'm facing the same issue with my Apollo GraphQL server. `console.log` statements in the mutation resolver are not executed and `null` is always returned. The mutation, however, shows up correctly in the GraphQL Playground schema but never gets executed.

**Comment by pdoria** [comment]
Just got hit with the same thing: mutation resolver not being called?!

`extend type Mutation {
    createTool(
        company: ID!
        internal_nbr: String
        description: String!
        serial_nbr: String
        model: String
        supplier: ID!
        power: String
        entry_date: Date!
        status: ToolStatus!
        entry_photo: String
    ): Tool! @auth
    updateTool(id: ID!, update: ToolInput): Tool @auth
    deleteTool(id: ID!): Tool @auth
}`

resolver:
`
....other resolvers...

updateTool: async (root, args, { req }, info) => {
            console.log('\x1b[33mHERE!')
            const { id, update } = args;
            if (!mongoose.Types.ObjectId(id)) {
                throw new UserInputError(`${id} is not a valid ObjectId`);
            }
            if (!mongoose.Types.ObjectId(update.company)) {
                throw new UserInputError(`Company id ${update.company} is not a valid ObjectId`);
            }
            if (!mongoose.Types.ObjectId(update.supplier)) {
                throw new UserInputError(`Supplier id ${update.supplier} is not a valid ObjectId`);
            }
            console.log('id: ', id)
            // Same rules as creation
            await Joi.validate(update, createTool, { abortEarly: false });
            return await Tool.findOneAndUpdate({ _id: id }, update, { useFindAndModify: false, new: true });
        },`

was working. not it stopped being called. at a loss here?!?

**Comment by pdoria** [comment]
> @BengBu-YueZhang I'm facing the same issue with my Apollo GraphQL server. `console.log` statements in the mutation resolver are not executed and `null` is always returned. The mutation, however, shows up correctly in the GraphQL Playground schema but never gets executed.
> 
> Would love to know how you were able to solve this!

Check if you don't have another resolver with the same name ;)

**Comment by dakshshah96** [comment]
> > @BengBu-YueZhang I'm facing the same issue with my Apollo GraphQL server. `console.log` statements in the mutation resolver are not executed and `null` is always returned. The mutation, however, shows up correctly in the GraphQL Playground schema but never gets executed.
> > Would love to know how you were able to solve this!
> 
> Check if you don't have another resolver with the same name ;)

Nope, no other resolver has the same name.

**Comment by ggmon** [comment]
did you guys, figure out the issue, I have hit the same wall

**Comment by jenaro94** [comment]
I have the same issue, my query responds null even though the schema shows up correctly on the playground, all the console.log statements are not running either.

**Comment by BenjaminDavidMoore** [comment]
Probably a little late for the previous posters, but to help any future soles coming here in a time of desperation, I had the same issue (resolver always returning null and no logs being executed in the resolver) when using Apollo Server with Typescript. The issue for me was that I was importing my resolvers with a glob like so:

```typescript
const resolversArray = loadFilesSync(path.join(__dirname, './**/*.resolvers.ts'));
```

Which when transpiled by Typescript, doesn't change the glob pattern... note the `.ts` which means when you look at your transpiled version, it's still looking for resolver files with the `.ts` extension. I recommend you either change your glob to 

```typescript
const resolversArray = loadFilesSync(path.join(__dirname, './**/*.resolvers.{ts,js}'));
```

Or manually / explicitly combine your resolvers yourself. Either way, I hope this helps, and if not, try looking to make sure you've properly brought in all of your resolvers!
