### ISSUE TITLE
apollo-datasource: missing property context

### ISSUE THREAD

**Issue by melkir** [apollographql/apollo-server#2617]
According to this javascript tutorial
https://github.com/apollographql/fullstack-tutorial/blob/master/final/server/src/datasources/user.js

The following file is missing the property `context`
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource/src/index.ts

Here's my workaround, but it would be nice if someone fixed it :)
```
// types/apollo-datasource/index.d.ts

import { DataSource } from 'apollo-datasource'

declare module 'apollo-datasource' {
  interface DataSource<TContext = any> {
    context: TContext
  }
}
```

**Comment by martijnwalraven** [comment]
Thanks very much for reporting this! We think this is a great idea, and would definitely review a PR. If you (or anyone else) is interested in working on this, that would be great - thanks!
