### ISSUE TITLE
How to include headers in RESTDataSource request?

### ISSUE THREAD

**Issue by szhang-ezypay** [apollographql/apollo-server#2631]
I'm trying to use apollo RESTDataSource to wrap my rest api. I need to pass some headers to the api call.

I'm following the example from the docs: https://www.apollographql.com/docs/apollo-server/features/data-sources#intercepting-fetches

This is my code:
```
  willSendRequest(request: RequestOptions) {
    console.log(`request 1: ${JSON.stringify(request)}`);
    request.headers.set('Authorization', this.context.authorization);
    console.log(`request 2: ${JSON.stringify(request)}`);
  }
```

I'm expecting the headers to contain 'Authorization'. But it's always empty.

The log from the above code:

```
request 1: {"method":"POST","path":"partnerinvoices","body":{"command": "input","params":{},"headers":{}}
request 2: {"method":"POST","path":"partnerinvoices","body":{"command":"input","params":{},"headers":{}}

```

I can override body and params in `willSendRequest` method without any problem.

**Comment by k3v3n** [comment]
Hi, did you forgot to pass the request to the context like the following: 

`const server = new ApolloServer({
  schema,
  dataSources: () => ({
    api,
  }),
  context: async ({ req, res }) => ({
    request: req,
    response: res,
    me: await authorize(req, api),
  }),

  playground: !isProduction,
  tracing: !isProduction,
});
`

**Comment by shandrolis** [comment]
That is exactly how I'm setting the header myself, so I'm not sure what's wrong. Are you certain the value in this.context.authorization is not undefined?

I'm using it like as follows, for which I'm certain it works.
`willSendRequest (request) {
    request.headers.set('csrftoken', this.context.token)
  }
`

**Comment by k3v3n** [comment]
It's really hard to tell what the issue here without your complete setup. Do you have any repo that we can take a look at ? I have the save logic for willSendRequest and it working just fine.

**Comment by abernix** [comment]
The third option to, e.g. `post`, `put`, `delete`, etc. allows passing of [`fetch` options](https://github.com/bitinn/node-fetch).  For example:

```js
class MoviesAPI extends RESTDataSource {
  constructor() {
    super();
    this.baseURL = 'https://movies-api.example.com/';
  }

  async getMovie(id) {
    return this.get(`movies/${id}`, undefined, {
      headers: {
        'Authorization': 'Bearer 123abc',
      },
    });
  }
}
```

**Comment by chloesun** [comment]
> The third option to, e.g. `post`, `put`, `delete`, etc. allows passing of [`fetch` options](https://github.com/bitinn/node-fetch). For example:
> 
> ```js
> class MoviesAPI extends RESTDataSource {
>   constructor() {
>     super();
>     this.baseURL = 'https://movies-api.example.com/';
>   }
> 
>   async getMovie(id) {
>     return this.get(`movies/${id}`, undefined, {
>       headers: {
>         'Authorization': 'Bearer 123abc',
>       },
>     });
>   }
> }
> ```
@abernix  Thanks for your answer, my code worked after adding `undefined` to the `GET` request, but I'm confused what is `undefined` in the syntax? Any documentation for reference? Thank you!

**Comment by shandrolis** [comment]
> @abernix Thanks for your answer, my code worked after adding `undefined` to the `GET` request, but I'm confused that what is `undefined` in the syntax? Any documentation for reference? Thank you!

Second function param is to add (url)query parameters, so you don't have to manually add it to the path yourself.
Its usage and source can be seen [here](https://github.com/apollographql/apollo-server/tree/master/packages/apollo-datasource-rest ).
I'm not sure if there are extensive official docs on it, but you can quite easily look in the [source](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts).

**Comment by dipakparmar** [comment]
In case anyone looking for passing headers from graphql request to datasources:

You can setup like this:

```js
const createServer = (graphQLOptions) =>
  new ApolloServer({
    typeDefs,
    resolvers,
    introspection: true,
    dataSources,
    context: ({ request }) => {
      return {
        xauthsid: request.headers.get('X-AUTH-SID'),
        xauthsecret: request.headers.get('X-AUTH-SECRET'),
        useragent: request.headers.get('User-Agent') || null,
      };
    },
  })
```

all these will be available as `this.context` in your datasource class( eg. `this.context.xauthsid`)

**Comment by glasser** [comment]
You can also move the full `headers` object over if that helps!

**Comment by dipakparmar** [comment]
> You can also move the full `headers` object over if that helps!

yeah, as needed full `headers` can be passed and it will be available at `this.context.headers` accessed with `this.context.headers.get('X-AUTH-SID')` In my use case, I only needed two headers from the user.
