### ISSUE TITLE
violate tslint rules 

### ISSUE THREAD

**Issue by mrdulin** [apollographql/apollo-server#2671]
![image](https://user-images.githubusercontent.com/17866683/57668448-ee048d80-7639-11e9-96c4-8becea994b68.png)

I think `apollo-server` should has `tslint.json` for itself. Shouldn't obey the tslint rules of users(the developers)' projects.

```json
"apollo-server": "^2.4.8",
"tslint": "^5.15.0",
"typescript": "^3.4.3"
```

**Comment by abernix** [comment]
We don't use `tslint.json` for the `apollo-server` repository itself and it's unlikely that we will be adopting it.

If you'd like to avoid your own `tslint.json` settings on other projects, I'd suspect there is a setting in your tooling to do that.

**Comment by ryami333** [comment]
I don't fully understand the reasoning here @abernix. If you have and use Tslint, then why don't you have a tslint.json? Conversely if you don't have a tslint.json then how can you use Tslint? I understand why you would have both, or have neither, but not why you would have one without the other.

Supplementary question - are you going to migrate to @typescript-eslint now that Tslint is deprecated? Would this be something you'd consider a PR for?
