### ISSUE TITLE
How to unit test data source methods

### ISSUE THREAD

**Issue by bharatvaggu** [apollographql/apollo-server#2679]
How to unit test data source methods individually. I want to test below Sample method. I have some custom code resolveURL()  in DataSourceBase. It is giving error like undefined "context" in resolveURL method.

* BaseDataSource.js
import { RESTDataSource } from 'apollo-datasource-rest';
export default class BaseDataSource extends RESTDataSource {
public async resolveURL(request) {
    if (!this.context.apiGatewayEvent.headers['token']) {
      throw new Error('token is missing');
    }
return super.resolveURL(request);
}
}

* Graph.js
import BaseDataSource from './DataSourceBase';
export default class Graph extends BaseDataSource {
  public Sample(params) {
    return {"key":params.value}
  }
}

Thanks

**Comment by JakeDawkins** [comment]
I realize it's been quite some time since you opened this, but if you haven't already figured this out, I'd recommend taking this question to the [Apollo Server channel within the Apollo community on Spectrum.chat](https://spectrum.chat/apollo/apollo-server) to discuss it further. Thanks!
