### ISSUE TITLE
apollo-server responding 500 on 4xx errors

### ISSUE THREAD

**Issue by mykevinjung** [apollographql/apollo-server#2681]
apollo-server-plugin-operation-registry throws `ForbiddenError` when a forbidden operation is invoked.  However, this error is responded with 500 http response code instead of 403 as in the following code:

https://github.com/apollographql/apollo-server/blob/577b35c4decf280cec612ac4e40efdcc4fe4601a/packages/apollo-server-core/src/runHttpQuery.ts#L287-L326

I think these 4xx Errors should be also handled separately with proper http response code as following example:

```
catch (error) {
    if (error instanceof HttpQueryError) {
      throw error;
    } else if (error instanceof AuthenticationError) {
        return throwHttpGraphQLError(401, [error], options);
    } else if (error instanceof ForbiddenError) {
        return throwHttpGraphQLError(403, [error], options);
    }
    return throwHttpGraphQLError(500, [error], options);
  }
```

**Comment by mykevinjung** [comment]
It seems that we can make it work using `GraphQLRequestListener` and `ApolloServerPlugin`. Closing.

**Comment by MM3y3r** [comment]
@mykevinjung could you give some example code?
