### ISSUE TITLE
Feature: GraphQL and Response formatter

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [apollographql/apollo-server#2682]
Here is a scenario, we are going through, kindly help or advise  or recommend options/alternatives.

We use GraphQL for querying data from PostgreSQL, it is working fine. Our requests are basically for three columns/attributes like name, value, timestamp.

With GraphQL, we get the data that seems to be having complete json output, with sort of format like this.
[
{
   "name": "temperature",
   "value": 31,
   "timestamp": 1558065273941
},

{
   "name": "fan_speed",
   "value": 60,
   "timestamp": 1558065273941
}
]

we want to reduce the transfer time and byte size, we want to format the GraphQL data in below format for few cases.

[
['temperature',31,1558065273941],
['fan_speed',60,1558065273941]
],

we can save 50% bytes on bandwidth, 50% improvement in downloading content. We would like to know if we can customize the graphql output format, we can handle the responses currently from graphql client side. 

We have 30+ charts per dashboard page, 500+ users and 10000+ devices, 300+ million records to handle in difference scenarios, some customisation like above would help us to build faster dashboard

**Comment by sbrichardson** [comment]
GraphQL doesn’t currently support scalar union types directly.
https://github.com/graphql/graphql-spec/issues/215

You could use a string for all 3 and parse on your own potentially. Example:

```gql
GetDashboardData(filter: DashboardDataFilterInput): [[String]]
```

**Comment by otang** [comment]
@gopalakrishnan-subramani this is a great suggestion and I'm also running into limitations of JSON format for very large nested JSON responses. Please let me know if you find a good solution. For now we are heavily caching the responses to static files and then serving them with Nginx -.-

**Comment by martijnwalraven** [comment]
For most cases, it turns out gzipping responses works well enough, but optimized transports might be worth looking into. They are not currently on the roadmap however, so I'm closing this issue.
