### ISSUE TITLE
Apollo Datasource Rest class not de-duping/memoizing

### ISSUE THREAD

**Issue by codegoblin** [apollographql/apollo-server#2686]
Hi all,

I'm trying to replace our apollo server's connector + dataloader setup w/ a datasource but it seems to not be memoizing identical datasource requests that happen w/in the same graphql query. I have even gone as far as printing out some console statements from the lib, ig:
```
            if (request.method === 'GET') {
                let promise = this.memoizedResults.get(cacheKey);
                console.log('CACHE KEY: ', cacheKey, `found: ${!!promise}`);
                if (promise)
                    return promise;
                promise = performRequest();
                this.memoizedResults.set(cacheKey, promise);
                return promise;
            }
            else {
                this.memoizedResults.delete(cacheKey);
                return performRequest();
            }
```
(This ^ is from the compiled ts code from line 257 of https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts)

here are some results:
```
CACHE KEY:  
https://judicata.free.beeceptor.com/api/search?exclude_criminal=false&exclude_old=false&filters=published_2%2Cpublished_3&page=1&query=test&sort_by=score&text_filters[]=&types[]=case
found: false

CACHE KEY:  
https://judicata.free.beeceptor.com/api/search?exclude_criminal=false&exclude_old=false&filters=published_2%2Cpublished_3&page=1&query=test&sort_by=score&text_filters[]=&types[]=case 
found: false
```
Note the identical cacheKey string. Any idea why this would be happening?

and yeah, just a simple
```
      dataSources: () => {
        return {
          judicataAPI: new JudicataAPI(),
        };
      },
```
in the middleware setup and w/in the datasource class here is how we're calling the request:
```
return await this.get(`/search?${qs}`);
```

**Comment by codegoblin** [comment]
Nvm it turned out to be due to contexts not being shared between batched queries

**Comment by EloB** [comment]
@codegoblin So the solution is to create the instance of `DataSource` outside `dataSources` function? What is the downside of doing this? All their examples uses instance creation within that function. I'm also trying to move to data sources...

**Comment by jasonvooo** [comment]
@codegoblin Have you found a solution to share the datasource instances between batch queries?

**Comment by jasonvooo** [comment]
> @codegoblin So the solution is to create the instance of `DataSource` outside `dataSources` function? What is the downside of doing this? All their examples uses instance creation within that function. I'm also trying to move to data sources...

Following up on this if anybody was interested, the downside of moving the initialisation of dataSources to the outside of the dataSources function is that if you have dynamic context variables then the context will be set to the latest values, not necessarily the context values which were set for the initial request.
