### ISSUE TITLE
Cant pass fragment variables via stitched schema to sub schemas.

### ISSUE THREAD

**Issue by daradoro** [apollographql/apollo-server#2698]
Cant pass fragment variables via stitched schema to sub schemas.

query ($id: String!) {
  elavonApp(filter: {_id: $id}) {
    ...ElavonApp
    __typename
  }
}
.....

that doesnt work..

{
  elavonApp(filter: {_id: '123'}) {
    ...ElavonApp
    __typename
  }
}

works.

Has any one had this problem before? Is this a feature that is missing? I cant seem to find any information on it

You can reproduce this by creating quick graphql apollo server project that has sub schemas and to query on it using fragment variables from the playground like i did above.

**Comment by trevor-scheer** [comment]
Hey @daradoro, schema stitching is part of `graphql-tools`, so you may want to open an issue there. Note that schema stitching is being deprecated and the recommendation is to migrate to federation however.
