### ISSUE TITLE
GraphQLExtension.didEncounterErrors with context or requestContext

### ISSUE THREAD

**Issue by morris** [apollographql/apollo-server#2702]
Feature request: GraphQLExtension.didEncounterErrors could receive the current context or requestContext. I would like to use it for logging, but I need the context (in our case, it holds a request ID which we'd like to see in our monitoring).

We work around this by using willSendResponse instead. This works, however in TypeScript this requires casting of GraphQLFormattedError to GraphQLError to get all the details we'd like to log. This could lead to bugs if apollo-server ever decides to strip the additional properties of GraphQLError when converting to GraphQLFormattedError.

**Comment by martijnwalraven** [comment]
`didEncounterErrors` should have access to the current context under `requestContext.context`: https://github.com/apollographql/apollo-server/pull/2719. Feel free to re-open this issue if that isn't working for you.

**Comment by cuchi** [comment]
I think @morris meant to use the Context via the `graphql-extensions` API, which is something I also need, [but it is not supported yet](https://github.com/apollographql/apollo-server/blob/3186d4039449fbb87c7746425d1644168cc70289/packages/graphql-extensions/src/index.ts#L49).
