### ISSUE TITLE
GRAPHQL_VALIDATION_FAILED and other default errors are missing when NODE_ENV=production

### ISSUE THREAD

**Issue by RIP21** [apollographql/apollo-server#2704]
`apollo-server: 2.5.0`
When I run a server with `NODE_ENV=development` and run some query that is wrong I'm getting.
```
{
  "error": {
    "errors": [
      {
        "message": "Field \"topupLimit\" of type \"Money!\" must have a selection of subfields. Did you mean \"topupLimit { ... }\"?",
        "locations": [
          {
            "line": 9,
            "column": 7
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {}
        },
        "level": "error",
        "timestamp": "2019-05-21T18:50:16.427Z"
      }
    ]
  }
}
```
But if I run exactly the same server but with `NODE_ENV=production` all default errors are swallowed and just I'm getting.
```
{
  "error": {
    "errors": [
      {
        "message": "Internal server error",
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR"
        }
      }
    ]
  }
}
```
More specific, that I created myself based of `ApolloError`, are returned back no problem.

PLS HALP! Wasn't able to find any issue about it.

**Comment by devniel** [comment]
Hello, got the same problem, how did you solve it ? 
Thanks!

**Comment by RIP21** [comment]
@devniel yup you're right :)

**Comment by kfrajtak** [comment]
What? I don't want to show the stacktrace in production.

**Comment by capndave** [comment]
I know it's a bit late @devniel, but in what file/code block do you specify `debug: true`?
