### ISSUE TITLE
[Feature] transform headers in transformRequest.

### ISSUE THREAD

**Issue by Pruxis** [apollographql/apollo-server#2713]
Adding the ability to set the headers in transformRequest would open a range of new possibilities to safeguard yourself when writing microservices and stitching them together.

Use case:

I have a main API gateway Apollo Server where we handle all authentication and authorization.
I have a microservice Apollo Server that manages a subset of the entire schema.

Upon stitching I want to make sure that my team and me do not forget to write the wrapping resolver to handle the authentication and authorization.

By setting a dynamic header in the transformRequest function it opens up the possibility to expect this header in your microservice or else deny the request immediately. This brings you safeguarding when you have forgotten to write the "link" resolver between your parent schema and child schema's.

I would like to work on this, but before I send in a PR I would like to make sure that this functionality is something Apollo sees a fit for.

**Comment by martijnwalraven** [comment]
`transformRequest` is part of the `graphql-tools` API, so you may want to open an issue there. Note that schema stitching is being deprecated and we recommend using federation instead however.
