### ISSUE TITLE
mention CDN in README or docs?

### ISSUE THREAD

**Issue by odigity** [apollographql/apollo-server#2720]
I just noticed that the instance of GraphQL Playground served by Apollo Server is actually hosted on a CDN (cdn.jsdelivr.net).

Given that this may have privacy and reliability implications for some people, I suggest explicitly mentioning this in the README or docs.

**Comment by JacksonKearl** [comment]
It is mentioned in the GraphQL Playground [README](https://github.com/prisma/graphql-playground/#as-html-page), along with steps to host locally. We link to the readme from our own [GraphQL Playground docs](https://www.apollographql.com/docs/apollo-server/features/graphql-playground), where we also state that we are not the creators of GraphQL Playground.

Closing this for now but if you think that is insufficient we can take another look.
