### ISSUE TITLE
server API doc missing some options

### ISSUE THREAD

**Issue by odigity** [apollographql/apollo-server#2721]
Just read through the Apollo Server API docs (learning) and noticed a few constructor options mentioned elsewhere were not documented there:

https://github.com/apollographql/apollo-server/blob/master/docs/source/api/apollo-server.md

Specifically:

- onHealthCheck
- plugins
- dataSources

**Comment by glasser** [comment]
The `plugins` option is now documented at https://www.apollographql.com/docs/apollo-server/api/apollo-server

The `onHealthCheck` and `dataSources` options are not part of Apollo Server 4.
