### ISSUE TITLE
[2.6.0] TypeError: Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by wKovacs64** [apollographql/apollo-server#2753]
### Description

Just tried to update `apollo-server-express` from 2.5.1 &rarr; 2.6.0 but it's failing with the following:

```
TypeError: Cannot read property 'some' of undefined

  61 | 
> 62 |   const apolloServer = new ApolloServer({
     |                        ^

  at typeDefs.some.typeDef (node_modules/apollo-server-core/src/utils/isDirectiveDefined.ts:8:25)
      at Array.some (<anonymous>)
  at Object.<anonymous>.exports.isDirectiveDefined (node_modules/apollo-server-core/src/utils/isDirectiveDefined.ts:7:12)
  at new ApolloServerBase (node_modules/apollo-server-core/src/ApolloServer.ts:275:12)
  at new ApolloServer (node_modules/apollo-server-express/src/ApolloServer.ts:84:5)
```

It appears this only happens when importing typeDefs from an SDL file.

### Reproduction

[Glitch Remix](https://glitch.com/edit/#!/ubiquitous-adjustment) (see server.js line 5, and open the logs)

---

#### Hacky Workaround

I modified `isDirectiveDefined` locally to include a truthiness check and that works, but I'm not sure if that's a real fix or just masking an actual problem (e.g. should all `typeDef` objects have a `definitions` property, or is `undefined` valid?).

[packages/apollo-server-core/src/utils/isDirectiveDefined.ts#L8](https://github.com/apollographql/apollo-server/blob/ddb51cc1c4efa07d1be5320201cac3b69bcd0571/packages/apollo-server-core/src/utils/isDirectiveDefined.ts#L8)
```diff
  typeDefs.some(typeDef =>
-    typeDef.definitions.some(
+    typeDef.definitions && typeDef.definitions.some(
      definition =>
```
The code indicates `typeDef` is of type `DocumentNode` from `graphql/language` but I didn't see `DocumentNode` in the exported type definitions and ran out of time to chase that further. ¯\\\_(ツ)_/¯

**Comment by trevor-scheer** [comment]
Hey @wKovacs64, thanks for taking the time to report your issue. Based on the typings for a `DocumentNode`, it's invalid for `definitions` to be `undefined` (it should be at least an empty array):

```typescript
export interface DocumentNode {
    readonly kind: "Document";
    readonly loc?: Location;
    readonly definitions: ReadonlyArray<DefinitionNode>;
}
```

In the glitch you provided, you're passing a string as `typeDefs`, when it really wants a `DocumentNode` (we know those more familiarly as the result of `gql`).

By passing that string into `graphql-tag`'s function, we get the resulting `DocumentNode` that we want, like so:

```javascript
const server = new ApolloServer({
  typeDefs: gql`${typeDefs}`,
  resolvers
});
```

I'm fairly certain this should resolve the issue, but if not, please feel free to reopen. Thanks again!

**Comment by trevor-scheer** [comment]
@abernix and I have discussed this a bit and recognize it as an unintended breaking change. We're working on a patch to reintroduce support for `typeDefs` as `string`s as we speak. Once again, appreciate the report!

**Comment by abernix** [comment]
Fixed in 2.6.1 (#2754), thanks to the both of you! 🚀

**Comment by wKovacs64** [comment]
Thank you!

**Comment by spondbob** [comment]
Bump this issue for latest 2.6.6

Passing `string` to `typeDefs` triggers same error unless wrap it in `gql`.

**Comment by ngbrown** [comment]
I'm getting this error again in `apollo-server-core@2.9.7`.  It wasn't happening in `apollo-server-core@2.4.8` but I updated all the sub-dependencies of `apollo-server-express` and have no outstanding npm updates.

**Comment by mg9101** [comment]
Hi! I'm getting the same error and it's wrapped in `gql`. 
Version 2.11

**Comment by trevor-scheer** [comment]
@mg9101 can you please provide a runnable reproduction for us? Also if you're able, please make sure your server is running the latest version. Thanks!

**Comment by chrisjaimes** [comment]
@trevor-scheer I am also facing the same TypeError even after wrapping in `gql`. I created a repo to run and reproduce it here https://github.com/chrisjaimes/apollo-server-error Any suggestions what I could be missing?

**Comment by chrisjaimes** [comment]
Finally... I got it to work after making this changes: https://stackoverflow.com/questions/64285400/error-when-building-typedefs-typeerror-cannot-read-property-some-of-undefined/64288307#64288307
