### ISSUE TITLE
Unknown type "Upload". Did you mean "Float"?

### ISSUE THREAD

**Issue by rico345100** [apollographql/apollo-server#2765]
I followed this [post](https://blog.apollographql.com/file-uploads-with-apollo-server-2-0-5db2f3f60675).

And this is my graphql schema:

```graphql
extend type Mutation {
  bannerAdd(
    title: String!
    image: Upload
  ): ID
}
```

But when I run the app, it fails with:

> Error: Unknown type "Upload". Did you mean "Float"?

Followed from above post, apollo-server automatically put the Upload scalar, but why gives me this error?

Also trying to put Upload scalar also not working:

```graphql
scalar Upload

...
```

It gives me:

> Error: There can be only one type named "Upload".

What am I missing?

Versions:
- Node@10.14.2
- Apollo Server@2.6.1
- Apollo Server Exrepss@2.6.1
- polka@0.5.2

**Comment by rico345100** [comment]
I'm currently renamed to something like "scalar FileUpload" or something and it seems working now, but you guys should be fix this issue.

**Comment by JacksonKearl** [comment]
Hey, that was a mistake on our part. In fact, the `Upload` type is only added if you do not pass a `schema` explicitly. The post was updated but you might not have seen that. In any case, thanks for reporting this!

**Comment by rico345100** [comment]
@JacksonKearl  Thanks for reply. Could you give me url address of that post?

**Comment by JacksonKearl** [comment]
It’s the one you linked in the original issue

**Comment by ScripterSugar** [comment]
why is this issue closed? there's still a problem, I can't add scalar named "Upload" when I'm manually setting my schema, because apollo server gives me an error Error: There can be only one type named "Upload" still it doesn't adds Upload scalar automatically.
