### ISSUE TITLE
@Provides Directive Unexpected Error

### ISSUE THREAD

**Issue by ksaldana1** [apollographql/apollo-server#2772]
Reproduction Repo: https://github.com/ksaldana1/provides-fed-repro

I am pretty confused by what I am seeing here. I followed the example from the docs, and from what I can tell the structure I have isn't any different from the example provided in the [federation-demo](https://github.com/apollographql/federation-demo/blob/master/services/reviews/index.js), but maybe I'm missing something really obvious.

Despite me [labeling](https://github.com/ksaldana1/provides-fed-repro/blob/master/services/users/index.js#L11) my [fields](https://github.com/ksaldana1/provides-fed-repro/blob/master/services/users/index.js#L17), I'm still getting error messages such as : 
```UnhandledPromiseRejectionWarning: GraphQLSchemaValidationError: [users] Kitchen.name -> is marked as @external but is not used by a @requires, @key, or @provides directive.```

This was happening on a larger project and seemed to continue when I scaled it down. 

Thanks for all your hard work! Federation is really awesome!

**Comment by jbaxleyiii** [comment]
@ksaldana1 this does indeed seem like a bug! @JakeDawkins can you take a look?

**Comment by JakeDawkins** [comment]
I'm on it!

**Comment by JannesV** [comment]
@JakeDawkins, any update on this? I seem to be having a similar issue:

```
extend type TruckType @key(fields: "id"){
    id: ID! @external
}
```

throws the following error:
```
Exception: GraphQLSchemaValidationError: [inquiries] TruckType.id -> is marked as @external but is not used by a @requires, @key, or @provides directive
````

Thanks for the hard work!

**Comment by JakeDawkins** [comment]
Hey @JannesV! Sorry for the slow response. I have a [WIP PR](https://github.com/apollographql/apollo-server/pull/2878) open for the issue now. I have a couple more cases to fix, especially around `@requires`, but I'm trying to wrap it up quickly!

**Comment by JannesV** [comment]
Thanks! I've just found out my error was due to my own ignorance. I forgot to specify the @key directive on the type I'm extending. When including that it resolved my issue.

**Comment by ksaldana1** [comment]
Thanks for getting this fixed @JakeDawkins ! The first time I read through the federation docs I thought "I don't think I'll need these advanced features...", but then after I grokked them it felt hard to live without. So thanks for being one step ahead on the features!
