### ISSUE TITLE
Object.fromEntries is not defined in Node.js versions < 12

### ISSUE THREAD

**Issue by hannesj** [apollographql/apollo-server#2775]
In https://github.com/apollographql/apollo-server/commit/7e78a2353b9e855d85a7998b06e8f9d4cb1db54d usage of `Object.fromEntries` was added to apollo-server-lambda. [Package.json](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-lambda/package.json#L25) specifies that Node.js versions from 6 up are supported. When running `apollo-server-lambda` in Node.js versions older than 12, I get the error `Object.fromEntries is not a function`, as support was only added in [that version](https://node.green/#ES2019-features--Object-fromEntries).

**Comment by trevor-scheer** [comment]
This is resolved in the most recent publish: https://github.com/apollographql/apollo-server/commit/4fdf6f2aa2f14854b54b0d6de7d477afc7702916

`- apollo-server-lambda@2.6.2`

Thanks for reporting!
