### ISSUE TITLE
[Federation] __resolveType is not executed

### ISSUE THREAD

**Issue by Pruxis** [apollographql/apollo-server#2781]
When utilising an union or interface, __resolveType resolvers are not executed when passed into a federated schema.

Codesandbox: https://codesandbox.io/s/apollo-server-z8vml?fontsize=14

Currently you can write a 'hack' around it to pass the __typename in your return function yourself. Instead of relying on the interface to have this functionality.

I'll investigate the code what the difference is and why this is the case, so I can PR a solution

**Comment by trevor-scheer** [comment]
Thanks @Pruxis for submitting this (and the demonstration)!

If you'd like to take this on (it sounds like you intend to), just let me know if I can help at all. Otherwise, just let us know so we can resolve the issue.

**Comment by Pruxis** [comment]
I've dug through the code a bit, and to be frank it's quite obfuscated to pinpoint what is missing.
Seems like the implementation is just missing in modules aswell and is quite different to how regular schema's are scaffolded.

**Comment by trevor-scheer** [comment]
@Pruxis I spent some time trying to clarify the issue for myself since it wasn't quite apparent to me. I forked and simplified your example, can you confirm the reproduction here is what you were describing to me?

1) Toggle between federated and non-federated schema
2) Note that `__resolveType()` isn't invoked in federated schema (but `__isTypeOf()` is!)

**Comment by Pruxis** [comment]
Hey @trevor-scheer thanks for taking the time to check this, I can use __isTypeOf for now as in the end it covers the same functionality only difference is that the code is more spread out over different types.

**Comment by trevor-scheer** [comment]
@Pruxis No problem, thanks for identifying it. I've got a PR open to resolve the issue, should have this fixed up some time tomorrow. Keep an eye out for the release 😄
