### ISSUE TITLE
federation: @provides on list types

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/apollo-server#2788]
**Reproduction:**
https://github.com/apollographql/federation-demo/compare/master...lennyburdette:search-service-provides-error?expand=1

This does not work:

```graphql
extend type Query {
  searchProducts(term: String!) [Products!]! @provides(fields: "name")
}
```

The error is: 
```
uses the @provides directive but `Query.searchProducts` returns `[Product!]!`, 
which is not an Object type. @provides can only be used on Object types 
with at least one @key.
```

Can `@provides` look at the object type _inside_ the list type for provided fields?

**Comment by jbaxleyiii** [comment]
@lennyburdette yes this should definitely work! Thanks for the reproduction!
