### ISSUE TITLE
Passing PerMessageDeflate configuration options to the WebSocket Server

### ISSUE THREAD

**Issue by roman-may** [apollographql/apollo-server#2791]
We have a UseCase for GraphQL Subscriptions where we'd like to activate perMessageDeflate on the underlying WebSocket server. Normally, this can be configured with the PerMessageDeflate ServerOption on the WebSocket Server, but as far as I know there is currently no way to pass additional configuration options to the Server.

Therefore, I'd like to propose to add a perMessageDeflate configuration Option to the SubscriptionServerOptions object in the ApolloServer Config.

I could provide a PR for this.

**Comment by Aldrian** [comment]
I have the opposite issue on my server, where the WebSocket is closed before the connection is established.
I'm using a microsoft azure app-service for this, and an [FAQ article](https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-faq#language-support) says to disable perMessageDeflate.
If this is related, maybe perMessageDeflate is activated by default? 

In any case, providing websocket configuration option to the ApolloServer config could be useful.

**Comment by andylhansen** [comment]
I am also experiencing a possible issue with perMessageDeflate being enabled by default. I am using a dot net graphql client, and it is failing to connect.

Can anybody confirm if it is enabled or disabled by default?

**Comment by glasser** [comment]
Direct subscriptions integration was removed from Apollo Server in v3 last year.
