### ISSUE TITLE
Adding apollo server middleware broke original routes

### ISSUE THREAD

**Issue by rico345100** [apollographql/apollo-server#2795]
I have a polka server:

```javascript
import * as polka from 'polka';

const app = polka({});

app.get('/health', (req, res) => {
	console.log('/health');
	res.end();
});
```

Run the server, accessing localhost:3000/health works fine. But after adding apollo server middleware, it always returns graphql server.

```javascript
import * as polka from 'polka';
import { server as graphqlServer, schema } from './apolloServer';

const app = polka({});

app.get('/health', (req, res) => {
	console.log('/health');
	res.end();
});

graphqlServer.applyMiddleware({
	app,
	path: '/'
});
```

My get route was set first, but when I try to access localhost:3000/health, it just returns graphql server instead. I might understand if my route settings were located after applyMiddleware, but it's not. Why this happens and how do I fix it?

Using polka@0.5.2 and Apollo Server@2.6.1

**Comment by JacksonKearl** [comment]
In polka, middleware mounted on '/' is executed before any route-specific middleware. See https://github.com/lukeed/polka#middleware-sequence. This is different from express, where middleware is executed in order of declaration. You can fix this by mounting Apollo Server on `/graphql`, which is actually the default.
