### ISSUE TITLE
`parseOptions` seems not affect result

### ISSUE THREAD

**Issue by piglovesyou** [apollographql/apollo-server#2799]
`new Apollo()` must accept `parseOptions` option but it doesn't affect result even I pass it. In my case `allowLegacySDLEmptyFields` didn't effect at all.

# Expected
I believe the parser accept the option so suppose `type Query { }` should be allowed.
https://github.com/graphql/graphql-js/blob/v14.1.1/src/language/__tests__/schema-parser-test.js#L831-L83

# Actual
It shows `Expected error: "GraphQLError: Syntax Error: Expected Name, found }"` as same as not passing the option.
https://codesandbox.io/embed/apollo-server-pd182

**Comment by chentsulin** [comment]
The error was thrown by `graphql-tag` package. It does not support parse options - `allowLegacySDLEmptyFields`.

https://github.com/apollographql/graphql-tag/blob/50a850e484a60d95ddb99801c39785031e55b7a2/src/index.js#L129

**Comment by piglovesyou** [comment]
Thank you for taking a look. Ah I didn't get it, the error seems to come from `node_modules/graphql/error/syntaxError.js`, no?

[The types seem declared too](https://github.com/apollographql/apollo-server/blob/1d2e8a1534499bfaee807b388e49d5a191d3540f/packages/apollo-server-core/src/types.ts#L72). I'm using `apollo-server-core@2.6.3` and `typescript@3.5.2` in my IntelliJ and I'm seeing the autocomplete.

![Screen Shot 2019-06-19 at 23 16 00](https://user-images.githubusercontent.com/217530/59773221-3a518600-92e8-11e9-8eba-934e1443a1d2.png)

**Comment by piglovesyou** [comment]
@chentsulin Sorry, I caught up. The `typeDefs` passed to `new ApolloServer()` must be `DocumentNode | DocumentNode[]` but `gql()` doesn't support accepting `allowLegacySDLEmptyFields` option.

Weird point: Where is a chance to consume `parseOptions`?

But I'll close this issue since I found a solution. `makeExecutableSchema()` accepts `typeDefs: string[]`.

```js
    const typeDefs = `
        type Query { }
        extend type Query { _: Boolean }
        schema { query: Query }`;

    let message = '';
    try {
      new ApolloServerBase({
        schema: makeExecutableSchema({ typeDefs }),
      });
    } catch (e) {
      // Without the option a Syntax Error occurs
      message = e.message;
    }
    expect(message).toContain('Syntax Error: Expected Name, found }');

    // This works
    new ApolloServerBase({
      schema: makeExecutableSchema({
        typeDefs,
        parseOptions: { allowLegacySDLEmptyFields: true },
      })
    });
```
