### ISSUE TITLE
Problems using InMemoryCache with TypeScript

### ISSUE THREAD

**Issue by joemckie** [apollographql/apollo-server#2811]
When using `InMemoryCache` with TypeScript, the the following error is given:

`Type 'InMemoryCache' is missing the following properties from type 'KeyValueCache<string>': get, set, delete`.

This is in version `2.6.2`.

**Comment by JoviDeCroock** [comment]
I think this issue belongs in the `apollo-client` repository since the cache is published from there.

**Comment by joemckie** [comment]
@JoviDeCroock thanks, I'll post it there
