### ISSUE TITLE
Federation: Syntax error when adding a description to an extended type

### ISSUE THREAD

**Issue by JacksonKearl** [apollographql/apollo-server#2826]
The federated schema
```gql
"""
A description of this extended type.
"""
extend type User @key(fields: "id") {
  "The unique ID of the user."
  id: ID! @external
  "The URL of the user's avatar."
  avatar: String
}
```

Results in `GraphQLError: Syntax Error: Unexpected Name "extend"` at parse. This does not happen if the description is removed.

(Thanks to @mandiwise for finding this, over in #2808)

**Comment by JacksonKearl** [comment]
@jbaxleyiii Do you think extended types should be able to even have descriptions? It might make the most sense to prohibit/ignore descriptions on `@external` fields and extended types. What do you think?

**Comment by JacksonKearl** [comment]
Turns out this is per-spec, only type definitions may have a description, type extensions may not. https://graphql.github.io/graphql-spec/June2018/#sec-Object-Extensions

**Comment by mandiwise** [comment]
Good to know, thanks for the insight.
