### ISSUE TITLE
[Federation] Executor Type Mismatch (TypeScript)

### ISSUE THREAD

**Issue by mssngr** [apollographql/apollo-server#2834]
# Summary
I am trying to follow the example for creating a federated gateway in Apollo. I code mostly in TypeScript, so I decided to implement it as a `.ts` file. However, there's a type mismatch between what ApolloServer expects in the `executor` and what ApolloGateway provides.

# Expected Behavior
The TypeScript compiles because the `executor` type that `ApolloGateway` provides matches the `executor` type that `ApolloServer` expects.

# Actual Behavior
I receive this type error:
```
(property) executor?: GraphQLExecutor<Record<string, any>> | undefined

Type '<TContext>(requestContext: WithRequired<GraphQLRequestContext<TContext>, "document" | "operation" | "queryHash">) => Promise<GraphQLExecutionResult>' is not assignable to type 'GraphQLExecutor<Record<string, any>>'.
  Types of parameters 'requestContext' and 'requestContext' are incompatible.
    Type 'WithRequired<GraphQLRequestContext<Record<string, any>>, "document" | "operationName" | "operation">' is not assignable to type 'WithRequired<GraphQLRequestContext<Record<string, any>>, "document" | "operation" | "queryHash">'.
      Type 'WithRequired<GraphQLRequestContext<Record<string, any>>, "document" | "operationName" | "operation">' is not assignable to type 'Required<Pick<GraphQLRequestContext<Record<string, any>>, "document" | "operation" | "queryHash">>'.
        Types of property 'queryHash' are incompatible.
          Type 'string | undefined' is not assignable to type 'string'.
            Type 'undefined' is not assignable to type 'string'.ts(2322)

graphqlOptions.d.ts(16, 5): The expected type comes from property 'executor' which is declared here on type 'ApolloServerExpressConfig & { cors?: boolean | CorsOptions | undefined; onHealthCheck?: ((req: Request) => Promise<any>) | undefined; }'
```

# Reproducable Example
You can find the code to reproduce this error here: https://github.com/mssngr/apollo-federation-bug

**Comment by jbaxleyiii** [comment]
@mssngr this fix has landed on master and should be released today!

**Comment by dhm116** [comment]
Maybe I was looking in the wrong place, but I don't see any commits to `master` recently that would have addressed this issue (which I'm running into now).

`GraphQLOptions` still defines the expected type as [`GraphQLExecutor`](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/graphqlOptions.ts#L42) and the `load` method on the gateway is [not returning a `GraphQLExecutor`-typed method](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-gateway/src/index.ts#L163...L168)

Is there a specific commit that you could point to with the fix? Or perhaps it was merely a documentation change to help indicate how to avoid this issue? Any help or insight would be really appreciated! Thanks!

**Comment by dhm116** [comment]
My bad, I hadn't seen the `queryHash` addition to [the requestPipelineAPI.ts file](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/requestPipelineAPI.ts#L100) for the `GraphQLExecutor` type.

**Comment by brianschardt** [comment]
I can confirm this is happening to me too. apollo gate way has not been updated in 7 days. Bug still exists
