### ISSUE TITLE
Gateway does not deduplicate variables

### ISSUE THREAD

**Issue by hannesj** [apollographql/apollo-server#2839]
When using a federated graph gateway, variable definitions in the query should be deduplicated.

When sending the following query to the gateway: 

```
query TestQuery($size: Int!){
  me {
    id
    name
    profilePicture(size:$size)
    backgroundImage(size:$size)
  }
}
```

It sends the following query downstream to the service providing `me`. Note the duplicated size variable definition.

```
query ($size: Int, $size: Int) {
  me {
    id
    name
    profilePicture(size: $size)
    backgroundImage(size: $size)
  }
}
```

**Comment by hannesj** [comment]
Should probably done [here](https://github.com/apollographql/apollo-server/blob/408e9a99b7efb1f18a292c92b334ad999ef4a04b/packages/apollo-gateway/src/executeQueryPlan.ts#L338-L349)

**Comment by jbaxleyiii** [comment]
@hannesj thanks for the report and the fix!
