### ISSUE TITLE
Add headers to @apollo/gateway service definitions

### ISSUE THREAD

**Issue by heysailor** [apollographql/apollo-server#2852]
It is currently impossible to federate schemas from child servers where the child servers require headers to be passed at time of federation, eg an authorization header.

Currently, ApolloGateway accepts a service list of the form `{ url: string, name: string }`, and calls `loadServicesFromRemoteEndpoint` from `@apollo/gateway/src/loadServicesFromRemoteEndpoint.ts`.  To load the service definitions, fetch is called with headers of only `'Content-Type': 'application/json'`.

It would be very helpful to allow definition of custom headers in the service list, which are then passed in `loadServicesFromRemoteEndpoint`.

eg, a `ServiceDefinition` of
```typescript
interface ServiceDefinition {
  url: string
  name: string
  headers?: {[key: string]: string}
}
```

and replace lines 29-35 of `@apollo/gateway/src/loadServicesFromRemoteEndpoint.ts` with
```typescript
      return fetch(service.url, {
        method: 'POST',
        body: JSON.stringify({
          query: 'query GetServiceDefinition { _service { sdl } }',
        }),
        headers: { 
          ...(service.headers ? service.headers : {} ),
          'Content-Type': 'application/json'
        },
      })
```

A similar facility exists in `willSendRequest` [as documented here](https://www.apollographql.com/docs/apollo-server/api/apollo-gateway/#constructoroptions-remotegraphqldatasource) but this is only applied when an external graphql request is made.

As an extra bonus, the header provided in the ServiceDefinition could be also passed in every request to prevent duplication.

**Comment by calebfaruki** [comment]
https://github.com/apollographql/apollo-server/issues/2833

**Comment by JacksonKearl** [comment]
Alternative: #2892.
