### ISSUE TITLE
Get Started button on https://www.apollographql.com/docs/apollo-server/ does nothing

### ISSUE THREAD

**Issue by alexmiddeleer** [apollographql/apollo-server#2879]
The "Get started" button on https://www.apollographql.com/docs/apollo-server/ does nothing.

![image](https://user-images.githubusercontent.com/5400639/59697269-8a7efa00-91bb-11e9-8499-44539ce3f91e.png)

**Comment by abernix** [comment]
This should be fixed thanks to #2902.  I appreciate you reporting this!
