### ISSUE TITLE
federation improvement requisition

### ISSUE THREAD

**Issue by moniz1** [apollographql/apollo-server#2885]
Hi Apollo officer,

currently I've been working with federation & I found out few problems:

1. While gateway is instrospecting (gateway.load) the services, I cannot add custom header due to you guys hard code that

2. buildFederation function is not accepting any custom directive and I cannot add graphql-constraint-directive to the schema.

Please help to provide an enhancement on it thanks you.

**Comment by codyspate** [comment]
@moniz1 you can add `introspectionHeaders` now to apollo gateway. 
See https://www.apollographql.com/docs/apollo-server/api/apollo-gateway/#parameters for docs

**Comment by trevor-scheer** [comment]
Resolved by #3120 (also #2892)
