### ISSUE TITLE
Cannot provide hash function for persisted queries

### ISSUE THREAD

**Issue by ryanjo9** [apollographql/apollo-server#2894]
[Apollo-link-persisted-queries](https://github.com/apollographql/apollo-link-persisted-queries) allows you to provide a hash function for persisting a query. However, at line 167 in [requestPipeline.ts](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/requestPipeline.ts) in [apollo-server-core] (https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-core) the server hashes the query passed in with the request always using SHA 256 Hex and then compares it against the hash passed in with the request. If the client uses any other hash function than SHA 256 the server will throw an error saying "provided sha does not match query".  The ability to provide a hash function seems like it should be available on both the client and the server or neither.

**Comment by hchuff** [comment]
The intention of the client API was to provide a different implementation of SHA 256. We are not looking to provide a custom hash implementation on the server-side.
