### ISSUE TITLE
Error types (instanceof) are lost if thrown from resolver

### ISSUE THREAD

**Issue by stringbeans** [apollographql/apollo-server#2898]
**apollo-server-express@2.6.3**

If I throw an `AuthenticationError` from a resolver, I cannot detect this from the `formatError` handler. For example:

```
// somewhere in a resolver...
import { AuthenticationError } from 'apollo-server-express'
const resolve = (_, args, context) => {
  throw new AuthenticationError('test')
}

// in formatError handler
const formatError = (error) => {
  console.log(error instanceof AuthenticationError) // returns false
  return error
}
```

HOWEVER, if the error is `SyntaxError` or `ValidationError` produced by GraphQL automatically due to a malformatted graphql request, then the `instanceof` check works.

A quick working sample: https://codesandbox.io/s/apollo-server-ft3ul?fontsize=14

**Comment by stringbeans** [comment]
as an aside, my use case is i want to use the `instanceof` check to handle specific errors in the `formatError` handler based on the type of error (ie. for logging purposes). 

if for some reason its impossible to preserve the error type, then exporting a static list of the different error codes produced by apollo's errors would be useful so i could check based on those as an alternate route

**Comment by kabachook** [comment]
Same for me, it just returns `GraphQLError` for everything

**Comment by bnaoki** [comment]
Have you tried checking `error.originalError`?

**Comment by kabachook** [comment]
@bnaoki Thanks, it works. But I think it should be stated somewhere in docs.

**Comment by stringbeans** [comment]
@kabachook @bnaoki when i use `instanceof` on error.originalError it still doesnt preserve the original error type thrown (or at least i am unable to reproduce it)

**Comment by kabachook** [comment]
@stringbeans following your example, I changed `error` to `error.originalError` and it worked. On CodeSandbox it is an old version of `apollo-server`, try upgrading it.

**Comment by bhishp** [comment]
I am having this same issue, even with `error.originalError`

I am using TypeORM which will throw a `QueryFailedError` when a query Timeout occurs (along the lines of `QueryFailedError: Error: Timeout: Request failed to complete in 5000ms`).

This is the correct instance in the resolver, but when it reaches formatError it seems to have been mutated. Note, I **don't** have any plugins on the server.

```ts
// within resolver
{
...
    try {
      const typeORMResult = await query.getMany();
      return typeORMResult;
    } catch (e) {
      console.log(e.name); // logs 'QueryFailedError'
      console.log(e instanceof QueryFailedError); // logs 'true'
      throw e;
    }
...
}

// formatError
formatError: err => {
  console.log(err.originalError.name); // logs 'Error'
  console.log(err.originalError instanceof QueryFailedError); // logs 'false'
  console.log(err.originalError instanceof Error); // logs 'true'
  return err;
},
```

Additional: If I create an apollo plugin and hook in to `didEncounterErrors` the same thing happens. The originalError here is also no longer a QueryFailedError

**Comment by bhishp** [comment]
Interestingly, if an ApolloError is thrown from the Resolver it seems to preserve the Error type, but not if any custom errors are thrown. Some more snippets..

A custom error

```ts
export class CustomError extends Error {}

// within resolver
try {
  const cargoes = await query.getMany();
  return convertColumns(cargoes);
} catch (e) {
  const E = new CustomError('Boo');
  console.log(E instanceof CustomError); // logs 'true'
  throw e;
}

// within formatError
formatError: err => {
  console.log(err.originalError instanceof CustomError); // logs 'false'
  return err;
},
```

An ApolloError

```ts
// within resolver
try {
  const cargoes = await query.getMany();
  return convertColumns(cargoes);
} catch (e) {
  throw new ApolloError('Foo');
}

// within formatError
formatError: err => {
  console.log(err.originalError instanceof ApolloError); // logs 'true'
  return err;
},
```

**Comment by cerino-ligutom** [comment]
@bhishp Have you found a solution or workaround for this? We're throwing custom errors and we're still getting `INTERNAL_SERVER_ERROR` as the error code on an `ApolloError` instance once it gets past `formatError`. Still remains an issue on v3.

```js
"apollo-server-core": "3.3.0"
"apollo-server-express": "3.3.0"
```

**Comment by bhishp** [comment]
> @bhishp Have you found a solution or workaround for this? We're throwing custom errors and we're still getting `INTERNAL_SERVER_ERROR` as the error code on an `ApolloError` instance once it gets past `formatError`. Still remains an issue on v3.
> 
> ```js
> "apollo-server-core": "3.3.0"
> "apollo-server-express": "3.3.0"
> ```

Afraid not. I am no longer working on the project so haven't had to do any more related to Apollo server error reporting

**Comment by cerino-ligutom** [comment]
@bhishp Thanks for getting back. Idk if you were using TypeScript back then but in my case, turns out it was TS related. Updated #5704.

**Comment by bhishp** [comment]
> @bhishp Thanks for getting back. Idk if you were using TypeScript back then but in my case, turns out it was TS related. Updated #5704.

Ah, interesting, good investigation. Yes, it was a typescript project so I imagine it was the same problem. Thanks
