### ISSUE TITLE
Cache Control headers not set when cacheControl extension is enabled

### ISSUE THREAD

**Issue by blimmer** [apollographql/apollo-server#2918]
## Package Name & Version
The issue is present in `apollo-server-express`, the latest version (2.6.4).

## Latest version where the problem did not occur
I believe this issue was introduced with [this commit](https://github.com/apollographql/apollo-server/commit/ae14665aea126c0e6464dbabb34726534a3456c6), where a test was added explicitly for this behavior.

## Expected Behavior

When the `cacheControl` extension is enabled, the server should continue sending `Cache-Control` HTTP headers.

## Actual Behavior

When the `cacheControl` extension is enabled, the server no longer sends `Cache-Control` HTTP headers.

## Repo demonstrating the problem

https://github.com/blimmer/apollo-server-express-bug-report

**Comment by blimmer** [comment]
This issue is a result my PR attempting to document this behavior (https://github.com/apollographql/apollo-server/pull/2880) where @abernix recommended opening an issue.

**Comment by glasser** [comment]
The `cacheControl` option for configuring cache control was removed from Apollo Server in v3 last year. (The feature still exists but is implemented as a standard Apollo Server plugin.)

My memory is that `cacheControl: true` was a weird backwards-compatible thing that added a GraphQL extension to the response (used by the engineproxy project which was discontinued in 2018) and did not set cache-control headers, so the bug reported here was "working as intended" but not a useful feature, and this legacy support is no longer part of Apollo Server.
