### ISSUE TITLE
@requires not working when referencing an empty String

### ISSUE THREAD

**Issue by hugues33** [apollographql/apollo-server#2925]
Hi,

@apollo/gateway: 0.6.9

I have the following type :
`extend type Enrollment @key(fields: "enrollmentId") {
  enrollmentId: ID! @external
  adminUserId: String @external
  adminUserEmail: String @requires(fields: "adminUserId")
}
`
when I get adminUserEmail, it's working if adminUserId is a non empty string, but not if it's value is an empty string "".
In this case I get the error :

> "Error: Field \"adminUserId\" was not found in response.",
            "    at executeSelectionSet (c:\\cloud\\common-graphql-gateway\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:162:27)",
            "    at executeSelectionSet (c:\\cloud\\common-graphql-gateway\\node_modules\\@apollo\\gateway\\dist\\executeQueryPlan.js:178:51)"

Is it a bug or should I have a non empty string in adminUserId ?

Thanks

**Comment by hugues33** [comment]
I think it's the same as #2928

**Comment by jbaxleyiii** [comment]
@hugues33 yep! @evans is on it 🎉
