### ISSUE TITLE
apollo-server-hapi - hapi dependency is renamed

### ISSUE THREAD

**Issue by plaidman** [apollographql/apollo-server#2926]
in ApolloServer.ts, you have `import 'hapi'`. hapi has moved to `@hapi/hapi` in the most recent versions.

**Comment by trevor-scheer** [comment]
Hey @plaidman, thanks for bringing this to our attention! Would you be interested in submitting a PR for this? Thanks!

**Comment by abernix** [comment]
Please keep in mind that, while it's okay to rename the package, if the implementations are truly identical, if the version is not exactly the same, we won't be able to accept such a PR without a major breaking release and we plan on phasing out the integration specific implementations — in lieu of a more universal interface — in the next major version of Apollo Server.

**Comment by plaidman** [comment]
@abernix That sounds cool.
@trevor-scheer Unfortunately we're in the process of migrating from hapi to express in our app so I don't have a good testing environment to be sure that any changes I make won't break everything.

**Comment by abernix** [comment]
While I appreciate you surfacing this, and I think we'd still welcome a PR for this, I'm going to close this for now as I'm afraid that releasing this change right now could be more breaking than intended (peer dependencies, and such) and I'd like to make sure that this is well tested.  Truth be told, I think this will be a better match for Apollo Server 3.x.
