### ISSUE TITLE
Deprecate/update README on NPM for graphql-server-koa

### ISSUE THREAD

**Issue by dejan9393** [apollographql/apollo-server#2936]
The current readme on [graphql-server-koa](https://www.npmjs.com/package/graphql-server-koa) states that:

> We are continuing to release matching versions of the package under the old name

However, this is no longer the case as the last publish was over a year ago.
The package should be marked as deprecated and the readme updated

**Comment by abernix** [comment]
😍 Thanks for pointing this out, and sorry for any confusion!  This was the case for some period of time, but it didn't persist after we bumped to 2.x and changed our deployment process.

I've gone ahead and resolved this by updating the `README` and deprecating the packages appropriately.
