### ISSUE TITLE
Documentation Printing only First page - Fix included.

### ISSUE THREAD

**Issue by filucian** [apollographql/apollo-server#2944]
Hi,

I have been trying to wrap my head around Federation for a while now. I have not yet succeeded.

So, I wanted to print the documentation, but only the _**first**_ page prints on Chrome or firefox.

I fixed it using overflow: visible on the following html element.
`#___gatsby>div>div>main `

I am unable to raise a PR for this as I am not familiar with Gatsby.  If you could incorporate this in your print stylesheets, any one looking to print documentation in the future would not face this issue.

**Comment by abernix** [comment]
👋 	Thanks for reporting this!  Our theme lives on another repository and when it's updated, it automatically works its way into this repository's deployment.  Would you consider opening a PR on https://github.com/apollographql/gatsby-theme-apollo/ with the fix?  (You can hopefully test it over there too!)

Thanks again!

**Comment by abernix** [comment]
Also, if you need help wrapping your head around Apollo Federation, you should hop into our [Spectrum.chat's _Federation_ channel](https://spectrum.chat/apollo).  I'm sure someone would be happy to help you out!
