### ISSUE TITLE
mergeSchemas for composable authorization

### ISSUE THREAD

**Issue by Pruxis** [apollographql/apollo-server#2956]
## Goal

Ability to have composable authorization over federated services.
This is the implementation I had in mind, but is blocked due to that the executor seems to block this behaviour.

``` javascript
const createAuthorizer = (schema: GraphQLSchema) => async (
  _: unknown,
  args: GraphQLArgs,
  context: object,
  info: GraphQLResolveInfo & { mergeInfo: MergeInfo }
) => {
  // Do Authorization here.
  const result = await info.mergeInfo.delegateToSchema({
    info,
    args,
    schema,
    context,
    operation: info.operation.operation,
    fieldName: info.fieldName,
  });
  return result;
};

const { schema, executor } = await gateway.load();
const authorizer = createAuthorizer(schema);
const server = new ApolloServer({
    schema: mergeSchemas({
      schemas: [schema],
      resolvers: {
        Query: {
          something: authorizer,
        },
      },
    }),
    executor,
});
```

Is there anyone else that has a working similar implementation. Only thing that seems to work at this point is wrapping the gateway in a separate Apollo Server and calling executeOperation and then deconstructing the results to pass them back, however error handling is brittle with this.

**Comment by Pruxis** [comment]
This implementation is ofcourse working for vanilla merged schema's, once you want to serve several graphql modules to multiple endpoints with different authorization requirements this becomes of so much added value.

**Comment by glasser** [comment]
I'm not exactly sure what this is asking for. Perhaps the mergeSchemas referred to is part of the now-separate graphql-tools project?
