### ISSUE TITLE
chore: Introduce a `apollo-server-types` package.

### ISSUE THREAD

**Issue by abernix** [apollographql/apollo-server#2970]
Currently, there are a number of types which are used across many of the Apollo Server packages which are creating cycles and unnecessarily heavy dependencies on core packages for only their types.

For example, `apollo-engine-reporting` relies on (only) the `GraphQLRequestContext` type from `apollo-server-core`, but `apollo-server-core` relies heavily on `apollo-engine-reporting`.  This creates cycles in the dependency graph that we could avoid by having another package.

Likewise, packages like `apollo-server-plugin-base` currently rely on types from `apollo-server-core`, but because of a desire to maintain loose versioning between the `apollo-server-plugin-base` package and `apollo-server-core` (to maximize plugin compatibility ranges), we are currently _not_ depending on `apollo-server-core` in the way we should be in order to provide dev-time typings. (https://github.com/apollographql/apollo-server/issues/2964).

Some candidates for becoming members of a `apollo-server-types` package might be:

* `GraphQLServiceContext`
* `GraphQLRequest`
* `GraphQLResponse`
* `GraphQLRequestContext`
* `GraphQLExecutionResult`

These are just from a quick glance into `apollo-server-core/src/requestPipelineAPI`, but I'm sure there are more!

**Comment by JacksonKearl** [comment]
`GraphQLService` too, which is the interface Apollo Gateway implements.

**Comment by abernix** [comment]
Good point!  I didn't include that on my first pass for https://github.com/apollographql/apollo-server/issues/2970, but I think adding it makes sense!
