### ISSUE TITLE
Light theme buttons design issue (Playground)

### ISSUE THREAD

**Issue by websolutions-hamburg** [apollographql/apollo-server#2979]
Since **apollo-server-express** version **2.5.1** and **@apollographql/graphql-playground-react** version **1.7.26** the buttons have a black background and font color for the **light theme**. This makes the buttons unrecognizable.

![image](https://user-images.githubusercontent.com/26099903/60584371-601d6700-9d8d-11e9-94cf-ca99376b887a.png)

**Comment by abernix** [comment]
Thanks for reporting this!  Since we don't provide this configuration, this appears that it would need to be fixed upstream in https://github.com/prisma/graphql-playground (which Apollo consumes, albeit through [a fork](https://github.com/apollographql/graphql-playground) that we update regularly).  Do you mind opening an issue (and preferably a PR?) with the repository that provides that integration?

**Comment by websolutions-hamburg** [comment]
I'm not 100% sure, but I think I saw this issue just in the apollo fork. Apollo use:
```
<script src="//cdn.jsdelivr.net/npm/@apollographql/graphql-playground-react@1.7.26/build/static/js/middleware.js"></script>
```
with version **1.7.26**. Prisma use currently version **1.7.20**, if I'm not wrong. And the Prisma version **1.7.20** doesn't have this issue.

With this configuration everything works fine:
```js
playground: {
  cdnUrl: 'https://cdn.jsdelivr.net/npm',
  version: '1.7.20'
}
```
```
<script src="https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.20/build/static/js/middleware.js"></script>
```

**Comment by abernix** [comment]
Ah, so maybe it's already been fixed upstream and we just need to bring it up to date!  I'll check.

**Comment by abernix** [comment]
This should be fixed by https://github.com/apollographql/graphql-playground/pull/18.  I'll publish it into an `alpha` on the 1.7.0 branch momentarily!

**Comment by abernix** [comment]
Thanks for reporting this originally.  Please try out the latest release, `2.7.0-alpha.6`, and report back if this is still a problem!
