### ISSUE TITLE
Authorization header not used for server connection (Playground)

### ISSUE THREAD

**Issue by websolutions-hamburg** [apollographql/apollo-server#2981]
I'm using Traefik as reversy proxy with a basic authentication. It seems, that the playground ignoring (not send) the **Authorization** header for the server connection.

I checked the Chrome Dev Tools and I can't see the **Authorization** header for the server connection in the **Request Headers**:

![image](https://user-images.githubusercontent.com/26099903/60590203-b85b6580-9d9b-11e9-85cc-6686d011f5c9.png)

But if a connection is established, then the **Authorization** header will be send with the request:

![image](https://user-images.githubusercontent.com/26099903/60590249-d4f79d80-9d9b-11e9-90f2-13352f3cec3e.png)

I use:
```
apollo-server-express: 2.5.1
@apollographql/graphql-playground-react: 1.7.26
```

**Comment by abernix** [comment]
I can't seem to reproduce this.  If you're able to update this issue with a runnable reproduction, either on CodeSandbox or on a GitHub repository that can be cloned and started with `npm start`, and demonstrates this as being a bug in Apollo Server, we'd happy to re-open this.  GraphQL Playground essentially a client that just sends the request, so if something isn't showing up in Chrome Dev Tools, that seems like a `graphql-playground` bug, and possibly something that needs to be upstreamed to the [`graphql-playground` repository](https://github.com/prisma/graphql-playground).

**Comment by websolutions-hamburg** [comment]
Thx for you answer @abernix. Now I know that this is not an issue with the playground. It's an issue with the basic authentication, the preflighted request and Traefik together.

This answer https://github.com/containous/traefik/issues/2861#issuecomment-366990075 and this issue https://github.com/containous/traefik/issues/1019 helped me to find a solution for this.

**Comment by fabicsp** [comment]
My conection is established, but also not sends the Auth header. Just in the request playlod.
(Works locally, and with postman)

You can test it out at AWS: http://ec2-54-90-82-252.compute-1.amazonaws.com:5000/playground

**Comment by websolutions-hamburg** [comment]
@fabicsp for me it works on page load request and if I push the execute button.

![image](https://user-images.githubusercontent.com/26099903/61059868-102c4900-a3fa-11e9-9f95-708c6f1850ea.png)

**Comment by fabicsp** [comment]
Its so strange. Should be than some browser issue. 
<img width="745" alt="Auth" src="https://user-images.githubusercontent.com/18398619/61063836-f0e4ea00-a400-11e9-973b-776a23db4efc.png">

But thats also strange, that locally works.

**Comment by websolutions-hamburg** [comment]
I used Chrome version 75.0.3770.100 (64-Bit) on mac.
All I can say now, is disable all plugins and try the incognito mode for testing. Sorry, but I have no more ideas for this issue.

**Comment by fabicsp** [comment]
@websolutions-hamburg  Thanks for your time, 
It was also does not work in incognito.
I have updated chrome version, and now it works :)

**Comment by noilda** [comment]
Any solution to this.
I am using forwardauth and I got the same issue.
I was getting one error every time that the middleware was being activated but not if I was doing the call form Postman. I noticed that if I create another service to handle the OPTIONS method than it is not throwing any error.

**Comment by ivanmirandastavenuiter** [comment]
https://github.com/nestjs/graphql/issues/48#issuecomment-571109336 Worked perfect for me

**Comment by mkwatson** [comment]
Also having the same issue.
* graphql-playground-react@1.7.32
* macos 10.15.6
* chrome 85.0.4183.102
