### ISSUE TITLE
Apollo Gateway 0.6.12 breaks @provides behaviour on list return types

### ISSUE THREAD

**Issue by TheSabby** [apollographql/apollo-server#2982]
The latest version of the `@apollo/gateway` (`0.6.12`) package changed how the `@provides` directive is handled. Before the update, these errors weren't being thrown (`0.6.11` was working fine).

To reproduce: Attempt to run the gateway on top of any services with federation done on a field that returns a list. Example:

```graphql
# service A

type Author @key(fields: "id") {
  id: ID!
  name: String!
}

# service B

extend type Author @key(fields: "id") {
  id: ID! @external
  name: String! @external
}

type Book {
  id: ID!
  authors: [Author!]! @provides(fields: "name")
}
```

The expected behavior: The gateway works fine
 
The actual behaviour: Error is thrown:

```
Book.authors -> uses the @provides directive but `Book.authors` returns `[Author!]!`, which is not an Object type. @provides can only be used on Object types with at least one @key.
```

**Comment by ksaldana1** [comment]
Related issue #2788
