### ISSUE TITLE
Apollo broke again

### ISSUE THREAD

**Issue by wesdse001** [apollographql/apollo-server#2984]
No matching version found for apollo-server-express@^2.6.4

**Comment by abernix** [comment]
Happy to re-open this if you're able to provide more in-depth details about how you've diagnosed this, but the packages definitely exist on npm, as is abundantly clear from [npm's page for `apollo-server-express`](https://www.npmjs.com/package/apollo-server-express?activeTab=versions) and using some of the `npm` command tooling:

```
$ npm view apollo-server-express time | grep -E "'2\.6"
  '2.6.0-alpha.0': '2019-05-13T19:23:15.163Z',
  '2.6.0-alpha.1': '2019-05-22T18:34:40.647Z',
  '2.6.0-alpha.2': '2019-05-22T20:09:04.820Z',
  '2.6.0-alpha.3': '2019-05-22T20:13:33.062Z',
  '2.6.0-alpha.4': '2019-05-23T17:21:34.241Z',
  '2.6.0-alpha.5': '2019-05-23T19:39:50.532Z',
  '2.6.0-alpha.6': '2019-05-24T21:22:27.068Z',
  '2.6.0-alpha.7': '2019-05-27T18:27:53.657Z',
  '2.6.0-alpha.8': '2019-05-28T15:26:20.738Z',
  '2.6.0-alpha.9': '2019-05-30T19:55:21.150Z',
  '2.6.0-rc.0': '2019-05-30T20:30:04.079Z',
  '2.6.0': '2019-05-31T17:59:05.790Z',
  '2.6.1-alpha.0': '2019-05-31T21:41:58.386Z',
  '2.6.1': '2019-05-31T22:02:53.843Z',
  '2.6.2-alpha.0': '2019-06-06T15:27:26.054Z',
  '2.6.2': '2019-06-06T19:48:53.133Z',
  '2.6.3': '2019-06-12T06:09:51.399Z',
  '2.6.4': '2019-06-20T20:50:32.217Z',
  '2.6.5-alpha.0': '2019-06-21T16:51:16.986Z',
  '2.6.5': '2019-06-25T16:20:46.029Z',
  '2.6.6': '2019-06-25T18:10:59.678Z',
  '2.6.7-alpha.0': '2019-06-25T22:08:40.572Z',
  '2.6.7': '2019-06-26T11:51:26.652Z',
```

Care to elaborate on what you've tried or even exactly the command that you've run to generate the above error?  Have you tried from another computer?  Was this from CI?  Was this run in a corporate network?  With a different npm registry?

If you can provide a demonstrable reproduction, or some indication of what you've tried, we can look into it further, but as of right now this could be any number of things unrelated to Apollo itself, and it certainly seems unfair to decidedly say, "Apollo broke again" with the number of potential error fronts.
