### ISSUE TITLE
Subscription request body changes

### ISSUE THREAD

**Issue by herenickname** [apollographql/apollo-server#3023]
I use schema stitching, for some reason Apollo-server changes the body of the subscription request.

I want to understand why this is happening and how to disable it. My second GraphQL server is experiencing difficulties due to this.

Here is an example request that I submit to Apollo-Server:
```
subscription HomeCreatedMatchesSubscription {
  matches(
    where: {
      game_id: {
        _eq: 2
        },
      status: {
        _eq: "CREATED"
      }
    }
  ) {
    map_id
  }
}
```

Here is what another GraphQL server receives after passing a request through the apollo-server:
![image](https://user-images.githubusercontent.com/1989823/60994212-bde71b80-a358-11e9-9766-ba0a970d9b5c.png)

Apollo-Server transfers variables from the request body to `payload.variables` and changes the structure of the request as a whole.

**Comment by ekifox** [comment]
@martijnwalraven @abernix

**Comment by glasser** [comment]
Direct subscriptions integration was removed from Apollo Server in v3 last year.
