### ISSUE TITLE
Formatting problem in docs

### ISSUE THREAD

**Issue by gschmidt** [apollographql/apollo-server#3037]
In the docs as deployed here:
https://www.apollographql.com/docs/apollo-server/api/apollo-server/

There are some issues (see below):
1) Run-on sentence (period needed after "http server"?)
2) Bottom link (to node's server docs) does not render correctly

![image](https://user-images.githubusercontent.com/143488/61190074-54faee80-a64b-11e9-810e-1b81761e4941.png)

**Comment by gschmidt** [comment]
Also, "method" should probably be plural and it should probably be something like "options" rather than "methods"?

**Comment by abernix** [comment]
Thanks, @gschmidt.  Hopefully improved in various ways by https://github.com/apollographql/apollo-server/commit/8546d330826b6c7c2ea36a75ca8ac324a2d0968c.
