### ISSUE TITLE
Cannot read property 'bind' of undefined while using createTestClient in apollo-server-express

### ISSUE THREAD

**Issue by kartikjain26** [apollographql/apollo-server#3055]
Bug - Cannot read property 'bind' of undefined while using createTestClient

Dependencies
```
"apollo-datasource-rest": "0.6.0",
"apollo-server-express": "2.7.0",
"express": "4.17.1",
"apollo-server-testing": "2.7.0"
```

Expected behaviour - Expected create test client to create a query function.

Actual behaviour - When using standalone apollo-server, this problem did not occur. However, after upgrading to apollo-server-express: 2.7.0, I am getting the error - 
`TypeError: Cannot read property 'bind' of undefined` at
`node_modules/apollo-server-testing/dist/createTestClient.js:14:54`
 `const executeOperation = server.executeOperation.bind(server);`

Console.log (server.executeOperation) gives undefined.

**Comment by kartikjain26** [comment]
@abernix

**Comment by kartikjain26** [comment]
Apologies for creating this issue. I was supplying express app instance to createTestClient whereas I had to provide graphql server instance to it.

**Comment by masiamj** [comment]
@kartikjain26 Any updates on this? Did you figure out the issue?

**Comment by kartikjain26** [comment]
@masiamj  Used supertest for querying the server rather than createTestClient (this requires the graphql app instance). Since I was using apollo-server-express, I used supertest which we were already using in other tests.
