### ISSUE TITLE
Unable to set custom headers on errors

### ISSUE THREAD

**Issue by ustun** [apollographql/apollo-server#3062]
The headers for errors seem to be fixed, one cannot set any headers for errors via any other means (extensions etc).

See https://github.com/apollographql/apollo-server/blob/f51aa07fafbaf946f89b8f781e6b69c880f6360b/packages/apollo-server-core/src/runHttpQuery.ts#L79

The use case is explained in this issue: https://github.com/apollographql/apollo-server/issues/3061

Note that I was able to send response headers for successful responses there, but not for errors.

**Comment by abernix** [comment]
Please try this with the new implementation provided in https://github.com/apollographql/apollo-server/pull/2719 and let us know if it's not possible.

Roughly, I think you'd want this:

```ts
import { ApolloServer } from 'apollo-server';
const server = new ApolloServer({
  typeDefs,
  resolvers,
  plugins: [
    {
      requestDidStart() {
        return {
          didEncounterErrors({ response, errors }) {
            // You can inspect `errors`, if you'd like!
            response.http.headers.set('Your-Own-Header', 'SEVERITY!');
          }
        }
      },
    },
  ],
});
```

**Comment by ustun** [comment]
Hmm, it seems that there are different categories of errors. 

I was already catching errors in resolvers and the new plugin also worked for errors in resolvers, however unfortunately that didn't do the trick for parsing or validation errors, e.g. when we send a malformed query from the client. 

When a validation error is detected (you ask for a field that is not in typedef), didEncounterErrors function is executed, however that response with headers is ignored, at least for the `apollo-server-express`.

**Comment by PrimarchAlpharius** [comment]
In my case, the error is picked up by didEncounterErrors, but setting of the header simply doesn't work.

If I set the header in formatResponse the header is set correctly, but this isn't a solution for me because the error isn't picked up by formatResponse.
And formatError doesnt have the context available to it so I can't set the header there either.
Any ideas?

**Comment by PrimarchAlpharius** [comment]
Well I found a workaround for my particular use-case (using willSendResponse and requestContext.metrics.persistedQueryHit), however I think this is really something that needs fixing.

**Comment by msdinit** [comment]
For anyone trying to resolve this, the problem seems to be that for some errors (namely APQ errors), apollo server forces some pre-defined headers. A temporary workaround is to manually throw an HttpQueryError with your own headers:
```
didEncounterErrors ({ errors, debug }) {
    if (hasPersistedQueryError(errors)) {
        throw new HttpQueryError(
            200,
            JSON.stringify({ errors: formatApolloErrors(errors, { debug: debug }) }),
            true,
            { 'Cache-Control': 'max-age=0, stale-while-revalidate' }
        )
    }
}
```
