### ISSUE TITLE
Updating Playground DOM through external Javascript doesn't update Playground

### ISSUE THREAD

**Issue by pratiknikam** [apollographql/apollo-server#3071]
**Issue:** I've created a chrome extension to replace "Authorization" header in playground with new auth token every 1hr so that developer don't need to copy paste token when previous once expires.

I'm using vanilla Javascript to update HTML DOM but for some reason Playground still says `Server cannot be reached` even though new token is a valid one.

It works when I manually copy paste a token in HTTP Headers tab.

**Versions:**

`apollo-server-express`: `v2.2.4`
`graphql-playground-html`: `v1.6.24`

**Expected behavior:** When we replace bearer token, `Server cannot be reached` should go away and I should be able to make subsequent calls.

**Javascript code to update DOM:** You can copy paste in your running playground and can easily reproduce issue.

```
document.querySelector('div:nth-child(2) > .CodeMirror-line .cm-string:nth-child(5)').innerHTML = "<new-auth-token>"
``` 

**HTTP Headers in Playground:**

```
{
  "Authorization": "<old-auth-token>"
}
```

When I hit play even though error `Server cannot be reached` persists, I get following error. I can use new bearer token in a new tab without any issues though and was able to parse successfully at https://jwt.io/

```
Could not parse JWT header. Error: SyntaxError: Unexpected token \b in JSON at position 12
```

- I did inspect playground DOM and there isn't anything suspicious there.
- I think it has to do something with the way Playground is built in React so it has to do something with actions, triggers etc.,?

**Comment by abernix** [comment]
Thanks for opening this, and thanks for taking the time to put together a Chrome extension to help with this pain point you've identified.  Unfortunately, I don't think that this repository is the right place for this issue, nor the right place to find the answer.

While we do provide `graphql-playground`, it's entirely almost just a direct fork of the [`prisma/graphql-playground`](https://github.com/prisma/graphql-playground) repository, so it's possible that if you opened an issue over there you might find some guidance, but I'll forewarn that I think (as you note above) that you're actually being held up by something much more nuanced: updating the actual internal React context from external code.  

JavaScript being as dynamic as it is, I'm suspect that you'll find a way to do what you need to do, but I'm almost certain that it won't be as straightforward as simply modifying the DOM.

**Comment by pratiknikam** [comment]
I really appreciate your honest response. Thanks for pointing me to right project.
