### ISSUE TITLE
BadRequestError when upload file with cookies

### ISSUE THREAD

**Issue by JMoldes** [apollographql/apollo-server#3074]
When I use `apollo-upload-client` with express and redis with cookie session, I can't upload files.

The message error is:

```
BadRequestError: Missing multipart field ‘operations’ (https://github.com/jaydenseric/graphql-multipart-request-spec).
```

I have created a fork of the example project to simulate the problem, you can see it in:

[https://github.com/JMoldes/apollo-upload-examples/tree/error-with-express-redis](https://github.com/JMoldes/apollo-upload-examples/tree/error-with-express-redis)

The changes that I have made are:

* Install the modules `express`, `apollo-server-express`, `connect-redis-sessions`  and `cookie-parser`
* Modify `server.mjs` to use express, and use the middleware connect-redis-sessions, and create a test session when upload the first file
* Modify `_app.js` for add `credentials: 'include' `  to **createUploadlink**

When I execute `npm run dev' for api and app, (previously I have to install redis ...), the first file I upload is ok, because I have not sent any cookies yet,

But after the first file is sent, te api sent a cookie to client, and when I upload the sencod file the Api show the next message:

```
BadRequestError: Missing multipart field ‘operations’ (https://github.com/jaydenseric/graphql-multipart-request-spec).
```

If I comment the line 22: `app.use(fnCRS)`  the file upload ok.

![image](https://user-images.githubusercontent.com/4438532/61524099-ff8d5b80-aa15-11e9-856a-e00197a05b49.png)

If I inspect the outgoing network request body, `operations` is present. 

![image](https://user-images.githubusercontent.com/4438532/61611959-81bb9100-ac5d-11e9-96f8-71586020d401.png)

The server works fine for all other cases in my app. 

Why can not I upload files with express and redis using session cookies ?

the version of the `apollo-server-express` is  2.7.0

**Comment by abernix** [comment]
I appreciate the thorough details that you've provided here, but the upload mechanism is entirely powered by a community package called [`graphql-uploads`](https://github.com/jaydenseric/graphql-upload) that is not managed within this repository, though it is consumed by Apollo Server.  Further, the upload examples repository that you forked is also part of that `graphql-upload` package and in thanks to the community that developed it.

Put another way, I think you'll need to open this issue with either of those repositories to get help with the matter.

**Comment by gaspan** [comment]
i have this trouble with `apollo-server` and `graphql-uploads` . when i use   `graphql-uploads`  for scalar and `graphql-yoga` for server it worked, but when i use `graphql-uploads`   with  `apollo-server` it throw error  :

```
BadRequestError: Missing multipart field ‘operations’ (https://github.com/jaydenseric/graphql-multipart-request-spec).

```
i use "apollo-server": "2.9.16"

i hope you fix this, i interest to use apollo server. thanks.
