### ISSUE TITLE
Support different schemas depending on context

### ISSUE THREAD

**Issue by wmertens** [apollographql/apollo-server#3114]
For security, it would be nice if depending on the login state, a different schema it used.

So, if you are not logged in, only the open queries and login mutation are available, and if you're logged in but not an admin, you don't have the admin-level mutations.

Not having queries/mutations available in the schema is more secure than making sure in each resolver to apply the correct access restrictions, because:
- It is easy to verify, just look at the schema in GraphiQL
- It is harder for attackers to find out what mutations to target
- It groups course-grained access control in one place or at least provides a canonical way to implement it, minimizing mistakes

**Comment by abernix** [comment]
Duplicate of https://github.com/apollographql/apollo-server/issues/2010, I believe? Happy to re-open if you disagree, but I think adding this over there with a :+1: would be most beneficial!
