### ISSUE TITLE
cacheControl / apollo-server-cache-redis not triggered

### ISSUE THREAD

**Issue by nicolasg-playster** [apollographql/apollo-server#3137]
```
"apollo-datasource-rest": "0.6.1",
"apollo-server-cache-redis": "1.1.1",
"apollo-server-express": "2.8.1"
```

I'm unable to get caching to work + cacheControl is not available in the resolvers. No keys are ever created in Redis either.

I can see that a `SELECT` and `INFO` are performed at start and a rare `MGET` operation for some requests.

### Server Initialization
```js
const { ApolloServer } = require('apollo-server-express')
const { RedisCache } = require('apollo-server-cache-redis')

new ApolloServer({
  typeDefs,
  resolvers,
  schemaDirectives,
  cacheControl: {
    defaultMaxAge: 60
  },
  cache: new RedisCache({ host: '...' }),
  context: ({ req, res }) => ({ req, res }),
  dataSources: () => ({
    exampleAPI: new ExampleAPI()
  })
})
```

### Schema
```graphql
type Query {
  search(
    firstName: String
    lastName: String
  ): [UserSearchResult] @cacheControl(maxAge: 120)
}

type UserSearchResult @cacheControl(maxAge: 240) {
  id: Int!
  email: String!
  firstName: String
  lastName: String
}
```

### Resolver
```js
async search (_source, args, { cacheControl, dataSources }) {
  // cacheControl.setCacheHint({ maxAge: 120, scope: 'PUBLIC' })
  return dataSources.exampleAPI.searchMember(args)
}
```
In the above code, `cacheControl` is always `undefined`. 

No keys are ever created in Redis and the REST endpoint is always called on every request.

I closely followed the docs [[1]](https://www.apollographql.com/docs/apollo-server/features/data-sources/#using-memcachedredis-as-a-cache-storage-backend) [[2]](https://www.apollographql.com/docs/apollo-server/features/caching/#adding-cache-hints-statically-in-your-schema) but I can't get anything to work. Is something broken or am I missing something obvious?

**Comment by rizowski** [comment]
Isn't `cacheControl` on the fourth parameter of a resolver? Looks like you are trying to destructure it from the context.
https://www.apollographql.com/docs/apollo-server/features/caching/#adding-cache-hints-dynamically-in-your-resolvers

**Comment by abernix** [comment]
See @rizowski's suggestion above. 😄 

(Thank you, @rizowski!)

**Comment by manojHDwork** [comment]
> Isn't `cacheControl` on the fourth parameter of a resolver? Looks like you are trying to destructure it from the context.
> https://www.apollographql.com/docs/apollo-server/features/caching/#adding-cache-hints-dynamically-in-your-resolvers



> ```
> "apollo-datasource-rest": "0.6.1",
> "apollo-server-cache-redis": "1.1.1",
> "apollo-server-express": "2.8.1"
> ```
> 
> I'm unable to get caching to work + cacheControl is not available in the resolvers. No keys are ever created in Redis either.
> 
> I can see that a `SELECT` and `INFO` are performed at start and a rare `MGET` operation for some requests.
> 
> ### Server Initialization
> ```js
> const { ApolloServer } = require('apollo-server-express')
> const { RedisCache } = require('apollo-server-cache-redis')
> 
> new ApolloServer({
>   typeDefs,
>   resolvers,
>   schemaDirectives,
>   cacheControl: {
>     defaultMaxAge: 60
>   },
>   cache: new RedisCache({ host: '...' }),
>   context: ({ req, res }) => ({ req, res }),
>   dataSources: () => ({
>     exampleAPI: new ExampleAPI()
>   })
> })
> ```
> 
> ### Schema
> ```graphql
> type Query {
>   search(
>     firstName: String
>     lastName: String
>   ): [UserSearchResult] @cacheControl(maxAge: 120)
> }
> 
> type UserSearchResult @cacheControl(maxAge: 240) {
>   id: Int!
>   email: String!
>   firstName: String
>   lastName: String
> }
> ```
> 
> ### Resolver
> ```js
> async search (_source, args, { cacheControl, dataSources }) {
>   // cacheControl.setCacheHint({ maxAge: 120, scope: 'PUBLIC' })
>   return dataSources.exampleAPI.searchMember(args)
> }
> ```
> 
> In the above code, `cacheControl` is always `undefined`.
> 
> No keys are ever created in Redis and the REST endpoint is always called on every request.
> 
> I closely followed the docs [[1]](https://www.apollographql.com/docs/apollo-server/features/data-sources/#using-memcachedredis-as-a-cache-storage-backend) [[2]](https://www.apollographql.com/docs/apollo-server/features/caching/#adding-cache-hints-statically-in-your-schema) but I can't get anything to work. Is something broken or am I missing something obvious?

@nicolasg-playster is it work for you because i'm also facing same issue ?
