### ISSUE TITLE
upload large file causing "Error: Network error: Failed to fetch" 

### ISSUE THREAD

**Issue by Zyc0017** [apollographql/apollo-server#3152]
I'm using apollo-server-koa, it works fine with small files, but when I tried to upload a 20mb pdf, it just throws a network error.  i'm guessing maybe there is a size limit?  but I didn't find any documentation about this topic.

**Comment by Pikachews** [comment]
Same issue here, but strangely only happens on my remote server; when running locally, it seems to work fine. Trying to upload ~25mb zip file.

**Comment by Pikachews** [comment]
Actually, it seems to fail even with a 1mb file. But smaller files seem to work. The limits set on the server are beyond that, though.

**Comment by Pikachews** [comment]
Okay, it was my mistake. It seems like it was a restriction of nginx; by default, it limits you to 1 mb max request size.

**Comment by abernix** [comment]
The default body size limit for `koa-bodyparser`, the underlying body parsing implementation used within `apollo-server-koa` is not very high, so if your uploads are larger, you'll likely need to tweak them.  I think the relevant 

You can set whatever is appropriate for your server using the `bodyParserConfig` attribute to pass appropriate [`bodyParserOptions`](https://github.com/koajs/bodyparser#options) to Apollo Server's `applyMiddleware`:

```
server.applyMiddleware({
  app: app,
  bodyParserConfig: {
    // Settings from https://github.com/koajs/bodyparser#options
  },
});
```
