### ISSUE TITLE
Support for Asp.net core

### ISSUE THREAD

**Issue by aammfe** [apollographql/apollo-server#3162]
💡 Feature request

**Comment by abernix** [comment]
It's unlikely that we will embark on building completely different implementations in different languages within any short-term timeline, but this repository will always be the home for the TypeScript/JavaScript version of Apollo Server.

Either way, I think it's reasonable to track the demand for such a request _somewhere_.  That said, please open this request in https://github.com/apollographql/apollo-feature-requests/, but please provide a lot more information describing what you're looking for, in particular.
