### ISSUE TITLE
Add resolver info to error objects

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-server#3170]
I'd like to be able to track more information about errors that occur inside resolvers. With `didEncounterErrors` I can access the context and request, but I'd also like to know where in the document the field that's being resolved is, and the below `obj` and `args` params. I can do that with the below pattern of wrapping all resolvers in a `try...catch`, but am thinking it might be nice for Apollo to do it automatically.

```js
function resolver(obj, args, context, info) {
  try {
    // logic
  } catch (e) {
    e.resolverInfo = { obj, args, context, info }
    throw e
  }
}

const apollo = new ApolloServer({
  ...
  formatError: e => {
    reportError({
      error: e,
      metadata: e.resolverInfo
    })
    return e
  }
})
```

**Comment by falkenhawk** [comment]
> With `didEncounterErrors` I can access the context and request

How do you do it? There is no context or request data in the array of errors passed to `didEncouterErrors` hook, if I am not mistaken.

**Comment by lorensr** [comment]
Looks like there are two `didEncounterErrors`. The plugin one gets context:

https://www.apollographql.com/docs/apollo-server/integrations/plugins/#didencountererrors
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-plugin-base/src/index.ts#L44

And this one gets an error array:

https://github.com/apollographql/apollo-server/blob/master/packages/graphql-extensions/src/index.ts#L49

**Comment by glasser** [comment]
GraphQLErrors thrown in fields do have `nodes`, `source`, `positions`, and `path` properties. 

Adding references to the entire set of arguments and info for every error thrown by a resolver seems like a lot. You'd have to be careful that this doesn't end up in the part of an error that gets serialized in responses, and it could lead to unnecessary retention of memory.

In general Apollo Server isn't very opinionated about what happens inside your resolvers.  As a convenience you can specify `resolvers` to the constructor, which is implemented by the `graphql-tools` makeExecutableSchema function, but in general you can construct your schema and set up resolvers whatever way you want.  This seems like a better fit for one of the schema transformation tools in `graphql-tools`, or `graphql-middleware` or something.
