### ISSUE TITLE
Apollo gateway does not set Cache-Control header. 

### ISSUE THREAD

**Issue by kvzhkv** [apollographql/apollo-server#3181]
### Package versions
@apollo/gateway:0.8.2 + apollo-server:2.8.1

### Expected behavior
Gateway server should set Cache-Control header in consideration of Cache-Control headers & cacheControl hints in extensions field of responses from federated services
It is highly important for correct caching on CDNs. 

### Current behavior
Cache-Control is not set. I've tried all possible settings of `cacheControl` in ApolloServer constructor. Even if I set `defaultMaxAge` there is no cache-control header.

Setting `cacheControl: true` gives me this in response:
```
{
    "data": {
        ...
    },
    "extensions": {
        "cacheControl": {
            "version": 1,
            "hints": []
        }
    }
}
```
So empty hints, but `hints` array is not empty in response from federated service.
Anyway, for using CDNs that is more important to set header, then merge `hints` from federated services.

**Comment by abernix** [comment]
Thanks for reporting this! This duplicates #3194, which I realize was opened later, but has a bit more traction now, along with a reproduction.
