### ISSUE TITLE
Weird union type behavior breaks queries caching

### ISSUE THREAD

**Issue by fernandobandeira** [apollographql/apollo-server#3192]
First off, this "bug" may belong to the apollo-client itself or maybe to both libraries.

We found a really strange behavior while using unions across our system, we're using apollo federation but it shouldn't matter in this case.

Here's a simplified version of the schema we're using

```graphql
union TransactionDesignationEntity = Organization | Campaign | Ticket | Event

type TransactionDesignation @key(fields: "id") {
  id: ID!
  type: String!
  amount: Float!
  netAmount: Float
  designation: TransactionDesignationEntity
}
```

Now consider the following parts of two queries, one is made in the admin dashboard listings, the other is in the donor profile:

```graphql
transactions {
  items {
    id
    amount
    designations {
      id
      type
      designation {
        ... on Event {
          id
          name
          slug
        }
        ... on Campaign {
          id
          title
          slug
        }
        ... on Organization {
          id
          name
          slug
        }
      }
    }
  }
}

transactions {
  items {
    id
    amount
    designations {
      id
      type
      amount
      designation {
        ... on Event {
          id
          name
        }
        ... on Ticket {
          id
          name
        }
      }
    }
  }
}
```

### Current server behavior
Here's the problem since the client adds __typename to the designation type when making the query, the first query will also return the Ticket record. containing only the __typename.

### Expected server behavior
Maybe the server shouldn't do that since you didn't select the ticket at all?

### Current client behavior
As you can imagine, the first query will not have the ticket id, while the second one will have it, the problem arises when we navigate from the dashboard page to the donor profile page directly or vice versa, an error is thrown because of the conflicting type Ticket, the queries have different names but I think that since it's the same transaction and designation it ends up using the same cache storage and breaks the second query that is made.

### Expected client behavior
It shouldn't break the query just because it fails writing to the cache, also, we've defined the possible types in the fragmentMatcher so maybe it shouldn't select the __typename for the entire designation, but just for the selected types?

#### Workaround
As a workaround for now we'll be selecting all of the possible designation types and their ids everytime and maybe migrate this to an interface but since it's quite tricky to find the cause of this and it may occur with other people I'm posting here so you can either change the behavior or document it.

**Comment by glasser** [comment]
It sounds like you were asking for GraphQL union queries to work like this:

schema:
```
type A { a: ID }
type B { b: ID }
union U = A | B
type Query { u: [U] }
```

operation:
```
{
  u {
    ... on A { a }
   }
}
```

It sounds like your assumption would be that if `u`'s resolver would return a list of items, some of which are As and some of which are Bs, the fact that you are only applying an inline fragment to `A` should in fact remove the `B`s from the list. But that's just not how GraphQL unions or lists work. If you'd like your field to only return items of a particular type, you should write the resolver to do that; there's no magic "filter a list to only contain items where there's more information requested about them".
