### ISSUE TITLE
Apollo Core: TypeError: response.http.headers is not iterable

### ISSUE THREAD

**Issue by stevenolay** [apollographql/apollo-server#3205]
Package: apollo-server-core@2.9.0
Expected Behavior: Well I'm not sure what to expect. 

Actual Behavior: These lines in apollo-server-core are stopping my application from returning payloads to the client. 

https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/runHttpQuery.ts#L309-L313

I receive the following stacktrace: 
```
"TypeError: response.http.headers is not iterable",
              "    at /Users/<ommited>/Documents/<ommited>/<ommitted>/node_modules/apollo-server-core/src/runHttpQuery.ts:311:49",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (/Users/<ommited>/Documents/<ommited>/<ommitted>/node_modules/apollo-server-core/dist/runHttpQuery.js:4:58)",
              "    at process._tickCallback (internal/process/next_tick.js:68:7)"
```
When I comment out those 4 lines of code everything works normally. 

I have logged what the headers look like at that point and they are the following:
Headers { _headers: {} }

Seems to be some class instance of headers however, the way that the core package tries to iterate over the headers causes a type error to be thrown. 

I am using apollo-server-express. Any hints as to why its unable to interface with the headers correctly? 

This is the minimum code example needed to reproduce:
```
const app = express();
import { ApolloServer } from 'apollo-server-express';
const server = new ApolloServer({
  schema: schema,
  formatError: (err) =>{
    console.log(err);
    return err;
  },
  context: async ({ req, res, ...rest }, ...other) => {
    return {
      hi: 5
    }
  },
  introspection: true,
  tracing: false,
  cacheControl: false
});

server.applyMiddleware({ app, path: '/api', cors: corsOptions });
const httpServer = createServer(app);
httpServer.listen(PORT, () => console.log('GraphQL API running at http://localhost:3001/api'));
```

**Comment by stevenolay** [comment]
This was resolved. It was an issue with my .tsconfig. My base path wasn't correct and seems it had hidden side effects. 

Im sorry this solution won't help everybody.

**Comment by duxtinto** [comment]
Hi @stevenolay ! Good evening!

I'm experiencing exactly the same issue as you did, but whenever using an instance of the apollo server from inside a lambda function.

> It was an issue with my .tsconfig. My base path wasn't correct and seems it had hidden side effects.

Could you please elaborate a bit more about the .tsconfig solution that fixed it for you?

Thank you very much.

**Comment by stevenolay** [comment]
@duxtinto 

Hey, how are you doing. I'm not sure what it could be in your specific case but in my case my baseUrl in my tsconfig was incorrect.

Which was interesting because my project compiled just fine if i went in the node modules folder and commented out the part where it was getting the "response.http.headers " is not iterable from.

But as soon as the base url was corrected... the issue magically disappeared.  I know this was the issue because I pair programmed with a buddy of mine and we just kept making minor edits to the tsconfig until we could get something to work. To this day I can still reproduce the error just by changing the baseUrl. 

** Shrugs **

Sorry if this isn't of any help...

**Comment by duxtinto** [comment]
Hi @stevenolay ! 

Thank you very much for your help... probably it was the same issue for me... but as serverless+webpack is handling all the Typescript configuration for me under the cover, after fixing it, I'm not sure which part was responsible for the issue :sweat_smile: ... I really appreciate your help :). 

Thank you very much, and have a nice day.

**Comment by sportnak** [comment]
To provide a *little* more clarity, this worked for me by changing my baseUrl from `.` to `./` (mildly infuriating, but c'est la vie)
