### ISSUE TITLE
Property 'connection' does not exist on type 'ExpressContext'

### ISSUE THREAD

**Issue by dauledk** [apollographql/apollo-server#3208]
I am trying to follow [this guide](https://www.apollographql.com/docs/apollo-server/features/subscriptions/#middleware), on setting up subscriptions with `apollo-server-express@2.9.0`, but the middleware connection check is giving a typescript problem:

**Property 'connection' does not exist on type 'ExpressContext'**

The code snippet:
```typescript
const server = new ApolloServer({
  schema,
  context: async ({ req, connection }) => { // Typescript error here
    if (connection) {
      // check connection for metadata
      return connection.context;
    } else {
      // check from req
      const token = req.headers.authorization || "";

      return { token };
    }
  },
});
```

Currently, I am doing this workaround: `const { req, connection } = v as any;`

**Comment by abernix** [comment]
I believe this was meant to be be fixed via https://github.com/apollographql/apollo-server/pull/2959.  Is it possible you have multiple versions of `apollo-server-express` in your project? (You can run `npm ls apollo-server-express` or `yarn ls apollo-server-express` to find the answer).

@stefanholzapfel @Siyfion Did you find that the typing problem with the `connection` property was resolved after #2959?

**Comment by abernix** [comment]
@dauledk Also, whether or not it's the exact steps in the guide, including a runnable reproduction would be helpful.

**Comment by dauledk** [comment]
Running `npm ls apollo-server-express` only gave `2.9.0`. Looking around [here in the github repo](https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-express/src), are we not missing `connection` from this line [here](https://github.com/apollographql/apollo-server/blob/4cb2d9110c4d2bd4c0314cd324221cda02b5dfcd/packages/apollo-server-express/src/expressApollo.ts#L10)?

**Comment by stefanholzapfel** [comment]
@abernix @dauledk Just upgraded from 2.8.1 to 2.9.0 without any problems. Using context like this:
`context: async ({ req, connection }) => {}`

**Comment by dauledk** [comment]
After closing VS code and opening again, the error is gone. Thanks for the help - and sorry for the inconvenience 😅

**Comment by abernix** [comment]
@dauledk No inconvenience; thanks for following up! (And thank you @stefanholzapfel for jumping in!)

**Comment by MichaelHindley** [comment]
@abernix when working with Subscriptions, you get an ExpressContext that has `connection` but no `req` or `res`. Shouldn't they hence be nullable?

![image](https://user-images.githubusercontent.com/1016639/72820176-cbb61b80-3c6e-11ea-8f81-22d86265d360.png)

**Comment by rashidRizvi98** [comment]
> After closing VS code and opening again, the error is gone. Thanks for the help - and sorry for the inconvenithis

> After closing VS code and opening again, the error is gone. Thanks for the help - and sorry for the inconvenience 😅

this worked for me too! 😅
