### ISSUE TITLE
Is there logging utility that can record how many restful api calls Apollo-datasource-rest made?

### ISSUE THREAD

**Issue by AlexSun98** [apollographql/apollo-server#3212]

**Comment by AlexSun98** [comment]
I’d like to log and capture network data (restful api calls) from graphql api. Fiddle and graphql-network seems doesn’t help much. Any ideas? Thanks

**Comment by delianides** [comment]
@AlexSun98 depending on what metrics you wanted to capture you could override the `didReceiveResponse` [method](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts#L95). It's passed the request and the response so you can do quite a bit.

**Comment by AlexSun98** [comment]
Thanks Deliandes. It solves my problem. I m going to close this case.
