### ISSUE TITLE
Combine apollo lambda and apollo express

### ISSUE THREAD

**Issue by GerbenRampaart** [apollographql/apollo-server#3249]
What is the best approach to have an apollo server in lambda but also expose express routes?

When I use apollo server express I don't get the createHandler and when I use apollo server express I can't add the express routes.

**Comment by abernix** [comment]
This isn't really a concern that's unique to Apollo Server, so I suspect you'll want to adopt something like the suggestions provided by AWS themselves, where you'd use the `apollo-server-express` integration combined with their instructions:

https://github.com/awslabs/aws-serverless-express

**Comment by abernix** [comment]
Also, if you have any other questions or you're still having problems with this, feel free to ask in the [Apollo community on Spectrum.chat](https://spectrum.chat/apollo), but this doesn't seem to be an actual bug, more a question of how to use an express middleware pattern in AWS Lambda.

**Comment by GerbenRampaart** [comment]
AWS-serverless-express was exactly what I was doing now. Using the apollo-server-lambda createHandler is much cleaner imho. Can't it be a feature where both are supported?
