### ISSUE TITLE
Why does the gateway expand interface fragment into multiple implementations fragments? (federation)

### ISSUE THREAD

**Issue by vitramir** [apollographql/apollo-server#3253]
For example we have SDL with interface and multiple implementations:

```GraphQL
interface Node{
    id: ID!
}

type Brand implements Node{
    id: ID!
    title: String!
}

type Department implements Node{
    id: ID!
    title: String!
}

type Query{
    brand: Brand
}
```

Then query
```GraphQL
{
    brand {
        ... on Node {
            id
        }
    }
}
```

will be transformed into

```GraphQL
Fetch(service: "data") {
    {
      brands {
        ... on Brand {
          id
        }
        ... on Department {
          id
        }
    }
}
```

So, the result will be error "Fragment cannot be spread here as objects of type \"Brand\" can never be of type \"Department\"."

Why don't we pass fragments as is?

**Comment by vitramir** [comment]
Ok, I think I can answer the question myself. We should do it because we don't want to define all interfaces in every service.

**Comment by trevor-scheer** [comment]
@vitramir my apologies for not responding to your question. This is actually a bug within query planner that we'll be working to fix. The query is fine, and the query planner should just remove the type condition `Node` since every `Brand` is also a `Node`. I currently have a simple reproduction and am building one that's a bit more complex with nesting. @martijnwalraven and I will be working on this Monday!

**Comment by vitramir** [comment]
@trevor-scheer Check my PR, please.
I store all parent types from fragments (and nested fragments too), find intersection of implementations and expand fragment into possible types only.

**Comment by vitramir** [comment]
My team found one more case. Interface inside interface.

```GraphQL
interface Item{
    id: ID!
    content: Content
}

enum ContentType{
    text
    number
}

interface Content{
    type: ContentType
}

type Text implements Content{
     type: ContentType
     value: String
}

type Number implements Content{
     type: ContentType
     value: Int
}

type Brand implements Item{
    id: ID!
    content: Text!
}

type Department implements Item{
    id: ID!
    content: Number!
}

type Query{
    item: Item
}
``` 

Then query
```GraphQL
{
  item {
    content {
      type
    }
  }
}
```

will be transformed into

```GraphQL
Fetch(service: "data") {
    {
      item {
        ... on Brand {
           content {
              ... on Text {
                type
              }
              ... on Number {
                type
              }
           }
        }
        ... on Department {
           content {
              ... on Text {
                type
              }
              ... on Number {
                type
              }
           }
        }
    }
}
```

But Department's content can't be of type Text and Brand's content can't be of type Number

**Comment by vitramir** [comment]
Looks like I have fixed this in last commit

**Comment by rtymchyk** [comment]
I don't follow this conversation - is this still a TODO @trevor-scheer?

**Comment by rtymchyk** [comment]
@vitramir @Pruxis what is the fix? Would be great if you could share...

**Comment by Pruxis** [comment]
For me bumping to the latest version solved my issues.

**Comment by vitramir** [comment]
@rtymchyk did you check the PR https://github.com/apollographql/apollo-server/pull/3257

**Comment by rtymchyk** [comment]
@vitramir Ah ok, my bad, got confused thinking there was an app-specific fix. The PR makes sense and fixes the problem in our use case.
