### ISSUE TITLE
Accessing server context in RemoteGraphQLDataSource

### ISSUE THREAD

**Issue by christophior** [apollographql/apollo-server#3256]
package versions
- `@apollo/federation@0.8.0`
- `@apollo/gateway@0.8.1`
- `apollo-server-lambda@2.8.1`

Not sure if there's something I've missed but I'm attempting to build our context in our server and have this context accessible in `willSendRequest` in our `RemoteGraphQLSource`.

Example snippet:
```
import { ApolloServer } from 'apollo-server-lambda';
import { ApolloGateway, RemoteGraphQLDataSource } from '@apollo/gateway';

const gateway = new ApolloGateway({
  serviceList: [...],
  buildService: ({ name, url }) =>
    new RemoteGraphQLDataSource({
      url,
      willSendRequest({ request, context }) {
        // expect context from below
        console.log(context);
      },
    }),
});

const server = new ApolloServer({
  gateway,
  // build context using example
  context: ({ event }) => ({
    example: event.example
  }),
  ...
});
```

What we're expecting is for the context which has the `example` attribute to be available in the `willSendRequest` function that we have in our `RemoteGraphQLDataSource` so that we can use that info in our request.

Currently even after setting our context in our server (or even hard coding it to an object), `context` in `willSendRequest` is always an empty object.

**Comment by trevor-scheer** [comment]
Hey @christophior, thanks for submitting an issue! I'm tempted to say (based on the empty object) that this is a result of a change we implemented recently in #3120.

I believe what you're seeing is the data source _first_ firing the introspection query (which has an empty `context` object). Subsequent requests should have the expected object in `context`.

If I'm mistaken, would you please provide me with a runnable reproduction?

**Comment by MichelDiz** [comment]
I'm going back to using Apollo and wanting to test the federation. So far so good, but I'm having a bad time with the idea of auth between services in federation.

My services have it self contained a way of checking JWT tokens. So I need to pass the tokens across the services.

My question, server context would be the way? my context is empty tho. I can see it only in the gateway instance. Not in the resolvers from remote servers.

ref: https://www.apollographql.com/docs/apollo-server/security/authentication/

**Comment by trevor-scheer** [comment]
Closing as stale / probably resolved. For anyone that ends up here with the same problem, this is a behavior we're looking to improve upon in the future.
