### ISSUE TITLE
i18n on documentation

### ISSUE THREAD

**Issue by andresg747** [apollographql/apollo-server#3265]
Hi.
Is there any plan on translating the docs?

If not, I'm available to help translating the docs, at least in **spanish**. 
I love apollo and I want to see more people using it.
Also, I think Apollo is mature and yet simple enough for newcomers, even for those without much experience in software development.

Translating to their native language surely helps bridging the gap. Let's democratize Apollo and GraphQL awesomeness for everyone!
 
Sorry if the subject has been discussed before. I couldn't find anything related.

**Comment by StephenBarlow** [comment]
Hi @andresg747, thank you for opening this! Unfortunately, official support for translations of the Apollo docs is currently outside of our bandwidth. Although we would celebrate community-driven efforts to translate the docs, our responsibility to keep the official docs complete and up to date means that those efforts would have to remain separate for the time being. Proper support for translations will require a great deal of planning, development, and investment that we have yet to do.

We'll be sure to announce any changes to this in the future as they arise!
