### ISSUE TITLE
IntrospectionQuery being called non stop every 2 seconds (infinite loop) 

### ISSUE THREAD

**Issue by brunolemos** [apollographql/apollo-server#3266]
#### Package version

apollo-server-micro: 2.9.3
@apollographql/graphql-playground-html: 1.6.24

#### What is the expected behavior?

Instropected query be called only once.

#### What is the actual behavior?

A new request is made every couple seconds. The http returns 200 and the response json is correct. I can see the schema and docs correctly in the UI, but the polling never stops, making my logs huge and slowing things down. 

#### What steps may we take to reproduce the behavior?

Simple server using `apollo-server-micro`, then open the playground. The polling starts automatically and never stops.

_Please provide a gif or image of the issue for a quicker response/fix._

![Kapture 2019-09-08 at 19 28 28](https://user-images.githubusercontent.com/619186/64495322-e31bdb80-d26e-11e9-8f46-8f26dce33e38.gif)

**Comment by trevor-scheer** [comment]
Hey @brunolemos, thanks for submitting an issue! This is expected behavior and configurable in [playground's settings](https://github.com/prisma/graphql-playground#settings).

**Comment by brunolemos** [comment]
Weird default behavior. But thanks!

**Comment by yurilongaray** [comment]
Well, it didnt work for me...
I set the  "schema.polling.enable": false and the playground continues to send requests: 
![Uploading image.png…]()

**Comment by orenansouza** [comment]
"schema.polling.enable": false solved for me
