### ISSUE TITLE
File uploads in apollo-server-hapi appear broken

### ISSUE THREAD

**Issue by swashcap** [apollographql/apollo-server#3267]
### Package name

Here are the relevant package versions:

* `apollo-server-hapi@2.9.3`
* `apollo-server-core@2.9.3`
* `@hapi/hapi@18.3.2`

I've tested this on Node.js `10.16.3` and `npm@6.9.0`.

### Expected behavior

I expect file uploads as described in [the "File uploads" documentation](https://www.apollographql.com/docs/apollo-server/features/file-uploads/) to work with apollo-server-hapi.

### Actual behavior

The server always sends `400` errors with a message of "GET query missing."

### Reproducible

I made https://github.com/swashcap/apollo-hapi-upload to show the problem. That project's test is essentially copied from here: https://github.com/apollographql/apollo-server/blob/10402c46013920b5c9cd64d5ae1cc41f5fe5ceb5/packages/apollo-server-hapi/src/__tests__/ApolloServer.test.ts#L411-L496

**Comment by swashcap** [comment]
Note that the file upload test for apollo-server-hapi is ignored! Might be good to un-ignore the test.

**Comment by swashcap** [comment]
I'll take a look at fixing this in a pull request. I think the problem comes from `handleFileUploads`:

https://github.com/apollographql/apollo-server/blob/10402c46013920b5c9cd64d5ae1cc41f5fe5ceb5/packages/apollo-server-hapi/src/ApolloServer.ts#L18-L34

Something to do with that not working.

**Comment by mkgo** [comment]
Any updates to this issue? I am hitting the same problem with our Hapi/Graph platform.

Has anyone found a workaround if this has not been fixed?

**Comment by wzrdtales** [comment]
i am having doubts that this ever worked... it is even on hapi 17 not working

**Comment by glasser** [comment]
Integration with a fork of an old version of `graphql-upload` was removed from Apollo Server last year in AS3.

Additionally, Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Hapi integration. It should not be that hard for excited Hapi users to build and maintain a Hapi integration, and our guess is they will do a better job of it than the Apollo Server core team, who did not use Hapi at all other than to maintain the integration. There is not a Hapi integration at this time, but some interest has been expressed over at https://github.com/apollographql/apollo-server/issues/6028. Sorry for the delay!
