### ISSUE TITLE
[apollo-server-koa] access koa.Context in dataSources function

### ISSUE THREAD

**Issue by sophister** [apollographql/apollo-server#3271]
This is a 💡 Feature request

I've some `DataSource`s, I can access `DataSource` in `Resolvers`. But I also want to access `DataSource` in `koa` `middleware`. 

For example, there is a `UserDataSource` to request the user service, normally we use it in `Resolvers` to retrieve user-related data; now I also need to use `UserDataSource` in a `middleware` such as user login *Authentication*.

So how can we share the same `DataSource` in `middleware` and `Resolver`?

Maybe I can initialize `UserDataSource` in a `middleware`, and assign it to `koa.Context`, and later in the `dataSources` function I can return `UserDataSource` from `ctx.userDataSource`. But I cannot access the `koa.Context` in the `dataSources` function at the moment.

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Koa integration. Check out the [@as-integrations/koa](https://www.npmjs.com/package/@as-integrations/koa) package; this new package is maintained by Ka users and most likely already solves the issue described above. Sorry for the delay!
