### ISSUE TITLE
apollo-server-micro logs flood console

### ISSUE THREAD

**Issue by kennetpostigo** [apollographql/apollo-server#3293]
`apollo-server-micro` package floods the console with not really useful content, what makes it worse is that it logs this on keystroke and any interaction with `graphiql` and every few seconds for no specific reason that matters to the dev ux. It makes it very difficult to find the things you are actually logging, and other request information.

Package: `apollo-server-micro`
Version: `^2.9.3`
Expected Behavior: Only log request and response data like regular micro
Actual Behavior: Logs flood console.

<details>
<summary>Example of content that floods the console constantly</summary>
<img src="https://user-images.githubusercontent.com/8888991/64913117-fcf26e00-d707-11e9-9843-79c8af502e92.png " />
</details>

**Comment by b3nab** [comment]
Yes, same as me. I noticed that maybe the Playground is flooding console logs.
