### ISSUE TITLE
Missing TypeScript typing for Upload type (with fields like createReadStream)

### ISSUE THREAD

**Issue by dko-slapdash** [apollographql/apollo-server#3306]
Hi.

E.g. I searched for createReadStream occurrences in Apollo sources, but didn't find any mentions for it in d.ts files. 

Most likely it should be something like:

```ts
interface Upload {
  filename: string;
  mimetype: string;
  encoding: string;
  createReadStream: () => Stream;
}
```

**Comment by rheaditi** [comment]
@dko-slapdash 

You can get it from the [`FileUpload` type from `graphql-upload`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d2b0b330eb3cb7d1e52af5e5aecacd737d6f1f8c/types/graphql-upload/index.d.ts#L43-L48) which I think is the underlying implementation..

**Comment by aleccool213** [comment]
This can be closed. @rheaditi is correct.

**Comment by glasser** [comment]
Integration with `graphql-upload` was removed in Apollo Server 3 last year.
