### ISSUE TITLE
Is there a known solution to work with Apollo Pub/Sub and apollo-server-azure-functions ApolloServer

### ISSUE THREAD

**Issue by sergsalo** [apollographql/apollo-server#3318]
This question was asked before in spectrum chat (never got answered), and stackoverflow (but it was mainly about AWS lambda support). 

So, is it possible to get PubSub working with Azure Functions? Is there any documentation about this?

**Comment by rlimberger** [comment]
I would also be interested in an answer on this. Now that Azure functions has a premier tier, that allows functions to stay alive (as if they were hosted in App Service), this should possible. But I can't find an example of how to make it work.

**Comment by sergsalo** [comment]
for now I switched to use web app and apollo express

**Comment by rlimberger** [comment]
@sergsalo and may I ask if you have any binding to CosmosDB change feed to publish changes to GraphQL subscription clients?

**Comment by sergsalo** [comment]
I backed it up by Azure Redis Cache.

import { RedisPubSub } from "graphql-redis-subscriptions";

const xxxTopic = "TopicName";
const redisConnection = getRedisCacheConnection();
const pubsub = new RedisPubSub({
    connection: {
        host: redisConnection.host,
        port: redisConnection.port,
        password: redisConnection.password,
        tls: {}
    }
});

export async function notifyGraphQL(params: ...){
    ...
    await pubsub.publish(xxxTopic , notificationObject);
}

**Comment by rlimberger** [comment]
And you construct the ApolloServer with the `subscription` option? This is the part that's missing from `apollo-server-azure-functions` and I can't figure out how to add the WebSocket to the function handler.

**Comment by sj7272** [comment]
Does anyone have any update on this?

**Comment by glasser** [comment]
Direct subscriptions integration was removed from Apollo Server in v3 last year. (Partially because of how the old flimsy integration led to problems like this one.)
