### ISSUE TITLE
Should error, but doesn't (incorrect type in named query)

### ISSUE THREAD

**Issue by mwalkerwells** [apollographql/apollo-server#3336]
Apollo Server 2.9.4

It took me forever to figure out why I was getting this result...

<img width="722" alt="Screen Shot 2019-09-24 at 7 45 11 PM" src="https://user-images.githubusercontent.com/16157429/65565312-63e00600-df04-11e9-82ff-3f262e0b6a26.png">

**Comment by freakomonk** [comment]
@mwalkerwells  Elaborate your findings please :)

**Comment by mwalkerwells** [comment]
My specific example is this...

```
mutation VerifyPhoneOwner($phoneNumber: Phone!, $deviceID: String!) {
  verify_phone_owner(phone: $phoneNumber, device_id: $deviceID) {
    time_expiration
    time_sent
  }
}
```

``deviceID`` should be of type ``ID``, but when incorrectly specificed as ``String``, I would expect an error describing an incorrect query, but ``errors`` is ``null``.

This took a lot of time to debug, so thought I'd flag it as an issue!

**Comment by mwalkerwells** [comment]
Found the bug and it was unshockingly on my end when calling this constructor function...

**Previous:**
```js
new Apollo.ApolloServer({
  //...
  formatError     : (e) => () => { throw e },
  //...
});
```

**Fix:**
```js
new Apollo.ApolloServer({
  //...
  formatError     : (e) => { throw e },
  //...
});
```
