### ISSUE TITLE
apollo-server-lambda v2: expose gateway event and context

### ISSUE THREAD

**Issue by khaledosman** [apollographql/apollo-server#3337]
### Problem

There're a few usecases I can think of when developing an AWS Lambda with apollo-server where the developer needs access to the original APIGatewayEvent and Context. The current way to develop a lambda in apollo-server v2 is as follows:
```
exports.graphqlHandler = server.createHandler({
  cors: {
    origin: '*',
    credentials: true
  }
})
```
create handler takes care of creating the incoming handler that uses the original ApiGatewayEvent and Context. While we can use the `context` property of ApolloServer for authroization logic to have access to the incoming gateway event and context, there're some cases where we need the original gateway event before that on the handler level, some of the usecases I can think of is

### Usecases
1. Database connection caching
To be more specific with Mongoose the recommended way to cache the db connection is by checking it on the handler level as explained here https://mongoosejs.com/docs/lambda.html

2. Warming up the lambda to avoid cold starts and skipping execution if its a warmup check
To be more specific using the [serverless-plugin-warmup](https://github.com/FidelLimited/serverless-plugin-warmup) to avoid executing the handler if its a warmup request and do an early return.

3. setting `context.callbackWaitsForEmptyEventLoop = false` ,  I believe the created handler by apollo-server already adds this?

4. other initialisation logic like defining a mongoose/database schema, models, etc...

### Current Version
apollo-server-lambda v2.9.3

**Comment by FlorinDavid** [comment]
@khaledosman thank you for `context.callbackWaitsForEmptyEventLoop = false` hint. 
My lambda function was hanging in browser GET request when I was training to load the playground page. And I think that was because of the asynchronous MongoDB connection time

I avoided to create the handler on every request and to reconnect to MongoDB so I have done something similar to:

```js

const connect = initConnection() // initConnection() will return a promise

const graphQLHandler = server.createHandler()

exports.handler = (event, context, callback) => {
  context.callbackWaitsForEmptyEventLoop = false

  // initConnection will run only once and after that the promise is fulfilled
  connect.then(() => graphQLHandler(event, context, callback))
}

```

**Comment by khaledosman** [comment]
@FlorinDavid 
Right in mycase I also wanted to share the db connection before hitting graphql's context to check if the user is authenticated and share him across the resolvers, so I had to do something like this

```
//handler.js
 connect.then((connection) => graphQLHandler(event, {...context,cnnection}, callback))
```
then use the db connection in apollo server's context to have the user or the authentication error accessible from resolvers
```
//apollo-server.js
 context: async ({ event, context }) => {
    const mongooseConnection = context.mongooseConnection
    try {
      const decodedToken = await validateAuthHeader(event.headers.Authorization)
      // try to retrieve a user with the token
      const User = mongooseConnection.model('User')
      const user = await User.findById(decodedToken._id).lean()
      // add the user to the context
      return { user, mongooseConnection }
    } catch (err) {
      // console.log(err)
      return { mongooseConnection, err }
    }
  },
```

**Comment by jeremyswann** [comment]
This exactly the explanation I needed thank you @khaledosman , hope to see this in Apollo doc soon.

**Comment by benalexb** [comment]
I was reading https://mongoosejs.com/docs/lambda.html and then came across the issue reported here. Thank you @khaledosman this is exactly what I was looking for. Hopefully, the documentation will be updated soon.

**Comment by sanketCactus** [comment]
> @khaledosman thank you for `context.callbackWaitsForEmptyEventLoop = false` hint.
> My lambda function was hanging in browser GET request when I was training to load the playground page. And I think that was because of the asynchronous MongoDB connection time
> 
> I avoided to create the handler on every request and to reconnect to MongoDB so I have done something similar to:
> 
> ```js
> const connect = initConnection() // initConnection() will return a promise
> 
> const graphQLHandler = server.createHandler()
> 
> exports.handler = (event, context, callback) => {
>   context.callbackWaitsForEmptyEventLoop = false
> 
>   // initConnection will run only once and after that the promise is fulfilled
>   connect.then(() => graphQLHandler(event, context, callback))
> }
> ```

Thanks @FlorinDavid  & @khaledosman 
I had a similar issue where I was adding Redis object on cache property of apollo config from [doc](https://www.apollographql.com/docs/apollo-server/data/data-sources/#using-memcachedredis-as-a-cache-storage-backend)


I was in the situation where any hits to the endpoint from postman worked but the playground didn't load resulting in timeout after 3 sec on lambda, so I tried your above code and it work. 


Commenting this for anyone looking for similar query with Redis connection to Apollo Lambda.

**Comment by aadibajpai** [comment]
> I was able to get the original gateway event and context as follows since createHandler returns a function. But still having this in the readme/documentation [here](https://www.apollographql.com/docs/apollo-server/deployment/lambda/) would be good
> 
> ```js
> exports.graphqlHandler = (event, context, callback) => {
>   context.callbackWaitsForEmptyEventLoop = false
>   // warmup plugin early return
>   // if (event.source === 'serverless-plugin-warmup' || (context.custom && context.custom.source === 'serverless-plugin-warmup')) {
>   //   console.log('WarmUp - Lambda is warm!')
>   //   callback(null, {
>   //     statusCode: 200,
>   //     body: 'warmed'
>   //   })
>   // } else {
>   initConnection().then((connection) => {
>     console.log('creating handler')
>     server.createHandler({
>       cors: {
>         origin: '*',
>         credentials: true
>       }
>     })(event, context, callback)
>   })
> }
> ```

do you know how this would need to be adjusted to add support for Apollo 3, notably from the changelog:
```
The handler returned by createHandler can now only be called as an async function returning a Promise (it no longer optionally accepts a callback as the third argument).

If you've written your own handler that calls the handler returned by createHandler with a callback, you'll need to handle its Promise return value instead.
```
I'd rather use apollo 3 as it uses apollo-server-express under the hood that simplifies some stuff for me, but I still need to solve the reusing mongoose connection problem.

**Comment by glasser** [comment]
You can access `event` and (Lambda) `context` in your (Apollo Server) `context` function. See docs: https://www.apollographql.com/docs/apollo-server/deployment/lambda/#getting-request-info
