### ISSUE TITLE
upload large file causing Error: "Payload content length greater than maximum allowed: 1048576"

### ISSUE THREAD

**Issue by Prosen-Ghosh** [apollographql/apollo-server#3354]
### Apollo Server Setup
```
const serverApollo = new ApolloServer({
    typeDefs,
    resolvers,
    schemaDirectives,
    uploads: {
        maxFieldSize: 52428800, //bytes = 50MB
        maxFileSize: 52428800,
        maxFiles: 10
    },
    formatError`
});
```
### Package name
`"hapi": "^17.8.5"`
`"apollo-server-hapi": "^2.4.8"`

### Actual Behavior
Less then 1MB File is uploading successfully. If the file size is gather then 1MB then i get the response is as given bellow. 
```
{
    "statusCode": 413,
    "error": "Request Entity Too Large",
    "message": "Payload content length greater than maximum allowed: 1048576"
}
```
### Expected Behavior
I expect file uploads as described in the "File uploads" documentation to work with apollo-server-hapi.

**Comment by abernix** [comment]
You have syntax errors in your _Apollo Server Setup_, but you've also left off the important bit after that to see how you're using `serverApollo` with `applyMiddleware` currently.

Regardless, 1MB is the [default limit by Hapi 17](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hapi/v17/index.d.ts#L1334-L1339).  If you want to change it — much like any Hapi middleware — you'll need to adjust Hapi's `maxBytes` by setting it to something higher if you want to send more bytes than that.

For `apollo-server-hapi`, you can do this via `applyMiddleware`'s `route` parameter (which is passed to Hapi itself):

```js
serverApollo.applyMiddleware({
  app,
  route: {
    payload: {
      maxBytes: 52428800,
    },
  },
});
```

If you have any other questions, please ask in the [Apollo Server channel of Apollo's Spectrum.chat](https://spectrum.chat/apollo/apollo-server).

**Comment by Prosen-Ghosh** [comment]
here is my full apollo server setup code
```js
const serverApollo = new ApolloServer({
    typeDefs,
    resolvers,
    schemaDirectives,
    formatError,
    uploads: {
        maxFieldSize: 52428800, //bytes = 50MB
        maxFileSize: 52428800,
        maxFiles: 10
    }
});
await serverApollo.applyMiddleware({
    app,
    route: {
        payload: {
           maxBytes: 52428800
        }
    }
});
await serverApollo.installSubscriptionHandlers(app.listener);
```
after setting route payload in `applyMiddleware` it is throwing `Error on apollo server! { AssertionError [ERR_ASSERTION]: Cannot set payload settings on HEAD or GET request: GET /graphql`

**Comment by abernix** [comment]
I see.  As we move toward Apollo Server 3.x, we won't be able to give this any attention ourselves.  If this is important to you, we would accept a PR which (cleanly) splits the route registration into separate `GET` and `POST` registrations (i.e. rather than `method: ['GET', 'POST']`, a separate `method: 'GET'` and `method: 'POST'`) and omits the `payload` option on the `GET`:

https://github.com/apollographql/apollo-server/blob/aa3e23de9fbcde41a1bd3cca9c2eacf734bae582/packages/apollo-server-hapi/src/hapiApollo.ts#L36-L39

It should also add tests.  If that's something you're willing to do, I'd encourage you to first try it locally to ensure it will work, prior to opening the PR.

**Comment by rpandey** [comment]
> here is my full apollo server setup code
> 
> ```js
> const serverApollo = new ApolloServer({
>     typeDefs,
>     resolvers,
>     schemaDirectives,
>     formatError,
>     uploads: {
>         maxFieldSize: 52428800, //bytes = 50MB
>         maxFileSize: 52428800,
>         maxFiles: 10
>     }
> });
> await serverApollo.applyMiddleware({
>     app,
>     route: {
>         payload: {
>            maxBytes: 52428800
>         }
>     }
> });
> await serverApollo.installSubscriptionHandlers(app.listener);
> ```
> 
> after passing `route` object in `applyMiddleware` it is throwing `Error on apollo server! { AssertionError [ERR_ASSERTION]: Cannot set payload settings on HEAD or GET request: GET /graphql`
> 
> my setup is much like [this](https://glitch.com/edit/#!/join/279f5f0c-3e03-4bde-b7e1-d97bbea20e8f)

Yes, I'm facing  exact same error.
