### ISSUE TITLE
Gateway error: Server requires either an existing schema, modules or typeDefs

### ISSUE THREAD

**Issue by P48L0** [apollographql/apollo-server#3365]
"@apollo/gateway": "^0.10.5"
    "apollo-server": "2.6.1"

**node version v12.10.0
npm version 6.11.3**

Apollo server throws the error in the title when trying to start the gateway server:

**server.js**
```
const { ApolloServer } = require('apollo-server'); 
const { ApolloGateway } = require('@apollo/gateway'); 

const gateway = new ApolloGateway({
  serviceList: [
    { name: 'accounts', url: 'http://localhost:4001/graphql' } 
  ]
}); 
const server = new ApolloServer({
  gateway  
}); 
server.listen().then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`);
});

```

**Comment by abernix** [comment]
The latest version of `apollo-server` is 2.9.4.  Please update to a more recent version of `apollo-server` and report back with a runnable reproduction (per the issue instructions) if you're still experiencing this problem.  Thanks!
