### ISSUE TITLE
Reliable Messaging in Apollo Subscription

### ISSUE THREAD

**Issue by itsbentsai** [apollographql/apollo-server#3375]
Currently I have been testing the Subscription feature according to the docs, however, I have encountered a situation where certain users (about 5 out of 40 - all online in the same room with decent internet connection) will miss a few messages. To my understanding this is related to WebSockets. Are there any fallback mechanisms that I would be able to implement to refrain this from happening or this is not the correct use case for reliable messaging?

Any input on this issue is appreciated. Thanks.
```
function Fetch() {
  const { loading, error, data, subscribeToMore } = useQuery(FETCH_QUERY);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;

  subscribeToMore({
    document: FETCH_SUBSCRIPTION,
    updateQuery: (prev, { subscriptionData }) => {
      if (!subscriptionData.data) return prev;
      const newItem = subscriptionData.data.items;
      const exists = prev.items.find(({ id }) => id === newItem.id);
      if (exists) return prev;

      return Object.assign({}, prev, {
        items: [...prev.items, newItem]
      })
    }
  });

  return data.items.map((items, index) => {
    <div>{items.content}</div>
  });
}
```

**Comment by glasser** [comment]
The minimalist integration with an unmaintained subscriptions package was removed from Apollo Server last year in v3.
