### ISSUE TITLE
Performance issues on error in lambda handler

### ISSUE THREAD

**Issue by nenti** [apollographql/apollo-server#3395]
"apollo-server-lambda": "^2.9.5",

When an error is thrown within any resolver and lambda has been running for a longer time already it seems to execute code that was stalled or is busy with something else in the event queue for up to 4 seconds. Executing the failing query multiple times after another the performance will return to normal.

- [ ] The expected behavior.
No high spikes when error is handled

- [ ] The actual behavior.
Up to 4 second response time spikes in the apollo server part of handling it.

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Lambda integration. Check out the [`@as-integrations/aws-lambda`](https://www.npmjs.com/package/@as-integrations/aws-lambda) package; this new package is maintained by Lambda users and implements support for the API Gateway v1 and v2 protocols. If you need to work with different AWS projects, you may be able to add that support to that package, or take another approach such as combining the [`@vendia/serverless-express`](https://www.npmjs.com/package/@vendia/serverless-express) package with Apollo Server 4's built-in `expressMiddleware` (this is the same approach that `apollo-server-lambda` takes in AS3). Sorry for the delay!
