### ISSUE TITLE
ApolloServer sendHeaders not working

### ISSUE THREAD

**Issue by squarewave24** [apollographql/apollo-server#3406]
my react app is adding the authorization header, but it is lost in ApolloServer on the way to the graphQL endpoints. 

i can see it in the context below, but the final destination throws a "missing authorization header" error.  does the below code look complete or do i need to set something else to ensure the auth header is getting passed ? 

```
const gateway = new ApolloGateway({
    serviceList: [
        { name: 'url1', url: 'http://url1../graphql' },
        { name: 'url2', url: 'http://url2../graphql' },
        { name: 'url3', url: 'http://url3../graphql' } 
    ],
  });
const server = new ApolloServer({ 
    gateway, 
    subscriptions: false, 
    engine: {sendHeaders: {all: true}},   // based on docs here: https://www.apollographql.com/docs/apollo-server/api/apollo-server/#apolloserver
    context: (ctx:any) => {
        console.log('ApolloServer req headers: ', ctx.req.headers)  // authorization token visible here
    }
 });
```

**Comment by squarewave24** [comment]
I am also trying to achiever this with context. but setting this property makes the whole thing crash.. 

```
const server = new ApolloServer({ 
    gateway, 
    subscriptions: false, 
    engine: {sendHeaders: {all: true}},
    context: (ctx:ExpressContext) => {
        console.log('ApolloServer ExpressContext', ctx.req.header('authorization'));  // header is there. 
        return {'authorization': ctx.req.header('authorization')}  // attempting to pass the header on to the graphql endpoint 
    }
 });
```

**Comment by cvandermeer** [comment]
I have the same issue.

**Comment by madox2** [comment]
Same issue ^2.11.0

**Comment by GlebLitvinov** [comment]
hey, guys. Any solution on this?

**Comment by glasser** [comment]
The old `engine.sendHeaders` configuration was about configuring whether traces in usage reports sent to the Apollo Engine (now Studio) service contain request headers.  This is now configured via the hopefully clearer

```
plugins: [
    ApolloServerPluginUsageReporting({
      sendHeaders: { all: true },
    }),
  ]
```

It looks like you're trying to configure how gateway talks to subgraphs, which is done via the buildService parameter to ApolloGateway.
