### ISSUE TITLE
The parameter `path` of applyMiddleware doesn't support regular expression.  `apollo-server-koa`

### ISSUE THREAD

**Issue by circlle** [apollographql/apollo-server#3407]
- description: I'm using apollo-server-koa as my BFF core, when I call applyMiddleware function with ``` { path: "/graphql/:businesscode" } ``` parameters, `path` are just recognized as plain string "/graphql/:businesscode", rather than a regular expression
- package: ```apollo-server-koa: 2.8.1```
- expected behavior:  Value of path can be in the form of regular expression. businesscode in my example can be a dynamic value.
The way how apollo-server-express’s applyMiddleware function work in handling path parameter is exactly what I want.
- my code
```js
 import { ApolloServer } from "apollo-server-koa"
 import Koa from "koa"

 const app = new Koa()
 let apollo = new ApolloServer({
   // my configuration
 });
 apollo.applyMiddleware({
  disableHealthCheck: true,
  cors: false,
  app,
  path: "/graphql/:businesscode"
})
```

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Koa integration. Check out the [@as-integrations/koa](https://www.npmjs.com/package/@as-integrations/koa) package; this new package is maintained by Ka users and most likely already solves the issue described above. Sorry for the delay!

(Additionally, Apollo Server 4 drops internal path parsing; I expect you'd just use the Koa Router directly with the new middleware!)
