### ISSUE TITLE
TypeError: Cannot read property 'fetch' of undefined

### ISSUE THREAD

**Issue by experimentalPrivateRepos** [apollographql/apollo-server#3429]
### When trying to add a RESTDataSource all requests made within this class fail.
Why is this?

The link belows allows you to test the code i wrote.
[CodeSandBox Link](https://codesandbox.io/s/apollo-server-k9oiw?fontsize=14)
Version: latest

**Expected behaviour**
Being able to make a get Request to the dummy API
**Actual behaviour**
Request fails with the following error:
`"errors": [
    {
      "message": "Cannot read property 'fetch' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "hello"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'fetch' of undefined",
            "    at API.<anonymous> (/sandbox/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:158:63)",
            "    at Generator.next (<anonymous>)",
            "    at /sandbox/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:8:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (/sandbox/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:4:12)",
            "    at trace (/sandbox/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:153:78)",
            "    at API.<anonymous> (/sandbox/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:196:24)",
            "    at Generator.next (<anonymous>)",
            "    at /sandbox/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:8:71",
            "    at new Promise (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": {
    "hello": null
  }
}`
When logging `this` in the API class this is the result:
`API {
  httpFetch: undefined,
  memoizedResults: Map {},
  baseURL: 'https://jsonplaceholder.typicode.com/' }`

**Comment by trevor-scheer** [comment]
Hey @experimentalPrivateRepos, thanks for submitting an issue (and especially the reproduction!)

I forked your sandbox and found that removing the `initialize` override, or restoring it to the [same behavior](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts#L56-L59) as the `RESTDataSource` resolved the issue.

**Comment by wzup** [comment]
@trevor-scheer 
Could you please elaborate on details of your answer?

**Comment by trdaya** [comment]
Hi @trevor-scheer . According to the official tutorial mentioned [here](https://www.apollographql.com/docs/tutorial/data-source/#add-data-sources-to-apollo-server), 
<img width="736" alt="Screen Shot 2020-03-17 at 10 17 27 AM" src="https://user-images.githubusercontent.com/14902243/76841291-ddfca200-6838-11ea-8755-5c79fe9c03b7.png">

Also, [here's](https://github.com/apollographql/fullstack-tutorial/blob/8a2afd782896f17812ea1532179447c4cd2c30ba/final/server/src/datasources/user.js#L19) how it is done in the official tutorial. 

By your following comment, do you intend that the tutorial is out of date?

> Hey @experimentalPrivateRepos, thanks for submitting an issue (and especially the reproduction!)
> 
> I forked your sandbox and found that removing the `initialize` override, or restoring it to the [same behavior](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts#L56-L59) as the `RESTDataSource` resolved the issue.

**Comment by robe007** [comment]
I had the same problem with `apollo-datasource-rest` combined with `graphql-yoga`, but I can make it work.

You can see my comments about it [here](https://github.com/apollographql/apollo-server/issues/3882#issuecomment-693954273)

**Comment by jpouillard** [comment]
Same here.
If can help : 
```
constructor() {
    super();
    this.baseURL = CHAT_API_HOST;
    this.initialize({} as DataSourceConfig<any>); // <===== this one resolve the issue
  }
```
