### ISSUE TITLE
502 errors when using serverless-apigw-binary

### ISSUE THREAD

**Issue by AustinGil** [apollographql/apollo-server#3437]
### Description
I have a Serverless GraphQL endpoint and I'm trying to add a serverless route that returns a PDF. For that, I think I need to define the "Binary Media Types" in AWS. And do accomplish that, Im using the [`serverless-apigw-binary`](https://github.com/maciejtreder/serverless-apigw-binary) plugin, but this causes some issues. With the plugin disabled, the GraphQL endpoint works, but the PDF endpoint does not. When I enable the plugin, the PDF works, but the GraphQL endpoint experiences some strange internal server error.

### Package details
"apollo-server-lambda": "^2.9.0"
"serverless-apigw-binary": "^0.4.4"

### Expected behavior
I expect the serverless plugin to integrate without causing a server error.

### Actual behavior
When I enable the plugin, the GraphQL endpoint returns message in the GraphQL playground:
```
{
  "error": "Response not successful: Received status code 502"
}
```
And for any query or mutation:
```
{
  "error": {
    "message": "Internal server error"
  }
}
```
Exploring the logs returns this error message:
```
2019-10-22 17:23:42.786 (-07:00)	8fa3224b-aeb8-48e9-b955-8d2ba05eede3	ERROR	Invoke Error	{"errorType":"SyntaxError","errorMessage":"Unexpected token e in JSON at position 0","stack":["SyntaxError: Unexpected token e in JSON at position 0","    at JSON.parse (<anonymous>)","    at graphqlHandler (/var/task/node_modules/apollo-server-lambda/dist/lambdaApollo.js:24:24)","    at /var/task/node_modules/apollo-server-lambda/dist/ApolloServer.js:112:16","    at Runtime.exports.graphql [as handler] (/var/task/src/index.js:50:12)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)","    at process._tickCallback (internal/process/next_tick.js:68:7)"]}
```

**Comment by 2color** [comment]
Were you able to resolve the bug @Stegosource?

**Comment by Stegosource** [comment]
I was not able to resolve the issue, but I did find a workaround. I run the PDF handling with a different serverless function altogether. This is kind of annoying because now I have 1 serverless.yml file for the gql service, and 1 for the pdf, but at least it's working.

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Lambda integration. Check out the [`@as-integrations/aws-lambda`](https://www.npmjs.com/package/@as-integrations/aws-lambda) package; this new package is maintained by Lambda users and implements support for the API Gateway v1 and v2 protocols. If you need to work with different AWS projects, you may be able to add that support to that package, or take another approach such as combining the [`@vendia/serverless-express`](https://www.npmjs.com/package/@vendia/serverless-express) package with Apollo Server 4's built-in `expressMiddleware` (this is the same approach that `apollo-server-lambda` takes in AS3). Sorry for the delay!
