### ISSUE TITLE
Express server does not expose a way of handling unexpected server errors 

### ISSUE THREAD

**Issue by eduardoramirez** [apollographql/apollo-server#3459]
**Plot**
An unexpected server error occurs outside of the query/mutation resolution path (eg, in a GraphQL Extension).

**Expected**
The graphql middleware calls `next` with the unexpected error so express error middleware can handle the error properly (eg, log it, mark the tracing span as error'ed, etc).

**Actual**
The graphql middleware sets the response status to 500 and calls `end` on the response.

**Example**

```javascript
class MyExtension extends GraphQLExtension {
  public willSendResponse() {
    throw new Error('oops')
  }
}

const app = express()

const server = new ApolloServer({
  extensions: [
      () => new MyExtension(),
  ],
})

server.applyMiddleware({app})

app.use((err, _req, res, _next) => {
  // Expected this to print but will not
  console.log('Error occurred: ', err)
})
```

**Commentary**
It feels to me that https://github.com/apollographql/apollo-server/blob/6d9c3b8c9779af25e2d7e50720624da21ab48836/packages/apollo-server-express/src/expressApollo.ts#L55-L57 should also be checking whether this was an unexpected 500 as thrown by https://github.com/apollographql/apollo-server/blob/fdaebaa284e3f912310a3e6807345303a589fcdc/packages/apollo-server-core/src/runHttpQuery.ts#L344-L348

Alternatively, if this is the expected behavior then is there a way to hook into that error state? If not, why is that the case?

**Metadata**
Package: `apollo-server-express`
Version: 2.4.0

**Comment by Rmnlly** [comment]
I'd like to revive this/bring attention to it. If an error is thrown in your plugin for example there is nowhere for it to be caught and logged easily but it does go through the process of getting into the formatError pipeline. Is there an ideal place where you should be logging errors from, as logging them from the didEncounterErrors hook is not a complete solution clearly.

**Comment by eduardoramirez** [comment]
irrc, an exception in a plugin would not trigger `didEncounterErrors` esp if it was a plugin function that runs in a phase after query execution (like `willSendResponse`). i don't recall if `formatError` was called; though `formatError` isn't great, at least not for us, bc it doesn't give you access to the request so the logs from `formatError` tend to be limited in what they can output (and not to mention you lose track of other useful request specific data like a tracing span).

it's possible some of these issues have been fixed since i last looked into it, I don't know.
