### ISSUE TITLE
In apollo-server-hapi, unauthenticated requests for playground page are not blocked

### ISSUE THREAD

**Issue by alistair-thomson-qatalog** [apollographql/apollo-server#3470]
--package: apollo-server-hapi
--version: 2.9.6

We have a hapi app and want to be able to disable all api access for unauthenticated users, including the GraphIQL gui.

Currently it's possible to authenticate graphql requests themselves but the gui page is shown regardless of the users authenticated state. This is because the route is configured during an onRequest event handler.

In case that's not clear, adding something along the lines of the following exhibits the behaviour we were hoping to see:

```diff
diff --git a/packages/apollo-server-hapi/src/ApolloServer.ts b/packages/apollo-server-hapi/src/ApolloServer.ts
index 0575d89c..de20eec2 100644
--- a/packages/apollo-server-hapi/src/ApolloServer.ts
+++ b/packages/apollo-server-hapi/src/ApolloServer.ts
@@ -85,6 +85,14 @@ export class ApolloServer extends ApolloServerBase {
             ) === 'text/html';
 
           if (prefersHTML) {
+            if (!request.auth.isAuthenticated) {
+              return h
+                .response('Unauthenticated')
+                .code(401)
+                .type('text/html')
+                .takeover();
+            }
+
             const playgroundRenderPageOptions: PlaygroundRenderPageOptions = {
               endpoint: path,
               subscriptionEndpoint: this.subscriptionsPath,
```

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Hapi integration. It should not be that hard for excited Hapi users to build and maintain a Hapi integration, and our guess is they will do a better job of it than the Apollo Server core team, who did not use Hapi at all other than to maintain the integration. There is not a Hapi integration at this time, but some interest has been expressed over at https://github.com/apollographql/apollo-server/issues/6028. Sorry for the delay!
