### ISSUE TITLE
apollo-server-fastify warning `beforeHandler` has been deprecated

### ISSUE THREAD

**Issue by Tiim** [apollographql/apollo-server#3477]
## Packages
* apollo-server 2.9.4
* apollo-server-fastify 2.9.4
* fastify 2.10.0

When registering the graphql server with fastify like this:

```js
  const server = new ApolloServer({
    typeDefs,
    resolvers,
    context,
  });
  fastify.register(server.createHandler());
```
## Current behavior
The following warning gets printed to the console:
```log
(node:220) Warning: The route option `beforeHandler` has been deprecated, use `preHandler` instead
```

## Expected behavoir
No warnings get printed to the console.

## Simple runnable reproduction

See [this Glitch remix](https://glitch.com/~chalk-niece)

**Comment by markrzen** [comment]
Recap for those new to the issue.

There are currently at least 5 PRs attempting to fix this issue:
- https://github.com/apollographql/apollo-server/pull/2391
- https://github.com/apollographql/apollo-server/pull/3527
- https://github.com/apollographql/apollo-server/pull/3561
- https://github.com/apollographql/apollo-server/pull/3674
- https://github.com/apollographql/apollo-server/pull/3911

The oldest pull request, pre-dating this issue, [@abernix]  states it can not be resolved until Apollo Server V3](https://github.com/apollographql/apollo-server/pull/2391#issuecomment-495711653).

**Comment by harveyconnor** [comment]
Any progress on this? I'm assuming its going to be a v3 thing inline with apollo-client's v3 ?

**Comment by jsumners** [comment]
Fastify v3 was released last week https://github.com/fastify/fastify/releases/tag/v3.0.0

Related #4355 and #4356.

**Comment by AndyGura** [comment]
Hey guys, waiting this issue to be resolved for so long. Any updates?

**Comment by abernix** [comment]
Please see the update I just posted on https://github.com/apollographql/apollo-server/pull/4356#issuecomment-677515901 for the availability of the Fastify v3 support on Apollo Server.
