### ISSUE TITLE
UserInputError mutates it's second argument

### ISSUE THREAD

**Issue by bwesner** [apollographql/apollo-server#3481]
I am using the `UserInputError` class from the `apollo-server-micro` package version 2.9.7.

Reproduction:

```
import { UserInputError } from "apollo-server-micro";
console.log(new UserInputError('Test Error1', { test: 'test error' }));
console.log(new UserInputError('Test Error2', { name: 'test error' }));
```

Expected output (roughly):

```
{ UserInputError: Test Error1
    at XXX
  test: 'test error',
  extensions: { test: 'test error', code: 'BAD_USER_INPUT' } }
{ UserInputError: Test Error2
    at XXX
  name: 'test error',
  extensions: { name: 'test error', code: 'BAD_USER_INPUT' } }
```

Actual output (roughly):

```
{ UserInputError: Test Error1
    at XXX
  test: 'test error',
  extensions: { test: 'test error', code: 'BAD_USER_INPUT' } }
{ UserInputError: Test Error2
    at XXX
  name: 'UserInputError',
  extensions: { name: 'test error', code: 'BAD_USER_INPUT' } }
```

It seems that if the object passed to the second argument of the `UserInputError` constructor contains the `name` key, then `UserInputError` replaces the corresponding value with the string `UserInputError`.

The real world use case here for me is that I am trying to pass mongoose validation errors directly to the `UserInputError`, which sometimes contain the key `name`.

**Comment by glasser** [comment]
In Apollo Server 4 we've simplified error handling by just using GraphQLError directly without a bunch of random subclasses like UserInputError. https://www.apollographql.com/docs/apollo-server/migration#apolloerror
