### ISSUE TITLE
Federation caching

### ISSUE THREAD

**Issue by drager** [apollographql/apollo-server#3507]
Hey, how is it supposed to work with Apollo federation and changes to federated schemas? We have 3 different services and one "federation service" that merges the schemas together. However, if we make a change to a schema in one of the services, then we need to restart the "federation service" so it can load the new schema. Is this how it's supposed to work? Do we really need to restart that service all the time? Or is this some schema caching problem in Apollo federation?

Thanks!

**Comment by abernix** [comment]
As noted in the issue template, questions should be referred to Spectrum.

There are existing conversations on there about this, and you don't need an account to view them.  e.g., https://spectrum.chat/apollo/apollo-federation/auto-reload-of-schema-changes-in-apollo-federation-services-without-restart-of-gateway~2b54f60d-3add-4703-92b6-ebe2d2b5d0e3

We also have [some documentation](https://www.apollographql.com/docs/graph-manager/federation/) that might help you as there are considerations to be made about ensuring that the new graph is fully compose-able after an underlying service restarts with changes.

The managed federation approach provides tooling to make that happen more reliably.  Alternatively, there are hooks to integrate your own tooling, as that thread notes, but you should ensure that you have the proper pre-flight checks in place prior to attempting to reload.
