### ISSUE TITLE
Context undefined issue in GraphQL resolver

### ISSUE THREAD

**Issue by manojkumaraut** [apollographql/apollo-server#3524]
Team,
I am facing an issue on context undefined with the graphql resolver,when using with the apollo server .This is the code used.
return new ApolloServer({
			schema,
			context: ({ req}) => ({
				req
			}),
			playground:true,
			 introspection: true
		});
Thanks and appreciate your help...

**Comment by DennisOosterling** [comment]
Hi @manojkumaraut, 

Perhaps you already found it, but you can directly return the request data like this:
`context: ({ req }) => req`

**Comment by dep-dt** [comment]
Did you figure this out @manojkumaraut ?  same problem here.

**Comment by DennisOosterling** [comment]
@dep-dt 
It's been some time, but if I remember correctly the code below worked for me
```
ApolloServer({
    schema,
    context: ({ req }) => req,
    playground:true,
    introspection: true
});
```

**Comment by Makwe-O** [comment]
Ran into a similar issue. Restarting the server worked for me

**Comment by hannesreinsch** [comment]
Still struggling with this - anyone got a solution?

**Comment by dep-dt** [comment]
My issue was how I was forming the actual `context`.

**Bad, doesn't work for me:**
```js
const server = new ApolloServer({
    schema,
    dataSources,
    context: ({ req }) => {
        console.log(req);
    },
});
```

**Good:**
```js
const server = new ApolloServer({
    schema,
    dataSources,
    context: req => {
        console.log(req);
    },
});
```

And then you should be able to test this using something like `curl` from the command line.

```
▶ curl \
  -X POST \
  --data '{ "query": "{ foo { bar } }" }' \
http://localhost:4000/graphql
```

Good luck out there!

**Comment by shameekagarwal** [comment]
I have a few resolvers which need authentication and few which dont.
This works for me, not sure if this is the way im supposed to do it....
This is for graphql-yoga

```
const { GraphQLServer } = require("graphql-yoga");

const checkAuth = ({ request }) => {
  try {
    const authHeader = request.headers.authorization;
    const token = authHeader.split(" ")[1];
    const { id } = jwt.verify(token, process.env.JWT_SECRET);
    return { user: id };
  } catch (error) {
    return;
  }
};

const resolvers = require("./resolvers");
const { checkAuth } = require("../controllers/auth");

const server = new GraphQLServer({
  typeDefs: "./src/schema.graphql",
  resolvers,
  context: checkAuth,
});

```

**Comment by glasser** [comment]
There isn't enough information in this issue to understand exactly what the issue is.

Additionally, in Apollo Server 4 we're [improved our TypeScript type declarations around the context value](https://www.apollographql.com/docs/apollo-server/migration/#improved-typing-for-context). So anyone using TS with AS4 should get a lot more automatic help in writing a good context function.
