### ISSUE TITLE
The sendReportsImmediately engine option is undocumented

### ISSUE THREAD

**Issue by scherroman** [apollographql/apollo-server#3538]
The [sendReportsImmediately](https://github.com/apollographql/apollo-server/blob/1abf851bb3dc6a3a0e5b1f9e8e3bc82bc8f5e16c/packages/apollo-engine-reporting/src/agent.ts#L162) option is currently undocumented in the [EngineReportingOptions](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#enginereportingoptions). 

After looking into the codebase it appears this is provided by default in the stateless packages like [apollo-server-lambda](https://github.com/apollographql/apollo-server/blob/84e1aa5ad3ee2acf410ca8984cfc68e90d4f8a66/packages/apollo-server-lambda/src/ApolloServer.ts#L27), but the existence of the reportIntervalMs option along with the [Graph Manager documentation](https://www.apollographql.com/docs/graph-manager/setup-analytics/) seem to imply traces are always sent in batches after intervals. This would be helpful to acknowledge in the documentation for deployments to stateless environments like [AWS Lambda](https://www.apollographql.com/docs/apollo-server/deployment/lambda/) to avoid confusion!

**Comment by theJC** [comment]
This is documented now, I believe this can be closed now
https://www.apollographql.com/docs/apollo-server/api/plugin/usage-reporting/#options
