### ISSUE TITLE
Request, response objects missing when using apollo-server-lambda

### ISSUE THREAD

**Issue by sami616** [apollographql/apollo-server#3544]
Hi there, im migrating an apollo server setup from zeit to netlify functions and am having some trouble with accessing the request, response objects that are usually available in my context when using `exports.handler = server.createHandler()`. The rest of my app relies on these for setting cookies etc.

is there a way to still access these objects in my context for passing down to resolvers?

**Comment by abernix** [comment]
The context is different for each integration based on what the integration provides.  

For more details on each interface, including the one available for Lambda, [see the `context` section of the Apollo Server API](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#parameters), recently added in #3506.
