### ISSUE TITLE
Apollo Server's `graphqlExpress` should not ignore query string on POST

### ISSUE THREAD

**Issue by xealot** [apollographql/apollo-server#3547]
https://github.com/apollographql/apollo-server/blob/431688390b2d1af8756515e9680332d569f8b73f/packages/apollo-server-express/src/expressApollo.ts#L36

When receiving a `POST` the `graphqlExpress` adapter ignores the data in the query string. To me this flies in the face of expected HTTP behavior.

I am allowed to send a query string in on a `POST`, so IMO it should be supported. I think support would be relatively safe and easy as well.

Before:
```ts
query: req.method === 'POST' ? req.body : req.query,
```

After:
```ts
query: {...req.query, ...(req.method === 'POST' ? req.body : {}},
```

The reasoning here is that it provides a far easier mechanism to test APQ using tools that offer GraphQL support. (Postman, Insomnia, Playground, etc...). It's far easier to send a query string in with your formatted body than it is to get those clients to append an `extension` into the JSON post.

**Comment by glasser** [comment]
The de facto standard for GraphQL over HTTP has been to provide the operation string in the body for POST and in the query string for GET; this is also reflected in the draft [GraphQL Over HTTP spec](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md).

That spec also documents the concept of request `extensions`, so hopefully your favorite tools will support them soon.
