### ISSUE TITLE
Does apollo-server-cloudflare support apollo-engine ?

### ISSUE THREAD

**Issue by Cerberus** [apollographql/apollo-server#3555]
I added `engine: 'service:...'` to `new ApolloServer(..)` and `wrangler publish`(v1.2).

This is what I got..

```
✨  Built successfully, built project size is 487 KiB.
Error: Something went wrong! Status: 400 Bad Request
..
{
  "errors": [
    {
      "code": 10021,
      "message": "Uncaught Error: Some functionality, such as asynchronous I/O, timeouts,
and generating random values, can only be performed while handling a request.
  at line 49 in t.EngineReportingAgent
  at line 37 in t.ApolloServerBase
  at line 71 in t.ApolloServer"
    }
  ]
}
```

After remove `engine`, everything is working perfectly. Does it support now ?

**Comment by abernix** [comment]
Cloudflare is a V8 runtime and doesn't have some of the Node.js functionality that `apollo-engine-reporting` relies on (e.g. `process.hrtime()`).  Further, to prevent timing-based attacks on workers, I believe they only advance the clock when I/O occurs, which would affect the accuracy of the reports generated and transmitted to Apollo Graph Manager.  [This forum post](https://community.cloudflare.com/t/cloudflare-workers-how-do-i-measure-execution-time-of-my-method/69672/5) talks about it briefly.

If this is important to you within Cloudflare workers, please contact Apollo Graph Manager support and let them know so we can track this internally on our product board and consider what a solution might look like.

> Does it support now ?

Yes, `now` works correctly to my knowledge.
