### ISSUE TITLE
Federation: how to forward request headers to implementing services

### ISSUE THREAD

**Issue by ahouzzer** [apollographql/apollo-server#3558]
According to https://www.apollographql.com/docs/apollo-server/api/apollo-gateway/#willsendrequest-requestcontext-request-graphqlrequest-context-recordstring-any--promisevoid, I wrote the following code
```js
class DataSource extends RemoteGraphQLDataSource {
    async willSendRequest({ request, context }) {
        console.log('will', request.http.headers);
    }
}
```
However, the only headers that's printed out are
```
'Content-Type': [ 'application/json' ]
```
Other headers passed by clients are not there.

I tried to search in the forum but didn't find a meaningful discussion of this issue.

**Comment by ahouzzer** [comment]
With the help of https://spectrum.chat/apollo/apollo-federation/forwarding-response-headers-back-to-the-client~e7d0f3cf-c999-42b0-ae38-93ff32eab070?m=MTU3NDcxMjU4NDM3Ng==, I finally understood what this doc means https://www.apollographql.com/docs/apollo-server/federation/implementing/#customizing-incoming-requests

My first time using Apollo Server.

**Comment by marcusbesjes** [comment]
I think you mixed up the `context.req` incoming client request with the `request` which is the outgoing "forwarded" request to the federated service.

We do something like

```
class DataSource extends RemoteGraphQLDataSource {
    async willSendRequest({ request, context }) {
        const headers = context.req.headers
        for (const key in headers) {
            const value = headers[key];
            if (value) {
                request.http?.headers.set(key, String(value));
            }
        }        
    }
}
```
I'm still wondering if there's a way to do this without defining a custom DataSource.. I would kind of expect this to be a standard feature.

**Comment by jpasquers** [comment]
> I think you mixed up the `context.req` incoming client request with the `request` which is the outgoing "forwarded" request to the federated service.
> 
> We do something like
> 
> ```js
> class DataSource extends RemoteGraphQLDataSource {
>     async willSendRequest({ request, context }) {
>         const headers = context.req.headers
>         for (const key in headers) {
>             const value = headers[key];
>             if (value) {
>                 request.http?.headers.set(key, String(value));
>             }
>         }        
>     }
> }
> ```
> 
> I'm still wondering if there's a way to do this without defining a custom DataSource.. I would kind of expect this to be a standard feature.
> 
> (Adding this here because my web search lead me to this page, and it might help others)

Just a note to be careful here, because Express defines header values as `string | string[]` and GraphQLRequest.Request.Headers defines header values as just `string`. So any array headers (there are luckily very few, just set-cookie and potentially x-forwarded-for) need to be handled a bit differently.
