### ISSUE TITLE
Upgrade graphql-upload to 9.0 to support Node.JS 13

### ISSUE THREAD

**Issue by lcswillems** [apollographql/apollo-server#3579]
Apollo Server upload feature is not working for Node.JS 13 because it uses version ^8.0.2 of `graphql-upload` which is not working on Node.JS 13: https://github.com/jaydenseric/graphql-upload/issues/170

A new version (version 9) had been published yesterday that support Node.JS 13. Is it possible to upgrade the dependency?

**Comment by remiroyc** [comment]
I confirm this issue. https://github.com/apollographql/apollo-server/issues/3508

**Comment by zsolt-dev** [comment]
This should be an easy fix...  Is there something that is holding back the graphql-upload upgrade to 9.0?

**Comment by mickeyschwab** [comment]
Bumping this as v10.0 has now been released. I've used resolutions to pin v10 in a project and that is what it took to resolve my upload issues.

**Comment by jz222** [comment]
Using the latest `graphql-upload` also doesn't work with Node 12 as outlined here jaydenseric/graphql-upload#185

**Comment by jaydenseric** [comment]
@jz222 

> Using the latest graphql-upload also doesn't work with Node `12`.

That's not correct, all the tests are passing for Node.js v12:

https://github.com/jaydenseric/graphql-upload/runs/410403846?check_suite_focus=true#step:4:132

**Comment by jz222** [comment]
@jaydenseric sorry if I wasn't clear enough. I referenced the issue since you found out that it is related to mismatching versions of `graphql-upload` as mentioned [here](https://github.com/jaydenseric/graphql-upload/issues/185#issuecomment-583572804).

**Comment by hemedani** [comment]
please upgrade it's throwing this error : `Maximum call stack size exceeded`

**Comment by lucasbemol** [comment]
updates?

**Comment by hemedani** [comment]
I'm disabling upload property [look at here](https://github.com/MichalLytek/type-graphql/issues/37#issuecomment-592467594)

**Comment by abernix** [comment]
Duplicate of #3508.  Please also see the update / suggestion I posted there in https://github.com/apollographql/apollo-server/issues/3508#issuecomment-662371289

**Comment by joelmagner** [comment]
Still an issue on Node 14.
