### ISSUE TITLE
Bug/Documentation - Following docs to disable reporting still gives console warnings.

### ISSUE THREAD

**Issue by itmayziii** [apollographql/apollo-server#3611]
Packages: 
@apollo/federation: 0.11.2
apollo-server-express: 2.9.9

The [documenation](https://www.apollographql.com/docs/apollo-server/federation/metrics/#turning-it-on) leads me to believe that setting these options `{ engine: true, reporting: false }` in the server constructor should disable reporting for a federated service (so that the gateway can do that work.) When I do this though I am still getting the console warning 

_It looks like you're running a federated schema and you've configured your service to report metrics to Apollo Graph Manager. You should only configure your Apollo gateway to report metrics to Apollo Graph Manager._

The expected behavior is that this warning will not show up if the correct constructor options have been passed in per the documentation.

**Comment by damianesteban** [comment]
Any update on this? It is very confusing.

**Comment by abernix** [comment]
The documentation is wrong.  The correct configuration for implementing services is to just set `engine: false` (or ensure that `ENGINE_API_KEY` is not set in the environment.)

**Comment by abernix** [comment]
I've removed it from the documentation in https://github.com/apollographql/apollo-server/commit/87c8be4a3c1091a26cac420b95a669201736bd8b.  See the `EngineReportingOptions` interface, as defined here for current options:

https://github.com/apollographql/apollo-server/blob/87c8be4a3c1091a26cac420b95a669201736bd8b/packages/apollo-engine-reporting/src/agent.ts#L48-L199

Thanks for reporting this!

**Comment by xenoterracide** [comment]
Hi, so I just got this error. Currently we have a single server, no gateway, however I'm trying to write the code such that it cold be easily federated, are we able to leave the `engineApiKey` enabled, it will still function correct?

**Comment by StevenLangbroek** [comment]
This is still happening for us, I'm unsure how to disable this...
