### ISSUE TITLE
Deploying to zeit now

### ISSUE THREAD

**Issue by nadzic** [apollographql/apollo-server#3617]
Hi,

after reviweing your tutorial and wanted to deploy apollo server (express) with zeit now I found that your part of docs are outdated.

https://www.apollographql.com/docs/apollo-server/deployment/now/

Actually as far as I know, zeit now looks for build not start.

Could you please update documentation accordingly that you will be able to deploy apollo-server to zeit now?

Kinds,
Nik

**Comment by bartdominiak** [comment]
+1

**Comment by abernix** [comment]
Thanks for reporting this! This is somewhat related to https://github.com/apollographql/apollo-server/pull/3648, which _removes_ the Zeit docs entirely, though it's worth noting that these existing docs are for Zeit 1.0, which is deprecated for new users (who are put onto the Zeit 2.0 platform).

If someone is willing to make a PR to update the existing documentation for the Zeit 2.0 patterns, that would be greatly appreciated and, I think, the best step forward.

At the very least, an annotation being added to the existing documentation which makes it very clear that they are 1.0 would be more actionable.  We could just remove the Zeit deployment instructions entirely, but that seems less than desirable.

PRs to improve this very much welcome to improve this!
