### ISSUE TITLE
apollo-server-integration-testsuite not found in npmjs.com

### ISSUE THREAD

**Issue by mmindenhall** [apollographql/apollo-server#3625]
Yesterday my project was building and deploying just fine.  Today I made a small dependency change, then ran `yarn install`, which produced the following error:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/apollo-server-integration-testsuite: Not found".
```

When I checked for the package on [npmjs.com](https://www.npmjs.com/search?q=apollo-server-integration-testsuite), it has completely vanished since yesterday.  Any idea what happened there?

**Comment by abernix** [comment]
Not sure what changed for you, but that package is not intended to be published to npm.  It's marked as a `private` package and always has been and it has never been published before.

https://github.com/apollographql/apollo-server/blob/91a8c4db0ddf55d6ad6bc8299789dd20acb22084/packages/apollo-server-integration-testsuite/package.json#L2-L4
