### ISSUE TITLE
Constructor option 'modules' not described in MD file

### ISSUE THREAD

**Issue by ErikBongers** [apollographql/apollo-server#3642]
`ApolloServer` constructor has a `modules` option that is nowhere to be found in the documentation. Not even in the MD file. The `modules` option is handled in `ApolloServerBase`, and at least [this option test](https://github.com/apollographql/apollo-server/blob/81529d9c99352f9f1df23da674388636f3ab9193/packages/apollo-server-core/src/ApolloServer.ts#L182) should be mentioned in the docs.

Having said that, I didn't really find any documentation whatsoever on modules in Apollo. Only this external [blog post](https://blog.logrocket.com/from-rest-to-graphql/). (but I may have overlooked it)

**Comment by pavittarx** [comment]
I cannot find the docs about module option either. The constructor option in the Apollo Server API reference [here](https://www.apollographql.com/docs/apollo-server/api/apollo-server/) doesn't even mentions it.

**Comment by glasser** [comment]
`modules` was a confusing option that was nearly equivalent to passing `typeDefs` and `resolvers` but used a different slightly-incompatible implementation under the hood. It has been [removed in Apollo Server v4](https://www.apollographql.com/docs/apollo-server/migration/#modules). The reference docs should now document all constructor options. (Though we did add the documentation at some point before removing it, I think.)
