### ISSUE TITLE
unable to view playground after deployed into aws lambda using serverless (apollo-server-lambda)

### ISSUE THREAD

**Issue by Mohamed-Abubucker** [apollographql/apollo-server#3643]
Hi,
recently i have deployed my apollo graphql server into aws lambda using serverless. i used apollo-server-lambda package for that.

after deployment, i am able to do query and mutations and i am getting fair response from my  graphql endpoint https://3drjwyz1z8.execute-api.us-east-1.amazonaws.com/dev/graphql

my problem is, i am unable to view graphiql playground from my browser. i tried a lot but nothing helped me. i am getting below error while i am hitting the endpoint from browser to view playground.
```
{
message: "Internal server error"
}
```

i have allowed cors, any header and so on. they only problem is with playground. i set playground:true too.

```
const server = new ApolloServer({
  schema,
  context,
  playground: true,
  introspection: true,
});
```

nothing helping me. i want to display the playground to the users if they hit from browser, then only they can view the gql types and schema design.

 kindly guide me how to address this issue.

**Comment by arthurandrade** [comment]
I had this same problem!

to solve it, in my serveless.yml, I add it

```graphql:
    handler: graphql.handler
    events:
    - http:
        path: graphql
        method: POST
        cors: true
    - http:
        path: graphql
        method: GET
        cors: true
    - http:
        path: playground
        method: ANY
        cors: true
```

and to access the playground I used this url `https://......amazonaws.com/dev/playground`

**Comment by Mohamed-Abubucker** [comment]
@arthurandrade , thanks for your comment, i will try as you said and get back to you.

**Comment by cmejet** [comment]
I tried this without success @Mohamed-Abubucker did you get it working?

**Comment by Mohamed-Abubucker** [comment]
Hi @cmejet ,

i did not tried the above solution, i am using graphqlbin for playground and i already went live with my gql backend.

https://www.graphqlbin.com/v2/new

above is the graphqlbin url, you have to enter your gql end point. 

![image](https://user-images.githubusercontent.com/26508192/77139730-24ead180-6a9d-11ea-81dc-01e6bad17e5a.png)

there you can have your playground 

![image](https://user-images.githubusercontent.com/26508192/77139760-48158100-6a9d-11ea-9d72-f4bf33110eda.png)

but, for that you have to add the below lines of code in your gql backend

```
const server = new ApolloServer({
  schema,
  context,
  playground: true,
  introspection: true,
  tracing: true
});
```

As the above solution worked for me and i no longer require playground in production, i don't have time to try @arthurandrade's solution

**Comment by tanphamhaiduong** [comment]
![image](https://user-images.githubusercontent.com/22660833/84033680-70898900-a9c3-11ea-9fe0-32c4d702595e.png)
I can run this on serverless-offline but after deploy to lambda it always shows me Internal Server Errors without error log on cloud watch. Does anybody face with this problem?

**Comment by Mohamed-Abubucker** [comment]
@tanphamhaiduong  Yes, i too faced same problem. but now i am not working on it.

**Comment by tanphamhaiduong** [comment]
@Mohamed-Abubucker so how can you resolve this problem?

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Lambda integration. Check out the [`@as-integrations/aws-lambda`](https://www.npmjs.com/package/@as-integrations/aws-lambda) package; this new package is maintained by Lambda users and implements support for the API Gateway v1 and v2 protocols. If you need to work with different AWS projects, you may be able to add that support to that package, or take another approach such as combining the [`@vendia/serverless-express`](https://www.npmjs.com/package/@vendia/serverless-express) package with Apollo Server 4's built-in `expressMiddleware` (this is the same approach that `apollo-server-lambda` takes in AS3). Sorry for the delay!

We also have replaced the hardcoded unmaintained Playground package with a landing page plugin system, defaulting to Apollo Explorer.
