### ISSUE TITLE
Is there some reason to allow an Int <-> String auto casting?

### ISSUE THREAD

**Issue by scarfunk** [apollographql/apollo-server#3654]
When I try to make resolver and scheme.
Some types are cast automatically.
There seems to be hard to trust a type. Is there some reason?
I think simply, why don't you using `typeof` operator?

Here's my test (resolver and gql scheme)

```
        bool2strCase: () => { // success
		return true;
	},
	str2boolCase: () => { // fali!
		return 'true';
	},
	int2strCase: () => { // success
		return 1;
	},
	str2intCase: () => { // success
		return '1';
	},
```

```
    bool2strCase: String!
    str2boolCase: Boolean!
    int2strCase: String!
    str2intCase: Int!
```

**Comment by queerviolet** [comment]
This is the behavior of `graphql.js`. If I had to hazard a guess as to why, it's that autoconversion to booleans is very likely to be incorrect (and maybe with surprising results, i.e. `Boolean([]) === true`), whereas autoconversion from string representations of numbers to numbers is both heavily expected in JS and also useful in some cases—for example, many databases will return certain number types as strings when the underlying type can't be perfectly represented as a 64-bit float.

**Comment by queerviolet** [comment]
In any case, I agree this is a bit surprising, but it would be a breaking change, and I think it's not quite so surprising as to warrant that.

**Comment by scarfunk** [comment]
Thanks for commenting!
