### ISSUE TITLE
Opentracing / OpenTelemetry implementation (WIP)

### ISSUE THREAD

**Issue by vladislav-kiva** [apollographql/apollo-server#3658]
Hello, i started to implement opentracing in graphql-gateway and for now what i did( i'm new to js and ts so if u have some improvements do not hesitate to say it ):
```
import {FORMAT_HTTP_HEADERS, Span, Tracer} from "opentracing";
import {RemoteGraphQLDataSource} from "@apollo/gateway";
import {Headers, Request, Response} from "apollo-server-env";
import {GraphQLRequestContext} from 'apollo-server-types';

export default class OpentracingDataSource extends RemoteGraphQLDataSource {

  private tracer: Tracer;
  private requestSpan: Span | null;

  constructor(tracer: Tracer,
              config?: Partial<RemoteGraphQLDataSource> &
                  object &
                  ThisType<RemoteGraphQLDataSource>) {
    super(config);
    this.tracer = tracer;
    this.requestSpan = null;
  }

  willSendRequest<TContext>(requestContext: Pick<GraphQLRequestContext<TContext>, "request" | "context">): Promise<void> | void {
    if (requestContext.request.http != null) {
      this.requestSpan = this.tracer.startSpan("graphql-service-request", {
        tags: {"graphqlQuery" : requestContext.request.query}
      }/*, {
      childOf: externalSpan ? externalSpan : undefined
    }*/);
      let traceHeader: Headers = new Headers();
      this.tracer.inject(this.requestSpan.context(), FORMAT_HTTP_HEADERS, traceHeader);
      for (const [key, value] of Object.entries(traceHeader)) {
        requestContext.request.http.headers.append(key, value);
      }
    }
  }

  didReceiveResponse<TResult = any, TContext = any>(response: Response, request: Request, context?: TContext): Promise<TResult> {
    const body = super.didReceiveResponse(response, request, context);
    if (this.requestSpan != null) {
      this.requestSpan.finish();
    }
    return body;
  }
}
```
And that what i got at UI:
![Screenshot_2020-01-09 Jaeger UI](https://user-images.githubusercontent.com/26868991/72066418-95cd7a80-32f1-11ea-9b2b-71768c21a8e5.png)
Here u can see i got my HTTP populated with correct tracing header and the next service (orange on image) see my header and when span returns we have now our chain.
Problem that on RemoteGraphQLDataSource layer i can not access HTTP headers that comes to graphql gateway. I need access them to eject incoming span from it and then prolongate via my OpentracingDataSource.

I saw in executeQueryPlan.ts (https://github.com/apollographql/apollo-server/blob/master/packages/apollo-gateway/src/executeQueryPlan.ts#L315) we have access to incoming HTTP headers, so my question: Is there any good way u suggest me to path http headers to RemoteGraphQLDataSource so they can be visible there?(and i can access them at willSendRequest method to fill my commented childOf)

**Comment by vladislav-kiva** [comment]
Upd: Ohh i found the logic with traceNode, i can implement smth like it too i think

**Comment by abernix** [comment]
Thanks for opening this originally.  We recently published [this documentation](https://www.apollographql.com/docs/federation/opentelemetry/) on how to instrument Apollo Server with OpenTelemetry.  You can also see an example of what it looks like in Zipkin in the [Supergraph Demo](https://github.com/apollographql/supergraph-demo#open-telemetry) repository that @prasek put together 😎 !

We're open to feedback for this documentation, but please open new issues to track tasks that might make sense to build on based on this new information.  Thanks again for opening this originally!
