### ISSUE TITLE
Wrong/Missing Typescript type for `__resolveReference`

### ISSUE THREAD

**Issue by aleccool213** [apollographql/apollo-server#3666]
### This bug report should include:

- [x] A short, but descriptive title. The title doesn't need "Apollo" in it.
- [x] The package name and version of Apollo showing the problem.

`apollo-graphql`, `@apollo/federation`

- [ ] If applicable, the last version of Apollo where the problem did _not_ occur.
- [x] The expected behavior.

[__resolveReference](https://www.apollographql.com/docs/apollo-server/api/apollo-federation/#__resolvereference) can be typed with `GraphQLFieldResolver` (or another new type?) from the [graphql](https://www.npmjs.com/package/graphql) library.

- [x] The actual behavior.

When using Typescript, resolvers passed into `buildFederatedSchema` can be typed with the [GraphQLResolverMap](https://github.com/apollographql/apollo-tooling/blob/933c3d44b9e5fb7e3c0b462f60ce5b2d7875b15d/packages/apollo-graphql/src/schema/resolverMap.ts#L7) interface defined from [apollo-graphql](https://www.npmjs.com/package/graphql).

e.g.

```typescript
import { GraphQLResolverMap } from 'apollo-graphql';

/**
 * service graphql resolvers.
 */
const resolvers: GraphQLResolverMap<Context> = {
  Query,
  Mutation,
  Foo,
  DateTime,
};
```

When looking at the type for `GraphQLResolverMap` you can see that resolvers can be typed with `GraphQLFieldResolver`. This type does not work correctly with `__resolveReference` though and can cause unintentional errors.

When looking at the api reference of [__resolveReference](https://www.apollographql.com/docs/apollo-server/api/apollo-federation/#__resolvereference), `context` is the second argument when in `GraphQLFieldResolver`, `context` is the third argument.

e.g.

```typescript
import { GraphQLFieldResolver } from 'graphql';

import * as Models from '../../db/models';
import * as Schema from '../generated/schema-types';
import { Context } from '../helpers/context';

/**
 * Given the id, resolves the Foo model.
 */
// NOTICE: This function is broken.
// GraphQLFieldResolver usage is wrong! Notice `context` should be second argument.
const __resolveReference: GraphQLFieldResolver<{ id: Schema.Foo['id'] }, Context, null> = async (
  reference,
  _args,
  context
): Promise<Models.Foo> => {
  return await context.fooLoader.load(reference.id);
};
``` 

- [ ] A **simple**, runnable reproduction!
      Please make a GitHub repository that anyone can clone and run and see the
      problem. Other great ways to demonstrate a reproduction are using our
      CodeSandbox template (https://codesandbox.io/s/apollo-server), or re-mixing
      our Glitch template (https://glitch.com/~apollo-launchpad).
-->

**Comment by dncrews** [comment]
That's because `__resolveReference` isn't a `GraphQLFieldResolver`, it's a `GraphQLReferenceResolver`, but I don't know if that's exported anywhere.

**Comment by aleccool213** [comment]
Got it working 🎉

e.g.

```typescript
import { GraphQLReferenceResolver } from '@apollo/federation/src/types';
```

Thank you @dncrews

**Comment by Kosta-Github** [comment]
@aleccool213 would you mind to show the full working example?

**Comment by aleccool213** [comment]
I was able to export it but after spending some time trying to implement it, it doesn't work as expected.

Lets say you want to use this type as such:

```typescript
import { GraphQLReferenceResolver } from '@apollo/federation/src/types';

import { Context } from '../helpers/context';

const __resolveReference: GraphQLReferenceResolver<Context> = async (
  reference: { id: Schema.FooBar['id'] },
  context: Context,
) => {
  return await context.fooBarLoader.load(reference.id);
};

const FooBar = {
  __resolveReference,
};

export { FooBar };
```

And then import this resolver into a resolver map for apollo-server to use:

```typescript
/**
 * Upload service graphql resolvers.
 */
const resolvers: GraphQLResolverMap<Context> = {
  FooBar,
};
```

This will error because `GraphQLReferenceResolver` is not a part of the compatible types inside `GraphQLResolverMap`. It makes sense as Apollo Federation is new. I will create a separate issue for this type to be added there.

**Comment by aleccool213** [comment]
New issue here: https://github.com/apollographql/apollo-server/issues/3921

**Comment by DarkLite1** [comment]
I'm fairly new to TypeScript and also struggling a bit with this. The code below throws this error:

> TS7006: Parameter 'object' implicitly has an 'any' type.

```js
const typeDefs = gql`
  extend type Query {
    me: User
  }
  type User @key(fields: "id") {
    id: ID!
    name: String
    username: String
  }
`const resolvers = {
  Query: {
    me() {
      return users[0]
    },
  },
  User: {
    __resolveReference(object) {
      return users.find((user) => user.id === object.id)
    },
  },
}
```
Converting the code above to be TS compatible I tried:
```js
  User: {
    __resolveReference(object: GraphQLReferenceResolver['reference']) {
      return users.find((user) => user.id === object.id)
    },
  },
```
I'm probably doing something wrong. If you can tell me what I'm doing wrong that would be nice.

**Comment by DarkLite1** [comment]
Oh, my bad. I need to define an `interface` for each `type`:
```js
interface UserInterface {
  id: string
  name: string
  username: string
  birthDate: string
}
// resolvers
User: {
    __resolveReference(object: UserInterface) {
      return users.find((user) => user.id === object.id)
    },
  },
```

I expected this to be done automatically. Anyway, sorry for hijacking the threat.
