### ISSUE TITLE
__resolveReference within the same service

### ISSUE THREAD

**Issue by tvvignesh** [apollographql/apollo-server#3670]
Hi. I have been using Apollo Federation and while __resolveReference has worked great for resolving data between microservices, what do we do if we want to use __resolveReference within the same service? 

Say there are 3 or 4 types in the same GraphQL service and I want to return ID and use __resolveReference within the same service. I have noticed that it only works when used in some other service.

Any thoughts? Thanks.

**Comment by queerviolet** [comment]
This isn't currently supported. `__resolveReference` rehydrates the parent object from a key—the expectation is that within a service, the parent resolver will already have been called, so you shouldn't have to rehydrate anything.

I agree that it would be nice for a resolver to be able to return `{ id: 1 }` and have the child receive an appropriately exalted model reference, but this would require hooking execution more deeply than we currently do.

Our current recommendation here is to take your `__resolveReference(forType:)` logic and put it in a function that's accessible to all resolvers.

**Comment by tvvignesh** [comment]
@queerviolet Thanks a lot for your reply. Yup. That makes a lot of sense. Will go ahead with whatever is supported now. You may close this issue if you want :-)

**Comment by HunderlineK** [comment]
This would be a really useful feature. One way to hack around it is to define a type and resolver like this:

In Schema:
```
type Entity { id: ID!, details: EntityDetails }

```

In resolvers:
```
Entity: { details ({ id }, undefined, context) { return context.dataSources.entityApi.getById(id) } }
```
