### ISSUE TITLE
Uploads option maxFileSize not working correctly

### ISSUE THREAD

**Issue by phuo1032** [apollographql/apollo-server#3703]
I am setting up an file upload server with apollo-server-express. I have the following configuration for instantiating the ApolloServer:

```
const apolloServer = new ApolloServer({
	typeDefs,
	resolvers,
	uploads: {
		maxFileSize: 1000000 // 1 MB
	})
```
And the resolver code as the following:

```
const upload = async(parent, { file }, context) => {
	const { createReadStream } = await file;
	const stream = createReadStream();
	// rest of the stream handling code
}
```

If I try to upload a 2MB file, instead of getting the error
`File truncated as it exceeds the ${maxFileSize} byte size limit`, the code proceeds as usual. But I could tell the stream only contains about 1MB of data if I tried to pipe it to a physical file (which would never end because the stream seems to be problematic.

This seems to return the expected error if I tried a relatively small maxFileSize like 1000 or 10000. Anything I am doing wrong?

**Comment by phuo1032** [comment]
Followed up on this. I changed the dependency of graphql-upload to 10.0.0. It resolved this issue but looks like it is incompatible with the latest apollo-server-express. I got an uncaught exception instead of properly handled and returned by the server.

**Comment by dakshshah96** [comment]
@phuo1032 This is what worked for me: https://github.com/apollographql/apollo-server/issues/3508#issuecomment-662371289

**Comment by glasser** [comment]
Integration with a fork of an old version of `graphql-upload` was removed from Apollo Server last year in AS3.
