### ISSUE TITLE
sendVariableValues does not send variables to the Apollo Engine

### ISSUE THREAD

**Issue by armeny007** [apollographql/apollo-server#3732]
After adding sendVariableValues: { exceptNames: ['password'] } to the apollo.config.js, query variables still are not sent to the Apollo Engine.

package: "apollo-server-express": "2.9.7"

Here is my apollo.config.js file
module.exports = {
  client: {
    service: 'servicename',
    includes: ['./webapp/imports/app/**/*.js'],
  },
  engine: {
    apiKey: '*******',
    sendVariableValues: { exceptNames: ['password'] },
  },
};

Here is a screenshot from apollo engine:
<img width="1312" alt="Graph Manager | ********@devel | Metrics 2020-01-28 20-06-21" src="https://user-images.githubusercontent.com/34646451/73287182-e4dc4080-4209-11ea-8abe-db67c2143f82.png">

**Comment by abernix** [comment]
`ApolloServer` doesn't utilize `apollo.config.js` unless you've done something to make that work (e.g. `require`-ing the file; but probably don't do that, these are not meant to be the same interfaces, **yet** at least).

Put another way, `sendVariableValues` should be put into the `EngineReportingOptions` (i.e. the `engine` object) on the `ApolloServer` constructor's options.

See the [API documentation here](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#enginereportingoptions).


```javascript
const server = new ApolloServer({
  engine: {
