### ISSUE TITLE
missing documentation for `uploads` option

### ISSUE THREAD

**Issue by gabor** [apollographql/apollo-server#3745]
when configuring an `ApolloServer` instance, file-upload-related options can be set using the `uploads` variable, for example:
```
const server = new ApolloServer({
    uploads: {maxFieldSize: 1000}
});
```

this option is missing in the api-server api reference, available here: https://www.apollographql.com/docs/apollo-server/api/apollo-server/

**Comment by ebickle** [comment]
Ran into the same issue here. Had to dig through the source.

**Comment by glasser** [comment]
Integration with a fork of an old version of `graphql-upload` was removed from Apollo Server last year in AS3.
