### ISSUE TITLE
graphql-upload unreliable mime type

### ISSUE THREAD

**Issue by WillSquire** [apollographql/apollo-server#3759]
File parsing middleware `graphql-upload` returns a file mime type using `busboy`, however the mime type it returns is not foolproof and it might lead to holes if it's taken at 'face value'. It might be better to check this alongside something like `file-type` as it can easily be tricked. I've tested this.

Package: apollo-server-core
Version: 2.9.16

**Comment by jaydenseric** [comment]
The `mimetype` property is only provided for convenience; it is documented that this comes from the client and can't be trusted:

> File MIME type. Provided by the client and can’t be trusted.
> — https://github.com/jaydenseric/graphql-upload#type-fileupload

If verifying the MIME type of the upload is something you need to do in your resolver, you can analyse the read stream yourself. This is not always necessary and complicates dependencies and how the stream should be handled so I don't think it should be done by default.

**Comment by glasser** [comment]
Integration with a fork of an old version of `graphql-upload` was removed from Apollo Server last year in AS3. Suggestions for `graphql-upload` should be filed in [its repository](https://github.com/jaydenseric/graphql-upload), though the above comment is by its main author.
