### ISSUE TITLE
Apollo Server Express - CORS issue

### ISSUE THREAD

**Issue by brunocrosier** [apollographql/apollo-server#3760]
According to the Apollo docs for Express, the way to enable CORS is in the .applyMiddleware({app}) function
I have tested this and it doesn't work. My setup is exactly the same as this: https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-express#express except that the applyMiddleware now looks like this:

```
server.applyMiddleware({
  app,
  cors: {
    credentials: true,
    origin: new RegExp("/*/")
  }
})
```

Still, on my frontend I get a CORS error: 

"Access to fetch at 'https://blablabla.now.sh/graphql' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

I'm going crazy trying to figure this out - any ideas how to make it work?

**Comment by gusMoreno** [comment]
I have the same issue, but I am using `apollo-server-azure-functions`. I tried everything, and it works with postman and insomnia, but doesn't work in browser.

```
exports.graphqlHandler = server.createHandler({
  cors: {
    origin:         '*',
    exposedHeaders: 'Authorization',
    allowedHeaders: 'Authorization',
    credentials:    true,
  }
})
```

I got the same error as @brunocrosier does.

How can I fix it??

**Comment by nikhilunni511** [comment]
@brunocrosier @gusMoreno  I got the same error and fixed the issue by doing the following things : 

- set cors origin as the client url and credential as true at server side

`  cors: { origin: CLIENT_URL, credentials: true },`

- and set `credentials: include` at client side

>   When responding to a credentialed request, the server must specify an origin in the value of the Access-Control-Allow-Origin header, instead of specifying the "*" wildcard.

**Comment by abernix** [comment]
I don't believe this is a problem with Apollo Server.  The express integration directly passes the options to [`cors`](http://npm.im/cors):

https://github.com/apollographql/apollo-server/blob/53f9021923f0cb74c5df730f38e1217e85a9ffed/packages/apollo-server-express/src/ApolloServer.ts#L174-L179

Please consider the suggestion from @nikhilunni511 or investigate the problem more generically outside of the context of Apollo Server itself.

**Comment by miliu99** [comment]
I got the same problem and already spend hours on it and tried many options but no luck. @nikhilunni511 suggestion is not very clear -- where do I put "credentials: include"? If I do 

`const client = new GraphQLClient({ url: config.graphql.URL, credentials: include });`

I got this error: `'include' is not defined`

`const client = new GraphQLClient({ url: config.graphql.URL, credentials: 'include' });`

I got no error, but it didn't help either.

 Can you post the exact code? Strange thing is that I have another project with the same settings but that one works.

**Comment by miliu99** [comment]
OK, I got it working now. It turns out the error message is completely unrelated to my problem - it has nothing to do with CORS. In my case, it had included a file from wrong path. If I had looked at the CloudWatch log, I would have figured it out right away, but I was misled by the message and looking for CORS all the time. I could have deleted my previous post, but i think it might help somebody down the road running into similar problems. So, check the CloudWatch log first!

**Comment by ashalfarhan** [comment]
Is there any solution with my issue,
i'm trying to deploy both difference, client in netlify, and server in heroku
`server`
```ts
const whitelist = [
    "http://localhost:3000",
    process.env.CLIENT_URL,
  ];

app.use(
    cors({
      credentials: true,
      origin: whitelist,
    })
  );
```
`client`
```ts
const gqlApi = isDev
  ? "http://localhost:4040/graphql"
  : process.env.REACT_APP_GQL_API + "/graphql";

const httpLink = createHttpLink({
  uri: gqlApi,
  credentials: "include",
});

const client = new ApolloClient({
  // link: ApolloLink.from([authLink, refreshTokenLink, errorLink]),
  link: ApolloLink.from([authLink, refreshTokenLink, errorLink, httpLink]),
  cache: new InMemoryCache(),
  // uri: gqlApi,
  // credentials: "include",
});
```

Have been trying to toggle the comments but got the same issue, if i run locally, it works but not with production
`
Access to fetch at 'https://adm-haans.herokuapp.com/graphql' from origin 'https://dashboard-haans.netlify.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by glasser** [comment]
@ashalfarhan I don't think there's enough information to debug here, but also noting that the problem here probably isn't with apollo-server, given that you are (reasonably) disabling AS's cors support. Is process.env.CLIENT_URL actually https://dashboard-haans.netlify.app?
