### ISSUE TITLE
How to do live-reload

### ISSUE THREAD

**Issue by nsisodiya** [apollographql/apollo-server#380]
I am using react-apollo.
My problem is - When I make some changes in express server based app, I have to manually reload the browser tab at `http://localhost:3000/graphiql`.
IMHO , we should provide something like

```
app.use('/graphiql', graphiqlExpress({
  endpointURL: '/graphql'
  livereload: true
}));
```

**Comment by helfer** [comment]
I think this could be really neat!

**Comment by nscarlson** [comment]
+1

**Comment by stubailo** [comment]
There hasn't been any movement in this direction yet, but this could be neat! Please reopen if you're interested in working on this :]

**Comment by kettanaito** [comment]
How do you think the technical side of this feature would look like?

It's possible to achieve HMR with webpack, I believe it should be possible to find out when the schema gets updated. The only thing which needs to be updated is the interface itself (meaning all the fields/types descriptions, etc.). I don't think that re-applying the middleware would cause the desired effect.

I would be glad to know how that's theoretically possible.

**Comment by linonetwo** [comment]
I'm auto reload server by npm-script:
```json
{
"scripts": {
    "start": "concurrently \"nodemon --ignore ./server/generated/ -e graphql --exec 'yarn gql2flow'\" \"NODE_ENV=development nodemon --ignore ./server/generated/ -e js --delay 0.9 ./index.dev.js\"",
    "serve": "NODE_ENV=production node ./index.prod.js",
    "flow-typed": "rimraf flow-typed/npm && flow-typed install --overwrite || true",
    "gql2flow": "yarn build-schema && yarn gql-gen && yarn gqlJson2flow",
    "build-schema": "node ./scripts/buildSchema.js > ./server/generated/schema.graphql",
    "gql-gen": "mkdir -p ./server/generated && apollo-codegen introspect-schema ./server/generated/schema.graphql --output ./server/generated/schema.json",
    "gqlJson2flow": "gql2ts ./server/generated/schema.json -e $PWD/scripts/@gql2ts-language-flow.js -o ./server/generated/types.flow.js --ignore-type-name-declaration && prettier-eslint \"./server/generated/*.js\" --write"
  }
}
```
But GraphiQL web page won't reload introspection automatically.
