### ISSUE TITLE
GraphQLError: Unknown fragment - Validation failed.

### ISSUE THREAD

**Issue by LunaticMuch** [apollographql/apollo-server#3801]
Hi,

I am dealing with a strange error, probably not a bug, but cannot find anything in the doc can point me to right direction. 
Simple schema:
```graphql
type Query {
    entity: Entity
}

type Entity {
    field1: String
    field4: EntityChild
}

type EntityChild {
    fieldA: String
    fieldB: String
    fieldC: String
}

fragment Children on EntityChild {
    fieldA
    fieldB
    fieldC
}
```

I wish to place a query like 

```graphql
query {
  entity {
    field1
    field4 {
      ...Children
    }
  }
}
```

The schema and query are semantically correct. But fragment does not appear.
I am using `apollo-server": "2.10.1"` and my simple server is
```typescript
import * as fs from 'fs';
import { makeExecutableSchema, ApolloServer } from 'apollo-server'

const typeDefs = fs.readFileSync("schema3.graphql", "utf8").toString();

const jsSchema = makeExecutableSchema({
  typeDefs,
})

const server = new ApolloServer({
  schema: jsSchema,
  introspection: true,
})

server.listen({ port: process.env.PORT || 4000 }).then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`);
});
```

(this is a lean version of my server, cut everything out to reproduce the case).  Error message is:
```javascript
       "message": "Unknown fragment \"Children\"."
```

I am wondering if I must load the fragment in a different way, but did not find anything useful online. Interestingly, the fragment does not appear in the playground as part of the documentation/schema. Any help is much appreciated.

thanks
LM

**Comment by abernix** [comment]
The `fragment` isn't part of the schema.  It should be sent with in the `query` from the client.
