### ISSUE TITLE
Consider providing an option to disable the "x-powered-by" header

### ISSUE THREAD

**Issue by scottohara** [apollographql/apollo-server#3812]
**Affected package/version**: `apollo-server@2.10.1`

# Issue description
When using `apollo-server` (*without* explicitly calling `server.applyMiddleware()`), the out-of-box configuration defaults internally to `apollo-server-express`.

Responses from this default server include the following response header:

```
X-Powered-By: Express
```

As per Express [Production Best Practices: Security](https://expressjs.com/en/advanced/best-practice-security.html#at-a-minimum-disable-x-powered-by-header), consider disabling this header to avoid unnecessary disclosure to potential attackers that the server is running Express.

Alternatively, consider providing an option in the `ApolloServer` constructor to allow developers to opt into, e.g.

```js
const server = new ApolloServer({
  ...opts,
  disable: 'x-powered-by'
});
```

The presence of this header is commonly flagged by security scanning tools such as Netsparker.

# Steps to reproduce

Assume `NODE_ENV=production` (playground disabled).

### Server setup
```js
const { ApolloServer } = require('apollo-server');
const server = new ApolloServer({ ...opts });
(async () => {
	const { url } = await server.listen()
	console.log(`🚀  Server ready at ${url}`);
})()
```

### Request
```
GET / HTTP/1.1
Host: localhost:4000
Accept: */*
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
Connection: Keep-Alive
```

### Response
```
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Content-Type: application/json
Access-Control-Allow-Origin: *
```

Note the presence of the `x-powered-by` header in the response.

# Additional notes
It is possible to disable the header when using `apollo-server-express` directly, e.g.

```js
const express = require('express');
const { ApolloServer } = require('apollo-server-express');
const server = new ApolloServer({ ...opts });

const app = express();
app.disable('x-powered-by');  // <- ** HEADER DISABLED HERE **
server.applyMiddleware({ app });

app.listen({ port: 4000 }, () =>
  console.log(`🚀 Server ready at http://localhost:4000${server.graphqlPath}`)
);
```

However developers following the [Getting Started](https://www.apollographql.com/docs/apollo-server/getting-started/) guide, which uses code similar to the reproduction above, should be set up for success by defaulting to a server configuration that adheres to Express best practices for security.

**Comment by abernix** [comment]
PR welcome!

**Comment by andrewmcgivery** [comment]
@abernix Just wondering, does it make sense to introduce generic properties for adding and removing static headers? For example, I may want to add headers similar to ones that the Helmet package adds and I'm not sure if that is possible now if not using the express middleware.

**Comment by abernix** [comment]
@andrewmcgivery Your proposal seems like a bigger conversation. Perhaps we can just disable this default Express header for now without any configuration?  I don't think it adds much value in its current reveal of the server being "Express".

@scottohara, @pauloedurezende others: Thoughts of just disable the header for now, without a top-level configuration setting which I'd rather not introduce for this?

**Comment by abernix** [comment]
I think in the future, the transport abstraction (#3184, #3576, #2360) will be the place where any such default headers would be set.  It is not currently an easily accomplished feat with the current integration packages.

**Comment by scottohara** [comment]
@abernix 

I’d be happy with just disabling the x-powered-by header by default for now.

I’d like to create a PR with that change if it’s likely to be accepted?

**Comment by abernix** [comment]
@scottohara Unless someone objects, I think that would be fine and welcome.  However, it's worth noting that @pauloedurezende opened a PR recently which referenced this issue and I left a comment on it: https://github.com/apollographql/apollo-server/pull/3821#issuecomment-590287342.  Perhaps the adjustments can just be made to that PR, otherwise, a new PR would be welcome.

And if anyone watching objects to disabling this default header in the `apollo-server` integration, please speak up!  (Also worth noting: anyone can disable this in `apollo-server-express` by calling  `app.disable('x-powered-by');` on their own Express `app`!)

**Comment by scottohara** [comment]
Yep, thanks @abernix; I noticed that PR was already up after my earlier comment (so I edited accordingly).

I’ll wait to see if the other PR progresses or stalls. Thanks.

**Comment by andrewmcgivery** [comment]
@abernix I'm good with the simple disable of the header change.

However, I'm still wondering if it is worth shipping apollo-server-express with the helmet middleware out of the box to encourage security best practices. Is there any downsides to that approach that you can think of?

**Comment by abernix** [comment]
@andrewmcgivery I agree with the idea generally, but introducing those middleware, which  might be carefully placed in existing `app`'s middleware chain, would be a breaking change for some deployments.  Additionally, these might be more restrictive than are desired by some!

As noted above: in a not-too-distant version of Apollo Server, this functionality will all live in an HTTP-specific transport in future versions.  We plan on providing a production best-practice / pre-flight guide to supplement that pattern, and including `helmet` in there seems reasonable, to me!

**Comment by andrewmcgivery** [comment]
@abernix Thanks!

**Comment by abernix** [comment]
https://github.com/apollographql/apollo-server/pull/3821
