### ISSUE TITLE
Update schema (typedefs and resolvers) without downtime

### ISSUE THREAD

**Issue by loicmarie** [apollographql/apollo-server#3824]
**This issue is a Feature Request:**

It would be great to be able to easily **update the schema** (typedefs and resolvers), without downtime.

**Why :** some teams use entity-based management tools in order to manage a tremendous quantity of types. In this case, imports and exports **schemas are automatically generated**.

While using Apollo with graphQL seems to be a perfect fit for those applications, Apollo lacks of some methods / pipelines / tools for handling streamed schema updates without downtime.

I already tried to use the schema auto-update ability of Graph Manager, but as far as I understand, it is not designed to update resolvers.

This has already been mentioned in some issues, but:
- the issue has been closed with a very doubtful workaround using non-documented methods
- the case was concerning the dev environment (hot reload with webpack for example), not a process of continuous schema updates in production
- the case was very particular (no need for updating resolvers) and has been resolved using Graph Manager

**This issue is a Doc Request too:**

I think schema hot/streamed update is a very important feature, and I am very surprised that it is not documented at all in Apollo docs. Moreover, this feature does not appear in v3 roadmap.

If this is not possible, the doc should precise it. (or precise that it is in the roadmap)
If this is possible, it would be great to explain how to accomplish this.

**Comment by MStumpp** [comment]
Interested online schema updates (types + resolvers) too.

**Comment by cramatt** [comment]
Maybe related to https://github.com/apollographql/apollo-server/issues/1275?

**Comment by glasser** [comment]
Agreed, this is solved as stated in #1275 because this is what the `gateway` interface implements. Could be better documented, though.
