### ISSUE TITLE
BUG: tracing is using local time client making the request in reporting response times when using PLAYGROUND on deployed server

### ISSUE THREAD

**Issue by maapteh** [apollographql/apollo-server#3831]
When we did show the advantages of dataloaders we used a computer (so our client, our visitor so to say) with a local time 1 minute behind real time.
This resulted in the fact that the trace reports being off with 60000ms. And not only in 'graphql playground' but also 'Graph Manager' which makes it super weird to trust these metrics which are vital for us.

![report engine](https://i.imgur.com/UmpkRmO.png)

## Setup

We are [using](https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-express):
```
        "apollo-server": "2.10.1",
        "apollo-server-express": "2.10.0",
```

with:

```
    const server = new ApolloServer({
        schema,
        introspection: true,
        tracing: true
```

so nothing fancy. 

## Reproduce
To reproduce simply change your local-time :) For playground i dont really care so much if its off. But these results will also be in Apollo engine (now Graph Manager) and thats a real disadvantage.

**Comment by abernix** [comment]
Sorry, I don't understand your claim at all.  Can you try to explain this in a different way and provide actual bullet-points of your reproduction steps, server configuration, server time, client time, what is "client", testing method, what relation the use of Dataloader and computer date-time have with each other, etc?

**Concretely:** The request latency graph you're showing indicates that there were a number of requests (there's no indication of how many requests you sent; you've shown a request latency graph but omitted the number of requests) that took over a minute but 99% of all requests finished in _under 252ms_.  Further, 99.9% (p999) of all requests finished in less than 39.5seconds.  That's slow, but I don't understand the relation to dataloader or client date.

> It's also worth noting that `tracing` and `engine` are different configuration/packages which gather timing in identical but duplicative ways.  One is for GraphQL Playground visibility (`tracing`) and one is for aggregation and reporting in Graph Manager (`engine`).  You touch on both here, but I thought I'd note it before I continue.

Regardless of the package, all timing captured is based on the server that captures the traces, not based on any date from the client itself.  Resolvers are wrapped and have start-time and end-times captured.  In the event of using `engine` (Graph Manager), clock skew between individual servers reporting data is handled by Apollo Graph Manager's ingress.  You can see all the fields in the trace that is transmitted to Apollo Graph Manager (again, when `engine` is enabled, this has nothing to do with `tracing`) in [this protobuf definition](https://github.com/apollographql/apollo-server/blob/d8ade4df4d343cd2ad441ebcb88c87a7f986dde6/packages/apollo-engine-reporting-protobuf/src/reports.proto#L154).  If you're using `tracing`, you can see the entirety of the mechanism in [this file](https://github.com/apollographql/apollo-server/blob/062e6a3a76f00c6f9c5253c1db00f77ba4a74ae4/packages/apollo-tracing/src/index.ts).  If you're seeing _something_ in GraphQL Playground, it would be helpful to share a screenshot of what you mean.

**Comment by maapteh** [comment]
ok i will try, we wanted to show the effect of dataloader. It has nothing, but really nothing to do with this bug report. Its only because when showing the resolvers we found this weird reporting in the tracing tab. 

We saw response times of minutes, while actually visually were resolving in milliseconds! Then we used more computers as clients to go to this playground. They all had different times because not correct with auto data-time on the notebooks then we tested with offset of 7 minutes and saw that it gave tracing of 7minutes plus.

**Comment by maapteh** [comment]
13:47 now, i set clock to 11:47 of my notebook. I go to playground. Locally the trace shows correct metrics it resolves in 22ms avg. Now i go to the deployed playground on k8s cluster with default AMS timezone. I do the same query:

![bug](https://i.imgur.com/TNExJ3G.png)

So on the server itself the tracing is correct. But when i go to playground and use a machine with a browser and a local time way off it will influence the trace report being sent. This result is then also stored in Graph. I know playground must be off in Production but on staging we have it on and want to make decisions based upon it. Then we need to know for sure the data is from real users.

**Comment by maapteh** [comment]
Its good that playground is an unidentified client at the moment, so i can filter it out in our data collection. Maybe we should set the playground client to `name: 'playground', version: '2.0.1'` for example?

**Comment by maapteh** [comment]
@abernix is it now clear?

**Comment by maapteh** [comment]
i cant reproduce it anymore. Only locally the tracing is off with 2 hours but not in the engine report!
