### ISSUE TITLE
[BUG][Federation Gateway]: GraphQLError when query union types containing field with same name but different type

### ISSUE THREAD

**Issue by IvayloAndonov** [apollographql/apollo-server#3832]
### Taking this schema example :

![Screenshot 2020-02-26 at 13 32 11](https://user-images.githubusercontent.com/10476819/75341279-c6b34000-589c-11ea-99cb-ef784a972c4b.png)

### With this resolver for the `Body` union type:
![Screenshot 2020-02-26 at 13 33 24](https://user-images.githubusercontent.com/10476819/75341408-0a0dae80-589d-11ea-8e2e-5f4f926f70d8.png)

### With this query:
![Screenshot 2020-02-26 at 12 14 38](https://user-images.githubusercontent.com/10476819/75341476-375a5c80-589d-11ea-83cc-9ad085210835.png)I am getting the error `"GraphQLError: Cannot query field \"url\" on type \"TextAttributes\""`  even if we have inline fragments in the query ( `...on Text {}`, `...on Image {} `)

Obviously, that the issue here comes from `attributes` field name which is defined for both types - `Text` and `Image` and seems that for some reason it looks for `Image.attributes.url` in `Text` type as well.

**My question is** : is that _GraphQL Apollo Server_ union type limitation ( when union types contains same field name but with different type ) or I'm missing something and some piece of schema def is wrong ?

**NOTE**: if I rename the `attributes` field name to be unique foe each union type, it works fine.

**UPDATE** : This issue is produced only when using **Apollo Federation** , the query is executed against the Apollo's Gateway which expose the data from different underlying data services.
If we send the same query agains the particular underlying service - it works fine without any errors.

**Comment by nialloc9** [comment]
Any update on this? Also causing a problem here.

**Comment by jhampton** [comment]
Hello!  Can @nialloc9 or @IvayloAndonov please paste the specific versions of @apollo/gateway and @apollo/federation are in use here?  The gateway is the most important, and I'd love to know what version is resolved (yarn.lock or package-lock.json).  Thanks!

**Comment by IvayloAndonov** [comment]
Hello @jhampton , thanks for your response!
- apollo: `2.24.0` ( root )
- @apollo/federation: "^0.11.2", resolves to version `"0.11.3"` in yarn.lock ( service package )
- @apollo/gateway: "^0.10.8",  resolves to version `"0.10.9"` in yarn.lock ( gateway package )

**Comment by abernix** [comment]
@IvayloAndonov Thanks for opening this issue.  Can you put together a _runnable_ reproduction (e.g. a GitHub repository that can be cloned, or a CodeSandbox/Glitch) that demonstrates this problem?

**Comment by gsgalloway** [comment]
Seems to have been patched in `@apollo/gateway: "0.14.0"`
