### ISSUE TITLE
Why, just absolute paths are allowed in serviceList for apollo-gatway?

### ISSUE THREAD

**Issue by sherazali123** [apollographql/apollo-server#3861]
I have a situation here, from docker i get host name as simple string like "gms-customers" which is alive host and received response when i ping but unfortunately, apollo-gateway is not supporting it. I have no way around at the moment. Is there any other way around? more details are here https://stackoverflow.com/questions/60534429/access-docker-container-from-another-docker-container

**Comment by abernix** [comment]
Can you provide a bit more of an example?  Are you saying that when the `url` in a `serviceList` record is literally `gms-customers` it doesn't work?  Is there an error message?

**Comment by abernix** [comment]
Happy to discuss more with additional context!
