### ISSUE TITLE
printFederatedSchema produces invalid syntax when field description contains double quotes

### ISSUE THREAD

**Issue by coyotebush** [apollographql/apollo-server#3864]
[CodeSandbox reproduction](https://codesandbox.io/s/hidden-mountain-xw944)

Add to the schema in a federated service:
```graphql
type Query {
  """
  This is a description containing "double quotes".
  """
  hello: String
}
```

The federated service will work on its own, but the response to `{ _service { sdl } }` will contain
```graphql
type Query {
  "This is a description containing "double quotes"."
  hello: String
}
```
which fails to parse in Apollo Gateway (`Syntax Error: Expected :, found Name "quotes"`). Expected outcome is a syntactically valid schema equivalent to the original.

It looks like the graphql-js implementation of printSchema would handle this correctly, because it prints all descriptions as block strings and escapes instances of `"""` within the description.

**Comment by njg-nf** [comment]
I ran into this error too. Rather amateurish mistake tbh, and pretty annoying since you'll need to go through the comments in the entire schema to work around it.
