### ISSUE TITLE
Apollo-server-koa returns not found

### ISSUE THREAD

**Issue by theerfan** [apollographql/apollo-server#3883]
When I run a basic Apollo Server using the code provided [here](https://github.com/apollographql/apollo-server/blob/master/README.md),
Everything works out as planned and http://localhost:4000/ opens the playground.
But when I try to run the Apollo-Server-Koa example as specified [here](https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-koa),

http://localhost:4000/graph just returns a "not found" string and nothing else.
What could be the problem here?

Koa: ^2.11.0
Apollo-server: ^2.11.0
Apollo-server-koa: ^2.11.0
Node: v12.16.1
OS: Windows 10 x64

**Comment by abernix** [comment]
What is the exact output — copy-pasted — from your terminal from running that Koa example?  Are you accessing `http://localhost:4000/graph` or `http://localhost:4000/graphql`?

**Comment by theerfan** [comment]
![image](https://user-images.githubusercontent.com/11455681/76415117-deff8080-63ad-11ea-930b-402dd4fdcebb.png)

**Comment by theerfan** [comment]
Apparently this is an issue caused by VSCode's terminal's inability to print emojis, localhost:4000/graphql works fine.
