### ISSUE TITLE
In apollo-server-lambda how to use apollo-server-testing

### ISSUE THREAD

**Issue by rongliangduan** [apollographql/apollo-server#3899]
In apollo-server-lambda how to use apollo-server-testing 
am use jest to do test,  don't want use apollo client to send request to test in local, i found apollo server testing library , but  in apollo-server-lambda how to config this

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Lambda integration. Check out the [`@as-integrations/aws-lambda`](https://www.npmjs.com/package/@as-integrations/aws-lambda) package; this new package is maintained by Lambda users and implements support for the API Gateway v1 and v2 protocols. If you need to work with different AWS projects, you may be able to add that support to that package, or take another approach such as combining the [`@vendia/serverless-express`](https://www.npmjs.com/package/@vendia/serverless-express) package with Apollo Server 4's built-in `expressMiddleware` (this is the same approach that `apollo-server-lambda` takes in AS3). Sorry for the delay!

(Also, in AS4 there's just one ApolloServer class, not one per web integration, and you can use its `executeOperation` method (the replacement for `apollo-server-testing`) without needing to think about a particular web integration at all.)
