### ISSUE TITLE
POST body missing. Did you forget use body-parser middleware?

### ISSUE THREAD

**Issue by wcl1ll** [apollographql/apollo-server#3904]
koa2 service  apollo-server-koa 2
const Koa = require('koa');
const app = new Koa();
const views = require('koa-views');
const json = require('koa-json'); 
const onerror = require('koa-onerror');
// const bodyparser = require('koa-bodyparser');
const bodyparser = require('koa-bodyparser-graphql');
const logger = require('koa-logger');
const { ApolloServer, gql } = require('apollo-server-koa');
const typeDefs = gql(require('./graphql/types'));
const resolvers = require('./graphql/resolvers');

import { database } from './mongoDb/index'

const index = require('./routes/index');
const users = require('./routes/users');

onerror(app);
database();
app.use(bodyparser());

app.use(json());

app.use(logger());

app.use(require('koa-static')(__dirname + '/public'));

app.use(views(__dirname + '/views', {
  extension: 'pug'
}));

// logger
app.use(async (ctx, next) => {
  const start = new Date();
  await next();
  const ms = new Date() - start;
  console.log(`${ctx.method} ${ctx.url} - ${ms}ms`)
});

app.use(index.routes(), index.allowedMethods());
app.use(users.routes(), users.allowedMethods());

const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: ({ ctx }) => ({
    headers: ctx.req.headers
  }),
  cors: true,
  formatError: error => console.log(error)
});

server.applyMiddleware({ app });

app.on('error', (err, ctx) => {
  console.error('server error', err, ctx)
});

module.exports = app;

**Comment by wcl1ll** [comment]
in appllo service 2, it call we can use koa-bodyparser instead of koa-bodyparser-graphql
but it can't work

**Comment by glasser** [comment]
We no longer maintain a Koa integration; we recommend the use of [`@as-integrations/koa`](https://www.npmjs.com/package/@as-integrations/koa) with Apollo Server 4 and Koa-specific issues using it should be directed to their repository.
