### ISSUE TITLE
cacheControl: true does not set cache-control HTTP response header

### ISSUE THREAD

**Issue by mrdulin** [apollographql/apollo-server#3905]
Code here: 
```js
const server = new ApolloServer({
  typeDefs,
  resolvers,
  tracing: true,
  // use LRU-memory cache by default
  plugins: [responseCachePlugin()],
  // set cache-control HTTP response header as expected
  // cacheControl: {
  //   defaultMaxAge: 5,
  // },
  // bug? DOES NOT set cache-control HTTP response header
  cacheControl: true,
});
```
actual behavior: 

`cacheControl: true` DOES NOT set cache-control HTTP response header. Got response header from client-side for the first  HTTP request:
```
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 684
ETag: W/"2ac-uXuoDGX2oaj8jK/XpKo4wccGK8U"
Date: Fri, 20 Mar 2020 09:48:51 GMT
Connection: keep-alive
```
It cached the response with LRU-memory cache as expected.  Got response header for the second HTTP request:

```
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
age: 6
Content-Length: 134
ETag: W/"86-8WX9qaWLvLqy3LqMARxicFplfgY"
Date: Fri, 20 Mar 2020 09:52:30 GMT
Connection: keep-alive
```
As you can see, there is a `age:6` HTTP response header indicates the time of the response that has been cached. Which means the second request hit the cache and the response payload will load from  LRU-memory cache rather than graphql resolver.

expected behavior:
it should set `cache-control: max-age: 40, public` HTTP response header. I also tested `cacheControl: { defaultMaxAge: 5 }`, it works as expected.  

Besides, if I use `cacheControl: true`,  the response payload will contain `extensions` and `tracing` fields. 

First request:
![image](https://user-images.githubusercontent.com/17866683/77154171-271d5200-6ad6-11ea-8903-5fd0a4d12323.png)

second request(hit the cache):
![image](https://user-images.githubusercontent.com/17866683/77154221-3e5c3f80-6ad6-11ea-97b0-71feed1436ed.png)

`tracing` field disappears.

If I use `cacheControl: { defaultMaxAge: 5 }`,  the reponse payload will NOT contain `extentions` 
 and `tracing` fields, like:

![image](https://user-images.githubusercontent.com/17866683/77154030-e32a4d00-6ad5-11ea-97c1-03530a6b2f28.png)

I am confused about this different behavior.

package versions:
```json
"apollo-server-testing": "^2.11.0",
"apollo-server-plugin-response-cache": "^0.3.11",
```

minimal reproducible code repo: https://github.com/mrdulin/apollo-graphql-tutorial/tree/master/src/caching/01

**Comment by glasser** [comment]
See https://github.com/apollographql/apollo-server/issues/2918#issuecomment-1284745114
