### ISSUE TITLE
When using ApolloServer express middleware, HTTP POST request (errors/fails) is sent to ApolloServer at 2-3 second intervals.

### ISSUE THREAD

**Issue by pbergeron** [apollographql/apollo-server#3937]
![image](https://user-images.githubusercontent.com/4247325/78156572-97946f00-7404-11ea-87ec-b180a713550e.png)

`{"errors":[{"message":"GraphQL introspection is not allowed by Apollo Server, but the query contained __schema or __type. To enable introspection, pass introspection: true to ApolloServer in production","locations":[{"line":2,"column":3}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}]}`

I tried to disable introspection (introspection: false in ApolloServer config), but still get the error.

How do I stop the repeated middleware POST request to the ApolloServer?

**Comment by abernix** [comment]
If you have GraphQL Playground (or other clients, which behave similarly) open, it will try to refresh the schema every 2000ms by default.

These can be safely ignored, but this client-side behavior also be disabled in the _Settings_ on GraphQL Playground by changing `schema.polling.enable` to `false`.  Making that change will require that you manually update the schema when you want it to reflect the most recent value available from server introspection.  Alternatively, the `schema.polling.interval` can be changed to a higher value to reduce the frequency.  If you've disabled introspection on the server-side, then having it enabled on your client is not necessary.

![Screen Recording 2020-04-08 at 11 10](https://user-images.githubusercontent.com/841294/78760686-32072c00-798a-11ea-83f5-a258de86ed8b.gif)
