### ISSUE TITLE
Questions:How to close server?

### ISSUE THREAD

**Issue by codenoobforreal** [apollographql/apollo-server#3938]
I used the constructTestServer method from the tutorial from the picture below and just wondered if the server return from the constructTestServer method has a close or shutdown method. 

![image](https://user-images.githubusercontent.com/18373253/78177071-197daa00-7490-11ea-9bdd-c07dd3c28ce6.png)

I can use it on testing in afterAll method

![image](https://user-images.githubusercontent.com/18373253/78177615-fb647980-7490-11ea-934a-ad882501683e.png)

**Comment by abernix** [comment]
You should be able to call the [`.stop`](https://github.com/apollographql/apollo-server/blob/7ad9897c411d61df492bb2e52c4832d2c285b4d3/packages/apollo-server-core/src/ApolloServer.ts#L656-L663) method.  I can't tell which integration of `ApolloServer` you're using, but if it's `apollo-server`, it will additionally stop the Express server, [as seen here](https://github.com/apollographql/apollo-server/blob/6597e396c788dd079a76711bbb5d08d1d96daf8f/packages/apollo-server/src/index.ts#L134-L141).
