### ISSUE TITLE
Minor version bump for graphql-tools required for GraphQL 15 compatability

### ISSUE THREAD

**Issue by zackdotcomputer** [apollographql/apollo-server#3954]
Ran into a low-urgency bug when I tried updating to graphql 15:

## Currently:
Currently, most of the packages within this apollo-server monorepo have a dependency on `graphql-tools` pinned to `^4.0.0`.

## Problem:
Because of how npm handles transitive dependencies, machines with an earlier version of graphql-tools installed than the current 4.0.7 will not be updated to the latest version. That is, unless they manually add their own dev dependency, as this repo has in the root (package.json)[https://github.com/apollographql/apollo-server/blob/master/package.json].

This is a problem for future `graphql: ^15.0.0` support, as graphql-tools 4.0.7 or higher will be required because it adds support for the new graphql package names.

## Solution:
I suggest updating pinned versions in the package.json files to `"graphql-tools": "^4.0.7"`. Then npm will update to that version.

**Comment by dandv** [comment]
I'd love it if graphql-tools were updated directly to v6 per the [chore](https://github.com/apollographql/apollo-server/pull/4156), so we can do only one major version compatibility test instead of two (v5, v6).

v6 also [fixes this enum issue](https://github.com/ardatan/graphql-tools/issues/715#issuecomment-638526540).

**Comment by wtrocki** [comment]
> I'd love it if graphql-tools were updated directly to v6 per the chore, so we can do only one major

It is very important to have Apollo server using latest graphql-tools. Lots of community members now updating the to latest GraphQL-tools that have significant improvements, but Apollo-Server internally still uses 0.4.0. This brings issues with typing - community packages that were creating custom directives using GraphQL-Tools might stop working after update etc. 

6 GraphQL tools is fixing many different issues, so most of the project would not be able to avoid having two different versions. etc.

**Comment by glasser** [comment]
Going to handle this over at #4865.

**Comment by glasser** [comment]
OK, two parts to this:
- I'm going to do the suggested 4.0.0 -> 4.0.7 dependency bump as part of the release branch https://github.com/apollographql/apollo-server/pull/4922 (in fact, I'll go to 4.0.8, the final v4 version, which puts in the right peer dep)
- I've filed https://github.com/apollographql/apollo-server/issues/4923 to consider upgrading graphql-tools as part of AS3 (or dropping the dependency)
