### ISSUE TITLE
405 Apollo supports only GET/POST requests

### ISSUE THREAD

**Issue by joel-cunningham** [apollographql/apollo-server#3958]
I have used apollo-server-lambda on a AWS ApiGateway HttpApi (currently in beta) endpoint. I have done this previously but when I tried this today I got "405 Apollo supports only GET/POST requests" error when I hit the endpoint.

I figured out this was because newly created endpoints default to payload format version 2.0 which causes this 405 issue. Changing back the endpoint integration back to 1.0 fixes the issue.

Is it possible to support payload format version 2.0 in AWS ApiGateway?

https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

**Comment by michaelmerrill** [comment]
Hey @abernix, just want to check if this is on your radar? I know you're busy and working on 3.0. It's been 6 months since this was posted and there are quite a few other issues related to this.
