### ISSUE TITLE
apollo-server-env NPM scripts block all Windows development

### ISSUE THREAD

**Issue by ebickle** [apollographql/apollo-server#3961]
Package: apollo-server-env
Version: master (GitHub)

The `clean` script of `package.json` in the `apollo-server-env` package contains the Unix-specific commands `rm` and `cp`. The `prepare` script references `npm run clean` and `npm run compile`, causing an `npm install` of `apollo-server-env` to always fail on Windows.

```
  "scripts": {
    "clean": "rm -rf dist",
    "compile": "tsc && cp src/*.d.ts dist",
    "prepare": "npm run clean && npm run compile"
  },
```

This issue blocks all Windows development of `apollo-server`. The base apollo-server package.json calls lerna and runs an `npm install` on all packages. 

The `rm` command should be replaced with a cross-platform equivalent.

**Comment by abernix** [comment]
Hopefully fixed by #4043!  Thanks so much @mac2000 for opening that!
