### ISSUE TITLE
apollo-engine-reporting-protobuf NPM scripts block all Windows development

### ISSUE THREAD

**Issue by ebickle** [apollographql/apollo-server#3962]
Package: apollo-engine-reporting-protobuf
Version: master (GitHub)

The `prepare` and `pbjs` scripts of `package.json` in the apollo-engine-reporting-protobuf` package contains Bash-specific syntax, particularly invocation of `bash` as well calls to `mkdir`, `grep` and other Unix-only utilities. This causes an `npm install` of `apollo-engine-reporting-protobuf` to always fail on Windows and any other non-Bash environment.

```
  "scripts": {
    "prepare": "npm run pbjs && npm run pbts && cp src/* dist",
    "pbjs": "bash -c 'mkdir -p dist && apollo-pbjs --target static-module --out dist/protobuf.js --wrap commonjs --force-number <(grep -v \"package mdg.engine.proto\" src/reports.proto)'",
    "pbts": "apollo-pbts -o dist/protobuf.d.ts dist/protobuf.js"
  },
```

This issue blocks all Windows development of `apollo-server`. The base apollo-server package.json calls lerna and runs an `npm install` on all packages. 

The scripts should be modified to have cross-platform equivalents.

**Comment by glasser** [comment]
I think we fixed this in #4044 years ago, but we also removed the `prepare` script from `@apollo/reporting-protobuf` (the new name of this package) so that you don't need to run these scripts unless you're actively trying to update the reporting protobuf to a newer version.
