### ISSUE TITLE
Global Teardown Jest and apollo server

### ISSUE THREAD

**Issue by dmp2tech** [apollographql/apollo-server#3964]
Hello,
I would like to do unit tests for my server. I put a client in my tests, but I would like to start the server that is done with globalSetup but impossible to stop the server. I can't find the method to stop it. How to do ? thank you in advance

**Comment by abernix** [comment]
Are you looking for `.stop`?

**Comment by glasser** [comment]
I believe they are in fact looking for `.stop`.
