### ISSUE TITLE
[server@2.12.0] APQ registration causes "addProtobufError called before startTiming!"

### ISSUE THREAD

**Issue by vanwalj** [apollographql/apollo-server#3978]
I'm using `apollo-server-lambda` to serve a GraphQL Application in an AWS Lambda and `apollo-client` with `apollo-link-persisted-queries` so I can benefit from "persisted queries" feature

Upgrading to `2.12.0` broke the persisted queries requests, the server is now returning a 500 error whenever a client make a request using the persisted query extension

Here is a query exemple
```json
{"operationName":"Themes","variables":{},"extensions":{"persistedQuery":{"version":1,"sha256Hash":"abc5e6f7d2b18d51853698b172c002b7866af0cab36178a6867b8f0f92a61a60"}}}
```
And here is the server response
```json
{"errors":[{"message":"[internal apollo-server error] addProtobufError called before startTiming!","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}
```

Rollbacking `apollo-server-lambda` to `2.11.0` fixed the issue

**Comment by trevor-scheer** [comment]
Thanks for the report @vanwalj. Can you please provide a reproduction? We'll start looking into this today but anything helps.

**Comment by abernix** [comment]
Seems related to https://github.com/apollographql/apollo-server/issues/3627, which recently seems to have resurfaced https://github.com/apollographql/apollo-server/issues/3627#issuecomment-595747172 and was still present in `2.11.0`.

**Comment by abernix** [comment]
Looking into this now!

**Comment by abernix** [comment]
I tried to reproduce this, deploying all the way to Lambda using `serverless` (the precise instructions are [in our documentation](https://www.apollographql.com/docs/apollo-server/deployment/lambda/#deploying-with-the-serverless-framework), the only change I made was providing an `ENGINE_API_KEY` within the `environment:` property of `provider` within the `serverless.yml`).

However, I was unable to re-create this using `apollo-server-express@2.12.0` with Apollo Graph Manager enabled.

To move forward, we'll need much more precise reproduction steps (e.g. is this via `POST`, `GET`, directly invoked Lambda payload?, and as _many_ details as you can provide!), as nothing would seem to have changed in the 2.12.0 release that would triangulate to the manifestation you're seeing here.

**Comment by vanwalj** [comment]
Thank you @trevor-scheer and @abernix for your investigations, I will try this week to isolate the problem on my side so we can reproduce it, I'll keep you updated!

Thanks again!

**Comment by abernix** [comment]
Happy to re-open this if you're able to provide a reproduction, but I'm going to close it for now.
