### ISSUE TITLE
Apollo Gateway engineConfig for managed federation

### ISSUE THREAD

**Issue by tvvignesh** [apollographql/apollo-server#3982]
Hi. I have been using Apollo Gateway with managed federation for quite some time now and it used to work very well, but recently, I noticed an error in the gateway like this after upgrading dependencies:

![Screenshot from 2020-04-14 15-35-37](https://user-images.githubusercontent.com/1165845/79212818-c5969c00-7e65-11ea-98f4-029cc26fdbd6.png)

`Error checking for changes to service definitions: When `serviceList` is not set, an Apollo Engine configuration must be provided. See https://www.apollographql.com/docs/apollo-server/federation/managed-federation/ for more information.
When `serviceList` is not set, an Apollo Engine configuration must be provided. See https://www.apollographql.com/docs/apollo-server/federation/managed-federation/ for more information.`

Which did not come before. Since it is a managed federation, I don't have a serviceList and this is how I used to initialize my ApolloGateway:

```typescript
import { ApolloGateway, RemoteGraphQLDataSource } from '@apollo/gateway';
const gateway = new ApolloGateway({
        buildService(service) {
            return new RemoteGraphQLDataSource({
                url: service.url,
                willSendRequest: ({ request, context }) => {
                    request.http.headers.set('authorization', context.token);
                }
            });
        },
        debug: false
    });

const server = new ApolloServer({
        gateway,
        subscriptions: false,
        introspection: true,
        playground: {
            endpoint: config.apollo.playgroundEndpoint
        },
        engine: {
            apiKey: process.env.ENGINE_API_KEY,
            schemaTag: process.env.SCHEMA_TAG
        },
        context: async ({ req }) => {
            // Some code here....
            // Return variables
            return {variables};
        }
    });
```

May I know what changed I have to make? Looks like there are some new parameters but I don't find any documentation related to that.

For eg. I am not sure what to give in `federationVersion` which is a property of ManagedConfig as per this commit: https://github.com/apollographql/apollo-server/commit/f6ba2dea9b4f7c8aa602cad66398685d8bdbc3a2#diff-7b5e66976a637efc823826a985fa8e65

Thanks.

**Comment by abernix** [comment]
Can you provide the versions you were running before and the versions you're running now?  There are not any new parameters, and things should have remained the same for you between upgrades, aside from the breaking changes listed in the `CHANGELOG.md`.

**Comment by tvvignesh** [comment]
I used to run `@apollo/gateway` `^0.11.7` but now I am running `^0.14.0`

It doesn't seem to crash, but digging through the code I find a line like this:

```
if (!this.engineConfig) {
      throw new Error(
        'When `serviceList` is not set, an Apollo Engine configuration must be provided. See https://www.apollographql.com/docs/apollo-server/federation/managed-federation/ for more information.',
      );
    }
```

May I know if I am missing some config? Thanks.

**Comment by tvvignesh** [comment]
And the check seems to exist for remote and local config but I can't find one for managed config:

```typescript
if (isLocalConfig(config)) {
      return { isNewSchema: false };
    }

    if (isRemoteConfig(config)) {
      const serviceList = config.serviceList.map(serviceDefinition => ({
        ...serviceDefinition,
        dataSource: this.createAndCacheDataSource(serviceDefinition),
      }));

      return getServiceDefinitionsFromRemoteEndpoint({
        serviceList,
        ...(config.introspectionHeaders
          ? { headers: config.introspectionHeaders }
          : {}),
        serviceSdlCache: this.serviceSdlCache,
      });
    }
```

**Comment by tvvignesh** [comment]
I noticed when logging that `this.engineConfig` is coming out to be undefined for me and hence it is throwing the error. But, debugging why its undefined. Any ideas?

**Comment by tvvignesh** [comment]
@abernix I got the issue and looks like a bug. Its because of it being asynchronouse I guess.

When `loadServiceDefinitions` function is called for the first time `this.engineConfig` is not initialized leading to undefined, but later it gets the value in subsequent calls. So, for the first time, this condition turns out to be true if you log it but works subsequently.

```
if (!this.engineConfig) {
                console.log('this.engineConfig-----', this.engineConfig);
                throw new Error('When `serviceList` is not set, an Apollo Engine configuration must be provided. See https://www.apollographql.com/docs/apollo-server/federation/managed-federation/ for more information.');
            }
```

**Comment by abernix** [comment]
Your issue sounds somewhat connected to https://github.com/apollographql/apollo-server/pull/3979 which I'm cutting an `alpha` release for right now.  I'll let you know when it's ready.

**Comment by abernix** [comment]
I've just published `@apollo/gateway@0.14.1-alpha.0` with the fix provided by @trevor-scheer in #3979.  Try installing it and seeing if that resolves the problem for you?  (It's published on the `next` tag, but you can also just install it directly — e.g. `npm install @apollo/gateway@0.14.1-alpha.0` or `yarn add @apollo/gateway@0.14.1-alpha.0`)

**Comment by tvvignesh** [comment]
@abernix Perfect! Tried it out. This works.

**Comment by abernix** [comment]
Thanks for reporting it!

**Comment by abernix** [comment]
This has been promoted to `latest`.
