### ISSUE TITLE
Default value for a non-nullable argument

### ISSUE THREAD

**Issue by floriantz** [apollographql/apollo-server#3995]
According to the [GraphQL Spec](http://spec.graphql.org/June2018/#sec-Input-Object-Required-Fields) (unless I misunderstand it) it should be possible to have a non-nullable argument which has a default value in case the argument is undefined in the request (Not an explicit null).

Example:
```gql
type Query {
  Ressources(some_argument: ArgumentType! = "default" ): [Ressources!]!
}
```

We should be able to request Ressources while omitting the argument and get `"default"` in the resolver but it should not accept null as a value for `some_argument`.

**Comment by glasser** [comment]
I agree that you should be able to do that.

The implication is that doing this didn't work in Apollo Server, but you didn't provide any way for us to see that for ourselves, so I'm going to close this. Sorry for the delay!
