### ISSUE TITLE
Resolver parent's argument is not the same object as what was returned by the parent's resolver

### ISSUE THREAD

**Issue by fromi** [apollographql/apollo-server#4001]
If have a simple schema:
```
type Game {
  id: ID!
  players: [Player!]!
}
type Player {
  id: String!
}
```
I am trying to resolve a game and its players.
In the game's resolver, I return a object which is a decorator (from mongoose). Game.id and Player.id are [virtual getters](https://mongoosejs.com/docs/tutorials/virtuals.html). There are also functions like 'save' on that object.

Based on [the resolver's documentation](https://www.apollographql.com/docs/apollo-server/data/resolvers/#resolver-arguments), I expect to get the very same object provided as the parent in the Player resolver.
It does not work: I get passed some kind of serialized Game object where all my virtual fields and functions are gone.
The direct consequence is that I cannot properly serialize my objects "id" on 2 levels: the first level gets serialized properly because the id field is accessed by name here (with the default property serializer), but on the deeper level, the object are serialized some way before it gets to the resolvers, and the getter is already gone.

Is it the intended behavior, and the documentation is missing that information, or is it a bug?
How and why is the object serialized before it is passed to children resolver?

**Comment by HunderlineK** [comment]
I'm having a similar issue, some of the fields are completely missing and are undefined on the parent, while the actual object has them

**Comment by glasser** [comment]
Resolvers should receive the same object returned by the parent's field. I'm not sure exactly what the two of you are seeing, but it won't be possible to debug further unless I can see it on my own machine. I'll be happy to reopen this issue if it contains full instructions for seeing the issue without any creativity on my part; typically this involves a git repo I can clone or a codesandbox.io link, not just a short snippet of code.
