### ISSUE TITLE
Current DataSource design is not reentracy safe

### ISSUE THREAD

**Issue by erkkah** [apollographql/apollo-server#4011]
In short - since the `initialize` method is called on each request to prepare the DataSource - instance for processing the request, and the only reasonable way to keep context-specific state is in the DataSource - instance itself, any re-entrant requests will overwrite the context-specific state of previously started continuous requests.

**This can lead to a user getting access to another user's data**, since the contexts get mixed up.

This can be shown by creating a DataSource / resolver setup like this:

```js
const { ApolloServer, gql } = require("apollo-server");
const { DataSource } = require("apollo-datasource");

const typeDefs = gql`
  type Query {
    test: String
  }
`;

const resolvers = {
  Query: {
    test: async (_parent, _, context, _info) => {
      const dataSources = context.dataSources;
      const waitTime = dataSources.wait.requestSpecificData || 0;
      await new Promise(resolve => {
        setTimeout(resolve, waitTime * 1000);
      });
      return dataSources.wait.requestSpecificData;
    }
  }
};

let wait = true;

class WaitDataSource extends DataSource {
  constructor() {
    super();
    console.log("Creating a new WaitDataSource");
  }

  initialize() {
    this.requestSpecificData = wait ? 5 : 0.5;
    wait = !wait;
    console.log(`Initializing WaitDataSource, wait = ${wait}`);
  }
}

const dataSource = new WaitDataSource();

const server = new ApolloServer({
  typeDefs,
  resolvers,
  dataSources: () => ({
    wait: dataSource
  })
});

server.listen().then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`);
});
```
https://codesandbox.io/s/polished-snowflake-jdr3n

Running two or more of these queries concurrently will "randomly" return either 5 or 0.5 and wait 5s or 0.5s.

Expected: Each time the service waits 5s it should print 5s
Actual: Sometimes the printed time matches the waited time, sometimes not.

Looking at the implementation of [RestDataSource](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts) shows that it is vulnerable for this:
```typescript
initialize(config: DataSourceConfig<TContext>): void {
    this.context = config.context;
    this.httpCache = new HTTPCache(config.cache, this.httpFetch);
}  
```

Not sure what the original idea with running initialize on each request is? Reading from the confusion in other issues here, this is surprising. Also, the context is provided in each resolver call, there is no good reason for passing it to the DataSource.

I'm running apollo-server-lambda v2.10.1.

**Comment by MarMun** [comment]
[I have asked this on SO a while ago.](https://stackoverflow.com/questions/60709949/avoid-replacing-mixing-user-contexts-in-apollo-server-datasources-during-the-exe)

I still assume (as I got no answer on SO) this should solve the problem:

```
const server = new ApolloServer({
  typeDefs,
  resolvers,
  dataSources: () => ({
    wait: new WaitDataSource() <-- create new instance here
  })
});
```


As we are instructed in the docs:

> If you use this.context in your datasource, it's critical to create a new instance in the dataSources function and to not share a single instance. Otherwise, initialize may be called during the execution of asynchronous code for a specific user, and replace the this.context by the context of another user.

**Comment by erkkah** [comment]
Hey, @MarMun, thanks for the feedback. I did not find your SO post while googling.
I could not find the info in the docs you are referring to in the official docs. The implementation of RESTDataSource is confusing as well, since it stores the context _and_ creates a new HTTP cache on each request: https://github.com/apollographql/apollo-server/blob/e544af1c89ee032fcbe2cf6496f50439125d07cc/packages/apollo-datasource-rest/src/RESTDataSource.ts#L56-L59. 
I guess I don't see the point in recreating this heavy object on each request.

The current design is really counter-intuitive and error prone, and should at least be screamed out in the documentation.

**Comment by MarMun** [comment]
[You can find it here (second paragraph from the bottom)](https://www.apollographql.com/docs/tutorial/data-source/)

Aside from if it makes sense or not: Does creating a new instance on each request solve your problem of context mixing?

**Comment by erkkah** [comment]
I did not go that far down into the tutorial, since I thought I got what I needed from the reference part, thanks for pointing it out!

For my specific case, my workaround is to not use the datasource concept, since it does not give me any upsides. But absolutely, re-creating datasources on each request is a workaround for the context problem.

**Comment by Aeolun** [comment]
I would like to re-prioritize this bug. The request context in a data source is always the request context of the very last request that was sent to the server.

```
class LogDataSource extends DataSource {
  constructor() {
    super();
  }

  async getValue() {
    console.log(this.context.req); <--- prints out request context for last concurrent request for all the requests sent
  }
}
```

**Comment by moberegger** [comment]
```javascript
const server = new ApolloServer({
  typeDefs,
  resolvers,
  dataSources: () => ({
    wait: dataSource
  })
});
```

This should be 

```javascript
const server = new ApolloServer({
  typeDefs,
  resolvers,
  dataSources: () => ({
    wait: new WaitDataSource();
  })
});
```

The datasource needs to be instantiated on each request.
