### ISSUE TITLE
apollo-server-caching has no exported member 'testKeyValueCache'

### ISSUE THREAD

**Issue by mrdulin** [apollographql/apollo-server#4012]
I follow this [Testing cache implementations](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-caching/README.md#test-helpers) doc and try to test my custom key-value cache. When I import like this:

`keyValueCache.test.ts`:
```js
import { TestableKeyValueCache, testKeyValueCache } from 'apollo-server-caching';
```
TSC throw an error:
> import testKeyValueCache
'testKeyValueCache' is declared but its value is never read.ts(6133)
Module '"../../../../../../../../../Users/ldu020/workspace/github.com/mrdulin/apollo-graphql-tutorial/node_modules/apollo-server-caching/dist"' has no exported member 'testKeyValueCache'.ts(2305)

So I think maybe the doc is outdated. 

package versions: `"apollo-server-caching": "^0.5.1"`, `"typescript": "^3.8.3"`

**Comment by kdybicz** [comment]
just faced same issue :/

**Comment by glasser** [comment]
Yeah, I think you're right that the doc is outdated. I don't think we export that test suite helper any more; it can be used within the apollo-server repo but not outside.  I'm not sure if we should just remove the reference from the README or commit more to having this test helper be exported. Maybe it should even be a separate package with a jest dependency, vs making apollo-server-caching need to have a public API that depends on jest stuff?

**Comment by kdybicz** [comment]
One way or another, it would be nice to have a set of tests you guys use to test your cache implementation, as a base for tests of other people implementations. I was trying to use those built-in tests in a cache wrapper I wrote. In the end, instead of importing them from apollo package I ended up copying it all into my project. It working, but it's not ideal.

**Comment by glasser** [comment]
We no longer provide a test suite for implementations of `KeyValueCache`. That said, we expect the most common usage will be via `@apollo/utils.keyvAdapter` to wrap a Keyv implementation, and they should have their own tests.
