### ISSUE TITLE
ExpressContext interface inaccurate for subscriptions

### ISSUE THREAD

**Issue by johanlajili** [apollographql/apollo-server#4023]
**Package:** 
apollo-server-express@2.9.16
**Expected Behaviour:**
the **req** and **res** property of ExpressContext should be optional, because when in a subscription they are not present (that object only contain connection). So if I try to access req.headers, typescript should complain that req can be undefined. 

Actual Behaviour
**req** and **res** are not optional, meaning typescript doesn't complain and you can have a runtime error if you try to directly access, for instance, req.headers and you have subscriptions.

Reproduction: https://codesandbox.io/s/serene-faraday-5kz3f?file=/index.js

**Comment by glasser** [comment]
Direct subscriptions integration was removed from Apollo Server in v3 last year. (Partially because of how the old flimsy integration led to problems like this one.)
