### ISSUE TITLE
Add granular field-level caching

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-server#4042]
Currently, we use `@cacheControl` to inform:
- setting HTTP header
- saving full response in the cache

This is a feature request for adding:
- saving the value of each field (or resolver return value) in the cache

For instance if we send this query:

```gql
query {
  foo
}
```

and then this:

```gql
query {
  foo
  bar
}
```

and if `Query.foo` has a `@cacheControl`, I'd like the server to use the `Query.foo` value in the first query's response when responding to the second query (instead of calling the `Query.foo` resolver again).

**Comment by SachaG** [comment]
This is actually how I thought @cacheControl/setCacheHint worked in the first place, and it took me a while to understand that it didn't. I think this would be a very natural and "GraphQL-y" way of handling caching, personally.

**Comment by thexpand** [comment]
@glasser Is there a plan for the Apollo team to develop this as a separate plugin in the future?

**Comment by glasser** [comment]
There's no particular roadmapped plan to do so.
