### ISSUE TITLE
[Feature request] subscription fallback

### ISSUE THREAD

**Issue by sakulstra** [apollographql/apollo-server#4052]
### Problem
We're working with lot's of corporates where websockets are not necessarily reliably availabe throughout all our customers. As I get it, apollo-server subscriptions don't provide any fallback in case that in fact is the case.

### Feature request
*Disclaimer: I'm not quite sure if this is the correct repo to open this request as it actually relates to both server and client I guess.* 
It would be great if subscriptions would fall back to e.g. socket.io in case websockets aren't available for some reason to ensure the system still works even when websockets don't. Afaik meteor has sth similar built in - falling back to long polling.

### Expected behavior
I thought/hoped this would "just work" with the official packages. Never considered this not being baked in by default :sweat_smile:

### Actual behaviour
In edgecases it doesn't, and I didn't find any workaround yet.
https://github.com/apollographql/subscriptions-transport-ws doesn't have a fallback - there seem to be multiple now deprecated/never to apollo server 2 ported userland socket.io transport packages https://github.com/datoml/subscriptions-transport-ws.
In one of the blogpost `@live` was mentioned as an alternative, but was since then removed from the roadmap #2189 

### Packages
Apollo server <= 2.12

**Comment by intellix** [comment]
I'm not sure if it's enough but in the Client I just saw these methods in the client which may allow us to poll when down?

```ts
export const enum AppEvent {
  CW_WEB_SOCKET_DISCONNECTED = 'CW_WEB_SOCKET_DISCONNECTED',
  CW_WEB_SOCKET_RECONNECTED = 'CW_WEB_SOCKET_RECONNECTED',
}

const wsClient = new SubscriptionClient(`${endpoint}/graphql`, { reconnect: true });
const ws = new WebSocketLink(wsClient);

wsClient.onDisconnected(() => dispatchEvent(platform, AppEvent.CW_WEB_SOCKET_DISCONNECTED));
wsClient.onReconnected(() => dispatchEvent(platform, AppEvent.CW_WEB_SOCKET_RECONNECTED));
```

and then later:
```ts
fromEvent(document, AppEvent.CW_WEB_SOCKET_DISCONNECTED).subscribe(() => this.queryRef.startPolling(1000));
fromEvent(document, AppEvent.CW_WEB_SOCKET_RECONNECTED).subscribe(() => this.queryRef.stopPolling());
```

**Comment by glasser** [comment]
Apollo Server 3 does not have subscriptions built in.
