### ISSUE TITLE
[Feature request] Allow more control over error formatting

### ISSUE THREAD

**Issue by tylr** [apollographql/apollo-server#4054]
## Description
I believe the current `ApolloServer` configuration options lack necessary control to properly configure a production environment for logging, monitoring and error reporting. 

## Behavior
The issue I am having with the current options is that in order to enable stacktraces being logged I must both write a custom `formatError` function and set `debug: true`. While the `formatError` is useful the `debug` option is ambiguous as to what features this may or may not enable.

As far as I can tell `debug` affects the behavior of `ApolloServer` in two ways...

**1. Setting the log level**
https://github.com/apollographql/apollo-server/blob/fa42e36ff6601a7e7bd0b48fb4eb5ea9b6e71173/packages/apollo-server-core/src/ApolloServer.ts#L185

**2. Passed to `formatApolloErrors` to avoid calling `enrichErrors` that adds things like the stacktrace to the error**
https://github.com/apollographql/apollo-server/blob/fa42e36ff6601a7e7bd0b48fb4eb5ea9b6e71173/packages/apollo-server-errors/src/index.ts#L106

## Proposal
Given the ambiguity of `debug` I am hesitant to use this in production but without it I am unable to adequately log / monitor / diagnose production errors. I am also forced to check that the debug flag doesn't do something that would effect performance in production before upgrading versions.

I'd like to decouple the `debug` and provide more granular control over errors. Either by allowing me to configure wether or not `enrichErrors` happens or letting me dictate whether or not a stacktrace is included with the errors.

Otherwise, what is the convention for monitoring errors in production?

**Comment by mhart** [comment]
As well as this, we've looked into whether we can use a plugin with `didEncounterErrors` to log errors instead (in the hope that this isn't affected by the `debug` option), but we've run into an issue with that too: https://github.com/apollographql/apollo-server/issues/4055

**Comment by dandv** [comment]
Related: I've also found that for an AuthenticationError on a query with variables, `.source` contained only `.body`, and I couldn't find the variables anywhere in the error object.

**Comment by glasser** [comment]
We did in fact decouple the two unrelated features of this flag in Apollo Server 4; it is now called [`includeStacktraceInErrorResponses`](https://www.apollographql.com/docs/apollo-server/migration/#debug).
