### ISSUE TITLE
Missing dependency in package.json

### ISSUE THREAD

**Issue by jsumners** [apollographql/apollo-server#4061]
https://github.com/apollographql/apollo-server/blob/4e5c0f692564781ff3f1fc6f722a87210f63dcf6/packages/apollo-server-fastify/src/ApolloServer.ts#L16

That dependency is not listed in:

https://github.com/apollographql/apollo-server/blob/4e5c0f692564781ff3f1fc6f722a87210f63dcf6/packages/apollo-server-fastify/package.json#L27-L35

**Comment by glasser** [comment]
Duplicate of #4715
