### ISSUE TITLE
Playground sends periodically POST requests

### ISSUE THREAD

**Issue by juergenzimmermann** [apollographql/apollo-server#4067]
I want to switch from _GraphQL.js_ and _GraphiQL_ to Apollo Server and also Playground. Now I use _apollo-server-express 2.13.0_ and the according _apollo-server 2.13.0_, and all Jest-based tests are passing.

However, when I use the _Playground_ in the current Chrome browser the server receives tons of POST requests like the following, although I was submitting just *1* query, and the requests don't stop:

```
POST /api 200 48.563 ms - -
POST /api 200 12.315 ms - -
POST /api 200 16.632 ms - -
POST /api 200 64.937 ms - 94
POST /api 200 9.398 ms - -
POST /api 200 7.912 ms - -
...
```

**Comment by oguimbal** [comment]
I think that these are the schema polling requests :)

See [graphql playground](https://github.com/prisma-labs/graphql-playground#settings)

You can disable them here:
![image](https://user-images.githubusercontent.com/8973947/81067280-bb087900-8ede-11ea-92cd-6bc7f4bb3b82.png)

**Comment by juergenzimmermann** [comment]
@oguimbal Got it. Thank you very much for your support.
