### ISSUE TITLE
Middlewares execute many times

### ISSUE THREAD

**Issue by jorgeAM** [apollographql/apollo-server#4083]
Hi everyone. I've created a server with `apollo-server-express`  and y add a middleware to handle authorization header.

```
const app = express()

const config = {
  typeDefs,
  resolvers,
  context: ({ req }) => ({
    req,
    models,
    user: req.user
  })
}

const server = new ApolloServer(config)

app.use('/graphql', authenticationMiddleware)

server.applyMiddleware({ app, path: '/graphql' }
```
Inside my middleware and some query I've added a `console.log`

![image](https://user-images.githubusercontent.com/19254966/81361502-2bacc280-90a4-11ea-8e0b-7977f5a6832f.png)

As you can see, middleware don't stop executing.
Is something wrong with my code or there's a bug with library?

**Comment by glasser** [comment]
This doesn't provide enough information for us to try to reproduce your issue. For example, you don't include the line that prints "hi from middleware".
