### ISSUE TITLE
ApolloError name is always "Error" instead of "ApolloError"

### ISSUE THREAD

**Issue by itmayziii** [apollographql/apollo-server#4087]
**Package name and version**
apollo-server-express: 2.13.0

**The expected behavior**
It should be possible to determine if an error is an ApolloError or not but sadly it is not possible at this time. Currently in `apollo-server-errors/src/index.ts` there is a check for `if (!this.name` then set the name to ApolloError but this is impossible logic as this class extends the native Error object so name will always be `Error`. 

I believe this is a bug because it's clear in the code there is intention to set the name to 'ApolloError'.

**The actual behavior.**
Name is always 'Error' for ApolloErrors.

I would be happy to submit a PR to help fix this if this is in fact behavior you would like to fix.

**Comment by glasser** [comment]
As of Apollo Server 4, [there is no special ApolloError class](https://www.apollographql.com/docs/apollo-server/migration/#apolloerror) any more.  So the check you're looking for is now `if (false)` :)
