### ISSUE TITLE
typings: `GraphQLRequestListener` should maybe return `undefined`.

### ISSUE THREAD

**Issue by abernix** [apollographql/apollo-server#4103]
The review of #3988 (specifically this [[Review comment]]) yielded some questions (and learnings!) about the return values of the types which are returned from `GraphQLRequestListener` life-cycle methods.

This #3988 didn't introduce the concern, but the `void` return type is currently applied to the methods which are defined on a `GraphQLRequestListener`, which is [intended to be used](https://stackoverflow.com/a/58885486) when the return value of a function _will not be observed_ (sic).

https://github.com/apollographql/apollo-server/blob/db0e3780e4e2691ac675dcb7018bb4077c2de541/packages/apollo-server-plugin-base/src/index.ts#L73-L75

It's not clear what the intent of the original author of these types was and if the `| void` on the right side of this return-type union was intentional OR a conflation of "void 0 === undefined".  That's of question because we do "observe" the return type of these methods, however we only do that in order to determine if it's a function.  If it's not a function (the other left-side of the types), then we don't do anything with the value that is returned from it.

Arguably though, if anything else but a function is being returned from these life-cycle hooks, it could very well be an unintentional mistake.  On the other hand, it might just be the result of someone using a short-hand fat-arrow function return value.

Fixing this now would be a breaking change at compilation time, but is possibly worth introducing now (read: immediately) that it's been found.  Luckily breaking type changes are less controversial and this one would seem to be pretty easy to fix in any implementations which are currently returning _a value that is not a function_.

[Review comment]: https://github.com/apollographql/apollo-server/pull/3988/files#r421632153

**Comment by glasser** [comment]
I'm not a big fan of `x | void` but it does seem to be what TypeScript requires if you want a function that can either return a particular thing or skip `return` entirely. That said, #5295 (AS3) at least changes it so that the callbacks are consistently asynchronous, and it's just a matter of "after resolving the Promise, is there more stuff there or not", not "what model do we need to use to execute the callback?".
