### ISSUE TITLE
apollo-datasource-rest doesn't understand application/problem+json mime type

### ISSUE THREAD

**Issue by davedx** [apollographql/apollo-server#4110]
In RESTDataSource.parseBody, it checks the media type of an API response as follows:

      (contentType.startsWith('application/json') ||
        contentType.startsWith('application/hal+json'))

However there is an additional JSON mime type used in for example ASP.NET core to return non-200 JSON responses called "application/problem+json". [1] If an API returns a response with this mime type, you'll end up with a plaintext response in your graphql server code instead of a JSON object.

It seems fairly straightforward that this type should just be added to the above check. I'll make a PR

[1] https://tools.ietf.org/html/rfc7807

**Comment by abernix** [comment]
See:

* https://github.com/apollographql/apollo-server/issues/1976#issuecomment-441992398
* https://github.com/apollographql/apollo-server/pull/1645#issuecomment-439370832
