### ISSUE TITLE
CORS error on lambda only with multipart/form-data content type

### ISSUE THREAD

**Issue by eurobob** [apollographql/apollo-server#4112]
Similar to https://github.com/jaydenseric/apollo-upload-client/issues/131 , except I don't think the outcome is the same.

Making a standard post request works fine, but attaching a file does not.

```
Access to XMLHttpRequest at 'https://api.example.com/graphql' from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Happens on localhost and my live site.

When I run my graphql server with serverless-offline, it works perfectly.

## Server index.ts : 
(Using cross-fetch)
```
const server = new ApolloServer({
  schema,
  playground: {
    endpoint: '/dev/graphql',
  },
  introspection: true,
  context: ({ event, context }) => {
    const tokenWithBearer =
      event.headers.Authorization || event.headers.authorization || ''
    const token = tokenWithBearer.split(' ')[1]
    const user = getUser(token)

    return {
      headers: event.headers,
      functionName: context.functionName,
      event,
      context,
      user,
    }
  },
})

export const handler: APIGatewayProxyHandler = (event, context, callback) => {
  if (Object.keys(event.headers).includes('Content-Type')) {
    event.headers['content-type'] = event.headers['Content-Type']
  }
  const graphql = server.createHandler({
    cors: {
      origin: true,
      credentials: true,
      allowedHeaders: [
        'Accept',
        'Authorization',
        'content-type',
        'Content-Type',
        'Origin',
      ],
    },
  })
  return graphql(event, context, callback)
}
```

## Client setup:
```
const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: from([
    (operation, forward) => {
      operation.setContext({
        headers: {
          authorization: `Bearer ${Auth.getToken()}`,
        },
      });
      return forward(operation);
    },
    new createUploadLink({
      uri: "https://api.example.com/graphql",
      fetch,
    }),
  ]),
});
```

**Comment by mathix420** [comment]
I think you are uploading a too big file for AWS Lambda (https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html#w603aac11c66c15 => 6MB max).
You can confirm this by having a look into headers of failing request, you should see `RequestTooLargeException` or an HTTP Status Code `413`.

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Lambda integration. Check out the [`@as-integrations/aws-lambda`](https://www.npmjs.com/package/@as-integrations/aws-lambda) package; this new package is maintained by Lambda users and implements support for the API Gateway v1 and v2 protocols. If you need to work with different AWS projects, you may be able to add that support to that package, or take another approach such as combining the [`@vendia/serverless-express`](https://www.npmjs.com/package/@vendia/serverless-express) package with Apollo Server 4's built-in `expressMiddleware` (this is the same approach that `apollo-server-lambda` takes in AS3). Sorry for the delay!
