### ISSUE TITLE
Integration Testing for Subscriptions

### ISSUE THREAD

**Issue by andrewphillipo** [apollographql/apollo-server#4113]
Am I correct in saying that ```apollo-server-testing``` currently does not support subscriptions into a graphql server?  It would be really useful to support this; subscriptions are things that feel quite brittle and prone to people accidentally breaking them as they are transient - i.e. if you receive a notification it should change the UI under that even not before, so it is not immedately apparent that you have broken something. Maybe I'm misunderstanding but how do I go about writing integration tests in the same way as for mutation and query?

The expected behavior is I should be able to create a subscription that can be mocked with apollo-server-testing, event fired from it and I should receive the mocked notification/subscription event in my components. 

I guess this is somewhat of a feature request! Thanks for the amazing work you guys do on Apollo!

**Comment by Pat-Up** [comment]
This would be nice

**Comment by glasser** [comment]
Direct subscriptions integration was removed from Apollo Server in v3 last year. (Partially because of how the old flimsy integration led to problems like this one.)
