### ISSUE TITLE
Is subscriptions supported in apollo-server-fastify

### ISSUE THREAD

**Issue by Odonno** [apollographql/apollo-server#4114]
Hi,

I am trying to implement subscriptions with a `apollo-server-fastify` server. I am using a simple `pubsub` (in-memory). It seems ok but when I try to use it with the Playground I got this error:

![image](https://user-images.githubusercontent.com/6053067/81994857-1528dd00-9649-11ea-9c94-91ba2e764c5d.png)

Do you know how to fix this issue?

**Comment by Odonno** [comment]
Ok, I just found that I need to add the following line of code:

```ts
server.installSubscriptionHandlers(app.server);
```

**Comment by SyedAli00896** [comment]
Hi, can you please share your code of configuring subscriptions in apollo-server-fastify?
