### ISSUE TITLE
Enabling tracing wipes extension data, e.g. __queryPlanExperimental

### ISSUE THREAD

**Issue by godspeedelbow** [apollographql/apollo-server#4116]
Spent some time trying to figure out why `response.extensions.__queryPlanExperimental` was getting removed from the response [after it was set](https://github.com/apollographql/apollo-server/blob/9b2f1868aed30a720ec71d9bf7cceade6ff3776c/packages/apollo-gateway/src/index.ts#L733-L735).

Basically, when `config.tracing` is set to `true`, [it includes the `TracingExtension`](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/requestPipeline.ts#L402) which has a `format` method and [which will override whatever was set on `response.extensions`](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/requestPipeline.ts#L402.).

The expected behavior is that extension data does not get wiped. Or if it is the intended behavior, then I think it makes sense if there's an extension hook that gets called with `response` data, so that an extension can pluck the data it needs, e.g. `__queryPlanExperimental` and then format that data with the `format` method.

**Comment by godspeedelbow** [comment]
🦗 🦗

**Comment by abernix** [comment]
Can you try again with the latest version of Apollo Server, 2.14.1?  The tracing extension was recently ported to a new technique in Apollo Server 2.14.0 via #3991.

**Comment by glasser** [comment]
The `tracing` option and the `TracingExtension` (which created an old inefficient kind of inline trace) are no longer part of Apollo Server.
