### ISSUE TITLE
GET query missing  with apollo-server-fastify on PM2

### ISSUE THREAD

**Issue by winzaa123** [apollographql/apollo-server#4122]
Anyone found this issue?

i test my code javascript(build) with apollo-server-express on PM2 and run with ts-node on local it working but javascript(build) with apollo-server-fastify on PM2 not work :weary:  

PM2 on docker
apollo-server-express is plan B for production :grinning:

### my config 

![image](https://user-images.githubusercontent.com/15700798/82117811-05221200-979d-11ea-8fb6-70c7f7332416.png)

### Package    
"apollo-server-fastify": "^2.12.0"

![image](https://user-images.githubusercontent.com/15700798/82117793-dd32ae80-979c-11ea-9eb8-96994ec803e4.png)

![image](https://user-images.githubusercontent.com/15700798/82117730-6c8b9200-979c-11ea-8d87-74639add504a.png)

**Comment by EdwardGoomba** [comment]
My issue is that local works fine - when I go to deploy online w / fastify OR express - I run into the get query missing.

**Comment by StevenLangbroek** [comment]
Running into this issue as well now. Is there any info we can provide to help debug?

**Comment by StevenLangbroek** [comment]
Ok, found several issues while digging through the code:

- Use of old `addContentTypeParser` api
- Use of `request.req` instead of `request.raw`
- This causes the issue in `fastify@3`: `beforeHandler` had been renamed to `preHandler` for a while. If I change this in `node_modules` it works.

I'll work on a bugfix and open a PR>

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Fastify integration. Check out the [`@as-integrations/fastify`](https://www.npmjs.com/package/@as-integrations/fastify) package; this new package is maintained by Fastify users and most likely already solves the issue described above. Sorry for the delay!
