### ISSUE TITLE
docs: Do not suggest the use of makeExecutableSchema

### ISSUE THREAD

**Issue by tafelnl** [apollographql/apollo-server#4133]
When ApolloServer is used in combination with `graphql-tools` `makeExecutableSchema` sometimes all or some directives might not work. More specifcally this happens when someones uses `graphql-tools`@v5.0. For more info on this you can read here: https://github.com/ardatan/graphql-tools/issues/1462

In this doc:
https://www.apollographql.com/docs/graphql-tools/schema-directives/
the use of `makeExecutableSchema` is suggested. Which shouldn't in my opinion.

But in this doc: https://www.apollographql.com/docs/apollo-server/schema/directives/ (which I guess is newer) the following method is suggested:
```
const server = new ApolloServer({
  typeDefs,
  resolvers,
  schemaDirectives: {
    upper: UpperCaseDirective,
  }
});
```

This lets ApolloServer decide which version of `graphql-tools` to use, which seems much safer to me.

So I suggest to either remove the use of makeExecutableSchema in the docs or explicitly state which version(s) is/are safe to use.

**Comment by rplinzner** [comment]
I have lost 2 hours today because of that (my directives did not want to work at all). Please fix this ASAP!

**Comment by yaacovCR** [comment]
This should be fixed by the latest release of graphql-tools (v6), see further discussion within issue linked above, https://github.com/ardatan/graphql-tools/issues/1462

**Comment by bcarriereupgrade** [comment]
If you had to use `makeExecutableSchema` to turn on a specific option like `inheritResolversFromInterfaces` and you have `schemaDirectives` set in the Apollo server configuration options, eg:

```javascript
const server = new ApolloServer({
  schema: makeExecutableSchema({ typeDefs, resolvers, inheritResolversFromInterfaces: true }),
  schemaDirectives,
```

The directives will run through during schema definition, but the resolvers (if you change them) will get overwritten. So you have to make sure to include the `schemaDirectives` as a configuration to `makeExecutableSchema` eg,

 ```javascript
const server = new ApolloServer({
  schema: makeExecutableSchema({ typeDefs, resolvers, schemaDirectives, inheritResolversFromInterfaces: true }),
 /* removed schemaDirectives */,
```

**Comment by glasser** [comment]
In Apollo Server 3 we are:
- upgrading the version of graphql-tools used to support the `typeDefs`/`resolvers`/`mocks`/`mockEntireSchema` options (to a version that should fix the issue you ran into)
- not re-exporting any of the graphql-tools symbols from AS packages
- fine with you using your own graphql-tools package (or any mechanism of creating a `GraphQLSchema`!) if you'd like
