### ISSUE TITLE
Async resolve functions do not throw errors if they return undefined

### ISSUE THREAD

**Issue by jer-sen** [apollographql/apollo-server#4134]
When `allowUndefinedInResolve === false`, a resolver should throw an error if it returns undefined. But with an async resolver, no error is thrown.

`apollo-server-lambda@2.13.1`

**Comment by glasser** [comment]
This option is a parameter to `makeExecutableSchema`, a function that used to be part of Apollo Server but now is part of the separate `graphql-tools` project.

Additionally, it looks like this option was [removed from `graphql-tools` last year](https://github.com/ardatan/graphql-tools/pull/3081) (not mentioned in PR description but it's in the diff).
