### ISSUE TITLE
Feature Request: apollo-cache-control allow specifying cache control header name and value 

### ISSUE THREAD

**Issue by TLadd** [apollographql/apollo-server#4147]
Currently, apollo-cache-control sets the Cache-Control header [here](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-cache-control/src/index.ts#L168).

```
      o.graphqlResponse.http.headers.set(
        'Cache-Control',
        `max-age=${
          overallCachePolicy.maxAge
        }, ${overallCachePolicy.scope.toLowerCase()}`,
      );
```

When using a CDN, this works well if you're looking to cache responses in both the CDN and the browser. However, my current use case is to cache response data in the CDN but not the browser. That way, it is possible to purge the CDN's cache at an appropriate time and API consumers will immediately see the updated result. There are a couple of different ways of doing this depending on CDN. You can set `s-max-age` instead of `max-age` and Fastly has a [Surrogate-Control](https://docs.fastly.com/en/guides/configuring-caching#surrogate-control) header. In any case, having more control over the header that's set here would be helpful.

Not sure what API would make sense for this. A function passed into the plugin that takes maxAge and scope and returns name and value would be easy, but would prevent setting different headers for different queries. If you wanted a mishmash of different headers for different queries, it would get pretty complicated trying to annotate that information and merge it in a sensical way. My personal need is to always set `Surrogate-Control`, so a plugin-wide function would work for me.

**Comment by dumbNickname** [comment]
Hi,

I was just going through the issues and found this one as i have a similar problem. In my case we would like to set caching headers for different layers of the system - so possibly different caching times for browser, CDN and e.g. some HTTP accelerator such as Varnish. I was already thinking to write my own plugin inspired by cacheControl, but maybe such an extension would be welcome here?

My rough idea for API was to provide a kind of property-header mapping at plugin setup (will try to use the example from @TLadd here):

```
    cacheControl: {
      defaultMaxAge: 0,
      custom: { // yeah, name can be probably sth better
        cdnAge: {
          header: 'Surrogate-Control',
          default: 60, // optional
        },
      },
    },
```
and later use statements such as:
```
hello:String @cacheControl(maxAge: 5, cdnAge: 20)
```
If browser cache would not be needed then simply `maxAge` would be skipped. The delivered response would contain both headers  'Surrogate-Control' and `Cache-Control`, each consumed by another layer of the system or in the browser (in our case it might end up with 3 headers). 

From what I checked the plugin would need to be just slightly extended in all places where `maxAge` is processed and simply do the same for all entries provided in mapping. What would you say? Just let me know if interested as I will probably need to implement that anyway :)

**Comment by TLadd** [comment]
Yeah @dumbNickname, I ended up doing something similar to your proposal but as a nexus schema plugin, since that's what I'm using to build my schema anyways. I also added a cacheTags field that allows specifying an array of cache tags for a field (surrogate-key in Fastly or cache-tag in Cloudflare) so I can purge any query that contains a particular field when it is affected in a mutation.

**Comment by tomphilbin** [comment]
Hey @TLadd, @dumbNickname I've opened https://github.com/apollographql/apollo-server/pull/4288 which I think may resolve this. Please let me know if you have any feedback!

**Comment by glasser** [comment]
As described in https://github.com/apollographql/apollo-server/pull/4288#discussion_r588636299 you can just turn off the built-in HTTP header setting and set your own with a tiny plugin that runs after the cache-control plugin calculates the cache policy.
