### ISSUE TITLE
Reporting protobuf: conflict with other libraries (ERROR.prototype.toJSON)

### ISSUE THREAD

**Issue by miguelrcDEV** [apollographql/apollo-server#4160]
![image](https://user-images.githubusercontent.com/17248343/82799188-ed701b00-9e79-11ea-9283-2383c64b710d.png)

ERROR.prototype.toJSON has conflict with axios library. Please don't override ERROR functions.

![image](https://user-images.githubusercontent.com/17248343/82799333-2dcf9900-9e7a-11ea-867f-af7a34ab94f3.png)

**Comment by abernix** [comment]
That `Error` that you've identified is not the global `Error` object, it is a locally scoped `Error` function declared within `Trace.Error`:

https://www.runpkg.com/?apollo-engine-reporting-protobuf@0.5.0/dist/protobuf.js#1197

I agree with your premise that we shouldn't override the global `Error.prototype.toJSON`, but the last time there was an interoperability problem between Apollo and Axios, it didn't reveal that we were doing anything incorrectly: https://github.com/apollographql/apollo-server/issues/1433#issuecomment-514773285.

Please open a reproduction that demonstrates the problem you're experiencing, as requested when opening an issue.  Thanks!
