### ISSUE TITLE
📑 documentation request: file uploads with schema stitching

### ISSUE THREAD

**Issue by maxlever** [apollographql/apollo-server#4164]
[This page on file uploads](https://www.apollographql.com/docs/apollo-server/data/file-uploads/), which corresponds to [this file](https://github.com/apollographql/apollo-server/blob/master/docs/source/data/file-uploads.md), indicates that file uploads don't work with schema stitching. However, the [linked issue](https://github.com/ardatan/graphql-tools/issues/671) was resolved in [version 5 ](https://github.com/ardatan/graphql-tools/issues/1306) of graphql-tools. 

Can the documentation be updated to (a) confirm that graphql file uploads are working and (b) show the correct procedure to get file uploads to work with schema stitching? Thanks!

**Comment by iMitaka** [comment]
Is there any progress with documentation updates about this topic how to upload a file when from schema stitching gateway ?

**Comment by yaacovCR** [comment]
Apollo afaik supports graphql-tools v4 only. Later versions are maintained separately, with documentation unfortunately in some respects lagging functionality.

See a working example here: https://github.com/ardatan/graphql-tools/blob/master/packages/links/tests/upload.test.ts

Consider opening a pull request to help fill out discussion if you have time.

Note also that it may not be so advisable to simple proxy files to the subschema. You may wish to instead upload files to storage directly from gateway and send links to those endpoints to the downstream services.

**Comment by glasser** [comment]
Integration with a fork of an old version of `graphql-upload` was removed from Apollo Server last year in AS3.

We maintained some examples of how to use `graphql-upload` as part of the AS3 docs but have removed them in AS4; the `graphql-upload` docs would be the best place to look if you want to learn more about that package. (Apollo does not recommend the use of `graphql-upload` as doing uploads as we do not think it is [best practices](https://www.apollographql.com/blog/backend/file-uploads/file-upload-best-practices/) to do an upload as part of a GraphQL operation, and the protocol used by `graphql-upload` has serious [security concerns](https://github.com/jaydenseric/graphql-multipart-request-spec/pull/64) unless mitigated.)
