### ISSUE TITLE
2.14.0: apollo-server-testing createTestingClient broken

### ISSUE THREAD

**Issue by Tallyb** [apollographql/apollo-server#4170]
I am sorry for not deep diving into this any further, but this is more of a pre warning (as the version was released few hours ago). 

Running tests with apollo-server and apollo-server-testing at 2.14 results this error: 

TypeError: Cannot redefine property: Symbol(apolloServerExecutionDispatcherWillResolveField)
        at Function.defineProperty (<anonymous>)

      at Object.<anonymous> (../../node_modules/apollo-server-core/src/requestPipeline.ts:431:14)
      at fulfilled (../../node_modules/apollo-server-core/dist/requestPipeline.js:5:58)

Downgrading to 2.13.1 restores to working. 

### This bug report should include:

- [ ] A short, but descriptive title. The title doesn't need "Apollo" in it.
- [ ] The package name and version of Apollo showing the problem.
- [ ] If applicable, the last version of Apollo where the problem did _not_ occur.
- [ ] The expected behavior.
- [ ] The actual behavior.
- [ ] A **simple**, runnable reproduction!
      Please make a GitHub repository that anyone can clone and run and see the
      problem. Other great ways to demonstrate a reproduction are using our
      CodeSandbox template (https://codesandbox.io/s/apollo-server), or re-mixing
      our Glitch template (https://glitch.com/~apollo-launchpad).
-->

**Comment by pdemarino** [comment]
I've noticed exactly the same issue.

**Comment by abernix** [comment]
Thanks for reporting this!

@pdemarino Can you put together a minimal reproduction?

**Comment by abernix** [comment]
Hopefully fixed in 2.14.1 via https://github.com/apollographql/apollo-server/commit/79c00252d2a2ecf8604cf4d080da27d1572219a7.  Please report back if it's still problematic!

**Comment by Tallyb** [comment]
@abernix  - I can confirm it works for me.
