### ISSUE TITLE
Misleading type mentioned for 'formatResponse' in the docs

### ISSUE THREAD

**Issue by asif-ir** [apollographql/apollo-server#4186]
The type for `formatResponse` option is wrongly mentioned as `Function` though it is declared differently as `(response: GraphQLResponse | null, requestContext: GraphQLRequestContext<TContext>) => GraphQLResponse` in the code.

**_Docs Reference:_** https://github.com/apollographql/apollo-server/blob/master/docs/source/api/apollo-server.md#parameters

**_Code Reference:_** https://github.com/apollographql/apollo-server/blob/8059326ce43a776b6f34e1a6de4cb78da4e4a2b3/packages/apollo-server-core/src/graphqlOptions.ts#L48

(**Note:** This change was actually introduced in [this commit](https://github.com/apollographql/apollo-server/commit/8059326ce43a776b6f34e1a6de4cb78da4e4a2b3#diff-5102db46bcc7f6cc0c59149e9cc375d3).)

**Comment by dgurns** [comment]
Same issue here. Looks like the `formatResponse` function type should allow returning `GraphQLResponse | null`. 

Current:
```
formatResponse?: (
    response: GraphQLResponse | null,
    requestContext: GraphQLRequestContext<TContext>,
  ) => GraphQLResponse
```

Probably should be:
```
formatResponse?: (
    response: GraphQLResponse | null,
    requestContext: GraphQLRequestContext<TContext>,
  ) => GraphQLResponse | null
```

**Comment by glasser** [comment]
@asif-ir In general our API docs just say `Function` for any function type; if you need the more precise type, the TypeScript definitions are canonical.

@dgurns You're right that the typing looks wrong. Fixing in #5089.
