### ISSUE TITLE
plugins option missing in Apollo Server Koa constructor

### ISSUE THREAD

**Issue by rahul22048** [apollographql/apollo-server#4192]
There is an optional parameter called plugins inside apollo-server-express constructor or apollo-server constructor, but the same parameter is missing in apollo server koa constructor

**Comment by rahul22048** [comment]
@abernix :- This is the code snippet:-

const server = new ApolloServer({
    schema,
    context,
    tracing: true,
    plugins: [routingPlugin],
    playground: config.enablePlayground
  });

Above works fine for express, but while migrating to Koa, plugins option was giving error. We replaced apollo-server-express with apollo-server-koa package, for migrating to Koa from express.

**Comment by abernix** [comment]
@rahul22048 a PR would be welcome if you track it down!

**Comment by kubejm** [comment]
If this isn't actively being worked on, then I'd be willing to give this a look.

**Comment by kubejm** [comment]
@rahul22048 can you reproduce the issue and provide an example?  Is it possible your routing plugin needs to be adjusted to work with koa instead of an issue with apollo-server-koa?

I took a quick look at this and this appears to work as expected.  I took the example getting started snippet from https://github.com/apollographql/apollo-server/tree/main/packages/apollo-server-koa and added a simple plugin to investigate this issue and it appeared to work as expected.

Example with plugin:
```javascript
const Koa = require('koa');
const { ApolloServer, gql } = require('apollo-server-koa');

// Construct a schema, using GraphQL schema language
const typeDefs = gql`
  type Query {
    hello: String
  }
`;

// Provide resolver functions for your schema fields
const resolvers = {
  Query: {
    hello: () => 'Hello world!',
  },
};

const server = new ApolloServer({ 
  typeDefs, 
  resolvers,
  plugins: [{
    serverWillStart() {
      console.log('this is a plugin');
    }
  }]
});

const app = new Koa();
server.applyMiddleware({ app });
// alternatively you can get a composed middleware from the apollo server
// app.use(server.getMiddleware());

app.listen({ port: 4000 }, () =>
  console.log(`🚀 Server ready at http://localhost:4000${server.graphqlPath}`),
);
```

Output:
```bash
🚀 Server ready at http://localhost:4000/graphql
this is a plugin
```

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Koa integration. Check out the [@as-integrations/koa](https://www.npmjs.com/package/@as-integrations/koa) package; this new package is maintained by Ka users and most likely already solves the issue described above. Sorry for the delay!

(That said, I think the previous comment is correct and this probably was working at least in AS3.)
