### ISSUE TITLE
Not able to access parameters set in Koa Context Object when using apollo-server-koa package

### ISSUE THREAD

**Issue by rahul22048** [apollographql/apollo-server#4195]
Parameters like Koa.Context.Request, Koa.Context.Response are not accessible when using apollo-server-koa package. Whereas i am able to access these parameters , inside my custom routes , say health endpoint(/health), which i have myself added to routes. Upon digging on this issue i came across the couple of articles below, which could be the possible reasons for it:-

1) https://stackoverflow.com/questions/22148087/request-body-is-undefined-in-koa
2) https://stackoverflow.com/questions/54006318/ctx-request-body-is-undefined-with-nodejs

And i verified what the above articles say for my custom route (/health).

So, when i am on /graphql route, the onus is on apollo-server-koa , to correctly invoke body parsers , so that parameters are correctly set on Koa.Context object and is accessible everywhere inside the code.

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Koa integration. Check out the [@as-integrations/koa](https://www.npmjs.com/package/@as-integrations/koa) package; this new package is maintained by Ka users and most likely already solves the issue described above. Sorry for the delay!
