### ISSUE TITLE
[Question] GraphQL-Tools docs around directives is outdated?

### ISSUE THREAD

**Issue by wtrocki** [apollographql/apollo-server#4197]
GraphQL Tools received major bumps recently to version 6.0.0 and made multiple updates. However, this version is not working with the latest Apollo-Server versions that are still using 4.x

While the community understands that graphql-tools usage with Apollo will be deprecated in near future. There are still numerous of the entries in docs that rely strongly on GraphQL-tools:

https://www.apollographql.com/docs/apollo-server/schema/creating-directives/#gatsby-focus-wrapper

As library creator, I'm getting pings that my libraries do not work anymore with the latest graphql-tools, but using latest graphql tools can have some compatibility issues with Apollo sever.

Do you see providing some updates in near future on alternative ways to support stuff like custom directives etc.? 

Would ApolloServer recommend to create schema outside Apollo (instead of passing typedefs and resolves inside).
Any info would be amazing :)

**Comment by yaacovCR** [comment]
Just a gentle suggested edit to above, there are no current plans to deprecate graphql-tools -- the current apollo-server roadmap suggests that plan for v3 will be to deprecate *use* of graphql-tools within apollo-server, which I am guessing is what you are referring to.

Considering the recent reinvigoration of graphql-tools, my personal hope is that Apollo continues to use graphql-tools for a long time to come!

**Comment by wtrocki** [comment]
Made correction. I actually realized that most of the people will be using graphql-tools to create schema and then pass that to the Apollo client. 

So deprecation will be related with the passing GraphQL schema created by graphql-tools into Apollo? If graphql-tools will be used in server internally that will be amazing and resolve all problems. I'm going to close this issue as it was based on me wrongly interpreting the information.
