### ISSUE TITLE
Extensions property not getting set inside ApolloError object in case of network timeouts .

### ISSUE THREAD

**Issue by rahul22048** [apollographql/apollo-server#4207]
As per this documentation:- https://www.apollographql.com/docs/apollo-server/data/errors/ , extensions property is always set inside ApolloError object, but apparently it is not getting set when network timeouts occur. Either the documentation should clearly state that, extensions property is not set in case of network errors, or it should set the property in case of network timeouts as well.

**Comment by rahul22048** [comment]
Any update on the above issues

**Comment by glasser** [comment]
This issue doesn't have a self-contained reproduction so it's hard to understand exactly what it's about. For example, where are these network timeouts occurring? On calls made in resolvers? We've also simplified error serialization and normalization in Apollo Server 4, which perhaps maybe have helped with this issue?
