### ISSUE TITLE
Typescript Compliation errors on from old version of `graphql-tools`

### ISSUE THREAD

**Issue by TSiege** [apollographql/apollo-server#4219]
Currently I'm trying to use `apollo-server-fastify` `v2.14.1`. Anytime I run `tsc` I get the following error. It looks like `apollo-server-core` is running `graphql-tools@^4.0.0`. The latest `graphql-tools` is `@6.0.8`. As was suggested in another thread, manually installing the latest `graphql-tools` did not resolve the problem for me.
```
node_modules/apollo-server-core/node_modules/graphql-tools/dist/Interfaces.d.ts:29:18 - error TS2430: Interface 'IGraphQLToolsResolveInfo' incorrectly extends interface 'GraphQLResolveInfo'.
  Types of property 'mergeInfo' are incompatible.
    Type 'MergeInfo' is missing the following properties from type 'MergeInfo': replacementSelectionSets, replacementFragments, mergedTypes

29 export interface IGraphQLToolsResolveInfo extends GraphQLResolveInfo {
                    ~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

### This bug report should include:

- [ ] A short, but descriptive title. The title doesn't need "Apollo" in it.
- [ ] The package name and version of Apollo showing the problem.
- [ ] If applicable, the last version of Apollo where the problem did _not_ occur.
- [ ] The expected behavior.
- [ ] The actual behavior.
- [ ] A **simple**, runnable reproduction!
      Please make a GitHub repository that anyone can clone and run and see the
      problem. Other great ways to demonstrate a reproduction are using our
      CodeSandbox template (https://codesandbox.io/s/apollo-server), or re-mixing
      our Glitch template (https://glitch.com/~apollo-launchpad).
-->

**Comment by tobiasdiez** [comment]
If I understood this correctly, then graphql-tools has been removed/upgraded in the latest v3 branch. So maybe this issue can be closed/added to the v3 milestone or project?

**Comment by glasser** [comment]
Correct, `release-3.0` depends on new versions of a couple of the `@graphql-tools/*` packages but not on the old `graphql-tools` v4. Aiming for a final release this month.
