### ISSUE TITLE
Maybe has been moved from graphql/tsutils to graphql/jsutils

### ISSUE THREAD

**Issue by bumpusfrancus** [apollographql/apollo-server#4223]
[Issue 2621 ](https://github.com/graphql/graphql-js/pull/2621) of graphql moved Maybe from tsutils to jsutils.

**Comment by mark600211** [comment]
same issue

**Comment by wodka** [comment]
as this is an internal element from graphql-js it should probably be removed from apollo server
https://github.com/graphql/graphql-js/pull/2621#issuecomment-641927660
