### ISSUE TITLE
Incorrect type definition for `server.applyMiddleware({ app })` as listed in docs

### ISSUE THREAD

**Issue by nozzle-a** [apollographql/apollo-server#4225]
Version: apollo-server-express@2.14.2, express@4.17.1

I get a TS error using the [code that appears in the documentation](https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-express#express)

```
Type 'Server' is missing the following properties from type 'Application': router, settings, resource, map, and 3 more.
```
I believe this is due to the type definition in `ApolloServer.ts` which defines the `app` member as an `express.Application`, but `const app = express();` seems to be returning an `express.Server` object.

I'm happy to open a PR for this but the comments in the `ApolloServer.ts` file around this seem to indicate there are issues with changing the type definition here.

Or it's possible I'm just doing something wrong?

**Comment by nozzle-a** [comment]
Any update on this.  As it stands, I am unable to run the server using `ts-node` due to this error.

**Comment by nozzle-a** [comment]
I had a bad `@types/express` dependency in my package.json.  Once I fixed that, compilation worked as expected.

**Comment by HasBert** [comment]
As @nozzle-a pointed out correctly, you probably installed `npm install types/express --save-dev` instead of `npm install @types/express --save-dev`.

**Comment by sgup** [comment]
Same issue. I had copied `types/express` from a doumentation / example online.

**Comment by Note45** [comment]
I had the same issue. Run `yarn add -D @types/express` works for me.
