### ISSUE TITLE
Promote "Experimental" gateway hooks to "Supported," and provide documentation

### ISSUE THREAD

**Issue by jhampton** [apollographql/apollo-server#4227]
Like it says "on the tin".  I'm down for documenting these and talking about the promotion of these hooks.  I'd like y'all's input on whether/when this should happen.

REF: https://github.com/apollographql/apollo-server/blob/f71b61fdc3e7deca10522ee269595d4d2e7686bc/packages/apollo-gateway/src/index.ts#L57

**Comment by trevor-scheer** [comment]
Hey @jhampton, just finished talking this out with @abernix. If you have the time to take care of this with documentation included, let's do it! This will be a breaking change to the gateway, but very easy to correct when updating (and we're pre-1.0, and they're marked as `experimental_`, so not unexpected either!).

**Comment by jhampton** [comment]
Awesome, sounds good.  If y'all have a preexisting preference on how these should be named, please speak now :) @trevor-scheer

**Comment by trevor-scheer** [comment]
@jhampton Probably just removing the `experimental_` prefixes, I don't think we've had any complaints with the current naming.

**Comment by jhampton** [comment]
@trevor-scheer and @abernix Closing in favor of AS3/Gateway roadmap.
