### ISSUE TITLE
playground  load slow

### ISSUE THREAD

**Issue by menglingyu** [apollographql/apollo-server#4233]
## This is:
bug
## Specifications
OS: MacOS
Browser: Chrome

## Expected Behavior
playground load fast

##  Now

playground   Has been loading ，takes about a minute to load

**Comment by abernix** [comment]
The artifacts for playground are served [from a CDN](https://www.jsdelivr.com/package/npm/@apollographql/graphql-playground-react), and also includes a Google Font, etc.  If you are experiencing slowness, please check your connectivity to that CDN as the first step.  Your browser Developer Tools are likely to indicate the source of the slowness.

If you need it to work fully offline or need to avoid the CDN, you'll need to disable the default playground integration with `playground: false` and explore adding `graphql-playground-react` directly to your project: https://github.com/prisma-labs/graphql-playground/tree/master/packages/graphql-playground-react.

There is also the possibility of setting the `cdnUrl` in the playground settings to another CDN that can provide these artifacts which is more appropriate for your geographical location.

**Comment by menglingyu** [comment]
resolved   
https://fonts.googleapis.com/css  load slow ，if you don't Over the wall ，
find in node_modules/@apollographql/graphql-playground-html/dist/render-playground-page.js

and delete

`<link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|Source+Code+Pro:400,700\" rel=\"stylesheet\">\n`



![image](https://user-images.githubusercontent.com/19648678/84374640-df0f5680-ac10-11ea-87d3-cdbe7f5a871b.png)
