### ISSUE TITLE
Update/Maintain changelog for graphql-extensions

### ISSUE THREAD

**Issue by simhnna** [apollographql/apollo-server#4242]
The latest entry in the [changelog](https://github.com/apollographql/apollo-server/blob/master/packages/graphql-extensions/CHANGELOG.md) for graphql-extensions is for 0.1.0-beta

Would be nice to have a place to look at changes, especially since graphql-extensions is still using a 0.x version

**Comment by abernix** [comment]
Thanks for opening this.  The `graphql-extensions` package is now deprecated, and I've updated the `CHANGELOG.md` appropriately in https://github.com/apollographql/apollo-server/commit/3d7c8fe8797e93227e44956afd2195fa00908ab4.  Please use the [plugin API](https://www.apollographql.com/docs/apollo-server/integrations/plugins/) going forward.  Thanks!
