### ISSUE TITLE
Type mismatch between apollo-datasource-rest & apollo-server-caching keyValueCache

### ISSUE THREAD

**Issue by varmakarthik12** [apollographql/apollo-server#4256]
I found this when i'm working with cacheOptions on apollo-datasource-rest. Look like the keyValueCache of apollo-server-caching that apollo-datasource-rest uses can take ttl has null. But apollo-datasource-rest doesn't allow that cause of a wrong type.

**Intended outcome**
CacheOptions ttl type should be identical to keyValue cache. To leave out any confusion or fill in something that can be possible with apollo-server-caching but apollo-datasource-rest can't
**Actual outcome**
CacheOptions ttl is not identical to keyValueCache ttl
**How to reproduce the issue**
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts#L41 [apollo-datasource-rest]
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-caching/src/KeyValueCache.ts#L7 [apollo-server-caching]
validates that.

**Comment by varmakarthik12** [comment]
This is a easy fix from the source. I created a PR https://github.com/apollographql/apollo-server/pull/4257 addressing the issue.

**Comment by glasser** [comment]
These packages have both been refactored a bunch and also renamed to `@apollo/datasource-rest` and `@apollo/utils.keyvaluecache` and I have to assume we would have caught this issue at some point if it still existed.
