### ISSUE TITLE
Cache control Type issue

### ISSUE THREAD

**Issue by yaswanthkoneri** [apollographql/apollo-server#4261]
Getting this error
 
`TS2717: Subsequent property declarations must have the same type.  Property 'cacheControl' must be of type '{ setCacheHint: (hint: CacheHint) => void; cacheHint: CacheHint; }', but here has type '{ setCacheHint: (hint: CacheHint) => void; cacheHint: CacheHint; }'.`

Tried deleting, node_modules and package.lock.json and reinstalling but it's not working

Can someone help on this?

**Comment by tejaswi2710** [comment]
Facing the same issue, 
ERROR in [at-loader] ./node_modules/apollo-server-express/node_modules/apollo-cache-control/dist/index.d.ts:24:9 

Even the apollo-server-express does not have node modules

**Comment by Ciboulette** [comment]
Same for me

**Comment by Ciboulette** [comment]
I found a fix if you `rm yarn.lock` && `yarn`

**Comment by Fallenstedt** [comment]
I encountered this too. It looks like the version of `apollo-server-plugin-base` was too new for the version of `apollo-server-core` I was using. 

You can check your lock file for the dependencies of `apollo-server-core`. You should see `apollo-server-plugin-base` and the version in the dependencies. Install that specific version and you should see this error go away. 

![Screen Shot 2022-02-23 at 12 18 02 PM](https://user-images.githubusercontent.com/13971824/155401422-aeece764-151e-41ba-80d1-4df7c78bc652.png)

**Comment by glasser** [comment]
Yeah, there are too many packages that are part of Apollo Server, and the package breaks aren't designed well to avoid circular/diamond dependencies in some cases. Fixing this is a major design goal for Apollo Server 4; if you look at the `version-4` branch you will see far fewer separate packages.

**Comment by glasser** [comment]
I'm going to close this issue because it's pretty challenging to solve with the current package structure but should be solved with AS4.

There's a workaround for this issue at https://github.com/apollographql/apollo-server/issues/3339#issuecomment-696224937 (though that is a bit outdated since the particular package you have to specify is no longer `apollo-cache-control`).
