### ISSUE TITLE
Print composed schema with composition "service" directives

### ISSUE THREAD

**Issue by abernix** [apollographql/apollo-server#4263]
> Not sure what to call these directives specifically, so the name of this issue can certainly be updated/renamed accordingly. 😉 

**Depends on apollographql/rust#61**, which is meant to evaluate/design/discuss which directives would need to exist within a composed, executable, federated schema in order to be _planned_ by a _different_ query planner, rather than leveraging attributes attached to the executable (JavaScript) schema.

This issue tracks the implementation necessary to include them on the appropriate fields in the printed schema, from (JS) `@apollo/gateway` when printed with [`printFederatedSchema`](https://github.com/apollographql/apollo-server/blob/131c9b8895e10317179ce9cab92d4766537f1900/packages/apollo-federation/src/service/printFederatedSchema.ts#L11), much in the same way as we print other federated directives (e.g., `@key`, `@requires`, etc.).

**Comment by trevor-scheer** [comment]
Completed via #4405
