### ISSUE TITLE
gateway: Change query planner tests to test structures rather than strings

### ISSUE THREAD

**Issue by abernix** [apollographql/apollo-server#4271]
> This depends on the outcome of #4265 

Once the pruned query plans are determined, we should change the existing query plan tests to test against the trimmed down snapshots of the query-plan structures themselves rather than the pretty-printed version (which we return in `extensions`.`__queryPlanExperimental` and subsequently display within the _Query Plan_ section of GraphQL Playground.

**Comment by JakeDawkins** [comment]
Completed with #4297 :)
