### ISSUE TITLE
Subscriptions won't work in production

### ISSUE THREAD

**Issue by arnasledev** [apollographql/apollo-server#4272]
The issue occurs when we deploy the app on our AWS server. We are using ELB. GraphQL subscriptions server is mounted on the same port as our express server. Configuration:

```javascript
const graphQLServer = new ApolloServer({
  playground: true,
  introspection: true,
  schemaDirectives: { IsAuthDirective },
  context: async ({ req, connection }) => {
    const identifier = connection ? connection.context.Authorization : req.headers.authorization;
    const user = await identifyUserByAccessToken(identifier, 'graphql'); // todo extract path

    return {
      user
    };
  },
  tracing: true,
  subscriptions: SubscriptionsConfig,
  formatError: err => {
    console.log('apollo error:', { err });
    return err;
  },
  engine: {
    debugPrintReports: true
  },
  plugins: [Plugins.ServerStart, Plugins.Request],
  typeDefs,
  resolvers
});

export { graphQLServer };
```

app.js:
```javascript
...
const app = express();
const server = http.createServer(app);
const API_PORT = process.env.API_PORT || 3000;
...
graphQLServer.applyMiddleware({ app });
graphQLServer.installSubscriptionHandlers(server);

server.listen(API_PORT, () => {
  winston.info(`APP ENV STATUS: ${process.env.NODE_ENV}`);
  winston.info(`APP is running now on port ${API_PORT}`);
});
```

so what I'm expecting here are the subscriptions to work on my playground. And it works. But only **localy** and not when we deploy to our AWS server.

The message I get when I try to run subscriptions in our AWS server:

> {
  "error": "Could not connect to websocket endpoint wss://domain.com/graphql. Please check if the endpoint url is correct."
}

Package.json version: ^2.11.0

Want to mention that sockets in this server work fine on a different port. GraphQL queries, mutations - also working. 

Where the issue can be?

**Comment by stephanrotolante** [comment]
Same using Elastic beanstalk, getting 404s when I try to so subscriptions. Works fine locally. I did get it working on a test server in beanstalk, but I didnt have any auth attached to the routes.....

**Comment by stephanrotolante** [comment]
@arnasledev send me your subscription config, I think I can help you

**Comment by guiaramos** [comment]
> Same using Elastic beanstalk, getting 404s when I try to do subscriptions. Works fine locally. I did get it working on a test server in beanstalk, but I didnt have any auth attached to the routes.....

@stephanrotolante got work with websockets in aws eb you need to select "application load balancer" as it mention in here:
https://aws.amazon.com/blogs/aws/new-aws-application-load-balancer/

**Comment by guiaramos** [comment]
@arnasledev I think the problem is the port, on AWS EB environment you can access the port by `process.env.PORT`, my setup is like this and working fine now:

notice that I am trying to access the port by `process.env.PORT`. which works fine on AWS EB

another thing is that when creating the environment it will show two option: 1- class load balancer; 2- application load balancer

you must select "Application Load Balancer" to work with websockets(subscription) in AWS EB as mentioned here:
https://aws.amazon.com/blogs/aws/new-aws-application-load-balancer/


server.ts
```ts
function normalizePort(val: string): string | number | false {
    const port = parseInt(val, 10);

    if (Number.isNaN(port)) {
      return val;
    }
    if (port >= 0) {
      return port;
    }

    return false;
  }

  const port = normalizePort(process.env.PORT || process.env.BACKEND_PORT || '4000');

  // Database connection
  const connection = await create();

  // Apollo Server
  const apollo = newApolloServer();

  // Error Handler
  Sentry.init(getSentryOptions(app));

  // Express App
  app.use(Sentry.Handlers.requestHandler());
  app.use(Sentry.Handlers.tracingHandler());
  app.set('port', port);

  apollo.applyMiddleware({
    app,
    cors: corsOptions,
    path: '/api/graphql'
  });

  const server = http.createServer(app);

  // Subscriptions
  apollo.installSubscriptionHandlers(server);

  server.listen(port);

  server.on('error', (err) => onError(err, port));
  server.on('listening', () => onListening(server, connection));
```

**Comment by stephanrotolante** [comment]
@guiaramos Thanks. My issues was that the my `.ebextensions` wasn't getting picked up. I torn down my environment and created a new one. Everything worked fine afterwards

**Comment by guiaramos** [comment]
@stephanrotolante may I ask you, are you facing any issue with the latency? when I connect to serve its latency increase significantly to 60.001 on all Ps(p99, p90...)

**Comment by stephanrotolante** [comment]
@guiaramos Im not sure what you mean by `60.001 on all Ps(p99, p90...)`, but yeah there is a little delay on the subscription. It's not a deal breaker though, were talking milliseconds.

**Comment by glasser** [comment]
We will be removing the cursory integration of `subscriptions-transport-ws` with Apollo Server in AS3. We hope to later bring back subscriptions in a more fully integrated way.

**Comment by mshjri** [comment]
This is not an answer to the above question. But if if you're here because subscriptions work on your local but not on production then it might be worthy to check that you're sending subscription request to the [subscriptions endpoint](https://www.apollographql.com/docs/apollo-server/data/subscriptions/#setting-a-subscription-endpoint) specified in your ApolloServer config. if it is not specified, then by default it will be `http{s}://{youserver}/graphql`
