### ISSUE TITLE
How to customize cloud service providers

### ISSUE THREAD

**Issue by LeonYanghaha** [apollographql/apollo-server#4279]
I can use graph manager with any graphql server. If I use Apollo Federation, I should use managed Federation.. The question is: graph manager and managed Federation all rely on GCS (Google cloud services), which is not safe for us. Can I customize the cloud service provider? Or use your own server.

**Comment by abernix** [comment]
Hi @LeonYanghaha. Please contact support through [Apollo Graph Manager's chat widget](https://engine.apollographql.com/) with this question.  Thanks!
