### ISSUE TITLE
graphql peer dependencies issue

### ISSUE THREAD

**Issue by Orzoon** [apollographql/apollo-server#4287]
I tried to deploy my express graphql app to aws through codepipeline and elastic beanstalk.
in the log i keep on getting the versioning issues with graphql all the time. this is the log screenshot when i first tried to deploy the app.
![1](https://user-images.githubusercontent.com/25638825/85166052-12ee1a00-b2aa-11ea-865e-cdd17dd2cbbe.JPG)

i thought downgrading to version 0.12.0 would resolve most of the issues then, this is what i got in the log after redeploying everything
![2](https://user-images.githubusercontent.com/25638825/85166330-77a97480-b2aa-11ea-98d6-72f012b82861.JPG)

i ran this command for the last time: 
yarn add  graphql@14.0.0
and this is what i got again
![3](https://user-images.githubusercontent.com/25638825/85166487-b4756b80-b2aa-11ea-9052-de9502b12aa5.JPG)

it is like if i somehow resolve few peer dependencies by downgrading or upgrading the version, some peer dependencies still cannot be resolved.
how do i get around this problem, i even tried updating every packages to their latest version as well.
this is how my package.json looks like after getting lost for 2 hrs,
![4](https://user-images.githubusercontent.com/25638825/85166810-2b126900-b2ab-11ea-8a82-9ba67b5ac0f3.JPG)

any help would be appreciated thanks

**Comment by felipebutcher** [comment]
@Orzoon the message says: "you must install peer dependencies yourself". Have you tried that?

**Comment by glasser** [comment]
Our peer dependencies have been upgraded a lot over the last few years. (Also, our docs generally show that you should install `graphql` alongside Apollo Server.) This should be fixed now?
