### ISSUE TITLE
npm test doesn't finish on integration tests when APOLLO_KEY is set

### ISSUE THREAD

**Issue by mnick00** [apollographql/apollo-server#4292]
Version:
"apollo-server": "^2.15.0",
"apollo-server-testing": "^2.15.0",
"jest": "^25.5.4",
"ts-jest": "^25.5.1",

Occurs on every of my integration tests following the official example:
https://www.apollographql.com/docs/apollo-server/testing/testing/

```ts
  test("test signupRequest with valid data should succeed", async () => {
    const { server, authenticatingAPI } = constructTestServer({
      context: contextInvalidToken,
    });
    const { query } = createTestClient(server);

    const mockPost = jest.fn(async () => REQUEST_RESPONSE_API);

    authenticatingAPI.setPost(mockPost);

    const res = await query({
      query: AUTH_REQUEST,
      variables: { authRequest: REQUEST_VARIABLE },
    });

    expect(mockPost.mock.calls).toHaveLength(1);
    expect(res).toMatchSnapshot();
  });
```

```ts
const constructTestServer = ({
  context = defaultContext,
} = {}): ConstructedTestServer => {
  const server = new ApolloServer({
    schema,
    dataSources: (): DataSources<MyDataSources> => initDataSources(),
    context: context,
    engine: false,
  });

  return { server, conversationAPI, friendAPI, authenticatingAPI, eventAPI };
};
```

Expected behavior: Test should run and jest should exit afterward.

Actual behavior: 
In the CI pipeline, it runs infinitely. 

Local: 
Error: A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --runInBand --detectOpenHandles to find leaks.

Even with `engine=false`, the error still occurs. 

Without the APOLLO_KEY env variable being set, everything works fine.

Current workaround: 

`"test": "env APOLLO_KEY= jest",`

**Comment by glasser** [comment]
You need to call `await server.stop()` in your tests (perhaps with some sort of `afterEach`).  (It happens that this is because the usage reporting plugin is active, but there could be other things in your server that need to be cleaned up as well.)

You may also want to explicitly disable usage reporting in your tests (overriding the environment variable), which used to be `engine: false` and now involves ApolloServerPluginUsageReportingDisabled().
