### ISSUE TITLE
TS2688: Cannot find type definition file for 'make-fetch-happen'

### ISSUE THREAD

**Issue by razorness** [apollographql/apollo-server#4332]
Facing type error with `@apollo/gateway` `v0.16.10`:

```
"C:\Program Files\nodejs\node.exe" C:\Users\xxx\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js run start:dev
yarn run v1.22.4
$ cross-env NODE_ENV=development nest start --watch

[17:56:47] Starting compilation in watch mode...

node_modules/@apollo/gateway/dist/index.d.ts:1:23 - error TS2688: Cannot find type definition file for 'make-fetch-happen'.

1 /// <reference types="make-fetch-happen" />
                        ~~~~~~~~~~~~~~~~~

[17:56:51] Found 1 error. Watching for file changes.
```

Test repo: https://github.com/razorness/nestjs-apollo-gateway-make-fetch-happen
- checkout
- run `yarn`
- run `yarn build` (may you need nest cli by `yarn global add @nestjs/cli`)

Probably related to: https://github.com/apollographql/apollo-server/pull/4326/commits/b5cd43c5c2b321ba34a394a237d3d27350366b65

Last working version: `v0.16.9`  

Please start pull request for typings to `make-fetch-happen` as already asked in npm/make-fetch-happen#20 or push into https://github.com/DefinitelyTyped/DefinitelyTyped.

**Comment by trevor-scheer** [comment]
@razorness the fix for this is in the latest release of `@apollo/gateway@0.16.11`. Please let me know if you run into any trouble!

**Comment by razorness** [comment]
Fix works well. Thank you very much!

**Comment by trevor-scheer** [comment]
Thanks for reporting back! I agreed with your recommendation enough to go ahead and just put that typings PR together, feel free to track progress here: https://github.com/npm/make-fetch-happen/pull/31
