### ISSUE TITLE
Support multiple GraphQL servers on the same HTTP server on different paths with subscriptions

### ISSUE THREAD

**Issue by Yogu** [apollographql/apollo-server#4336]
Currently, to my understanding, you can not create multiple `ApolloServer` instances on the same http.Server with subscription support, even if you specify different values for `subscriptions.path`. The reason is that the `ws` library does not transparently support this, and they even [see it as out-of-scope](https://github.com/websockets/ws/issues/1726). They [offer a way to do it yourself](https://github.com/websockets/ws#multiple-servers-sharing-a-single-https-server), but it only works if can specify `noServer` on the WebSocket options and call `handleUpgrade` on the WebSocket instances manually. I don't think this is possible with the ApolloServer abstraction.

Ideally, ApolloServer would handle this transparently, and it would be good to support regular expressions in paths like it is supported in the `path` option for the regular GraphQL-over-HTTP API.

Or is there already a way to do this manually (specifying the `noServer` option and accessing the WebSocket instances so we can call `handleUpgrade` on them)?

**Comment by glasser** [comment]
Direct subscriptions integration was removed from Apollo Server in v3 last year.
