### ISSUE TITLE
Connect Integration

### ISSUE THREAD

**Issue by ChayimFriedman2** [apollographql/apollo-server#4348]
I've seen the package `apollo-server-express` is supposed to work with Connect but it doesn't for me. Moreover, after digging into its source I saw it imports `express` and uses `express.Router`, so how does it supposed to work without it?

**Comment by glasser** [comment]
We did actually run tests against Connect so it was supposed to work to some degree (perhaps express.Router didn't actually use any Express-specific APIs?). That said, we've dropped support for Connect from Apollo Server 4, though you can use our new simple stable framework integration API to build your own Connect support pretty easily.
