### ISSUE TITLE
Support fastify3

### ISSUE THREAD

**Issue by gtolarc** [apollographql/apollo-server#4355]
The official fastify 3 version has been released.
But, currently, apollo-server-fastify does not work because it does not support version 3.
Can you guys support version 3 soon?

**Comment by gtolarc** [comment]
Given that fastify v3 has several improvements that are not consistent with existing ones, batch compatibility updates have been made to the fastify plugin eco systems. Therefore it is not difficult to move from the current v2 to v3 if only common plugins were used.
Most fastify users don't want to stay on v2 anymore. If that's all right, please review the fastify v3 support sooner.

**Comment by gtolarc** [comment]
#4356

**Comment by abernix** [comment]
Please see the update I just posted on https://github.com/apollographql/apollo-server/pull/4356#issuecomment-677515901, and thank you @gtolarc for the contribution.
