### ISSUE TITLE
typescript apollo-server-testing

### ISSUE THREAD

**Issue by ehddnr301** [apollographql/apollo-server#4362]
```
const {
        data: {
          createUser: { id, username },
        },
      } = await mutate({
        mutation: CREATE_USER,
        variables: {
          email: "emailpart",
          username: "uuname",
          password: "passsword",
        },
      });
```

this is my test code using apollo-server-testing

but I if use this code with `strictNullChecks:true`

I get error `Property 'createUser' does not exist on type 'Record<string, any> | null | undefined'`

I think this need to set the type more detail.

if I use `strictNullChecks:false` and errors are gone

**Comment by ehddnr301** [comment]
```
import { createTestClient } from "apollo-server-testing";
const { query, mutate } = createTestClient(server);
```

**Comment by glasser** [comment]
This is what the generic type arguments we added to `server.executeOperation` in Apollo Server 4 are for. (`apollo-server-testing` was just a thin wrapper around `executeOperation` and was removed in Apollo Server 3.)
