### ISSUE TITLE
gateway: query planner "mutation" tests

### ISSUE THREAD

**Issue by abernix** [apollographql/apollo-server#4384]
Currently, while the _query_ planner does also work for planning `mutation`s in a federated model, we're lacking tests for them in the [query planner tests](https://github.com/apollographql/apollo-server/blob/HEAD/packages/apollo-gateway/src/__tests__/build-query-plan.feature) that exist today.

This tracks the need for those!

**Comment by JakeDawkins** [comment]
Resolved with #4390 :)
