### ISSUE TITLE
Possible memory leak request pipeline

### ISSUE THREAD

**Issue by mschipperheyn** [apollographql/apollo-server#4385]
We are seeing a memory leak on our dataloader infrastructure. The problem is that `invokeResolveField` seems to keep a context reference alive 
https://github.com/apollographql/apollo-server/blob/43470d6561bee31101f3afc56bdd154db3f92b30/packages/apollo-server-core/src/requestPipeline.ts#L421

<img width="919" alt="Screen Shot 2020-07-16 at 01 39 46" src="https://user-images.githubusercontent.com/384959/87627626-7f233880-c705-11ea-8ed3-cdc9901a245d.png">

The strange thing is that the reference is being kept alive through our rest APIs, which are simple implementations of ApolloRestDataSource.

The fact that context is passed to the apollo rest datasource on construction looks iffy to me also. If context is mutable with every request, it should not be stored as a class instance property. Or do we need to instantiate a new Datasource with each request? Perhaps this is my mistake in fact, not understanding that Datasources need to be instantiated for each request?

apollo-server 2.15.1
apollo-datasource-rest 0.9.3

### This bug report should include:

- [x ] A short, but descriptive title. The title doesn't need "Apollo" in it.
- [ x] The package name and version of Apollo showing the problem.
- [] If applicable, the last version of Apollo where the problem did _not_ occur.
- [x ] The expected behavior.
- [x ] The actual behavior.
- [ ] A **simple**, runnable reproduction!

**Comment by mschipperheyn** [comment]
So yeah, it is indeed required to reinstantiate the restAPI class with every request. That could be a bit cleared but if you read the docs carefully, it is there. 

I still have dataloader references hanging around with the fixes I applied. The subscription Websocket seems to hog references as well. Oh well. I'm using the new `willSendResponse` event handler to clean out as much as I can.

**Comment by glasser** [comment]
I think you're saying that using RESTDataSource as designed (a new object per request) solved your issue, but if not and this still is occurring, it would be worth looking into!
