### ISSUE TITLE
graphiql koa 0.9.0 Error: Can't set headers after they are sent

### ISSUE THREAD

**Issue by VladShcherbin** [apollographql/apollo-server#439]
After updating to graphql-server-koa 0.9.0, there is an error when trying to use graphiql. Graphql itself is working. No error in 0.8.5.

```console
Error: Can't set headers after they are sent.
```

Updated packages:

```console
- graphql-server-core@0.9.0
- graphql-server-koa@0.9.0
- graphql-server-module-graphiql@0.9.0
```

Env:

- node 8.1.2
- mac os 10.12.5
- koa 2.3.0
- koa-router 7.2.1
- koa-bodyparser 4.2.0

Code:

```js
import { createServer } from 'http'
import Koa from 'koa'
import Router from 'koa-router'
import koaBody from 'koa-bodyparser'
import { graphqlKoa, graphiqlKoa } from 'graphql-server-koa'
import schema from './graphql'

const app = new Koa()
const router = new Router()

router
  .get('/', async (ctx) => {
    ctx.body = 'Main / Home'
  })
  .get('/graphiql', graphiqlKoa({ endpointURL: '/graphql' }))
  .post('/graphql', koaBody(), graphqlKoa({ schema }))

app
  .use(router.routes())
  .use(router.allowedMethods())

const server = createServer(app.callback())

server.listen(3000)
```

**Comment by DxCx** [comment]
is that still happens on version 1.0.0?
anyway, this is the diff between the versions:
https://github.com/apollographql/graphql-server/commit/0d5add048ebdfb14da44faff7ad6e09a027d1b3d

@NeoPhi can you take a look at that?

**Comment by VladShcherbin** [comment]
@DxCx yes, this also happens on 1.0.0.

I think, *await* is missing in graphiql resolution somewhere [here](https://github.com/apollographql/graphql-server/blob/master/packages/graphql-server-koa/src/koaApollo.ts#L54).

**Comment by VladShcherbin** [comment]
This was fixed.

**Comment by arvi** [comment]
@VladShcherbin hello what was the fix? Can you post the commit id? Thanks a lot. I am having the same issue on a different package https://github.com/graphcool/graphql-playground/issues/557

**Comment by VladShcherbin** [comment]
@arvi this one I guess: https://github.com/apollographql/apollo-server/commit/c22bb379968581a21b5a3833450e74624883a090

**Comment by arvi** [comment]
@VladShcherbin thanks, reported it to graphcool :smile:
