### ISSUE TITLE
Subresolver paremeters depends on mocks settings

### ISSUE THREAD

**Issue by deftomat** [apollographql/apollo-server#4398]
To have a strongly typed code, we are using a sort of "inline" subresolvers which allows us to defer resolution as necessary.

**Example:**
```ts
const typeDefs = gql`
  type Query {
    user: User!
  }

  type User {
    id: String!
    tags(filter: String!): [String!]!
  }
`;

const resolvers = {
  Query: {
    user: () => {
      return {
        id: "abc123",
        tags: (first, second) => {
          return ["admin", "internal"].filter(v => v.includes(first.filter));
        }
      };
    }
  }
};
```

These subresolvers are little bit different as the first arg is not the `parent` but `variables`.

It all works when `mocks` are disabled. Enabling the mocks will add the `parent` arg and basically moves the variables into the second arg.

Please see https://codesandbox.io/s/adoring-torvalds-nfdff?file=/index.js

When mocks are disabled, user's tags are filterable by variable, however, enabling mocks will broke it as `filter` value will be in the second argument.

*Looks like it is caused by https://github.com/ardatan/graphql-tools/issues/1807*

**Comment by deftomat** [comment]
[`graphql-tools@7`](https://github.com/ardatan/graphql-tools/pull/1935) fixed this issue. So, upgrade to the latest version is necessary.

**Comment by yaacovCR** [comment]
Soon to be released, available now as alpha:

https://github.com/ardatan/graphql-tools/pull/1935#issuecomment-679413268

**Comment by glasser** [comment]
The mocks feature of Apollo Server was just a simple invocation of a function from a particular old version of `graphql-tools`, and so in Apollo Server 4 we've removed that integration in favor of letting you use `graphql-tools` yourself directly (which also means you can upgrade yourself when bugs in it are fixed).
