### ISSUE TITLE
Documentation on Apollo Server initialization with modules

### ISSUE THREAD

**Issue by sketchnotes** [apollographql/apollo-server#4401]
I'm aware of  'spectrum', and previously I left my [question there](https://spectrum.chat/apollo/apollo-server/declare-directives-with-graphqlschemamodule~9a9b03be-2eef-4001-a953-550fe11f98f0).

Whenever it's possible to initialize the Apollo server with modules, I found no way to make the directives work. May anyone clarifies how the directives should be added in the case of the module's initialization?

```
const User = { typeDefs, resolvers, };
const Post = { typeDefs, resolvers, };

const apolloServer = new ApolloServer({
  schemaDirectives: {                      // Directives will be ignored
    authenticated: AuthenticationDirective,
    authorized: AuthorizationDirective
  },
  modules: [User, Post],
  context: (session) => session
});
```

n.b. The official docs tells about `modules: GraphQLSchemaModule[]` only in context of [@apollo/federation](https://www.apollographql.com/docs/apollo-server/api/apollo-federation/#buildfederatedschema).

**Comment by justinmchase** [comment]
In addition to the schemaDirectives (the code you have there looks right) you probably need a little gql submitted as a module as well.

Such as:
```ts
const directiveTypedefs = gql`
  directive @authenticated on FIELD_DEFINITION
  directive @authorized on FIELD_DEFINITION
`;

const Directives = { typeDefs: direciveTypedefs, resolvers: [] };
const User = { typeDefs, resolvers, };
const Post = { typeDefs, resolvers, };

const apolloServer = new ApolloServer({
  schemaDirectives: {
    authenticated: AuthenticationDirective,
    authorized: AuthorizationDirective
  },
  modules: [Directives, User, Post],
  context: (session) => session
});
```

If that still doesn't work let me know I have a few PR's open for other errors with modules and may be able to help make it work:
* https://github.com/apollographql/apollo-tooling/pull/2069
* https://github.com/apollographql/apollo-tooling/pull/2067

**Comment by glasser** [comment]
Right now we are planning to remove support for `schemaDirectives` in Apollo Server 3, because the project that implements it (graphql-tools) considers it to be a legacy API. Folks who want to use `schemaDirectives` or its non-legacy replacement `schemaTransforms` can use `@graphql-tools/schema` directly to create a schema passed in with `new ApolloServer({schema})`;  issues relating to these options should probably be opened in the graphql-tools repo.
