### ISSUE TITLE
apollo-server-core has a hardcoded dependency on graphql 14.7.0

### ISSUE THREAD

**Issue by mschipperheyn** [apollographql/apollo-server#4413]
Apollo server core depends on 14.7.0, whereas apollo-server-express has a peerdependency permitting 15.0.0.
This can create problems in monorepos and is for me. I can prob work around it, but the @types/graphql-upload is already a year old. It should prob be updated to 8.0.3

Versions
apollo-server-express: 16.0

Expected
depend on graphql 15 and allow resolving to that version

Actual
Resolving to graphql 15.x results in a build error with `yarn install --frozen-lockfile`

### This bug report should include:

- [x ] A short, but descriptive title. The title doesn't need "Apollo" in it.
- [ x] The package name and version of Apollo showing the problem.
- [ ] If applicable, the last version of Apollo where the problem did _not_ occur.
- [ x] The expected behavior.
- [ x] The actual behavior.
- [ ] A **simple**, runnable reproduction!
      Please make a GitHub repository that anyone can clone and run and see the
      problem. Other great ways to demonstrate a reproduction are using our
      CodeSandbox template (https://codesandbox.io/s/apollo-server), or re-mixing
      our Glitch template (https://glitch.com/~apollo-launchpad).

  Please make sure that you include the following information to ensure that your issue is actionable.

  If you don't follow the template, your issue may end up being closed without anyone looking at it carefully, because it is not actionable for us without the information in this template.

-->

**Comment by mschipperheyn** [comment]
graphql-upload and @types/graphql-upload should be upgraded to 11.0.0 to fix this.

**Comment by tvvignesh** [comment]
Yup. Looks like the version of `graphql-upload` package is `11.0.0` and it supports graphql `15.x` but apollo-server-core uses `8.0.2` (https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-core/package.json) May need an upgrade.

<img width="683" alt="Screenshot 2020-08-29 142505" src="https://user-images.githubusercontent.com/1165845/91633126-75c70480-ea03-11ea-9f34-3cb829f7ade9.png">

CC: @abernix

**Comment by lewebsimple** [comment]
Any update on this ?

**Comment by bigman73** [comment]
any update of this?

**Comment by Shawnxkwang** [comment]
any update?? This is a serious issue

**Comment by tal130** [comment]
Any update on this? I saw there was new release but it still not resolve

**Comment by abernix** [comment]
I believe this was fixed by https://github.com/apollographql/apollo-server/commit/c871152ba3a05a4a0422da98f6fe902ca523a551 in https://github.com/apollographql/apollo-server/pull/4922, and released in Apollo Server 2.21.0.  Please report back if this is not the case!
