### ISSUE TITLE
apollo-server-lambda does not support middleware

### ISSUE THREAD

**Issue by MichaelHindley** [apollographql/apollo-server#4422]
According to https://www.apollographql.com/docs/apollo-server/integrations/middleware/, in order to use middleware with apollo-server-lambda, one is supposed to use the `applyMiddleware` function on the `server` object created with `new ApolloServer`.

This object does not provide an `applyMiddleware` function.

**Comment by anand-kashyap** [comment]
Any updates on this? I had been trying to create a cached mongoose connection by making a wrapper but could not due to this.

**Comment by rluisnpt1** [comment]
Yes, I think the only function available is .createHandler();

const server = new ApolloServer({ 
  typeDefs, 
  resolvers,
  context: ({ event, context }) => ({
    headers: event.headers,
    functionName: context.functionName,
    event,
    context,
  })
  ,formatError: (error) => {
    console.log(error);
    return error;
  },
});

exports.handler = server.createHandler({
  cors: {
    //origin: true,
    origin: '*',
    credentials: true,
  },
});

-- You can the documentation at  https://www.apollographql.com/docs/apollo-server/integrations/middleware/

**Comment by theseyi** [comment]
@abernix is there a workaround for this? the docs mention using `applyMiddleware` as a way to integrate with Express middleware but nothing specifically for `apollo-server-lambda` https://www.apollographql.com/docs/apollo-server/integrations/middleware/  which does not have this method defined on the server. https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-lambda/src/ApolloServer.ts

**Comment by nikola1912** [comment]
Try doing something like this as a workaround:
```javascript
const { Client } = require('pg')
const config = require('./config')
const generateServer = require('./server')

const server = generateServer()

const invokeHandler = (event, context, handler) => {
  return new Promise((resolve, reject) => {
    const callback = (error, body) => (error ? reject(error) : resolve(body))
    handler(event, context, callback)
  })
}

exports.graphqlHandler = async (event, context) => {
  const graphqlHandler = server.createHandler({
    cors: {
      origin: '*',
      credentials: true
    }
  })

  const client = new Client(config.db)

  let response
  try {
    await client.connect()

    response = await invokeHandler(
      event,
      { ...context, client },
      graphqlHandler
    )
  } catch (error) {
    console.error(error)
    throw new Error(error.message)
  } finally {
    await client.end()
  }

  return response
}

```

**Comment by theseyi** [comment]
Thanks @nikola1912 I opted to use an Express server with apollo-server-express middleware for now. I think it's a solution that gives the best of both world's afaict

**Comment by tafelnl** [comment]
Would using plugins help you guys out? You can read more about it here: https://www.apollographql.com/docs/apollo-server/integrations/plugins/#requestdidstart

**Comment by glasser** [comment]
Yeah, this is a docs issue. We sort of try to have "generic" docs for all the integrations but the different integrations have different APIs; some have an "applyMiddleware" pattern and some have a "createHandler" pattern.

**Comment by jaedag** [comment]
> ```js
>  let respons
> ```

Has anyone tested this reply? And does it work? I'm not sure I understand every part of the code and would be grateful if someone could help by explaining it to me

**Comment by teenkevo** [comment]
Apollo-server-lambda is built on top of apollo-server-express. It combines the HTTP server framework express with a package called @vendia/serverless-express that translates between Lambda events and Express requests. By default, this is entirely behind the scenes, but you can also provide your own express app with the expressAppFromMiddleware option to createHandler:

`const { ApolloServer } = require('apollo-server-lambda');
const express = require('express');

exports.handler = server.createHandler({
  expressAppFromMiddleware(middleware) {
    const app = express();
    app.use(someOtherMiddleware);
    app.use(middleware);
    return app;
  }
});
`
Source: https://www.apollographql.com/docs/apollo-server/v3/deployment/lambda/#customizing-http-serving

Hopefully this is what you are looking for. Please update if it helps.

**Comment by vuk** [comment]
Docs above feel like invalid syntax

**Comment by glasser** [comment]
@teenkevo That's correct: as of Apollo Server v3, you can in fact use middleware with apollo-server-lambda.
