### ISSUE TITLE
Apollo-server-hapi health check doesn't play nice with auth

### ISSUE THREAD

**Issue by b-jam** [apollographql/apollo-server#4429]
Default apollo path will be at `/graphql`
So you can set 
```     
server.applyMiddleware({
    auth: {
        mode: 'try',
    },
````

However the health check path is statically at `.well-known/apollo/server-health` So you cannot override auth for this. For automation reasons, I'd like to disable auth on the health check.

Of course, I can implement my own route, but it would be nice to set this directly when calling `applyMiddleware` instead

Code reference:
https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-hapi/src/ApolloServer.ts#L108

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Hapi integration. It should not be that hard for excited Hapi users to build and maintain a Hapi integration, and our guess is they will do a better job of it than the Apollo Server core team, who did not use Hapi at all other than to maintain the integration. There is not a Hapi integration at this time, but some interest has been expressed over at https://github.com/apollographql/apollo-server/issues/6028.

Additionally, health checks are no longer a part of Apollo Server; it's much easier to just add a little handler yourself than to add all the configuration you might like to our middleware. See https://www.apollographql.com/docs/apollo-server/migration/#health-checks for details.

Sorry for the delay!
