### ISSUE TITLE
Error code not right when throwing ApolloError

### ISSUE THREAD

**Issue by SathishGovindaraju** [apollographql/apollo-server#4431]
When throwing custom error using `ApolloError`, I set a custom error code but when I query, I always get the code as `INTERNAL_SERVER_ERROR`. I am using federated service.

Example Resolver
```js
MyQuery: {
    myData: async (_parentValue, { id }) => {
      try {
        const response = await getDataFromAPI()

        return response;
      } catch (err) {
        throw new ApolloError('Missing data', 'DATA-ERROR-001');
      }
    },
}
```

**Expected behaviour**
- Should return code which has been set in `ApolloError`

Expected response
```json
"errors": [
    {
      "message": "Missing data",
      "locations": [],
      "path": [],
      "extensions": {
        "code": "DATA-ERROR-001",
        "exception": {
            "stacktrace": {}
        }
      }
    }
]
```

**Actual behaviour**
- Returns `INTERNAL_SERVER_ERROR` irrespective of what has been set in ApolloError when throwing it

Example Response
```json
"errors": [
    {
      "message": "Missing data",
      "locations": [],
      "path": [],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
            "stacktrace": {}
        }
      }
    }
]
```

**Comment by apedroferreira** [comment]
same here

**Comment by glasser** [comment]
Hi. Sorry for the delay in response; Apollo Server is now back in active maintenance mode.

I love fixing bugs but it's hard for me to fix bugs that are only demonstrated via a brief code snippet. Can you provide a full reproduction recipe: a series of steps (perhaps including `git clone` or something like codesandbox.io) that lets me immediately see the issue on my computer without me having to be creative at all? I am happy to reopen this issue when it contains a self-contained reproduction.
