### ISSUE TITLE
Adjust graphql playground to save your queries

### ISSUE THREAD

**Issue by arnasledev** [apollographql/apollo-server#4447]
Hello, I'm always facing the same issue since I started to work with grapqhl. When you are working with many queries, mutations and subscriptions, you are starting to miss global variables logic. For example, I would need to save my authorization token on a global constant and use it for every other TAB where I'm executing any kind of resolver. The second very frustrating thing is history. Since you can't open more than X amount of visible tabs (depends on your screen resolution) you need to scroll it and look for the one you are looking for. And you can't close it if you are willing to use them in the future. You can star them, but I see them missing after some time. Also, you can check "history" for any resolver you used to use but its the same scenario - it has limited memory on that. Especially when you are working in localhost. 

So I want to request a feature to save your "tabs" (resolvers) with all the request and payload params, to define global variables and change them in the same way as POSTMAN does for example.

I believe I'm not the only one who is struggling with the same issues. I'll start to develop those features within the next 2 months if nobody will take action on that. Thank you.

**Comment by glasser** [comment]
The third-party GraphQL Playground project has been unmaintained for a while. In Apollo Server 3 last year, we allowed you to choose a different landing page, and the default page sends you to Apollo Sandbox, which does have similar features to what you describe.
