### ISSUE TITLE
Insconsistent response when error is thrown at `parseLiteral` vs within resolver 

### ISSUE THREAD

**Issue by grillorafael** [apollographql/apollo-server#4449]
Dependencies:

```
    "@apollo/federation": "0.19.0",
    "@apollo/gateway": "0.19.0",
    "apollo-server": "2.9.7",
```

https://codesandbox.io/s/trusting-bardeen-48xv5?file=/index.js

Codesandbox doesn't work but the code works locally.

Scenarios:

1. Throwing error in resolver
```
{
  hello
}
```

response: 

![image](https://user-images.githubusercontent.com/1812267/89229102-bab07480-d5d8-11ea-8c82-35f631629426.png)

2. Throwing in parseLiteral
```
mutation {
  myMutation(input: 2123)
}

```
![image](https://user-images.githubusercontent.com/1812267/89229170-dae03380-d5d8-11ea-8a6e-dab53aada75c.png)
 

My expectation was to not see the extra `errors` key

**Comment by glasser** [comment]
Error normalized has been simplified a bunch in Apollo Server 4. As you mentioned, your codesandbox doesn't actually work, so I wasn't able to try to upgrade it to AS4. If this is still an issue in AS4, please share an updated reproduction and we'll look into it! Sorry for the delay.
