### ISSUE TITLE
Graphql Voyager

### ISSUE THREAD

**Issue by hmontes** [apollographql/apollo-server#445]
It's only an idea. 

Do you know https://github.com/APIs-guru/graphql-voyager ?

It's an amazing tool! Can you include this tool in graphql server like Graphiql. It's more complete, interactive  and is more easy to document.

**Comment by stubailo** [comment]
I think it should be possible to include it as a module just like we have GraphiQL today! Would be cool to work on a PR for that :]

**Comment by IvanGoncharov** [comment]
@hmontes @stubailo Thanks to  @steplov Voyager npm package now includes middleware for Express, Koa and Hapi. Docs are here: https://github.com/APIs-guru/graphql-voyager#middleware

**Comment by Samueljoli** [comment]
@IvanGoncharov That's awesome! So is it still viable to bring this feature into the codebase?

**Comment by stubailo** [comment]
That's awesome! I think it would be cool to have some kind of integration - like maybe we can make it so that you can just configure graphiql/voyager once, rather than having two middlewares?

**Comment by abernix** [comment]
In general, we're trying to make Apollo Server more composable, so making this a part of core doesn't seem like the best approach, but as suggested above, it's already a middleware so I'm not sure what would stop this from being used today.  I love GraphQL Voyager, but I think it's best to keep it as a separate component that can be opted into as necessary. 
 Happy to re-open if anyone has some concrete reasons why this wouldn't be possible though!  Thanks!
