### ISSUE TITLE
Normalize all errors 

### ISSUE THREAD

**Issue by amatiushkin** [apollographql/apollo-server#4455]
[Error handling](https://www.apollographql.com/docs/apollo-server/data/errors/) covers basic functionality of handling or customizing error messages. 

But there are at least three kind of errors, which are hard to normalize or customize to make it graphql spec compliant.

**HTTP 405 Method not allowed**, current response:
 [Apollo Server supports only GET/POST requests.](https://github.com/apollographql/apollo-server/blob/e4e8cbccf462245ec7fb798b9258f8a8cb24e6c6/packages/apollo-server-core/src/runHttpQuery.ts#L224)

![image](https://user-images.githubusercontent.com/47459964/89372453-12171900-d69b-11ea-9bcd-edd273ed0f3d.png)

Desired response payload for **HTTP 405**:
```
{
  "errors": [
    "message": "Apollo server supports only GET/POST requests."
  ]
}
```

**HTTP 500 Internal Server Error**, current response:
```
{}
```
![image](https://user-images.githubusercontent.com/47459964/89372750-db8dce00-d69b-11ea-9c73-ddc69d78cde2.png)

Desired payload for **HTTP 500**:
```
{
  "errors": [
    "message": "Internal server error"
  ]
}
```

**HTTP 404 Not found**, current response:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /graphql2</pre>
</body>
</html>
```

![image](https://user-images.githubusercontent.com/47459964/89372736-d16bcf80-d69b-11ea-860f-2076743dddab.png)

Desired payload for **HTTP 404**:
```
{
  "errors": [
    "message": "Cannot POST /graphql2"
  ]
}
```

Plain text and html errors do make sense if a human person can open endpoint served by Apollo server. 
If there is another active component (api gateway or server) which interacts with Apollo server, it requires somehow to manage discrepancies since errors are not consistent. 

It would be nice to have configuration flag or customization option to make all errors fully-normalized according to graphql specification.

**Comment by glasser** [comment]
Apollo Server 4 [makes these errors into JSON](https://www.apollographql.com/docs/apollo-server/migration/#improvements-to-error-handling-outside-of-resolvers) and allows you to handle them with the `formatError` hook and observe them with the `invalidRequestWasReceived` plugin event, which I think is what you're asking for.
