### ISSUE TITLE
Pre resolver traversing phase to plan the whole query to be send to the db?

### ISSUE THREAD

**Issue by j0nd0n7** [apollographql/apollo-server#446]
In my experience with GraphQL+Apollo with MongoDB, I always try to avoid sending to the DB multiples queries to resolve a graphql query, every time I can.

In my opinion, the actual design of resolvers do not promote the building of an optimal db query without coding a traversal very similar to the one that resolvers make.

It would be very useful to include an optional pre resolver traversal fase, very similar to the resolver one, to plan and build the query to be send to the db (or to a webservice or ...), based on: fields requested by the client, extra fields to add in order to resolve unions/interfaces, joins (lookup's) to be executed to get fields stored outside the collection/table of the base type queried in the entry point.

EDIT: I found this and is very similar to the topic of this issue: http://sangria-graphql.org/learn/#query-reducers.
I get there from here: https://github.com/graphql/graphql-js/issues/353

Let me show you an example:

Schema
```
type UberTrip {
    id: ID
    state: TripState!
    driver: Driver
    passenger: Passenger
    ...
}

type Driver {
    id: ID
    name: String
    vehicles: [Vehicle]
    #this is the current vehicle being used by the driver 
    vehicle: Vehicle!
    ...
}

type Query {
   getTrip(id:ID) : UberTrip
}
```

A valid query
```
query {
  getTrip(id:"123ABC") {
      state      
      driver {
          id
          vehicle {
             plate
          }
      }
  }
}
```

An opinionated MongoDB collections definition
```
trips {
   _id
   state
   driverId
   passenger {
      name
      ...
   }
   ...
}

drivers {
   _id
   name
   // With this index you get the current vehicle indexing the vehicles array
   currentVehicleIndex
   vehicles: [
       {
           plate
           ...
       }
   ] 
   passenger {
      name
      ...
   }
   ...
}
```

For example to resolve the current vehicle (the `vehicle` field of Driver)  I would:
do the join, fetch the entire driver with all his/her vehicles and fields (note the need of a join / lookup) and then a resolver for vehicle would be:
```
  Driver: {
    vehicle(driver, params, context, info) {
      return driver.vehicles[driver.currentVehicleIndex];
    }
  },
```
Other option (the one I actually do) could be: from the entry point `getTrip` traverse the requested fields (included as part of the info parameter), plan the whole query, so after it returns from the db, the resolver has all the data needed, and only the data needed.

With an optional pre resolver fase with a similar design than the resolvers I could do:

NOTE: This is the pre resolver fase 
```
  Driver: {
    vehicle(driver, params, context, info) {
           context.dbQuery.driver.addFieldsInProjection('vehicles', 'currentVehicleIndex');
           
           // Or even for a better performance (sorry very mongo specific)
           // context.dbQuery.driver.addFieldInProjection('vehicle', { '$arrayElemAt': ['$driver.vehicles', '$driver.currentVehicleIndex']});           
    }
  },
```
So when the pre resolver fase ends, the resulting query is sent to the db (may be as part of the resolver of the entry point `getTrip`) and when it returns, every resolver has the data needed to resolve and only the fields required where requested to the db.

Let me know if there is a better approach, or if there is already a something like this to send optimal queries to the db.

Thank you.

**Comment by jbaxleyiii** [comment]
@j0nd0n7 this is currently possible at the root level using the `info` field though in general we don't recommend this as per entity kind of caching tends to be a better, more scalable solution. Thanks so much for the idea though!
