### ISSUE TITLE
npm install apollo-server-express gives error

### ISSUE THREAD

**Issue by zhumabek** [apollographql/apollo-server#4460]
command -  npm install apollo-server-express

npm ERR! 404 Not Found - GET https://registry.npmjs.org/@wry%2fequality - Not found
npm ERR! 404 
npm ERR! 404  '@wry/equality@^0.1.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'apollo-utilities'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by calazans10** [comment]
I've just got this error too.

**Comment by Rennzie** [comment]
I'm also seeing this error. But using yarn to install it.

**Comment by JoseTappx** [comment]
It's a problem with the npm reegsitry cache: https://status.npmjs.org/

**Comment by Rennzie** [comment]
Thanks @JoseTappx

**Comment by zhumabek** [comment]
@JoseTappx thanks, now it's working
