### ISSUE TITLE
Lambda Package Sized (pt2)

### ISSUE THREAD

**Issue by kyeotic** [apollographql/apollo-server#4462]
I've raised this issue [before](https://github.com/apollographql/apollo-server/issues/2162), but the situation has gotten significantly worse since then. Running `npx cost-of-modules` after an install of `apollo-server-lambda` shows an install footprint of **34MB**, which is zipping down to about **9MB**.

```
┌──────────────────────────┬──────────────┬────────┐
│ name                     │ children     │ size   │
├──────────────────────────┼──────────────┼────────┤
│ apollo-server-lambda     │ 222          │ 34.38M │
```

The major offenders appear to be related to polyfill/backwards-compatability. Its not clear to me how necessary they are, or why they are so incredibly large.

```
6.8M    core-js
4.0M    @apollo
3.2M    util.promisify
3.2M    string.prototype.trimstart
3.2M    string.prototype.trimend
3.2M    object.getownpropertydescriptors
3.0M    graphql
1.4M    @types
```

Surprisingly the usual dead-weight suspect, `@types`, is at the bottom of this list. The polyfill libs are made up almost entirely of their own copies of `es-abstract`, a 3.1MB [compatability layer](https://www.npmjs.com/package/es-abstract). I don't know why each one has a seperate copy, it seems like they should have been flattened by npm.

The largest offender, `core-js`, is used by `apollo-env`. It's not clear to me how this happens: `npm ls` lists it as a direct dependencies, but it is not in the [package.json](https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-env/package.json) as far as I can tell.

I'd like to discuss possible avenues for addressing the size of this package. I understand that some of these, like `@types` can be [safely stripped from deployment artifacts](https://github.com/apollographql/apollo-server/issues/4020#issuecomment-617834411), so perhaps this is also true of some of the above. If not I think its worth identifying why they are present and how they might be avoided.

**Comment by duboisj-illuminate** [comment]
(Slightly off-topic, but you once mentioned in the previous thread that you could share your test harness.  If that is easy for you to do, I'm interested.  If not, no sweat. My immediate goal is doing cold-start testing on other graphql frameworks, although Apollo is one possibility for us so I might want to test that eventually.)

**Comment by kyeotic** [comment]
@duboisj-illuminate Apologies, its an internal tool that was rejected from Open Source release 🤕

**Comment by duboisj-illuminate** [comment]
I see, no sweat - I'll manage another way.  Thanks for the fast response, and for the good writeups about start times.
