### ISSUE TITLE
[apollo-server-fastify] playground not working

### ISSUE THREAD

**Issue by marcopeg** [apollographql/apollo-server#4463]
I followed the instructions at https://www.npmjs.com/package/apollo-server-fastify and the `/graphql` endpoint works but it doesn't run the playground even with `playground: true, introspection: true` in the settings.

## Versions

```json
"dependencies": {
  "fastify": "3.2.0",
  "apollo-server-fastify": "2.16.1"
},
```

## Expected behavior:

Going to `/graphql` with a browser should run the playground

## Actual behavior:

It shows: `GET query missing.`

## How to reproduce it:

You can run the example in a CodeSandbox:  
https://codesandbox.io/s/wispy-dream-66j5g?file=/package.json:197-281

**Comment by arturataideJobCloud** [comment]
Same here, when using it with nestJs.
Got the same result of `GET query missing`.

  ```
  ... 
  "@nestjs/platform-fastify": "^7.4.2",
  "@nestjs/platform-fastify": "^7.4.2",
  ...
```

```
 export const graphQLConfig: GqlModuleOptions = {
    typePaths: ['./**/*.graphql'],
    // playground: environment.isDevelopment,
    playground: true,
    ...
}
```

**Comment by a7ul** [comment]
Faced the same issue. 
Seems like its because this package doesnt support fastify v3.
Downgrading to fastify 2 makes it work.

I guess we can either wait for  https://github.com/apollographql/apollo-server/pull/4356/files to land or downgrade to fastify v2 for the time being.

**Comment by arturataideJobCloud** [comment]
> Faced the same issue.
> Seems like its because this package doesnt support fastify v3.
> Downgrading to fastify 2 makes it work.
> 
> I guess we can either wait for #4356 to land or downgrade to fastify v2 for the time being.

Exactly... In my case I will wait and use graphiQL by now. Will keep an eye on #4356

**Comment by mpeirone** [comment]
I have the same issue, do you know any workaround?

**Comment by Duduzera1997** [comment]
+1

**Comment by NickMandylas** [comment]
Would love an update for Fastify v3!

**Comment by phattranky** [comment]
I simply upgrade the `apollo-server-fastify` to  "apollo-server-fastify": "^3.0.0-alpha.3" .

The alpha version seems not safe, But I didn't see any errors so far

**Comment by Duduzera1997** [comment]
> To fix this issue, I simply upgrade the `apollo-server-fastify` to "apollo-server-fastify": "^3.0.0-alpha.3" .
> 
> The alpha version seems not safe, But I didn't see any errors so far

@phattranky This works for me, for now my application does not need something 100% safe, thanks!

**Comment by inakineitor** [comment]
@phattranky @Duduzera1997 I upgraded to the alpha version but get this error. What version of the `graphql` and `@nestjs/graphql` packages are you using?

```
(node:1501) UnhandledPromiseRejectionWarning: TypeError: this.apolloServer.installSubscriptionHandlers is not a function
    at GraphQLModule.<anonymous> (/Users/inakineitor/Documents/Couponara/couponara-backend/node_modules/@nestjs/graphql/dist/graphql.module.js:97:35)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/inakineitor/Documents/Couponara/couponara-backend/node_modules/tslib/tslib.js:111:62)
(node:1501) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1501) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Duduzera1997** [comment]
> @phattranky @Duduzera1997 I upgraded to the alpha version but get this error. What version of the `graphql` and `@nestjs/graphql` packages are you using?
> 
> ```
> (node:1501) UnhandledPromiseRejectionWarning: TypeError: this.apolloServer.installSubscriptionHandlers is not a function
>     at GraphQLModule.<anonymous> (/Users/inakineitor/Documents/Couponara/couponara-backend/node_modules/@nestjs/graphql/dist/graphql.module.js:97:35)
>     at Generator.next (<anonymous>)
>     at fulfilled (/Users/inakineitor/Documents/Couponara/couponara-backend/node_modules/tslib/tslib.js:111:62)
> (node:1501) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:1501) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

"@nestjs/common": "^7.0.0",
"@nestjs/core": "^7.0.0",
"@nestjs/graphql": "^7.7.0",
"@nestjs/platform-fastify": "^7.4.4",
"apollo-server-fastify": "^3.0.0-alpha.3",",
"graphql": "^15.3.0",
"graphql-tools": "^6.2.4"

**Comment by inakineitor** [comment]
Weird. I have the same versions for everything but `graphql-tools`, for which I have `^6.2.5`. I decided to change back to express for now until apollo-server-fastify 3 leaves alpha. Thanks @Duduzera1997!

**Comment by abernix** [comment]
For those attempting to use Apollo Server 3.x for its newer Fastify version, please see https://github.com/apollographql/apollo-server/pull/4356#issuecomment-677515901, which is a comment I wrote for a similar audience on another PR which introduced the functionality.  In particular, pay attention to my suggestion in that comment about reading the v3 `CHANGELOG.md` for details on how `installSubscriptionsHandlers` is affected (Subscriptions has been de-coupled from the core of the project, but is still installable separately).

**Comment by simoami** [comment]
Thanks @abernix for the update. We are working with a client to deploy a graphql gateway/orchestrator solution. We have an sla for high throughput, which is why I'm recommending Fastify as the underlying web framework. Apollo server needs to side with performance because it often ends up in the forefront ingesting all traffic in transitional architectures, and therefore Fastify (the performance web framework) is equally important to prioritize. I am excited to get graphql and Apollo into production in the near future and thanks for the great work.

**Comment by tonimedina-pri** [comment]
+1

**Comment by glasser** [comment]
This is fixed on the release-3.0 branch, which supports Fastify v3 (only). Apollo Server 3.0 is now under active development; I hope to get some alphas out within a week.

**Comment by genu** [comment]
Although this issue may be fixed, I'm unable to test it with `3.0.0-alpha.4` due to startup error: 

`TypeError: this.ensureStarting is not a function
    at ApolloServer.createHandler (/node_modules/apollo-server-fastify/dist/ApolloServer.js:22:14)`

**Comment by glasser** [comment]
@genu What version of apollo-server-core is installed? There might be an issue there.

That said I'll have another alpha out pretty soon hopefully; there's been a lot of improvements since the last one.

**Comment by marcopeg** [comment]
@genu I finally got it working by also installing `apollo-server-core@3.0.0-alpha.4` (same version as `apollo-server-fastify`). Here is my working `package.json`: https://github.com/forrestjs/forrestjs/blob/master/packages/service-fastify-gql/package.json

@glasser Somehow, I and some others didn't figure this out by reading the docs. Your last comment pointed me in the right direction. 

Do you think it might be useful to make it more explicit in the docs?

**Comment by genu** [comment]
I'll test that configuration on my end and report back.

Thx

**Comment by tkow** [comment]
I found current preview version affects yarn.lock version polluted.
If you use yarn, it can fix resolutions until next release.

See the detail: https://github.com/apollographql/apollo-server/issues/5278

**Comment by glasser** [comment]
@marcopeg Yes, planning to get peer deps right as part of AS3 release. #5210.
