### ISSUE TITLE
[apollo-server-lambda] allow regex support for Acess-Control-Allow-Origin

### ISSUE THREAD

**Issue by sachinmour** [apollographql/apollo-server#4470]
To enable CORS response for requests with credentials (cookies, http authentication) the allow origin header must equal the request origin.
Current cors options
* origin: boolean | string | string[]

In the current scenario either we allow everything by setting it to true which will allow all domains, which is not ideal most of the times unless you're creating a public api.
Then there is an option of string array which makes it really hard to define all the possible subdomains and ports which are needed when developing locally.
I purpose to support regex array and/or regex which will really help to make sure you define exactly what you need in a very consistent manner.

For eg.
```javascript
{
  origin: [/localhost:(.*)$/, /\.example\.com$/]
}
```

**Comment by iamnnort** [comment]
I have the same issue, is there a reason why the library does not support all options from Express? https://github.com/expressjs/cors#configuration-options

**Comment by dsuwirya** [comment]
I also need the ability to pass Function here as what expressjs cors middleware can do.

**Comment by prescottprue** [comment]
+1 Took a bit of debugging to figure out what was going on, but seemed like we would just need to add regex matching as part of [this if logic in ApolloServer](https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-cloud-functions/src/ApolloServer.ts#L86)

Took a stab at adding to both `apollo-server-cloud-functions` and `apollo-server-lambda` [in this PR](https://github.com/apollographql/apollo-server/pull/5077)

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Lambda integration. Check out the [`@as-integrations/aws-lambda`](https://www.npmjs.com/package/@as-integrations/aws-lambda) package; this new package is maintained by Lambda users and implements support for the API Gateway v1 and v2 protocols. If you need to work with different AWS projects, you may be able to add that support to that package, or take another approach such as combining the [`@vendia/serverless-express`](https://www.npmjs.com/package/@vendia/serverless-express) package with Apollo Server 4's built-in `expressMiddleware` (this is the same approach that `apollo-server-lambda` takes in AS3). Sorry for the delay!
