### ISSUE TITLE
ExpressGraphQLOptionsFunction does not guarantee req input

### ISSUE THREAD

**Issue by Isigiel** [apollographql/apollo-server#448]
`export interface ExpressGraphQLOptionsFunction {
    (req?: express.Request, res?: express.Response): GraphQLOptions | Promise<GraphQLOptions>;
}`

The interface implies that req could be undefined. Is this correct and how should an undefined request be handled?
I use it to store login data and to use optics.

If this is a mistake please fix it, as it keeps erroring on compiling.

**Comment by zachariahtimothy** [comment]
I am curious about this as well. When I run queries and mutations from the graphiql page the first argument in the resolver is undefined. Seems like this should be the request object which I require for authentication.

**Comment by kctang** [comment]
In the meantime, you can force TypeScript to assume that request is defined using the `!` [postfix character](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html).

```
    app.use(endpoint, bodyParser.json(), graphqlExpress(request => {
      return {
        schema,
        context: {
          user: request!.user,
          headers: request!.headers,
        }
      }
    }))
```

**Comment by joearasin** [comment]
Looking at the code, it looks like a mistake to me. Certainly, request and response are required when entering the middleware.

**Comment by abernix** [comment]
Hopefully fixed by https://github.com/apollographql/apollo-server/commit/fd347718417fea630b6255fa5b18f5bc0c4afbf2.  Thanks for reporting this originally!
