### ISSUE TITLE
Issue with directives and nested resolvers

### ISSUE THREAD

**Issue by ilyavolodin** [apollographql/apollo-server#4480]
- [x] The package name and version of Apollo showing the problem.
apollo-server-express v2.16.0
- [x] The expected behavior.
When nested resolver throws, error should be logged on the console.
- [x] The actual behavior.
Error is only logged on the console if the primary resolver throws.
- [x] A **simple**, runnable reproduction!
https://codesandbox.io/s/laughing-buck-cs1lv?file=/index.js
If you uncomment throw under `Query > profile` and execute the query, you will see console log with the exception being thrown. However, if you uncomment throw under `UserProfile > user` and execute the query again, nothing is logged on the console. However, the directive is on the Query itself, not on the type, so I would expect both cases to log.

Apollo Server version: ^2.16.0

**Comment by jhampton** [comment]
@ilyavolodin Thank you for the reproduction.  I believe that the behavior you're experiencing is correct.  Please see this fork to demonstrate what the Visitor is doing: https://codesandbox.io/s/friendly-bouman-23ixx?file=/index.js

Essentially, the visitor ensures that the associated _resolver_'s exception is logged.  In this case, that only applies to the resolver for the Query itself, which makes sense.  If you apply the `@throws` exception on the _type_ being returned, then you see the exception as expected.

You could achieve the behavior you want by modulizing the logic for each resolver and ensuring that the query resolver follows the same code paths, thereby ensuring that an exception thrown within that function's closure is properly caught and logged.

I'll close this for now, but please let us know if this makes sense.  FWIW, it took me a minute and some additional logging to see what was happening here.  I have also checked the `graphql-js` project to make sure this isn't an underlying issue.

HTH!

-Jeff
