### ISSUE TITLE
Docs: create a Quick Start section in docs for Apollo 2

### ISSUE THREAD

**Issue by mlizchap** [apollographql/apollo-server#4505]
I thought it was nice to have in the docs a [Quick Start](https://www.apollographql.com/docs/apollo-server/v1/example/) section for the initial setup for v1.  For v2, I found the [Getting Started](https://www.apollographql.com/docs/apollo-server/getting-started/) section to be pretty verbose, especially for someone familiar with Node and coming from a v1 background.  I eventually saw the code I needed could be accessed by scrolling down through the tutorial, but this took some time and wasn't very intuitive. I feel like having a `Quick Start` where users could quickly see the startup code instead of scrolling through a tutorial would be beneficial for potential future users. 

 I'd love to make this update, let me know if you want to make the PR.  Thanks in advance.

**Comment by glasser** [comment]
Is the [Complete example](https://www.apollographql.com/docs/apollo-server/getting-started/#complete-example) helpful enough here? I think it might me.
