### ISSUE TITLE
transformSchema swallows custom error codes

### ISSUE THREAD

**Issue by cgrice** [apollographql/apollo-server#4508]
Package: apollo-server @ 2.16.1

**Expected behaviour**
If a schema is transformed with `transformSchema`, and has a custom error thrown in a resolver, the error code of that error should match that of the error thrown. e.g., if `ForbiddenError` is thrown, there should be a code of `FORBIDDEN`.

**Actual Behaviour**
When wrapping a schema with transformSchema, custom error codes are lost and replaced by `INTERNAL_SERVER_ERROR`.

Reproduction here: https://github.com/cgrice/apollo-server-transform-schema-bug

**Comment by JaanJah** [comment]
Any updates on this?

**Comment by glasser** [comment]
`transformSchema` is part of `graphql-tools` which used to be part of the Apollo Server project but is now maintained by a separate team over at https://github.com/ardatan/graphql-tools/

In Apollo Server 2 we do import an old version (v4) of `graphql-tools` and re-export every symbol from it; we're removing this behavior in the imminent Apollo Server 3 and allowing folks who want to use `graphql-tools` functionality to use it directly with the version of their choice.

`graphql-tools` has had a lot of improvements over the last few years, and I think transformSchema has had some big improvements too.

The reproduction above uses the `transformSchema` function which I believe has been replaced in newer versions of `graphql-tools` by the [`wrapSchema` API](https://www.graphql-tools.com/docs/schema-wrapping/).

If the reproduction can be updated to use a newer version of `graphql-tools` with `wrapSchema` and it still shows the error handling problem, I'm happy to reopen this and look into it further, but until then the most likely conclusion is that this is a bug in an old version of `graphql-tools` which will no longer be part of Apollo Server very soon.
