### ISSUE TITLE
Implement passConnectionParams (e.g. passHeader) for subscriptionsEndpoint

### ISSUE THREAD

**Issue by mjgallag** [apollographql/apollo-server#452]

**Comment by martijnwalraven** [comment]
Could you add some more context for this issue?

**Comment by mjgallag** [comment]
See https://github.com/apollographql/apollo-server/blob/20722fddf2d985efa0fd4f31c827aa2c09b4cce0/packages/apollo-server-module-graphiql/src/renderGraphiQL.ts#L17, we need similiar functionality in order to use authenticated websockets in GraphiQL

**Comment by unhawkable** [comment]
It would be great to have this implemented.

**Comment by abernix** [comment]
We're planning on re-designing the way that subscriptions are implemented in Apollo Server 3.  This feature request has a fairly small amount of context, but if it's still important to any interested parties, a full feature request with demonstrated use-cases would go a long way in the design of the next generation of the featue.  That said, we'll still put this in a project so it can be reviewed in the future.  Thanks!
