### ISSUE TITLE
using custome parser in apollo server

### ISSUE THREAD

**Issue by TheEhsanSarshar** [apollographql/apollo-server#4521]
I want to use a native C++ graphql parser with apollo server.  how can I do that  ;)

**Comment by glasser** [comment]
Apollo Server doesn't have a way to override the GraphQL parser (other than I suppose installing your package into `node_modules/graphql` and hoping it implements everything that the real `graphql` package does).  The point of Apollo Server is to be the glue between `graphql-js` and a web framework; abstracting out `graphql-js` seems challenging.
