### ISSUE TITLE
Reply error when no apiKey is present in header

### ISSUE THREAD

**Issue by Durisvk** [apollographql/apollo-server#453]
I simply want to reply an error if the `secureGuard.authenticate` returns null.. How could I do that?

Here is more info about the issue:
https://stackoverflow.com/questions/44971710/check-every-request-apollo-server-and-return-error-for-missing-apikey

**Comment by martijnwalraven** [comment]
It seems like this was answered on StackOverflow.

**Comment by Durisvk** [comment]
@martijnwalraven No it was too stupid answer because it doesn't answer anything... Guy just pointed out the fact that my comment is not a valid syntax (which I know - it was just a comment - not an actual code...). So I decided not to use apolloServer because it doesn't provide a mechanism for checking the apiKey and I decided to create my own package which solves that and many other things I needed. You can find my package here: https://github.com/Durisvk/senegraph
It connects seneca with graphql. It provides the per request option which looks something like this:

```js
const senegraphOptions = {

    ...

    perRequest: (seneca, request) => {
          // It can either return a value or a Promise ( if Promise is rejected the error message is returned )
         return new Promise((resolve, reject) => {
                const identity = options.securityGuard.authenticate(request) // <== returns null if not authenticated (if api key is not present in request header)...
                if(!identity) {
                     reject(new Error('You must provide an api key'));
                } else {
                     resolve({ context: { identity }, rootValue: { some: 'root value' } });
                }
         }
    }

   ...

}
```

So simply if you consider this approach to be useful for you, you can use it ( I did it myself so that I don't depend on others )...
