### ISSUE TITLE
Consider export-ing `Query` and `Mutation` type

### ISSUE THREAD

**Issue by jpqy** [apollographql/apollo-server#4530]
Similar to #4389, I need access to the `Query` and `Mutation` types when using the `query` and `mutate` methods in the `createTestClient` hook. 

I am writing some utility wrapper functions around the `query` and `mutate` functions, and the wrapper functions need these types to define its own param, i.e:

```ts
const { query } = createTestClient(testServer);

async printQueryResponse(gqlQuery: Query): Promise<void> {
    const response = await query(gqlQuery);

    // Pretty-print the response object
    console.log(JSON.stringify(response, null, 2));
  }
```

They are not even exported in `apollo-server-testing/src/createTestClient.ts` so I'm currently redefining those types locally to match.

**Comment by glasser** [comment]
`apollo-server-testing` was just a thin wrapper around `server.executeOperation` that added very little value, so we removed it last year in Apollo Server v3. So these types aren't needed anymore. The arguments to `executeValue` should be exported, more or less.
