### ISSUE TITLE
Need the graphql info object while creating context

### ISSUE THREAD

**Issue by rramaa** [apollographql/apollo-server#4531]
When creating an instance of the `ApolloServer`, the context function is called with the `RequestContext`.

However, there might be a use case, that `GraphQLInfo` might be needed while creating the context itself.

For example, in my case, I needed to know whether the incoming operation was of type `query` or of type `mutation`, so that I could create my API Client with the correct headers(headers are dependent on whether its a purely read operation or the operation mutates something in the Backend). I could not find a way to get the information about the grapqhl operation inside by context creation function.

The workaround I had to come up with was to override all the resolvers and directives and modify their contexts in the resolver function(the info object is present as an argument in the resolver function). This has made my application somewhat fragile.

 I could not find a way to implement such behaviour through any standard approach.

If this feature is not possible then any suggestions?

Edit:
I am using `apollo-server-express@2.8.1`

**Comment by kuksik** [comment]
Good proposal, i think it will be useful in some case.

**Comment by Flamenco** [comment]
My use case is reading the requested fields and putting them into the context to avoid each of my resolvers from having to parse the info parameter to get them, or to bypass a check to see if a parent resolver already parsed them.

Currently I am forced to check/parse fields in every resolver at every graph node.

**Comment by glasser** [comment]
The context function is called before parsing the operation, so what you're asking for directly will be hard. I'd suggest using a plugin that hooks into something like `executionDidStart` or `didResolveOperation` and adds a field to requestContext.context at that point, ie something like

```
new ApolloServer({
  async context({ req }) {
    return {
      user: await getUser(req.header.apiKey),
      apiClient: null,
    };
  },
  plugins: [{
    async requestDidStart() {
      return {
        didResolveOperation({ requestContext }) {
          requestContext.context.apiClient = new APIClient({ isMutation: requestContext.operation?.operation === 'mutation' });
        }),
      };
    }
  }],
})
```

**Comment by Flamenco** [comment]
Thanks for the suggestion @glasser.  I had found that stuffing fields in the context of the resolver ended up burning me.  I had several resolvers getting called in the same execution, and they apparently share the same context object...  So one resolver was getting the other's parsed fields...

Looking forward to trying your approach!

**Comment by glasser** [comment]
Right, the context is shared across all resolvers. But this plugin function is only called once!

**Comment by Flamenco** [comment]
@glasser  So I have tried several approaches and each has a caveat.

Ultimately, I need to set the context per operation.  But when I override the `willResolveField` handler, it is using a shared context.

So what I really need is a 'per operation' context in that handler, that will get merged in with the shared context.

**Comment by Flamenco** [comment]
@glasser So I have found that my concept of a plugin that will add context per resolver will not work using the current architecture.  I have looked at the source code and I have a suggestion.

1. Modify current `willResolveField` hook, or add a new plugin hook that allows returning context specific to the resolver. This will be shallow merged into the context the resolvers receive. 

1a. Either add a function in `willResolveField's` info called setResolverContext()
1b. Or add a new hook onResolverContext the receives the same arguments as `willResolveField` and returns the context object to merge.

2. Because the resolvers will now receive a merged context object, mutating this object will not be shared with other resolvers in the same or other operations. as they are now.  So to solve that issue, the info will contain a method `updateContext` that will merge with the global context.  This would have the advantage that the developer cannot inadvertently mutate the context they receive without explicitly calling the updateContext method.

**Comment by glasser** [comment]
> So what I really need is a 'per operation' context 

When you say "operation", do you mean "operation" in the GraphQL sense (essentially an entire request) or "field"?

**Comment by Flamenco** [comment]
To clarify, it is a context per resolver call.

**Comment by Flamenco** [comment]
So i can set fields in the context from my plugin that are not shared between resolvers.

**Comment by glasser** [comment]
Context values are intended to be constant for an entire execution, according to the model set by the underlying graphql-js. 
 It doesn't get cloned either, so mutating it will affect parallel executions. A kinda hacky thing we do in the cache control plugin is use `willResolveField` to add stuff to the *info* object: https://github.com/apollographql/apollo-server/blob/93ebfc742fb201f885227474836ebdeaa4ab0691/packages/server/src/plugin/cacheControl/index.ts#L202-L208 (link goes to `version-4` branch), which is better than nothing until graphql-js gives us something that solves this issue more directly.

**Comment by glasser** [comment]
Alternatively, just add a function to context that folks can *pass* info to:

```
  someFieldResolver(parent, args, context, info) {
     const somethingUseful = context.figureItOut(info);
  }
```

**Comment by Flamenco** [comment]
Is the info object unique per resolver call?

**Comment by glasser** [comment]
It is, though it doesn't have "official" extension points so adding fields to it is a bit hacky!

**Comment by Flamenco** [comment]
Well I certainly do not want my clients calling functions with the `info` if the `info` might change anyway!.  I think the best way to go is simply adding a`fieldContext` object to the `info,` as you demonstrated.  I would be nice to have that field typesafe :)
