### ISSUE TITLE
"ENOENT" warnings from es-abstract

### ISSUE THREAD

**Issue by jasonmay** [apollographql/apollo-server#4546]
I provide expected/actual outcome and repro steps in the PR that's associated with this.  I'm creating this issue as a formality. See #4545 for all the information.

**Comment by jasonmay** [comment]
Another way to reproduce (again, look at the PR linked in the description for original steps and output) is to make this into a bash script and run in a temporary directory somewhere:
```bash
#!/bin/bash
rm -rf ./apollo-server
git clone https://github.com/apollographql/apollo-server
cd apollo-server
npm i
cd packages/apollo-gateway
npm link
```

**Comment by glasser** [comment]
The issue with all the operation was closed. It seems to have been some sort of npm bug? Hopefully it's all good by now.
