### ISSUE TITLE
Define a default query to be displayed when Playground loads

### ISSUE THREAD

**Issue by andresloal** [apollographql/apollo-server#4552]
It would be nice to allow to define a default query to be displayed as an example or the most used query or to display information to users when Playground loads. It could be passed in a parameter when ApolloServer is defined.

For example:
```
const server = new ApolloServer({
	typeDefs,
	resolvers,
	playground: true,
	defaultQuery: {
		`{
			# This is my default Query
		}`
	},
});
```
![image](https://user-images.githubusercontent.com/58341665/92517248-fcd26480-f1db-11ea-8bcb-6605366001c9.png)

**Comment by abernix** [comment]
You can already do this, but it's specified per Tab (since Playground is a tabbed interface).  See the documentation [here](https://github.com/prisma-labs/graphql-playground#properties) (third bullet in the _Properties_ section or search for `tabs`).
