### ISSUE TITLE
Support custom executor for subscriptions

### ISSUE THREAD

**Issue by sethtippetts** [apollographql/apollo-server#4553]
I'm using a custom executor to memoize AST generation for common queries. It's working great, but I noticed the executor doesn't get called for subscription payloads. I'd love to submit a PR for this feature assuming the Apollo team thinks it's a valid use-case. 

A few implementation options:
1. Replace the default graphql `subscribe` function with one that creates an event source and uses the supplied `executor` function
2. Expose a configuration option for a custom `subscribe` passed to `subscriptions-transport-ws`
3. Expose a configuration option `subscriber` (maybe a better name closer to `executor`?) that takes an executor specifically for subscriptions

I'd like to know what everyone thinks before spending too much time heading down any particular path. If this work aligns or conflicts with the Apollo Server 3.0 roadmap let me know. I'd like to help in any way I can!

**Comment by glasser** [comment]
Direct subscriptions integration was removed from Apollo Server in v3 last year. (Partially because of how the old flimsy integration led to problems like this one.)
