### ISSUE TITLE
Upgrade GraphQL dependency to 15.3.0

### ISSUE THREAD

**Issue by jacklp** [apollographql/apollo-server#4557]
Trying to use this in conjunction with type-graphql but I'm getting the following error:

type-graphql upgraded their graphql dependency to latest (15.3.0) recently.

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
Error: Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.

**Comment by sgyyz** [comment]
I found that upgrade the `apollo-server-lambda` to `3.0.0-alpha.3` works fine with the latest version of `type-graphql`. Hope that `apollo-server-lambda` can resolve this dependency issue as soon as possible.

**Comment by glasser** [comment]
Thanks! Handling this at #4865.

**Comment by glasser** [comment]
Apollo Server v2.21.0 will fix this.  I published alpha packages with version v2.21.0-alpha.0.  I'd love some folks to try the alpha and let me know if it works for you! Both folks who actually use the upload feature and those who don't! It's currently in the release-2.21.0 branch, being tracked at https://github.com/apollographql/apollo-server/pull/4922
