### ISSUE TITLE
API Gateway Lambda payload 2.0

### ISSUE THREAD

**Issue by natac13** [apollographql/apollo-server#4569]
Is there any support coming for ApiGatewayProxyHandlerV2?

**Comment by vaunus** [comment]
I would like to know whether this is planned as well.

**Comment by krivachy** [comment]
This seems to be supported as of [v2.23.0](https://github.com/apollographql/apollo-server/blob/main/CHANGELOG.md#v2230), I was able to get it working with:

```typescript
import { ApolloServer } from 'apollo-server-lambda';
import { APIGatewayProxyEventV2 } from 'aws-lambda';

const apolloServer = new ApolloServer<APIGatewayProxyEventV2>({
  typeDefs,
  resolvers,
  context: async (apolloContext): Promise<ReqContext> => {
    const apiGatewayEvent = apolloContext.event as APIGatewayProxyEventV2;
    // ....
  }
});

export const handler = apolloServer.createHandler({
  cors: {
    origin: '*',
  },
});
```

**Comment by glasser** [comment]
Thanks for linking this here @krivachy! Yes, we now aim to support payload 1.0 and 2.0 in `apollo-server-lambda` as of v2.23.0.
