### ISSUE TITLE
Graphiql doesn't work

### ISSUE THREAD

**Issue by Ibrahim9595** [apollographql/apollo-server#457]
I've setup the graphql-tools from Apollo and the graphiql doesn't show results it gives me plain html any idea how to fix this

**Comment by bwlt** [comment]
is it like the #449 issue ?

**Comment by shkurkin** [comment]
I just ran into this. The fix for me was that I hadn't set the endpointURL correctly. 

before (broken, just seeing lots of red html in the results box)
```
app.use('/gql', bodyParser.json(), graphqlExpress({ schema: schema }))
app.use('/iql', graphiqlExpress({ endpointURL: '/iql' }));
```

after (fixed)
```
app.use('/gql', bodyParser.json(), graphqlExpress({ schema: schema }))
app.use('/iql', graphiqlExpress({ endpointURL: '/gql' }));
```
