### ISSUE TITLE
apollo-server-core missing lru-cache dependency

### ISSUE THREAD

**Issue by ThomWright** [apollographql/apollo-server#4601]
Error:

```
Cannot find module 'lru-cache'
Require stack:
- /app/node_modules/apollo-server-core/dist/plugin/usageReporting/signatureCache.js
- /app/node_modules/apollo-server-core/dist/plugin/usageReporting/plugin.js
- /app/node_modules/apollo-server-core/dist/plugin/usageReporting/index.js
- /app/node_modules/apollo-server-core/dist/plugin/index.js
- /app/node_modules/apollo-server-core/dist/ApolloServer.js
- /app/node_modules/apollo-server-core/dist/index.js
- /app/node_modules/apollo-server-express/dist/index.js
- /app/dist/index.js
```

Dependency versions:
```
└─┬ apollo-server-express@2.18.0
  └── apollo-server-core@2.18.0 
```

Pretty sure it was introduced in this commit: https://github.com/apollographql/apollo-server/commit/1bb4527a5b074489e1a2cabf40f89f6214bfefc7

Looks like the `lru-cache` dependency needs adding here: `packages/apollo-server-core/package.json`.

**Comment by abernix** [comment]
Thanks for reporting this! This is fixed by https://github.com/apollographql/apollo-server/pull/4600 which landed in v2.18.2 thanks to @oliversalzburg (for the fix) and @glasser (for the release; #4628).
