### ISSUE TITLE
applyMiddleware ServerRegistration not assignable with express

### ISSUE THREAD

**Issue by milorue** [apollographql/apollo-server#4635]
I have some previously working code from another project but trying out some new typescript configurations. When I try to use `ApolloServer.applyMiddleware` to add an express server it throws a type error for an express object not being assignable to an object of type ServerRegistration.

Error:
`TSError: ⨯ Unable to compile TypeScript
src/index.ts (22,13): Argument of type '{ server: any; path: string; cors: false; }' is not assignable to parameter of type 'ServerRegistration'.
  Object literal may only specify known properties, and 'server' does not exist in type 'ServerRegistration'. (2345)`

Code:

index.ts
```
import "reflect-metadata";
import {createConnection} from "typeorm";
import express from 'express'
import cors from 'cors'
import cookieParser from "cookie-parser";
import apolloServer from './server/server'

(async() => {
    const server = express()

    server.enable('trust proxy')

    createConnection().then(async _connection => {
        server.use(cors({
            credentials: true,
            origin: 'http://localhost:3000'
        }))

        server.use(cookieParser())

        apolloServer.applyMiddleware({
            server,
            path: '/graphql',
            cors: false
        })

        server.listen(8000, () => {
            console.info("Server started on port: 8000")
        })
    })

})
```

server.ts
```
import {ApolloServer} from 'apollo-server-express'
import schema from './schema'

const apolloServer = new ApolloServer({
    schema,
    context: ({req, res}) => ({req, res}),
    formatError: (err): Error => {
        if (err.message.startsWith('Database Error: ')) {
            return new Error('Internal server error');
        }
      
        return err;
    }
})

export default apolloServer
```

There are some other issues about this that didn't seem to solve my issue and didn't mention the type ServerRegistration.

My package.json looks like this for the related types
```
"apollo-server-express": "^2.18.2",
"express": "^4.17.1",
"express-serve-static-core": "^0.1.1",
```

```
"@types/express": "^4.17.8",
"@types/express-serve-static-core": "^4.17.13",
```

**Comment by musicpulpite** [comment]
Ran into the same problem when upgrading `apollo-server-express` from 2.15.0 to 2.19.0. 

Digging into the Typescript tsc error, it looks like the `ApolloServer.ServerRegistration` interface expects an argument of type `express.Application` not `express.Express` but the `Express` interface already extends the `Application` interface so this should be no problem.

```ts
// /node_modules/apollo-server-express/node_modules/@types/express-serve-static-core/index.d.ts

export interface Express extends Application {
    request: Request;
    response: Response;
}
```

I'm surprised the compiler can't handle this case automatically. Does anyone know of a compiler option that would allow this?

**Comment by sgentile** [comment]
I'm having the same issue - anyone come up with a work around ?

**Comment by ransfordarthurjr** [comment]
Try adding the "app" key to the applyMiddleware function
doing that resolved the error in my case
 
```
apolloServer.applyMiddleware({
    app: server,
    path: '/graphql',
    cors: false
})
```

**Comment by glasser** [comment]
@ransfordarthurjr was correct that the option was called `app`, not `server`. That said, in Apollo Server 4 we've simplified things by replacing this "applyMiddleware" function with an `expressMiddleware` function that returns a middleware that you can pass to `app.use` directly just like with any other middleware.
