### ISSUE TITLE
Directive \"dateFormat\" may not be used on FIELD.

### ISSUE THREAD

**Issue by usama-asfar** [apollographql/apollo-server#4653]
### Can't set directive on client query but works on the server-side schema.

I'm trying to set the directive `dateFormat` on my client-side query when I execute the query apollo throws `Directive \"dateFormat\" may not be used on FIELD.`, But setting the directive `dateFormat` on server-side schema works.

### package 

```
  "apollo-server-micro": "^2.16.0",
  "next": "9.3.6",
```
### code

Apollo server setup `pages/api/graphql`
```js
const { ApolloServer } = require("apollo-server-micro");

import schema from "../../server/graphql";

const apolloServer = new ApolloServer({
  schema,
  engine: {
    reportSchema: true,
    variant: "current",
  },
  context: async ({ req }) => {
    return { headers: req.headers };
  },

  // tracing: process.env.NODE_ENV === "development",
  // debug: process.env.NODE_ENV === "development",
});

export const config = {
  api: {
    bodyParser: false,
  },
};

export default apolloServer.createHandler({ path: "/api/graphql" });
```

Defining date format directive `schema.js`
```gql
directive @dateFormat(format: String) on FIELD_DEFINITION
```
Date format directive `dateFormat.js`

```js
const { SchemaDirectiveVisitor } = require("apollo-server-micro");
const { defaultFieldResolver } = require("graphql");
const dateFormat = require("dateformat");

class DateFormatDirective extends SchemaDirectiveVisitor {
  visitFieldDefinition(field) {
    const { resolve = defaultFieldResolver } = field;
    field.resolve = async function (...args) {
      const result = await resolve.apply(this, args);
      return dateFormat(result, "d mmmm yyyy");
    };
  }
}

export default DateFormatDirective;

```
Setting up directive 

```js

import { makeExecutableSchema } from "graphql-tools";


import {
  DateFormatDirective,
} from "./directives";

export default makeExecutableSchema({
  typeDefs: require("./schema"),
  resolvers: {
    Query: {
      ...
    },
    Mutation: {
      ...
    },
  },
  schemaDirectives: {
    dateFormat: DateFormatDirective,
  },
});

```

**Comment by glasser** [comment]
Right now we are planning to remove support for `schemaDirectives` in Apollo Server 3, because the project that implements it (graphql-tools) considers it to be a legacy API. Folks who want to use `schemaDirectives` or its non-legacy replacement `schemaTransforms` can use `@graphql-tools/schema` directly to create a schema passed in with `new ApolloServer({schema})`;  issues relating to these options should probably be opened in the graphql-tools repo.
