### ISSUE TITLE
apollo-server-fastify does not have method applyMiddleware

### ISSUE THREAD

**Issue by 97amarnathk** [apollographql/apollo-server#4657]
As per the documentation https://www.apollographql.com/docs/apollo-server/integrations/middleware/, all middle ware server packages should be having `applyMiddleware`

**Comment by alexneo2003** [comment]
have any thoughts on this? i faced the same problem too

` UnhandledPromiseRejectionWarning: TypeError: server.applyMiddleware is not a function`

**Comment by 97amarnathk** [comment]
Yes. The Fastify implementation doesn't have the applyMiddleware method for some reason.

Do this :

```typescript
(async function () {
  app.register(server.createHandler());
  await app.listen(3000);
})();
``` 

instead of doing 

```typescript
server.applyMiddleware(fastifyApp)
```

**Comment by 97amarnathk** [comment]
But if you already have a Fastify server implementation like I did, you could create a subscriptions endpoint using `subscriptions-transport-ws` package.

For this, server side implementation is pretty straight forward. However on the client side, the documentation is not up to date. Check out `urql` clients guide.

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Fastify integration. Check out the [`@as-integrations/fastify`](https://www.npmjs.com/package/@as-integrations/fastify) package; this new package is maintained by Fastify users and most likely already solves the issue described above. Sorry for the delay!
