### ISSUE TITLE
Incorrect type for ExpressContext req.header

### ISSUE THREAD

**Issue by AdrienLemaire** [apollographql/apollo-server#4674]
I had a difficult to debug bug due to an incorrectly inferred type for the result of `req.header()` from ExpressContext

example:
```ts
import type { ExpressContext } from "apollo-server-express/src/ApolloServer";

const context = async ({ req }: ExpressContext): Promise<Neo4jContext> => {
  const token = req.header("authorization")
    ? req.header("authorization").replace(/^Bearer /, "")
    : null;
  const user = token
    ? (jwt.verify(token, environment.neo4j.jwtSecret) as JwtUser)
    : null;

  return {
    driver,
    models: {
      User: generateUserModel(user),
    },
  };
```

**Expected types:**
* `token: string | null`
* `user: JwtUser | null`

**Actually inferred types:**
* `token: string`
* `user: JwtUser`

As a result, typescript didn't detect that that my function `generateUserModel` could receive null, while the function's implementation was only expecting a JwtUser.

When checking the type of `req.header`, I'm seeing:
> (method) Request<ParamsDictionary, any, any, QueryString.ParsedQs>.header(name: string): string (+1 overload) 

When I go to the type definition, I arrive to `node_modules/@types/express-serve-static-core/index.d.ts`

```ts
export interface Request<P = ParamsDictionary, ResBody = any, ReqBody = any, ReqQuery = ParsedQs> extends http.IncomingMessage, Express.Request {
    header(name: "set-cookie"): string[] | undefined;
    header(name: string): string | undefined;
```

The header function seems to return either a string or undefined, so I'm quite confused as why inference typing is broken here...

Packages:
* typescript 4.0.3
* apollo-server 2.17.0
* apollo-server-express 2.17.0

**Comment by glasser** [comment]
That does seem strange, but we can't look into it without a full self-contained reproduction. (eg, this might depend on your tsconfig settings.) Perhaps the passage of time and iterations of `@types/express-serve-static-core` may have resolved this issue?
