### ISSUE TITLE
docs: Either "schema" OR "typeDefs + resolvers" are required.

### ISSUE THREAD

**Issue by JoseJuan81** [apollographql/apollo-server#4684]
Hi, apollo team

The `apollo-server` only accepts  SDL syntax when is created (`typeDefs` and `resolvers`):
```js
const typeDefs = gql`
 type Query {
    hello: string
 }`
const resolvers = {
  Query: {
    hello: () => 'Hello world'
}
new ApolloServer({
  typeDefs,
  resolvers,
  ...
})
```
I wish can pass `GraphQLSchema` object syntax directly into ApolloServer instance.
I like this syntax over SDL but Apollo doesn't support it.

```js
const queryType = new GraphQLObjectType({
  name: 'Query',
  fields: {
    hello: {
      name: 'helloField',
      type: GraphQLString,
      resolve: () => 'Hola mundo',
    },
  },
});

const _schema = new GraphQLSchema({
  query: queryType,
});
new ApolloServer({
  schema: _schema,
  ...
})
```

**Comment by wmertens** [comment]
This is exactly what I do, and it just works. What is the error?

**Comment by JoseJuan81** [comment]
@wmertens can you tell me how do you do?

**Comment by wmertens** [comment]
@JoseJuan81 I do what you write, I pass a GraphQLSchema instance to ApolloServer.

What is the error you're getting

**Comment by JoseJuan81** [comment]
@wmertens Hi,
I have no errors in my project about this because I'm working with SDL syntax, I just want to pass a `GraphQLSchema` syntax.

I read in the docs that the `typeDefs` and `resolvers` are required: https://www.apollographql.com/docs/apollo-server/api/apollo-server/ so, do I have to pass `typeDefs`, `resolvers` and `schema` props to the ApolloServer?

Maybe the error is in the docs because there is no indications neither examples about GraphQLSchema syntax implementations.

**Comment by wmertens** [comment]
So when you try to use your example, you don't get an error, but it also doesn't work? Because my code is pretty much like your example and it just works...

**Comment by JoseJuan81** [comment]
Ok, @wmertens you're right, I just made a small test in development mode and works...
I guess It was a misunderstood, but I recommend to update the apollo docs:
<img width="757" alt="Captura de Pantalla 2020-12-22 a la(s) 12 02 30 p  m" src="https://user-images.githubusercontent.com/21971589/102914009-a79a2600-444d-11eb-8bed-2ac2eb36ab1d.png">
Those properties are required and that is confusing.

In the code `typeDefs` is not required:
<img width="576" alt="Captura de Pantalla 2020-12-22 a la(s) 12 13 51 p  m" src="https://user-images.githubusercontent.com/21971589/102915223-73276980-444f-11eb-9027-d6e149642aeb.png">

The ApolloServer needs one of them.

**Comment by abernix** [comment]
It is true that (`typeDefs` AND `resolvers`) **OR** (`schema`) should be passed.  In fact, in federation (when using `buildFederatedSchema`), it isn't uncommon to use `schema: buildFederatedSchema([{ typeDefs, resolvers }])`, rather than using `typeDefs` or `resolvers` at all!

Generally speaking, PRs are welcome!

cc @StephenBarlow for suggestions on how we might render this effectively (or if we should merely use our words to do so!)

**Comment by abernix** [comment]
And as the code above points out, there's a third option of using (the incredibly undocumented, I think?) `modules` approach in lieu of either of them.

**Comment by abernix** [comment]
See also: https://github.com/apollographql/apollo-server/issues/4386

**Comment by JoseJuan81** [comment]
I must say, my project now use GraphQLSchema over than SDL and that was somethig that I wanted, so thank you all @wmertens and @abernix .
I think you could add more examples in the tutorial about how to use apollo with GraphQLObjects and for Client side It would be nice to include some Vue (with vuex) tutorial.
Regards.

**Comment by glasser** [comment]
[The docs](https://www.apollographql.com/docs/apollo-server/api/apollo-server/) are pretty clear about this now, I hope.
