### ISSUE TITLE
Unexpected connection attempt to `engine-graphql.prod.svc.cluster.local`

### ISSUE THREAD

**Issue by oliversalzburg** [apollographql/apollo-server#4688]
When running an Apollo server with schema reporting enabled, I see the following message in our logs:
> Error reporting server info to Apollo during schema reporting: Error: request to http://engine-graphql.prod.svc.cluster.local:8081/api/graphql failed, reason: read ECONNRESET

That connection attempt is very unexpected and I don't know why a local address would be connected to for any reason.

**Comment by abernix** [comment]
The message is revealing an internal hostname of an internal GraphQL service in the Apollo Studio environment.  Are you seeing this message consistently or was this something that happened at or doing a particular period of time?

**Comment by oliversalzburg** [comment]
I was browsing through the server logs while troubleshooting an unrelated issue and saw a single occurences of this, without any additional context that seemed out of the ordinary.

Searching through the logs takes forever, so I haven't been able to verify if it occurred multiple times. If so, then it appears to be at very low frequency.

Sounds like it's just showing me a downstream error that's nothing to worry about?

**Comment by abernix** [comment]
That's right.  This was most likely a short-term outage in the schema reporting service (in one of *our own*) federated services which would have been retried by your own Apollo Server instance and wouldn't have affected its ability to serve requests.

I've let the team responsible for this know about it, but if you see this come up repeatedly, please reach out to them on Intercom support within [Apollo Studio](https://studio.apollographql.com/) so they can help further.
