### ISSUE TITLE
Azure Function runtime 3 support

### ISSUE THREAD

**Issue by donniekerr** [apollographql/apollo-server#4694]
When do you expect to support current version of Azure Function runtime?

**Comment by glasser** [comment]
We no longer directly maintain an Azure Functions integration. Instead, AS4 has a well-defined API for building integrations. If you're interested in helping to maintain a package for building Azure Functions with AS, we're discussing it over at https://github.com/apollographql/apollo-server/issues/6032

The snippet I linked in that issue about `@vendia/serverless-express` should support Azure Functions v3 and v4!
