### ISSUE TITLE
Working @defer example

### ISSUE THREAD

**Issue by mfsinareshe** [apollographql/apollo-server#470]
Hi Team,

Can you please share a blog/codebase showing the implementation of directives (defer, live and stream) in graphql?

**Comment by DxCx** [comment]
they are not offically supported by graphql-js

**Comment by mfsinareshe** [comment]
Thanks for quick response! 
So there are no publicly available implementation details and examples?

**Comment by stubailo** [comment]
Not that I know of, unfortunately. Certainly not widely used ones.

**Comment by BjornMelgaard** [comment]
@stubailo , hi, directives are part of graphql-js now, are there any examples how to add custom directive to apollo-server, like [this](https://medium.com/the-graphqlhub/graphql-tour-directives-558dee4fa903)?

**Comment by stubailo** [comment]
@BjornMelgaard can you link to what you mean by them being part of graphql-js?

**Comment by BjornMelgaard** [comment]
they are part of [graphql-js](https://github.com/graphql/graphql-js/blob/8dcc5b0cfb9b99be6195417dfc35fe59b333361a/src/validation/__tests__/UniqueArgumentNames-test.js) :smile: , graphcool made baas based on them))

**Comment by stubailo** [comment]
Yes, they parse as part of the query, but GraphQL.js doesn't have any special support for them on the server! Graphcool uses them as part of the schema to generate stuff, which is pretty different from this case. Plus, Graphcool doesn't use GraphQL.js for that.
