### ISSUE TITLE
Allow specifying a default ttl for InMemoryLRUCache

### ISSUE THREAD

**Issue by javiertury** [apollographql/apollo-server#4709]
`lru-cache` accepts a `maxAge` parameter during construction which becomes the default `ttl`. But it cannot be configured from InMemoryLRUCache which means there is no time limit, stale resources are kept indefinitely if they are not purged. This makes micro-caching cumbersome to implement and error prone because `ttl` must be specified for each cache write. In contrast the default value for memcached more reasonable, 300ms. In the case of redis it can be customized.

It would be great if InMemoryLRUCache could be configured with a default `ttl`, for instance:

```
  cache: new InMemoryLRUCache({
    maxSize: 1000,
    ttl: 1 // in seconds
  }),
```

And related to #2252, InMemoryLRUCache could also establish a more conservative default `ttl`, like 1 second or 1 hour, but not indefinitely.

If you think this is a good idea, tell me and I will submit a PR.

**Comment by glasser** [comment]
The current version of InMemoryLRUCache (in `@apollo/utils.keyvaluecache`) takes the same constructor arguments as `lru-cache` and passes them through (with its own defaults for `sizeCalculation` and `maxSize`).
