### ISSUE TITLE
RemoteGraphQLDataSource chaining

### ISSUE THREAD

**Issue by mac2000** [apollographql/apollo-server#4710]
According to type definition I can pass RemoteGraphQLDataSource instance as a constructor argument but it does not work as expected

Packages (latest):

package|version
-------- | ------
@apollo/federation|^0.20.4
@apollo/gateway|^0.21.0
apollo-server|^2.19.0

## The expected behavior

If I use something like `new LoggableDataSource( new PassClientHeaders ( { url } ) )` both datasources should be used

## The actual behavior

Only most top data source is being called

## Reproduction

Unfortunately I did not find a way to run both service and gateway in code sanbox like tools but repro is just two files:

**service.js**

```js
const { ApolloServer, gql } = require("apollo-server");
const { buildFederatedSchema } = require("@apollo/federation");

const typeDefs = gql`
  type Query {
    hello: String!
  }
`;

const resolvers = {
  Query: {
    hello: () => "world",
  },
};

const server = new ApolloServer({
  cacheControl: true,
  schema: buildFederatedSchema([{ typeDefs, resolvers }]),
  context: ({ req }) => {
    console.log("context", req.header("X-Foo"));
  },
});

server.listen({ port: 4001 }).then(({ url }) => console.log("service", url));
```

**gateway.js**

```js
const { ApolloServer } = require("apollo-server");
const { ApolloGateway, RemoteGraphQLDataSource } = require("@apollo/gateway");

class DataSource1 extends RemoteGraphQLDataSource {
  willSendRequest({ request }) {
    console.log("DataSource1::willSendRequest");
    request.http.headers.set("X-Foo", "foo");
  }
}

class DataSource2 extends RemoteGraphQLDataSource {
  willSendRequest({ request }) {
    console.log("DataSource2::willSendRequest");
    request.http.headers.set("X-Bar", "bar");
  }
}

const gateway = new ApolloGateway({
  serviceList: [{ name: "service", url: "http://localhost:4001" }],
  buildService: ({ url }) => new DataSource2(new DataSource1({ url })), // will not call DataSource1 at all
});

const server = new ApolloServer({
  gateway,
  subscriptions: false,
});

server.listen(process.env.PORT || 4000).then(({ url }) => console.log("gateway", url));
```

Not sure if this is by design, but why then there is such type definitions?

## Workaround

At moment we can extend class to achieve desired behavior, e.g.:

```js
class DataSource1 extends RemoteGraphQLDataSource {
  willSendRequest({ request }) {
    console.log("DataSource1::willSendRequest");
    request.http.headers.set("X-Foo", "foo");
  }
}

class DataSource2 extends DataSource1 {
  willSendRequest({ request }) {
    super.willSendRequest({ request })  
    console.log("DataSource2::willSendRequest");
    request.http.headers.set("X-Bar", "bar");
  }
}

const gateway = new ApolloGateway({
  serviceList: [{ name: "service", url: "http://localhost:4001" }],
  buildService: ({ url }) => new DataSource2({ url }), // use extends instead of chaining
});
```

**Comment by abernix** [comment]
The type definitions don't allow passing an instance of a `RemoteGraphQLDataSource`, but instead passing any of the properties or methods of the class in an options object.  It's a somewhat odd choice that allows a different approach than subclassing, but forgoes any of the protection that `private` distinctions offer since it assigns them directly onto the `this` of the instance.

Anyhow, your workaround is the correct approach.  We don't intend on allowing chaining.

**Comment by mac2000** [comment]
Hm, seems like I just misread the code

![image](https://user-images.githubusercontent.com/88868/103416244-7c6eaf80-4b8e-11eb-929f-930c35ea3a67.png)

But I can pass instance and nothing won't complain and will compile, e.g.:

```ts
import { RemoteGraphQLDataSource } from "@apollo/gateway";

class DataSource1 extends RemoteGraphQLDataSource {}
class DataSource2 extends RemoteGraphQLDataSource {}

new DataSource2(new DataSource1({ url: 'http://localhost:4000' }));
```

That probably was the main reason for my confusion and mismatched expectations and reality :)
