### ISSUE TITLE
Defered Queries (@defer) not working in alpha build

### ISSUE THREAD

**Issue by sanadella** [apollographql/apollo-server#4713]
I'm trying to get deferred queries to work following this [doc.](https://www.apollographql.com/docs/react/v2.4/features/defer-support/#the-defer-directive)
I installed the alpha build - "apollo-server": "^2.19.0-alpha.1",

I'm trying to use @defer tag on a field but I get "Unknown directive "defer"." error.
![error](https://user-images.githubusercontent.com/68077448/98143814-d13fc380-1e86-11eb-9225-4511a7431b4f.png)

**Comment by hwillson** [comment]
We're working on `@defer` / `@stream` support and will be tracking progress in https://github.com/apollographql/apollo-server/issues/5893. The docs you referenced were for an experimental implementation of `@defer` / `@stream` that did not make it into Apollo Server. Thanks!
