### ISSUE TITLE
bug: fast-json-stringify missing from apollo-server-fastify dependencies

### ISSUE THREAD

**Issue by quinnturner** [apollographql/apollo-server#4715]
`fast-json-stringify` is being required in `apollo-server-fastify`'s `ApolloServer.ts`. However, it does not list `fast-json-stringify` as a dependency. This is breaking Yarn 2's dependency management.

The fix involves adding `fast-json-stringify` to the dependency list for both Apollo v2 and v3.

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Fastify integration. Check out the [`@as-integrations/fastify`](https://www.npmjs.com/package/@as-integrations/fastify) package; this new package is maintained by Fastify users and most likely already solves the issue described above. Sorry for the delay!
