### ISSUE TITLE
Lint error for `createTestClient`

### ISSUE THREAD

**Issue by extjbhlego** [apollographql/apollo-server#4724]
Hello 👋

Using the `createTestClient` method upsets our linting rule `eslint@typescript-eslint/unbound-method`, [documented here](https://github.com/typescript-eslint/typescript-eslint/blob/v4.4.0/packages/eslint-plugin/docs/rules/unbound-method.md)

Looking at the implementation, I suspect it has to do with
`const executeOperation = server.executeOperation.bind(server);` on [line 31](https://github.com/apollographql/apollo-server/blob/9fbf66874953562ea6065b62a3f3c5c677354005/packages/apollo-server-testing/src/createTestClient.ts#L31)

`"apollo-server-testing": "2.19.0"`

- **The expected behavior**
No warnings

- **The actual behavior**
Warning

**Comment by lauriharpf** [comment]
Have also encountered this issue with `apollo-server-testing` `2.24.0`. Repository with a reproduction at https://github.com/lauriharpf/reproduce-create-test-client-linting-issue .

It looks like adjusting the typing of `ApolloServerTestClient` would remove the linter error. Could that be enough since the `createTestClient` function is not part of a class?

**Comment by glasser** [comment]
`apollo-server-testing` is merely a very thin wrapper around `ApolloServer.executeOperation` that introduces its own new API to learn for no apparent (to me) benefit.   I'm currently planning to (in the next few days) update our docs to remove references to `apollo-server-testing` and just document `executeOperation` instead, and then remove `apollo-server-testing` from the forthcoming AS 3.0.  See #4952 for details.

(There is one minor advantage that `apollo-server-testing` has over `executeOperation`: you can pass in either a string or a parsed document, whereas `executeOperation` only accepts a string. I will probably change `executeOperation` to have that property as well.)

I'd suggest as a "workaround" you just stop using `apollo-server-testing` today.  Replace this:

```js
import { createTestClient } from 'apollo-server-testing';

const { query } = createTestClient(server);
query({ query: SOME_QUERY });
```

with

```js
server.executeOperation({query: SOME_QUERY});
```

(If SOME_QUERY was a literal `gql` document, change it to a string, or if you want to keep it as a document in your code, pass it to `print` from `graphql` first. As mentioned above I will hopefully make this unnecessary soon.)

Let me know if this isn't an acceptable alternative and it may feed into the plans described above!

**Comment by lauriharpf** [comment]
Thank you for the explanation and the instructions, the suggested approach works well for me. Looking forward to the upcoming updates! :+1:
