### ISSUE TITLE
Custom formatError function is not called on malformed requests

### ISSUE THREAD

**Issue by louisbuchbinder** [apollographql/apollo-server#4734]
### Package Versions:
apollo-server-core@2.19.0
apollo-server-errors@2.4.2
apollo-server-express@2.19.0
apollo-server@2.19.0

### Expected Behavior:
The custom `formatError` function should be called for every error encountered by the server.

### Actual Behavior:
If a request is made to an apollo-server that is missing a query or is otherwise malformed the error handler short circuits and responds directly without calling the custom `formatError` function.

If an error is thrown in this block it will not call the custom `formatError`: https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-core/src/runHttpQuery.ts#L202-L230 

That will cause the program execution to be caught here where the response is sent directly: https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-express/src/expressApollo.ts#L54-L74 

### Reproduction:
- Apollo Server listening on localhost:80
- Custom `formatError` function defined in the Apollo Server instantiation. As an example:
```
formatError(err) {
  console.log(err);
  return err;
}
```
- format error does not get called: `curl localhost -X POST -H Content-Type:application/json --data '' -v`
- format error does get called: `curl localhost -X POST -H Content-Type:application/json --data '{"query":"{}"}' -v`

### Possibly Related:
apollo-server-core formatError never called [#1439](https://github.com/apollographql/apollo-server/issues/1439)

**Comment by trevor-scheer** [comment]
This should no longer be the case in AS v4. We also have some new plugin events which you might find useful (i.e. https://www.apollographql.com/docs/apollo-server/integrations/plugins-event-reference#invalidrequestwasreceived)
