### ISSUE TITLE
TypeError: Cannot create property 'message' on string

### ISSUE THREAD

**Issue by aaronadamsCA** [apollographql/apollo-server#4742]
https://github.com/apollographql/apollo-server/blob/a26c08dc43fb7896407d90be17b7b8befdbc73f0/packages/apollo-server-core/src/runHttpQuery.ts#L145-L146

This can cause the server to fail to respond due to an internal `TypeError`:

```
System.Private.CoreLib: Exception while executing function: Functions.graphql. System.Private.CoreLib: Result: Failure
Exception: TypeError: Cannot create property 'message' on string 'Invalid bearer token'
```

`Promise.reject("Invalid bearer token")` is valid, assuming `e` is an instance of `Error` is not.

This is easy to work around, but it took me a while to hunt down why my server was encountering trouble with a specific call.

**Comment by trevor-scheer** [comment]
This should no longer be the case in AS 4.

https://github.com/apollographql/apollo-server/blob/a404bf17e86d6f53588b2796c9190ad98779a6f9/packages/server/src/errorNormalize.ts#L94-L105
