### ISSUE TITLE
Inaccurate tracing request times

### ISSUE THREAD

**Issue by popey456963** [apollographql/apollo-server#4754]
**Apollo Version:** 2.19.0
**Package:** apollo-server-express

Using the GraphQL UI, I'm calculating response times to various requests.  All of the "Request" / "Response" times seem to be heavily exaggerated, hundreds of times larger than they are in reality.

![image](https://user-images.githubusercontent.com/1338129/99913929-4538f300-2cf2-11eb-97c2-d57ad08b6e9b.png)

This query did not take ~800ms to return.  Using firefox dev tools we see a much more realistic 4ms:

![image](https://user-images.githubusercontent.com/1338129/99913943-57b32c80-2cf2-11eb-8342-3ac99dca16b2.png)

This happens no matter my query and setup.  The "account" phase, which is the bit that actually matters, seems to be the correct time.  It's just a little disconcerting seeing it say the request took so long.

**Comment by popey456963** [comment]
Restarting seemed to fix the issue.  I can't reproduce this.

Leaving it open in case anyone has any ideas?

**Comment by dude-awesome** [comment]
having the same issue. The request time is increasing over time. only when I restart the server or redeploy its "fast" for a while and gets slower over time.

**Comment by popey456963** [comment]
Can agree with @dude-awesome, the application was open for two hours to get the above figures.  It's reproducible if you keep it up for a long time.

**Comment by dude-awesome** [comment]
its also slowing down my general apollo-server performance. so the queries are really getting slower over time. only a redeploy will fix this for some hours. CPU and Memory is fine. so there are no critical peaks or memory leaks but my queries are very slow.

**Comment by dude-awesome** [comment]
![Uploading studio.png…]()

**Comment by dude-awesome** [comment]
<img width="1554" alt="studio" src="https://user-images.githubusercontent.com/3764301/100467102-41321a00-30d2-11eb-8b28-9412cd2b76f2.png">

**Comment by trevor-scheer** [comment]
Possibly resolved in https://github.com/apollographql/apollo-server/pull/7000 ?

Sorry we never responded to this issue. If you get the chance to upgrade to AS4 and validate the fix that would be great. If the issue persists I'd be happy to reopen this.
