### ISSUE TITLE
Method that uses __resolveReference  not getting executed...Details are below.

### ISSUE THREAD

**Issue by shnisheeth** [apollographql/apollo-server#4759]
I have a use case where  reference of an attribute in one service has it definition/execution  in another service - in line with what the Federation of supposed to do, but somehow the __resolveReference is not getting called so am not sure what am I missing.
For me, there is no need to resolve the reference by a specific ID ,  as whatever data (array) I return from the called service to the caller is all applicable and so there is no need for the fitering. I am not sure If am missing something or Apollo Fed - __resolveReference only works when there is a reference established by some sort of a primary key/foreign key relationship.

Code Snippets - 
****Service that has the reference -**** 
type A{
    id: ID!
   name: String
    terms: [Term]

    }

Now the place where the Reference is defined - so the implementing or the called Service - 

const resolvers = {
  Term: {
    __resolveReference(object) {
      console.log("Resolving the Referencee......");
      return fetch(`${apiUrl}/terms/`).then(res => res.json());
    }
  },
Thanks for filing an issue on Apollo Server!

This never gets called and when I refer the type Term and its elements into my query - I get an error "Expected Iterable, but did not find one for field..." which makes sense as the data never got fetched.

Your help is deeply appreciated.

Before reporting a bug, please first check for existing or closed issues
and read the instructions for filing a bug report:

https://github.com/apollographql/apollo-server/blob/main/CONTRIBUTING.md#reporting-bugs

### This bug report should include:

- [x] A short, but descriptive title. The title doesn't need "Apollo" in it.
- [ ] The package name and version of Apollo showing the problem.
- [ ] If applicable, the last version of Apollo where the problem did _not_ occur.
- [ ] The expected behavior.
- [ ] The actual behavior.
- [ ] A **simple**, runnable reproduction!
      Please make a GitHub repository that anyone can clone and run and see the
      problem. Other great ways to demonstrate a reproduction are using our
      CodeSandbox template (https://codesandbox.io/s/apollo-server), or re-mixing
      our Glitch template (https://glitch.com/~apollo-launchpad).

  Please make sure that you include the following information to ensure that your issue is actionable.

  If you don't follow the template, your issue may end up being closed without anyone looking at it carefully, because it is not actionable for us without the information in this template.

-->

**Comment by shnisheeth** [comment]
Essentially, the quetion I have is - if the __resolveReference has to return an array of objects - what should we write in the calling function to accept it - 
Writing it like return { __typename: "Term", id:object.id} is definitely not working

**Comment by shnisheeth** [comment]
Any luck with this question, anyone?

**Comment by ScripterSugar** [comment]
Needs more information. IMO the problem should be one of these.

1. Your schema definition doesn't match federation requirements (In this case your gateway will fail to build proper query plan)
I need full schema definions for `Term` type to check this.

2. Your Type A resolver's terms field is broken (It should return array of objects including every fields(keys) described in @keys directive in your schema of origin service.

I need resolver code for type `A` to check this.

**Comment by trevor-scheer** [comment]
If this issue still persists, please reopen this issue against the https://github.com/apollographql/federation repo with a runnable reproduction.
