### ISSUE TITLE
Property 'applyMiddleware' does not exist on type 'ApolloServer' while using 'apollo-server-fastify'

### ISSUE THREAD

**Issue by Sparklytical** [apollographql/apollo-server#4768]
- [ ] Apollo fastify package is missing Middleware
- [ ] Like in apollo-server-express there is an option to apply middleware, it's also given there in docs by doing something like this 
```js
apolloServer.applyMiddleware({
    app,
    cors: false,
  });
```

- [ ] The ts compiler says that `Property 'applyMiddleware' does not exist on type 'ApolloServer'.` when I try to use the ApolloServer imported from 'apollo-server-fastify'

   versions- 
1. "apollo-server-fastify": "^2.19.0"
2.  "fastify": "^3.8.0",

Or maybe the way I'm applying it is wrong a bit of Info on either the official docs or in the readme of 'apollo-server-fastify' will be good enough

**Comment by kolserdav** [comment]
I have the same problem.

**Comment by kolserdav** [comment]
> I have the same problem. ![screenshot](https://camo.githubusercontent.com/7e0187514357dc9f5377d2f35b48ee2892c65a7e31a5053e7fcbaeb2ab3b0905/68747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f70772f414374432d3364584231555562626e436466525a6f3870717431634743774d7465694e384a54344b4a744a33347a4f4a67566365485a594c527a446f4a38637044726257414936334a307a6a4b486352443853413948634f6f694c65366f41585138426b4b5f363862744c4b4775375757754c356f447062394452636c57656b426d4c7933494d7a33584f3354595555644359734d426253684846583d77313536302d683837382d6e6f3f61757468757365723d303f7261773d74727565)

I use `apollo-server-express` instead `apollo-server-micro` and my problem was solved)

**Comment by NickMandylas** [comment]
"applyMiddleware" is not a fastify method, that's for express. Fastify uses "register" to apply middleware.

Here's my apollo-server + fastify boilerplate - https://github.com/NickMandylas/typescript-fastify-graphql-boilerplate/blob/master/src/index.ts, that'll help you out.

Also as well, the stable branch of apollo-server-fastify doesn't work with fastify v3, you need to use the alpha branch `apollo-server-fastify@3.0.0-alpha.3` or I recommend using this package `@autotelic/apollo-server-fastify`, for the time being.
