### ISSUE TITLE
Per-subscription authorization (authentication)

### ISSUE THREAD

**Issue by ScripterSugar** [apollographql/apollo-server#4771]
I'm currently looking for the best practice to achieve per-resolver level authorization for subscriptions, as the document only describes per-connection level authorization for subscriptions.

After some research, I found that it seems like currently there's no way to authorize subscription at the resolver level unless you use somewhat tricky ways to tweak the current implementation, As mentioned in #1248. And obviously it is bad way to achieve a very essential, commonly usable feature like this.

Authorizing subscriptions is very important and still basic feature to build production-level projects, As you don't want to create as many servers as the number of authorizing context you have for your subscriptions.

Is there any plan to provide this feature or is it already implemented but not documented yet?

**Comment by KeithGillette** [comment]
Agreed that this is an important unresolved issue. I've opened [a Discussion Idea thread](https://github.com/apollographql/apollo-server/discussions/4690) with a proposal for aligning the Subscription resolver API with that for Queries and Mutations to provide a mechanism for both validation and authorization of Subscriptions (authentication _is_ currently supported) and referenced the issue in the [the Apollo Server 3.0 roadmap post](https://github.com/apollographql/apollo-server/issues/2360#issuecomment-733847216).

**Comment by ScripterSugar** [comment]
For those who need per-resolver subscription authorization, I wrote a simple library to do this.

[Check out my implementation at graphql-authorize-subscription](https://github.com/ScripterSugar/graphql-authorize-subscription)

It's less than a kilobyte, you can give it a try. Please feel free to provide any feedbacks.
