### ISSUE TITLE
v2.18 regression in behavior of `APOLLO_SCHEMA_REPORTING=true` + `engine: {reportSchema: false}`

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#4778]
Before the big refactor in v2.18, setting `engine: {reportSchema: false}` would override the env var `APOLLO_SCHEMA_REPORTING=true`.

In v2.18 the `engine` parameter is just for backwards compatibility. By accident, this combination now leads to schema reporting; there is no way in code to override `APOLLO_SCHEMA_REPORTING=true`.

(Note: both of these statements are based on code observation, not running code.)

Two things that perhaps can be done here:
- Introduce a `ApolloServerPluginSchemaReportingDisabled`, like the other `*Disabled` plugins, that overrides the env var.
- Change the legacy `engine` option handling so that `false` overrides the env var.

Workaround: Don't set `APOLLO_SCHEMA_REPORTING` in environments where you don't want schema reporting; either only set it in appropriate contexts or only enable schema reporting via `plugins: [ApolloServerPluginSchemaReporting()]`.

**Comment by trevor-scheer** [comment]
The schema reporting plugin is now _only_ installed either explicitly or via setting `APOLLO_SCHEMA_REPORTING=true`

**Comment by glasser** [comment]
Actually I don't think this is fixed -- you still can't write code (say, tests) that ensures schema reporting is disabled even in the presence of the env var. (Typically env vars should be lower priority than actual code.) Adding a Disabled plugin should be pretty easy.
