### ISSUE TITLE
Cross origin access to a Next.js API route running apollo-server-micro

### ISSUE THREAD

**Issue by sakhmedbayev** [apollographql/apollo-server#4779]
I am having a hard time to make CORS work with next.js API routes and "apollo-server-micro".

I put together this sample repo to reproduce the issue:

https://github.com/sakhmedbayev/nextjs-graphql-example

My goal is to make the graphql API route - "apollo-server-micro" (http://localhost:3000/api/graphql) to be accessible from all origins, e.g., http://localhost:3000, http://subdomain.localhost:3000, or http://localhost:5000

I would greatly appreciate any help!

**Comment by wuichen** [comment]
im having issue implementing this as well

**Comment by arist0tl3** [comment]
Hey, combined some ideas from the repo @sakhmedbayev posted as well as https://github.com/apollographql/apollo-server/issues/2473 and came up with:

```
import { ApolloServer, gql } from 'apollo-server-micro';
import Cors from 'micro-cors';

const cors = Cors();

// This data will be returned by our test endpoint
const products = [
  {
    _id: 1,
    name: 'Cookie',
    price: 300,
  },
  {
    _id: 2,
    name: 'Brownie',
    price: 350,
  },
];

// Construct a schema using GraphQL schema language
const typeDefs = gql`
  type Product {
    _id: ID
    name: String
    price: Int
  }

  type Query {
    products: [Product]
  }
`;

// Provide resolver functions for your schema fields
const resolvers = {
  Query: {
    products: () => products,
  },
};

const server = new ApolloServer({ typeDefs, resolvers });

export default cors((req, res) => {
  if (req.method === 'OPTIONS') {
    res.end();
    return false;
  }

  return server.createHandler({
    path: '/api/graphql',
  })(req, res);
});

export const config = {
  api: {
    bodyParser: false,
  },
};
```

Let me know if this works for you

**Comment by abernix** [comment]
If [the CORS example in the `README.md` for the `apollo-server-micro` package](https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-micro/README.md#cors-example) doesn't work ([which is published to npm](https://npm.im/apollo-server-micro)), please open a PR that adjusts it!

**Comment by wuichen** [comment]
i can confirm the example works. thanks

**Comment by SinsamutQ** [comment]
If you encounter problems 
```[Error: You must `await server.start()` before calling `server.createHandler()` in next.js]```

This thread can help you 
https://stackoverflow.com/questions/69034677/error-you-must-await-server-start-before-calling-server-createhandler-i

Credit [brielov](https://stackoverflow.com/users/2491452/brielov) and thank you very much for your code
```ts
import Cors from "micro-cors";
import schema from "graphql/schema";
import { ApolloServer } from "apollo-server-micro";
import { PageConfig } from "next";
import { createContext } from "graphql/context";

export const config: PageConfig = {
  api: {
    bodyParser: false,
  },
};

const cors = Cors();

const server = new ApolloServer({
  context: createContext,
  schema,
});

const startServer = server.start();

export default cors(async (req, res) => {
  if (req.method === "OPTIONS") {
    res.end();
    return false;
  }

  await startServer;
  await server.createHandler({ path: "/api/graphql" })(req, res);
});
```

**Comment by glasser** [comment]
@SinsamutQ I'd encourage you to upgrade to AS4 and use https://www.npmjs.com/package/@as-integrations/next instead!
