### ISSUE TITLE
subscription not working

### ISSUE THREAD

**Issue by Eriickson** [apollographql/apollo-server#4782]
Greetings I am using the subscriptions, I had never used them, that's why I started to do a test and the results were quite nice (In the test), so I decided to implement this functionality in my application, but this is where the error comes from, since When I call pubsub, with its triggerName it does not run, I will show you the test subscription and the production subscription in case it is necessary for you, reiterating that the test one works perfectly for me, while the production one does not

Step 1: create the subscription in the schema
production:
![image](https://user-images.githubusercontent.com/38663299/101916957-03d38f00-3b9e-11eb-9890-4bd3dc037c69.png)

testing:
![image](https://user-images.githubusercontent.com/38663299/101917316-780e3280-3b9e-11eb-80ac-27fa557f0007.png)

step 2: we create the subscription in the resolver
production:
![image](https://user-images.githubusercontent.com/38663299/101918082-53668a80-3b9f-11eb-8495-99e952cbe999.png)

testing:
![image](https://user-images.githubusercontent.com/38663299/101918035-4184e780-3b9f-11eb-931a-d3da0d27beba.png)

step 3: I call subscription, to alert when a product or publication has been created
production:
![image](https://user-images.githubusercontent.com/38663299/101918376-ad675000-3b9f-11eb-9168-3c9fd80bad01.png)

testing:
![image](https://user-images.githubusercontent.com/38663299/101918455-c4a63d80-3b9f-11eb-9d34-f99d6588ceb3.png)

this would be the imports and the part of creating the triggerName
production
![image](https://user-images.githubusercontent.com/38663299/101918755-1a7ae580-3ba0-11eb-80aa-a12c175722a3.png)

testing:
![image](https://user-images.githubusercontent.com/38663299/101918673-033bf800-3ba0-11eb-99df-18ef137dc259.png)

I detailed the problem as much as I can, to see if they can help me with this, the detail is that I have this, and it is assumed that in the middle of the before and after the variables that are in the production image of step 2 should be printed

![image](https://user-images.githubusercontent.com/38663299/101919041-82313080-3ba0-11eb-96ab-95f1f30179a9.png)

but i only come across these messages on console:
![image](https://user-images.githubusercontent.com/38663299/101919477-fe2b7880-3ba0-11eb-993a-4b4e4099d35b.png)

thanks in advance and I hope you can help me

**Comment by trevor-scheer** [comment]
@Eriickson sorry we never responded to this, hopefully you got to the bottom of the issue.

Apollo Server no longer supports subscriptions natively (though you can still use them https://www.apollographql.com/docs/apollo-server/data/subscriptions). If you're still having issues using subscriptions, please reference your subscription library's docs and file an issue there.
