### ISSUE TITLE
Default field resolver

### ISSUE THREAD

**Issue by jskorepa** [apollographql/apollo-server#479]
https://github.com/graphql/graphql-js/pull/865 added ability to specify default field resolver. Is there any way to use it with apollo-server?

**Comment by freiksenet** [comment]
I started working on this, this needs some updates to DefinetelyTyped GraphQL Typescript definitions, I'll make them and then the PR can be merged. https://github.com/apollographql/apollo-server/pull/482

**Comment by freiksenet** [comment]
Waiting on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18346

**Comment by martijnwalraven** [comment]
This has just been published in Apollo Server 1.1.0.
