### ISSUE TITLE
makeExecutableSchema Existing Schema directiveResolvers Context Headers

### ISSUE THREAD

**Issue by someyoungideas** [apollographql/apollo-server#4794]
*Package: v2.18.2 apollo-server*

Expected Behavior:
Currently using Apollo Server 1 (old pattern) with `makeExecutableSchema` for the schema. The docs state this pattern may be migrated away from, but is backwards compatible. We are using `directiveResolvers` and expecting the `context` parameter for each directive resolver to contain headers.

Actual Behavior:
Our directive resolvers are not able to access the headers property on the `context` object parameter, and instead it is only accessible as a Symbol with the name of `kHeaders`. This is how we had to implement a hotfix for our current implementation for direct resolvers.

Let me know if I can provide any more information.

**Comment by trevor-scheer** [comment]
@someyoungideas sorry we never responded to this. If this issue persists in more current versions and you can provide us a reproduction for us to debug, I'll gladly reopen this issue.

**Comment by glasser** [comment]
Additionally, makeExecutableSchema is now part of the separate `graphql-tools` project, not Apollo server itself.
