### ISSUE TITLE
When I upload file the file size 0kby

### ISSUE THREAD

**Issue by ahmedelamine** [apollographql/apollo-server#4801]

**Comment by ahmedelamine** [comment]
I need a full script for the backend for upload file with apollo-server

**Comment by jaydenseric** [comment]
This is a usage question, not a bug.

What is happening is your resolver is returning before the file has uploaded, causing the server to respond before the client has finished uploading. You need to promisify and await the file upload stream events in the resolver or the uploaded file's size will be 0 KB.

See: https://stackoverflow.com/a/65974865/1596978

> I need a full script for the backend for upload file with apollo-server

You can see a full stack example of Apollo and file uploads here:

https://github.com/jaydenseric/apollo-upload-examples

**Comment by glasser** [comment]
Thanks for answering, @jaydenseric!
