### ISSUE TITLE
Exceptions produced during the execution of graphqlOptions function are not logged

### ISSUE THREAD

**Issue by schwer** [apollographql/apollo-server#483]
I have the following code initializing the graphiql capability:

```
  const graphqlOptions = (req) => {
    return {
      context: {
        user: req.user,
        dataLoaders: dataLoaderBuildingFunc(),
      },
      schema: graphqlSchema,
   };
  };
  server.post('/graphql', graphqlRestify(graphqlOptions));
  server.get('/graphiql', graphiqlRestify({ endpointURL: '/graphql' }));

```

I observed that when visiting the graphiql page, and when the `dataLoaderBuildingFunc` produces an exception, the exception and error message are swallowed and a rather inspecific error message is produced: `Invalid options provided to ApolloServer: ...`.

Providing a logging function to the `makeExecutableSchema` function did not solve the problem.

In order to track down the exception, I now execute a mocked version of the `dataLoaderBuildingFunc` at startup. This is not ideal.

**Comment by hwillson** [comment]
We no longer use `graphqlOptions` with Apollo Server 2. Closing - thanks!
