### ISSUE TITLE
Disable UsageReporting with ENV in LOCAL

### ISSUE THREAD

**Issue by legopin** [apollographql/apollo-server#4831]
## Environment
apollo-server@2.19.1
apollo-server-core@2.19.1

## Expected Behavior
There should be a way for a project to specify usage reporting settings in server init yet disable reporting in LOCAL dev environments with the use of ENV variables. 

## Actual Behavior
When Apollo server is initialized with `ApolloServerPluginUsageReporting`, the following error occurs
```
Error: You've enabled usage reporting via ApolloServerPluginUsageReporting, but you also need to provide your Apollo API key, via the APOLLO_KEY environment variable or via `new ApolloServer({apollo: {key})
    at Object.serverWillStart (/sandbox/node_modules/apollo-server-core/dist/plugin/usageReporting/plugin.js:62:23)
    at Promise.all.plugins.map (/sandbox/node_modules/apollo-server-core/dist/ApolloServer.js:315:118)
    at Array.map (<anonymous>)
    at ApolloServer.<anonymous> (/sandbox/node_modules/apollo-server-core/dist/ApolloServer.js:315:69)
    at Generator.next (<anonymous>)
    at fulfilled (/sandbox/node_modules/apollo-server-core/dist/ApolloServer.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

## A **simple**, runnable reproduction!
https://codesandbox.io/s/apollo-server-plugin-cant-disable-0rld2?file=/sandbox.config.json

## Current Workaround
My current work around is to detect whether APOLLO_KEY is defined and add the plugin dynamically, but it feels backwards

```js
const apolloServer = new ApolloServer({
  typeDefs: typeDefs,
  resolvers: extendResolvers,
  context: ({ ctx }) => ctx.contextValue,
  introspection: config.apolloServer.allowIntrospection,
  plugins: process.env.APOLLO_KEY
    ? [
        ApolloServerPluginUsageReporting({
          sendHeaders: { all: true },
        }),
        ApolloServerPluginSchemaReporting(),
      ]
    : undefined,
});
```

**Comment by KhalitovAdel** [comment]
I have same issue, I think join of official documentation of https://www.apollographql.com/docs/apollo-server/migration-engine-plugins/

Because if you see of implementation of that library you can see:

```

import {
  GraphQLOptions,
  FileUploadOptions,
  ApolloServerBase,
  formatApolloErrors,
  processFileUploads,
  ContextFunction,
  Context,
  Config,
} from 'apollo-server-core';

...

export class ApolloServer extends ApolloServerBase {
```

**Comment by glasser** [comment]
To disable usage reporting, you can install the ApolloServerPluginUsageReportingDisabled plugin.

We try to keep the rules about when plugins are installed automatically as simple as possible.  "If you provide an API key and graph ref, we report usage" is the rule. If you want to override that, use ApolloServerPluginUsageReportingDisabled. Full details at https://www.apollographql.com/docs/apollo-server/v3/api/plugin/usage-reporting/
