### ISSUE TITLE
Extra nesting of errors when context function throws an error

### ISSUE THREAD

**Issue by saihaj** [apollographql/apollo-server#4858]
This was reported in  https://github.com/graphql/graphql-js/issues/2885 by @HarishTeens.

As per spec GraphQL errors follow this format 
[<img src="https://user-images.githubusercontent.com/44710980/105529018-5dee6680-5cab-11eb-92a5-deb6c06bee83.png" width="450" />](http://spec.graphql.org/draft/#example-90475)

### Issue
In Apollo server if error is thrown by a context it wraps it with `error` like this:
[<img src="https://user-images.githubusercontent.com/44710980/105274485-edd4c900-5b62-11eb-98a1-581bb7bb0b79.png" width=450 />](https://github.com/graphql/graphql-js/issues/2885#issuecomment-764202010) 

### Version information
```json
  "dependencies": {
    "apollo-server": "^2.19.2",
    "graphql": "^15.4.0"
  }
```

### Additional Information
I tired a similar thing using [`express-graphql`](https://github.com/graphql/express-graphql) and don't have that issue.
[<img src="https://user-images.githubusercontent.com/44710980/105525054-27fab380-5ca6-11eb-9e35-1161f0b63129.png" width=450 />](https://github.com/graphql/graphql-js/issues/2885#issuecomment-765575682)

**Comment by trevor-scheer** [comment]
I suspect this isn't still happening in current versions of Apollo Server, but I'm happy to reopen this issue if that's not the case. If it is still happening, a reproduction would be a great start.
