### ISSUE TITLE
I got error from graphiql when I use variable parameter 

### ISSUE THREAD

**Issue by lagmanzaza** [apollographql/apollo-server#486]
![777](https://user-images.githubusercontent.com/5283709/28611416-eefe0e8e-7215-11e7-831a-46342fe2fc08.PNG)

**Comment by abernix** [comment]
If you’re still experiencing this problem on newer versions of Apollo Server 2.x, please open a new issue with a full reproduction.  That said, I’m fairly confident this is working properly now with `graphql-playground` since I’ve used it very recently.

Thanks for opening this originally!
