### ISSUE TITLE
Add Module and CommonJS support

### ISSUE THREAD

**Issue by yanickrochon** [apollographql/apollo-server#4860]
Upgrading a project to Node.js v14, I got into a problem where this module would not import without going through some workaround, which breaks during tests (i.e. it either works fine as-is in tests using Babel, or it breaks using Node 14+, but the workaround is the other way around)

In order to support both Babel and Node v14+ modules, the `package.json` should be modified with conditional exports :

```
   "main": "./src/index.js",
   "type": "module",
   "exports": {
      ".": [
         {
            "import": "./src/index.js",
            "require": "./cjs/index.cjs",
            "default": "./src/index.js"
         },
         "./src/index.js"
      ]
   }
```

**Comment by trevor-scheer** [comment]
Apollo Server now ships with both CJS and ESM in v4!
