### ISSUE TITLE
where did subscriptions onOperation/onOperationComplete go?

### ISSUE THREAD

**Issue by RichardWright** [apollographql/apollo-server#4864]
onOperation and onOperationComplete events are listed here - https://www.apollographql.com/docs/graphql-subscriptions/lifecycle-events/

However when I look at the source code I can see this - 

https://github.com/apollographql/apollo-server/blob/b7a91df76acef748488eedcfe998917173cff142/packages/apollo-server-core/src/ApolloServer.ts#L640

There is no way of passing in either of these functions. Is there a reason for this? We were hoping to count subscriptions starting/ending.

**Comment by trevor-scheer** [comment]
Subscriptions is no longer supported natively by Apollo Server, though they can be integrated:
https://www.apollographql.com/docs/apollo-server/data/subscriptions

Any issues you have with the subscriptions API would now be on the shoulders of the library you use (presumably the non-deprecated `graphql-ws` package).
