### ISSUE TITLE
Some Apollo Server dependencies have peerDeps incompatible with graphql@15, and the latest npm really cares

### ISSUE THREAD

**Issue by DakotaLarson** [apollographql/apollo-server#4865]
Hi,

I am running into an error when installing apollo-server-core as a dependency of apollo-server-express. 

The most recent version of apollo-server-core includes graphql-upload v8.x as a dependency, however, v8 of graphql-upload requires a peer dependency of graphql v14 or earlier. I have v15.x of graphql installed. 

The latest version of graphql-upload has support for graphql v15 as a peer dependency. 

Essentially, I am wondering if it's possible to update the graphql-upload dependency of apollo-server-core to use the most recent version. I am not running into any runtime errors at the moment.

Thanks!

**Comment by theodorDiaconu** [comment]
Latest version of graphql-upload is 11 (updated 8 months ago), we need to all be in this one so graphql@15 is supported across all ecosystem. Same problem here: https://github.com/apollographql/graphql-subscriptions/issues/242

**Comment by glen-84** [comment]
PR #4039.

**Comment by glasser** [comment]
Thanks for the report. I'm ramping up on Apollo Server maintenance and am learning rapidly that [this week's release of npm@7](https://github.blog/2021-02-02-npm-7-is-now-generally-available/) makes peer dependency issues really important.  I'm going to close a few other issues as dupes of this one and get to this first thing next week.

**Comment by glasser** [comment]
My current plan, which I hope to work on tomorrow, is to fork `graphql-upload` v8 to `@apollographql/graphql-upload-deprecated-fork` and add the peer dep there, and change apollo-server to depend on this fork. I will probably also officially deprecate our `graphql-upload` implementation in that release and improve the documentation of how to just use `graphql-upload`directly.

**Comment by glasser** [comment]
I've done the above plan (swap out graphql-upload for a fork with a wider peer dep). It's currently in the release-2.21.0 branch, being tracked at https://github.com/apollographql/apollo-server/pull/4922

I'll close this issue now, though it doesn't help you until the release goes out (probably today or tomorrow).

I'd love some folks to try the alpha and let me know if it works for you! Both folks who actually use the upload feature and those who don't!
