### ISSUE TITLE
Enable RedisCache to have ioredis client injected

### ISSUE THREAD

**Issue by RichardWright** [apollographql/apollo-server#4870]
Current code from RedisCache

`export class RedisCache implements TestableKeyValueCache<string> {
  readonly client: any;
  readonly defaultSetOptions: KeyValueCacheSetOptions = {
    ttl: 300,
  };

  private loader: DataLoader<string, string | null>;

  constructor(options?: RedisOptions) {
    const client = new Redis(options);
    this.client = client;

    this.loader = new DataLoader(keys => client.mget(...keys), {
      cache: false,
    });
  }
`

Could we inject the ioredis and new it up if it's not there?

**Comment by RichardWright** [comment]
I opened up a pr to fix this.

**Comment by glasser** [comment]
I've released a prerelease with this fix (`apollo-server-cache-redis@1.4.0-alpha.0`, part of the Apollo Server 2.23.0 release). Try out the alpha and see if it works for you! Please provide any feedback in #5094.

**Comment by glasser** [comment]
This has been released in `apollo-server-cache-redis@1.4.0`.
