### ISSUE TITLE
Only call context creation function following GraphQL validation

### ISSUE THREAD

**Issue by andyrichardson** [apollographql/apollo-server#4872]
## About

Currently, the context creation function is called regardless of whether the incoming request will ever get to a resolver.

If an incoming query can't be parsed, there's no point creating context as execute will never be called.

## Example

Consider the following query coming through to apollo-server

```gql
this is not valid query syntax
```

### Expected result

A GraphQL validation error is thrown before context creation is triggered

### Actual result

Context creation function is called and then a GraphQL validation error is thrown

## Suggestion

It would make sense to validate the incoming query before calling the context creator.

This would help with use cases where the query is required at context-creation time (#4531)

## Example (inside apollo-server)

``` 
// ...
const errs = validate(schema, document); // <- Check prior to context creation

if (errs.length) {
  throw new ValidationError(/* */);
}

const context = typeof args.context === function ? args.context(/* */) : args.context;
const response = execute(schema, document, root, context, variables, operationName)

// ...
```

**Comment by glasser** [comment]
The current call ordering is pretty baked into the structure of Apollo Server's request pipeline. An advantage to this ordering is that you can throw an error in `context` before even getting to GraphQL parsing and validation if something looks problematic. In addition, if you're using the HTTP batching feature, the context is shared across all operations in an HTTP request (this is basically the only good thing about the batching feature) so this inversion wouldn't make sense in that context. Finally, several plugin hooks are called before validation which receive the context; inverting the order would mean they wouldn't have that access. I don't think we're likely to change this ordering.
