### ISSUE TITLE
[cache-control]: when set to 0, still calls Redis?

### ISSUE THREAD

**Issue by maapteh** [apollographql/apollo-server#4873]
Im trying to understand the following. In our schema we set the following:
```
type Member @cacheControl(maxAge: 0, scope: PRIVATE)
```
Just to make sure we do not want anyone to set it into caching. We start our server with Redis configuration. But then when checking the purePath for that execution we see the following:

<img width="800" alt="Screenshot 2021-01-27 at 14 07 34" src="https://user-images.githubusercontent.com/25961356/105995722-ab067a00-60a9-11eb-92ca-1648121711bb.png">

Im not sure about mget twice maybe/hopefully thats Sentinel or wrong with our dynatrace. But is it correct that even when having maxAge at 0 the server will always go to Redis first, in which it cant find anything? Is this expected behaviour? Should we not set any cacheControl at all?

**Comment by maapteh** [comment]
Shit, the notice about two times mget is actually true :(
I added also new bug in #4876

**Comment by trevor-scheer** [comment]
I'm going to leave this open since it actually seems like an issue with how cache control works. If you can provide a reproduction in the meantime that would be very helpful.

**Comment by glasser** [comment]
I explained this here: https://github.com/apollographql/apollo-server/issues/4877#issuecomment-1286432962
