### ISSUE TITLE
Performance Impact of deprecated `graphql-extensions`

### ISSUE THREAD

**Issue by DrewML** [apollographql/apollo-server#4889]
Profiling our Apollo Server setup, it looks like the [deprecated](https://github.com/apollographql/apollo-server/pull/4135) `graphql-extensions` package is eating up a significant amount of time. Specifically, the `whenResultIsFinished` hook seems to be dominating.

I'm not seeing any [warnings about deprecated extension usage](https://github.com/apollographql/apollo-server/blob/902e2c457358a00dc3727d367f1bdaa0e38794b8/packages/apollo-server-core/src/requestPipeline.ts#L692-L703) during startup, so I was surprised to see the runtime cost of (`graphql-extensions`) is substantial.

![image](https://user-images.githubusercontent.com/5233399/106533876-8569de00-64b8-11eb-907e-eb7cfe866563.png)

Running tests locally, it seems like I can eliminate this cost entirely by adding a `_extensionsEnabled` property to my schema _before_ being passed to the `ApolloServer` constructor, and that seems to bypass all the extension hooks.

If we're using Apollo Studio to capture and view metrics, are there any metrics we'll be missing by disabling extension support? As far as I can tell, all this functionality was migrated to the newer Plugin API a few months ago.

**Comment by glasser** [comment]
Are you saying that you actually see a notable performance improvement when you disable the graphql-extensions schema instrumentation with `schema._extensionsEnabled`?

The newer plugin schema instrumentation code is pretty similar to the older extensions schema instrumentation code, so I'd be a little surprised if the impact of having both of them on is significantly worse than just having the newer instrumentation code on. Is the other whenResultIsFinished from apollo-server-core (that's the plugin one) and does it use a similar amount of time?

I'm not sure exactly how to interpret the screenshot. `whenResultIsFinished` itself does very little (calls promise.then, Promise.all, etc, or invokes its callback).  Does this only show the time literally spent inside this function, or does it include time waiting on promises created in the function? (I assume the former.)

Now that all the first-party extensions have been rewritten as plugins and we've added deprecation warnings for the use of extensions, I think we could avoid calling `enableGraphQLExtensions` unless there are actually extensions provided. I would review a PR that makes that change.  That said, if there's really a serious performance issue in your benchmarks from just the no-op extension instrumentation, you'll still presumably have half of that from the plugins instrumentation...

**Comment by DrewML** [comment]
Hey @glasser, thanks for the reply.

> I'm not sure exactly how to interpret the screenshot. whenResultIsFinished itself does very little (calls promise.then, Promise.all, etc, or invokes its callback). Does this only show the time literally spent inside this function, or does it include time waiting on promises created in the function? (I assume the former.)

Apologies, I should have clarified a bit more. The `Self Time` for `whenResultIsFinished` above is the aggregate time that has been spent on that function in this particular stack (just time spent in the body of this function, not its children). In this screenshot, that stack is a single run of resolvers (one at the top, mostly default resolvers below). When resolving all fields in this request, the `whenResultIsFinished` from `graphql-extensions` added 31ms of compute time.

In my tests, the `whenResultIsFinished` from `graphql-extensions` takes between 1.3-1.5ms each time it's invoked. Because every field in the schema invokes this function via the wrapped `field.resolve`, the cost of this no-op grows with the number of fields requested.

![image](https://user-images.githubusercontent.com/5233399/106771146-49439400-6604-11eb-8ba3-ba981a76f264.png)

> The newer plugin schema instrumentation code is pretty similar to the older extensions schema instrumentation code, so I'd be a little surprised if the impact of having both of them on is significantly worse than just having the newer instrumentation code on.

They both add _some_ overhead. So doing that work 2x is always going to be more expensive than just once.

**Comment by glasser** [comment]
OK. So the complaint is less "the cost of instrumentation is so terrible that it makes getting value out of instrumentation not worth it for your app", and more "the cost of instrumentation is bad enough that we really should only do it once rather than twice"? That makes sense. Can you send a PR to make the enableGraphQLExtensions call conditional?

**Comment by DrewML** [comment]
Hopefully my input came off more as friendly feedback than a complaint 😄 Apologies if it seemed otherwise!

But yeah, it definitely more of a request to do that kind of work once 👍 

PR in https://github.com/apollographql/apollo-server/pull/4893

**Comment by glasser** [comment]
Sorry, I meant to say "concern"! This was a helpful issue.

**Comment by DrewML** [comment]
Thanks for the quick help @glasser!

**Comment by glasser** [comment]
Released in v2.20.0.
