### ISSUE TITLE
Why does auto-fill/complete fill in nullable fields?

### ISSUE THREAD

**Issue by ffxsam** [apollographql/apollo-server#489]
Given the following schema:

```graphql
  type Thing {
    name: String!
    size: Int
    dummy1: Boolean!
    dummy2: Boolean
  }

  type Query {
    things: [Thing]
  }
```

I type the following in GraphiQL:

```graphql
{
  things
}
```

And when I run the query, `things` expands:

```graphql
{
  things {
    size
    dummy2
  }
}
```

This strikes me as a bit odd. Why would the nullable fields populate, instead of the non-nullable ones?

**Comment by stubailo** [comment]
This sounds like an issue with GraphiQL - maybe better to file it there! https://github.com/graphql/graphiql
