### ISSUE TITLE
visitFieldDirective in schemaDirectiveVisitor class is unable to write field.extensions

### ISSUE THREAD

**Issue by harshil4076** [apollographql/apollo-server#4894]
Unable to add extra Metadata to field.extensions - HELP
I followed the steps in https://blog.grandstack.io/authorization-in-graphql-using-custom-schema-directives-eafa6f5b4658 to add a custom directive called `@extensionsDir` to add extensions on fields.
This is what my server file looks like.
```
class ExtensionDirective extends SchemaDirectiveVisitor {
  visitFieldDefinition(field) {
    field.extensions = "Demo"
    console.log(field)
  }
}
const schema = makeAugmentedSchema({
  typeDefs,
  schemaDirectives: {
    extensionsDir: ExtensionDirective,
  },
})
```
directive declaration is `directive @extensionsDir on FIELD_DEFINITION`
usgae :
```
type Sample {
sampleField: Boolean! @extensionsDir
}
```
The console log shows that its successfully added to .extensions but when I fetch introspection results in the client, the client schema does not indicate changes made to the field on that type. However the directives list does show an object named extensionsDir.
I am able to replace field.description with a custom value but not the field.extensions.

Am I missing something here? 

It might be the case that apollo-server is using graphql-tools version 4(based on the docs) and the extensions property was added in later version of graphql-toos. In that case i can not see any work arounds. I am open to other suggestions as well.

**Comment by glasser** [comment]
https://github.com/apollographql/apollo-server/issues/4810#issuecomment-773524379

**Comment by glasser** [comment]
Hi. It looks like the function you're calling above (makeAugmentedSchema) is from `neo4j-graphql-js`. I'm not sure if what you're running is from `apollo-server` at all. I can look more into this if you can show a complete reproduction (eg, something on codesandbox.io or a git repo I can clone) that uses Apollo Server directly and ideally does not use `neo4j-graphql-js`.

That said, as you've alluded to Apollo Server just gets these functions from an old version of graphql-tools. If the old version is buggy or lacks new features, the best approach is to use `graphql-tools` directly yourself. See https://github.com/apollographql/apollo-server/issues/4810#issuecomment-791788071 for more details.

**Comment by harshil4076** [comment]
Thank you so much for looking into this. And yes we have to use `neo4j-graphql-js` in our app since our resolvers are generated by `makeAugmentedSchema`, but we are running it from `apollo-server`. The server is identical from this https://github.com/grand-stack/grand-stack-starter repo.(src/api) 
The `neo4j-graphql-js` package uses a newer version of `graphql-tools` shown here https://github.com/neo4j-graphql/neo4j-graphql-js/blob/master/package.json#L78 so I think your solution from the https://github.com/apollographql/apollo-server/issues/4810#issuecomment-791788071 comment should work. I will give it a try. Thanks again..
