### ISSUE TITLE
Documentation Improvement: schema property

### ISSUE THREAD

**Issue by pedroBruno7** [apollographql/apollo-server#4895]
Hi,

I wasted some time figuring out how do add resolvers when using the schema property instead of typeDefs and resolvers

I think would help beginners if you add a line saying "if schema is used, the resolvers are added this way:

const { makeExecutableSchema } = require('@graphql-tools/schema')

const schema = makeExecutableSchema({ typeDefs, resolvers })

"

Thank you : )

**Comment by glasser** [comment]
Thanks for the feedback! Is there a particular section of the docs where you think this would be helpful? The docs can be found in this repository in the `docs` directory and we appreciate pull requests. That said, there's definitely a distinction in our docs between "tutorial"/"guide" sections where we try to show the most common/recommended use cases and "reference" sections where we try to exhaustively document all ways to use the APIs (though some aspects are only documented in one of the two kinds of sections).

**Comment by trevor-scheer** [comment]
Looks like we've since improved the docs on this:
https://www.apollographql.com/docs/apollo-server/api/apollo-server/#schema
