### ISSUE TITLE
Variable \"$file\" of type \"Upload!\" used in position expecting type \"Upload!\

### ISSUE THREAD

**Issue by hipgnosis** [apollographql/apollo-server#4896]
I'm working on implenting uploading using apollo-server-express 2.19.2

However, each time I try to run a mutation and upload a file I receive :

`{"errors":[{"message":"Variable \"$file\" of type \"Upload!\" used in position expecting type \"Upload!\".","locations":[{"line":1,"column":43},{"line":2,"column":45}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Variable \"$file\" of type \"Upload!\" used in position expecting type \"Upload!\".","    at Object.leave (d:\\apiserver\\node_modules\\graphql\\validation\\rules\\VariablesInAllowedPositionRule.js:55:35)","    at Object.leave (d:\\apiserver\\node_modules\\graphql\\language\\visitor.js:344:29)","    at Object.leave (d:\\apiserver\\node_modules\\graphql\\utilities\\TypeInfo.js:390:21)","    at visit (d:\\apiserver\\node_modules\\graphql\\language\\visitor.js:243:26)","    at Object.validate (d:\\apiserver\\node_modules\\graphql\\validation\\validate.js:69:24)","    at validate (d:\\apiserver\\node_modules\\apollo-server-express\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:221:34)","    at Object.<anonymous> (d:\\apiserver\\node_modules\\apollo-server-express\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:118:42)","    at Generator.next (<anonymous>)","    at fulfilled (d:\\apiserver\\node_modules\\apollo-server-express\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:5:58)"]}}}]}
`
Looking at the validation logic, it appears to be doing an === comparison between two input types that appear identical in the debugger, but I'm guessing have different memory addresses.

Any suggestions as to how to prevent this or work around it would be appreciated!

The pertinent schema parts are :

`scalar FileUpload
updateProfileImage(userId: String!, file: FileUpload!): String`

with the resolver specifying the FileUpload scalar with :

`import {GraphQLUpload} from 'apollo-server-express';

interface Resolvers {
  JSON: GraphQLScalarType,
  FileUpload: typeof GraphQLUpload,
  Query: QueryResolvers,
  Mutation: MutationResolvers,
}

export const resolvers: Resolvers = {
  FileUpload: GraphQLUpload,
 ...}`

**Comment by glasser** [comment]
I'm not an expert on apollo-server's `graphql-upload` integration, but I don't think this is how we document that you're supposed to use it?  [The docs](https://www.apollographql.com/docs/apollo-server/data/file-uploads/) expect you to use a scalar called `Upload`, not `FileUpload`, and apollo-server takes care of adding the correct resolvers for you. The error message you've included also doesn't have the word FileUpload even though that's what your example includes. I don't think this report has enough detail for further investigation. I'll happily reopen this if you can include a full reproduction recipe (ie, a set of steps, probably starting with `git clone`, that shows your error).

**Comment by hipgnosis** [comment]
If someone else stumbles across this, and the problems with getting Upload recognized in the schema read through this :

[https://stackoverflow.com/questions/56423772/unknown-type-upload-in-apollo-server-2-6](url)

Ended up having to change my constructor from

`const apolloServer = new ApolloServer({ introspection: true, typeDefs: schema, resolvers: resolvers as any,`

to

`const apolloServer = new ApolloServer({ introspection: true, schema: makeExecutableSchema({typeDefs: schema, resolvers: resolvers as any}),`

to get things to work (went through the struggles of scalar Upload causing failure both if present and if not present as explained in the SO article.

**Comment by PatrickChow** [comment]
Remove graphql-upload module from package.json,
Delete upload resolver code.
