### ISSUE TITLE
using aliases in fragments using delegate to schema breacks resolution

### ISSUE THREAD

**Issue by Luscha** [apollographql/apollo-server#4912]
Having a delegateToSchema apollo gateway, if a query uses an alias inside a fragment the resolution breaks and thows error if the aliased field is not nullable.

Schema:
```gql
type Query {
    getVisualNovel(id: String!): VisualNovel
  }
  interface Metadata {
    id: String!
  }

  type VisualNovel implements Metadata {
    id: String!
  }
```

Query
```gql
result: getVisualNovel(id: "tFHEKeWbZcw5") {
    ... on VisualNovel {
      i: id
    }
  }
```

- ["apollo-server": "2.9.7" ] The package name and version of Apollo showing the problem.
- 
- The expected behavior.
The query returns
```
{
  "data": {
    "result": {
      "i": "tFHEKeWbZcw5"
    }
  }
}
```

- The actual behavior.
```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field VisualNovel.id.",
      "path": [
        "result",
        "i"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
}
  "data": {
    "result": null
  }
}
```

- [x] A **simple**, runnable reproduction!
the code can be found at https://codesandbox.io/s/friendly-worker-c5s7c .
The sandbox do not work but copying index.js and package.json and running `npm i && npm run start` will start an instance on localhost:4000 already connected to a live database where you can run the query

**Comment by glasser** [comment]
It seems like this is primarily a concern about `@graphql-tools/delegate`? That sounds like something that should be reported in the [graphql-tools repo](https://github.com/ardatan/graphql-tools), which is actively maintained by the graphql-tools community.

Additionally, v2.9.7 was released in October 2019; we're almost up to v2.20 now, so if this is an Apollo Server problem I'd recommend that you start by upgrading!
