### ISSUE TITLE
Acephei example is broken.

### ISSUE THREAD

**Issue by michaelmerrill** [apollographql/apollo-server#4915]
The Acephei example fails to build due to type errors. 

Also, playground is still unable to connect to locally running services. There is already a ticket for this [here](https://github.com/apollographql/apollo-server/issues/4515). However, upon further investigation, it seems that the issue is caused by more than just the `StrictOperationsPlugin`.

To reproduce, clone this repo and follow the steps in the Acephei README. This is occurring on the current version and (afaik) node 12.

**Comment by glasser** [comment]
Thanks. This example is a bit out of date and doesn't really need to be here. We may put it somewhere else later, but the build issues seem really connected to it being nested under another node_modules and might as well remove it from here for now.

**Comment by michaelmerrill** [comment]
Sounds good. Thanks @glasser
