### ISSUE TITLE
Subscriptions not working behind Apache Reverse Proxy - 400 Bad Request

### ISSUE THREAD

**Issue by Tarow** [apollographql/apollo-server#4917]
I am running my application behind a reverse proxy.
The proxy should speak https:// and wss:// while my graphql-api speaks http:// and ws://.

My server looks like this: 
```
import morganBody from 'morgan-body';
import express from "express";
import bodyParser from 'body-parser';
import http from "http";
import cors from "cors";
import mongoose from "mongoose";
import dotenv from "dotenv";
import ApolloServerM from "apollo-server-express";
const { ApolloServer } = ApolloServerM;
import WebSocket from "ws";

import resolvers from "./graphql/resolvers.mjs";
import schema from "./graphql/schema.mjs";

const app = express();
app.use(bodyParser.json());
morganBody(app);
app.use(cors());

const server = new ApolloServer({ typeDefs: schema, resolvers: resolvers, playground: true, introspection: true });
server.applyMiddleware({
  app,
});

const httpServer = http.createServer(app);

// How can i enable logging for these handlers?
server.installSubscriptionHandlers(httpServer);

var port = process.env.PORT || 3000;
httpServer.listen(port, () => {
  console.log(`Server ready at http://localhost:${port}${server.graphqlPath}`);
  console.log(
    `Subscriptions ready at ws://localhost:${port}${server.subscriptionsPath}`
  );
});



// Forwarding to this Test-Server works perfect fine
const wss = new WebSocket.Server({ port: 3001, path: '/wsTest' });

wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(message) {
    console.log('received: %s', message);
	ws.send('echo: '+message);
  });
  ws.send('connection successful');
});
```

The Apache proxy config:
```
RewriteCond ${HTTP:Upgrade} websocket [NC]
RewriteCond ${HTTP:Connection} upgrade [NC]
RewriteRule ^/?graphql(.*) "ws://someIP:3000/graphql$1" [P,L]

ProxyPass        /graphql http://someIP:3000/graphql
ProxyPassReverse /graphql http://someIP:3000/graphql
```

Using the proxy the subscriptions won't work.
Trying to open a subscription result in a "400-Bad Request" response.

I was thinking it might be an issue with the proxy, thats why i setup a second echo-Websocket-Server. Forwarding to the /wsTest endpoint works perfectly fine, so there seems to be something that apollo-server doesn't like about forwarded packages.

How would one configure a reverse proxy for apollo subscriptions? Also: How can i enable debugging for the websocket operations? So far, i can see nothing in the logs.

**Comment by glasser** [comment]
Hi! I think this might be disappointing to hear, but this isn't something we can helpfully provide support for in the setting of "Apollo Server issues". It sounds like your server is working in itself, and you're just having problems setting up a separate Apache-based proxy. That's pretty external to Apollo Server and I don't think helping you is going to include improving Apollo Server.

Additionally, the integration between Apollo Server and subscriptions is pretty thin. It primarily consists of an easy to use method to help glue your server to the SubscriptionServer implemented by `subscriptions-transport-ws`. But the rest of Apollo Server doesn't really support subscriptions in a deep way.

Our [current plan for Apollo Server 3.0](https://github.com/apollographql/apollo-server/blob/release-3.0/CHANGELOG.md) is to remove this "helper function" and encourage folks who want to use `subscriptions-transport-ws` to install it directly. I hope we do the work to add subscription support across the server-side Apollo platform in a more coherent way later, but the current integration is not that.

I think this discussion is best put either on:
- an issue on [`subscriptions-transport-ws`](https://github.com/apollographql/subscriptions-transport-ws), though as you can see that package is not under very active maintenance
- a [discussion on this repo](https://github.com/apollographql/apollo-server/discussions/), where you may be able to get community help
- one of Apollo's other community resources (I'd suggest our Spectrum but we are in the process of migrating from it to a new Discourse which is not yet set up)
