### ISSUE TITLE
Usage Reporting Plugin: Error encoding trace: root.child.error.message: string expected

### ISSUE THREAD

**Issue by sepiette** [apollographql/apollo-server#4918]
## Apollo Version
`apollo-server-express` version 2.19.2. I just upgraded us from 2.12.0. 

## Expected Behavior
No Logging Errors on completed requests

## Actual Behavior
After a successful request (for both queries and mutations), I am seeing the following error in our deployed environment logs:
```
" Error encoding trace: root.child.error.message: string expected"
"    at /app/node_modules/apollo-server-core/dist/plugin/usageReporting/plugin.js:265:39"
"    at Generator.next (<anonymous>)</anonymous>"
"    at fulfilled (/app/node_modules/apollo-server-core/dist/plugin/usageReporting/plugin.js:5:58)"
Object
```

### Simple App 
**Note** - I am only seeing this error in our deployed environments, so I haven't been able to re-produce locally. However I've made a basic server with the same versions of NestJS and GraphQL packages we are currently using. We also have configured environment variables for Apollo GraphQL Studio in our deployed environment.

[Repo Here](https://github.com/sepiette/apollo-issue-mvp) 

Deployed instance of App - [http://apollo-issue-mvp.herokuapp.com/graphql](http://apollo-issue-mvp.herokuapp.com/graphql). I have logging monitoring hooked up to it to see if the same thing is happening.

**Comment by glasser** [comment]
Hi @sepiette! I'm not sure I understand the Simple App part — are you able to reproduce the issue with that heroku app?

What this means is that we're trying to report an error to Studio whose `message` property is not a string.  (It's OK for the message to be null or undefined, but it shouldn't be a number or another kind of object.)

One question: are you using the `rewriteError` option? Specifically, if you're calling `ApolloServerPluginUsageReporting()` yourself, are you using `rewriteError` there, or if you're using the older `engine` option to `new ApolloServer`, are you including `rewriteError` there?

**Comment by sepiette** [comment]
Hey @glasser! I'm actually not manually calling `ApolloServerPluginUsageReporting` or new `ApolloServer` at all. Right now we've only enabled the connection to Studio via the environment variables.  So to answer your question, we don't have any `rewriteError` function configured. Is that a necessary function to configure?

**Comment by glasser** [comment]
Hmm, how are you using ApolloServer if you're not calling `new ApolloServer`? Are you using some library that creates the ApolloServer for you?

**Comment by sepiette** [comment]
Yes we use [NestJS GraphQL](https://docs.nestjs.com/graphql/quick-start) `@nestjs/graphql `. In their words: 
```
The GraphQLModule is a wrapper around the Apollo server. We use this proven GraphQL package to provide a way to use GraphQL with Nest.
```

So in our [App Module](https://github.com/sepiette/apollo-issue-mvp/blob/master/src/app.module.ts#L10) we initialize it like so. I have a feeling it initializes the defaults, which may not match our current error format, so I may need to manually configure the usage reporting plugin.

**Comment by glasser** [comment]
I see. A brief glance at `@nestjs/graphql` does not suggest that it passes `rewriteError`, so that's not the problem. However, it is actually something we can use to help debug and/or work around the problem.

Are you able to reproduce the issue with the heroku thing you mentioned? Is there a way I could see the problem?

When it's happening, does it occur on every single query/mutation, or just on some?

Here's something we can do to get more information (and work around it). It looks to me like you can effectively pass arguments to the ApolloServer constructor by passing them to GraphQLModule.forRoot in your app. So you should be able to do something like (untested, composing directly in GitHub):

```js
import { ApolloServerPluginUsageReporting } from "apollo-server-core";
import { GraphQLError } from "graphql";

// ...
  GraphQLModule.forRoot({
   // ... whatever you're passing already and:
    plugins: [ApolloServerPluginUsageReporting({
      rewriteError(err) {
        if (err.message != null && typeof err.message != "string") {
          console.error(`An error had a surprising message of type ${typeof err.message}: ${err.message}`);
          err.message = "[non-string message removed]";
        }
        return err;
      }
    })]
  })

```

This should find the sorts of error messages that trigger that stack trace, log a bit of information about them, and replace the message with a string so that the stack trace isn't triggered.

Want to give that a shot and let me know what it logs?

**Comment by sepiette** [comment]
I wrote and deployed this last night before seeing your reply and unfortunately am still seeing the stack trace error:
```
 ApolloServerPluginUsageReporting({
                rewriteError(err) {
                  if (typeof err.message === 'string') {
                    return err;
                  }
                  return null;
                },
              }),
```
I'll add the logging mechanism you have above to try to register more info and let you know what shows in the logs! Thank you!

**Comment by trevor-scheer** [comment]
Closing as stale. Presumably we'd have seen more traffic here or new issues pop up if this wasn't resolved at this point. Happy to reopen if this is still a problem that exists on current versions.
