### ISSUE TITLE
Support Health Checks for Azure functions package

### ISSUE THREAD

**Issue by vany0114** [apollographql/apollo-server#4925]
According to the [documentation](https://www.apollographql.com/docs/apollo-server/monitoring/health-checks/) the health checks is a built-in feature but it seems to be this is not working/included in the `apollo-server-azure-functions` package. 

I can help with this if you guys want it.

**Comment by glasser** [comment]
You're correct: that package doesn't implement that feature. I'd be happy to merge a PR that implements it; it shouldn't be too hard to borrow an implementation from the Lambda package or something.

**Comment by trevor-scheer** [comment]
Looks like a fix for this landed in #5003
