### ISSUE TITLE
Graphiql error highlighting broken

### ISSUE THREAD

**Issue by mariog712** [apollographql/apollo-server#494]
I recently updated my apollo server from 0.7.2 to 1.0.5. 

It appears that syntax error highlighting in the graphiql query editor component has stopped working. The error highlighting in the query variable component still works. 

From what I can tell this stopped working in apollo server v0.8.1. That was the first version of apollo server using graphiql 0.10.2. That version of graphiql switch over to using the graphiql-language-service from what I can see. But I don't know if that is the actual cause.

You can see this in launchpad. Typing in an invalid query does not generate a red underline.

**Comment by jamsheer-thottathil** [comment]
Any update regarding this issue  ?

**Comment by mariog712** [comment]
After further review the issue is due to the current version (i.e. 0.11.2) of graphiql that apollo server 1.0.5 is depending on. 

This graphiql issue appears to have since been corrected in the graphiql master branch.
