### ISSUE TITLE
requestDidStart not called on subscriptions, no way to handle directive errors

### ISSUE THREAD

**Issue by guisehn** [apollographql/apollo-server#4942]
## Module versions
- `apollo-server`: 2.21.0
- `graphql`: 15.5.0
- `graphql-tools`: 7.0.4

## Description
When I run a query or mutation, the `requestDidStart` function of my plugin is called. With that, I can write a `didEncounterErrors` callback to handle application errors with the request context.

However, `requestDidStart` and `didEncounterErrors` are never called for subscriptions, making it impossible to handle errors for them.

## Expected behavior
`requestDidStart` should be called on every request including subscriptions. `didEncounterErrors` should be called if an error happens in the request lifecycle for subscriptions.

## Actual behavior
`requestDidStart` and, by consequence `didEncounterErrors`, are never called for subscriptions.

## Simple, runnable reproduction
I've extracted only the minimum amount of code to reproduce this issue, it can be found here:

https://github.com/guisehn/request-did-start-not-called-on-subscriptions

See README.md of the repository to see how to reproduce the issue.

**Comment by glasser** [comment]
As described in https://github.com/apollographql/apollo-server/issues/4354#issuecomment-784570753 the current Apollo Server subscriptions integration is limited and we plan to remove it to hopefully clear the way for a deeper integration later.
