### ISSUE TITLE
Error: Cannot find module 'graphql' apollo-server-express v2.10.1

### ISSUE THREAD

**Issue by FlavioAPareja** [apollographql/apollo-server#4949]
Suttendly we started to get this error and just fixed with a `npm i graphql`

Graphql packages: 
- "apollo-server-express": "2.10.1"
- "graphql-parse-fields": "1.2.0"
- "graphql-tools": "4.0.7",

Node version: v8.4.0

after run `npm install` and initialize the express server we got this error: 

```
0|api-prov | Error: Cannot find module 'graphql'
0|api-prov |     at Function.Module._resolveFilename (module.js:489:15)
0|api-prov |     at Module.Hook._require.Module.require (/home/zcebjobs/.nvm/versions/node/v8.4.0/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
0|api-prov |     at require (internal/module.js:11:18)
0|api-prov |     at Object.<anonymous> (/var/www/ceb-providers/core-api/node_modules/apollo-server-errors/dist/index.js:4:19)
0|api-prov |     at Module._compile (module.js:573:30)
0|api-prov |     at Object.Module._extensions..js (module.js:584:10)
0|api-prov |     at Module.load (module.js:507:32)
0|api-prov |     at tryModuleLoad (module.js:470:12)
0|api-prov |     at Function.Module._load (module.js:462:3)
0|api-prov |     at Module.require (module.js:517:17)
0|api-prov |     at Module.Hook._require.Module.require (/home/zcebjobs/.nvm/versions/node/v8.4.0/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
0|api-prov |     at require (internal/module.js:11:18)
0|api-prov |     at Object.<anonymous> (/var/www/ceb-providers/core-api/node_modules/apollo-server-core/dist/runHttpQuery.js:15:32)
0|api-prov |     at Module._compile (module.js:573:30)
0|api-prov |     at Object.Module._extensions..js (module.js:584:10)
0|api-prov |     at Module.load (module.js:507:32)
0|api-prov |     at tryModuleLoad (module.js:470:12)
0|api-prov |     at Function.Module._load (module.js:462:3)
0|api-prov |     at Module.require (module.js:517:17)
0|api-prov |     at Module.Hook._require.Module.require (/home/zcebjobs/.nvm/versions/node/v8.4.0/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
0|api-prov |     at require (internal/module.js:11:18)
0|api-prov |     at Object.<anonymous> (/var/www/ceb-providers/core-api/node_modules/apollo-server-core/dist/index.js:18:22)
```

The application is running with the latet version of PM2 :)

**Comment by glasser** [comment]
apollo-server-express expects graphql to be installed as a peer dependency, instead of installing it itself. (Though I believe npm v7 will install it for you since it treats peer dependencies differently.) So this is working as expected. Did you see any docs that told you to install apollo-server-express without also installing graphql?

(Also, apollo-server-express v2.10.1 is over a year old.)

**Comment by jbsulli** [comment]
Yes, the apollo-server-express npm module page mentions installing it without the graphql dep: https://www.npmjs.com/package/apollo-server-express

**Comment by glasser** [comment]
Thanks, I've fixed that README (in git, npmjs will be fixed at next publish): https://github.com/apollographql/apollo-server/commit/80a97475a24e4d914076eeb4ca9ca6de2ea77e82

If anyone motivated to look at all the READMEs in this repo for more `npm install` lines, I'm happy to review the output.

**Comment by AnirudhaGohokar** [comment]
Why did it suddenly started breaking?

**Comment by glasser** [comment]
@AnirudhaGohokar Likely due to npm v7 being released as "latest", which treats peer dependencies differently if you've started using it.

**Comment by MrSaints** [comment]
I just came across this. I believe the docs for https://github.com/apollographql/apollo-server/tree/main/packages/apollo-server-fastify, and perhaps others needs updating as well.

**Comment by glasser** [comment]
@MrSaints Thanks, updated that one and all others I found with `git grep 'npm install'` in https://github.com/apollographql/apollo-server/commit/b82c4315e4330bcb3b5fb9daf9e9b5b45dd25de2
