### ISSUE TITLE
Consider whether `dataSources` needs to continue to be part of apollo-server-core

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#4950]
The DataSource API was added to AS a few months before the new plugin API.

As it turns out, basically everything you can do with a DataSource you can also do with a plugin.

In the interest of keeping Apollo Server's API simple, I'd like to experiment with seeing if DataSources could just be a plugin rather than a core part of the AS API in AS3.

This wouldn't be removing the functionality entirely; it would just be a change from
```
new ApolloServer({dataSources: {x: new XDataSource()}})
```
to
```
new ApolloServer({plugins: [ApolloServerPluginDataSources({x: new XDataSource()})]})
```

We would introduce the new plugin as an alternative in v2 and remove the old version in v3.

**Comment by glasser** [comment]
I really don't think we need the top-level `dataSources` option in AS3, but in the interest of scope I'll leave it in for now and remove this from the AS3 project.

**Comment by trevor-scheer** [comment]
We got rid of `dataSources` 🥳
