### ISSUE TITLE
No server response regardless of processes all running

### ISSUE THREAD

**Issue by jdevng** [apollographql/apollo-server#4958]
The package name and version of Apollo showing the problem.
- [ ] If applicable, the last version of Apollo where the problem did _not_ occur.

Did not see this problem a few months ago - starting appearing about six weeks ago.

 "dependencies": {
    "@apollo/federation": "^0.20.6",
    "@apollo/gateway": "^0.21.3",
    "@prisma/client": "2.13.1",
    "apollo-server": "^2.19.0",
    "apollo-server-express": "^2.19.1",
    "auth0": "^2.30.0",
    "dotenv": "^8.2.0",
    "esm": "^3.2.25",
    "express": "^4.17.1",
    "express-jwt": "^6.0.0",
    "graphql": "^15.4.0",
    "graphql-middleware": "^4.0.2",
    "graphql-shield": "^7.4.2",
    "jwks-rsa": "^1.11.0",
    "jwt-decode": "^3.1.2",
    "nodemon": "^2.0.6",
    "request": "^2.88.2",
    "wait-on": "^5.2.0"
  },
  "devDependencies": {
    "concurrently": "^5.3.0",
    "@prisma/cli": "2.13.1"
  },

The expected behavior.
Expecting Apollo Server to respond to requests after launching indefinitely.

The actual behavior.
Within 1-3 days, Apollo Server stops responding.

Using 

ps -C <process invocation>
ps --no-headers -u -p <process id> -o pcpu,rss | awk '{cpu += $1; rss += $2} END {print cpu, rss}'

shows that the process is still running on the server. There is no log output that would suggest anything is wrong.

Running

ps -eH | less

Shows three npm processes invoked as expected.

A **simple**, runnable reproduction!

Unable to provide as it is an intermittent issue, and not sure how to debug this. It would appear to me to be some sort of socket issue. 

I have tried the following:

Reduced the schema and resolvers to one type and query only. No requests given to server - server still becomes unreachable. Running on CentOS. Tried to access the server using Playground, Firecamp and iOS, all same result.

**Comment by glasser** [comment]
Does it stop responding to all HTTP requests, or just to GraphQL requests (eg, can you load the root page in a web browser)/

Was this associated with a particular upgrade?

Note that Node is single-threaded, which means that this issue can be caused by an infinite loop anywhere in your Node app.  Does looking with ps or top indicate heavy CPU usage?

**Comment by jdevng** [comment]
I can load the root page in a browser - the errors vary. Sometimes I get a graph not valid error - similar to when I make a change in a resolver, and the server was automatically rebuilt, instead of stopped and restarted. Sometimes I get "error": "Response not successful: Received status code 500" - which I just got now. Process running, max CPU on top is 0.3%, max memory is 3% from mysqld.

I don't think it was associated with a particular upgrade. It just slowly got worse, and over the past few weeks it seems like the error occurs within 8 hours.

I thought about the infinite loop, which is why I minimized the size of the model. I'm not seeing any heavy CPU usage - and the memory is 16G, the machine is really unused.

I'm going to try and setup a virtual machine on bluehost and see if I can duplicate it, but if you have any suggestion on how generally to activate more internal logging, that would be appreciated. It's odd to me that the process looks fine, and it's mostly unreachable resolver wise.

I loaded the same server onto my laptop yesterday, and still seems to work fine, so I wonder if there is some incompatibility with the CentOS setup. I'm just not sure how to troubleshoot this - we're migrating from Ruby on Rails, it usually either died or spit out a ton of error messages before failing to respond to a request.

**Comment by glasser** [comment]
I'd suggest trying to use the Node debugger (eg, running your app with `node --inspect` and connecting to it with Chrome Devtools once it gets bad).

I'm not sure I have much other advice other than generic Node debugging advice at this point.

**Comment by jdevng** [comment]
Thank you for the advice, trying now. I'm setting up a few experiments on different servers, I'll let you know the results.

**Comment by jdevng** [comment]
I set up another server and see the same results. What's odd is that upon error, the socket breaks in SSL that I used to invoke npm, but when I put a catch on the npm process, it never fires during the error condition. If I kill the process, the exit is caught.  From the top level of home I searched for the error INTERNAL_SERVER_ERROR below, and found no hits of any log files:

$ find . | xargs grep -s INTERNAL_SERVER_ERROR | grep -v ".ts" | grep -v ".js"
$

This is the most meaningful error I've seen, which is in initSchema. Why would this suddenly error after several hours with no usage of the server?

{
  "errors": [
    {
      "message": "This data graph is missing a valid configuration. More details may be available in the server logs.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: This data graph is missing a valid configuration. More details may be available in the server logs.",
            "    at servername/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/ApolloServer.js:211:23",
            "    at processTicksAndRejections (node:internal/process/task_queues:94:5)"

**Comment by glasser** [comment]
This error means that your server failed to load its schema (from managed federation or whatever mechanism you're using the gateway). The error handling right now is poorly arranged so that the full stack trace with context gets logged once on startup in a place where you can't really handle it in your code, and then the error you've shown above gets returned from every response thereafter. My main project right now is improving the error handling so that this will cause your server to fail fast on startup instead of seeming to happily starting up in an unfixable broken state (see https://github.com/apollographql/apollo-server/milestone/55)

**Comment by trevor-scheer** [comment]
Seems like this is resolved. If someone comes across this and finds the error message to still be unhelpful please open a new issue.
