### ISSUE TITLE
[Need help] User registration email verify with apollo-server-express

### ISSUE THREAD

**Issue by viiiprock** [apollographql/apollo-server#496]
I'm working on registration with `graphql`, `apollo-server-express`. My flow is:
1. User submit user name, email and password.
2. Server send an email to user (mailgun-js) with unique link.
3. User follow the link to verify the registration.
Example: user follow the link url =  `/verified?:token` the *token* is generated by `uuid`
And I got stuck at the step that user follow link and the server will make a mutation resolver such as 
```js
    verifiedUser: async (root, data, { mongo: {Users} }) => {
      await Users.updateOne(
        { email: data.email },
        {
          $set: {is_verified: true},
          $unset: {verification_token: {token: ''}}
        }
      )
    },
```

Could anybody has any direct example or give me a hint to solve this out? thanks so much!

**Comment by martijnwalraven** [comment]
This isn't really an issue specific to `apollo-server-express` or even Apollo Server, and it's also more of a usage question than anything actionable. Closing this, because I think the best venue for this would be the [Apollo Slack](http://www.apollodata.com/#slack).
