### ISSUE TITLE
apollo-server-cache-redis doesn't update after mutations

### ISSUE THREAD

**Issue by Pixelatex** [apollographql/apollo-server#4962]
apollo-server version: 2.5.0

So I setup my redis cache using the example as provided
```
const cache = new RedisCache({
  host: "",
  port: 17146,
  password: "",
  // Options are passed through to the Redis client
});
```

However, it has become clear to me that mutations don't update the redis cache causing my graphql server to return incorrect data and the user thinking that their update didn't work.

I can't find ANYTHING on how this is supposed to be handled, prior people having this issue,.. My only solution is to ssh in my redislabs account and nuke the entire content of the database..

**Comment by kekakuka** [comment]
Yes, need to invalidate the cache after mutation. Otherwise, it is hard to use.

**Comment by glasser** [comment]
I assume this is referring to the full response cache plugin? Yes, there's no specific way to do cache invalidation right now, which does mean that the feature is not appropriate for many use cases.
