### ISSUE TITLE
Add support for GraphQL multipart requests in apollo-server-fastify

### ISSUE THREAD

**Issue by SirMishaa** [apollographql/apollo-server#4975]
Hello.

I recently wanted to use GraphQL and Graphql-upload on Nest with Fastify.
And it was an adventure, it was very hard to find the reason why it didn't work.

It seems that it just lacks multipart support and you need to add a contentTypeParser.
This seems to be already integrated on apollo-server-express.

Can you / can I do a PR in order to integrate it natively in the next version? 

Thank you very much. ❤

```ts
import { processRequest } = from 'graphql-upload'

function fastifyGraphQLUpload(fastify, options = {}, done) {
  fastify.addContentTypeParser('multipart', (req, done) => {
    req.isMultipart = true
    done()
  })

  fastify.addHook('preValidation', async function(request, reply) {
    if (!request.req.isMultipart) {
      return
    }

    request.body = await processRequest(request.req, reply.res, options)
  })

  done()
}
```

**Comment by glasser** [comment]
Hi! The Apollo Server core team do not personally use Fastify so we are definitely reliant on PRs to improve `apollo-server-fastify`.

I'm happy to review a PR to improve `apollo-server-fastify`. Note that Apollo Server 2 has a "built in" graphql-upload integration (which is stuck on a fork of an old version of `graphql-upload`), but we're planning to remove that integration pretty soon in Apollo Server 3.

Are you saying that the existing `apollo-server-fastify` `graphql-upload` integration doesn't actually work?  Or that trying to integrate it yourself (which you'll need to do in AS3) is impossible?  If the former, I'm a bit surprised, but also not super motivated to improve the existing integration instead of encouraging folks to switch the their own version of (probably up-to-date) `graphql-upload`. If the latter then yep, definitely happy to review a PR to add whatever integrations points are necessary to `apollo-server-fastify` to allow it to work with your own import of `graphql-upload`.

I did not understand what your code snippet was implying but perhaps this would be more clear as a PR?

**Comment by zanechua** [comment]
So I'm working on adding support for this with AS3 and I'm definitely not having a great time with getting this going.

I'm very sure I'm utilizing the functions correctly but it fails with AS3 with the same error as https://github.com/apollographql/apollo-server/issues/5230. I'm not even utilizing the `batteries-included` version and am only using `apollo-server-fastify`.  Middleware is being handled by `middie`.

Even after using the middleware and `processRequest` from `graphql-upload`, the replaced body is on the `request.raw` object when accessed during the context and not directly on the `request` object. I just assigned the variable accordingly from `request.raw` and that's where I'm getting stuck at. Trying to figure it out at the moment and will post example code of the broken project if I still can't get it going.

**Comment by zanechua** [comment]
Okay. So I worked this out. I spent a few hours trying to figure out what went wrong where and it was my understanding of how fastify handles the different context types. Which brought me to the docs which states that it does not handle multipart and i installed `fastify-multipart` and that's where the troubles began. 

You should **NOT** use `fastify-multipart` as you can only register one handler for each content type.

Add the following to your server and this will handle all `graphql-upload` multipart requests, not sure at the moment how to handle if you're using both traditional multipart  requests and graphql-upload specific ones.

```javascript
fastify.addContentTypeParser('multipart', function (request, payload, done) {
  try {
    // Assign payload from node request to FastifyRequest
    done(null, payload.body);
  } catch (err) {
    err.statusCode = 400;
    done(err, undefined);
  }
});
```

You'll also need to use the middleware from `graphql-upload` to process the request, but you'll have to install `middie` or equivalent to handle the middleware. I've asked the author of `graphql-upload` in https://github.com/jaydenseric/graphql-upload/issues/255 to see if he could make a small change so you don't have to copy and modify 1 line of the code for the middleware.

```javascript
// Register middleware handler
await fastify.register(fastifyMiddie);
fastify.use((request, response, next) => {
  // Only handle multipart requests
  if (!(/^multipart\/form-data/.test(request.headers['content-type']))) return next();

  const finished = new Promise((resolve) => request.on('end', resolve));
  const { send } = response;

  response.send = (...args) => {
    finished.then(() => {
      response.send = send;
      response.send(...args);
    });
  };

  processRequest(request, response, {
    maxFileSize: 10000000, // 10 MB
    maxFiles: 20
  })
    .then((body) => {
      request.body = body;
      next();
    })
    .catch((error) => {
      if (error.status && error.expose) response.status(error.status);
      next(error);
    });
});
```

The rest of the code you can just follow the AS3 docs 

https://www.apollographql.com/docs/apollo-server/v3/data/file-uploads/

**Comment by glasser** [comment]
OK. So there are no code changes required to get this working?

If you'd like to send a PR to add a fastify example to https://www.apollographql.com/docs/apollo-server/v3/data/file-uploads/
 (that's docs/source/data/file-uploads.md in this repo) that would be great!

**Comment by zanechua** [comment]
None at the moment that I can see that's blocking anything. Subscriptions work accordingly with the GraphIQL client.

Okay. Let me grab some time out and do a PR for the docs as that would be really helpful for the rest of the users
