### ISSUE TITLE
Jest Testing: TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by Prefinem** [apollographql/apollo-server#4988]
I am trying to test with Jest right now using the apollo-server-testing.  Right now anytime I try and require `apollo-server` or `apollo-server-X` it fails with this

```
TypeError: Class extends value undefined is not a constructor or null

      1 | const { createTestClient } = require('apollo-server-testing');
    > 2 | const { ApolloServer } = require('apollo-server');
        |                          ^
      3 | const schema = require('./graphql');
      4 | const models = require('./graphql/models');
      5 | const knex = require('knex');

      at Object.<anonymous> (node_modules/apollo-server-types/src/index.ts:154:49)
      at Object.<anonymous> (node_modules/apollo-server-core/src/requestPipeline.ts:35:1)
      at Object.<anonymous> (node_modules/apollo-server-core/src/runHttpQuery.ts:13:1)
      at Object.<anonymous> (node_modules/apollo-server-core/src/index.ts:3:1)
      at Object.<anonymous> (node_modules/apollo-server-express/src/index.ts:1:1)
      at Object.<anonymous> (node_modules/apollo-server/src/index.ts:9:1)
      at Object.<anonymous> (src/index.test.js:2:26)
```

This is not a type script project, so I am sure there is some failure with jest trying to view the types, but this also seems to be an issue with the apollo-server-core library that has a circular reference.

**Comment by glasser** [comment]
Can you provide a full reproduction? This seems like the sort of thing that would be very specific to your build system.  ie, can you hand me a git repo or codesandbox.io or something where I can see this error directly on my computer?

That said, it looks like the line in `apollo-server-types` at the top of the stack trace is

```
export class InvalidGraphQLRequestError extends GraphQLError {}
```

GraphQLError comes from the `graphql` package (graphql-js), which is a peer dependency of the Apollo Server packages. Have you installed `graphql` in your project?

(Note: I'm not sure why this would be specific to apollo-server-testing, but if it is, I will note that that package is a very thin layer around the ApolloServer `executeOperation` method. So if for some reason you find yourself unable to use that package when the rest of Apollo Server works, you can just run `executeOperation` yourself.  eg `server.executeOperation({query: yourGraphQLOperationString})`, or if your operation is a parsed AST from the `gql` graphql tag, `server.executeOperation({query: print(yourParsedGraphQLOperation})` where `print` is imported from `graphql`. I am considering removing the package from Apollo Server 3 as it doesn't provide that much value over executeOperation.)

**Comment by Prefinem** [comment]
@glasser Thanks for taking the time to look at this.  I ended up finding the issue when recreating the test repo to give to you.

If anyone finds this down the road, if you set an additional `moduleDirectories` for jest and it happens to include `graphql`, then this is the error you will receive
