### ISSUE TITLE
add another backend

### ISSUE THREAD

**Issue by ulrikstrid** [apollographql/apollo-server#500]
If I wanted to implement another backend for Apollo server how would you want me to do that? Create a separate repo and add it to npm or should I fork this repo and create a PR?

**Comment by martijnwalraven** [comment]
If it's generally useful, a new `apollo-server-` package in this repo sounds great! What backend are you interested in implementing?

**Comment by ulrikstrid** [comment]
Azure Functions is what I want to implement. I think that the approach I want to take is to create a separate repo and publish under my namespace on npm. When I'm done I will ping you here and see if you're interested in a PR in to this repo.

**Comment by ulrikstrid** [comment]
The PR is open #503.

For usage example https://github.com/ulrikstrid/azure-functions-graphql. I published it under my namespace on npm as well.

**Comment by ulrikstrid** [comment]
My PR was merged so I'm closing this.
