### ISSUE TITLE
Err Query fields must be an object with field names as keys or a function which returns such an object. babelrc dev server

### ISSUE THREAD

**Issue by Kielan** [apollographql/apollo-server#501]
I am implementing graphql-server-express routes inside of a express server which also serves a frontend react app. I want to set up graphiql to explore my type queries but come across this issue. There is no stacktrace, only to the internal node modules.

```  [2] Error: Query fields must be an object with field names as keys or a function which returns such an object. 
at invariant (/*/node_modules/graphql/jsutils/invariant.js:19:11)
[2]     at defineFieldMap (/*/node_modules/graphql/type/definition.js:266:27)
[2]     at GraphQLObjectType.getFields (/*/node_modules/graphql/type/definition.js:235:44)
[2]     at /*/node_modules/graphql/type/schema.js:207:27
[2]     at typeMapReducer (*/node_modules/graphql/type/schema.js:219:7)
[2]     at Array.reduce (native)
[2]     at new GraphQLSchema (/*/node_modules/graphql/type/schema.js:95:34)
```

I assume my err is happening not in my schema itself (which only has queries no mutation or subscriptions) and inside of my type's field method which should return an object

objectType.js
```
module.exports = new GraphQLObjectType({
  name: "Object",
  fields: () => ({
      firstName: {
        type: GraphQLNonNull(GraphQLString)
      },
      lastName: {
        type: GraphQLNonNull(GraphQLString)
      },
      status: {
        type: GraphQLNonNull(GraphQLString)
      }
  })
})
```

```
const {
  GraphQLObjectType,
  GraphQLSchema,
} = require('graphql');
const queries = require('./queries');

module.exports = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'Query',
    field: queries
  })
});
```

```
module.exports = {
  type: practiceType,
  args: {
    firstName: {
      name: 'firstName',
      type: GraphQLString
    }
  }
  resolve: (root, { firstName }, { db: { graphqltest } }, fieldASTs) => {
    return new Promise((resolve, reject) => {
      const projection = getProjection(fieldASTs)
      practice.findOne(firstName)
        .select(projection)
        .exec()
        .then(data => resolve(data))
        .catch(err => reject(err))
    })
  }
}
```
is it possible this err has nothing to do with my actual type or schema definition, or what can i do with this stack trace and err message? I am not sure how to follow the err or validate that my fields method is returning an iterable key.

**Comment by abernix** [comment]
I'm going through and trying to cleanup some older issues which may no longer be problematic.  There's been a number of changes to Apollo Server since this was opened, and this doesn't appear to be continually affecting anyone.  That said, if you're still having problems, please feel free to ping back or open a new issue with a reproduction (preferably a runnable CodeSandbox/Glitch or GitHub repository which can be easily cloned and debugged!)

Thanks for reporting this originally!
