### ISSUE TITLE
Using apollo-datasource-rest with client certificates? 

### ISSUE THREAD

**Issue by matteoredaelli** [apollographql/apollo-server#5021]
I'd to fetch data from an external REST service that requires client certificates. How could I manage it with apollo-datasource-rest?

https://help.qlik.com/en-US/sense-developer/February2021/Subsystems/RepositoryServiceAPI/Content/Sense_RepositoryServiceAPI/RepositoryServiceAPI-Example-Connect-Nodejs.htm

Regards
Matteo

**Comment by glasser** [comment]
As [documented](https://www.apollographql.com/docs/apollo-server/data/data-sources/#http-methods) you can pass an `options` to any of the fetch/get/post/etc methods which is then passed to the underlying fetch implementation. This `options` is the same as the `request` passed to [willSendRequest](https://www.apollographql.com/docs/apollo-server/data/data-sources/#intercepting-fetches) so you can also use that method to add stuff to it.  `apollo-datasource-rest` uses `node-fetch` under the hood. `node-fetch` lets you include an `agent` on the request which can be used to implement client certs (and our typings include the appropriate `RequestOptions.agent` field). So you can set up an `https.Agent` (here's a [blog post](https://sebtrif.xyz/blog/2019-10-03-client-side-ssl-in-node-js-with-fetch/) with some guidance) and write a `willSendRequest` that does `request.agent = myCertAgent`.)

**Comment by matteoredaelli** [comment]
Thanks to your suggestions I was able to create a new Apollo datasource for Qliksense

  https://github.com/matteoredaelli/apollo-datasource-qliksense

Regards
Matteo
