### ISSUE TITLE
Lambda GraphiQL errors when event.queryStringParameters is null

### ISSUE THREAD

**Issue by thevtm** [apollographql/apollo-server#504]
I'm running a Lambda GraphQL Server using AWS Lambda and API Gateway.
The GraphiQL is configured as a `Lambda Proxy integration`.

**Intended outcome**
Get the regular GraphiQL interface when I access `https://myapi.com/graphiql`.

**Actual outcome**
`Cannot read property 'query' of null`

**How to reproduce the issue**
```typescript
import { graphiqlLambda } from "apollo-server-lambda";

export default graphiqlLambda({
  endpointURL: "/beta",
});
```
GraphiQL method configured as a  `Lambda Proxy integration`.

**Workaround**
`https://myapi.com/graphiql?foo=42` works just fine.

**Comment by alanhoff** [comment]
I was able to reproduce it and the workaround worked.

**Comment by nenti** [comment]
Is there a workaround to fix this on the server rather than by sending the client a different url?

**Comment by harshabonthu** [comment]
If I downgrade `graphql-server-lambda` to `0.8.5`, then it works and any version above that its broken.

**Comment by diit** [comment]
Ran into this as well, a good solution would be to change this:

https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-lambda/src/lambdaApollo.ts#L87

to:
```
const query = event.queryStringParameters || {};
```

**Comment by stubailo** [comment]
I think #512 fixes this issue!

**Comment by abernix** [comment]
Closing as I suspect this is fixed, but please do ping back or open a new issue if this is still occurring on the latest versions of Apollo Server 2.x!

Thanks for reporting this originally!
