### ISSUE TITLE
Lambda Appolo Server, CORS Bug: Access-Control-Allow-Origin NOT been added when {origin: true,     credentials: true} is set 

### ISSUE THREAD

**Issue by hansheng654** [apollographql/apollo-server#5040]
Lambda Version: "apollo-server-lambda": "^2.21.0",

Set up: 
1.  Serverless framework deployment of apollo-sever-lambda 
2. Typescript 

` export const graphqlHandler = server.createHandler({
       cors: {
    methods:['WNY IS ORIGIN NOT BEEN SET?'],
    origin: '*',
    credentials: true,
    allowedHeaders: ['x-correlation-id'],
  },
      });

Severerless: (for reader's context :)
functions: # Your "Functions"
  graphql:
    handler: src/apollo-server.graphqlHandler
    events:
      - http:
          authorizer:
            name: authorizerFunc
            type: request
            resultTtlInSeconds: 300
            identitySource: method.request.header.Authorization, context.path, context.httpMethod
          path: graphql
          method: post
          cors:
            origin: '*'
            headers:
              - X-Correlation-ID
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
`
However, the response header DOES NOT contain Access-Control-Allow-Origin, 
![image](https://user-images.githubusercontent.com/13898041/111563789-9609b580-87d3-11eb-99f7-1ca7c164e487.png)

I have tried
1. run locally using severless offline
2. deployed on AWS and call the api
3. different combinations of setting of {origin: true, credentials: true, origin:"*", credentials:true, origin:["http//:localhost"]}, nothing get reflected in the response header... 

Everything else is working, can get data back, preflight cors(managed by the serverless framework) is working.

Expected behaviour: 
Access-Control-Allow-Origin should present in response header with the correct setting in cors

**Comment by hansheng654** [comment]
I have a feeling that this is a serverless framework issue.... please let me know if anyone faced a similar situation, feel free to close this issue if no one else is having the same problem:)

Thanks

**Comment by glasser** [comment]
Thanks for filing the issue. It is much easier for us to debug issues (especially ones that involve interactions with other software like `serverless` or Lambda itself) if there is a full reproduction that we can use without any creative thought to see the issue ourselves. For Lambda, that would probably be a series of instructions starting with "Create an AWS IAM user and an API key, run `git clone` and `npm install` in this repository, and then..."  A code snippet like the above is not enough for us to help. Happy to reopen the issue and investigate if a complete reproduction instruction is provided.

If at all possible, minimizing the number of external dependencies would be helpful. For example, you suggest that this might be related to `serverless`; are you able to reproduce the issue without `serverless`? I see that you are passing CORS configuration to both `serverless` in its config file and to Apollo Server.

**Comment by glasser** [comment]
@mjhost If you're using `@koa/cors` yourself, you should disable AS' CORS defaults by passing `cors: false` to `getMiddleware`.

We are planning to improve the documentation and add some logging around CORS defaults soon: #5076

**Comment by mjhost** [comment]
right, it took a while to find it, thanks for your help
