### ISSUE TITLE
Update cors and @types/cors

### ISSUE THREAD

**Issue by paolocattani** [apollographql/apollo-server#5055]
I'm using `cors@2.8.5` and `@types/cors@2.8.10` but apollo-server-express still use `cors@2.8.4` and `@types/cors@2.8.8` and this is causing a types error.

**Comment by glasser** [comment]
Sounds reasonable, but can you share what the error you're seeing is?

**Comment by glasser** [comment]
I suppose it is probably related to the errors that CI is seeing on https://github.com/apollographql/apollo-server/pull/4930

For what it's worth, the express-related `@types` packages have a lot of problems where using specific versions of them require you to use specific versions of other ones, but the actual published npm dependency ranges are just `*`. You may need to make sure your app pulls in a newer version of something like `@types/express-serve-static-core` to resolve the issue.

**Comment by glasser** [comment]
Nah, looks like this is actually something specific to `@types/cors`, and ironically caused by [a PR that was intended to help Apollo somehow](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49130). I'll fix.

**Comment by paolocattani** [comment]
@glasser thanks for super fast response 😄 . 
As you said the problem was on `@types/cors` .
The `origin` prop has been changed from `origin?: boolean | string | RegExp | (string | RegExp)[] | CustomOrigin;` to `origin?: StaticOrigin | CustomOrigin;`
