### ISSUE TITLE
Make it more clear that the default CORS strategy is permissive

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#5076]
Our docs aren't clear about what the default behavior for cors is.

Specifically, the default behavior for some integrations such as the most popular `apollo-server` and `apollo-server-express` is to install the `cors` package with the default configuration, which is to set `Access-Control-Allow-Origin: *`. Other integrations default to doing nothing unless `cors` is installed explicitly.

This issue is about *documenting the behavior of Apollo Server 2.x* and perhaps making other backwards-compatible changes, not about considering making backwards-incompatible changes to make the behavior more consistent or generally better. (See #4859 for that.)

We should be much more clear what the default CORS behavior is on https://www.apollographql.com/docs/apollo-server/api/apollo-server/ and https://www.apollographql.com/docs/apollo-server/integrations/middleware/ and probably add a little page under Security about CORS.

We can also consider other changes that make the default behavior more clear. For example, perhaps the integrations that turn on cors by default can log a brief message saying that it's setting `Access-Control-Allow-Origin: *`; you can remove the log without changing the behavior by passing `cors: true` to `new ApolloServer`, or adjust the behavior with other options.

**Comment by glasser** [comment]
https://github.com/apollographql/apollo-server/pull/3460 is related.

**Comment by glasser** [comment]
In AS3 we are making the CORS default behavior more *consistent* (always serving `acao: *` in all integrations). This is a great default for getting started with development, but not great for production. After AS3 is out we should change it to log a warning when you have `acao: *` enabled (maybe only in production?) unless you explicitly opt in to it. We should also have a full docs page about CORS.

**Comment by yanickrochon** [comment]
Upgrading from `apollo-server-koa@2.25.2` to `apollo-server-koa@3.1.2`, the application breaks with the error 

> Access to fetch at 'http://localhost:4000/graphql' from origin 'http://localhost:3002' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

I have to downgrade it back for the app to work again. No idea how to resolve this.

**Comment by glasser** [comment]
@yanickrochon This is documented in the migration guide: https://www.apollographql.com/docs/apollo-server/migration/#cors--is-now-the-default

In AS2, apollo-server-koa had a different default from the other web framework integrations (and this wasn't even documented); we've aligned them to all work the same in AS3. The migration guide shows how to get the AS2 behavior of "echo the incoming origin" with apollo-server-koa (which is required in the Fetch API in order to include cookies).

(We are also still planning to work on this ticket soon by improving our docs around CORS and making it clear what the default is via added logging!)

**Comment by yanickrochon** [comment]
@glasser I had that setting in the server constructor. 

```
const apolloServer = new ApolloServer({
  ...processSchema(schemas),
  ...graphqlConfig,
  cors: false,
  context: ({ ctx }) => ctx,
});
await apolloServer.start();
````
And the middleware
```
app.use(apolloServer.getMiddleware());
```

So, I removed option `cors` in the constructor, and moved it insie `getMiddleware`, as
```
app.use(apolloServer.getMiddleware({ cors: {} }));
```
and it now works. Thanks!

**Comment by glasser** [comment]
Good to hear! I recommend using TypeScript so it's easier to put parameters in the right place.

**Comment by susannakosic** [comment]
Hi @glasser, do you know if default cors configuration is expected to apply as well to .well-known/apolo/server-health? I could not find any ref about this on docs.
[#6095](https://github.com/apollographql/apollo-server/issues/6095)

**Comment by glasser** [comment]
I answered on #6095.
