### ISSUE TITLE
Consider replacing apollo-server-lambda with apollo-server-express + wrapper

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#5078]
I am getting more and more convinced that continuing to add more and more features to apollo-server-lambda (and other serverless frameworks) that just make up for their lack of middleware structure (eg, more and more complex `cors` options) is not a great use of this project's efforts. I'd like to see whether we can replace the entirety of `apollo-server-lambda` with something that wraps `apollo-server-express` with something like [`@vendia/serverless-lambda`](https://github.com/vendia/serverless-express) to convert an Express app into a Lambda app. Then we only have to implement features once in `apollo-server-express`, and folks can use standard Express libraries to implement other features.

This might mean "`apollo-server-lambda` is a small package that combines those two packages" or even "`apollo-server-lambda` is removed from AS3 and docs teach you how to use `@vendia/serverless-lambda` itself.

Note that despite the name, this package is not related to https://github.com/serverless/serverless

**Comment by coyoteecd** [comment]
Note this reverses the changes made in https://github.com/apollographql/apollo-server/issues/5018, because createHandler now returns a Handler type exported by aws-lambda (whose author intentionally doesn't want to remove the callback from the handler signature).
