### ISSUE TITLE
Problem with cookies

### ISSUE THREAD

**Issue by thealjey** [apollographql/apollo-server#508]
```javascript
const schema = require('./api/schema');
const express = require('express');
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');
const {graphqlExpress, graphiqlExpress} = require('apollo-server-express');

const app = express();

async function buildOptions(req, res) {
  console.log(req.cookies); // always {}

  return {
    context: {},
    schema
  };
}

app.use(cookieParser());

app.use('/graphql', bodyParser.json(), graphqlExpress(buildOptions));

app.use('/graphiql', graphiqlExpress({ // requests handled through this are passing the cookies correctly
  endpointURL: '/graphql',
  subscriptionsEndpoint: `ws://localhost:${PORT}/subscriptions`
}));
```

Hi!
A really basic setup here.

I do not know what I've configured wrong, but when my resolvers are called through the "/graphiql" endpoint they receive all the cookies configured, but when called through the "/graphql" endpoint `req.cookies` is always an empty object.

Btw, I've tried putting `cookieParser()` like this
```javascript
app.use('/graphql', cookieParser(), bodyParser.json(), graphqlExpress(buildOptions));
```
and this
```javascript
app.use('/graphql', bodyParser.json(), cookieParser(), graphqlExpress(buildOptions));
```
with no result

Thanks!

**Comment by thealjey** [comment]
turns out the problem only exists when `react-apollo` calls the API from the server side, so the issue must be in that library (or in my configuration of it)

**Comment by stubailo** [comment]
Yeah - you need to make sure to send the cookie manually since there's no browser on the server to send it for you.

**Comment by StupidSexyJake** [comment]
Did you find a solution to this? I'm having the same issue. I can set cookies but not get them, even though the cookie is clearly set in the browser. console.log(req.cookies) returns undefined.

I believe this is an issue with apollo-server-express.

**Comment by alanyong91** [comment]
I find `apollo-server`. I tried with `apollo-server-express` and `apollo-server-micro`. Both have the same problem: `req.cookies` return empty object. I found a lot of questions in stackoverflow, mostly just save token in cookie, which I don't want to do that. Kind of waste my time to study `apollo-server`. Not reliable after all.

**Comment by sterlingbm** [comment]
Same issue. 

The cookie is actually returning in the headers and I can access it in req.headers.cookie.token. Even though the browser clearly shows it is being stored as a cookie. 

req.cookies.token is undefined.
