### ISSUE TITLE
Nest.js - Plugin implementation - Typescript error

### ISSUE THREAD

**Issue by ThibautJ** [apollographql/apollo-server#5092]
Package name: apollo-server-plugin-base v0.10.0

I'm creating a plugin in my nest.js application to change the transaction name inSentry and I'm following the nest.js [documentation](https://docs.nestjs.com/graphql/plugins) to do so.
```typescript
import { Plugin } from "@nestjs/graphql";
import { ApolloServerPlugin, GraphQLRequestListener, GraphQLRequestContext } from "apollo-server-plugin-base";
import * as Sentry from "@sentry/node";

@Plugin()
export class SentryPlugin implements ApolloServerPlugin {
  requestDidStart(ctx: GraphQLRequestContext): GraphQLRequestListener {
    // Override transaction name with query/mutation name
    const scope = Sentry.getCurrentHub().getScope();
    if (scope && ctx.request.operationName) {
      scope.setTransactionName(ctx.request.operationName);
    }
    return {};
  }
}
```
All seems good, except the TS error on my SentryPlugin class saying: 

> Class 'SentryPlugin' incorrectly implements interface 'ApolloServerPlugin<Record<string, any>>'.
> Index signature is missing in type 'SentryPlugin'.

Where do this error is coming from? And should it be better documented or am I simply doing something wrong?

Thanks,

**Comment by glasser** [comment]
I played around with this snippet for a moment but wasn't able to reproduce it. Perhaps this depends on the precise versions of `apollo-server-plugin-base`, `@nestjs/graphql`, and `typescript` installed, or the exact tsconfig parameters. Can you provide a complete reproduction recipe, probably starting with `git clone` or a pointer to codesandbox.io, that allows me to see the issue for myself? Happy to reopen and investigate if so.
