### ISSUE TITLE
Consider a major release of apollo-server-cache-redis changing the interface

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#5099]
The AS 2.23 release includes a v1.4.0 release of apollo-server-cache-redis which introduces `BaseRedisCache` into which you inject a redis client, and changes RedisCache and RedisClusterCache into being wrappers around these that construct the client for you. This way we don't have to worry about "but do we support every potential redis client constructor shape" like we did with the old classes.

We should consider (either as part of the AS3 lifecycle, or just independently) releasing a major version bump of this package which renames BaseRedisCache back to RedisCache and drops the old wrappers.

**Comment by glasser** [comment]
I'm going to remove this from the AS3 milestone. While it may be a good idea, the versioning schema of ASCR is not related to AS' own versioning, so we can put out a v2 of it at any time.

**Comment by trevor-scheer** [comment]
Closing as no longer relevant, since we no longer maintain these cache wrappers ourselves and instead defer to the `keyv` project for this kind of functionality.
