### ISSUE TITLE
Schema not getting updated after instantiation

### ISSUE THREAD

**Issue by AienTech** [apollographql/apollo-server#5106]
Basically after the server is instantiated, the schema change process won't run and thus resolvers aren't getting updated.

The issue actually happens in a CMS where, after the user changed the schema, we should update the server accordingly so that introspection and resolving work.

here's a sample of how the process takes effect:

```javascript
// initial build
let external;

let externalServer: any = new ApolloServer({
    introspection: true,
    playground: true,
    schema: buildSchema(`type Query { boot: Boolean }`),
});

pubSub.subscribe("REBUILD_EXTERNAL", async(payload) => {
    external = await createExternal(connection);  // this function creates the new schema and the context after a change
    externalServer.schema = external.schema;
    externalServer.context = external.context;
    externalServer.schemaDerivedData = externalServer.generateSchemaDerivedData(external.schema);
});

// to update the schema after first initialization
pubSub.publish("REBUILD_EXTERNAL", {
    name: "SERVER_BOOT"
});

externalServer.applyMiddleware({
    app,
    path: `${config.path}graphql`,
        cors: {
            origin: true,
        },
});
```

this issue is actually taken from [PrimeCMS](https://github.com/birkir/prime/issues/329) with some small changes for better readability.

**Comment by glasser** [comment]
Updating these fields to change the schema is not part of the Apollo Server API. We refactored the internal storage of these fields in v2.22.

If you want to update your schema over time, you can create an object that obeys the GraphQLService API including the onSchemaChange method and pass it as the `gateway` argument.

It might also be reasonable for us to expose a public API to let you set your schema that does
```
      if (this.state.phase === 'started') {
        this.state.schemaDerivedData = this.generateSchemaDerivedData(schema);
      }
```
just like the onSchemaChange callback.

But this is for now working as intended.
