### ISSUE TITLE
apollo-server-testing throws error: Unable to create test client (TypeError: Cannot read property 'bind' of undefined)

### ISSUE THREAD

**Issue by bigfish** [apollographql/apollo-server#5111]
Using apollo-server & apollo-server-testing 2.22.2

Following documentation to setup an integration test here https://www.apollographql.com/docs/apollo-server/testing/testing/

I get the error when I run jest:

 ```
TypeError: Cannot read property 'bind' of undefined

      104 |         });
      105 |         // console.log(server);
    > 106 |         const { query } = createTestClient(server);
          |                           ^
      107 |
      108 |         const res = await query({
      109 |           query: GET_ROUTES

      at createTestClient (node_modules/apollo-server-testing/src/createTestClient.ts:31:52)
      at Object.<anonymous> (spec/routesResolver.spec.js:106:27)
```
 
Looking at the referenced source code, it is attempting to bind a function named executeOperation. Apparently this doesn't exist? 

```
export default (server: ApolloServerBase): ApolloServerTestClient => {
  const executeOperation = server.executeOperation.bind(server);
```

Is there some mismatch between the testing library and the server?

**Comment by glasser** [comment]
This is a method that exists. I can't reproduce your issue; if you can post a complete reproduction (eg, a repo I can `git clone` or something on codesandbox.io) I can reopen and dig into it.

For what it's worth, `apollo-server-testing` is a VERY thin layer around executeOperation and I don't think having the separate package is really worth the added complexity of having to install another package, etc.  I realize it is what we document but I'd suggest just using `server.executeOperation` directly (once you figure out why it doesn't exist for you?). We may remove `apollo-server-testing` in Apollo Server 3 (https://github.com/apollographql/apollo-server/issues/4952).  Here's an example of a PR that changes a project from using `apollo-server-testing` to using `executeOperation`: https://github.com/apollographql/federation/pull/554

**Comment by bigfish** [comment]
ah, in the process of preparing the repo for the issue, I found my mistake.. I wasn't destructuring the returned value from my createTestClient() helper function, so I was passing an object like `{ server }` to `createTestClient()`. After passing the server itself, it is working as expected. Perhaps a more helpful error message like 'The argument provided to createTestClient() is not a valid ApolloServer instance: ' could be thrown?

**Comment by glasser** [comment]
Maybe, but I think a better approach would just be to change the docs that mention `apollo-server-testing` to just document `server.executeOperation` instead and leave `apollo-server-testing` as a curio that exists only for backwards compatibility.
