### ISSUE TITLE
AS3: Update all Fastify packages

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#5120]
`release-3.x` already has [initial fastify3 support](https://github.com/apollographql/apollo-server/pull/4356) merged, but we're not testing against v3 by default, and there are other fastify packages like [fastify-accepts](https://github.com/apollographql/apollo-server/pull/4371) that are out of date. Fastify is increasingly popular and we should let AS3 be an opportunity to be fully up to date.

**Comment by abernix** [comment]
Ref: https://github.com/apollographql/apollo-server/pull/4254

**Comment by glasser** [comment]
@abernix not sure I know why you're linking that issue; it doesn't look like Fastify?

**Comment by glasser** [comment]
OK, I don't know why I said "we're not testing against v3"; we are. I've filed #5174 to get us on the very latest versions.

**Comment by glasser** [comment]
Fixed on release-3.0 in #5174
