### ISSUE TITLE
When I try to migrate to ApolloServerPluginSchemaReporting in plugins, I get error "crypto.getRandomValues() not supported"

### ISSUE THREAD

**Issue by alexbjorlig** [apollographql/apollo-server#5130]
Using node.js apollo server version `apollo-server-express: 2.23.0`, I can't start the node.js process if I include `ApolloServerPluginSchemaReporting` in my plugins array. It fails with: 

```js
'crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported'
```

**Comment by abernix** [comment]
Is that the entire output? Is there a stack trace?

**Comment by glasser** [comment]
In what environment (version of Node or otherwise) are you trying this?

**Comment by alexbjorlig** [comment]
I'm using node v14. I just realized that the error only occurs, when using: 

```
ApolloServerPluginSchemaReporting({
    initialDelayMaxMs: 30 * 1000,
})
```

Is this option not supported - according to this [article](https://www.apollographql.com/docs/apollo-server/api/plugin/schema-reporting/)?

**Comment by glasser** [comment]
That seems odd; all that option does it change a default from 10000.

Can you share a reproduction recipe — a series of instructions (probably starting with `git clone` or using codesandbox.io or something) that demonstrates this?

crypto.getRandomValues() is in fact only in Node 15+... but we also don't use it directly in Apollo Server. As Jesse said, is there a stack trace?

I'll be happy to reopen this issue once it contains a way for us to see the problem ourselves, or at least a full transcript of all output.

**Comment by glasser** [comment]
Also, can you share what version of `uuid` is installed? Though that would be easier with a full reproduction that lets me look at your package-lock.json.
