### ISSUE TITLE
Support for Fastify 3

### ISSUE THREAD

**Issue by StarpTech** [apollographql/apollo-server#5139]
Hi, the current plugin doesn't support fastify 3.

Reproduction: Follow https://github.com/apollographql/apollo-server/tree/main/packages/apollo-server-fastify

On server start:

```
 (node:18586) [FSTDEP003] FastifyDeprecation: You are using the legacy Content Type Parser function signature. Use the one suggested in the documentation instead.
(Use `node --trace-warnings ...` to show where the warning was created)
🚀 Server ready at http://localhost:4000/graphql
(node:18586) [FSTDEP001] FastifyDeprecation: You are accessing the Node.js core request object via "request.req", Use "request.raw" instead.
```

Response when calling the playground: `GET query missing.`

There are some open issues but it looks like that there is no progress. What's the current status?

Related: https://github.com/apollographql/apollo-server/pull/4356, https://github.com/apollographql/apollo-server/issues/4463

**Comment by glasser** [comment]
This is fixed on the `release-3.0` branch. Apollo Server 3.0 is now under active development; I hope to get some alphas out within a week.

**Comment by StarpTech** [comment]
Could you point to the test?

**Comment by JanVoracek** [comment]
Hi @glasser, did you consider adding `"fastify": "^2"` as a peer dependency of `apollo-server-fastify`? It would save a lot of time spent trying to figure out why it doesn't work after upgrading the project's dependencies.

**Comment by StarpTech** [comment]
I hope you mean `^3`?

**Comment by glasser** [comment]
That makes sense. I want to make sure I understand the choices we've made in our existing integration libraries about deps vs peer deps.
