### ISSUE TITLE
CORS does not allow * wildcard with current apollo graphiql implementation

### ISSUE THREAD

**Issue by diit** [apollographql/apollo-server#514]
## Expected:
- Setup GraphQL endpoint with cors (default express setup)
- Setup GraphiQL (default setup)
- Allows querying

## Actual:
- Throws `Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin '<location>' is therefore not allowed access.`

Cause: https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-module-graphiql/src/renderGraphiQL.ts#L147

**Comment by stubailo** [comment]
Ooh, hmm.

Should we switch the default credentials to `same-origin`?

**Comment by diit** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials

CORS is not my strong suit but that appears to be the correct option.

**Comment by stubailo** [comment]
Oh I mean on the GraphiQL side - we can change the way it sends the cookies to avoid the error. We can replace `include` with `same-origin`

**Comment by stubailo** [comment]
Awesome - mind sending a PR for that?

**Comment by diit** [comment]
Can we get a feature bump on this so it can be used?

**Comment by evenfrost** [comment]
Seems to be solved in [`v.1.1.6`](https://github.com/apollographql/apollo-server/blob/df51fd90dad90c9468a74e2c4ec2a6af69f4188d/CHANGELOG.md#v116).

**Comment by stubailo** [comment]
Thanks!
