### ISSUE TITLE
Update Playground dependency to fix subscription results not being scrollable

### ISSUE THREAD

**Issue by puchm** [apollographql/apollo-server#5145]
Apollo Server 2.22.1

##  Behavior
When receiving multiple messages while you are subscribed to a query, the result list should be scrollable. This is however not the case since it is leaving the oldest events at the top and making the user unable to view the latest updates.

## Reproduction
Just use any Apollo GraphQL server that has subscriptions. An example would be the example sandbox linked in the official [subscriptions docs](https://www.apollographql.com/docs/apollo-server/data/subscriptions/): 
https://codesandbox.io/s/github/apollographql/docs-examples/tree/main/server-subscriptions

## Solution
As described in graphql/graphql-playground#1021, this should be resolved by updating the GraphQL playground dependency.

**Comment by glasser** [comment]
Thanks. We haven't kept our fork as up to date as would be ideal. I've cherry-picked that change and released `@apollographql/graphql-playground-react@1.7.40`. I'll make sure it's the default playground version in Apollo Server 3 (where I'm currently generalizing our Playground support); to get it in your app now you can pass `new ApolloServer({playground: {version: '1.7.40'}})`.
