### ISSUE TITLE
Plugins should be initialized sequentially (i.e. calling serverWillStart sequentially)

### ISSUE THREAD

**Issue by jeanbmar** [apollographql/apollo-server#5146]
The current plugin system won't work if 2 plugins are dependent because serverWillStart calls are launched in parallel.

https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-core/src/ApolloServer.ts#L557
```js
await Promise.all(
    this.plugins.map(
        (plugin) =>
            plugin.serverWillStart && plugin.serverWillStart(service),
    ),
)
``` 

For instance, I have a generic plugin `A` pulling data from AWS S3, and another generic plugin `B` loading JSON files in memory.
I had to write an ugly wrapper plugin to make sure B is waiting for A to finish, but it's not a good solution since all the events system is messed up.
On the other hand, I can't see a drawback running serverWillStart sequentially.

Thanks for your work btw :).

**Comment by glasser** [comment]
async serverWillStart plugins may need to do IO/network work. I think in most cases it's better if those things can happen in parallel for a faster startup.

If you need to order your plugins (which seems like a rarer case), there are several solutions. As you suggest, you can write a wrapper plugin. You can also just make one wait on the other to finish. I've found the little package `@josephg/resolvable` helpful for these sort of "barrier" situations though it works with normal Promises too.

```
import resolvable from '@josephg/resolvable';

const barrier = resolvable();

new ApolloServer({
  plugins: [FirstPlugin({resolveWhenDone: resolvable}), SecondPlugin({waitFor: resolvable})],
})

function FirstPlugin({resolveWhenDone}) {
  return {
    async serverWillStart() {
      doStuff();
      resolveWhenDone.resolver();
    }
  };
}

function FirstPlugin({waitFor}) {
  return {
    async serverWillStart() {
      await waitFor;
      doMoreStuff();
    }
  };
}
```
