### ISSUE TITLE
Improving the documentation: Using subscriptions with koa

### ISSUE THREAD

**Issue by istomyang** [apollographql/apollo-server#5160]
# Improving the documentation: Using subscriptions with koa
## package name and version
`"apollo-server-koa": "^2.24.0"`

## The expected behavior
this example comes from [apollo_graphql_document/subscriptions/Using_with_middleware_integrations](https://www.apollographql.com/docs/apollo-server/data/subscriptions/#using-with-middleware-integrations)
~~~js
const http = require('http');
const { ApolloServer } = require('apollo-server-koa');
const express = require('express');

async function startApolloServer() {
  const PORT = 4000;
  const app = new koa();
  const server = new ApolloServer({ typeDefs, resolvers });
  await server.start();
  server.applyMiddleware({app})

  const httpServer = http.createServer(app);
  server.installSubscriptionHandlers(httpServer);

  // Make sure to call listen on httpServer, NOT on app.
  await new Promise(resolve => httpServer.listen(PORT, resolve));
  console.log(`🚀 Server ready at http://localhost:${PORT}${server.graphqlPath}`);
  console.log(`🚀 Subscriptions ready at ws://localhost:${PORT}${server.subscriptionsPath}`);
  return { server, app, httpServer };
}
~~~
It should works!

## The actual behavior.
But it doesn't work! Can't connect ws server.

## Solution
I reviewed koa source code, and got the solution. Just change the line here:
` const httpServer = http.createServer(app.callback()); `

**Please insert this  code line String into that line above.**

**Comment by glasser** [comment]
We are removing the superficial integration between `subscriptions-transport-ws` and Apollo Server in AS3. We will be documenting some common ways to set up subscriptions with popular GraphQL subscription libraries instead.

**Comment by Oxyaction** [comment]
thanks @istomyang !

@glasser 
can you mention it in `packages/apollo-server-koa/README.md`?

**Comment by hryjosn** [comment]
Thanks @istomyang !
You save my day.

**Comment by glasser** [comment]
That README links to our [main docs site](https://www.apollographql.com/docs/apollo-server/) which has a Subscriptions page in the left sidebar.
