### ISSUE TITLE
Add capability to terminate an in-progress query

### ISSUE THREAD

**Issue by StephenBarlow** [apollographql/apollo-server#5221]
As inquired about in the Apollo forums: https://community.apollographql.com/t/server-request-cancellation

If a querying client terminates its connection before the server finishes resolving the query, it might be helpful to be able to end resolution early, especially for more expensive queries.

**Comment by yaacovCR** [comment]
Looking @glasser issue upstream at graphql js https://github.com/graphql/graphql-js/issues/3764

**Comment by glasser** [comment]
I don't think there's much for us to do here until https://github.com/graphql/graphql-js/issues/3764 is fixed (which we could contribute to); once there's an API that can be used, we can reopen an issue about integrating properly with the new API.
