### ISSUE TITLE
Non-nullable mutation payloads prevent partial responses from multiple mutations

### ISSUE THREAD

**Issue by atkinchris** [apollographql/apollo-server#5225]
When executing a query that includes multiple mutations, if these mutations have non-nullable payloads, any errors will return `null` for the whole `data` object. If the mutation payloads are nullable, `null` will be confined to the mutation that errored.

## Reproducible Example

https://github.com/atkinchris/apollo-server-nullable-issue

```sh
git clone https://github.com/atkinchris/apollo-server-nullable-issue.git
cd apollo-server-nullable-issue
npm install
npm run test
```

Observe that the "non-nullable - with errors" test fails

## Example Server

```js
const { ApolloServer, gql } = require("apollo-server");

const typeDefs = gql`
  type Book {
    title: String
  }

  type Query {
    books: [Book]
  }

  type Mutation {
    nullable(throwError: Boolean): Book
    nonNullable(throwError: Boolean): Book!
  }
`;

const mutation = (_, { throwError }) => {
  if (throwError) throw Error("Error!!!");
  return { title: "A book" };
};

const resolvers = {
  Query: {
    books: [],
  },
  Mutation: {
    nullable: mutation,
    nonNullable: mutation,
  },
};

module.exports = new ApolloServer({ typeDefs, resolvers });
```

## As expected: Nullable Payload Behaviour

Given the example server and the following query

```gql
mutation {
  mutation1: nullable(throwError: false) {
    title
  }
  mutation2: nullable(throwError: true) {
    title
  }
}
```

The returned `data` is as expected:

```json
{
  "mutation1": { "title": "A book" },
  "mutation2": null,
}
```

## Not as expected: Non-nullable Payload Behaviour

Given the example server and the following query

```gql
mutation {
  mutation1: nonNullable(throwError: false) {
    title
  }
  mutation2: nonNullable(throwError: true) {
    title
  }
}
```

I would expect the `data` to be:

```json
{
  "mutation1": { "title": "A book" },
  "mutation2": null,
}
```

But instead the whole `data` response is `null`.

```json
null
```

**Comment by glasser** [comment]
This is [spec-compliant GraphQL behavior](http://spec.graphql.org/draft/#sec-Handling-Field-Errors). There's nothing special about mutations or the fact that this is on the root of the query here. In general:
- if a field returns an error then its value becomes null.
- if a field's type is declared as non-nullable, then we will never return `null` for it; any null (eg from an error) gets propagated up a level.

**Comment by atkinchris** [comment]
Thanks - suspected it was deliberate, but thanks for providing context!
