### ISSUE TITLE
No docs for how to use graphql-uploads with node 14

### ISSUE THREAD

**Issue by terion-name** [apollographql/apollo-server#5230]
> To use file uploads with Node 14, you can disable built-in support by passing uploads: false to the ApolloServer constructor. You can then install and use the lastest version of graphql-upload directly (see the documentation).

This says absolutely nothing about how to do this, documentation over link also has no info of how to use it with ApolloServer.And it doesn't work just "as is". Even after some figuring out, code like this:

```js
let schema = makeExecutableSchema({
        typeDefs: mergeTypeDefs(['scalar Upload', ...scalarsTypeDefs, ...customTypes, app.typeDefs]),
        resolvers: mergeResolvers([{Upload}, scalarsResolvers, app.resolvers])
    });

    const server = new ApolloServer({
        schema,
        formatError,
        context: createContext,
        playground: true,
        introspection: true,
        uploads: false, // https://www.apollographql.com/docs/apollo-server/data/file-uploads/#uploads-in-node-14-and-later
    });

    await server.listen({port})
        .then(({url}) => {
            console.log(`🚀  Server ready at ${url}`);
        })
        .catch(() => {
            console.log('Failed to start server')
        });
```

Crashes on upload with `POST body missing. Did you forget use body-parser middleware?`

**Comment by spaghettiguru** [comment]
We are having the same issue

**Comment by glasser** [comment]
Those more detailed docs do currently exist on our release-3.0 branch: https://github.com/apollographql/apollo-server/blob/release-3.0/docs/source/data/file-uploads.md

(In AS3, the built-in integration with the ancient version of `graphql-upload` will be fully removed; to use those instructions with AS2, just add `uploads: false`.)

The main thing to note is that you'll have to move from the `apollo-server` "batteries included, no customization of HTTP functionality" package to a package such as `apollo-server-express` which lets you add other middleware.

I recognize it would be more helpful if these docs were already on the AS2 site but right now we're focused on getting AS3 out as soon as possible, so I'm going to close this.
