### ISSUE TITLE
Docs: Deploying to Lambda with CDK and SST

### ISSUE THREAD

**Issue by jayair** [apollographql/apollo-server#5235]
Hi all,

Appreciate all the hard work with Apollo!

I'm one of the creators of [SST](https://github.com/serverless-stack/serverless-stack), a framework for building serverless apps with [AWS CDK](https://aws.amazon.com/cdk/). We recently created a construct that makes it easy to deploy Apollo to Lambda — https://serverless-stack.com/examples/how-to-create-an-apollo-graphql-api-with-serverless.html. The added twist is that you can test and debug these live without having to redeploy to AWS. We have an example showing how to do this as well.

Would you be open to me submitting a PR adding an alternative to Serverless Framework for this doc — https://www.apollographql.com/docs/apollo-server/deployment/lambda/.

Let me know and I can submit one.

Thank you!

**Comment by glasser** [comment]
That's great to see!

I'm starting to feel a little concerned that continuing to add deployment guides to our docs section that document third-party software in detail may lead to out of date docs.  Would it make sense to add this as a link to your site rather than as instructions directly on our site?

**Comment by jayair** [comment]
Yeah I can see how keeping them up to date on your side could be an issue.

How about a link to our docs where we have the instructions and keep them updated? Something like:

> If you are looking to use CDK to deploy Apollo to Lambda, [follow these steps](link).

Hope that make sense!

**Comment by glasser** [comment]
That sounds good. Can you issue a PR against the release-3.0 branch? There have been some refactorings to the lambda page over there.

**Comment by jayair** [comment]
Just added it here https://github.com/apollographql/apollo-server/pull/5242

Let me know if you want the link moved elsewhere in the doc.
