### ISSUE TITLE
Update Apollo Authentication in Documentation

### ISSUE THREAD

**Issue by alanyong91** [apollographql/apollo-server#5252]
https://www.apollographql.com/docs/react/networking/authentication/

Currently this documentation only explain retrieve token from local storage. But what if we store in cookies instead of local storage. Seems like no way to retrieve token from cookies.  

---

https://www.apollographql.com/docs/apollo-server/security/authentication/

Secondly, I found `apollo-server` (or other similar packages like `apollo-server-micro` and `apollo-server-express`) quite troublesome when I tried to retrieve cookies from `req.cookies` which it return an empty object. 

I tried to retrieve cookies with nextjs. I googled this issues but many people are facing this problem. That would be great if someone can update the documentation.

**Comment by glasser** [comment]
The first link is about the client docs, so is best asked at https://github.com/apollographql/apollo-client/ or at https://community.apollographql.com/

For your concern about reading cookies in the server, apollo-server does nothing special with respect to cookies. If you'd like to read cookies, I suggest you use `apollo-server-express` and install the [`cookie-parser` middleware](https://www.npmjs.com/package/cookie-parser) before installing the Apollo Server middleware. That should set up `req.cookies` for you.
