### ISSUE TITLE
[apollo-server-fastify] fastify.inject

### ISSUE THREAD

**Issue by blueyestar** [apollographql/apollo-server#5272]
Testing with fastify.inject will get an error.

### Versions:
fastify: 3.14.1
apollo-server-fastify: 3.0.0-alpha.4

### Expected behavior:
Should be able to test with fastify.inject

### Actual behavior:
Get an error

```
Error: You must `await server.start()` before calling `server.createHandler()`
    at ApolloServer.assertStarted (...\node_modules\apollo-server-core\dist\ApolloServer.js:242:19)
    at ApolloServer.createHandler (..\node_modules\apollo-server-fastify\dist\ApolloServer.js:24:14)
```
### Example
```
/** app.js **/

const { ApolloServer, gql } = require('apollo-server-fastify');
const { typeDefs, resolvers } = require('./module');

const server = new ApolloServer({
  typeDefs,
  resolvers,
});

const app = require('fastify')();

module.exports = app

```
```
/*test.js*/

'use strict'

const build = require('./app')

const test = async () => {
  const app = build()

  const response = await app.inject({
    method: 'GET',
    url: '/'
  })

  console.log('status code: ', response.statusCode)
  console.log('body: ', response.body)
}
test()
```

**Comment by tkow** [comment]
Maybe it is related to https://github.com/apollographql/apollo-server/issues/5278.

**Comment by StarpTech** [comment]
We use it successfully. As the error states. You have to start the server before calling `createHandler()`

Example:

```js
const { ApolloServer, gql } = require('apollo-server-fastify');
const { typeDefs, resolvers } = require('./module');

const server = new ApolloServer({
  typeDefs,
  resolvers,
});

const app = require('fastify')();

(async function () {
  await server.start();
  app.register(server.createHandler());
  await app.listen(3000);
})();
```

**Comment by blueyestar** [comment]
The benefits of using fastify.inject is you do not need to start the server, and able to make fake http request.

https://www.fastify.io/docs/latest/Testing/

**Comment by StarpTech** [comment]
Then don't start the server and use inject. It was just an example.

**Comment by blueyestar** [comment]
@StarpTech then following error is given
```
You must `await server.start()` before calling `server.createHandler()`
```

**Comment by StarpTech** [comment]
Could you post a fully reproducible example? As zip or repository link.

**Comment by glasser** [comment]
There's a distinction between "starting Apollo Server" (making sure the schema has loaded, invoking `serverWillStart` on plugins, etc) and "having your web server listen". With Apollo Server 3, you absolutely have to start your server before you can start running GraphQL operations. That doesn't mean you have to hook it up to an HTTP listener.

Note that this requirement is new in AS3, which is still in preview. (I understand that Fastify users are using the preview versions because AS2 doesn't support recent versions of Fastify.)
