### ISSUE TITLE
support for graphql 0.11.1

### ISSUE THREAD

**Issue by klauszhang** [apollographql/apollo-server#529]
It is pretty new... but when I install graphql 0.11.1 and I got this error message:
```
Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.
```
it works all good with 0.10.5.

Thanks

**Comment by dobesv** [comment]
I fixed this issue myself by also updating graphql-tools to the latest version.

**Comment by klauszhang** [comment]
@dobesv I tried `graphql-tools@next` still no luck..

**Comment by dobesv** [comment]
Oh yes, you are right, that was what fixed it for me with `0.10.5`.  It looks like apollo has a dependency on `0.10.5` and if you install `0.11.1` the `apollo-server` gets its own copy of the older version, and `instanceof` takes the file path into account.

**Comment by dobesv** [comment]
I think we have to wait for a new release of apollo that has the new version of GraphQL as a dependency.

**Comment by strues** [comment]
Any chance of a new release with peerDependencies updated to `0.11.x`? I see the `  "@types/graphql": "0.11.1"` reflects the latest version.

**Comment by wmertens** [comment]
does it work with 0.11? There was a [breaking change](https://github.com/graphql/graphql-js/releases/tag/v0.11.0), `subscribe()` now returns a Promise

**Comment by janhartmann** [comment]
Can confirm, that apollo-server-express is not compatible with the 0.11.3 of graphql. Look forward to a new version!

**Comment by spencerhakim** [comment]
Tagging @stubailo @martijnwalraven since they seem to have been the ones who did the last several releases.

**Comment by Panoplos** [comment]
Badly needed, or I cannot update anything to `graphql@0.11.x`.

**Comment by wmertens** [comment]
I think the point has been made, no need to keep spamming this issue if you're not going to provide solutions.

**Comment by martijnwalraven** [comment]
I'll be taking a look at it today.

**Comment by kbrandwijk** [comment]
I seem to be having the same issue with `graphql@0.11.7` and `apollo-server-express@1.2.0`
