### ISSUE TITLE
Batched requests' mutations should be executed serially?

### ISSUE THREAD

**Issue by Z3roCoder** [apollographql/apollo-server#531]
Hello!

Upon discussing with our Senior Developer about a problem we are having right now, I now want to ask about your opinion, and possibly propose a Pull Request for an Issue we are having.

At the moment, the function `httpRunQuery` in the file `apollo-server/master/packages/apollo-server-core/src/runHttpQuery.ts` maps through all payloads (Line Nr.73), creates promises and then calls Promise.all(requests), executing all in parallel.

Now we have the problem that we need to execute mutations that will not be waited on to finish to modify data in the background (Specifially, logging of user interactions). Now when a user speeds up his clicking, several of these mutations get shoved into a payload and sent off to the server. Then, all of these payloads will be executed at once, causing problems with caching and saving data to/from the database.

Now, our proposal would be the following:

Instead of mapping through all of the payloads, it might be possible to check wether the operation is a mutation or not, and only execute the mutations serially, while the queries are left beeing executed in parallel. This would still mean through that the newly resulting requests array should still be in the same order as before, but now the mutations are executed one by one, causing a more consistent workflow overall.

I will be happy to provide a pull request should this find any consensus from core developers.

**Comment by jbaxleyiii** [comment]
@Z3roCoder the batching order isn't a guaranteed order so mutation executed in batch will all run in parallel aside from an ordered serial list of mutations. I would recommend not batching with mutations on the client
