### ISSUE TITLE
Strict type versions in apollo-server-express require update

### ISSUE THREAD

**Issue by electerious** [apollographql/apollo-server#5350]
`apollo-server-express` strictly uses `@types/express` in version `4.17.11` and `@types/express-serve-static-core` in version `4.17.19`. Both should either be updated to `4.17.12` and `4.17.21` or they should not strictly use outdated versions (`^4.17.11` and `^4.17.19`). The new versions are containing a fix for the following TS errors:

```
../../node_modules/.pnpm/@types+express-serve-static-core@4.17.19/node_modules/@types/express-serve-static-core/index.d.ts:589:18 - error TS2430: Interface 'Response<ResBody, Locals, StatusCode>' incorrectly extends interface 'ServerResponse'.
  Property 'req' is optional in type 'Response<ResBody, Locals, StatusCode>' but required in type 'ServerResponse'.

589 export interface Response<
                     ~~~~~~~~

../../node_modules/.pnpm/@types+express@4.17.11/node_modules/@types/express/index.d.ts:58:55 - error TS2344: Type 'Response<any, Record<string, any>>' does not satisfy the constraint 'ServerResponse'.
  Property 'req' is optional in type 'Response<any, Record<string, any>>' but required in type 'ServerResponse'.

58     var static: serveStatic.RequestHandlerConstructor<Response>;
                                                         ~~~~~~~~
```

Here are the specified versions in the `package.json`:

https://github.com/apollographql/apollo-server/blob/6b9c2a0f1932e6d8fb94a8662cc1da24980aec6f/packages/apollo-server-express/package.json#L34-L35

Related:

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46639#issuecomment-858857876
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52775

**Comment by glasser** [comment]
This is [fixed on the active development branch, `release-3.0`](https://github.com/apollographql/apollo-server/blob/release-3.0/packages/apollo-server-express/package.json). We are currently working on finalizing that release and are not as focused on AS2 now.

Is there any workaround here? These versions do work with each other; is the problem some conflict with a third party package? If there's no workaround I can spend some time on a patch release today.

**Comment by charles-hill-exelon** [comment]
@glasser I've spent the past hour trying different package versions, including rolling back a minor version or two.  And, haven't gotten past this error.

**Comment by glasser** [comment]
Ok, see if 2.25.2 makes you happier!

**Comment by charles-hill-exelon** [comment]
That solved it.  Thanks!!

P.S. I did find a brute-force workaround using npm-force-resolutions.  But that will force the same version on all instances of the nested dependency, which may break other stuff.
