### ISSUE TITLE
Error or warning on plugin hooks problems

### ISSUE THREAD

**Issue by migsar** [apollographql/apollo-server#5351]
I am writing a plugin with version Apollo Server 2.25.0.

I was using an `async requestDidStart` handler that returned a `willSendResponse` handler, there was no error or warning in the logs/console but code inside `willSendResponse` was not running, after a while I realize the problem was the `async` part. I would like to have better feedback when writing the plugin.

I did not want to open this as a bug, because I am not sure if it is, probably it is somewhat obvious for someone more experienced. I think some error or a more verbose or visible message if there is any would be great. I am happy to contribute if possible, but first I would like to know if this makes sense or I am missing something? Could it be a PR to improve documentation or a code PR to send feedback to the developer?

**Comment by glasser** [comment]
In Apollo Server 3 (the version under active development), all plugin hooks (except `willResolveField`) are `async`. See https://github.com/apollographql/apollo-server/pull/5295

I think this resolves your concern?
