### ISSUE TITLE
Update doc version branches for 3.x as latest

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#5364]
Currently, main publishes v2 docs linking to v1 in `version-1`, and `release-3.0` publishes v3 docs linking to v2 in `main`.

After we merge, we should start a `version-2` branch and change main to link to v2 there.

**Comment by StephenBarlow** [comment]
(and also change the default docset to point to `main`)

**Comment by glasser** [comment]
Also drop the one landing-pages -> v3 redirect from `_redirects`

**Comment by glasser** [comment]
@StephenBarlow Do you remember what you meant by "default docset" in your comment above?
