### ISSUE TITLE
Response not successful: Received status code 500 only after adding dataSources to ApolloServer

### ISSUE THREAD

**Issue by sahoosumit** [apollographql/apollo-server#5379]
--> After Adding  dataSources i am facing this issue.Please any one help me on this. 
--> Below i added .babelrc and package.json and ApolloServer conf

.babelrc
-------------
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-function-bind",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    "@babel/plugin-transform-runtime",
    [
      "@babel/plugin-proposal-class-properties"
    ],
    "@babel/plugin-proposal-json-strings",
    [
      "@babel/plugin-proposal-private-methods"
    ]
  ]
}

package.json
-----------------
{
  "version": "0.1.0",
  "description": "",
  "main": "./src/server.js",
  "scripts": {
    "start": "NODE_ENV=dev nodemon --max-old-space-size=4096 ./src/server.js --exec babel-node -e js",
    "prodStart": "NODE_ENV=production nodemon ./src/server.js --exec babel-node -e js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "devDependencies": {
    "@babel/cli": "^7.14.5",
    "@babel/core": "^7.4.0",
    "@babel/node": "^7.0.0",
    "@babel/plugin-proposal-async-generator-functions": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-function-bind": "^7.0.0",
    "@babel/plugin-proposal-json-strings": "^7.0.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/plugin-proposal-private-methods": "^7.4.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-syntax-import-meta": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/polyfill": "^7.12.1",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-react": "^7.11.4",
    "babel-loader": "v8.0.0-beta.0",
    "babel-plugin-import": "^1.13.3",
    "cors": "^2.8.4",
    "node-fetch": "^1.7.3",
    "nodemon": "^1.18.4"
  },
  "dependencies": {
    "@babel/runtime": "^7.14.6",
    "@google-cloud/bigquery": "^4.4.0",
    "apollo-datasource": "^0.6.3",
    "apollo-datasource-rest": "^0.10.0",
    "apollo-datasource-soap": "^1.2.4",
    "apollo-engine": "^0.8.1",
    "apollo-server": "^2.6.4",
    "apollo-server-express": "^2.6.4",
    "babel-core": "^7.0.0-bridge.0",
    "casual": "^1.5.17",
    "compression": "^1.7.1",
    "cookie-parser": "1.4.0",
    "express": "^4.17.1",
    "google-play-scraper": "^7.0.4",
    "graphql": "^14.4.1",
    "graphql-redis-subscriptions": "^2.1.1",
    "graphql-subscriptions": "^1.1.0",
    "graphql-type-json": "^0.3.0",
    "lodash": "^4.17.4",
    "mongoose": "^4.13.2",
    "node-fetch": "^1.7.3",
    "pg": "^7.12.1",
    "pg-pool": "^2.0.7",
    "regenerator-runtime": "^0.11.1",
    "sequelize": "^4.28.2",
    "uuid": "^3.3.3",
    "webtask-tools": "^3.2.0"
  }
}

ApolloServer
-------------------

const server = new ApolloServer({
    typeDefs: [typeDefs],
    resolvers: resolvers,
    dataSources: () => {
    return {
        SOAPAPI: new SOAPAPI()
    };
},
context: ({req, res}) => ({
    headers: (req != undefined) ? req.headers : req,
    secrets: process.env
}), subscriptions: {
    keepAlive: 1000,
        onConnect: async (
        websocket,
        context
    ) => {
        // Handling connection context here
    },
    onDisconnect: (websocket, context) => {
        console.log("WS Disconnected! -> ", JSON.stringify(context));
    },
},
tracing: true,
    cacheControl: true,
    playground: (conf.gateway_restriction === "ALLOW") ? true : false,
    introspection: true
});

**Comment by glasser** [comment]
Hi. While you've shared a lot of code here, it's not nearly enough for me to be able to reproduce your issue (or understand what the problem even is) without a lot of creativity. I'm happy to reopen this issue if you provide a full reproduction: an explicit series of steps leading to seeing the bug. A good reproduction often starts with `git clone` or uses codesandbox.io.
