### ISSUE TITLE
Cloning the context fails if the request has the ip in runHttpQuery.cloneObject

### ISSUE THREAD

**Issue by repl-shenoy-sukumaran** [apollographql/apollo-server#5397]
- [x] A short, but descriptive title. The title doesn't need "Apollo" in it.
- [x] The package name and version of Apollo showing the problem.
   - We are running appllo server on aws lambda via @vendia/serverless-express": "^4.3.4 apollo-server-express": "^2.19.1"
- [x] If applicable, the last version of Apollo where the problem did _not_ occur.
- We can reproduce in all versions
- [x] The expected behavior.
  -  Basically the introspect query request should not fail

- [x] The actual behavior.
  - The introspect query fails with below exception
  - {"errors":[{"message":"Cannot set property ip of #<IncomingMessage> which has only a getter","extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError: Cannot set property ip of #<IncomingMessage> which has only a getter","    at Function.assign (<anonymous>)","    at cloneObject (/var/task/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/runHttpQuery.js:271:19)","    at buildRequestContext (/var/task/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/runHttpQuery.js:121:29)","    at /var/task/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/runHttpQuery.js:163:44","    at Generator.next (<anonymous>)","    at /var/task/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/runHttpQuery.js:8:71","    at new Promise (<anonymous>)","    at __awaiter (/var/task/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/runHttpQuery.js:4:12)","    at processHTTPRequest (/var/task/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/runHttpQuery.js:99:12)","    at Object.<anonymous> (/var/task/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/runHttpQuery.js:94:16)"]}}}]}

- [x] A **simple**, runnable reproduction!
      Please make a GitHub repository that anyone can clone and run and see the
      problem. Other great ways to demonstrate a reproduction are using our
      CodeSandbox template (https://codesandbox.io/s/apollo-server), or re-mixing
      our Glitch template (https://glitch.com/~apollo-launchpad).

This issue occurs only if you run inside a AWS lambda,

![image](https://user-images.githubusercontent.com/13564819/124062637-ab3ae500-da4e-11eb-9f55-9d22ade30bdb.png)

**Comment by repl-shenoy-sukumaran** [comment]
If you change the cloneObject as below its solves the problem

```
function cloneObject(object) {
    return Object.assign({}, object);
}
```

**Comment by glasser** [comment]
I'm not sure I follow. The only thing being cloned here is the `context` object, which is something that you determine for yourself in your server. Can you show a complete reproduction (ie, something I can try for myself with `git clone` or codesandbox or something — happy to deploy to lambda if that helps if it's just following the instructions in the AS lambda docs, say)?

Also note that apollo-server-lambda has been completely rewritten (to use `@vendia/serverless-express`!) in Apollo Server 3, which is in release candidate state right now. I'd suggest you try using AS3 and see if you can reproduce.

Install the RC with `npm install apollo-server-lambda@rc`.

V3 Lambda tutorial: https://www.apollographql.com/docs/apollo-server/v3/deployment/lambda/
V3 migration section about Lambda: https://www.apollographql.com/docs/apollo-server/v3/migration/#apollo-server-lambda

Hopefully the way we integration `@vendia/serverless-express` addresses the issue?

If you can provide a full reproduction I'm happy to reopen.

**Comment by repl-shenoy-sukumaran** [comment]
This issue occurs only if you run inside a AWS lambda, with API Gateway

Code Sandbox:
Just deploy below code in AWS with API Gateway V2
https://codesandbox.io/s/bitter-mountain-4my2f?file=/index.js

**Comment by glasser** [comment]
That repo uses Apollo Server 2. Please let me know if you can reproduce with AS3 as mentioned in my previous comment!

**Comment by repl-shenoy-sukumaran** [comment]
Its **works** with apollo-server-lambda@3.0.0 thank you very much @glasser 

https://codesandbox.io/s/old-frog-slyl0?file=/package.json

**Comment by repl-shenoy-sukumaran** [comment]
Does still make sense to fix the shaallow clone in v2? @glasser 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptors#creating_a_shallow_clone

**Comment by glasser** [comment]
Right now we're fully focused on Apollo Server 3! We might put out backports to AS2 but mostly just for security and for things that make it easier to upgrade.

**Comment by SamMcKay** [comment]
Any work on this issue?
I'm receiving the same error as above using version 3 of apollo-server.

"@vendia/serverless-express": "^4.3.11",
"apollo-server-express": "^3.3.0"
