### ISSUE TITLE
Hot schema reload with Apollo server: schemaDirectives not work

### ISSUE THREAD

**Issue by rickgong** [apollographql/apollo-server#5414]
When i create ApolloServer instance with specified **schemaDirectives** and typeDefs,  Directive works fine.

```
 _createApolloServer = function (defaultSchema) {
        return new ApolloServer({
            typeDefs: graphql_parse(defaultSchema),
            schemaDirectives: {
                spy: MyDemoDirective
            },
        });
    };
```

However, when schema hot reloaded,  the directive MyDemoDirective no longger triggered.
I use this solution to hot reload schema:  https://github.com/apollographql/apollo-server/issues/1275

```
const schemaDerivedData = this.apolloServer.generateSchemaDerivedData(schema);
lodash_set(this.apolloServer, 'state.schemaDerivedData', schemaDerivedData);
```

The schema does reloaded successfully,  new schema has the exactly same directive.  But the directive does not take effect anymore. 

Could anyone have a clue please?

```
  "dependencies": {
    "graphql": "15.5.0",
    "apollo-server": "2.24.1",
    "@apollo/gateway": "0.28.1",
    "@apollo/federation": "0.25.0",
    "properties-reader": "2.2.0",
    "graphql-tools": "7.0.5",
    "lodash": "4.17.21",
    "apollo-server-express": "2.24.1",
    "jsonwebtoken": "8.5.1",
    "axios": "0.21.1"
  }
```

**Comment by glasser** [comment]
schemaDerivedData is an internal field of ApolloServer; you shouldn't rely on it.  Additionally, a bunch of this stuff has been refactored in Apollo Server 3 which is about to be released (#5262). `schemaDirectives` is no longer built in to Apollo Server (https://www.apollographql.com/docs/apollo-server/v3/migration/#schemadirectives).
Additionally, this isn't a complete reproduction: I have to use a lot of creativity to make it work on my computer. A full reproduction typically starts with `git clone` or uses codesandbox.io.

If you can show a complete reproduction of this with Apollo Server 3, I'm happy to take another look.
