### ISSUE TITLE
Update engines range to support Node.js v16

### ISSUE THREAD

**Issue by setchy** [apollographql/apollo-server#5418]
The `apollo-gateway` "engines" range was updated a [few months back](https://github.com/apollographql/federation/commit/a834c193b3285fa2a24bd974bdb2ced2fe7336fe) to support Node.js v16

Can the same please be done for `apollo-server`.  Currently the "engines" range is `"node": ">=6 <15"`

**Comment by glasser** [comment]
That's fixed on `release-3.0`, right? Release candidate released yesterday, 3.0.0 expected next week.

We were unable to test AS2 with Node 16 because some dependencies like the Hapi web framework didn't support it; fortunately all these dependencies are finally upgraded for AS3.
