### ISSUE TITLE
RESTDataSource `resolveUrl` unexpectedly appends trailing slash when requesting root resource

### ISSUE THREAD

**Issue by camjackson** [apollographql/apollo-server#5422]
Package: `apollo-datasource-rest@0.14.0`

This is sort of similar to #3359. Here's a failing unit test:

```js

it('fails with urn-like resource', async () => {
  const dataSource = new (class extends RESTDataSource {
    // Note: no trailing slash in the baseURL:
    baseURL = 'https://api.example.com';

    getRoot() {
      // Note: no slash as part of the path here:
      return this.get('');
    }
  })();

  dataSource.httpCache = httpCache;

  fetch.mockJSONResponseOnce();

  await dataSource.getRoot();

  expect(fetch.mock.calls.length).toEqual(1);
  expect(fetch.mock.calls[0][0].url).toEqual('https://api.example.com');
});
```

The final assertion fails because the request URL was actually `'https://api.example.com/'`, with a trailing slash on the end.

The problem comes from [this line of code](https://github.com/apollographql/apollo-server/blob/main/packages/apollo-datasource-rest/src/RESTDataSource.ts#L83).

Unfortunately, I imagine that changing this behaviour would probably would be a breaking change. Some people might be relying on it (knowingly or otherwise) 😞

**Comment by glasser** [comment]
Huh. I'm not really sure if there is a difference between those two URLs as far as fetching is concerned. Don't they both turn into `GET /` in the HTTP request?  I recognize that trailing slashes after a non-trivial path affect the actual HTTP request, but does this slash actually have semantic effect?

**Comment by camjackson** [comment]
Maybe my example was too simplified. My real use-case is:

- `baseURL`: `api-gateway.example.com/api/my-app`
- Method call: `this.get('')`
- Desired final URL: `api-gateway.example.com/api/my-app`
- Actual final URL: `api-gateway.example.com/api/my-app/`

All of the APIs I will hit begin with `/api/my-app`, which is why I wanted that as the baseURL. The gateway that my requests go through gives me a 404 on the above URL with the trailing slash.

To work around it for now I've basically moved the `my-app` portion from the `baseURL` to the method call:

- `baseURL`: `api-gateway.example.com/api`
- Method call: `this.get('/my-app')`
- Final URL: `api-gateway.example.com/api/my-app`

**Comment by glasser** [comment]
Ah, that's quite different.

You're right that the default resolveURL implementation in RESTDataSource normalizes base URLs to end in a slash. You can override resolveURL in your RESTDataSource subclass if you'd like different behavior here. It might be reasonable for us to change what happens in the special case where path is empty, but that would be a backwards-incompatible change that could affect people with similarly finicky URLs.

**Comment by camjackson** [comment]
Yep, totally understand. Changing this behaviour would cause breakage for those who depend on the trailing slash being put there automatically.

Thanks for taking the time to reply. I'll look into overriding `resolveURL` if I really need to.
