### ISSUE TITLE
peerDependency misunderstanding 

### ISSUE THREAD

**Issue by derberg** [apollographql/apollo-server#544]
Hi, why graphql is in peerDependencies in https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-express/package.json

For now what I do, I add `"graphql": "^0.11.2"` to my dependencies in my project but never directly use the package, which is very confusing. What is the recommended flow of handling such dependency. I don't want to keep it in my package.json as it doesn't make sense.

What is your recommendation for apollo-server-express users

**Comment by martijnwalraven** [comment]
That is the expected usage. Apollo Server requires `graphql`, but there can only be a single copy of it installed in your app. Peer dependencies are the usual workaround for that in npm (which is why they're also used by React for that same purpose for example).
