### ISSUE TITLE
Global context (Async Local Storage)

### ISSUE THREAD

**Issue by A-Shleifman** [apollographql/apollo-server#5453]
The context Apollo Server exposes through resolvers is very convenient when using it within the same function, however, when more layers are added, passing `ctx` all around becomes messy.

Let's say we have a `tenantId` and `tenantName` that we extract from headers on every request. We need to pass them on to internal APIs down the line, but we have the following structure:

```
resolver.ts => service.ts => internalApiRequests.ts
```

Can we pass `ctx` down to the function that consumes it? - absolutely, is it clean? - no.

I tried writing an express middleware that would wrap `next()` in Node's `AsyncLocalStorage`, but it doesn't work for some reason. [This was brought up previously](https://github.com/apollographql/apollo-server/issues/2042) regarding a library that was trying to achieve the same goal.

Then I wrote a wrapper `withCtx` that wraps around resolvers and the context becomes available in all downstream functions, but I have to wrap every resolver manually.

Is there a way to make express middleware work? Alternatively, is there some kind of apollo middleware that would allow wrapping the rest of the request in an ALS?

Here is an example app using both `express middleware` and `withCtx` solutions.
https://codesandbox.io/s/recursing-joliot-c5ibz?file=/src/index.ts:599-611

**Comment by A-Shleifman** [comment]
Using `localStorage.enterWith` instead of `localStorage.run` does the trick:

```ts
app.use((req, res, next) => {
  // localStorage.run(context, next)) <-- this doesn't work
  localStorage.enterWith(context);

  next();
});
```

Full solution: https://codesandbox.io/s/pensive-beaver-7w88e

**Comment by ezekiel25-17** [comment]
Both `localStorage.enterWith` and `localStorage.run` work for me in `apollo-server-express@2.26.0`.

Same code from https://codesandbox.io/s/pensive-beaver-7w88e doesnt work in *3.0.0*
