### ISSUE TITLE
[apollo-server-express] Express should not be a peer dependency

### ISSUE THREAD

**Issue by MikaStark** [apollographql/apollo-server#5466]
Hello there :)
Since version 3, apollo-server-express declare express as a peer dependency. That's fine with npm 7 but when you are using npm 6 peer dependencies are not installed automatically. That's lead to this error when you just install apollo-server-express and graphql (see https://github.com/apollographql/apollo-server/tree/main/packages/apollo-server-express)

Error: Cannot find module 'express'
Require stack:
- /var/www/deploy/bo-weezchat-nodejs/releases/20210713_165658/node_modules/apollo-server-express/dist/ApolloServer.js
- /var/www/deploy/bo-weezchat-nodejs/releases/20210713_165658/node_modules/apollo-server-express/dist/index.js
- /var/www/deploy/bo-weezchat-nodejs/releases/20210713_165658/src/utils.ts
- /var/www/deploy/bo-weezchat-nodejs/releases/20210713_165658/src/types/Mutation.ts
- /var/www/deploy/bo-weezchat-nodejs/releases/20210713_165658/src/types/index.ts
- /var/www/deploy/bo-weezchat-nodejs/releases/20210713_165658/src/schema.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/var/www/deploy/bo-weezchat-nodejs/releases/20210713_165658/node_modules/apollo-server-express/src/ApolloServer.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)

So the possible solutions :
- Add express an @types/express installation in your tutorials
- Make express a dependency and NOT a peer dependency (just like in version 2 : https://github.com/apollographql/apollo-server/blob/apollo-server%402.9.16/packages/apollo-server-express/package.json)

**Comment by glasser** [comment]
If you're using `apollo-server-express` (rather than the batteries-included `apollo-server`) then it's because you're attaching your ApolloServer to your own express app, so shouldn't you already be directly depending on `express` in your own app?  Does your app not directly import/require `express`?

**Comment by glasser** [comment]
Ah, I see that you're mostly suggesting changing the docs. The main place we document `apollo-server-express` in the docs site is at https://www.apollographql.com/docs/apollo-server/integrations/middleware/#apollo-server-express and it recommends installing `express` directly.  Same at https://www.apollographql.com/docs/apollo-server/integrations/middleware/#swapping-out-apollo-server

Are there other parts of the docs that tell you how to use `apollo-server-express` that don't encourage installing `express` yourself?

**Comment by glasser** [comment]
(I'm closing this for now because I think the main docs do already do what you've requested, but happy to reopen if there are remaining concerns.)

**Comment by MikaStark** [comment]
Hello @glasser
I’m using express middleware version because of subscriptions. Since in version 3 they are not natively provided I had to switch to Apollo-server-express.
You are right the guide actually encourage to install your own express dependency. I accidentally skip the instruction that explain it. So this issue is useless.

**Comment by MikaStark** [comment]
For those who, like me, skip the guide read carefully this page https://www.apollographql.com/docs/apollo-server/integrations/middleware/#swapping-out-apollo-server
