### ISSUE TITLE
Fix subscriptions docs around context

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#5472]
We didn't properly update https://www.apollographql.com/docs/apollo-server/data/subscriptions/#operation-context for Apollo Server 3's lack of integrated subscriptions. The ApolloServer context function won't be called by your subscription server.

We should probably just document using onConnect to return the context for subscriptions. This also probably involves updating the description of onConnect and the migration guide.

**Comment by glasser** [comment]
Oops, referenced wrong issue in that commit.

**Comment by glasser** [comment]
specifically I think this:

> If onConnect returns an object, that object's fields are added to the WebSocket connection's context object. This is not the operation context that's passed between resolvers. However, you can transfer these values from the connection's context when you initialize operation context.

is also not true any more (I think this is about something that was in the integration code, and now the onConnect actually becomes the operation context)

**Comment by trevor-scheer** [comment]
> specifically I think this:
> 
> > If onConnect returns an object, that object's fields are added to the WebSocket connection's context object. This is not the operation context that's passed between resolvers. However, you can transfer these values from the connection's context when you initialize operation context.
> 
> is also not true any more (I think this is about something that was in the integration code, and now the onConnect actually becomes the operation context)

For some reason I never saw this, but I arrived at the same conclusion while validating my updates so that's good!

Closing this issue via https://github.com/apollographql/apollo-server/pull/5555
