### ISSUE TITLE
CORS Errors on Apollo Studio

### ISSUE THREAD

**Issue by machooper** [apollographql/apollo-server#5485]
When using the standard `apollo-server` library I receive 

```
Network error: unable to reach server

We couldn't reach your server.
The server's response may be missing CORS headers.
To verify, please open Developer Tools and check the console for any CORS related error messages, like “Cross Origin Request Blocked”.
If that is the case, contact your system administrator and add https://studio.apollographql.com to your server's allow-list.
Learn more about enabling CORS 
The server may be not reachable at the provided endpoint. Please double check your configured endpoint URL for typos.
Check the endpoint URL
Is the server currently running?
```

I have tried enabling and disabling cors in the server definition.

Can anyone help me figure out how to make this server accessible? 

```
// index.js
const {ApolloServer} = require('apollo-server')
const typeDefs = require('./schema')
const resolvers = require('./resolvers')
const models = require('./models')

const apollo = new ApolloServer({
  typeDefs,
  resolvers,
  context: {models}
})

apollo.listen().then(({url}) => console.log(`🚀 Server ready at ${url}`))

```

Thank you

**Comment by glasser** [comment]
What version of Apollo Server are you running?

Have you told Studio to send cookies?

When you have Studio open, can you open the developer console and see if there are any relevant errors there?

**Comment by machooper** [comment]
@glasser 

Most recent version `^3.0.0` in package.json

How would I tell Studio to send cookies?

There are relevant cookies 
![Screenshot 2021-07-15 at 19 09 50](https://user-images.githubusercontent.com/5686378/125840437-01940a01-6e93-4feb-b3aa-66a882a0a019.png)

**Comment by glasser** [comment]
What browser?

**Comment by machooper** [comment]
That's in Safari. I can try with Chrome

**Comment by glasser** [comment]
I think there are known issues using any hosted API client in Safari that needs to talk to http://localhost, which we should document better in Studio. I'm going to ask somebody from the Studio team to chime in here.

**Comment by machooper** [comment]
> I think there are known issues using any hosted API client in Safari that needs to talk to http://localhost, which we should document better in Studio. I'm going to ask somebody from the Studio team to chime in here.

No worries I'll give Chrome a go as soon

**Comment by Jephuff** [comment]
Unfortunately Safari will block http requests from https, we don't have a work around for this but Chrome should work! 
We are going to be updating the error in the UI to help communicate this and hopefully avoid future confusion :)

**Comment by glasser** [comment]
I'm going to close this as this is an issue with Studio, not Server, and there's not really much that can be done to resolve it other than improve the UI.

**Comment by PritishSawant** [comment]
Works on Firefox

**Comment by lohnsonok** [comment]
Just update apollo-server to latest version "3.0.2" and set this params. It working fine for me
`plugins: [
    process.env.NODE_ENV === 'production' ?
    ApolloServerPluginLandingPageLocalDefault({ footer: false }) :
    ApolloServerPluginLandingPageLocalDefault()
  ],`
