### ISSUE TITLE
Could not connect to websocket endpoint ws://localhost:4000/graphql. Please check if the endpoint url is correct.

### ISSUE THREAD

**Issue by jensysantana** [apollographql/apollo-server#5490]
Hi i having this issue in my backendserver:
and i can see this url: 🚀 Subscriptions ready at ws://localhost:4000undefined

const { ApolloServer } = require("apollo-server-express");
const { PrismaClient } = require('@prisma/client');
const { PubSub } = require('graphql-subscriptions');
import { createServer } from 'http';

import { makeExecutableSchema } from '@graphql-tools/schema';
import express from "express";
const {
    ApolloServerPluginLandingPageGraphQLPlayground,
    ApolloServerPluginLandingPageDisabled
} = require('apollo-server-core');
const typeDefs = require("./schema/graphqlSchema");
const { getUserId } = require("./utils");

const Query = require('./resolvers/Query');
const Mutation = require('./resolvers/Mutation');
const User = require('./resolvers/User');
const Link = require('./resolvers/Link');
const Subscription = require('./resolvers/Subscription');

(async function () {
    const app = express();
    const httpServer = createServer(app);

    const resolvers = {
        Query,
        Mutation,
        Subscription,
        User,
        Link,
    }
    const pubsub = new PubSub();
    const prisma = new PrismaClient();

    const schema = new makeExecutableSchema({ typeDefs, resolvers });
    const server = new ApolloServer({
        schema,
        subscriptions: {
            path: '/graphql',

            keepAlive: 9000,
            onConnect: (connParams, webSocket, context) => {
                console.log('CLIENT CONNECTED');
            },
            onDisconnect: (webSocket, context) => {
                console.log('CLIENT DISCONNECTED')
            }
        },
        plugins: [
            ApolloServerPluginLandingPageGraphQLPlayground(
                {
                    'some.setting': true,
                    'general.betaUpdates': false,
                    'editor.theme': 'dark',//as Theme
                    'editor.cursorShape': 'line',// as CursorShape
                    'editor.reuseHeaders': true,
                    'tracing.hideTracingResponse': true,
                    'queryPlan.hideQueryPlanResponse': true,
                    'editor.fontSize': 14,
                    'editor.fontFamily': `'Source Code Pro', 'Consolas', 'Inconsolata', 'Droid Sans Mono', 'Monaco', monospace`,
                    'request.credentials': 'omit',
                }
            ),
        ],
        context: ({ req }) => {
            return {
                ...req,
                prisma,
                pubsub,
                userId: req && req.headers.authorization ? getUserId(req) : null
            }
        }
    });

    const PORT = 4000;
    await server.start()
    server.applyMiddleware({ app });
    httpServer.listen(PORT, () => {
        console.log(`🚀 Server ready at http://localhost:${PORT}${server.graphqlPath}`)
        console.log(`🚀 Subscriptions ready at ws://localhost:${PORT}${server.subscriptionsPath}`)
    })

})();

**Comment by glasser** [comment]
What version of Apollo Server are you using? It looks like you are mixing and matching Apollo Server 2 and Apollo Server 3.  ApolloServerPluginLandingPageGraphQLPlayground is newly introduced in AS3, but the subscriptions option to `new ApolloServer` is removed in AS3. If you're using AS3, https://www.apollographql.com/docs/apollo-server/migration/ explains how to add a subscription server to your Express app directly.
