### ISSUE TITLE
`Cannot read property 'state' of undefined` on executeOperation 

### ISSUE THREAD

**Issue by robertu7** [apollographql/apollo-server#5493]
## Issue

After upgraded to Apollo Server 3.0, we followed the migration guide and use `executeOperation` in our test cases, but there are errors running them:

```
  ● manage tag › rename and delete tag

    TypeError: Cannot read property 'state' of undefined

      152 | }: PutTagInput) => {
      153 |   const { executeOperation } = await testClient({ isAdmin, isAuth, isMatty })
    > 154 |   const result = await executeOperation({
          |                        ^
      155 |     query: PUT_TAG,
      156 |     variables: { input: tag },
      157 |   })

      at executeOperation (node_modules/apollo-server-core/src/ApolloServer.ts:886:12)
      at Object.putTag (src/types/__test__/tag.test.ts:154:24)
      at Object.<anonymous> (src/types/__test__/tag.test.ts:226:26)
```

## How to reproduce?
You can check out [this PR](https://github.com/thematters/matters-server/pull/2148/). We [made a util method `testClient`](https://github.com/thematters/matters-server/pull/2148/files#diff-211d3bdc2a0c7456f21e007f29aed4b87219b27cde704e9e6ac436cff1471c50) that returns `server` from `new ApolloServer()`, then run query or mutation like:

```
  const { executeOperation } = await testClient({
    isAuth: true,
  })

  const result = await executeOperation({
    query: PUBLISH_ARTICLE,
    variables: { input },
  })
```

## What I have tired?
* Using or without using`await server.start()` before returning `server` on `testClient`;
* Import `ApolloServer` from different packages like `apollo-server`, `apollo-server-express` and `apollo-server-core`;

**Comment by robertu7** [comment]
I believe it's occurred by using object restructuring, which breaks the `this` binding. 

Fixed by changing:

```
  const { executeOperation } = await testClient({
    isAuth: true,
  })

  const result = await executeOperation({
    query: PUBLISH_ARTICLE,
    variables: { input },
  })
```

to:

```
  const server = await testClient({
    isAuth: true,
  })

  const result = await server.executeOperation({
    query: PUBLISH_ARTICLE,
    variables: { input },
  })
```

**Comment by glasser** [comment]
Yep, you diagnosed that correctly. I believe our [migration docs](https://www.apollographql.com/docs/apollo-server/migration/#apollo-server-testing) show it in a working state.
