### ISSUE TITLE
SubscriptionsPath is now undefined in "apollo-server-express": "3.0.0"

### ISSUE THREAD

**Issue by UglyHobbitFeet** [apollographql/apollo-server#5494]
const server = new ApolloServer({ schema });
console.log(server.graphqlPath); // Works as expected
console.log(server.subscriptionsPath); // Now is undefined, but worked in versions prior to 3.0.0

So, if this is now removed, what is the equivalent?

**Comment by glasser** [comment]
Full details about how to take Apollo Server 2's built-in subscription integration and replace it with your own subscription integration can be found in [the migration guide](https://www.apollographql.com/docs/apollo-server/migration/#subscriptions).
