### ISSUE TITLE
(docs) Migrating to AS3 Guide - add details re: Graph Refs

### ISSUE THREAD

**Issue by setchy** [apollographql/apollo-server#5500]
First off, the [Migration Guide](https://www.apollographql.com/docs/apollo-server/migration/) is an amazing asset - super thorough and immensely helpful.  Kudos to the team!

One item that I didn't find in the guide but had to change  whilst migrating to AS3 was replacing:
*  `graphVariant` -> `graphRef`
*  `APOLLO_GRAPH_VARIANT` -> `APOLLO_GRAPH_REF`

**Comment by glasser** [comment]
Thanks. There's definitely a missing section there: the change in AS3 is that we no longer infer your graph ID by the brittle mechanism of parsing the structure of your API key. So you can still set graphVariant but if you do so you need to also set graphId.   This is documented in [a](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#apollo) [few](https://www.apollographql.com/docs/apollo-server/api/plugin/usage-reporting/#default-installation) [places](https://www.apollographql.com/docs/apollo-server/monitoring/metrics/#connecting-to-apollo-studio) but not in the migration guide! Will fix.

**Comment by glasser** [comment]
See also https://github.com/apollographql/federation/pull/897
