### ISSUE TITLE
'POST body missing' when programmatically invoking graphql handler in v3

### ISSUE THREAD

**Issue by tiagocpeixoto** [apollographql/apollo-server#5504]
When I programmatically invoke the graphql handler of the example posted by @Alec2435 in #5462, I get the following error:

```json
{
    "body": "POST body missing, invalid Content-Type, or JSON object has no keys.", 
    "isBase64Encoded": false, 
    "multiValueHeaders":  {
        "access-control-allow-origin": ["*"], 
        "content-length": ["68"], 
        "content-type": ["text/html; charset=utf-8"], 
        "etag": ["W/\"44-LstwwwiSrcEeuZb+mu4TKVPIfxQ\""], 
        "x-powered-by": ["Express"]
    },
    "statusCode": 400
}
```

- [x] The package name and version of Apollo showing the problem.

I'm using "apollo-server-lambda" version 3.0.1.

- [x] The expected behavior.

That it executes as in v2.

- [x] The actual behavior.

It returns the message "POST body missing, invalid Content-Type, or JSON object has no keys.".

- [x] A **simple**, runnable reproduction!

I'm executing this code:

```javascript
   const event  = generateEvent({
            query: `
              query {
                hello
              }
            `,
        });
    const result = await graphqlHandler(event, {});
    expect(result.body).toEqual("{\"data\":{\"hello\":\"Hello world!\"}}\n");
```

Where the event is generated by:

```javascript

exports.generateEvent = body => ({
    body: body ? JSON.stringify(body) : null,
    headers: {
        "Accept": "application/json",
        "Content-Type": "application/json",
    },
    multiValueHeaders: {},
    httpMethod: "POST",
    isBase64Encoded: false,
    path: "/",
    pathParameters: null,
    queryStringParameters: null,
    multiValueQueryStringParameters: null,
    stageVariables: null,
    requestContext: {
        accountId: "1234567890",
        apiId: "appid",
        httpMethod: "POST",
        identity: {},
        authorizer: {},
        protocol: "HTTP/1.1",
        path: "/",
        stage: "dev",
        requestId: "test",
        requestTimeEpoch: 0,
        resourceId: "none",
        resourcePath: "/",
    },
    resource: "/",
});

```

Is it a bug or am I doing something wrong? In v2 it works perfectly!

_Originally posted by @tiagocpeixoto in https://github.com/apollographql/apollo-server/issues/5462#issuecomment-881956725_

**Comment by tiagocpeixoto** [comment]
Could it be related to this apollo-server-core code?

```javascript
export async function processHTTPRequest<TContext>(
  options: WithRequired<GraphQLOptions<TContext>, 'cache' | 'plugins'> & {
    context: TContext;
  },
  httpRequest: HttpQueryRequest,
): Promise<HttpQueryResponse> {
  let requestPayload;

  switch (httpRequest.method) {
    case 'POST':
      if (
        !httpRequest.query ||
        typeof httpRequest.query === 'string' ||
        Buffer.isBuffer(httpRequest.query) ||
        Object.keys(httpRequest.query).length === 0
      ) {
        throw new HttpQueryError(
          400,
          'POST body missing, invalid Content-Type, or JSON object has no keys.',
        );
      }

      requestPayload = httpRequest.query;
      break;
    case 'GET':
      if (!httpRequest.query || Object.keys(httpRequest.query).length === 0) {
        throw new HttpQueryError(400, 'GET query missing.');
      }

      requestPayload = httpRequest.query;
      break;

    default:
      throw new HttpQueryError(
        405,
        'Apollo Server supports only GET/POST requests.',
        false,
        {
          Allow: 'GET, POST',
        },
      );
  }
  ...
```

**Comment by tiagocpeixoto** [comment]
I created an [issue](https://github.com/vendia/serverless-express/issues/436) @ vendia/serverless-express to post the same question.

**Comment by glasser** [comment]
I believe you're trying to simulate an API Gateway message, like https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

`body` is a string in these messages, not parsed JSON.

The way this is supposed to work is that `apollo-server-lambda` wraps `apollo-server-express`, and `apollo-server-express` installs the `body-parser` middleware before doing its own processing.

Can you provide a complete reproduction where I can run your code myself (eg with `git clone` or codesandbox.io or something) so I can see why `body-parser` isn't running for you? WIthout understanding where `graphqlHandler` comes from, we're unable to help. Happy to reopen this if you provide more of a reproduction.

**Comment by tiagocpeixoto** [comment]
Ok, I made an example for reproduction located at https://github.com/tiagocpeixoto/apollo-serverless-bug based on the example from @Alec2435.

This version uses apollo-server-lambda v2. If you change it to version 3.0.1, it won't work.

**Comment by tiagocpeixoto** [comment]
Okay, finally got it after @glasser's mention about the body-parser. I analyzed the example I prepared and I found that the fake ApiGatewaryEvent shouldn't have the multiValueHeaders property set (it should be be null or undefined), because of this @vendia/serverless-express code: 

```javascript
  if (event.multiValueHeaders) {
    headers = getCommaDelimitedHeaders({ headersMap: event.multiValueHeaders, lowerCaseKey: true })
  } else {
    headers = event.headers
  }
```

The problem is that the APIGatewayEvent type of the "aws-lambda" package makes it mandatory, which led me to the error (I'm using Typescript in my project, althought I haven't used it in this example).

**Comment by glasser** [comment]
Ah, yes, specifying that there are no headers will make it think that the content-type is not set.

As mentioned in https://github.com/apollographql/apollo-server/issues/5415#issuecomment-879532648, I think it would best if:
- The Lambda docs explicitly listed the AWS HTTP-based services that `apollo-server-lambda` supports
- The Lambda docs show a *minimal* sample event in one of those formats that people who want to do direct execution can target with their event shape
- The `apollo-server-lambda` test suite explicitly tests that this minimal event works.

Perhaps somebody motivated can work out the event shape and send a PR for the docs? I can put together the test if somebody else does the docs. I'd suggest the newer API Gateway v2 format as the target.
