### ISSUE TITLE
Error: Cannot find module 'ts-tiny-invariant'

### ISSUE THREAD

**Issue by seawatts** [apollographql/apollo-server#5505]
I just upgraded to `apollo-server-core`: 3.0.1. When I deploy my code to AWS Lambda with [ESBuild](http://esbuild.github.io/) I get the following error

```
Error: Cannot find module 'ts-tiny-invariant'
Require stack:
- /var/task/index.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
```

I am creating a new server with `apollo-server-express` 

I'm not 100% sure but this might be caused by `ts-is-defined` being compiled with Typescript 3.x https://github.com/iyegoroff/ts-is-defined/blob/master/package.json#L40

The compiled code after ESBuild is the following for `ts-is-defined`

```
// node_modules/ts-is-defined/dist/umd/index.js
var require_umd2 = __commonJS({
  "node_modules/ts-is-defined/dist/umd/index.js"(exports2, module2) {
    var __importDefault = exports2 && exports2.__importDefault || function(mod) {
      return mod && mod.__esModule ? mod : { "default": mod };
    };
    (function(factory) {
      if (typeof module2 === "object" && typeof module2.exports === "object") {
        var v = factory(require, exports2);
        if (v !== void 0)
          module2.exports = v;
      } else if (typeof define === "function" && define.amd) {
        define(["require", "exports", "ts-tiny-invariant"], factory);
      }
    })(function(require2, exports3) {
      "use strict";
      Object.defineProperty(exports3, "__esModule", { value: true });
      exports3.assertIsDefined = exports3.isDefined = void 0;
      var ts_tiny_invariant_1 = __importDefault(require2("ts-tiny-invariant"));
      function isDefined(value) {
        return value !== void 0 && value !== null;
      }
      exports3.isDefined = isDefined;
      function assertIsDefined(value, message) {
        ts_tiny_invariant_1.default(isDefined(value), message);
      }
      exports3.assertIsDefined = assertIsDefined;
    });
  }
});
```

And here is `ts-tiny-invariant` defined in the same file

```
// node_modules/ts-tiny-invariant/dist/umd/index.js
var require_umd = __commonJS({
  "node_modules/ts-tiny-invariant/dist/umd/index.js"(exports2, module2) {
    (function(factory) {
      if (typeof module2 === "object" && typeof module2.exports === "object") {
        var v = factory(require, exports2);
        if (v !== void 0)
          module2.exports = v;
      } else if (typeof define === "function" && define.amd) {
        define(["require", "exports"], factory);
      }
    })(function(require2, exports3) {
      "use strict";
      Object.defineProperty(exports3, "__esModule", { value: true });
      var isProduction = process.env.NODE_ENV === "production";
      var prefix = "Invariant failed";
      function invariant(condition, message) {
        if (condition) {
          return;
        }
        throw new Error(isProduction ? prefix : prefix + ": " + (message || ""));
      }
      exports3.default = invariant;
    });
  }
});
```

**Comment by glasser** [comment]
Do you have some instructions I can run without any creativity that lets me see the issue too? Happy to reopen the issue if it comes with a reproduction.

It looks like the dependency tree is `apollo-server-core` -> `@graphql-tools/mock` -> `ts-is-defined` -> `ts-tiny-invariant`. So it seems like it's likely that Apollo Server can't do anything directly — seems like maybe `ts-is-defined` needs to fix something, and then maybe `@graphql-tools/mock` might need to bump a dependency too?  Are you able to reproduce this issue using just `ts-is-defined` in a small program, or using `@graphql-tools/mock` without Apollo Server?

**Comment by ifiokjr** [comment]
@seawatts did you find a workaround?

I'm having the same issue when deploying with the latest version using `vercel`. Strangely, everything seems to work locally. 

I'm using the `esbuild-loader` package to bundle my dependencies and this is the error I notice. 

```
ERROR	Error: Cannot find module 'ts-tiny-invariant'
Require stack:
- /var/task/node_modules/ts-is-defined/dist/umd/index.js
- /var/task/node_modules/@graphql-tools/mock/index.cjs.js
- /var/task/node_modules/apollo-server-core/dist/ApolloServer.js
- /var/task/node_modules/apollo-server-core/dist/index.js
- /var/task/.next/server/pages/api.js
- /var/task/node_modules/next/dist/next-server/server/next-server.js
- /var/task/___next_launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at /var/task/node_modules/ts-is-defined/dist/umd/index.js:16:47
    at /var/task/node_modules/ts-is-defined/dist/umd/index.js:6:17
    at Object.<anonymous> (/var/task/node_modules/ts-is-defined/dist/umd/index.js:12:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/ts-is-defined/dist/umd/index.js',
    '/var/task/node_modules/@graphql-tools/mock/index.cjs.js',
    '/var/task/node_modules/apollo-server-core/dist/ApolloServer.js',
    '/var/task/node_modules/apollo-server-core/dist/index.js',
    '/var/task/.next/server/pages/api.js',
    '/var/task/node_modules/next/dist/next-server/server/next-server.js',
    '/var/task/___next_launcher.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
```

@glasser is it possible to re-open this? 

At the moment `apollo-server-micro@3.0.2` can't be deployed to production when used with `esbuild`.

**Comment by glasser** [comment]
Happy to reopen if there is a reproduction that doesn't require creativity on my part (eg, I don't want to have to guess about what it means to use esbuild-loader with vercel).

**Comment by riccardogiorato** [comment]
We are having the same issue by using "Serverless-stack: https://serverless-stack.com", it uses esbuild under the hood. 

The Apollo Server runs fine locally but on AWS Lambda the built version crashes with this error too:
```
Error: Cannot find module 'ts-tiny-invariant'
```

**Comment by riccardogiorato** [comment]
@ifiokjr can you explain more simple which steps did you took with "patch-package" to fix Apollo Server when running in the build with esbuild?

**Comment by glasser** [comment]
I don't think it's helpful to have open issues where somebody interested in fixing them wouldn't be able to start by reproducing the issue. I am very happy to reopen this issue as soon as it contains a complete description of how I can see the problem on my own computer without requiring any creativity or existing knowledge of things like esbuild or vercel.

(well, caveat, "as soon" modulo "the several-week vacation I'm about to go on", at least for the "I" part of that sentence :) )

**Comment by seawatts** [comment]
@ifiokjr I have not found a workaround. However, it looks like @colin-h just bumped the typescript dependency https://github.com/iyegoroff/ts-is-defined/pull/1 I believe this library will have to pull in that new dependency before this will be resolved.

**Comment by ctbarna** [comment]
I removed the `ts-is-defined` dependency from `@graphql-tools/mock` and the most recent patch of `@graphql-tools/mock` has the fix applied. `apollo-server` pulled the patch in #5552 so it should be fixed in the next release.

I manually patched my lockfile and confirmed that the fix works in a lambda environment.
