### ISSUE TITLE
Terrible version!!! 3.0

### ISSUE THREAD

**Issue by mizzzin** [apollographql/apollo-server#5509]
Version 2+ works very good, but your new 3.0 version is sucks!!!

Why you change this:
import {ApolloServer} from 'apollo-server-micro';

to this:
const {ApolloServer} = required('apollo-server-micro');

**Comment by benjamn** [comment]
Since this appears to be your very first GitHub contribution @mizzzin, this is either a throwaway/sock-puppet account you created just to troll this project, or you're new to GitHub (welcome!) and you might want to familiarize yourself with our [code of conduct](https://github.com/apollographql/apollo/blob/main/CODE-OF-CONDUCT.md#we-strive-to).

**Comment by mizzzin** [comment]
> Since this appears to be your very first GitHub contribution @mizzzin, this is either a throwaway/sock-puppet account you created just to troll this project, or you're new to GitHub (welcome!) and you might want to familiarize yourself with our [code of conduct](https://github.com/apollographql/apollo/blob/main/CODE-OF-CONDUCT.md#we-strive-to).

I write this because one version ago everything works fine, but now this is hell...

**Comment by glasser** [comment]
Whether or not I appreciate the attitude, it's unfortunately the case that your bug report doesn't have enough detail for me to understand what you were trying and why it has changed.  As far as I know, AS2 -> AS3 did nothing to change how you import/require the top level packages. If you can demonstrate a reproduction (eg, a repo I can git clone, or a codesandbox.io demo) and show how something like the above works fine with AS2 but doesn't work with AS3, that would be interesting! But the text enough isn't enough for me to do anything helpful.
