### ISSUE TITLE
apollo-server-plugin-response-cache with apollo-server-cache-redis stop working on v3.0

### ISSUE THREAD

**Issue by ralexrdz** [apollographql/apollo-server#5521]
My previous configuration for handling response cache with apollo server and redis stop working when installing new version of the packges

### **Previous version WORKING**
```
"apollo-server-cache-redis": "^1.5.0",
"apollo-server-plugin-response-cache": "^0.5.5",
```

### **New version NOT WORKING**
```
"apollo-server-cache-redis": "^3.0.1",
"apollo-server-plugin-response-cache": "^3.0.1",
```

### **Configuration**
```
const responseCachePlugin = require('apollo-server-plugin-response-cache');
const { RedisCache } = require('apollo-server-cache-redis')
// ...
cache = new RedisCache({
    host: REDIS_HOST,
    port: REDIS_PORT
})
apollo: {
    cacheControl: {
        defaultMaxAge: 300,
    },
    plugins: [responseCachePlugin()],
    cache
}
```

**Comment by glasser** [comment]
Did you only upgrade these packages, or did you also upgrade Apollo Server from AS2 to AS3? I don't think the AS3 version of the plugin is compatible with AS2.  If you'd like to upgrade the plugin, you should also [upgrade to Apollo Server 3](https://www.apollographql.com/docs/apollo-server/migration/).
