### ISSUE TITLE
Usage Reporting: should it report errors to Studio that are included in the response?

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/apollo-server#5533]
Reproduction: https://github.com/lennyburdette/apollo-studio-error-trace-repro

It appears that the Usage Reporting plugin only reports errors that happen during field execution. If errors are added to the response in `formatResponse`, Studio doesn't know about them.

Is this the intended behavior? I kinda expected that the presence of errors in the response would be recorded in Studio.

cc @v3i1r4in

**Comment by glasser** [comment]
I do think this is working as intended. `formatResponse` is specifically about, well, formatting the response to the end user, not semantically changing whether or not "it has errors".

**Comment by lennyburdette** [comment]
That’s fair. Just curious: is there another way to have a resolver result in a value *and* an error in AS? Graphql-Java has this ability.

**Comment by glasser** [comment]
I feel like I've answered this question before somewhere else but I can't find it. What's the name of the API that accomplishes that in Java?

**Comment by lennyburdette** [comment]
graphql.execution.DataFetcherResult as described here: https://www.graphql-java.com/documentation/v16/execution/
