### ISSUE TITLE
cors error .. nextjs API

### ISSUE THREAD

**Issue by manojap** [apollographql/apollo-server#5544]
Next js api route error
`import {gql,ApolloServer}  from 'apollo-server-micro';
import {PrismaClient} from '@prisma/client';
import { ApolloServerPluginLandingPageGraphQLPlayground } from 'apollo-server-core';
const prisma = new PrismaClient();
import Cors from 'micro-cors' 
const cors = Cors();
import { send } from 'micro';

const typeDefs= gql `
type Contact {
 id: String
 name: String
 email: String
}

type Query {
contacts: [Contact]
} 

`;

const resolvers ={
    Query:{
        contacts: (_parent,_args,_context) =>{
        return    prisma.contact.findMany();       
        },
    },   
}

const apolloServer=  new ApolloServer({typeDefs,resolvers,
   
}
);
 
 
module.exports = apolloServer.start().then(() => {
  const handler = apolloServer.createHandler({path:'/api/graphql'});
  return cors((req, res) => req.method === 'OPTIONS' ? send(res, 200, 'ok') : handler(req, res))
});

export const config ={api:{bodyParser:false}};
`
end up with **Server cannot be reached**

can any one help

**Comment by manojap** [comment]
find a fix 

https://gist.github.com/manojap/9ce06efffec89aa47bac962c7d11ef75

**Comment by kulagowskim** [comment]
This solution didn't work for me

**Comment by glasser** [comment]
As mentioned in https://github.com/apollographql/apollo-server/issues/5517#issuecomment-891526757 and https://github.com/apollographql/apollo-server/issues/5547#issuecomment-891408105 I am incredibly confused about the relationship between Micro and Next.js and I don't understand why people are coming to Apollo Server expecting our Micro support to work on Next.js.

Unfortunately this bug report doesn't have enough detail for me (as somebody who doesn't know much about Next.js) to reproduce and investigate the issue. I see that you've provided one source file, but running it requires me to make lots of guesses as to what versions of dependencies you're using, how you run the server, etc. Happy to reopen if a complete reproduction is provided!
