### ISSUE TITLE
Upgrading federated service to v3* results in startup errors

### ISSUE THREAD

**Issue by cactusblew** [apollographql/apollo-server#5557]
After migrating our current federated service to v3 the gateway service  errors on startup

Error: Couldn't load service definitions for "subgraph" at "subgraph url" 500:internal server error

**Comment by trevor-scheer** [comment]
Can you please provide some more details around your server configuration? Did you follow the migration guide? Is your server running/queryable? I'm happy to help, but I need as much detail as possible. A reproduction if you can provide one is ideal.

**Comment by cactusblew** [comment]
This was an issue very specific to my code. Regret raising an issue.
