### ISSUE TITLE
apollo-server-lambda: callback required but not used

### ISSUE THREAD

**Issue by joshbalfour** [apollographql/apollo-server#5592]
Hiya,

First off just wanted to say I love apollo and have used it extensively over the past few years 😊
Apologies if this is a duplicate, I couldn't find anything like it.

My current use case has me defining a lambda handler so I can use `type-graphql` to async generate my schema.
Now that AWS has deprecated the callback pattern of lambda handlers, async handlers look like this:
```js
export const handler = async (event, context) => {
```

However, passing only `event` and `context` to the handler returned from `server.createHandler()` results in a TypeError which you can see reproduced here:
https://codesandbox.io/s/apollo-server-lambda-callback-type-issue-fwpox?file=/index.ts

Currently, I'm working around this by passing a function in, which never gets called. Because it's not used in a promise context I'd expect this to be optional.

I'll be following up with a tiny PR that makes the callback optional.

Thanks!

**Comment by bhoudu** [comment]
I personally made a custom Promise that uses a custom callback function to be apollo compatible in aws lambda. Would be better if it was natively supported though. It is a plus not a requirement.

**Comment by bhoudu** [comment]
After testing with Apollo 3.1.2 and type-graphql 1.1.1, you can't "wrap" the generated handler by apollo-server-lambda (nothing works afterwards, only timeouts). Not using the last parameter works.

**Comment by glasser** [comment]
(See discussion on #5593)

**Comment by trevor-scheer** [comment]
https://github.com/apollographql/apollo-server/pull/5593#issuecomment-1275404249
