### ISSUE TITLE
How to disable GraphQL mutation/query name suggestions?

### ISSUE THREAD

**Issue by sandorvasas** [apollographql/apollo-server#5598]
I know it's a question, but I suspect they are cannot be disabled. They're also a security issue. 
Our app has been subject to penetration testing and the following issue came up:

e.g. https://HOSTNAME/graphql?query={user_} results in GraphQL API suggesting mutations and queries which have a similar name to ”user_”. 

I already disabled introspection with the graphql-disable-introspection npm module, but I can't find a setting to get rid of the query/mutation suggestions.

See related article:
https://apisecurity.io/issue-116-facebook-parler-api-vulnerabilities-clairvoyance/#tools--clairvoyance

**Comment by trevor-scheer** [comment]
This is a known issue in the [graphql-js library itself](https://github.com/graphql/graphql-js/issues/2247). For now, one solution might be to strip these out of the errors via `formatError` or a custom Apollo Server plugin.

Also, [introspection can be disabled via configuration of Apollo Server](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#introspection), no additional npm module needed.

**Comment by glasser** [comment]
Duplicate of #3919
