### ISSUE TITLE
Graphql breaks thanks to a missing graph ref?

### ISSUE THREAD

**Issue by Pixelatex** [apollographql/apollo-server#5603]
I upgraded to the latest version and locally it works but when I deployed to production, where the apollo studio api key is loaded in... everything breaks.

Error: To use ApolloServerPluginSchemaReporting, you must provide your graph ref (eg, 'my-graph-id@my-graph-variant'). Try setting the APOLLO_GRAPH_REF environment variable or passing `new ApolloServer({apollo: {graphRef}})`.

I can't find a damn reference to what this is supposed to be and the few references I can find state that this is a "warning" Yet it's being thrown as an error breaking my entire graphql server.

This is poorly designed and this shouldn't entirely break your app just for missing some new gimmick you added on the apollo studio side of things.

**Comment by trevor-scheer** [comment]
Hey @Pixelatex, sorry for the trouble with the upgrade. I know it can be frustrating when things aren't working as expected. I'd appreciate some benefit of the doubt here in our design, it's very possible there's a bug here if we're expecting a warning but throwing an error, and I'd be happy to help get that sorted out.

It looks like the plugin that's throwing the error [has to be explicitly enabled](https://www.apollographql.com/docs/apollo-server/api/plugin/schema-reporting/), so it would be helpful to see what your setup looks like. Would you mind sharing your configuration (AS constructor options + which env variables that you're providing) or better yet, a reproduction?

**Comment by glasser** [comment]
This is covered in the Apollo Server 3 migration guide under [Guessing Apollo Studio graph ID from API key](https://www.apollographql.com/docs/apollo-server/migration/#guessing-apollo-studio-graph-id-from-api-key). We removed a brittle piece of code that hard-coded assumptions about the structure of Apollo Studio API keys into Apollo Server; it does require you to provide a tiny bit more information in return.
