### ISSUE TITLE
Support for graphql@16

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-server#5605]
With the impending release of `graphql-js` 16 (https://github.com/graphql/graphql-js/issues/2860), we'll want to make sure Apollo Server and Federation (https://github.com/apollographql/federation/) are compliant.

**Comment by glasser** [comment]
Note that I've [asked Renovate to pin graphql to v15](https://github.com/apollographql/apollo-server/commit/c0415536986b8ffbd33b70b2cf906c283126e3cd) for now, so that we don't get all the noise of it rebasing constantly until it works. We can revert that commit once this is solved.

**Comment by hwillson** [comment]
Completed in https://github.com/apollographql/apollo-server/pull/5857 and available in Apollo Server 3.5.0.
