### ISSUE TITLE
Rest DataSource Caching Errors

### ISSUE THREAD

**Issue by cxl-todd** [apollographql/apollo-server#5608]
I'm experiencing a similar issue as https://github.com/apollographql/apollo-server/issues/1481. However, I have the latest rev: `"apollo-datasource-rest": "^3.1.1"` and it is clearly caching HTTP errors. Is there anyway to control the cache on a per-request level?

In my situation, our JWT auth expires and the subsequent call returns unauth 401. The code immediately requests a new JWT vi the login endpoint, but cannot resolve the original request because it has cached the 401 response.

**Comment by cxl-todd** [comment]
Seems the issue is with memoization. Based on some points noted in [this bug](https://github.com/apollographql/apollo-server/issues/1562) I added:

```
  didEncounterError(error, request) {
    this.memoizedResults.delete(this.cacheKeyFor(request));
    return super.didEncounterError(error, request);
  }
```

This seems to ensure that error responses are not held onto indefinitely. 

A few takeaways:

1. It fails the test of least surprise to see that errors are cached. Seems that this should not be the default behavior, imo.
2. Memoization appears to cache across requests. This is unexpected per https://www.apollographql.com/docs/apollo-server/data/data-sources/#using-with-dataloader where it says: 
> ...a memoization cache, which avoids loading the same object multiple times during a single GraphQL request.

My experience shows that across separate requests, the 401 response continues to be served up regardless.

Cheers

**Comment by alexandernanberg** [comment]
Where/how do you initialize your data sources? AFAIK they need to be inside the `dataSources` callback.

```js
const app = new ApolloServer({
  schema: executableSchema,
  dataSources: () => ({
    api: new MyApi(),
  }),
});
``` 

If you do something like this the data source will only be created once, meaning memoization won't reset between requests

```js
const dataSources = {
  api: new MyApi(),
};
const app = new ApolloServer({
  schema: executableSchema,
  dataSources: () => dataSources,
});
```

**Comment by glasser** [comment]
@alexandernanberg is correct: data sources are per-request. If the issue here is about long-lived data sources, then it should be closed. If this is a misunderstanding, happy to reopen.
