### ISSUE TITLE
Support ETag / complex caching headers

### ISSUE THREAD

**Issue by nmokkenstorm** [apollographql/apollo-server#5625]
Hello people,

So far I'm massively enjoying Apollo Server with datasources. I come from a rather puristic/theoretical REST, so I was pleasantly surprised with how easy the REST datasource is. Something I'm missing at this point is a way to cache responses to the origin server using the built-in caching mechanisms of the web ([link 1](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag), [link 2](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304), [link 3](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match)), which is wat makes REST as powerful as it is. I'd love to combine that power with the request consolidation that GraphQL offers.

[I made a similar comment in the community alternative](https://github.com/StarpTech/apollo-datasource-http/issues/13), it took a little bit more time to comb to the issues here, but I think nobody has raised this feature request yet. I'm comfortable enough with typescript/apollo and REST fundamentals at this point that I can implement this (probably [here](https://github.com/apollographql/apollo-server/blob/c9e8d72d2a8f47f5fa4dd8b0c3c00cd3bbe75573/packages/apollo-datasource-rest/src/RESTDataSource.ts#L110)), but I'd first like to explore if this is something that'd have support of the community.

I'd love to hear and share some thoughts.

**Comment by glasser** [comment]
Doesn't the [`HTTPCache`](https://github.com/apollographql/apollo-server/blob/main/packages/apollo-datasource-rest/src/HTTPCache.ts) inside apollo-datasource-rest implement ETag and friends already (based on the [`http-cache-semantics` npm module](https://www.npmjs.com/package/http-cache-semantics))?

(Note for full context: while the REST datasource codebase does live inside the `apollo-server` repo, it's essentially a mostly-unrelated subproject, and the current Apollo Server team hasn't yet fully onboarded into deep knowledge of that project. For the time being, apollo-datasource-rest is effectively unmaintained, although that is unfortunate.)

**Comment by nmokkenstorm** [comment]
You're correct, after diving a bit in the `http-cache-semantics` module it seems to be working as mentioned, in that case it's just the community alternative that could use some love here. A cursory glance through the issue list indeed does confirm that this part of the project is not as well maintained as could be, I might have a look to improve that.
