### ISSUE TITLE
Licensing issues with dependencies

### ISSUE THREAD

**Issue by selfagency** [apollographql/apollo-server#5640]
The following dependencies of Apollo Server/Apollo Client are throwing errors in my licensing compliance tools because they do not contain LICENSE files. Could you please add the appropriate licenses? Thank you.

- @apollographql/graphql-language-service-interface
- @apollographql/graphql-language-service-parser
- @apollographql/graphql-language-service-types
- @apollographql/graphql-language-service-utils

**Comment by glasser** [comment]
@selfagency Hi, good catch. These are forks of packages from https://github.com/graphql/graphiql that we haven't updated in a while, and the upstream didn't have licenses on them until https://github.com/graphql/graphiql/pull/849

Will look into publishing versions with MIT license, but to check — are you sure that these are actually dependencies of Apollo Server? I don't actually think Apollo Server 3 depends on these, even transitively. Can you share a package-lock.json that shows that these were pulled in?

I think they are used by the `apollo` CLI, which we are in the process of fully deprecating.

**Comment by glasser** [comment]
(https://github.com/apollographql/apollo-tooling/issues/1553 and https://github.com/apollographql/apollo-tooling/pull/2089 are relevant to the CLI here. Going to figure out why @hwillson closed the latter recently.  That said, the main fix here is killing off the `apollo` package.

**Comment by selfagency** [comment]
Here's the first one

![CleanShot 2021-08-23 at 18 03 07](https://user-images.githubusercontent.com/2541728/130525338-17c0209a-c366-4839-90ac-9b056014ae15.png)

And here are the other three

![CleanShot 2021-08-23 at 18 03 33](https://user-images.githubusercontent.com/2541728/130525397-6dc1fb1e-9bcf-40b3-9be0-423004e27adf.png)

**Comment by glasser** [comment]
Yeah, `apollo` is the CLI that we are finally going to make the push to fully deprecate. It should not be a dependency of Apollo Server, so I'm going to close this issue; the other issues I linked are more relevant to `apollo`. That said, do you know what commands you use `apollo` for? I can advise on whether there are better replacements for them yet or if we're still in the process of making that transition possible.

**Comment by selfagency** [comment]
It appears it's `vue-cli-apollo` that is using the `apollo` cli.

**Comment by selfagency** [comment]
Interestingly, only two `apollo` related packages appear to be dependencies of vue-cli-apollo: 

- "@apollo/client": "^3.2.1"
- "apollo-cache-inmemory": "^1.2.9"

**Comment by selfagency** [comment]
Aaaaand finally, `vue-cli-apollo` is a dependency of `@nuxtjs/apollo`. So it seems the official Vue and Nuxt integrations for Apollo are dependent on a deprecated feature.

**Comment by selfagency** [comment]
Anyhow, thanks for your help.

**Comment by glasser** [comment]
Thanks. Yeah, it looks like [`vue-cli-plugin-apollo`](https://github.com/Akryum/vue-cli-plugin-apollo/blob/master/package.json) depends on a lot of older stuff: the `apollo` CLI, Apollo Client 2 (AC3 was released over a year ago), Apollo Server 2, etc.

**Comment by selfagency** [comment]
Looks like it hasn't been updated for over a year (15 mos). Ouch.

**Comment by selfagency** [comment]
Appears other Nuxt users [have noticed](https://github.com/nuxt-community/apollo-module/issues/404) as well.
