### ISSUE TITLE
Docs: Validation Rules

### ISSUE THREAD

**Issue by abias1122** [apollographql/apollo-server#5656]
This isn't really a bug, but there wasn't an option for reporting issues in the docs.

The [docs](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#validationrules) for newing up `ApolloServer` say that the option `validationRules` takes an object:
<img width="556" alt="apollo server validation rules docs" src="https://user-images.githubusercontent.com/28871516/130978312-2636aacc-5129-4d92-bedf-922808bea0a8.png">

However, I noticed that the following is valid:
```
const server = new ApolloServer({
    // other properties
    validationRules: [depthLimit(10)]
});
```
`depthLimit` comes from [graphql-depth-limit](https://github.com/stems/graphql-depth-limit).

I propose the documentation be updated to say that `validationRules` can take an object or an array.

**Comment by abias1122** [comment]
@glasser  I see that the docs are updated in the GitHub repo. When will the update be applied to the docs on [Apollo's website](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#validationrules)?

**Comment by glasser** [comment]
Docs are auto deployed. We are currently doing an AB test on some improvements to the search functionality of the website and unfortunately the improved version needs to be manually updated, so if your browser ends up there you won't see the fix yet. I'm told we'll be wrapping up the experiment in a few days.
