### ISSUE TITLE
Hello world returned as response 

### ISSUE THREAD

**Issue by Johnsavadkuhi** [apollographql/apollo-server#5659]

**Comment by Johnsavadkuhi** [comment]
Hello  

when i logout account , the result will be Hello World but when i use the apollo studio as guest the result is ok and it works fine

**Comment by glasser** [comment]
@Johnsavadkuhi I think you've enabled mocking inside the Apollo Sandbox UI.  In Apollo Sandbox, click the Gear (settings) button that appears above the word "Documentation" in the screen shot above.  See if "Mock responses" is turned on.

![image](https://user-images.githubusercontent.com/16724/134224798-9bd7fb8e-dbc7-42de-ab5b-44e785a9658e.png)
