### ISSUE TITLE
AS3 Lambda - POST body missing, invalid Content-Type, or JSON object has no keys. ImageUpload

### ISSUE THREAD

**Issue by johnlongo** [apollographql/apollo-server#5670]
Getting http 400 error (body missing, invalid Content-Type, or JSON object has no keys.) when I try to upload an image (multipart/form-data) to apollo-server-lambda V3.1.2 (see attached). Any help/suggestions will be greatly appreciated!

![image](https://user-images.githubusercontent.com/23619505/131212917-5cf656fe-489b-4f1b-8fca-f8e678e662ce.png)

**Comment by glasser** [comment]
Looks like you already closed this, but — you'll want to share more details on what you actually tried (eg, a complete executable example).  In AS3 there is no built-in integration with `graphql-upload`: you need to integrate it yourself.
