### ISSUE TITLE
Subscriptions working on localhost but not working on host

### ISSUE THREAD

**Issue by hichamlehouedj** [apollographql/apollo-server#5674]
When I request any subscription on the local server it works fine but does not work on the hosting server and at the same time the rest of the queries work correctly.

This is the error message:

“error”: “Could not connect to websocket endpoint wss://example.com/graphql. Please check if the endpoint url is correct.”

I followed the documentation carefully, with the evidence that the code is running efficiently on the local server

playground localhost :

![0348](https://user-images.githubusercontent.com/44528743/131497737-306412f7-1514-47cb-90bd-cf950aa3357a.PNG)

playground hosting :

![0349](https://user-images.githubusercontent.com/44528743/131497748-553b8b52-e349-499a-8202-894e4bd2c7f2.PNG)

**Comment by glasser** [comment]
Apollo Server 3 does not have native support for subscriptions. Have you set them up based on the [integration described in the docs](https://www.apollographql.com/docs/apollo-server/data/subscriptions/)?

If this is a bug report about the example given in the docs, that's good to know and we can work on that, but without sharing a reproduction that we can look at ourselves, we can't help. Happy to reopen this if you provide a full reproduction (eg something from codesandbox.io or starting with `git clone`).

**Comment by hichamlehouedj** [comment]
@glasser 
Yes I followed the documentation for apollo sever 3

I will upload a simplified version of the project on Github and put the link here

**Comment by hichamlehouedj** [comment]
@glasser  This is a simple version of the project :
[https://github.com/hichamlehouedj/sempel-graphql-api.git](https://github.com/hichamlehouedj/sempel-graphql-api.git)

**Comment by glasser** [comment]
Great, we'll take a look. (Sorry, we've had some vacations in the past few weeks.) A detailed step by step description of how to reproduce once we hit `git clone` would certainly make things easier.

**Comment by hichamlehouedj** [comment]
@glasser 
I uploaded it to heroku and it works fine but when I upload it to cpanel it works mutation and query correctly but the subscription is giving me the error I think the problem is with cpanel or htaccess file, there is no other reason than them. Can you upload this project or another simple project on cpanle and let me know the right steps? I'm starting to despair of finding a solution

**Comment by glasser** [comment]
I'm sorry, I'm not familiar with "cpanel". If it works in one hosting environment and not another, it's probably not an Apollo Server issue...

**Comment by hwillson** [comment]
Just chiming in here quickly as I've worked with cPanel based hosting providers. @hichamlehouedj if you're using cPanel's default node setup, then you're likely using [Phusion Passenger](https://www.phusionpassenger.com/library/) under the hood, combined with either nginx or apache. If this is the case you're going to need to turn sticky session support on in Passenger to work with WebSockets. If you're using nginx for example, you can add `passenger_sticky_sessions on` to your server config (details [here](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_sticky_sessions)).

I agree with @glasser though - this isn't an Apollo Server issue. If you need more assistance with this I recommend reaching out in the [Apollo community forums](https://community.apollographql.com). Thanks!
