### ISSUE TITLE
High latency for a federated gateway downloading schema and tracing

### ISSUE THREAD

**Issue by adrianet86** [apollographql/apollo-server#5695]
Hello,
I have a federated server using _apollo-studio_ to handle schemas but since we have upgraded our libraries from version **2.25.2** to **3.0.0** we have a high latency with requests to the following urls to download schema and traces.

![image](https://user-images.githubusercontent.com/3386777/132461092-3d1c2f8c-d669-44fd-b268-e1efc1e6fa71.png)

-     "@apollo/gateway": "^0.39.0", (previous version was 0.30.0)
-     "apollo-server": "^3.3.0",
-     "apollo-server-express": "^3.3.0"

Do you have any clue regarding this issue?

**Comment by glasser** [comment]
Are you still seeing this? We have had some stability/performance issues recently (as seen at https://status.apollographql.com/) which could explain this. If you see this constantly, not just during our periods of performance issue (including right now), then that's worth knowing about.

**Comment by trevor-scheer** [comment]
This is interesting and I hope we hear back from @adrianet86 as to whether this issue still persists (especially on more current versions of our packages), but I'm going to close this as stale. Happy to reopen if the issue is ongoing.
