### ISSUE TITLE
http request timeout on queries

### ISSUE THREAD

**Issue by RichardWright** [apollographql/apollo-server#5697]
Versions involved -
"apollo-server": "^2.19.2",
"apollo-server-env": "^3.0.0",
"apollo-server-express": "^2.25.2",

What is the suggested way of setting a shared timeout for queries? Is there a global way, a middleware or does this need to be done on the resolver?

Thanks!

**Comment by glasser** [comment]
I don't think we have specific advice on doing this. It would be interesting to hear what conclusions other users have come to!

**Comment by RichardWright** [comment]
I can think of three ways - 

1) on the socket
2) on the response at the express level
3) on the resolver level.

All have drawbacks. That I can't find consensus on it is quite odd.

**Comment by sdacunha** [comment]
HI @glasser,

We were using connect-timeout + apollo-server-express and noticed a few similar issues as those in #5834.

What would be the best advice for setting timeouts on the server side? Socket timeouts was an approach that avoided ```Cannot set headers after they are sent to the client```, but suffer from the problems described above by @RichardWright. I also noticed issues in calling my subgraphs from my gateway with the switch to ```make-fetch-happen``` (various ECONNRESET errors), and so we switched our fetcher back to ```node-fetch```. For now I am considering removing the connect-timeout middleware and perhaps setting timeouts on the client, but any guidance would be appreciated!

**Comment by glasser** [comment]
As mentioned there, I think the best approach would be to improve graphql-js so that its execution is interruptible.

**Comment by ramsrib** [comment]
It would be great if apollo-server natively supports request timeout or atleast have recommendation (in their docs) on how to implement it with express.js.

NestJS's timeout interceptor example is pretty interesting and it works great with their graphql support, but not sure how they implemented without `graphql-js` interruptible execution support. Ex: https://github.com/nestjs/nest/blob/master/sample/01-cats-app/src/common/interceptors/timeout.interceptor.ts

**Comment by glasser** [comment]
Perhaps the NestJS timeout doesn't actually stop graphql-js execution from running, just returns an error in parallel to the client?

I've filed https://github.com/graphql/graphql-js/issues/3764
I don't think there's much for us to do here until that is fixed (which we could contribute to); once there's an API that can be used, we can reopen an issue about integrating properly with the new API.
