### ISSUE TITLE
Have content type of application/vnd.api+json parsed as json in the RestDataSource library

### ISSUE THREAD

**Issue by nholik** [apollographql/apollo-server#5724]
It would be nice if responses using [jsonapi](https://jsonapi.org/) where the content type is application/vnd.api+json would be parsed as JSON.

Right now anything with content type starting with 'application/json' or 'application/hal+json' as seen here:
https://github.com/apollographql/apollo-server/blob/0163a5fe6a8d1e5d15d088dfc2de5ac884906ab5/packages/apollo-datasource-rest/src/RESTDataSource.ts#L119
and here
https://github.com/apollographql/apollo-server/blob/0163a5fe6a8d1e5d15d088dfc2de5ac884906ab5/packages/apollo-datasource-rest/src/RESTDataSource.ts#L120
is parsed in the library, and it would be nice to have application/vnd.api+json follow the same pattern.

Either adding this additional type or making a more general change to anything ending with '+json' seem like to viable approaches.

I do see [here](https://github.com/apollographql/apollo-server/issues/5237#issuecomment-849036113) that one suggestion is overriding, but a more general approach may help avoid the question all together with checking for trailing '+json' and having the override option for more esoteric content types outside the two patterns.

I'd be happy to submit a PR if such a change could be accommodated.

**Comment by glasser** [comment]
Sure, file a PR. `apollo-datasource-rest` is not currently very actively maintained but a very simple PR should be fine.

**Comment by nholik** [comment]
Thanks @glasser submitted the change - pretty simple.
