### ISSUE TITLE
set Cookie issue

### ISSUE THREAD

**Issue by ayoubjamouhi** [apollographql/apollo-server#5725]
Apollo server can't set cookie on apollo server sandbox 

this is the middleware 

`app.use(
      session({
        name: "mid",
        store: new RedisStore({ client: redisClient, disableTouch: true }),
        cookie: {
          maxAge: 1000 * 60 * 60 * 24 * 365 * 10, // 10 years
          secure: false,
          httpOnly: true,
          sameSite: "lax",
        },
        saveUninitialized: false,
        secret: "secret",
        resave: false,
      })
    );`

Apollo instance before 
`    const server = new ApolloServer({
      schema,
      context: ({ req, res }): Context => ({ req, res, session: req.session }),
    });`

I added plugins for GraphQlPlayGround and it's set the cookie now

`    const server = new ApolloServer({
      schema,
      context: ({ req, res }): Context => ({ req, res, session: req.session }),
      plugins: [ApolloServerPluginLandingPageGraphQLPlayground()],
    });`

**Comment by cheapsteak** [comment]
👋 hi there

for cookie based auth, same-site would need to be set to "None" for it to work with sandbox since this would be a cross-origin request (from https://studio.apollographql.com to the endpoint)

**Comment by glasser** [comment]
I hope @cheapsteak's suggestion was helpful! Closing this.
