### ISSUE TITLE
Apollo server 3 does not work with serverless offline 

### ISSUE THREAD

**Issue by Krishantha** [apollographql/apollo-server#5738]
Apollo server 3 with AWS lambda (`apollo-server-lambda`) does not compatible with serverless offline plugin. 

```
const server = new ApolloServer({
  plugins: [ApolloServerPluginLandingPageGraphQLPlayground()],
  typeDefs: typeDefs,
  resolvers: resolvers,
  introspection: true,
});
```
its starts fine.

```bash
Serverless: Running "serverless" installed locally (in service node_modules)
offline: Starting Offline: dev/ap-southeast-1.
offline: Offline [http for lambda] listening on http://localhost:3002
offline: Function names exposed for local invocation by aws-sdk:
           * employee: aws-apollo-demo-dev-employee

   ┌────────────────────────────────────────────────────────────────────────────┐
   │                                                                            │
   │   POST | http://localhost:3000/dev                                         │
   │   POST | http://localhost:3000/2015-03-31/functions/employee/invocations   │
   │   GET  | http://localhost:3000/dev                                         │
   │   POST | http://localhost:3000/2015-03-31/functions/employee/invocations   │
   │                                                                            │
   └────────────────────────────────────────────────────────────────────────────┘

offline: [HTTP] server ready: http://localhost:3000 🚀
offline: 
offline: Enter "rp" to replay the last request
```

but when query it gives an error. 

#### current

`Cannot POST null`

#### expected
should return result and / should show playground as it does on `apollo-server-lambda 2.x.x`

how ever if I downgrade to `apollo-server-lambda 2.x.x` everything works fine with serverless offline.

also this works when deployed to aws.

how we can get this works with sls offline.

**Comment by glasser** [comment]
Hi! I know we [document how to use `serverless`](https://www.apollographql.com/docs/apollo-server/deployment/lambda/) but I'm not familiar with the offline plugin.  In order to reproduce the issue, I'd like to have to apply any creativity. Are you able to provide a full reproduction (eg, starting with `git clone`) that includes all of the files relevant (including however you enable `offline`) so we can see it ourselves in exactly the same way you see it? Happy to reopen if a full reproduction is included.

**Comment by UncleGrim** [comment]
Made an account for anyone else that stumbles upon this.

The problem with serverless-offline and Apollo3 is the default url property has changed. 

See [this post](https://github.com/dherault/serverless-offline/issues/1256#issuecomment-894646721)

To validate try issuing requests against the `/graphql` URI, this worked for me.
