### ISSUE TITLE
`apollo-server-lambda` using fastify (`apollo-server-lambda-fastify` ?!)

### ISSUE THREAD

**Issue by bryantbiggs** [apollographql/apollo-server#5751]
Basically as the title states - I'm curious if this would be supported natively through various means (separate package, ability to configure the current lambda package with a bring-your-own-server-framework, other?)

**Comment by glasser** [comment]
In Apollo Server 2, `apollo-server-lambda` involved a lot of built-in knowledge of Lambda. This was pretty unmaintainable as it required us to be Lambda experts and make lots of changes as AWS added features.

Now, `apollo-server-lambda` is built by combining `apollo-server-express` with `@vendia/serverless-express`, a package that interfaces between Lambda and Express.  Improvements to how Lambda events are parsed happen in that package, not Apollo Server. It's a much more reasonable scope for us — the non-test code in this repo now contains absolutely no "knowledge" of what a Lambda event or context looks like.

I definitely don't think we are in any way interested in adding code to this repo that converts between Lambda events and Fastify requests. That would be a step backwards in maintainability. If there exists a package out there like `@vendia/serverless-express`, then sure, we could make a package that combines `apollo-server-fastify` with that package, but that glue package could also be maintained outside of the `apollo-server` repo.  To be honest, it's already a big maintenance burden that this repo contains bindings for so many web frameworks (some of which are pretty marginal in usage) when the core Apollo Server team only actively dogfoods a subset of them.  It would be better for us to put the energy into making the interface between `apollo-server-core` and the framework bindings simpler and stabler and moving most of them out of this repo than to add more dependencies on specific frameworks.

**Comment by bryantbiggs** [comment]
totally understandable and can't say I don't disagree - thank you for the thorough explanation @glasser !
