### ISSUE TITLE
Backport `@cacheControl(inheritMaxAge: true)` to `v2`

### ISSUE THREAD

**Issue by garritfra** [apollographql/apollo-server#5752]
Hi!

I'm currently looking for a way to implement proper Server-Side Caching. Our application still uses `v2.25.0` of Apollo Server (Express), yet the `inheritMaxAge` feature added in #5247 is needed to get caching right. I'd like to avoid the migration to `v3`, so my question would be if this feature could be backported to `v2`? Judging by the code, the backport would be possible without any breaking changes to the API.

**Comment by garritfra** [comment]
We went the migration route. Sorry for the inconvenience!

**Comment by glasser** [comment]
We did significantly rewrite the cache control code in v3 (including changing what package it lives in and how it connects to the rest of the system) so I'm glad you were able to upgrade!
