### ISSUE TITLE
fixture.key file causing Aquasec scan  failures

### ISSUE THREAD

**Issue by Leonas-Komaras** [apollographql/apollo-server#5781]
Hello,

as of version 3.3.0 of apollo-server-core our Aquasec scans complain on sensitive data in our dependencies.
According to scan report issue is with packages/apollo-server-core/src/plugin/drainHttpServer/__tests__/stoppable/fixture.key file being part of the npm module.

Could this file (or complete tests) be excluded from the module?

Thank you.

**Comment by glasser** [comment]
This seems reasonable. I want to check with some team folks to see if there's any reason not to add `src/**/__tests__/**` to all npmignore files in this repo.
