### ISSUE TITLE
timelines or deadline for `@deprecated` directive

### ISSUE THREAD

**Issue by chenrui333** [apollographql/apollo-server#5815]
I wonder if it would be a good idea of adding a deadline syntax into the `@deprecated` directive, serving as urgency signal pushing folks to migrate off the API.

```
type ExampleType {
  oldField: String @deprecated(reason: "Use `newField`.", dueDate: "2021-12-31")
  newField: String
}
```

**Comment by glasser** [comment]
The `@depreacted` directive is defined by the GraphQL specification, so this would make more sense as a suggestion for the spec using the [RFC process](https://github.com/graphql/graphql-spec/blob/main/CONTRIBUTING.md).
