### ISSUE TITLE
docs: middleware examples are not valid TS

### ISSUE THREAD

**Issue by mortifia** [apollographql/apollo-server#5822]
https://www.apollographql.com/docs/apollo-server/integrations/middleware/#apollo-server-express

i get error with "No surcharge corresponds to this call." with 
```js 
await new Promise(resolve => httpServer.listen({ port: 4000 }, resolve));
``` 

httpServer.listen is already asynchronous so why not have to use this ? :
```js
await httpServer.listen({ port: 4000 });
```

with node v14, typescript, @types/node

**Comment by mortifia** [comment]
thank you for the feedback and the speed of the response

my opinion on it will be to have the example in colapse or tabs like stripe we do in their documentation of stripe

but in the current state a comment should be sufficient

as long as I think about it this function compared to the old version that I knew is more difficult to understand and can lose a certain number of the subtlety with the callback and async and their side effect

**Comment by glasser** [comment]
All code blocks in the docs which use `await new Promise` now have both TS and JS versions available via a popup.

**Comment by mortifia** [comment]
perfect (☞ﾟヮﾟ)☞
