### ISSUE TITLE
 Make keepAliveTimeout and headersTimeout configurable

### ISSUE THREAD

**Issue by serle** [apollographql/apollo-server#5833]
When running ApolloServer behind an AWS ALB at scale, we get random bad gateway errors. You can refer to a similar discussion: https://github.com/vercel/next.js/discussions/28642. Its is a common problem with all Node (>10) httpServer implementations.

**Comment by sameerkumar-potukuchi** [comment]
@serle not sure if you were able to get to the bottom of this, but just in case you are still having issues and if you are using apollo-server-express implementation you can do the following : 

in your gateway's index.ts 

await new Promise<void>(resolve => {
    const httpServer = app.listen({ port }, resolve);
    httpServer.keepAliveTimeout = 29000;
    httpServer.headersTimeout = 30000;
    return httpServer;
  });
  
 A couple of things to note headersTimeout should be greater than the keepAliveTimeout and your AWS ALB idle time out should be less than both of the above timeout settings. Hope this helps.

**Comment by glasser** [comment]
I"m going to close this since it didn't have enough details to understand what the issue was. Thanks @sameerkumar-potukuchi for your help though!
