### ISSUE TITLE
Swich to undici from node-fetch

### ISSUE THREAD

**Issue by chirag04** [apollographql/apollo-server#5856]
We are noticing that `apollo-datasource-rest` takes longer and longer when we make a bunch of parallel requests to our underlying microservices using dataloader. We haven't landed on the exact root cause but so far it points to node-fetch being slow and not tuned(custom http agent) for a lot of parallel requests.

Undici is an official nodejs project and claims to be much faster than node-fetch. Would be nice to switch to undici if that's true.

Potentially addresses the TODO mentioned here: https://github.com/apollographql/apollo-server/blob/77441b7f6c707741ebe4bd71322116d9e2b5e7b9/renovate.json5#L49-L53

**Comment by glasser** [comment]
@chirag04 `node-fetch` is the default HTTP fetcher for RESTDataSource but you can provide your favorite implementation as the argument to the RESTDataSource constructor.

I don't think any changes to defaults are likely to happen until apollo-datasource-rest returns to active maintenance (or is deprecated in favor of a more actively maintained community project).

**Comment by brainkim** [comment]
I believe `undici` is also Node 16+ for now, as an argument against (https://github.com/nodejs/undici/issues/1018).
