### ISSUE TITLE
ApolloServerPluginCacheControl rewrites requestContext.overallCachePolicy.maxAge in willResolveField method when handle composite type fields.

### ISSUE THREAD

**Issue by Qwedir** [apollographql/apollo-server#5861]
I use apollo-server-core@3.4.0 and found some unexpected behavior.

ApolloServerPluginCacheControl rewrites requestContext.overallCachePolicy.maxAge in willResolveField method when handle composite type fields.

I have structure like this:
```
@ObjectType()
@Directive('@cacheControl(maxAge: 10000, scope: PUBLIC)')
export class PostModel {
  // ...
  @Field(() => ContactModel, { nullable: true })
  author: ContactModel;
  // ...
}

@ObjectType()
export class ContactModel{
   // ...
}
```

[at here](https://github.com/apollographql/apollo-server/blob/apollo-server-core%403.4.0/packages/apollo-server-core/src/plugin/cacheControl/index.ts#L213) when `author` field willResolve maxAge sets to 0 for requestContext.overallCachePolicy and overwrites my old (10000) value

maybe we can change this [line](https://github.com/apollographql/apollo-server/blob/apollo-server-core%403.4.0/packages/apollo-server-core/src/plugin/cacheControl/index.ts#L100) to:
`const defaultMaxAge: number = options.defaultMaxAge ?? undefined;`

**Comment by glasser** [comment]
I believe this is working as intended, as described in the long comment above the first line you linked and at https://www.apollographql.com/docs/apollo-server/performance/caching/#why-are-these-the-maxage-defaults

**Comment by Qwedir** [comment]
I am trying to cache the whole request and I have a large nested object structure. With the current implementation, I need to set for all of nested models @cacheControl directive with `inheritMaxAge=true`, otherwise any of the nested models will overwrite maxAge for the entire request.
Also I need to watch out for new nested objects, since each can overwrite maxAge for request.

I suggest adding global flag that will change this behavior.
