### ISSUE TITLE
Unable to reach server Error when toggle on include cookies in apollo studio

### ISSUE THREAD

**Issue by dwalker93** [apollographql/apollo-server#5868]
I tried to create express-session based authentication with apollo server.  But when I enabled include cookies in apollo studio I got popup error,

```
Unable to reach server

To diagnose the problem, please run:
npx diagnose-endpoint@1.0.12 --endpoint=http://localhost:4000/api
Prefer to self diagnose?
```
I added these headers also as instructed.
Access-Control-Allow-Origin: https://studio.apollographql.com
Access-Control-Allow-Credentials: true

And got error as response

```
{
  "name": "TypeError",
  "message": "Failed to fetch",
  "stack": "TypeError: Failed to fetch\n    at window.fetch (https://www.datadoghq-browser-agent.com/datadog-rum-us.js:5:36191)\n    at https://cdn.ravenjs.com/3.22.1/raven.min.js:2:11497\n    at t.<computed>.t.<computed> (https://cdn.segment.com/next-integrations/integrations/fullstory/3.0.1/fullstory.dynamic.js.gz:1:3126)\n    at https://studio-ui-deployments.apollographql.com/build/static/js/ExplorerPage.964eee919220aedeceb3.js:83:32228\n    at Generator.next (<anonymous>)\n    at https://studio-ui-deployments.apollographql.com/build/static/js/ExplorerPage.964eee919220aedeceb3.js:83:15171\n    at new Promise (<anonymous>)\n    at fa (https://studio-ui-deployments.apollographql.com/build/static/js/ExplorerPage.964eee919220aedeceb3.js:83:14916)\n    at https://studio-ui-deployments.apollographql.com/build/static/js/ExplorerPage.964eee919220aedeceb3.js:83:31810\n    at https://studio-ui-deployments.apollographql.com/build/static/js/ExplorerPage.964eee919220aedeceb3.js:83:32897\n    at Generator.next (<anonymous>)\n    at s (https://studio-ui-deployments.apollographql.com/build/static/js/ExplorerPage.964eee919220aedeceb3.js:83:22223)"
}
```
![image](https://user-images.githubusercontent.com/65861708/140500035-0318f902-1c7e-49bd-8812-21413bcd0e0f.png)

I tried with playground using ApolloServerPluginLandingPageGraphQLPlayground plugin and working fine.

I recreated this error with this simple server,

```
const express = require("express");
const { ApolloServer, gql } = require("apollo-server-express");
const http = require("http");
const cors = require("cors");

const typeDefs = gql`
  type Query {
    hello: String
  }
`;

const resolvers = {
  Query: {
    hello: () => "world",
  },
};

(async () => {
  const app = express();
  app.use(
    cors({
      origin: "https://studio.apollographql.com",
      credentials: true,
    })
  );
  const httpServer = http.createServer(app);
  const apollo = new ApolloServer({
    typeDefs,
    resolvers,
  });

  await apollo.start();
  apollo.applyMiddleware({ app, path: "/api" });
  await new Promise((resolve) => httpServer.listen({ port: 4000 }, resolve));
  console.log(`🚀 Server ready at http://localhost:4000/api`);
})();
```

**Comment by dborstelmann** [comment]
I'm getting this too, my gateways worked yesterday, anybody know what's going on here?

**Comment by dwalker93** [comment]
playground doesn't show any errors when credentials set to include. But playground not sending any cookies. I think problem is in browsers. They are not allowing to set cookies in online editors. So I've to switch to Insomnia and it's also perfect with graphql. But If this error fixed I want to switch again to apollo studio. Apollo studio is very easy to use.

**Comment by ecker00** [comment]
I also added the headers like you, but when I inspect the Apollo Studio requests in my browsers network tab, then **I see that the `Access-Control-Allow-Origin` header is set to `*`** and not `https://studio.apollographql.com` which is what I've configured. I've tried to mess around configuring CORS in many different ways but can't seem to change the `*` value, it's like it's being overwritten right at the end.

In the browser console I see the following error:
```
Access to fetch at 'http://localhost:4000/graphql' from origin 'https://studio.apollographql.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
```

**Comment by dborstelmann** [comment]
I just took my apollo gateway lambda out of the VPC I'm running in but left the subgraph apollo server lambdas in the vpc and it solved my problem, so my issue is unrelated.

**Comment by ecker00** [comment]
Figured it out! The `apollo.applyMiddleware()` also sets default CORS behaviour, overwriting the headers defined earlier.

Change the middleware line to this, and everything works as expected:
```
apollo.applyMiddleware({ app, path: "/api", cors: { origin: 'https://studio.apollographql.com', credentials: true } });
```

Note: This config should not be used in production, so be sure to make your CORS configurable for production environment.

**Comment by dwalker93** [comment]
@ecker00 You saved my time ton bro. Thank you. Also if you already configured cors using cors package you can set this as well,
`apollo.applyMiddleware({ app, path: "/api", cors: false});`
