### ISSUE TITLE
Nested resolvers get called even when data is already present

### ISSUE THREAD

**Issue by cesargdm** [apollographql/apollo-server#5881]
# Nested resolvers get called even when data is already present

## Version
"apollo-server": "3.5.0",
"apollo-server-express": "3.5.0",
"graphql": "15.6.1",

## Expected
For a given type definition

```gql
type Query {
  user: User
}

type User {
  name: String!
  bestFriend: User!
}
```

And with the resolvers:

```js
resolvers: {
  query: {
    user: (...) => ({ name 'Juan', bestFriend: { name: 'John' }})
  },
  user: {
    bestFriend: () => throw new Error(''),
  }
}
```

I would expect the user.bestFriend resolver not to be called since the root query is already returning all the fields that the user could request.

## Actual

The user.bestFriend resolver get's called even when no data is missing. I remember that this was not always the default behavior. Nerveless, I cannot find any configuration to indicate to give preference to the preexisting root resolver values.

https://codesandbox.io/s/dawn-cloud-drglo

**Comment by glasser** [comment]
The value returned from a resolvers for object-typed fields can be any value at all.  It's only the value returned from resolvers for scalar-typed fields (string, etc) that are directly returned in the response.  The semantics of that value are "it's the thing that gets passed as the first argument to the resolver of its fields".

The assumption that this value is an object with fields corresponding to the fields of its GraphQL type just comes from the fact that the *default* resolver for a field named `f` if you don't define your own resolver is "look up the `f` field on the first argument". But as soon as you define your own resolver, that doesn't happen.

I would be incredibly surprised to learn that this has ever been different.
