### ISSUE TITLE
request to http://engine-registry.prod.svc.cluster.local/api/graphql failed, reason: read ECONNRESET

### ISSUE THREAD

**Issue by aaronArinder** [apollographql/apollo-server#5887]
We have schema checks run in our deployment pipeline, and for a while now we've been getting `request to http://engine-registry.prod.svc.cluster.local/api/graphql failed, reason: read ECONNRESET` multiple times a day making the pipeline fail. I'm not sure what would be useful to know, so let me know how best to help troubleshooting.

- Potentially related issue: #4688
- We're running 3.5.0
- Being intermittent behavior, I'm not sure how to repro it; I'm hoping you'll be able to see the econnresets on your end

**Comment by glasser** [comment]
While this is a good question, schema checks aren't part of `apollo-server` (they run from Rover or the old `apollo` CLI).  I'll point the folks working on registry reliability at this issue, though.

**Comment by aaronArinder** [comment]
Shoot, sorry, I should have thought through that a little better. I'll open
an issue with them tomorrow. Thanks dude.
