### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by brampurnot** [apollographql/apollo-server#5903]
Hi all,

We are using custom directives and everything was working fine on version 2.25.2. Today we upgraded the apollo-server package to the latest version and we are getting this error message:
TypeError: Class extends value undefined is not a constructor or null

We are using NodeJS v12 and below is an example of a custom directive we have:
```
class PrivateDirective extends SchemaDirectiveVisitor {
  visitFieldDefinition(field) {
    const originalResolve = field.resolve || defaultFieldResolver;
    field.resolve = function(...args) {
      const context = args[2];
      const internal = context.internal;

      if(internal == null || internal == "null" || internal == "false") {
        throw new AuthenticationError(`This is an internal API and cannot be called externally`);
      }

      return originalResolve.apply(this, args);
    }
  }
}
module.exports = PrivateDirective;
```

Any idea what this could be? 

Thanks,
Bram

**Comment by trevor-scheer** [comment]
`SchemaDirectiveVisitor` is no longer exported by Apollo Server, please take a look at the migration guide if you run into any other issues with your v2->v3 migration.
