### ISSUE TITLE
ForbiddenError no longer appears to be an "instanceof" ForbiddenError

### ISSUE THREAD

**Issue by bcarriereupgrade** [apollographql/apollo-server#5920]
- Packages: `apollo-server@2.25.3, apollo-datasource@^0.9.0`
- Latest version where it did _not_ occur: `apollo-server@2.2.22, apollo-datasource-rest@^0.6.11`

### Expected Behaviour

`ForbiddenError` passed to `didEncounterError` as an argument should pass `error instanceOf ForbiddenError`
 
### Actual Behaviour

`error instanceOf ForbiddenError` evaluates to false.

### Scenario

I have created a custom REST data source class that looks something like this:

```js
const { RESTDataSource } = require('apollo-datasource-rest');
const { AuthenticationError, ForbiddenError } = require('apollo-server');

class FancyDataSource extends RESTDataSource {
  static isAuthenticationError(error) {
    return error instanceof AuthenticationError;
  }

  static isForbiddenError(error) {
    return error instanceof ForbiddenError;
  }

  didEncounterError(error) {
    const { user } = this.context;

    if (FancyDataSource.isAuthenticationError(error)) {
      this.log.error(`AuthenticationError thrown for user ${user.id}`);
    }

    // Forbidden errors are logged, but we keep going without throwing
    if (FancyDataSource.isForbiddenError(error)) {
      this.log.error(`ForbiddenError thrown for user ${user.id}`);
      return;
    }

    throw error;
  }
}

// Simulate an HTTP request that returns a 403 
```

Before upgrading to `apollo-server@2.25.3` which I think bumps up `apollo-datasource-rest` to 0.9.0 the code worked as expected. After upgrading, `isForbiddenError(error)` return false, and the error is thrown which has unwanted effects further up stack.

Doing some quick checks in the code I spotted this commit https://github.com/apollographql/apollo-server/commit/9964c98b6cde492593958ef3369eab6d4fe831c0#diff-1547f15677eee7e5e46a0bbf326e03f21a06a7913046181084f606d7f6c3e313 which may or may not be related to the error I'm encountering.

**Comment by glasser** [comment]
`apollo-datasource-rest` is not currently actively maintained, though we hope to fix that.

**Comment by glasser** [comment]
In Apollo Server 4, we have removed the ForbiddenError class. We encourage folks to check to see what kind of error an error is by looking at the `code` or other extensions rather than via (brittle, as you observe) `instanceof` checks. See https://www.apollographql.com/docs/apollo-server/migration/#built-in-error-classes for more details.
