### ISSUE TITLE
"apollo-server-lambda" doesn't publish schema and metrics

### ISSUE THREAD

**Issue by trsrm** [apollographql/apollo-server#5927]
I've set all the environment variables, but the schema is never published to Apollo Studio. Also, once I published schema manual, I was unable to set-up metrics publishing.

**Comment by trsrm** [comment]
Update: I tried to configure "Usage reporting plugin" and the `sendReportsImmediately: true` option did help.
https://www.apollographql.com/docs/apollo-server/api/plugin/usage-reporting/#sendreportsimmediately

Does it make sense to update the docs to explain all the extra steps needed?
https://www.apollographql.com/docs/apollo-server/deployment/lambda/

**Comment by glasser** [comment]
Sorry for the delay; some issues got caught up in the December whirlwind.

sendReportsImmediately: true should be the default if you're using `apollo-server-lambda`. If you can share a full reproduction showing that not to be the case, I'd be happy to look into it.
