### ISSUE TITLE
Error type is lost in plugins

### ISSUE THREAD

**Issue by tallpants** [apollographql/apollo-server#5936]
I'm sending in an incorrect query that fails with this error:

```json
{
    "errors": [
        {
            "message": "Int cannot represent non-integer value: \"3\"",
            "locations": [
                {
                    "line": 11,
                    "column": 31
                }
            ],
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED"
            }
        }
    ]
}
```

This should be a `ValidationError` because of the `GRAPHQL_VALIDATION_FAILED` code according to the docs: https://www.apollographql.com/docs/apollo-server/data/errors/#error-codes

If I log the error in `formatError`, I can see that it's a `ValidationError` as expected:

```
FormatError [ValidationError: Int cannot represent non-integer value: "3"] {
  locations: [ { line: 11, column: 31 } ],
  path: undefined,
  extensions: {
    code: 'GRAPHQL_VALIDATION_FAILED',
    exception: { stacktrace: [Array] }
  }
}
```

However, within plugins, the error type is a generic `GraphQLError` and the error code has also been lost. For this plugin code:

```ts
const myPlugin: ApolloServerPlugin = {
  async requestDidStart(requestContext) {
    return {
      async didEncounterErrors(requestContext) {
        for (const err of requestContext.errors) {
          console.log(JSON.stringify(err));
          console.log('err.extensions?.code', err.extensions?.code);
          console.log('err.name', err.name);
          console.log('err.originalError', err.originalError);
          console.log('err.message', err.message);
          console.log('err instanceof ValidationError', err instanceof ValidationError);
        }
      }
    };
  }
};
```

I get this in the console:

```
{
    "message": "Int cannot represent non-integer value: \"3\"",
    "locations": [
        {
            "line": 11,
            "column": 31
        }
    ]
}
err.extensions?.code undefined
err.name GraphQLError
err.originalError undefined
err.message Int cannot represent non-integer value: "3"
err instanceof ValidationError false
```

I've updated to latest everything, and tried different versions of apollo-server (apollo-server-lambda and apollo-server-fastify) and can replicate it on both.

For context, I'm trying to have different error tracking behaviour based on the type of the error.

**Comment by tallpants** [comment]
Seems like this is a known issue and would be better served as a feature request and not a bug?

https://community.apollographql.com/t/cant-always-get-extensions-property-of-error-in-didencountererrors/847

**Comment by alexkrolick** [comment]
Is error.originalError the correct type? It seems like the errors sent to plugins (didEncounterErrors lifecycle) are wrapped with GraphQLError and the ones sent to formatError another type.

**Comment by tallpants** [comment]
@alexkrolick originalError is undefined. Copy pasting from the 2nd comment link here:

Pre-execution validation errors are indeed handled by graphql(JS)'s validate function which is invoked by Apollo Server in the request pipeline just after parsing the operation.

When a validation error is observed after invoking validate (as determined by a non-zero length array being returned from validate), we:

- Invoke any callback that was returned from the validationDidStart hook (that callback is known as “validation did end” and receives an array of GraphQLErrors.
- Invoke the didEncounterErrors life-cycle hook with the same array of errors.

The native graphql (JS) error is not a ValidationError, which is an Apollo-specific response treatment that currently happens after these life-cycle events.

**Comment by glasser** [comment]
I'm not exactly sure why we have code that shoehorns validation errors to be `ValidationError`s when we pass them to the older formatErrors function but not when we pass them to the newer didEncounterErrors plugin function. That said, if you are trying to specially handle validation errors in a plugin it seems easier to just implement the validationDidStart end hook.

I don't think making this change in AS3 would be very backwards-compatible, but @IvanGoncharov is also thinking about ways to simplify the error classes in Apollo Server.
