### ISSUE TITLE
Incorrect Documentation for apollo-server-fastify

### ISSUE THREAD

**Issue by NexWasTaken** [apollographql/apollo-server#5943]
The documentation on the website for [integrating apollo into fastify](https://www.apollographql.com/docs/apollo-server/integrations/middleware/#apollo-server-fastify) has incorrect documentation. The return type of `fastifyAppClosePlugin` i.e. `ApolloServerPlugin ` is not imported from anywhere (and from what I could tell is not even exported by any package).

**Comment by mannyluvstacos** [comment]
Hey there @NexWasTaken!

`ApolloServerPlugin` is [an interface that is exported](https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-plugin-base/src/index.ts#L48-L58) by `apollo-server-plugin-base`

I was working on implementing a federated gateway based on fastify and did a little poking around to unblock myself.
I hope this information helps you as well!

**Comment by glasser** [comment]
Thanks! Fixed by merging #5966.

The sheer number of packages in this repository is overwhelming. We're planning to publish soon our plan for an Apollo Server 4 that trims it down to one core package (based on other things discussed over the past few years).

**Comment by mannyluvstacos** [comment]
> Thanks! Fixed by merging #5966.
> 
> The sheer number of packages in this repository is overwhelming. We're planning to publish soon our plan for an Apollo Server 4 that trims it down to one core package (based on other things discussed over the past few years).

Awesome! I am looking forward to those plans!
Anything folks in the community may be able to help with @glasser?

**Comment by glasser** [comment]
I think so! Part of the plan will be (as per #3184) having a single well-defined interface for integrating any web framework with Apollo Server. As part of that, we'll move away from the status quo where the core team needs to actively maintain many specific integrations (despite the fact that we personally only have hands-on production experience with a few of them) to a world where more of the integrations are community-maintained.  So one of the biggest ways we can get help from the community will be for folks who are passionate about particular web frameworks to help/lead the maintenance of their favorite framework's integrations.  More details to come!
