### ISSUE TITLE
buildSubgraphSchema expected inputs

### ISSUE THREAD

**Issue by torohaifisch** [apollographql/apollo-server#5944]
Package versions:
  apollo-server-core: 3.5.0
  apollo-server-koa: 3.5.0
  @apollo/subgraph: 0.1.5

Hello i started using apollo server to understand how it worked but my real intentions were to implement apollo federation. Apollo server works, schemas resolvers and sandbox all work. The trouble is the change to a subgraph schema, the documentation shows it like  some simple steps: 
- install apollo subgraph
- import buildSubgraphSchema 
- use this method with your schema and resolvers 

With apollo server i use makeExecutableSchema from the package graphql-tools/schema, passing my schema and resolvers as shown in the demo code and everything works fine, replacing this with buildSubgraphSchema breaks everything. So it seems that the arguments arent compatible.

There are 2 errors: 
**TypeError: Cannot read property 'kind' of undefined** This is solved importing gql and adding it to the typedef strings

The second error is that the resolvers dont work. i dont know how to solve this in a proper way. Resolvers arent implemented in the demo code but i know they dont work because i have them implemented in my own code.

this issue was reported here last year: https://github.com/apollographql/apollo-server/issues/3602 but was closed without resolution. i report this here because i couldnt find anything in the docs or anywhere else. the only thing i found is that closed issue.

thanks in advance

Minimal Reproduction code: https://codesandbox.io/s/hidden-river-m7jpx?file=/src/index.js:144-163&resolutionWidth=320&resolutionHeight=675 

i recommend downloading the code and run it with npm start and replacing the methods when necesary for testing.

**Comment by trevor-scheer** [comment]
Thanks for the reproduction @torohaifisch. The last comment on the issue you linked is the correct way to go about this. You're correct that our API isn't 1:1 with `makeExecutableSchema`, but it only requires a minor change to adapt it to ours.

`buildSubgraphSchema` accepts an array of `GraphQLModule` which is of the shape `{ typeDefs, resolvers }`.

I forked your sandbox and made the changes here:
https://codesandbox.io/s/prod-wildflower-f1g88?file=/src/index.js:422-586
