### ISSUE TITLE
'Failed to Fetch' error-message after migrating to apollo-server-lambda v3

### ISSUE THREAD

**Issue by mikeyfe6** [apollographql/apollo-server#5946]
I have this issue where I just cannot figure out whats happening..

Does it have something to do with **CORS** or the way my function is wrote (*without async/await*)?

```
const server = new ApolloServer({
  typeDefs,
  resolvers,

  context: ({ context }) => {
    if (context.clientContext.user) {
      return { user: context.clientContext.user.sub };
    }
    return {};
  },

  // playground
  // plugins: [
  //   process.env.NODE_ENV === 'production'
  //     ? ApolloServerPluginLandingPageDisabled()
  //     : ApolloServerPluginLandingPageGraphQLPlayground(),
  // ],

  plugins: [ApolloServerPluginLandingPageGraphQLPlayground()],
  introspection: true,
});


// exports.graphqlHandler = server.createHandler();

exports.handler = server.createHandler({
  expressGetMiddlewareOptions: {
    cors: {
      origin: true,
      credentials: true,
    },
  },
});
```

[![Errormessage CORS][1]][1]

  [1]: https://i.stack.imgur.com/c3CJa.png

**Comment by glasser** [comment]
Sorry for the delay; there were some holidays and vacations etc and this ended up down the stack.

This looks correct to me (though `origin: true` is also the default in AS3). This doesn't have enough details to debug, unfortunately.

Apollo Server Lambda is designed to be run on AWS Lambda. Perhaps it doesn't work on Netlify — does Netlify have a Lambda-compatible environment?

**Comment by glasser** [comment]
Upon a bit of research: apollo-server-lambda doesn't have any code of its own to parse AWS Lambda events (of which there are a bunch of different formats depending on which particular AWS project you're using); instead, we rely on the `@vendia/serverless-express` package to do that work. I see that this package has https://github.com/vendia/serverless-express/issues/427 open which contains some workarounds. However I suspect they would also take a PR to improve their detection of the Netlify pseudo-Lambda environment!

(Note that in Apollo Server 4 it will be easier to build a Netlify Functions-specific integration for AS if that's a good idea.)
