### ISSUE TITLE
How can I route my rest api request to my subgraph in apollo federation?

### ISSUE THREAD

**Issue by Javadebi** [apollographql/apollo-server#5958]
Hello Im currently using apollo-server-fastify and I have some get methods for updating my database with lambda function,
for example:

`app.get("/api/get-list-inventory-supplies", async (request, reply) => {
  try {
    await getInventorySupply();
    console.log("success");
  } catch (err) {
    console.log(err);
  }
  return "Success";
});
`

How can I use this method with apollo federation because I get this error when I want to use my get method:

message":"Route GET:/api/get-list-inventory-supplies","error":"Not Found","statusCode":404}

**Comment by glasser** [comment]
Sorry for the delay; there were some holidays and vacations etc and this ended up down the stack.

I don't think there should be much different about accessing a REST endpoint in a federated subgraph than in a different kind of graph. If you can share a complete minimal reproduction (as a git repo, codesandbox.io, etc) that shows the thing that works and the thing that doesn't work without any extra information, I'd be happy to dig into it.
