### ISSUE TITLE
Error thrown in the parseLiteral method of custom scalars is of type ValidationError

### ISSUE THREAD

**Issue by sadokmtir** [apollographql/apollo-server#5964]
Throwing a `UserInputError` inside `parseLiteral` from custom scalar, creates an error of type `ValidationError` and not `UserInputError`.

The one from `parseValue` is of type `UserInputError`. I would expect the same from `parseLiteral`.

Example:
```typescript
const dateScalar = new GraphQLScalarType({
  name: 'Date',
  description: 'Date custom scalar type',
  serialize(value) {
    return value.getTime(); // Convert outgoing Date to integer for JSON
  },
  parseValue(value) {
    throw new UserInputError('Provided value is not an odd integer');  // this is of type `UserInputError`
  },
  parseLiteral(ast) {
    throw new UserInputError('Provided value is not an odd integer');  // this is of type `ValidationError`
  },
});
```
I would expect that:

```typescript
expect(res.errors).toBeDefined();
expect(res.errors![0]).toBeInstanceOf(UserInputError);
```
But unfortunately the error type is `ValidationError` is this intentional ??

**Comment by glasser** [comment]
parseLiteral is called for literals in the actual GraphQL document, whereas parseValue is called for variable values.

It's generally best practice to use static operation documents in your client and only put end-user input into variable values, just like how when using SQL you shouldn't manually construct a SQL query with end-user input in strings.  So it makes sense to consider a problem in the operation document as a validation issue (similar to using a field of the wrong type in the document) and a problem in variables as a user input issue.
