### ISSUE TITLE
bug in apollo-server-plugin-response-cache

### ISSUE THREAD

**Issue by kodeine** [apollographql/apollo-server#5965]
Getting an error, any idea's? 

```
{"stacktrace":["TypeError: Cannot read properties of null (reading 'cachePolicy')","    at cacheGet (/Projects/service-gateway/node_modules/apollo-server-plugin-response-cache/src/ApolloServerPluginResponseCache.ts:177:61
```

**Comment by glasser** [comment]
What version of this package and other Apollo Server packages are you using?

**Comment by kodeine** [comment]
@glasser Thank you for taking interest in this, following is the package.json
```
"dependencies": {
    "@apollo/gateway": "^0.42.0",
    "@nestjs/common": "8.2.1",
    "@nestjs/config": "1.1.0",
    "@nestjs/core": "8.2.1",
    "@nestjs/graphql": "9.1.1",
    "@nestjs/microservices": "8.2.1",
    "@nestjs/platform-express": "8.2.1",
    "apollo-server-cache-redis": "3.3.0",
    "apollo-server-plugin-response-cache": "3.4.0",
    "class-transformer": "0.4.0",
    "class-validator": "0.13.1",
    "graphql": "15.7.2",
    "helmet": "4.6.0",
    "http-proxy-middleware": "2.0.0",
    "ioredis": "^4.28.2",
    "joi": "17.4.0",
    "jsonwebtoken": "8.5.1",
    "reflect-metadata": "0.1.13",
    "rimraf": "3.0.2",
    "rxjs": "7.2.0",
    "uuid": "^8.3.2"
  },
```


```
export const redisCache: Redis = new Redis({
  host: process.env.REDIS_HOST,
  port: process.env.REDIS_PORT,
  password: process.env.REDIS_PASSWORD,
  options: {
    connectionName: process.env.APP_NAME,
  },
});

......
        gateway: {
          serviceList: config.get('SERVICES_LIST'),
        },
        server: {
          playground: config.get('NODE_ENV') === 'development',
          cache: redisCache,
          persistedQueries: {
            cache: new BaseRedisCache({
              client: redisCache,
            }),
          },
          plugins: [
            ApolloServerPluginCacheControl({ defaultMaxAge: 300 }),
            responseCachePlugin({ cache: redisCache }),
          ],
```

**Comment by glasser** [comment]
Can you share your full package-lock.json? Nest makes it hard to tell what
versions you are using.

**Comment by kodeine** [comment]
@glasser  attached is the package-lock file.

[package-lock.json.zip](https://github.com/apollographql/apollo-server/files/7772248/package-lock.json.zip)

**Comment by glasser** [comment]
One thing I'm seeing is that you have a copy of `apollo-server-core` v2 installed below `@ntegral/nestjs-sentry` (you end up with two copies of `@nestjs/graphql`, one v8 and one v9. It looks like `@ntegral/nestjs-sentry@3.0.7` (released this week) relaxes its dependency to allow v9 of `@nestjs/graphql`, so upgrading to that should hopefully clear up the "two copies of Apollo Server" problem.

If you're still having issue once there's no apollo-server-core v2 in your package-lock.json, please turn this into a minimal reproduction by shrinking your project to the smallest size possible that still shows the issue and providing us with clear reproduction steps that require no creativity to apply (typically starting with `git clone` or looking at a codesandbox.io sandbox). I'll be happy to reopen the issue if there's an easy reproduction.

BTW, it looks like what is happening is that the literal string `null` is getting stored in your cache somehow, which seems pretty surprising.
