### ISSUE TITLE
apollo-server-lambda Never Shows GraphQL Playground

### ISSUE THREAD

**Issue by ngoctranfire** [apollographql/apollo-server#5970]
Hi there,
I am using serverless to deploy with `apollo-server-lambda`, but the version I am using is: `.3.5.0`. However, even when I set the playground settings to `true`, or with 
```
playground: {
    endpoint: "/dev/graphql"
  }
```

I did both options, but I can't seem to have access to the playground. Instead, I get the default screen that encourages me to use the Apollo Studio to query my plugin. Do you have any way for me to figure out what is going on?

I feel that this seems like a bug.

**Comment by glasser** [comment]
The top-level playground option was removed in AS3. (I recommend using
TypeScript which would have made this into a clear compile error.) See the
migration guide for how to re-enable it (though I personally recommend
migrating away from Playground, as its maintainers have officially retired
it).
https://www.apollographql.com/docs/apollo-server/migration/#graphql-playground
