### ISSUE TITLE
I'm getting "message": "Cannot read properties of undefined (reading 'xxx')", in Apollo Studio after upgrade to Apollo v3 and enabling subscriptions

### ISSUE THREAD

**Issue by NicoSan20** [apollographql/apollo-server#5982]
I'm working on a project based on this starter kit [fullstack-apollo-express](https://github.com/the-road-to-graphql/fullstack-apollo-express-postgresql-boilerplate) and now I would like to update all dependencies.

With apollo-server v2 everythings works well (with `installSubscriptionHandlers()`), but after migrating to apollo-server v.3 and enabling the subscriptions as documented in the [official documentation](https://www.apollographql.com/docs/apollo-server/data/subscriptions/) , the result of the subscription works but is not complete when doing submitting a subscription from Apollo Studio.

Here the subcription :
```
subscription {
  messageCreated {
    message {
      id
      text
      createdAt
      user {
        id
        username
      }
    }
  }
}
```
As you can see, the result failed with the message "Cannot read properties of undefined (reading 'User')" :
```
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'User')",
      "locations": [
        {
          "line": 7,
          "column": 7
        }
      ],
      "path": [
        "messageCreated",
        "message",
        "user"
      ]
    }
  ],
  "data": null
}
```
But if I remove the user part it works fine :
```
subscription {
  messageCreated {
    message {
      id
      text
      createdAt
    }
  }
```
Result :
```
{
  "data": {
    "messageCreated": {
      "message": {
        "id": "4",
        "text": "Does my subscription work?",
        "createdAt": "2018-10-25T08:56:04.786Z"
        }
      }
    }
  }
}
```
With Apollo v2 and the subscription method `server.installSubscriptionHandlers()` all was working well and "User" information was also returned.

Here now my server with Apollo v3 :
```
Here my server :
//...
import {
  ApolloServer,
  AuthenticationError,
} from 'apollo-server-express';
import { createServer } from 'http';
import { execute, subscribe } from 'graphql';
import { SubscriptionServer } from 'subscriptions-transport-ws';
import { makeExecutableSchema } from "@graphql-tools/schema";

//...

    const schema = makeExecutableSchema({ typeDefs: schemas, resolvers });

    const subscriptionServer = SubscriptionServer.create(
      { schema, execute, subscribe },
      { server: httpServer, path: '/graphql' }
    );
  

    const server = new ApolloServer({
      schema,
      plugins: [{
        async serverWillStart() {
          return {
            async drainServer() {
              subscriptionServer.close();
            }
          };
        }
      }],

//...
```
Subscription :
```
import { PubSub } from 'graphql-subscriptions';

import * as MESSAGE_EVENTS from './message';

export const EVENTS = {
  MESSAGE: MESSAGE_EVENTS,
};

export default new PubSub();
```
Schema :
```
//...
extend type Subscription {
  messageCreated: MessageCreated!
}

type MessageCreated {
  message: Message!
}
```
Resolver :
```
//...
  Mutation: {
    createMessage: combineResolvers(
      isAuthenticated,
      async (parent, { text }, { models, me }) => {
        const message = await models.Message.create({
          text,
          userId: me.id,
        });

        pubsub.publish(EVENTS.MESSAGE.CREATED, {
          messageCreated: { message },
        });

        return message;
      },
    ),

//...

  Subscription: {
    messageCreated: {
      subscribe: () => pubsub.asyncIterator(EVENTS.MESSAGE.CREATED),
    },
  },
};
```
Thank you in advance for your help. If you need more details about the source code you can have a look into the git repository of this [project](https://github.com/the-road-to-graphql/fullstack-apollo-express-postgresql-boilerplate)

**Comment by polo13999** [comment]
the same here

**Comment by glasser** [comment]
I'd love to help you figure out how to upgrade your project to Apollo Server 3, but I can't help without the ability to reproduce the issue myself.  (The error message makes it seem like the issue is happening inside the `user` resolver which is not part of what you shared, for example.)

If you are able to share this issue in a form where I can reproduce it by following a few steps (perhaps starting with `git clone` or going to a codesandbox.io sandbox) without creativity I'd be happy to reopen this issue and put some time into trying to figure out what's going on.

**Comment by NicoSan20** [comment]
@glasser : Thank you for your time and your reply.

I put the project in a git directory which will allow you to do your tests. The only constraint is to have a postgres server available.

Here is the git directory : [apollo3-subscriptions-issue](https://github.com/NicoSan20/apollo3-subscriptions-issue)

Once you have made the `git clone`, you will have to install the dependencies with `npm install`. After that you must also to enter the information of your postgres server in the `.env` file.

At this step you can start the project with `npm start`.

Now to reproduce the issue you need to create a new message with a logged in user. You can try both these GraphQL operations in two separate tabs in Apollo Studio at `http://localhost:8000/graphql` to compare their output.

In the first tab, execute the subscription :
```
subscription {
  messageCreated {
    message {
      id
      text
      createdAt
      user {
        id
        username
      }
    }
  }
}
```
Results will indicate the tab is listening for changes. In the second tab, log in a user :
```
mutation {
  signIn(login: "rwieruch", password: "rwieruch") {
    token
  }
}
```
Copy the token from the result, and then paste it to the HTTP headers panel in the same tab :
```
{
  "x-token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJoZWxsb0Byb2Jpbi5jb20iLCJ1c2VybmFtZSI6InJ3aWVydWNoIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNTM0OTQ3NTYyLCJleHAiOjE1MzQ5NDkzNjJ9.mg4M6SfYPJkGf_Z2Zr7ztGNbDRDLksRWdhhDvTbmWbQ"
}
```
Then create a message :
```
mutation {
  createMessage(text: "Does my subscription work?") {
    text
  }
}
```
The expected result should be :
```
{
  "data": {
    "messageCreated": {
      "message": {
        "id": "4",
        "text": "Does my subscription work?",
        "createdAt": "2022-01-07T08:56:04.786Z",
        "user": {
          "id": "1",
          "username": "rwieruch"
        }
      }
    }
  }
}
```
But instead I have the following result :
```
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'User')",
      "locations": [
        {
          "line": 7,
          "column": 7
        }
      ],
      "path": [
        "messageCreated",
        "message",
        "user"
      ]
    }
  ],
  "data": null
}
```
I'm not an expert and I ask you to be indulgent with the information that I have just provided.

Hope you can help me to solve this issue. Thank you so much in advance for your help. Rgds.

**Comment by adostal** [comment]
Hello, I think that in "SubscriptionServer.create" you must return context in: onConnect: async () => { return context; }

**Comment by NicoSan20** [comment]
@adostal : Thank you for your message, but I don't sure to understand, sorry.

For more information and as I write in my first post, the subscription works fine. Example, if I remove the "user" part from the subscription :
```
subscription {
  messageCreated {
    message {
      id
      text
      createdAt
    }
  }
```
Result :
```
{
  "data": {
    "messageCreated": {
      "message": {
        "id": "4",
        "text": "Does my subscription work?",
        "createdAt": "2022-01-07T08:56:04.786Z"
        }
      }
    }
  }
}
```
With Apollo v2 and the subscription method `server.installSubscriptionHandlers()` all was working well and "User" information was also returned. Now with Apollo v3 it works halfway.

**Comment by adostal** [comment]
If you use context in resolvers:
```typescript
changeData: {
   subscribe: (root, args, context) => context.xxx,
}
```
You must return this context in "SubscriptionServer.create":

```typescript
SubscriptionServer.create ({
  execute,
  subscribe,
  diagram,
  onConnect: async () => {
    return {} // context
  }
})
```

**Comment by NicoSan20** [comment]
@adostal : Thank you for your reply and for those details, now I understand better. But I don't know how to adapt it, I have tried several ways, but without success.

Based on my project [apollo3-subscriptions-issue](https://github.com/NicoSan20/apollo3-subscriptions-issue). Would you be willing to help me ? I would appreciate it a lot, because I am a beginner.

Thank you for your patience.

**Comment by adostal** [comment]
What is the exact wording of that error message?

**Comment by NicoSan20** [comment]
@adostal 

```
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'User')",
      "locations": [
        {
          "line": 7,
          "column": 7
        }
      ],
      "path": [
        "messageCreated",
        "message",
        "user"
      ]
    }
  ],
  "data": null
}
```

**Comment by adostal** [comment]
You can try modify (resolvers/message.js):

```javascript
  Subscription: {
    messageCreated: {
      subscribe: () => pubsub.asyncIterator(EVENTS.MESSAGE.CREATED),
    },
  },
```

to
```javascript
  Subscription: {
    messageCreated: {
      resolve: (msg) => msg,
      subscribe: () => pubsub.asyncIterator(EVENTS.MESSAGE.CREATED),
    },
  },
```

or check:
```javascript
  Message: {
    user: async (message, args, { models }) => {
      console.log('models: ', models);
      return await models.User.findByPk(message.userId);
    },
  },
```

**Comment by NicoSan20** [comment]
@adostal : Thank you for your time.

I adapted the code as you suggested. Here the result of the subscription 
```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field MessageCreated.message.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "messageCreated",
        "message"
      ]
    }
  ],
  "data": null
}
```
And no message back from console.log

**Comment by glasser** [comment]
@NicoSan20 It sounds like @adostal is doing a great job of helping you integrate subscriptions-transport-ws into your app, so I'm going to hold off on researching this myself.

For what it's worth, we will hopefully be changing the recommended subscription library from the old unmaintained `subscriptions-transport-ws` to the newer actively maintained `graphql-ws` pretty soon.

**Comment by NicoSan20** [comment]
@glasser : Thanks for your reply. I hope that the `graphql-ws` library will be very soon compatible with GraphQL Playground Express Middleware, because currently there is still compatibility issue with subprotocols.

I have read on the internet that many people are not upgrading to apollo-server v.3 yet due to incompatibility with subscriptions. Too sad that you give it up.

@adostal : What if we just tried `subscriptions-transport-ws backwards` compatibility, could that be a solution ? I just tried to adapt the code like this :

```
//...
import schemas from './schema';
//...
(async function () {
    const app = express();

    app.use(cors());

    const getMe = async req => {
      const token = req.headers['x-token'];
    
      if (token) {
        try {
          return await jwt.verify(token, process.env.SECRET);
        } catch (e) {
          throw new AuthenticationError(
            'Your session expired. Sign in again.',
          );
        }
      }
    };

    const server = new ApolloServer({
      typeDefs: schemas,
      resolvers,
      context: async ({ req, connection }) => {
        if (connection) {
          return {
            models,
          };
        }
        if (req) {
        const me = await getMe(req);
        return {
          models,
          me,
          secret: process.env.SECRET,
        };
      }
      },
    });
    await server.start();
    server.applyMiddleware({ app, path: '/graphql' });

      const httpServer = createServer(app);

      httpServer.listen({ port: 8000 }, () => {
          new SubscriptionServer({
            execute,
            subscribe,
            schema: schemas,
          }, {
            server: httpServer,
            path: '/graphql',
          });
          console.log('Server ready at http://localhost:8000/graphql');
      });
})();
```
But when I try the subscribe I get this error :
```
{
  "message": "Expected [{ kind: \"Document\", definitions: [Array], loc: [Object] }, { kind: \"Document\", definitions: [Array], loc: [Object] }, { kind: \"Document\", definitions: [Array], loc: [Object] }] to be a GraphQL schema."
}
```
Apparently I have a problem with the way I declare the schema in `new SubscriptionServer`.

Here is my file which contains the schemas, I think it does not like that the export will be in an array ?!?
```
import { gql } from 'apollo-server-express';

import userSchema from './user';
import messageSchema from './message';

const linkSchema = gql`

scalar Date

  type Query {
    _: Boolean
  }

  type Mutation {
    _: Boolean
  }

  type Subscription {
    _: Boolean
  }
`;

export default [linkSchema, userSchema, messageSchema];
```

I admit I'm a bit lost here. I don't really know what to do anymore.

Thank you again for your helps.

**Comment by glasser** [comment]
As of this week, Apollo Studio's Explorer UI supports graphql-ws; we will be updating the Server docs soon to encourage use of graphql-ws over subscriptions-transport-ws now that we can show how to use it.

**Comment by NicoSan20** [comment]
@glasser : Thank you for your reply and for this good news.

I just installed `graphql-ws` with the following official documentation : [ws server usage with Apollo Server Express](https://github.com/enisdenjo/graphql-ws#apollo-server-express)

But when I run the subscription from Apollo Studio's Explorer I have the following error on the server :
```
WebSocket protocol error occured. It was most likely caused due to an unsupported subprotocol "graphql-ws" requested 
by the client. graphql-ws implements exclusively the "graphql-transport-ws" subprotocol, please make sure that the 
client implements it too.
```
Here are the versions I use :
```
apollo-server@3.6.1
apollo-server-express@3.6.1
graphql-ws@5.5.5
```
Do you have any idea what I'm doing wrong ? Thanks in advance.

**Comment by NicoSan20** [comment]
@adostal : After some research, I confirm that you are on the right way.

`models` is undefined at this point
```
  Message: {
    user: async (message, args, { models }) => {
      return await models.User.findByPk(message.userId);
    },
  },
```
With Apollo v2 and the subscription method `server.installSubscriptionHandlers()` all was working well, but now whether it's with backwards compatibility or with graphql-ws I have the same issue. But I don't know how to transmit `models `informations.

Do you have any last idea to fix it ? Thank you again for your patience.

**Comment by khofesh** [comment]
I encountered the same problem today.

here's the schema

```
import { gql } from 'apollo-server-express';

export default gql`
  extend type Query {
    messages(cursor: String, limit: Int): MessageConnection!
    message(id: ID!): Message!
  }

  extend type Mutation {
    createMessage(text: String!): Message!
    deleteMessage(id: ID!): Boolean!
  }

  extend type Subscription {
    messageCreated: MessageCreated!
  }

  type MessageCreated {
    message: Message!
  }

  type MessageConnection {
    edges: [Message!]!
    pageInfo: PageInfo!
  }

  type PageInfo {
    hasNextPage: Boolean!
    endCursor: String!
  }

  type Message {
    id: ID!
    text: String!
    createdAt: Date!
    user: User!
  }
`;

```

and here's the resolvers:

```
import { combineResolvers } from 'graphql-resolvers';
import Sequelize from 'sequelize';
import { isAuthenticated, isMessageOwner } from './authorization';
import pubsub, { EVENTS } from '../subscription';

const toCursorHash = (string) =>
  Buffer.from(string).toString('base64');

const fromCursorHash = (string) =>
  Buffer.from(string, 'base64').toString('ascii');

export default {
  Query: {
    messages: async (parent, { cursor, limit = 100 }, { models }) => {
      const cursorOptions = cursor
        ? {
            where: {
              createdAt: {
                [Sequelize.Op.lt]: fromCursorHash(cursor),
              },
            },
          }
        : {};

      const messages = await models.Message.findAll({
        order: [['createdAt', 'DESC']],
        limit: limit + 1,
        ...cursorOptions,
      });

      const hasNextPage = messages.length > limit;
      const edges = hasNextPage ? messages.slice(0, -1) : messages;

      return {
        edges,
        pageInfo: {
          hasNextPage,
          endCursor: toCursorHash(
            edges[edges.length - 1].createdAt.toString(),
          ),
        },
      };
    },
    message: async (parent, { id }, { models }) => {
      return await models.Message.findByPk(id);
    },
  },

  Mutation: {
    createMessage: combineResolvers(
      isAuthenticated,
      async (parent, { text }, { me, models }) => {
        try {
          const message = await models.Message.create({
            text,
            userId: me.id,
          });

          console.log('message', message);

          pubsub.publish(EVENTS.MESSAGE.CREATED, {
            messageCreated: { message },
          });

          return message;
        } catch (error) {
          throw new Error(error);
        }
      },
    ),
    deleteMessage: combineResolvers(
      isAuthenticated,
      isMessageOwner,
      async (parent, { id }, { models }) => {
        return await models.Message.destroy({ where: { id } });
      },
    ),
  },

  Message: {
    user: async (message, args, { models }) => {
      console.log('models: ', models);
      return await models.User.findByPk(message.userId);
    },
  },

  Subscription: {
    messageCreated: {
      subscribe: (parent, args, context) => {
        return pubsub.asyncIterator([EVENTS.MESSAGE.CREATED]);
      },
    },
  },
};

```
