### ISSUE TITLE
(docs) Migration to Apollo Server 3 schemaDirectives is out of date

### ISSUE THREAD

**Issue by Tohaker** [apollographql/apollo-server#5996]
The existing docs specify that the developer may simply pass the `schemaDirectives` object into `makeExecutableSchema`, however this is not supported in the latest version of `graphql-tools`.

At the risk of jumping the gun, I propose the following change and if all looks good I can raise it as a PR:

---

### `schemaDirectives`

In Apollo Server 2, you can pass `schemaDirectives` to `new ApolloServer` alongside `typeDefs` and `resolvers`. These arguments are all passed through to the [`makeExecutableSchema` function](https://www.graphql-tools.com/docs/generate-schema/#makeexecutableschemaoptions)  from the `graphql-tools` package. `graphql-tools` now considers `schemaDirectives` to be a [legacy feature](https://www.graphql-tools.com/docs/legacy-schema-directives/).

In Apollo Server 3, the `ApolloServer` constructor now only passes `typeDefs`, `resolvers`, and `parseOptions` through to `makeExecutableSchema`.

To create a schema with directives, you can pass the schema generated by `makeExecutableSchema` to the directives you wish to use.

That is, you can replace:

```javascript
new ApolloServer({
  typeDefs,
  resolvers,
  schemaDirectives,
});
```

with:

```javascript
import { makeExecutableSchema } from '@graphql-tools/schema';
import { renameDirective } from 'fake-rename-directive-package'

let schema = makeExecutableSchema({
  typeDefs,
  resolvers,
});
 
schema = renameDirective('rename')(schema);

new ApolloServer({
  schema,
});
```

This is described in further detail in the [graphl-tools documentation](https://www.graphql-tools.com/docs/schema-directives)

**Comment by glasser** [comment]
Thanks for pointing this out. I took a slightly different approach in https://github.com/apollographql/apollo-server/pull/6000

Does that look correct to you?
