### ISSUE TITLE
Subscriptions in apollo-server 3

### ISSUE THREAD

**Issue by lohnsonok** [apollographql/apollo-server#6020]
Please release a support for graphql subscriptions

**Comment by trevor-scheer** [comment]
Subscription support isn't built in to AS3, but there's nothing stopping you from adding the support in yourself (AS2 just used to do it for you). The [subscription docs](https://www.apollographql.com/docs/apollo-server/data/subscriptions/) will walk you through this.

**Comment by glasser** [comment]
Agree with @trevor-scheer . Some other notes:

- The docs he linked note that the package suggested there (`subscriptions-transport-ws`) is unmaintained. We plan to update the docs to suggest using the newer `graphql-ws` instead soon (we are working on improving client support for that package as well).
- We are going to be posting an Apollo Server 4 roadmap in the next few days, which includes a major rearchitecture which will make fully integrated subscriptions support (unlike the superficial integration that Apollo Server 2 had) feasible.

**Comment by lohnsonok** [comment]
> 

Ok where can I watch the roadmap for AS4 release please ? Very excited

**Comment by glasser** [comment]
https://github.com/apollographql/apollo-server/blob/main/ROADMAP.md
