### ISSUE TITLE
 Property 'extensions' does not exist on type 'ApolloServerExpressConfig'.

### ISSUE THREAD

**Issue by naveennagan** [apollographql/apollo-server#6024]
When i upgraded  apollo-server-express from 2.1.1 to 3.6.2
it shows the following error when i try to use extensions from ApolloServerConfig.

**Property 'extensions' does not exist on type 'ApolloServerExpressConfig'.
How do we access extensions in the latest version ?**

```
import { ApolloServerExpressConfig } from 'apollo-server-express';
export function mergeExtensions(
  kernelDefaultApolloConfig: ApolloServerExpressConfig,
  kernelInputApolloConfig: ApolloServerExpressConfig
) {
  return kernelDefaultApolloConfig.extensions
    ? kernelDefaultApolloConfig.extensions.concat(kernelInputApolloConfig.extensions || [])
    : kernelInputApolloConfig.extensions;
}
```

**Comment by glasser** [comment]
See the [migration docs](https://www.apollographql.com/docs/apollo-server/migration/#extensions)

`extensions` is an old mechanism for building plugins that is less powerful, flexible, and consistent than the plugin API introduced in v2.2.0 in 2018.

The code you're showing just shows how you merge together two lists of extensions; what extensions are you actually using? Built-in ones or ones you made yourself?
