### ISSUE TITLE
Call for maintainers: apollo-server-fastify

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#6027]
As described in [the roadmap](https://github.com/apollographql/apollo-server/blob/main/ROADMAP.md), Apollo Server 4 will shift from the model of "9 web framework integrations maintained by a team who only uses one of them and nope, you can't create your own" to "a stable web framework integration API that anyone can use for their favorite web framework".

As part of this, the Apollo Server core team is no longer planning to maintain `apollo-server-fastify`. We think users of this package are best served if their framework integration is maintained by a team of people who use Fastify every day.

This is where you come in! Do you love Fastify? Do you use it with Apollo Server? Would you like to be part of a team of community members who maintain `apollo-server-fastify`?

If so, chime in below! We'd love to find a group of people who will maintain the Apollo Server 4 version of `apollo-server-fastify`, and to help us maintain the section of the Apollo Server docs that shows how to use Apollo Server with Fastify.

We expect that maintaining this package will be more straightforward than maintaining an Apollo Server integration today, because its only responsibility will be translating Fastify's HTTP request and response objects to the formats used by Apollo Server's new API.

At the time that this issue is opened, we are actively looking for interested collaborators; however, the API you'll be implementing isn't yet ready. We can use this issue to get a team together who can get started at some point between an initial alpha release of the new `@apollo/server` package and the final v4.0.0 release.

**Comment by yorch** [comment]
@glasser would love to help!

**Comment by yorch** [comment]
@trevor-scheer hey, thanks for reaching out! certainly, happy to help and get involved!

**Comment by trevor-scheer** [comment]
Awesome, send me an email and we'll go from there.
trevor@apollographql.com

**Comment by trevor-scheer** [comment]
This package is in active development over [here](https://github.com/apollo-server-integrations/apollo-server-integration-fastify) and is published under the package name `@as-integrations/fastify`.

If you're interested in participating in the project, please feel free to get involved!
