### ISSUE TITLE
Gateway fetching uplink indefinitely

### ISSUE THREAD

**Issue by Nicoowr** [apollographql/apollo-server#6036]
(Originally posted in [federation](https://github.com/apollographql/federation/issues/1405) repo but I was told it was more relevant to post it here)

# Latest versions it didn't occur
```
    "@apollo/federation": "0.29.0",
    "@apollo/gateway": "0.38.0",
```

# Current versions
```
    "@apollo/gateway": "0.45.1",
    "@apollo/subgraph": "0.1.5",
```

# Set-up
Everything is hosted on AWS Lambda (Gateway & Subservices)

# Expected behavior
Setting `schemaConfigDeliveryEndpoint: undefined` in gateway config should keep the old behavior, namely not fetching the supergraph from uplink.

# Actual behavior
Setting `schemaConfigDeliveryEndpoint: undefined` does not always prevent the gateway from fetching the supergraph from uplink. When it does, the post requests do not succeed and the gateway continues to fetch until it times out:

![Screenshot 2022-01-19 at 16 59 51](https://user-images.githubusercontent.com/28652231/150169087-7591bc73-6436-45d1-a955-576604f2c393.png)

This might be linked to [this](https://github.com/apollographql/federation/issues/949)

**Comment by glasser** [comment]
Actually I think federation was the right place: I'll respond over there in https://github.com/apollographql/federation/issues/1405
