### ISSUE TITLE
New HTTP request execution API

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-server#6038]
Full details in https://github.com/apollographql/apollo-server/blob/main/ROADMAP.md

This is all described well in #3184, though that also covers some other issues in the 4.0 milestone..

**Comment by glasser** [comment]
We're feeling good about the state of the API! Leaving open #6528 for a moment to just double check that everything exported from externalTypes looks good (and maybe to move errors and expressMiddleware to nested imports).
