### ISSUE TITLE
Combine many packages into a single `@apollo/server`

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#6041]
We believe we can combine the following packages into a single `@apollo/server` package:
- `apollo-server-core`
- `apollo-server` (the "batteries-included" package --- we are looking forward to never having to type this phrase again)
- `apollo-server-plugin-base`
- `apollo-server-types`
- `apollo-server-express`
- `apollo-server-errors`
- `apollo-reporting-protobuf`

We should consider whether it makes sense to keep some of the stuff from `apollo-server-types` and `apollo-server-plugin-base` in a separate type-only `@apollo/server-types` package so that TS packages that implement plugins (and the gateway interface, etc) don't need a full dependency on `@apollo/server`; if so we should probably keep this repository as a monorepo but we won't need strict version locking and can still migrate from lerna to changesets.

**Comment by glasser** [comment]
Update: we think it's useful for apollo-reporting-protobuf to remain its own thing (though we're rename it to `@apollo/usage-reporting-protobuf` or something), because `@apollo/gateway` depends on it and we want to break the circular dependency (#6057)

**Comment by hwillson** [comment]
This work is now completed in https://github.com/apollographql/apollo-server/tree/version-4 (packages have been mostly combined and there is docs work to do, but the overall spirit of this issue is now complete).
