### ISSUE TITLE
Remove health checks and path parsing

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#6044]
As currently documented, you can run a trivial GraphQL query as a health check, or you can just use your web framework to create health checks that are unrelated to the state of the Apollo Server object. This will allow us to also remove the confusing choice between `app.use('/foo', s.getMiddleware())` and `app.use(s.getMiddleware({path: '/foo'}))`.

**Comment by hwillson** [comment]
Fixed in `version-4`.
