### ISSUE TITLE
Replace implementations of the cache interface with `keyv`

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#6045]
We no longer need to maintain our own abstraction around services such as Redis, because there are projects dedicated to doing the exact same thing.

**Comment by glasser** [comment]
I've removed the source for the caching packages on `version-4` but that's not actually the real work here — it's still using `apollo-server-caching` via the published npm package.

**Comment by trevor-scheer** [comment]
Done via #6154

**Comment by glasser** [comment]
New plan: we are continuing down the route of "it's keyv's job to implement bindings to redis and memcache, not ours" but we're going to go back to having the TS interface be our own (AS3-compatible) interface rather than defining it in terms of keyv's. We will distribute a tiny keyv-to-our-interface adapter so that the redis use case looks like:

```
npm install @apollo/utils.keyv-key-value-store keyv @keyv/redis

new ApolloServer({
  cache: new KeyvKeyValueStore(new Keyv("redis://...")),
})
```
or something

**Comment by glasser** [comment]
@trevor-scheer this is probably about done?

**Comment by trevor-scheer** [comment]
Done via #6488
