### ISSUE TITLE
Find an alternative to `apollo-server-env` for `fetch` API typing

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#6046]
(Or at least rename it to `@apollo/fetch-api-typing`, and separate the typing from the runtime wrapping of `node-fetch`.)

Note that this is also used by `apollo-datasource-rest` and `@apollo/gateway`.

**Comment by justinmchase** [comment]
There's another security issue with this library that seems to have no resolution available for it, so I will bump this idea.

> node-fetch  < 3.1.1
> node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://huntr.dev/bounties/d26ab655-38d6-48b3-be15-f9ad6b6ae6f7,https://github.com/node-fetch/node-fetch/commit/36e47e8a6406185921e4985dcbeff140d73eaa10
> fix available via `npm audit fix --force`
> Will install apollo-server-core@1.4.0, which is a breaking change
> node_modules/node-fetch
>   apollo-server-env  *
>   Depends on vulnerable versions of node-fetch

**Comment by glasser** [comment]
@justinmchase as mentioned in your #6065, that is already fixed.

**Comment by glasser** [comment]
Sort of related note: apparently we are currently (at least in tests? not sure?) accidentally pulling in `/// <reference lib="dom" />` via `@types/superagent@4.1.13`. Upgrading that package removes that line and breaks compilation of our tests (because `@apollo/client` which we use in tests seems to assume dom is loaded or something? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57641

I assume the correct answer to DOM typing is *not* "just use `lib:dom` (if for no other reason than that it's nice to have DOM typing that's node-fetch-compatible with an `agent` option) but we should make sure that whatever we do to solve this doesn't get confused by the fact that we have this lib=dom pulled in.  ie, whatever we do to fix this should probably also upgrade `@types/superagent` and figure out how to resolve the issue it causes.

(It seems to separately cause another issue relating to `@types/node` and `Blob` and `buffer`; this one can be fixed by upgrading `@types/node` to v16, though that might only be reasonable if we decide to bump our minimum Node version to v16 which is probably not OK.)

**Comment by glasser** [comment]
We temporarily removed apollo-server-env entirely on `version-4` and switched things to using `node-fetch` directly.  `@types/node-fetch` isn't the best thing to rely on because it's been deleted from `main` on DefinitelyTyped because the latest major version of node-fetch has its own types (but we don't want to use v3 because it's ESM-only).  Perhaps we want to use `@types/make-fetch-happen` (which was largely written by Apollo Server folks!) although it defines a bunch of its types based on `@types/node-fetch` anyway.

Also note that the `@types/node-fetch` types for Request.agent [are not quite accurate and miss `boolean`](https://github.com/apollographql/apollo-server/blob/0f2018dc89daf7605377e92057f8ade1139e78bb/packages/apollo-server-core/src/plugin/usageReporting/plugin.ts#L311-L319) so we have to have a bit of a hacky typecast to support the current usage reporting options API.

**Comment by glasser** [comment]
see also https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55533#issuecomment-1033163498

**Comment by trevor-scheer** [comment]
@glasser are our concerns with `@types/node-fetch` all resolved via your PR to restore them and fix the missing `agent: false` option? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58693

Curious if we can close this out or if we're still unsure about anything w.r.t dropping `apollo-server-env`.

**Comment by glasser** [comment]
Yeah looks like we successfully dropped apollo-server-env on version-4. Additionally, the remaining uses of `@types/node-fetch` are all around "plugins being clients of Apollo services" rather than key parts of the AS API itself.

**Comment by glasser** [comment]
OK, based on some research (involving both AS and gateway) we've come to the conclusion that there are lots of implementations of the fetch API and they have a lot of subtle ways that their typings end up differing for obscure features that aren't used by AS or gateway at all.  We think the best approach is to kinda stick with the old `apollo-server-env` approach of "we define our own fetch API" but with taking a very minimalist approach: define a `@apollo/utils.minimalist-fetch-api` package which exports a `FetchFunction` type and a `Response` type and allows for only the small set of parameters to be passed to it that are actually used by AS/Gateway.  Then that package's tests can validate that (at least!) `node-fetch` and `make-fetch-happen`'s TS types satisfy this new minimalist type.

**Comment by glasser** [comment]
Closing as fixed in v4 based on #6368. See also https://github.com/apollographql/federation/pull/1805 which does something similar for `@apollo/gateway`.
