### ISSUE TITLE
Move other plugins to their own repositories

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#6050]
Some plugins, like the usage reporting plugin, are built in to Apollo Server; they currently live in `apollo-server-core` and will live in `@apollo/server` in AS4. Other plugins live in their own packages.  These plugins will move to their own repositories. Specifically, this includes `apollo-server-plugin-operation-registry` and `apollo-server-plugin-response-cache`.

(Because `apollo-server-plugin-response-cache` will have no dependencies other than `@apollo/server` and `graphql`, it might be reasonable to merge it into `@apollo/server` as well. That said, keeping it as a separate package means we can make interface improvements to it on a versioning lifecycle that doesn't have to be strictly synchronized with the main Apollo Server API, so a separate package and repository is probably best.)

TODO
- [x] Re-add the test that was removed in [d6b1279](https://github.com/apollographql/apollo-server/commit/d6b1279d869244b1e94031822f81c1014fcb6a71)

**Comment by glasser** [comment]
What remains here is:
- Decide where the response cache plugin ends up
- Publish a new version of the new op reg plugin that's AS4-compatible

**Comment by trevor-scheer** [comment]
@glasser and I just decided to publish it as a separate package but keep it within the monorepo. This gives us both version independence and a slightly smaller maintenance burden that comes with an additional repo.

**Comment by trevor-scheer** [comment]
@glasser WIP branch (i have no idea where I left off) `trevor/v4-plugin-response-cache`

**Comment by glasser** [comment]
@trevor-scheer fixed on version-4 with #6610, right?
