### ISSUE TITLE
Removing mocking options

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#6063]
In general, many of our changes in Apollo Server 3 and 4 are around not serving as a simple pass-through to other packages. One place where we still do that is in the two top-level mocking options, which just wrap `@graphql-tools/mock`.  This led to an interesting experience where the AS3 upgrade took a major bump in `@graphql-tools/mock` which changed the API a lot, so upgrading AS required you to either rewrite your mock logic or manually pull in the old version.

It's not particularly hard to just use `@graphql-tools/mock` directly, and we can even give some documentation around how to do so, like we do for "schema directives".  We should evaluate whether the benefit of providing direct access to `@graphql-tools/mock` rather than just helping folks discover how to use it directly is worth the additional complexity.

**Comment by glasser** [comment]
Note that this is worth considering in conjunction with #6062. Using `@graphql-tools/mock` directly means you can't use `typeDefs/resolvers` so you'll need to either use `makeExecutableSchema` or the hypothetical new `graphql-js` schema creation function...

**Comment by trevor-scheer** [comment]
Closed via #6609
