### ISSUE TITLE
Add documentation to RESTDataSource for using some great cache features

### ISSUE THREAD

**Issue by kmcrawford** [apollographql/apollo-server#6067]
I spent a lot of time poring over documentation on caching, and there were a few things that were missing in the documentation that could have helped me.  I ended up finding my answers by reading the code of  `RESTDataSource` but I think these features could be documented to help developers.

My confusion started off with reading the many advanced caching behaviors of the response cache plugin.  What I was really looking for was how to cache the results of a thrid-party api that was not sending `Cache-Control` headers.

I found in my `RESTDataSource` api I could add a few features:
Such as `cacheOptionsFor`, which was the answer I was looking for where I could override the `Cache-Control` headers if nothing was sent by the third-party.
```
cacheOptionsFor(response , request) {
   return { ttl: 60  };
}
```
https://github.com/apollographql/apollo-server/blob/main/packages/apollo-datasource-rest/src/RESTDataSource.ts#L92

Or you could control the `ttl` at the specific api by passing the below to the `init` parameter of `this.get` briefly mentioned here: https://www.apollographql.com/docs/apollo-server/data/data-sources/#method-parameters

```
{cacheOptions: { ttl: 60  }}
```

Additionally I found this to be very powerful `cacheKeyFor` where I could override the cache key (helpful if I ever wanted to purge cache keys by another process, have a different cache for different headers, or didn't want a query string api-key as part of the cache key).
```
cacheKeyFor(request){
   return request.url;
}
```
https://github.com/apollographql/apollo-server/blob/main/packages/apollo-datasource-rest/src/RESTDataSource.ts#L70

I am proposing to update the `RESTDataSource` as I first followed the below and found nothing was being cached:
https://www.apollographql.com/docs/apollo-server/data/data-sources/#caching

Or perhaps explain some of the differences in some caching options such as when using the response cache plugin, it only caches for exact caches, and if you want some reuse of a cache for different queries, caching at the datasource would be required.
  
https://www.apollographql.com/docs/apollo-server/performance/caching/

**Comment by glasser** [comment]
We're planning to move `RESTDataSource` to its own repository soon (https://github.com/apollographql/apollo-server/issues/6048). As part of that we should make sure its README is complete!

The response cache plugin is not particularly related to RESTDataSource. (In fact, RESTDataSource is barely related to anything else in this repository: it's a caching HTTP client that is convenient to use when building a GraphQL server, but it doesn't really have much in the way of super detailed connections to anything else here.)

**Comment by kmcrawford** [comment]
If not formally documented, I leave this here for other curious people to find.
