### ISSUE TITLE
ApolloServer.logger should probably be public readonly in AS4

### ISSUE THREAD

**Issue by codedawi** [apollographql/apollo-server#6082]
### Proposal

We would like to propose exposing the `logger` property of `ApolloServerBase` class that is currently `private ` to any class that extends it by updating it to a `protected` property. 

https://github.com/apollographql/apollo-server/blob/fca56e78da91dd2b3bb470fdc6c8337bb3f0a9ba/packages/apollo-server-core/src/ApolloServer.ts#L127-L131

### Use case
We have extend the `ApolloServerBase` class using the serverless approach by implementing a custom handler. We would like to add logging in our handler method but do not want to use `console` or some global logger. We would like to access the `this.logger` property configured on initialization of the base class. We do not override constructor function and would prefer not for this a hack around the logger initialization.

```javascript
export class CustomApolloServerless extends ApolloServerBase {
    protected override serverlessFramework(): boolean {
        return true;
    }
    public createHandler() {
        this.logger.info("Initializing serverless handler...");
        
        return async (request: GraphQLRequest, context: any): Promise<GraphQLResponse> => {
            this.logger.debug(`Handling request ${context.requestId}...`);
        }
    }
}
```

**Comment by glasser** [comment]
Our plan for Apollo Server 4 (see https://github.com/apollographql/apollo-server/blob/main/ROADMAP.md and https://github.com/apollographql/apollo-server/milestone/60) is to change ApolloServer from having a subclass-based API to having a more well-defined public API that you extend by writing separate "createHandler" functions that take the single ApolloServer as an argument.  So changing `logger` to protected definitely won't make sense there.  But it might make sense to expose `logger` as part of `ApolloServer`'s *public* API, for this exact use case. Right now we're pretty focused on getting AS4 from "started" to "finished" as fast as possible so I'm not sure it makes sense to prioritize fixing this in AS3. I'm going to change this to an issue on the AS4 milestone to consider making `logger` public.

In the meantime, I don't see any reason we would get rid of `ApolloServerBase.logger` in AS3, so as a workaround you can write `this['logger']`, which is a [legitimate and type-safe way in TypeScript to access private properties](https://www.typescriptlang.org/docs/handbook/2/classes.html#caveats).  ie, feel free to consider this as a stable part of the AS3 API even though it is private.

**Comment by glasser** [comment]
Probably `cache` too.

**Comment by glasser** [comment]
Fixed in `version-4` in https://github.com/apollographql/apollo-server/pull/6668
