### ISSUE TITLE
healthcheck request blocked by CORS

### ISSUE THREAD

**Issue by susannakosic** [apollographql/apollo-server#6095]
Hi, I am not sure if this is the correct place for asking this question, if so please let me know.

It seems that apolo-server configuration for CORS it is not applied when querying the server-health endpoint (/.well-known/apollo/server-health).
Is this intended?

GraphQL queries requests targeting root are handled correctly.
Using apolo-server@3.6.2 and client uses fetch API with _mode: cors_ for this particular HTTP request to check health.

**Comment by glasser** [comment]
Yeah, that's how the health check is currently implemented. I think it's intended more for use by server-side systems like Kubernetes liveness checks where CORS isn't relevant.

We are planning to remove both the health check feature and CORS handling from Apollo Server 4 (#6044, #6043) other than perhaps a very simple version of it in the "standalone" server, as these features can easily be implemented in a way that fits your particular use case in your chosen web framework, so we're unlikely to change these semantics in AS3.

That said, if you just pretend that the HTTP-level health check doesn't exist and do a GraphQL-level health check by running a trivial GraphQL operation, CORS will work properly. The fact that a GraphQL health check will actually function like the rest of your GraphQL server is why it's the [first thing recommended at our health check page](https://www.apollographql.com/docs/apollo-server/monitoring/health-checks/).  If that's not suitable for some reason, you can disable our health check and CORS features (if using `apollo-server-express`, pass `cors: false, disableHealthCheck: true` to `applyMiddleware` or `getMiddleware`) and set them up in Express or your favorite web framework yourself.

**Comment by susannakosic** [comment]
Clear, thanks for elaborating @glasser.
