### ISSUE TITLE
Move GraphQL Playground plugin to another package in this repo

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#6109]
In AS3 we kept around a landing page plugin for GraphQL Playground to help with the migration from AS2. However, GraphQL Playground has been retired and continuing to maintain a wrapper around it doesn't seem like the best priority. We should certainly keep the flexible landing page API that we introduced in AS3, but perhaps we should change from "the apollo-server repo has a dependency on our fork of Playground and exports a plugin" to "we do a one-time publish of a separate package providing an AS4-compatible Playground landing page plugin".

**Comment by glasser** [comment]
`@apollo/server-plugin-legacy-graphql-playground` ?

**Comment by glasser** [comment]
Fixed on `version-4` in #6109. Decided to leave 'legacy' out of the package name.

**Comment by trevor-scheer** [comment]
Closed via #6925
