### ISSUE TITLE
Need offline doc

### ISSUE THREAD

**Issue by francelwebdev** [apollographql/apollo-server#6111]
How to read the apollo server docs offline ? When I don't have internet and I launch the server to read the doc I have a 404 page.

**Comment by trevor-scheer** [comment]
We don't offer our docs site in an offline mode. Your best option is to clone the server repo and reference the `docs` folder.

I was hoping to suggest that you could still run the docs site locally via `npx gatsby develop` from the `docs` folder but it seems our build step requires internet access (server github repo access specifically).

cc @trevorblades do you have any tricks up your sleeve for this one that I might be unaware of?

**Comment by trevorblades** [comment]
We're currently working on an offline mode for the docs. Will update this ticket with more info when I have it!
