### ISSUE TITLE
Meteor with Apollo-server v3?

### ISSUE THREAD

**Issue by imhazige** [apollographql/apollo-server#6120]
Does Apollo server v3 works with Meteor 2+?

I have tried, but it seems not work, the server crash.

The client throw error like this, the meteor websocket closed.
https://stackoverflow.com/questions/50384609/meteor-apollo-subscription-websocket-connection-closed
The apollo client is able to connect(both http and websocket), but the meteor server crash after a while.

events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Socket instance at:
    at Socket.onerror (internal/streams/readable.js:750:14)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by imhazige** [comment]
I have try noServer option which is a v2 option to subscriptionserver.
https://github.com/Pitchlyapp/meteor-apollo2/issues/1

It make the meteor works, but apollo subscription not work.

**Comment by glasser** [comment]
This sounds like a question for the Meteor repository. While some of us at Apollo worked on Meteor a long time ago, it's now a very separate thriving project.
