### ISSUE TITLE
apollo-tracing dependency

### ISSUE THREAD

**Issue by spencerhakim** [apollographql/apollo-server#616]
[Due to how semver carets are handled when major and minor version numbers are both 0](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004), `apollo-server-core`'s dependency on `apollo-tracing@^0.0.7` is essentially locked to v0.0.7, preventing use of the latest v0.0.8, which supports `graphql@^0.11.0`. Currently, trying to use one of the latest `apollo-server` packages with `graphql@^0.11.0` causes the following warning:

```
npm WARN apollo-tracing@0.0.7 requires a peer of graphql@^0.10.0 but none is installed. You must install peer dependencies yourself.
```

Preferably, this dependency would be changed to `^0.0.x` so that this issue doesn't occur again until `apollo-tracing` receives a major or minor version bump.

**Comment by martijnwalraven** [comment]
Ah, I hadn't realized that was the `0.0.x` behavior. Definitely makes sense to change.

**Comment by DxCx** [comment]
Why would tracing library be a dependancy of core graphql package anyway?

**Comment by spencerhakim** [comment]
@DxCx Collecting those measurements is useful for production metrics, though since it's disabled by default it could be argued that it should instead be a peerDependency. ¯\\_(ツ)_/¯

**Comment by martijnwalraven** [comment]
Yeah, I agree, I see this as a temporary dependency. I've been working on a `graphql-extensions` package that allows us to avoid the direct dependency and support more extensions (like the`apollo-cache-control` we just released), but it needs some work before we can support it as an extension point.
