### ISSUE TITLE
Subscription example on CodeSandbox doesn't work

### ISSUE THREAD

**Issue by TheDutchCoder** [apollographql/apollo-server#6224]
The example on [this page](https://www.apollographql.com/docs/apollo-server/data/subscriptions/#basic-runnable-example) doesn't work (anymore?).

Subscriptions are a difficult to grasp topic and it would be helpful if the example could be made to function again.

**Comment by trevor-scheer** [comment]
Thanks @TheDutchCoder! The old protocol appears to still be more widely used but there are pros and cons to defaulting either of them for now. In any case, it was considered a couple weeks ago and I've repitched it for consideration again.
