### ISSUE TITLE
Investigate ESM support

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/apollo-server#6243]
Apollo Server and friends are compiled for CJS. It would be nice to build for ESM as well.

Reference: https://community.apollographql.com/t/responsecacheplugin-is-not-a-function/2796/2

**Comment by glasser** [comment]
https://github.com/benduran/package-bundler might be nice — a new tool inspired by how `@apollo/client` works.

**Comment by glasser** [comment]
Note that as part of this we would probably want a separate entry point for `standalone` so we don't have to import express/cors/body-parser if we don't use it.

**Comment by alfaproject** [comment]
FYI: this seems like a duplicate of https://github.com/apollographql/apollo-server/issues/5627
Should we close that one?

**Comment by glasser** [comment]
(It would also be nice if we could drop `src/plugin/index.ts` while still keeping its advantages.)

@alfaproject technically #5627 is "do a thing" and #6243 is "consider doing a thing as part of the AS4 work" though they are certainly related.

**Comment by glasser** [comment]
I think I have this working at https://github.com/apollographql/apollo-server/pull/6580

**Comment by glasser** [comment]
This is finished with #6580. #6586 is a follow-up.
