### ISSUE TITLE
useQuery returning previousData even if Query Body changed

### ISSUE THREAD

**Issue by oliviercperrier** [apollographql/apollo-server#6255]
### Description

I'm currently facing a bug with the `useQuery` hook.  

I have 2 queries that look something like that: 

````
query AggregationInformation($sqon: JSON) {
     participant {
        ...
     }
}
````

````
query AggregationInformation($sqon: JSON) {
     biospecimen {
        ...
     }
}
````

When using `useQuery` hook with the first query and then with the second query, the second invocation has the `previousData` filled with the data returned by the first invocation. But we can clearly see that the 2 queries are not identical. In other words, when the Body of the DocumentNode changes, Apollo doesn't detect a query change.

### Package versions

Node: `16`
Apollo: `"@apollo/client": "^3.5.10"`

### Expected behavior

When changing the body of the DocumentNode, apollo should detect a query change and return undefined for the `previousData`

### Actual behavior

When using `useQuery` hook with the first query and then with the second query, the second invocation has the `previousData` filled with the data returned by the first invocation. But we can clearly see that the 2 queries are not identical. In other words, when the Body of the DocumentNode changes, Apollo doesn't detect a query change.

**Comment by glasser** [comment]
I think you're looking for https://github.com/apollographql/apollo-client ?
