### ISSUE TITLE
Support fastify

### ISSUE THREAD

**Issue by nfishe** [apollographql/apollo-server#626]
Hi everyone!  In respect to your contributing guidelines, I wanted to see if a consensus needed to be reached.  Fastify has been picking up traction with 3k stars and 7k downloads this month.  I'm using the [`fastify-apollo`](https://github.com/coopnd/fastify-apollo) plugin I made in production and am loving it.  To advocate, it's easy to implement routing and separate concerns outside of the graphql endpoint.  Also fastify/fastify#302 brought up the issue of not enough visibility.  

I got a good response in the Slack channel submit a PR but wanted to do my due diligence first.

**Comment by martijnwalraven** [comment]
Thanks for opening an issue! We'd be happy to include a`apollo-server-fastify` package based on `fastify-apollo`.

My only concern would be that we'd really prefer all packages in this repo to be written in TypeScript, because that makes testing and releasing things together a lot easier.

**Comment by coopnd** [comment]
> My only concern would be that we'd really prefer all packages in this repo to be written in TypeScript, because that makes testing and releasing things together a lot easier.

Not a problem

I am also thinking not to include `fastify-plugin` in this iteration.  Since each instance of fastify is scoped, the plugin just overrides that.  But routes are not scoped...so it doesn't matter and one less dependency.

**Comment by lednhatkhanh** [comment]
It's really a good idea, I search for fastify and apollo integration right after I tried it for the first time. Hope that we can have an Apollo + fastify package soon!

**Comment by tomByrer** [comment]
Thanks for working on this @addityasingh

**Comment by tomByrer** [comment]
What's the status of this please?
