### ISSUE TITLE
WebSocket connection to 'ws://localhost:8000/graphql' failed

### ISSUE THREAD

**Issue by berkaycimsir** [apollographql/apollo-server#6265]
i followed this guide https://www.apollographql.com/docs/apollo-server/data/subscriptions

i am using apollo sandbox to query my server
<img width="633" alt="Screen Shot 2022-03-27 at 16 55 17" src="https://user-images.githubusercontent.com/47090177/160284953-f70d135c-0383-4757-864f-c638075354eb.png">

my implementation code
```js
export const initApollo = async (app: Express, port: number) => {
  const schema = makeExecutableSchema();

  const httpServer = http.createServer(app);

  const wsServer = new WebSocketServer({
    server: httpServer,
    path: '/graphql',
  });

  const serverCleanup = useServer(
    {
      schema,
    },
    wsServer
  );

  const server = new ApolloServer({
    schema,
    context: ({ req }) => getApolloContext(req),
    plugins: [
      ApolloServerPluginDrainHttpServer({ httpServer }),
      {
        async serverWillStart() {
          return {
            async drainServer() {
              await serverCleanup.dispose();
            },
          };
        },
      },
    ],
  });

  await server.start();
  server.applyMiddleware({ app });

  httpServer.listen(port, () => {
    console.log(
      `🚀 Server ready at http://localhost:${port}${server.graphqlPath}`
    );
  });
};
```

error message
<img width="516" alt="Screen Shot 2022-03-27 at 16 46 57" src="https://user-images.githubusercontent.com/47090177/160284603-3a594176-747e-44df-94ab-0b5c2535c507.png">

packages' versions (using latest)
```json
"dependencies": {
    "@graphql-tools/graphql-file-loader": "^7.3.3",
    "@graphql-tools/load": "^7.5.1",
    "@graphql-tools/schema": "^8.3.1",
    "apollo-server-core": "^3.6.3",
    "apollo-server-express": "^3.6.3",
    "bcryptjs": "^2.4.3",
    "copyfiles": "^2.4.1",
    "dotenv": "^16.0.0",
    "express": "^4.17.3",
    "graphql": "^16.3.0",
    "graphql-subscriptions": "^2.0.0",
    "graphql-ws": "^5.6.4",
    "jsonwebtoken": "^8.5.1",
    "mongoose": "^6.2.2",
    "ws": "^8.5.0"
  },
  "devDependencies": {
    "@eslint/create-config": "^0.1.2",
    "@types/bcryptjs": "^2.4.2",
    "@types/express": "^4.17.13",
    "@types/jsonwebtoken": "^8.5.8",
    "@types/mongoose": "^5.11.97",
    "@types/node": "^17.0.18",
    "@types/ws": "^8.5.3",
    "@typescript-eslint/eslint-plugin": "^5.12.0",
    "@typescript-eslint/parser": "^5.12.0",
    "eslint": "^8.9.0",
    "nodemon": "^2.0.15",
    "ts-node": "^10.5.0",
    "typescript": "^4.5.5"
  }
```

**Comment by glasser** [comment]
Can you select graphql-js from the "implementation" menu? The default in Explorer is still the legacy deprecated protocol. I think that will fix your issue.

**Comment by berkaycimsir** [comment]
> Can you select graphql-ws from the "implementation" menu? The default in Explorer is still the legacy deprecated protocol. I think that will fix your issue.

yeah, i already tried that before but it gives an error like that. i searched this on google but couldn't find anything.

<img width="860" alt="Screen Shot 2022-03-28 at 23 49 03" src="https://user-images.githubusercontent.com/47090177/160484679-eedb7e20-0ed5-478c-bee8-11e223ce750e.png">

**Comment by glasser** [comment]
What browser?
