### ISSUE TITLE
apollo-server-express fails to resolve graphql 16 using yarn PnP

### ISSUE THREAD

**Issue by evanrlong** [apollographql/apollo-server#6269]
I am trying to use `apollo-server-express` in a project using yarn 3 w/ PlugNPlay dependency resolution. When I run `yarn add apollo-server-express` inside my project, I expect it to include the package without errors.  Instead, I see this...

![output](https://user-images.githubusercontent.com/3453944/160510960-02de621b-b3cd-42f6-a2d5-c862bcf61cb2.png)

And running `yarn explain peer-requirements <hash>` yields...

![explain](https://user-images.githubusercontent.com/3453944/160510999-3628c8be-13e8-4443-8a74-6ed9e808ec8e.png)

The problematic area seems to be an incorrect peerDependency inside `@apollographql/apollo-tools@0.5.2`. Strangely, [that package](https://github.com/apollographql/apollo-tooling/blob/%40apollographql/apollo-tools%400.5.2/packages/apollo-tools/package.json) does not seem to have any listed peerDependencies, so I'm a bit stumped.

Here is a minimal reproduction...

https://github.com/evanrlong/graphql-16-resolution-example

Could someone please take a look so that we can use `graphql@16.x` and `apollo-server-express` within yarn projects?  Thanks!

**Comment by evanrlong** [comment]
Whoops I fat fingered the enter key.  I am editing this now.

**Comment by arcanis** [comment]
Yarn hardcodes the peer dependency because graphql-tools forgot to do it; a PR is open here but it hasn't been merged yet.
- https://github.com/apollographql/apollo-tooling/pull/2049

**Comment by glasser** [comment]
thanks.  apollo-tooling has been deprecated for a while and we are working to remove the vestigial uses of it in Apollo Server as part of our AS4 work.  but we should probably fix the apollo-tools peer dep for now, since it is a dependency of AS even if it's only used by one particular `modules` option.

**Comment by glasser** [comment]
(cc @trevor-scheer who's been working on removing dependencies on the old tooling repo across our active projects)
