### ISSUE TITLE
Resolve reference is not being called when using custom directives

### ISSUE THREAD

**Issue by ujjawal-khare** [apollographql/apollo-server#6270]
I am currently using custom directives to handle authorization across mutations and queries for my subgraphs. However when I wrap my schema in the custom directive function using mapSchema (I created the custom directive with this) from graphql-tools, the __resolveReference function for a particular entity is not being called. But when I pass the schema returned from the buildSubgraphSchema function directly to the Apollo server constructor, everything works fine. Any idea what I could be doing wrong.? Thank you!

**Working code**
const schema = buildSubgraphSchema({typedefs, resolvers})
const server = new ApolloServer({schema}) // __resolveReference is getting called 

**Code with schema directives**
const schema = buildSubgraphSchema({typedefs, resolvers})
const updatedSchema = authDirectiveTransformer(schema)
const server = new ApolloServer({updatedSchema}) // __resolveReference is not been called on entities.

Link for sample code: https://github.com/ujjawal-khare/federation-demo/tree/feat/auth-directive

**Comment by glasser** [comment]
Hi, you also filed this at https://github.com/apollographql/federation/issues/1656 which was a better location. Closing this one (though that's also a duplicate).
