### ISSUE TITLE
apollo-server-express MaxListenersExceededWarning

### ISSUE THREAD

**Issue by david-wb** [apollographql/apollo-server#6296]
I'm seeing this error from `ApolloServer` when using `apollo-server-express` on AWS Lambda. The server is wrapped with `@vendia/serverless-express`, but the error seems to occur in the `ApolloServer` class. Nowhere in my code am I adding event emitters or listeners so I think it is a bug in `ApolloServer`. Does anyone have any advice? Thanks!

```
ERROR\	(node:9) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit\
    at _addListener (events.js:475:17)\
    at process.addListener (events.js:497:10)\
    at /var/task/api.js:249861:15\
    at Array.forEach (<anonymous>)\
    at ApolloServer.maybeRegisterTerminationSignalHandlers (/var/task/api.js:249860:13)\
    at ApolloServer._start (/var/task/api.js:249823:12)\
    at async ApolloServer.start (/var/task/api.js:249725:12)\
    at async createApp (/var/task/api.js:326237:3)\
    at async handler (/var/task/api.js:356957:15)
```

**Comment by glasser** [comment]
This typically means that you are creating a brand new ApolloServer object from scratch for every request (and not stopping it after every request).

Are you using `apollo-server-express` + `@vendia/serverless-express` yourself, or using `apollo-server-lambda` which combines them for you? It's actually just a thin wrapper around the two so it's probably what you want. https://www.apollographql.com/docs/apollo-server/integrations/middleware#apollo-server-lambda documents it.

**Comment by david-wb** [comment]
@glasser Thanks, yes I am using `apollo-server-express + @vendia/serverless-express` because I need add additional routes to the express server.

**Comment by glasser** [comment]
Have you seen the `expressAppFromMiddleware` option? https://www.apollographql.com/docs/apollo-server/deployment/lambda#customizing-http-serving

**Comment by david-wb** [comment]
@glasser No but I'll try it, thank you.
