### ISSUE TITLE
Cannot get GraphQLUpload

### ISSUE THREAD

**Issue by kamalkech** [apollographql/apollo-server#6301]
```"apollo-server-express": "^3.6.7",```

```typescript
@Mutation(() => MediaModel)
  async uploadMedia(
    @Args({ name: 'file', type: () => GraphQLUpload })
    file: FileUpload,
  ): Promise<MediaModel> {
    ...
  }
```

get this error message: ```Module '"apollo-server-express"' has no exported member 'GraphQLUpload'```

any idea to fixe this isse ?? or must to downgrade version ??

**Comment by glasser** [comment]
Hardcoded direct integration with a specific outdated version of graphql-upload was removed in AS3. See the migration guide for advice: https://www.apollographql.com/docs/apollo-server/migration/#file-uploads

**Comment by kamalkech** [comment]
understood, tnx
