### ISSUE TITLE
Context in formatError

### ISSUE THREAD

**Issue by Christilut** [apollographql/apollo-server#631]
Any way to reach the context inside the `formatError` function? I couldn't find anything about it in the docs.

```ts
export const graphQlRoute = graphqlExpress(req => ({
  schema,
  context: {
    user: req.user
  },
  formatError
}))
```

**Comment by danny-larsen** [comment]
Any progress on this or a work around?

**Comment by martijnwalraven** [comment]
What is your use case for this? 

As a workaround, you should be able to store the context as a local variable inside the closure. Something like:
```
export const graphQlRoute = graphqlExpress(req => {
  const context = {
    user: req.user
  };
  return {
  schema,
  context,
  formatError(context)
}))
```

**Comment by advance512** [comment]
This forces a re-evaluation of the formatError function on each request - kinda pointless.
I think you can define it outside of the request handler and still get access to the outer closure  variables.

BTW, how can you get the variables? Part of the `err.source.body`?

**Comment by codyzu** [comment]
This doesn't seem possible with apollo-server-koa. When logging and reporting errors, I need to get some info from the request in order to create a relation between the errors and the requester.

Has anyone made any progress for this or found workaround that works with the apollo server integrations?

**Comment by martijnwalraven** [comment]
I think there may be an alternative where `context` is an instance property, similar to how we do this for data sources. But let's revisit this when we finalize the API with the new request pipeline.

**Comment by BigMaster** [comment]
I have solved this problem!
[https://github.com/BigMaster/graphql-format-error-context-extension](https://github.com/BigMaster/graphql-format-error-context-extension)

**Comment by rnenjoy** [comment]
Needs this aswell.

**Comment by macsj200** [comment]
@martijnwalraven An example use case for this is if you have a custom logger object that you attach to the context, you may want to be able to reference that logger in the `formatError()` body.

**Comment by abernix** [comment]
For anyone encountering this issue still, the `formatError` on Apollo Server today is a hoisting of the principle/pattern behind the [underlying `formatError` in `graphql-js`](https://graphql.org/graphql-js/error/#formaterror), which doesn't have a notion of `context` supplied to it.   For those needing to react to things on the `context` (which makes a lot of sense!), you might consider using the `plugins` API's [`didEncounterErrors`](https://www.apollographql.com/docs/apollo-server/integrations/plugins/#didencountererrors) or [`willSendResponse`](https://www.apollographql.com/docs/apollo-server/integrations/plugins/#willsendresponse) life-cycle hooks, both of which receive `context`.  And for the custom logger use-case above, they _also_ receive the `logger` that is passed into the `ApolloServer` constructor, if you've provided one (but that defaults to `console`, if you haven't).

**Comment by Kl4rity** [comment]
Unfortunately, this doesn't allow you to catch exceptions that are thrown in the early stages of processing request, such as `parsingDidStart` or `validationDidStart`. Meaning, that any errors thrown in preprocessing the request (say, adding a user-object to the request) cannot be handled by `didEncounterErrors` or `willSendResponse`.  :(

**Comment by glasser** [comment]
@Kl4rity this is discussed with some workaround ideas at https://github.com/apollographql/apollo-server/issues/3039#issuecomment-902851382

**Comment by Uzziel306** [comment]
Everyone i got a solution!  :tada: 
it's true that you will not get the context in this formatError function, but you could use the [formatResponse](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#formatresponse) function, You can catch the all error in the response, and you'll have the context as well. Good luck! :rock:
