### ISSUE TITLE
@deprecated directive not working for inputs

### ISSUE THREAD

**Issue by samchungy** [apollographql/apollo-server#6314]
## Issue

We bumped up from Apollo Server 2 and found that the deprecated directive's on inputs are being omitted from the introspection schema. This is causing us issues when it comes to using codegen which rely on these.

No @deprecated directive
![image](https://user-images.githubusercontent.com/18017094/163131468-43a4354b-0f1e-497e-a439-4b537115f639.png)

@deprecated directive added to `id` field
![image](https://user-images.githubusercontent.com/18017094/163131503-fb45cf72-68e7-49c8-896d-b09aa3f615bc.png)

## Versions
Running on apollo-server-core 3.6.7 and apollo-server-koa 3.6.7.

## Steps to reproduce
https://github.com/samchungy/apollo-server-bug

1. Run `yarn`
2. Run `yarn start`
3. Run `npx diagnose-endpoint@1.1.0 --endpoint=http://localhost:4000/graphql`
It will say that `QueryInput` is missing arguments.

4. Remove the `@deprecated(reason: "boo")` from schema.ts (QueryInput).
5. Run `npx diagnose-endpoint@1.1.0 --endpoint=http://localhost:4000/graphql`
It will be resolved.

## Other

I pulled the 2 schemas down. [schemas.zip](https://github.com/apollographql/apollo-server/files/8479421/schemas.zip)

One where the `QueryInput` has  `"inputFields": []` when the deprecated field is used.

Another where `QueryInput` has the `id` field in the `inputFields` array.

**Comment by renato** [comment]
Hey @samchungy , were you able to instruct ApolloServer to include the deprecated input fields in its introspection query? Thanks!

**Comment by samchungy** [comment]
Yeah I guess there is a slight bug. When you go to download the schema using Apollo studio it'll download the one without inputField so something might need to be done on the Apollo side but this issue isn't related to the server since I can query what I want
