### ISSUE TITLE
Cache Tag plugin like Cache Control

### ISSUE THREAD

**Issue by davidbarratt** [apollographql/apollo-server#6318]
The [Cache-Control plugin](https://github.com/apollographql/apollo-server/blob/ab67eab1c48daa7a28b9278b4bd744ac465a6edf/packages/apollo-server-core/src/plugin/cacheControl/index.ts) is fantastic.

It would be super helpful if a similar plugin existed for `Cache-Tag` that would allow tags to be defined and added as a header to the response. Adding the tags allows the resources to have a much longer TTL since the resources can be purged from the cache by tag rather than by URL.

This means if you have a GraphQL Query that returns 10 blog posts, you could add a tag for each one. The response can have a TTL of... forever, since the query can remain in the cache until the blog posts change.

In other words, Cache Tags make GraphQL highly cacheable.

Cache Tags are availble at [Cloudflare](https://developers.cloudflare.com/cache/how-to/purge-cache/#cache-tags-enterprise-only), [Fastly](https://developer.fastly.com/reference/http/http-headers/Surrogate-Key/), and [Akamai](https://techdocs.akamai.com/purge-cache/docs/assign-cache-tags).

The plugin would actually be simpler than the `Cache-Control` plugin because it only needs to dedupe the input and roll them up. Since the header name is different per vendor, it would have to be configured globally.

It could also be useful to have "global" tags that are applied to every operation, which one could use for the name of the service supplying a subgraph for instance.

Alternatively, "tags" could be added as an option to the existing `Cache-Control` plugin since it is direclty tied to that behavior.

**Comment by glasser** [comment]
This looks like something that one could build as a non-core plugin using the API, right?  I think that would be a good place to start; if it requires more core functionality (or if it becomes quite popular) then moving into core would make sense. This is not to say that it doesn't sound valuable — just that if the plugin API works then it's worth using.

(FWIW for a new plugin I would consider not monkeypatching `info` like we do in the cache control plugin and probably putting something on `context` instead, like with data sources.)
