### ISSUE TITLE
the migration guide to graphql-ws doesn't provide guidance or useful info

### ISSUE THREAD

**Issue by iambumblehead** [apollographql/apollo-server#6323]
subscriptions-transport-ws is deprecated the npm page links to an apollographql "migration guide" that doesn't contain any useful information,

https://www.npmjs.com/package/subscriptions-transport-ws

https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws

please provide an upgrade path for users of subscriptions-transport-ws

**Comment by trevor-scheer** [comment]
Thanks for reporting!
