### ISSUE TITLE
TypeError is not a function when including ApolloServerPluginDrainHttpServer

### ISSUE THREAD

**Issue by msambol** [apollographql/apollo-server#6328]
I'm getting the following error when trying to include `ApolloServerPluginDrainHttpServer`:

```
TypeError: (0 , _apolloServerCore.ApolloServerPluginDrainHttpServer) is not a function
```

Here's the code:
```
    const gateway = new ApolloGateway({
      serviceList,
      buildService({ url }) {
        return new AuthenticatedDataSource({ url })
      }
    })

    const app = express()
    const httpServer = http.createServer(app)
    
    const server = new ApolloServer({
      gateway,
      introspection: true,
      plugins: [ApolloServerPluginDrainHttpServer({ httpServer })]
    })

    server.applyMiddleware({ app })

    httpServer.listen(config.PORT, () => log.info(`Listening on ${config.PORT}`))
```

Dependencies:
```
  "dependencies": {
    "@apollo/gateway": "^2.0.1",
    "@apollographql/graphql-playground-html": "^1.6.6",
    "@contrast/agent": "^2.16.4",
    "@sbg/gateway-auth": "^0.0.7",
    "@sbg/idps-client": "^1.0.1",
    "apollo-server": "^3.6.7",
    "apollo-server-core": "^3.6.7",
    "apollo-server-express": "^3.6.7",
    "bunyan": "^1.8.12",
    "bunyan-format": "^0.2.1",
    "dynamoose": "^1.3.0",
    "express": "^4.17.3",
    "express-bunyan-logger": "^1.3.3",
    "express-request-id": "^2.0.1",
    "graphql": "^16.3.0",
    "graphql-voyager": "^1.0.0-rc.31",
    "node-fetch": "^2.6.0",
    "wait-port": "^0.2.9"
  }
```

I'm following the docs [here](https://www.apollographql.com/docs/apollo-server/integrations/middleware/#apollo-server-express). Everything is in working order when I comment out the plugins. What am I missing?

**Comment by msambol** [comment]
User error here. The version of `apollo-server-core` did not match the version in dependencies.

**Comment by trevor-scheer** [comment]
Thanks for following up @msambol!

**Comment by trevor-scheer** [comment]
@YoussefBA-codings please share more details about your project so we can help. It looks like @msambol provided the reason behind the issue. I'm happy to help you dig into that if you're not sure how to resolve it.

What's the result of running the command `npm ls apollo-server-core` in your project? If you see multiple `apollo-server-core`'s, consider aligning your project's version with the others listed.
