### ISSUE TITLE
TypeError with ioredis 5.0.4

### ISSUE THREAD

**Issue by iamchathu** [apollographql/apollo-server#6329]
ioredis project previously used @types/ioredis for type information and since version 5 they have moved to Typescipt and they provide own type definitions.

After update to recent versions, get following error.

```
src/index.ts(49,13): error TS[232]()2: Type 'Redis' is not assignable to type 'RedisClient'.
  Types of property 'set' are incompatible.
    Type '{ (key: RedisKey, value: string | number | Buffer, callback?: Callback<"OK"> | undefined): Promise<"OK">; (key: RedisKey, value: string | ... 1 more ... | Buffer, get: "GET", callback?: Callback<...> | undefined): Promise<...>; (key: RedisKey, value: string | ... 1 more ... | Buffer, nx: "NX", callback?: Callback<.....' is not assignable to type '(key: string, value: string, option?: string | undefined, optionValue?: number | undefined) => Promise<any>'.
      Types of parameters 'callback' and 'option' are incompatible.
        Type 'string | undefined' is not assignable to type 'Callback<"OK"> | undefined'.
          Type 'string' is not assignable to type 'Callback<"OK">'.
src/index.ts(71,5): error TS2322: Type 'Express' is not assignable to type 'Application'.
  Types of property 'get' are incompatible.
    Type '((name: string) => any) & IRouterMatcher<Express, any>' is not assignable to type '((name: string) => any) & IRouterMatcher<Application, any>'.
      Type '((name: string) => any) & IRouterMatcher<Express, any>' is not assignable to type 'IRouterMatcher<Application, any>'.
        Types of parameters 'name' and 'path' are incompatible.
          Type 'PathParams' is not assignable to type 'string'.
            Type 'RegExp' is not assignable to type 'string'.

```

```
"apollo-server-cache-redis": "^3.3.1",
"apollo-server-core": "^3.6.7",
"apollo-server-express": "^3.6.7",
"ioredis": "^5.0.4",
```

**Comment by glasser** [comment]
We haven't taken the ioredis v5 upgrade for apollo-server-cache-redis yet, so you shouldn't be able to use it with AS. https://github.com/apollographql/apollo-server/pull/6263

Note that we are probably not going to take this upgrade. We are instead going to be (with AS4) getting out of the business of maintaining an Apollo-Server-specific cache abstraction interface; we're instead going to switch to [keyv](https://www.npmjs.com/package/keyv) which does basically the exact same thing as our apollo-server-caching KeyValueCache interface.  keyv has [already taken the ioredis v5 upgrade](https://github.com/jaredwray/keyv/pull/263).

Are there important features in ioredis v5 that mean it's urgent for you to upgrade today?  Honestly, if so my instinct is for me to just tell you to switch to keyv today; we can write an adaptor from keyv (which has a lot more implementations than our cache abstraction) to our cache abstraction pretty quickly.

**Comment by iamchathu** [comment]
If the project is going with keyv I think better to switch to it then. Any ETA about it?

**Comment by glasser** [comment]
For a quick wrapper, just

```
npm i keyv @keyv/redis
```

and

```
import Keyv from 'keyv';
export class KeyvKeyValueCache<V> implements KeyValueCache<V> {
  constructor(private keyv: Keyv) {}
  async get(key: string) {
    return this.keyv.get(key);
  }
  async set(key: string, value: V, options?: KeyValueCacheSetOptions) {
    this.keyv.set(key, value, options?.ttl ?? undefined);
  }
  async delete(key: string) {
    this.keyv.delete(key);
  }
}
```

Then you can do

```
new ApolloServer({
  cache: new KeyvKeyValueCache(new Keyv('redis://user:pass@localhost:6379')),
})
```

(or any other Keyv-based cache)
