### ISSUE TITLE
Apollo Server Does not run in gateway mode when passing Apollo Gateway executer and schema in constructor

### ISSUE THREAD

**Issue by farawaysouthwest** [apollographql/apollo-server#6338]
This issue happens when you preload the gateway and then passing the schema and the executer manually to the ApolloServer.

For example:
If the normal way to initiate ApolloServer is:
```javascript
const gateway = new ApolloGateway(apolloGatewayConfig);
const server = new ApolloServer({ gateway });
```

The usage that is leading to the bug is:

```javascript
const gateway = new ApolloGateway(apolloGatewayConfig);
const { schema, executer } = await gateway.load()
const server = new ApolloServer({ schema, executer });
```
ApolloServer assumes that if there is not a "gateway" prop in the apollo server config that means it's not running as a gateway (in the mode that is called 'gateway').
And that obviously leads to several potential issues, because it should be handled as a gateway in that case.

The place I've found that makes this condition is in `apollo-server-core@3.6.4`, file: `src/utils/schemaManager.ts:63`
```javascript
if ('gateway' in options) {
  this.modeSpecificState = {
    mode: 'gateway',
    gateway: options.gateway,
    apolloConfig: options.apolloConfig,
  };
} else {
  this.modeSpecificState = {
    mode: 'schema',
    apiSchema: options.apiSchema,
    // The caller of the constructor expects us to fail early if the schema
    // given is invalid/has errors, so we call the provider here. We also
    // pass the result to start(), as the provider can be expensive to call.
    schemaDerivedData: options.schemaDerivedDataProvider(options.apiSchema),
  };
}
```

**Comment by trevor-scheer** [comment]
Hey @farawaysouthwest, thanks for the report.

Passing schema/executor to AS is a very old way of doing things, but I understand you're only doing it to get a look at the `schema` object. I think I have some good news for you - the plugin system should be a very straightforward way of doing this.

```ts
new ApolloServer({
  //...your usual config
  gateway,
  plugins: [{
    async serverWillStart({ schema }) {
      // schema-dependent things here
    }
  }],
})
```

Let me know if I'm missing the point, but I think this is exactly what you're looking for.

**Comment by glasser** [comment]
(Though if you care about access to the schema as it changes over time, you may want to use `schemaDidLoadOrUpdate` instead!)
