### ISSUE TITLE
Unable to reach subscription server

### ISSUE THREAD

**Issue by syukronarie** [apollographql/apollo-server#6341]
I have some issue when I am running subscription in codesanbox or locally.

this is an error message on studio.apollographql:

`Unable to reach subscription server

To diagnose the problem, please run:
npx diagnose-endpoint@1.1.0 --endpoint=wss://idh66.sse.codesandbox.io/graphql`

**Comment by glasser** [comment]
I'm sorry, but there's not enough information for us to help you.  If you can provide a link to the codesandbox that we can see, we could try to help!
