### ISSUE TITLE
`ContextFunction` type has incorrect input/outputs 

### ISSUE THREAD

**Issue by salemhilal** [apollographql/apollo-server#6342]
Hey there! I have a problem that's showing up in `apollo-server-express`, but I think it originates in `apollo-server-core`.

## The problem
I'm writing a context function which should take in the default apollo-server-express context and spit out my own context:
```ts
   interface ApolloContext extends ExpressContext {
        db: Connection;
        jwt: JwtPayload;
    }
    
    const server = new ApolloServer<ApolloContext>({
        schema,
        context: async (ctx) => {
            return {
                // The default context (with req and res)
                ...ctx,
                db: getConnection(),
                jwt: getJwt(),
            };
        },
    });
```
However, the `ctx` argument passed to my context function has a type of `ApolloContext`, which can't be true since I haven't yet initialized the full context object. Further, the return type of my function is expected to be `object` and can't be changed, which means my return types could have any key and value. 

I dug in a bit and found that `ContextFunction`, the type for that function, _does_ have separate generics for its input and its output. 
https://github.com/apollographql/apollo-server/blob/dad2cddfeaea5c8e6c19069a5d2d768031f3fdc4/packages/apollo-server-core/src/types.ts#L25
However, the first generic, for its inputs, is the only one ever used.
https://github.com/apollographql/apollo-server/blob/e09a94bcff2ceecb930ff9e301df85298f154cdc/packages/apollo-server-core/src/ApolloServer.ts#L138
It gets that input generic from the one generic that ApolloServer accepts, which is used in the config passed to its constructor:
https://github.com/apollographql/apollo-server/blob/e09a94bcff2ceecb930ff9e301df85298f154cdc/packages/apollo-server-core/src/ApolloServer.ts#L129-L138

The result is that even though the inputs to the context function should be stable depending on which environment you're in, they're actually made to be the exact type of the context you're trying to initialize with that function.

## A possible fix
A solution to this could be to have `Context` accept a second generic (defaulting to `object`) for the return type of the context function:
```ts
export interface Config<ContextFunctionParams = any, ContextType = object> extends BaseConfig {
  // ...
  context?: Context | ContextFunction<ContextFunctionParams, ContextType>;
```
and then to have environment-specific packages like `apollo-server-express` augment `ContextFunctionParams` when extending `ApolloServerBase`, which would allow for the types to be backwards-compatible:
```ts
// in apollo-server-express
export class ApolloServer<
  ContextFunctionParams extends ExpressContext = ExpressContext,
  ContextType = object
> extends ApolloServerBase<ContextFunctionParams, ContextType> {
```
Or even better, don't allow the function param types to be modified. I could be wrong, but I don't know where the context could be modified before the context function.
```ts
// in apollo-server-express
export class ApolloServer<
  ContextType = ExpressContext
> extends ApolloServerBase<ExpressContext, ContextType> {
```

Let me know what you think, and thanks for all the work on the Apollo project!

**Comment by trevor-scheer** [comment]
@salemhilal thanks for the detailed report. The state of `Context`y generics in AS 2/3 is really not great, sorry for the trouble that's causing you.

@glasser and I discovered that the `ProducedContext` or expected context object shape really needs to be threaded through a bunch of types starting from the AS constructor. This is fixed in the upcoming AS v4 (mostly via https://github.com/apollographql/apollo-server/commit/d1b5b6abffdaa0440c7e95aa598a5d5a37b7066a). Keep an eye out for an alpha in the coming weeks!
