### ISSUE TITLE
Hapi v17

### ISSUE THREAD

**Issue by flipxfx** [apollographql/apollo-server#636]
Upgrade hapi plugin to work with new release of Hapi https://github.com/hapijs/hapi/issues/3658

**Comment by martijnwalraven** [comment]
A PR would be great!

**Comment by lobosan** [comment]
Yes please and also provide a simple boilerplate to get started and explain how to do authentication, acl, cookies and input validation. Thanks

**Comment by Samueljoli** [comment]
Hey is this currently assigned to anyone?

**Comment by flipxfx** [comment]
I haven’t had time recently so I’m not sure if anyone is working on this.

**Comment by daoanhnhat1995** [comment]
I can work on this today or tomorrow if nobody's been assigned

**Comment by martijnwalraven** [comment]
@daoanhnhat1995 That would be great, it doesn't seem like anyone is working on it!

**Comment by daoanhnhat1995** [comment]
@martijnwalraven  [Hapi17 typings](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20670) hasn't been updated yet so we'll have to wait till then?

**Comment by martijnwalraven** [comment]
@daoanhnhat1995 It seems like it, or maybe they would accept a PR as well?

**Comment by SOULPWRD** [comment]
[Hapi 17 typings](https://github.com/rafaelsouzaf/DefinitelyTyped/pull/1) are already in PR and been waiting just for a code review.

Any updates on this isssue?
Thanks :)

**Comment by rafaelsouzaf** [comment]
@SOULPWRD It's in under development, really :-)
