### ISSUE TITLE
websockets for query & mutations

### ISSUE THREAD

**Issue by playerx** [apollographql/apollo-server#637]
Hi guys,

I've one idea, I want to use websockets not only for subscriptions, but also for query and mutations too. Is it possible with current apollo-server?

I think it would not be difficult to be implemented, I was not able to find any documentation about that, if you have any kind of information or ideas please share it with me.

P.S. I think it will be the next level for modern web. http post is a legacy that should be dropped away imho.

**Comment by martijnwalraven** [comment]
You'll be happy to hear the existing [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws#full-websocket-transport) already supports this!

**Comment by playerx** [comment]
It looks like I was searching answers in wrong repository :) thanks @martijnwalraven !

**Comment by Panoplos** [comment]
You can do this easily. I am using [SocketCluster](https://socketcluster.io/#!/) with `makeExecutableSchema` and `graphql`'s `execute`. SocketCluster is great because it handles web token authentication for you and gives you scalability out of the box. Have a look at [this repo](https://github.com/ParabolInc/action) for a good reference implementation.

**Comment by playerx** [comment]
Very interesting, thanks @Panoplos  I'll take a look 👍

**Comment by shtse8** [comment]
Yes, [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws#full-websocket-transport) supports this feature. But I noticed that `apollo-server-express` graphiql is failed to use full websocket.

**Comment by soorena110** [comment]
I did something like this

`const id = Math.random();

    const req = link.request({
        query: gql`mutation {
            publisherMutation(message: "${id}")
        }`
    });
    if (req) {
        const sub = req.subscribe(res => {
            console.log("publisherMutation:", res);
            sub.unsubscribe()
        });
    }`

**Comment by soorena110** [comment]
And here's my full code

import {WebSocketLink} from "apollo-link-ws";
    import {SubscriptionClient} from "subscriptions-transport-ws";
    import gql from "graphql-tag";
    
    const GRAPHQL_ENDPOINT = "ws://localhost:3000/graphql";
    
    
    const client = new SubscriptionClient(GRAPHQL_ENDPOINT, {
        reconnect: true
    });
    
    const link = new WebSocketLink(client);

    const id = Math.random();

    const req = link.request({
        query: gql`mutation {
            publisherMutation(message: "${id}")
        }`
    });
    if (req) {
        const sub = req.subscribe(res => {
            console.log("publisherMutation:", res);
            sub.unsubscribe()
        });
    }

**Comment by soorena110** [comment]
remember my code is to `mutate` and is not subscription but it did not have any choice to call `mutate` without it.
if anyone has a better way to do this I would be glad with many thanks :)
