### ISSUE TITLE
`@apollo/utils.logger` should be declared in the dependencies of `apollo-server-types`

### ISSUE THREAD

**Issue by Grmiade** [apollographql/apollo-server#6389]
`@apollo/utils.logger` should be declared in the dependencies of `apollo-server-types`

Regression introduced by https://github.com/apollographql/apollo-server/commit/e09a94bcff2ceecb930ff9e301df85298f154cdc#diff-c3e5296b7b2d40bf15864e047a623dbd664f236d2d12229967402a5c0324e0d6

**Comment by glasser** [comment]
Good catch. Will fix.
