### ISSUE TITLE
File upload not working with csrfPrevention

### ISSUE THREAD

**Issue by ronald-truepill** [apollographql/apollo-server#6433]
Hi, I'm implementing file upload in graphql using `apollo-server-express` and `graphql-upload`, but is not working as shown in [docs](https://www.apollographql.com/docs/apollo-server/data/file-uploads/) for express
When I try to upload a file it throws this error
```
This operation has been blocked as a potential Cross-Site Request Forgery (CSRF). Please either specify a 'content-type'
header (with a type that is not one of application/x-www-form-urlencoded, multipart/form-data, text/plain) or provide a
non-empty value for one of the following headers: x-apollo-operation-name, apollo-require-preflight
```
![image](https://user-images.githubusercontent.com/98913760/168635410-a1880c18-6c08-49a5-854d-61ecaf7a04ac.png)

The code to reproduce it is the same as the one [here](https://www.apollographql.com/docs/apollo-server/data/file-uploads/#integrating-with-express)

How can I implement file upload with csrfPrevention enabled?

Note: The error appears with apollo server version 2 (setting `uploads: false`) and 3

**Comment by ronald-truepill** [comment]
@glasser That worked! I added this in my `useMutation` (I'm using React)
```js
  const [uploadDocument] = useMutation(UPLOAD_DOCUMENT, {
    context: {
      headers: {
        'apollo-require-preflight': true,
      },
    },
    onCompleted: () => {
      // ...
    },
    onError: (error) => {
      // ...
    },
  })
```

Not sure if there's a better way to do it from `apollo-upload-client` link.

Thank you for your help! Indeed would be great if that's added to the documentation because I searched everywhere about this and didn't find anything

**Comment by glasser** [comment]
It looks like you can add `headers` to `createUploadLink` rather than sending it on each `useMutation` call.

**Comment by trevor-scheer** [comment]
@glasser is there anything left to do here / did you want to leave this issue open? Going to close since I think the answer is no, just reopen if I'm wrong.

**Comment by glasser** [comment]
@ronald-truepill Thanks for the report. Sorry for going radio silence — this was the inspiration for https://github.com/apollographql/apollo-server/security/advisories/GHSA-2p3c-p3qw-69r4
