### ISSUE TITLE
Set up Changesets in apollo-server

### ISSUE THREAD

**Issue by danilobuerger** [apollographql/apollo-server#6443]
It would be nice if you could use github releases so people can watch this repo and get notifications on releases. This is already the case on other apollo repos like apollo-client.

**Comment by trevor-scheer** [comment]
Thanks @danilobuerger, this is our intention for v4 coming soon. I'll leave this open so we can track it on the milestone.

**Comment by glasser** [comment]
Specifically @trevor-scheer has set up the Changesets tool on that branch. As you can see in the `apollo-utils` repo which he set up similarly, it supports GitHub releases: https://github.com/apollographql/apollo-utils/releases

**Comment by trevor-scheer** [comment]
Via #6616
