### ISSUE TITLE
Nothing working 

### ISSUE THREAD

**Issue by R0N1n-dev** [apollographql/apollo-server#6446]
Apollo server express not working according to documentation instructions. 
Neither does fastify. Nothing but errors for me. All my graphql Backends with Apollo now rendered useless. 
Does ur documentation need updating or better maintenance.
Thanks for the mess. 😤

**Comment by glasser** [comment]
I'm sorry you're frustrated, but without showing us what you tried and how it didn't work, there's nothing we can do to help you.
