### ISSUE TITLE
Unable to install apollo-server

### ISSUE THREAD

**Issue by maxlew** [apollographql/apollo-server#6469]
At the moment users are unable to install apollo-sever since the release of 3.8.0 about an hour ago. I'm not sure if a broken build was published or if the order of publishing needs to be adjusted so as not to cause 'downtime' during a new version rollout.

Looking at the [package.json](https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-express/package.json) file inside of `apollo-server-express` seems to indicate that 3.8.0 was intended to be published, however it's not yet available in NPM - https://www.npmjs.com/package/apollo-server-express.

Running `npm install apollo-server graphql` in a blank project returns the message

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for apollo-server-express@^3.8.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'apollo-server'
npm ERR! notarget
```

node version: 14.19.3
npm version: 6.14.17

**Comment by trevor-scheer** [comment]
Yikes, thanks for the report! Looking into this now.

**Comment by Bigj420** [comment]
Ok

**Comment by trevor-scheer** [comment]
Update: the versions are in a weird state and it appears to be on NPM's side. I've reached out to support and will try to resolve the issue via a patch release or rolling back the `latest` tag on the versions that are `3.8.0` to `3.7.0` (this may be a bad choice if the issue resolves itself, so probably not going to do that as I'm thinking this through).

In the meantime, please specifically install `apollo-server@3.7.0`.

**Comment by trevor-scheer** [comment]
I didn't hear back from NPM tonight, so I went ahead and published new patch versions. All of the `apollo-server-*` packages are now at `v3.8.1` and you should be able to successfully install the latest versions. Thanks again for the report!

**Comment by fsabeti95** [comment]
I have still issues with installing `apollo-server-express@^3.8.1` 

```npm ERR! notarget No matching version found for apollo-server-express@^3.8.1.```

**Comment by hcasanov** [comment]
Hello ! We have found temporary solution with 

npm uninstall apollo-server-express
rm -f package-lock.json
rm -rf node_modules
npm i
npm i --save apollo-server-express@3..8.0

**Comment by dqn** [comment]
The problem is v3.8.1 which used to be able to be installed, can no longer be installed.
Is this a bug with npm? I have apollo-server-express v3.8.1 in local.

**Comment by codebombcode** [comment]
apollo-server-express@^3.8.0 doesn't exist。  The problem is v3.8.1 of apollo-server。so I keep the  version in  v3.8.0 of apollo-server, I solved it。eg: "apollo-server": "^3.8.0" =>  "apollo-server": "3.8.0"

**Comment by KriAga** [comment]
Yes, so currently the fix as mentioned by @hcasanov works fine, just run the below command:

`npm i --save apollo-server-express@3.8.0`

**Comment by dqn** [comment]
They are just workarounds, not a fundamental solution. The problem to be solved is that v3.8.1, which should be publicly available, does not exist.

> All of the apollo-server-* packages are now at v3.8.1 and you should be able to successfully install the latest versions.

**Comment by trevor-scheer** [comment]
This was working before, something is up with npm again. I'll take a look when I start my day and open a ticket with them if it hasn't resolved itself by then.

In the meantime please use the workaround proposed and install the most recent version that's available.

**Comment by Bipin-Chaudhary** [comment]
> This was working before, something is up with npm again. I'll take a look when I start my day and open a ticket with them if it hasn't resolved itself by then.
> 
> In the meantime please use the workaround proposed and install the most recent version that's available.

I have installed graphql previous version and its working fine.

**Comment by trevor-scheer** [comment]
Following up:

I've sent a message to npm. I've also discovered this affects `apollo-server-lambda`. For now please install version `3.8.0` of the following packages if you use them:
`apollo-server` (dependent on `apollo-server-express`)
`apollo-server-express`
`apollo-server-lambda`

You can install a specific version using the following notation as mentioned above:
`npm i apollo-server@3.8.0`

Due to a recent npm issue, `3.8.1` was published _over_ `3.8.0` as a hotfix. Codewise, they are the same, so you're not missing any important fixes in that patch. Thanks for your patience!

Going to reopen until this is resolved.

**Comment by trevor-scheer** [comment]
Still haven't heard from npm. I've updated the `latest` tag of `apollo-server` to `3.8.0` for now, since that's probably the most common and confusing path to error until `apollo-server-express@3.8.1` exists.

**Comment by trevor-scheer** [comment]
Still haven't heard from npm but the version issue seems to have cleared up. Repromoting `apollo-server@3.8.1` to `latest`. Please let me know if you see any other issues.
