### ISSUE TITLE
custom directive doesn't fire on subscription 

### ISSUE THREAD

**Issue by UchihaYuki** [apollographql/apollo-server#6482]
apollo-server-express@2.25.2  
```gql
type Query {
    onlineUsers: [String!]! @authenticated
}

type Subscription {
    message(
        clientId: String
        channelId: String 
    ): Message! @authenticated
}
```
I use the same directive on both query and subscription, and found that it doesn't fire on subscription, but it does fire on query. Is this behavior intended?

**Comment by glasser** [comment]
Apollo Server 2 is not maintained except for security patches.

The support for subscriptions in AS2 was hacky and not well integrated, which led to issues like the above. Rather than provide a poorly-integrated subscriptions feature, Apollo Server 3 has no built in support for subscriptions.
