### ISSUE TITLE
Reduce `standaloneServer` steps (v4)

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/apollo-server#6483]
While pairing, @glasser and I noticed we can simplify the `standaloneServer` API a bit.

Instead of having the user call and `await` `listen`, we can do that within the `standaloneServer` function instead by accepting `listen` args and returning the result of calling `listen`.

so...

```ts
const { url } = await standaloneServer(apolloServer, listenOpts, serverOpts);
```

...or something to that effect.

(rather than)
```ts
const expressServer = standaloneServer(apolloServer, serverOpts);
const { url } = await expressServer.listen(listenOpts);
```

cc @rkoron007

**Comment by glasser** [comment]
Fixed on version-4 in #6489.
