### ISSUE TITLE
Apollo-Server v3 migration - Subscriptions documentation missing validationRules

### ISSUE THREAD

**Issue by Cellule** [apollographql/apollo-server#6492]
I just went through the exercise of migrating from apollo-server v2 to v3 (I know I was kicking that can as long as I could 😅)
I followed the instruction to create the SubscriptionServer myself from Step 5. of https://www.apollographql.com/docs/apollo-server/migration#subscriptions

<img width="539" alt="image" src="https://user-images.githubusercontent.com/4157103/170842489-bf2e7e3b-0f31-4e8d-bc4d-584b0016c0f9.png">

I hit a little issue (not relevant in this issue) and got me digging into Apollo v2's way of doing it.
I stumbled upon the following 
https://github.com/apollographql/apollo-server/blob/ae444b2916deb2fa37dbd8fa091201235dc2ec6d/packages/apollo-server-core/src/ApolloServer.ts#L1048-L1051
(better context)
https://github.com/apollographql/apollo-server/blob/ae444b2916deb2fa37dbd8fa091201235dc2ec6d/packages/apollo-server-core/src/ApolloServer.ts#L1008-L1051

I then realized that only from following the instructions my SubscriptionServer no longer had the validation rules I was using (in my case operation depth limit check and no introspection in production)

Seems like this was omitted from the migration documentation and might have exposed people to be missing expected validation rules in their subscription server.
There's also the whole error formatting part that I'm not even sure if it affects me yet (decided to leave it alone for now)

**Comment by glasser** [comment]
I would highly suggest that, as the migration guide suggests, you stop using `subscriptions-transport-ws` (which has not been actively developed for 4+ years) and switch to `graphql-ws` instead. That said, it would be nice if the migration guide were as complete as possible. Patches to https://github.com/apollographql/apollo-server/blob/main/docs/source/migration.mdx are welcome; folks like you who actually use the feature probably are the best fit for these updates.
