### ISSUE TITLE
Docs responsive design breaks on table

### ISSUE THREAD

**Issue by mDeram** [apollographql/apollo-server#6498]
Hi!

Apollo docs v3:
(This layout issue is easier to see with dark mode on since there is some borders)

In the following page:
https://www.apollographql.com/docs/apollo-server/api/apollo-server#options

The "options" table does not respect the main content column width on a 1280x1024 screen, the article navigation overlap on the article content which should not.

Also when using dev tools to resize the page progressively towards small devices we can see that the "apollo-server-specific options" table does not respect the layout too, being bigger than the normal width of the article content:
https://www.apollographql.com/docs/apollo-server/api/apollo-server#apollo-server-specific-options

Could reproduce with:
Mozilla Firefox 99.0.1
Chromium 101.0.4951.41

![apollo_layout0](https://user-images.githubusercontent.com/26199542/171234319-ce5b1de3-8857-4685-b632-4a62662adf53.png)
![apollo_layout1](https://user-images.githubusercontent.com/26199542/171234316-4b8aa177-ab13-48ef-9cce-f1054a28d18a.png)

**Comment by glasser** [comment]
@StephenBarlow @trevorblades can you look into this?

**Comment by trevorblades** [comment]
Will take a look at this tomorrow and make a fix 👍

**Comment by trevorblades** [comment]
Fixed by https://github.com/apollographql/docs/commit/fb0e85bfba81b3c3a0964f1f1deb9308c8a084d8
