### ISSUE TITLE
apollo-server-cache with serverless redis 

### ISSUE THREAD

**Issue by chronark** [apollographql/apollo-server#6512]
Hey guys,

this isn't a bug or feature request but simply a question if you would consider merging a PR with a new package like [apollo-server-cache-redis](https://github.com/apollographql/apollo-server/tree/main/packages/apollo-server-cache-redis), but using serverless redis by [Upstash](https://upstash.com)?

Many developers deploy apollo server to serverless environments, where a traditional TCP connection can cause trouble.
With Upstash you can connect to redis using HTTP and won't have any connection issues on platforms like Vercel or Cloudflare.

Let me know what you think.

**Comment by trevor-scheer** [comment]
Sounds like a nice addition! We're in the process of moving away from maintaining our own cache adapters by offloading that to the `keyv` package (which specializes in exactly that).

We've written an adapter for `keyv` to be used as Apollo Server's cache. What do you think about implementing your serverless redis wrapper as a `Keyv` instead?

Here's our adapter:
https://github.com/apollographql/apollo-utils/tree/main/packages/keyvAdapter#keyvadapter-class

The syntax would look something like:
```ts
new ApolloServer({
  // ...
  cache: new KeyvAdapter(new ServerlessRedisKeyv(...)),
});
```

**Comment by chronark** [comment]
Sounds perfect, thank you.
