### ISSUE TITLE
Consider removing graphql-tag re-export

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#6527]
typeDefs can be a string. Why do we suggest people use `graphql-tag` for it? Sure, it provides syntax highlighting, but inline schema blocks seems like more of a testing thing than something we actually expect people to use for real apps (vs standalone files).  It feels to me like using `gql` in the server is a marginal enough use case that folks who want to use it can use `graphql-tag` directly.

**Comment by trevor-scheer** [comment]
```ts
Also worth mentioning you can get syntax highlighting (at least in vs code) via
const op = `#graphql
  query { ... }
`;
```

**Comment by glasser** [comment]
Finished on version-4 in #6546.
