### ISSUE TITLE
[apollo-server-cache-redis] document configuration to handle redis connection errors

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/apollo-server#6554]
When using `ioredis` and encountering a network partition, the default redis configuration appends commands to an unbounded queue and waits until the connection to redis is reestablished: https://github.com/luin/ioredis/blob/v5.0.6/lib/cluster/index.ts#L597-L602

For AQPs specifically, this is not the desired behavior. I'm not sure what the right configuration is, but it might be a combination of: 

* [`commandTimeout`](https://luin.github.io/ioredis/interfaces/CommonRedisOptions.html#commandTimeout)
* [`enableOfflineQueue`](https://luin.github.io/ioredis/interfaces/CommonRedisOptions.html#enableOfflineQueue)

**Comment by glasser** [comment]
We no longer maintain a Redis client; instead, we have a generic "keyv adapter" that adapts anything from the Keyv project such as `@keyv/redis`.
