### ISSUE TITLE
Update apollo-server-fastify packages for fastify v4

### ISSUE THREAD

**Issue by akylkb** [apollographql/apollo-server#6576]
The following error occurs

```
/../node_modules/fastify/lib/pluginUtils.js:118
    throw new FST_ERR_PLUGIN_VERSION_MISMATCH(meta.name, requiredVersion, this.version)
          ^
FastifyError [Error]: fastify-plugin: fastify-accepts - expected '3.x' fastify version, '4.0.2' is installed
    at Object.checkVersion (/../node_modules/fastify/lib/pluginUtils.js:118:11)
    at Object.registerPlugin (/../node_modules/fastify/lib/pluginUtils.js:133:16)
    at Boot.override (/../node_modules/fastify/lib/pluginOverride.js:28:57)
    at Plugin.exec (/../node_modules/avvio/plugin.js:80:33)
    at Boot.loadPlugin (/../node_modules/avvio/plugin.js:273:10)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',
  statusCode: 500
}
```

I think need to update these packages to fix this error
@fastify/accepts
@fastify/cors

**Comment by glasser** [comment]
See discussion at https://github.com/apollographql/apollo-server/commit/ea8578cf41e8849241c3de2dd6739aca65c93776#commitcomment-75998670

`@fastify/accepts` is a direct dependency of `apollo-server-fastify`. It looks like [v3](https://github.com/fastify/fastify-accepts/blob/07cdab5765ae9b0f47cd52065bd3a30d155ed9c9/index.js#L60) and [v4](https://github.com/fastify/fastify-accepts/blob/1c0cc9f4bdb20b22aedb4a1e991334430eb447bb/index.js#L60) of this package only work with Fastify v3 and v4 respectively, so it's not super clear to me how to publish a single version of `apollo-server-fastify` which works with either, even if we do assume that this is the *only* change needed to make ASF work with the new version of Fastify (and I have no idea if that's true). Unfortunately in AS3 the versions of the integration packages are tightly coupled to the versions of the core package so we can't just put out an apollo-server-fastify v4 and call it a day.

Soon, Apollo Server will have a simple stable web integration API and it'll be easy for Fastify experts to maintain apollo-server-fastify3 and apollo-server-fastify4 packages.  For the time being, I suspect the best approach would be for a fastify user to put out your own apollo-server-fastify4 package that works with the AS3 API; while that API is complicated and not too stable, we hopefully won't change it much more before AS4 is out!

**Comment by Valeronlol** [comment]
Hey, any updates on this?
We stuck on nestjs v8 because of this issue.
