### ISSUE TITLE
Does it support live directive? 

### ISSUE THREAD

**Issue by shtse8** [apollographql/apollo-server#658]
I want to do live data in my project. Does it support live directive for the latest release? or any reference for me to add this directive in my current apollo-server setup? thanks.

**Comment by martijnwalraven** [comment]
No, Apollo Server (or any other open source server I know of...) doesn't currently support `@live`. We do support subscriptions.

**Comment by shtse8** [comment]
Any plans to support `@live` directive? it's a big improvement to do live data like stock market.
subscription is hard to implement partial data patch to client.

**Comment by martijnwalraven** [comment]
It's definitely on the long term roadmap, but it isn't currently part of the GraphQL specification, and there is a lot of work to do on figuring out the best approach.

**Comment by shtse8** [comment]
I see, thanks for your information. I am so excited when I see this feature. Hope it will be supported soon.

**Comment by shtse8** [comment]
I can use `@live`, `@defer` now. Thanks all.

**Comment by smkhalsa** [comment]
@shtse8 Are you using these directives with apollo-server? Or another server? I'm interested in this for my project as well.

**Comment by shtse8** [comment]
@sammkj I am using @live and @defer with apollo-server. try https://github.com/DxCx/graphql-rxjs
