### ISSUE TITLE
document.document.definitions has undefined operation name

### ISSUE THREAD

**Issue by zelongc** [apollographql/apollo-server#6589]
Hello!
I am using nodejs 12, apollo-server-core 2.25.2, spollo-server-koa 2.25.2
I created a plugin to send the name of the graphql operation to dynatrace. However for some graphql methods, the operation name is undefined in the `GraphQLRequestContext`.

paste some code:

 my schema looks like this:

```
export default gql`
  extend type Mutation {
    exchangeToken(input ExchangeTokenInput!): String! @authenticated
}
`
```
The code where has a problem is:

```javascript
// within the graphql plugin hook:
willSendResponse(ctx: GraphQLRequestContext) {
   logger.info(ctx?.document?.definitions);
}
```

Wha it actual logs is:
```
[
  {
    kind: 'OperationDefinition',
    operation: 'mutation',
    name: undefined,
    variableDefinitions: [],
    directives: [],
    selectionSet: { kind: 'SelectionSet', selections: [Array], loc: [Object] },
    loc: { start: 0, end: 54 }
  }
]
```
However I am expecting: ( the `name: "exchangeToken"` part):
```javascript
[
  {
    kind: 'OperationDefinition',
    operation: 'mutation',
    name: "exchangeToken",
    variableDefinitions: [..some],
    directives: [..some],
    selectionSet: { kind: 'SelectionSet', selections: [Array], loc: [Object] },
    loc: { start: 0, end: 54 }
  }
]
```

Is it expected or a bug? Thanks!

**Comment by glasser** [comment]
You have not shown the operation that you're running here. My guess it it starts with `mutation {` rather than `mutation SomeMutationName {` and thus is an anonymous operation. (exchangeToken is the name of a field you are selected, not the name of the operation.)

**Comment by glasser** [comment]
By the way, if you did down under `selectionSet.selections` you should find the `exchangeToken` you're looking for.
