### ISSUE TITLE
using apollo-server-express to initialize a gateway does not respect intropsection = true

### ISSUE THREAD

**Issue by reduxdj** [apollographql/apollo-server#6592]
Using  a custom apollo-server-express to initialize a gateway does not respect intropsection: true prop.

When using 'apollo-server-express' outside the internal 'apollo-server' setup with 'graphql-tools' loading getSchemas graphql-tools and URLLoader, introspection true is not observed. Using the vanilla 'apollo-server' module an initializing gateway constructs this works.

The work around is to create a verbose introspection query and load the schema and typedefs the same way
 the apollo studio client does.... 

Observed in ^3.9.0

**Comment by glasser** [comment]
It sounds like you're combining a bunch of different software including graphql-tools and URLLoader here. The effect you're describing is surprising, but there's no way for us to investigate unless you include a complete reproduction recipe that allows us to look into it ourselves. I'm going to close for now but am happy to reopen if provided with a full reproduction: a series of steps (probably starting with `git clone` or a link to codesandbox.io) showing exactly what you did and what you saw.
