### ISSUE TITLE
[apollo-server-fastify] Feature request: Better align API with Fastify conventions and general maintenance 

### ISSUE THREAD

**Issue by olyop** [apollographql/apollo-server#6635]
As per #6027, the Apollo Server core team are no longer planning to maintain the `apollo-server-fastify` integration package. As I use Fastify with Apollo myself I thought I would have a go with general maintenance of the package and updating some minor inconsistentes with the API to make it better align with Fastify conventions. I also noted that Apollo Server v4 will be released soon, and like the call for maintainers stated, it would be a good time to update this integration with the changes in this version at the same time.

I have a pull request that implements the changes below, but not sure how to proceed. I definitely need feedback with these changes and support with updating to Apollo Server v4 and if there's any point in making these changes.

### Connecting method
Currently we connect Apollo to Fastify by calling the `createHandler` method for example:
```ts
fastify.register(apollo.createHandler(APOLLO_SERVER_OPTIONS));
```
But in Fastify, community plugins are usually called slightly differently and make use of the `fastify-plugin` (fp) wrapping package. I propose we use this package so the above code would become:
```ts
fastify.register(apollo.plugin, APOLLO_SERVER_OPTIONS);
```
And make use of `fp` by adding plugin metadata and also making use of `sharedHandler` for backwards compatability with `createHandler`.
```ts
class ApolloServer<...> extends ApolloServerBase<...> {
  ...
  public plugin = fp<ApolloFastifyPluginOptions>(
    (fastify, options) => this.sharedHandler(fastify, options),
    { fastify: '3 - 4', name: 'apollo-server-fastify' },
  );
```

### Change all handlers to use async/await
Use async/await in all handlers (more modern syntax).

### Minor: Fastify serializes out of the box
The health check doesn't make use of it. e.g. `'{"status":"fail"}' -> { status: 'pass' }`

**Comment by trevor-scheer** [comment]
Hey @olyop, you sound like just the person I want to talk to!

For v3 things:
We'd be happy to receive a PR which aligns us with the "fastify way" of doing things. We do not claim to be experts when it comes to each of the web frameworks, so we're happy to get help from someone in the space. My requirement with this work would be that there are no breaking changes (either in API or behavior) for current users. Are the changes you're proposing in line with that? If your proposal involves breaking changes to the API, maybe we could add a new export and deprecate the old one? Also, is what you're suggesting compatible with fastify v3 (the major version we currently depend on)?

For v4:
We will have a guide soon for building integrations with AS4. However, we'd really like to get at least Fastify and Lambda integrations up and running ASAP. If you're interested in maintaining a Fastify integration package, I'd be more than happy to work on this with you and have your package ready alongside the AS4 alpha. @yorch has also expressed interest, but I have yet to receive an email from them. If this is interesting to you, please send me an email: trevor@apollographql.com.
