### ISSUE TITLE
unpin renovate to graphql-js 15.x

### ISSUE THREAD

**Issue by setchy** [apollographql/apollo-server#6717]
Now that graphql-js 16.x is supported, is it time to remove the renovate.json5 package rule https://github.com/apollographql/apollo-server/issues/5605#issuecomment-955087681

**Comment by glasser** [comment]
We've upgraded to requiring v16 on `version-4`. On `main`, it makes sense to keep the version installed during the repository's development at v15, so we don't accidentally depend on any v15-specific features in v3.
