### ISSUE TITLE
No cached fields found in redis single instance with configured KeyvAdapter

### ISSUE THREAD

**Issue by sergiycheck** [apollographql/apollo-server#6734]
I am reading apollo server documentation [cache-backend](https://www.apollographql.com/docs/apollo-server/performance/cache-backends#single-instance) and trying to implement listed examples but no fields marked with cache hints in schemas or resolvers can be found in the running redis instance. 

dependencies
```json

  "dependencies": {
    "@apollo/utils.keyvadapter": "^1.1.1",
    "@graphql-tools/schema": "^8.5.0",
    "@keyv/redis": "^2.3.8",
    "apollo-server": "^3.10.0",
    "apollo-server-core": "^3.10.0",
    "apollo-server-express": "^3.10.0",
    "apollo-server-plugin-response-cache": "^3.7.0",
    "dotenv": "^16.0.1",
    "express": "^4.18.1",
    "graphql": "^16.5.0",
    "keyv": "^4.3.3",
    "rimraf": "^3.0.2"
  }
```
I expect to find cached fields here

![image](https://user-images.githubusercontent.com/29612247/181062421-c28e7281-ea6a-4cd5-b711-51ec7bfc02cb.png)

**Comment by glasser** [comment]
Hi, this is most of a reproduction but not quite enough for us to reproduce it.  For example, it requires figuring out how to set up Redis, guessing what operations you ran, etc. Happy to reopen if this contains a complete detailed reproduction with no creativity required. (Most likely your problem is not specific to Redis and could be reproduced with the default in-memory cache.)

**Comment by sergiycheck** [comment]
Hi. Thank for your response.
Actually the project that I provided includes all needed files to start the project.
I am using docker to run redis. I run examples from docs. You may any any query marked with **@cacheControl(maxAge: 30)** 
or query that has setting cache hits in it's resolver.
I have three different files
 - **config-external-caching.ts**
 - **config-in-memory-caching.ts**
 - **config-redis-caching.ts**
which is the exact examples as shown in [apollo server docs](https://www.apollographql.com/docs/apollo-server/performance/cache-backends)
The steps:

1. Start redis with the file  **run-redis.sh** that's located [here](https://github.com/sergiycheck/diff-graphql-projects/blob/main/leaning_from_docs/apollo-performance/run-redis.sh)
```sh
$./run-redis.sh
8a53275be3b8a7c1c61cf066cfbfc8826404fb92ea04164c36217cbefb2258bf
```
2. Start the server with yarn or npm
```bash
yarn run start:dev-redis
```
3. Open your browser at http://localhost:4080/graphql and query the server or use any other method to run 
the query show below.
```gql
query CachedBook {

  cachedBook {
    title
    cachedTitle
  }
}
```
I assume if the result of the query was cached it would be shown within the redis.
I connect to the docker container running redis with command:

```sh
docker exec -it redis-for-cache /bin/bash
```

then I run **redis-cli** command within the docker container

```sh
root@8a53275be3b8:/data# redis-cli
```

and then I try to see any cached data with the command

```sh
127.0.0.1:6379> keys *
(empty array)
127.0.0.1:6379> 
```
and get empty array.
Even If I start the sever with in-memory cache with the command

```sh
yarn run start:dev-in-mem
```
the resolver **cachedBook** is triggered despite of the fact that the corresponding query is marked with **@cacheControl(maxAge: 60)** ( [schema](https://github.com/sergiycheck/diff-graphql-projects/blob/main/leaning_from_docs/apollo-performance/src/schema.ts) ).

I think the cachedBook resolver should be triggered on the user's request after 60 seconds have passed. 
During 60 seconds data is retrieved from cache store. But it's triggered on each subsequent user's request.

Does it have to work like this? I think no. Maybe I don't understand something. Please help or correct me.
What else do I have to provide for you in order to reproduce it? Or maybe I have to use different way for caching with redis and apollo server.

[Full example with all files](https://github.com/sergiycheck/diff-graphql-projects/tree/main/leaning_from_docs/apollo-performance)

**Comment by Tanner-Scadden** [comment]
I have this issue as well on my local machine or if I have a preconfigured redis container on railway. Would love more information on how to cache correctly to help database loads.

**Comment by Tanner-Scadden** [comment]
@sergiycheck I'm not sure if this is your issue, but adding these plugins made my redis cache start working! 

```ts
import { ApolloServerPluginCacheControl } from "apollo-server-core";
import responseCachePlugin from "apollo-server-plugin-response-cache";

const server: ApolloServer = new ApolloServer({
  ...
  cache: new KeyvAdapter(graphqlKeyv),
  plugins: [
      ApolloServerPluginCacheControl({ defaultMaxAge: 60 }),
      responseCachePlugin({
        sessionId: (requestContext) =>
          requestContext.request.http.headers
            .get("authorization")
            ?.split(" ")?.[1] || null,
    }),
  ],
  ...
})
    ```

**Comment by terryf82** [comment]
There is certainly room for improvement in the caching documentation. That said, I was able to get it working with a local redis server with the following setup:
```
import Keyv from "keyv"
import { KeyvAdapter } from "@apollo/utils.keyvadapter"
import responseCachePlugin from "apollo-server-plugin-response-cache"
...
server = new ApolloServer({
      schema,
      ...
      cache: new KeyvAdapter(new Keyv(`redis://${CACHE_SERVER}:6379`)),
      plugins: [
        (responseCachePlugin).default()
      ]
})
```

**Comment by glasser** [comment]
Hi @sergiycheck . Sorry for the delay — busy few months around here. @terryf82 and @Tanner-Scadden are correct. Your example sets up cache metadata for the fields in your schema. By default this is enough to make it send response cache-control HTTP headers that could be used by a CDN or other caching proxy in front of your servers. To additionally make Apollo Server itself cache full responses, you need to install the response cache plugin. This is documented [here as "advanced"](https://www.apollographql.com/docs/apollo-server/performance/caching#caching-with-responsecacheplugin-advanced).

**Comment by sergiycheck** [comment]
Thanks @glasser , @Tanner-Scadden , @terryf82 . I will try. The apollo-server-plugin-response-cache plugin must fix this issue.

**Comment by sergiycheck** [comment]
@glasser 
From apollo server docs about  **apollo-server-plugin-response-cache plugin**
> The plugin uses the same in-memory LRU cache as Apollo Server's other features. For environments with multiple server instances, you might instead want to use a shared cache backend, such as [Memcached or Redis](https://www.apollographql.com/docs/apollo-server/performance/cache-backends#configuring-external-caching).

That is why I didn't used for the first time because it's said that **apollo-server-plugin-response-cache use in-memory LRU cache as Apollo Server's other features**

@Tanner-Scadden and @terryf82 did not provide the full configuration of their apollo server with appropriate redis configuration and package versions.
I don't know how did they managed to cache responses.

I provide a full config with the link to the repository which I used to try to cache responses with redis

[Runnable reproduction](https://github.com/sergiycheck/diff-graphql-projects/tree/main/leaning_from_docs/apollo-performance)

package.json file

```json
{
  "name": "apollo-performance",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "tsc",
    "start:default": "export NODE_ENV=development && nodemon ./src/cache-backends/default-persisted-queries.ts",
    "start:dev-external": "export NODE_ENV=development && nodemon ./src/cache-backends/config-external-caching.ts",
    "start:dev-in-mem": "export NODE_ENV=development && nodemon ./src/cache-backends/config-in-memory-caching.ts",
    "start:dev-redis:express": "export NODE_ENV=development && nodemon ./src/cache-backends/config-redis-caching-express.ts",
    "start:dev-redis:apollo": "export NODE_ENV=development && nodemon ./src/cache-backends/config-redis-caching-apollo.ts",
    "start:prod": "export NODE_ENV=production && node dist"
  },
  "devDependencies": {
    "@types/express": "^4.17.13",
    "nodemon": "^2.0.19",
    "ts-node": "^10.9.1",
    "typescript": "^4.7.4"
  },
  "dependencies": {
    "@apollo/utils.keyvadapter": "^1.1.1",
    "@graphql-tools/schema": "^8.5.0",
    "@keyv/redis": "^2.3.8",
    "apollo-server": "^3.10.0",
    "apollo-server-core": "^3.10.0",
    "apollo-server-express": "^3.10.0",
    "apollo-server-plugin-response-cache": "^3.7.0",
    "cors": "^2.8.5",
    "dotenv": "^16.0.1",
    "express": "^4.18.1",
    "graphql": "^16.5.0",
    "keyv": "^4.3.3",
    "rimraf": "^3.0.2"
  }
}

```

**config-redis-caching-apollo.ts** file

```ts
import dotenv from 'dotenv';
dotenv.config();

import { ApolloServer } from 'apollo-server';
import { ApolloServerPluginLandingPageLocalDefault } from 'apollo-server-core';
import { GraphQLSchema } from 'graphql';
import Keyv from 'keyv';
import { KeyvAdapter } from '@apollo/utils.keyvadapter';
import responseCachePlugin from 'apollo-server-plugin-response-cache';

import schema from '../schema';

async function startApolloServer(schema: GraphQLSchema) {
  const redis_port = process.env.REDIS_PORT;
  const redis_host = process.env.REDIS_HOST;

  const keyVInstance = new Keyv(`redis://${redis_host}:${redis_port}`);
  const keyVAdapter = new KeyvAdapter(keyVInstance);

  const server = new ApolloServer({
    schema,
    csrfPrevention: true,
    introspection: true,
    cache: keyVAdapter,
    plugins: [
      ApolloServerPluginLandingPageLocalDefault({ embed: true }),
      responseCachePlugin(),
    ],
  });

  const port = process.env.PORT;
  await new Promise<void>((resolve) => server.listen({ port: port }, resolve));
  console.log(`🚀 Server ready at http://localhost:${port}${server.graphqlPath}`);
}

startApolloServer(schema);

```

**schema.ts** file

```ts
import { CacheScope } from 'apollo-server-types';
import { makeExecutableSchema } from '@graphql-tools/schema';
import { GraphQLResolveInfo } from 'graphql';

type Book = {
  title: string;
  cachedTitle: string;
};

type Reader = {
  book: Book;
};

const books: Book[] = [
  { title: 'book title 1', cachedTitle: 'cached title 1' },
  { title: 'book title 2', cachedTitle: 'cached title 2' },
  { title: 'book title 3', cachedTitle: 'cached title 3' },
];

const typeDefs = /* GraphQL */ `
  enum CacheControlScope {
    PUBLIC
    PRIVATE
  }

  directive @cacheControl(
    maxAge: Int
    scope: CacheControlScope
    inheritMaxAge: Boolean
  ) on FIELD_DEFINITION | OBJECT | INTERFACE | UNION

  type Query {
    books: [Book]
    book: Book
    cachedBook: Book @cacheControl(maxAge: 60)
    reader: Reader @cacheControl(maxAge: 40)
  }

  # Error unknown directive "@key"
  # type Book @key(fields: "isbn") @cacheControl(maxAge: 30) {
  #   isbn: String!
  #   title: String
  # }

  type Book {
    title: String
    cachedTitle: String @cacheControl(maxAge: 30)
  }

  type Reader {
    book: Book @cacheControl(inheritMaxAge: true)
  }
`;

// TODO: can not see cached fields in
// redis keys
const resolvers = {
  Query: {
    books: (_parent: any, _args: any, context: any, info: GraphQLResolveInfo) => {
      return books;
    },

    book: (_parent: any, _args: any, context: any, info: GraphQLResolveInfo) => {
      info.cacheControl.setCacheHint({ maxAge: 60, scope: CacheScope.Public });
      const [first] = books;
      return first;
    },

    cachedBook: (_parent: any, _args: any, context: any, info: GraphQLResolveInfo) => {
      const cachedBook: Book = {
        title: 'cached book title 1',
        cachedTitle: 'cached title for cached book',
      };

      console.log('getting cached book', cachedBook);

      return cachedBook;
    },

    reader: (_parent: any, _args: any, context: any, info: GraphQLResolveInfo) => {
      const [_, second] = books;
      const reader: Reader = {
        book: second,
      };

      return reader;
    },
  },
};

const schema = makeExecutableSchema({ typeDefs, resolvers });
export default schema;

```

response that I get

![image](https://user-images.githubusercontent.com/29612247/194370184-3f56851c-53ff-45c6-a3e0-af29d47e94eb.png)

Something is wrong with  responseCachePlugin() because I can get response without using it.

Any Ideas ?

**Comment by glasser** [comment]
The error in your screenshot refers to DataLoader, which isn't mentioned anywhere in your code above. I'm not sure that you're running the code you're sharing...

**Comment by sergiycheck** [comment]
You can check it locally on your machine if you don't believe the results I provided. I said that I could get the response if I didn't use responseCachePlugin() in plugin section. I provided all the code I used with the link to reproducible example. What else do I have to provide to convince you ?

**Comment by glasser** [comment]
You have a large repository with many subprojects in it. I think the subproject I'm supposed to look at is `leaning_from_docs/apollo-performance` but I'm not sure — for example, it has no references to DataLoader even though your error message does. Then it has six different start scripts. Not sure which one you're using. Try to require as little creativity as possible from me, because that minimizes the chances that I'll guess something different from what you're doing and not be able to reproduce! Also, ideally, if the issue can be reproduced both with Redis and with the in-memory cache, it's best to present the in-memory version so your detailed instructions don't have to include setting up Redis too...

But still, I don't understand how the server would be using DataLoader if you're not using it in your app...

**Comment by sergiycheck** [comment]
Finally managed to make redis working with the following setup. Now I am able to cache responses with cache hints and see the actual data stored in redis.

package.json

```json
{
  "name": "sample_simple_with_redis",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "tsc",
    "start": "nodemon ./src/index.ts"
  },
  "devDependencies": {
    "@types/express": "^4.17.14",
    "nodemon": "^2.0.20",
    "ts-node": "^10.9.1",
    "typescript": "^4.8.4"
  },
  "dependencies": {
    "@apollo/utils.keyvadapter": "^1.1.2",
    "@graphql-tools/schema": "^9.0.4",
    "@keyv/redis": "^2.5.1",
    "apollo-server": "^3.10.3",
    "apollo-server-core": "^3.10.3",
    "apollo-server-express": "^3.10.3",
    "apollo-server-plugin-response-cache": "^3.7.1",
    "dotenv": "^16.0.3",
    "express": "^4.18.1",
    "graphql": "^16.6.0",
    "keyv": "^4.5.0",
    "rimraf": "^3.0.2"
  }
}

```

index.ts

```ts
import dotenv from 'dotenv';
dotenv.config();

import { ApolloServer } from 'apollo-server';
import { ApolloServerPluginLandingPageLocalDefault } from 'apollo-server-core';
import { GraphQLSchema } from 'graphql';

import Keyv from 'keyv';
import { KeyvAdapter } from '@apollo/utils.keyvadapter';

import responseCachePlugin from 'apollo-server-plugin-response-cache';
import schema from './schema';

async function startApolloServer(schema: GraphQLSchema) {
  const redis_port = process.env.REDIS_PORT;
  const redis_host = process.env.REDIS_HOST;
  const keyVInstance = new Keyv(`redis://${redis_host}:${redis_port}`);
  const keyVAdapter = new KeyvAdapter(keyVInstance);

  const server = new ApolloServer({
    schema,
    csrfPrevention: true,
    introspection: true,
    // cache: 'bounded',
    // cache: new KeyvAdapter(new Keyv()),
    cache: keyVAdapter,
    plugins: [
      ApolloServerPluginLandingPageLocalDefault({ embed: true }),
      responseCachePlugin(),
    ],
  });

  const port = process.env.PORT;
  await new Promise<void>((resolve) => server.listen({ port: port }, resolve));
  console.log(`🚀 Server ready at http://localhost:${port}${server.graphqlPath}`);
}

startApolloServer(schema);

```

schema.ts

```ts
import { CacheScope } from 'apollo-server-types';
import { makeExecutableSchema } from '@graphql-tools/schema';
import { GraphQLResolveInfo } from 'graphql';

type Book = {
  title: string;
  cachedTitle: string;
};

const books: Book[] = [
  { title: 'book title 1', cachedTitle: 'cached title 1' },
  { title: 'book title 2', cachedTitle: 'cached title 2' },
  { title: 'book title 3', cachedTitle: 'cached title 3' },
];

const typeDefs = /* GraphQL */ `
  enum CacheControlScope {
    PUBLIC
    PRIVATE
  }

  directive @cacheControl(
    maxAge: Int
    scope: CacheControlScope
    inheritMaxAge: Boolean
  ) on FIELD_DEFINITION | OBJECT | INTERFACE | UNION

  type Query {
    books: [Book]
    book(title: String): Book
  }

  type Book @cacheControl(maxAge: 60, scope: PUBLIC) {
    title: String
    cachedTitle: String
  }
`;

const resolvers = {
  Query: {
    books: (_parent: any, _args: any, context: any, info: GraphQLResolveInfo) => {
      info.cacheControl.setCacheHint({ maxAge: 60, scope: CacheScope.Public });
      console.log('getting books', books);
      return books;
    },

    book: (
      _parent: any,
      args: { title: string },
      context: any,
      info: GraphQLResolveInfo
    ) => {
      const book = books.find((book) => book.title.includes(args.title));
      console.log('getting book', book);
      return book;
    },
  },
};

const schema = makeExecutableSchema({ typeDefs, resolvers });
export default schema;

```
Actual data in the running redis container

![image](https://user-images.githubusercontent.com/29612247/194708647-05d744fc-4009-4687-9bd4-4d81b8601d70.png)

Works both with **cache: bounded and simple external in-memory cache new KeyvAdapter(new Keyv())**

**Comment by glasser** [comment]
We'd definitely love to improve the caching documentation; we made a big pass on it earlier this year but clearly it hasn't been enough. That said, I still don't follow what @sergeyicheck's issue was, nor do I know what yours is @david-j-davis. But definitely interested in looking at a PR to improve our docs, or more precise descriptions of what was misleading?

**Comment by zanechua** [comment]
@glasser 

Going through the AS4 migration docs and seeing similar behaviour here. 

Can I clarify that, if you:

1.  Implement a cache backend (https://www.apollographql.com/docs/apollo-server/performance/cache-backends/) e.g. Redis
2. Set the cache-control directive on a type (https://www.apollographql.com/docs/apollo-server/performance/caching#in-your-schema-static) 

I should be seeing the cache entries appear in Redis?

**Comment by glasser** [comment]
Yes, assuming that the overall operation is cacheable and not just, say, one field.
