### ISSUE TITLE
Restore all docs to version-4 branch

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#6758]
We removed all the docs on version-4 because they had not been evaluated to see if they are up to date. We need to restore all of them and make sure they are accurate.

## Pages to Update

* [x] [Introduction](https://www.apollographql.com/docs/apollo-server/)
* [x] [Get started](https://www.apollographql.com/docs/apollo-server/getting-started)
* [x] [Choosing which package to use](https://www.apollographql.com/docs/apollo-server/integrations/middleware)
**New in v3**
    * [x] [Migrating to Apollo Server 3](https://www.apollographql.com/docs/apollo-server/migration)
**Defining a Schema**
    * [x] [Schema basics](https://www.apollographql.com/docs/apollo-server/schema/schema)
    * [x] [Unions and interfaces](https://www.apollographql.com/docs/apollo-server/schema/unions-interfaces)
    * [x] [Custom scalars](https://www.apollographql.com/docs/apollo-server/schema/custom-scalars)
    * [x] [Directives](https://www.apollographql.com/docs/apollo-server/schema/directives)
    * [x] [Creating directives](https://www.apollographql.com/docs/apollo-server/schema/creating-directives) (REMOVED)
**Fetching Data**
    * [x] [Resolvers](https://www.apollographql.com/docs/apollo-server/data/resolvers)
    * [x] [Data sources](https://www.apollographql.com/docs/apollo-server/data/data-sources) (REPLACED "Fetching from REST")
    * [x] [Error handling](https://www.apollographql.com/docs/apollo-server/data/errors)
    * [x] [File uploads](https://www.apollographql.com/docs/apollo-server/data/file-uploads) (REMOVED)
    * [x] [Subscriptions](https://www.apollographql.com/docs/apollo-server/data/subscriptions)
**Development Workflow**
    * [x] [Build and run queries](https://www.apollographql.com/docs/apollo-server/testing/build-run-queries)
    * [x] [Request format](https://www.apollographql.com/docs/apollo-server/requests)
    * [x] [Mocking](https://www.apollographql.com/docs/apollo-server/testing/mocking)
    * [x] [Integration testing](https://www.apollographql.com/docs/apollo-server/testing/testing)
**Performance**
    * [x] [Caching](https://www.apollographql.com/docs/apollo-server/performance/caching)
    * [x] [Cache backends](https://www.apollographql.com/docs/apollo-server/performance/cache-backends)
    * [x] [Automatic persisted queries](https://www.apollographql.com/docs/apollo-server/performance/apq)
**Security**
    * [x] [Auth](https://www.apollographql.com/docs/apollo-server/security/authentication)
    * [x] [CORS](https://www.apollographql.com/docs/apollo-server/security/cors)
    * [x] [Terminating SSL](https://www.apollographql.com/docs/apollo-server/security/terminating-ssl)
    * [x] [Proxy configuration](https://www.apollographql.com/docs/apollo-server/proxy-configuration)
**Deployment**
    * [x] [Heroku](https://www.apollographql.com/docs/apollo-server/deployment/heroku)
    * [ ] [Lambda](https://www.apollographql.com/docs/apollo-server/deployment/lambda)
    * [ ] [Azure Functions](https://www.apollographql.com/docs/apollo-server/deployment/azure-functions)
    * [ ] [Google Cloud Functions](https://www.apollographql.com/docs/apollo-server/deployment/gcp-functions)
**Monitoring**
    * [x] [Metrics and logging](https://www.apollographql.com/docs/apollo-server/monitoring/metrics)
    * [x] [Health checks](https://www.apollographql.com/docs/apollo-server/monitoring/health-checks)
**API Reference**
    * [x] [ApolloServer](https://www.apollographql.com/docs/apollo-server/api/apollo-server)
**Built-in Plugins**
    * [x] [Overview](https://www.apollographql.com/docs/apollo-server/builtin-plugins)
    * [x] [Usage reporting](https://www.apollographql.com/docs/apollo-server/api/plugin/usage-reporting)
    * [x] [Schema reporting](https://www.apollographql.com/docs/apollo-server/api/plugin/schema-reporting)
    * [x] [Inline trace](https://www.apollographql.com/docs/apollo-server/api/plugin/inline-trace)
    * [x] [Drain HTTP server](https://www.apollographql.com/docs/apollo-server/api/plugin/drain-http-server)
    * [x] [Cache control](https://www.apollographql.com/docs/apollo-server/api/plugin/cache-control)
    * [x] [Landing pages](https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages)
**Custom Plugins**
    * [x] [Creating plugins](https://www.apollographql.com/docs/apollo-server/integrations/plugins)
    * [x] [Event reference](https://www.apollographql.com/docs/apollo-server/integrations/plugins-event-reference)

**Comment by glasser** [comment]
(Assigning @rkoron007 but this is likely a group project.)

**Comment by rkoron007** [comment]
Added the checklist of pages to update! :)

**Comment by rkoron007** [comment]
Things left to do:
- handle the deployment articles for the different AS4 integrations (once they exist)
- Figure how we want to handle the "Choosing which package to use" article.
  - It does feel like an article covering the different integrations would be a great add

**Comment by glasser** [comment]
I'm very excited to mark this as complete!
