### ISSUE TITLE
Request object not being received the same way on graphqlExpress and graphiqlExpress

### ISSUE THREAD

**Issue by welingtonms** [apollographql/apollo-server#680]
I have the following code, created based on the documentation availbale on [https://www.apollographql.com/docs/apollo-server/setup.html].

`
app.use('/graphql', graphqlExpress(request => {
    console.log('>>> graphql', request.session);
    return {
      schema,
      context: { user: request.session.user }
    };
  }));`

  `app.use('/graphiql', graphiqlExpress(request => {
    console.log('>>> graphiql', request.session);
    return {
      endpointURL: '/graphql',
      context: { user: request.session.user }
    };
  }));
`

What is happening is that the requestion session object is coming with the right info (user, in this case) only for graphiqlExpress, but not for graphqlExpress.
Based on the source code, there should be no difference, right?

**Comment by gregmartyn** [comment]
Click graphqlExpress settings cog. Add "request.credentials": "same-origin"

**Comment by trevorblades** [comment]
Did @gregmartyn's suggestion fix the problem? Closing this issue now, but please reopen if the issue still exists.
