### ISSUE TITLE
How to Separate Subscriptions alone to another server

### ISSUE THREAD

**Issue by gijo-varghese** [apollographql/apollo-server#681]
I'm planning to host my website on Google App Engine (GAE). So I don't have to worry about the scaling (I'll be using Redis or some other pubsub). However the problem is GAE doesn't support web sockets. I heavily use GraphQL subscriptions.

What Google recommends is to separate web socket into another VM (like Google Compute Engine) and keep the rest inside GAE: https://cloud.google.com/solutions/real-time-gaming-with-node-js-websocket

Is it possible to do this on Apollo Server? I'm using node js apollo-server-express

**Comment by abernix** [comment]
I realize it's been quite some time since you opened this, but if you haven't already figured this out, I'd recommend taking this question to the [Apollo community on Spectrum.chat](https://spectrum.chat/apollo) to discuss it further.  Thanks!
