### ISSUE TITLE
What's the purpose of duplicate packages

### ISSUE THREAD

**Issue by iamclaytonray** [apollographql/apollo-server#682]
I noticed that for every `apollo-server-*` package, there's also a `graphql-server-*` package. The `graphql` packages simply export `apollo` packages. I'm slightly curious/puzzled as to why there is so much duplication.

**Comment by martijnwalraven** [comment]
Apollo Server used to be called GraphQL Server, so the `graphql-server-` packages are placeholders from before the rename. We didn't want to break existing usage, so that's why we've left them in so far. But we'll likely at least deprecate them with the next release.

**Comment by iamclaytonray** [comment]
Okay. So if I contribute, just carry on with `apollo-server-*` and ignore everything else?

**Comment by martijnwalraven** [comment]
Yep!
