### ISSUE TITLE
Upgrade GraphQL to v16+?

### ISSUE THREAD

**Issue by ylemberg** [apollographql/apollo-server#6838]
Seems there some breaking changes that prevents the use of latest GraphQL. Would it be possible to upgrade GraphQL to 16+? 

https://github.com/apollographql/apollo-server/blob/main/package.json#L106

**Comment by trevor-scheer** [comment]
That dependency is for development at the monorepo level. `apollo-server-core` claims support for graphql v16: https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-core/package.json#L52

If you can be more specific about what problems you're seeing, I'll gladly reopen this. Please provide a reproduction (sandbox, clonable repo) that I can run to see the errors you're experiencing.
