### ISSUE TITLE
responseCachePlugin and empty arrays do not respect maxAge of fields requested

### ISSUE THREAD

**Issue by intellix** [apollographql/apollo-server#6839]
When using responseCachePlugin and the response is an empty array, the whole response will get cached because the amount resolver was never called (unexpected). If the response contains an array of wallets, it'll have a 0 cache (expected).

**Packages:** 
 - **graphql**: 15.8.0
 - **apollo-server**: 3.5.0
 -  **apollo-server-cache-redis**: 3.3.0
 - **apollo-server-plugin-response-cache**: 3.4.0

**Setup:**
```ts
import { RedisCache } from 'apollo-server-cache-redis';
import responseCachePlugin from 'apollo-server-plugin-response-cache';

... 

plugins: [
  responseCachePlugin({
    cache: new RedisCache({ ... }),
    sessionId: requestContext => requestContext.request.http.headers.authorization || null,
  }),
]
```

**Type definitions:**
```gql
type Query {
  wallets: WalletConnection!
}

type WalletConnection @cacheControl(maxAge: 30, scope: PRIVATE) {
  pageInfo: PageInfo!
  edges: [WalletEdge]
  total: Int
}

type WalletEdge @cacheControl(maxAge: 30, scope: PRIVATE) {
  node: Wallet
  cursor: String!
}

type Wallet implements Node @cacheControl(maxAge: 30, scope: PRIVATE) {
  id: ID!
  amount: Float @cacheControl(maxAge: 0)
}
```

**And a query like so** (should have 0 maxAge due to requesting amount field):
```gql
{
  wallets {
    edges {
      node {
        id
        amount
      }
    }
  }
}
```

**Response:**
```
{
  wallets: {
    edges: []
  }
}
```

If the response is an empty array, it'll get cached for 30 seconds (we assume because the amount resolver was not called since the response was empty).

I would have expected the subsequent calls not to be cached. Should the caching be based on the actual fields requested or that the resolvers were called? The way it currently works was surprising and unexpected for us.

**Comment by trevor-scheer** [comment]
I don't understand why the `amount` resolver be called? There is no `wallet` as you've said, so what would the `parentValue` (1st arg) be for the `amount` resolver?

Also, isn't it odd here for `wallets` to be an array at all? Its a `WalletConnection!`. At the very least wouldn't you expect something like:
`{pageInfo: { ... }, edges: [], total: 0}`

**Comment by intellix** [comment]
ok sorry, yeah it's not an array but I mean the cache is 30sec because the edges array is empty (edited original post to show the response)

**Comment by glasser** [comment]
There's a lot of subtlety to how cache control annotations work in Apollo Server; we won't be able to really help you without a complete reproduction we can trivially run on ourselves without any creativity (eg, detailed instructions starting with `git clone` or using something like codesandbox.io). Happy to reopen if there's a reproduction!

**Comment by intellix** [comment]
Basic reproduction: https://codesandbox.io/s/apollo-cache-empty-bug-xlc5lc
Steps: 

1) Query for wallets from userId: 2
```gql
query {
  wallets(userId: 2) {
    edges {
       node {
         id
         amount
       }
    }
  }
}
```

2) Create a Wallet for userId 2:
```gql
mutation {
  createWallet(input: {
    userId: "2",
    amount: 10,
  }) {
    wallet {
      id
      amount
    }
  }
}
```

3) Re-query for wallets for userId 2:
```gql
query {
  wallets(userId: 2) {
    edges {
       node {
         id
         amount
       }
    }
  }
}
```

You'll receive an empty list of edges, despite querying for amount which should bypass cache for the query

**Comment by glasser** [comment]
Thanks for the reproduction! You have described the issue correctly.

This particular response cache plugin does in fact choose its cache policy based on the resolvers that actually run in the execution of the operation, not based on a static analysis of the operation text.

This is actually important... after all, consider

```
interface Interface {
  id: ID
}

type Foo implements Interface {
  id: ID @cacheControl(maxAge: 40)
}

type Bar implements Interface {
  id: ID @cacheControl(maxAge: 50)
}

type Baz implements Interface {
  id: ID
}

type Query {
  someInterface: Interface @cacheControl(maxAge: 100)
}
```

```
query { someInterface { id } }
```

What cache policy should we assign to the `id` execution here? We can't know until we run the query and see if `someInterface` returns null, Foo, Bar, or Baz.

What you really need is a more direct way for your mutation to do cache invalidations. The rudimentary full response cache plugin that ships with Apollo Server doesn't support this; there are other cache plugins like https://github.com/thematters/apollo-response-cache that do.

**Comment by glasser** [comment]
(As a work-around, you could potentially use the `info` argument passed to the `wallets` resolver to look at `info.fieldNodes.selectionSet` with the graphql visitor and try to figure out if `amount` is being queried, and use `info.cacheControl.cacheHint.restrict` to dynamically set cache policy from `wallets`.)
