### ISSUE TITLE
Custom http response for context error

### ISSUE THREAD

**Issue by rrocha97** [apollographql/apollo-server#6840]
hey guys I've been struggling handling authentication from the context in the apollo server constructor, when the user is right it works perfect but the issue is when the user is wrong, I'm customizing my error using formatError attribute in the constructor, but it only changes my body message but my HTTP status code always is 400, I would like to have the ability to send custom status code in this point like 401 which is more accurate.
To follow the standard I'm using the class AuthenticationError from apollo-server-errors to parse my error.

Debugging the module I found when context fails it is only available to send two possible status code 400 or 500, it would be great if the user will send a custom status code at this point.

Maybe to follow the standard we could add another attribute  to the error class and  set by default standard status code for example for AuthenticationError it should have 401.

**Comment by glasser** [comment]
You're right — you can't override this right now, which is awkward.

I've made a change that should fix this in the upcoming Apollo Server 4: #6857.

**Comment by glasser** [comment]
Fixed on version-4 in #6857.
