### ISSUE TITLE
Use `getDirectives` when retrieving `cacheControl` directives

### ISSUE THREAD

**Issue by benatshippabo** [apollographql/apollo-server#6870]
## Issue
Currently we retrieve directives by calling `.directives` on the AST node, but this limits users with a code-first approach since in order for users to specify `inheritMaxAge` [it has to be statically defined](https://www.apollographql.com/docs/apollo-server/performance/caching/#recommended-starting-usage:~:text=Note%20that%20you%20can%20only%20set%20inheritMaxAge%20statically.) 

<details>
<summary>Context</summary>

https://github.com/apollographql/apollo-server/blob/f6c5c9fec04c222aa15272b90d203ddc3fe64857/packages/apollo-server-core/src/plugin/cacheControl/index.ts#L305-L321

https://github.com/apollographql/apollo-server/blob/f6c5c9fec04c222aa15272b90d203ddc3fe64857/packages/apollo-server-core/src/plugin/cacheControl/index.ts#L305-L321

https://github.com/apollographql/apollo-server/blob/f6c5c9fec04c222aa15272b90d203ddc3fe64857/packages/apollo-server-core/src/plugin/cacheControl/index.ts#L323-L333

https://github.com/graphql/graphql-js/issues/3213#issuecomment-892676158

https://github.com/graphql/graphql-js/issues/1343

</details>

## Proposal
We currently already use parts of `@graphql-tools/*`. We can use `@graphql-tools/utils` [`getDirectives`](https://www.graphql-tools.com/docs/schema-directives#what-about-code-first-schemas) so that users with a code-first approach are able to specify directives via `extensions.directives`.

So something like:

```ts
cacheAnnotationFromDirectives([
  // read directives from schema
  ...t.astNode.directives,
  // read directives specified under `extensions`
  ...getDirectives(schema, t.astNode)
])
```

and then users could do:

```ts
new GraphQLObjectType({
  name: 'ObjectInheritingMaxAge',
  fields: {
    date: { type: new GraphQLNonNull(GraphQLDate) },
  },
  extensions: {
    directives: {
      cacheControl: {
        inheritMaxAge: true,
      },
    },
  },
})
```

**Comment by glasser** [comment]
It's an interesting point. I do know that some movement has happened lately in the GraphQL world as far as potentially providing a more standard way of exposing directives (eg https://github.com/graphql/graphql-spec/issues/300) and it might be a bit of a shame to adopt the non-standard `extensions.directives` from graphql-tools if a more standard way is coming soon. I'm not sure why it's impossible for TypeGraphQL to just create AST nodes directly...

**Comment by benatshippabo** [comment]
Got it. Makes sense to me
