### ISSUE TITLE
[nodemon] clean exit - waiting for changes before restart

### ISSUE THREAD

**Issue by mrhouzlane** [apollographql/apollo-server#6887]
Server is not running : `[nodemon] clean exit - waiting for changes before restart`

Server in index.js which is main in scripts in package.json 
``` 
 // Run server
    httpServer.listen({ port:config.apolloServerPort }, () => {
        logger.info(`GraphQL Server ready at http://${ip.address()}:${config.apolloServerPort}${ apolloServer.graphqlPath }`);
        logger.info(`GraphQL Subscriptions ready at ws://${ip.address()}:${config.apolloServerPort}${ apolloServer.subscriptionsPath }`);
        console.info(`GraphQL Server ready at http://${ip.address()}:${config.apolloServerPort}${ apolloServer.graphqlPath }`);
        console.info(`GraphQL Subscriptions ready at ws://${ip.address()}:${config.apolloServerPort}${ apolloServer.subscriptionsPath }`);

            console.log("hey app is listening"); 

``` 

I have also this line of code : ``` apolloServer.installSubscriptionHandlers(httpServer); ``` 
but installSubscriptionHandlers seems not to be working anymore.

**Comment by glasser** [comment]
I don't quite follow. Can you provide a complete detailed reproduction that would enable me to see this on my machine (eg, steps that start with `git clone` and require no creativity on my part)?

installSubscriptionHandlers (and direct integration with an outdated and unmaintained implementation of GraphQL subscriptions) was removed in Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/data/subscriptions/
