### ISSUE TITLE
Exemple for Hapi 17 is wrong

### ISSUE THREAD

**Issue by orblazer** [apollographql/apollo-server#689]
Hello, this exemple for hapi is wrong, he causes a hapi crash :
```js
await server.register(graphqlHapi, {
  path: '/graphql',
  graphqlOptions: {
    schema: myGraphQLSchema,
  },
  route: {
    cors: true
  }
});
```

This is correct exemple :
```js
await server.register({
  plugin: graphqlHapi,
  options: {
    path: '/graphql',
    graphqlOptions: {
      schema: myGraphQLSchema
    },
    route: {
      cors: true
    }
  }
})
```

**Comment by EgoAleSum** [comment]
note that you referenced graphiqlHapi not graphqlHapi

Thanks for pointing this out, my PR got merged so I don't have the ability to fix this anymore.

**Comment by orblazer** [comment]
@EgoAleSum Thanks, i have fix the name

**Comment by palash7563** [comment]
can anyone tell me how to enable the GUI of graphql in hapiv17

**Comment by abernix** [comment]
This should have been fixed by https://github.com/apollographql/apollo-server/pull/690.  Thanks!
