### ISSUE TITLE
Expose apollo usage reporting hostname as constant

### ISSUE THREAD

**Issue by danilobuerger** [apollographql/apollo-server#6892]
It would be nice if the apollo usage reporting hostname `usage-reporting.api.apollographql.com` would be exposed as a constant. That way it can be imported into the application to handle outgoing requests without having to hardcode the hostname themselves.

**Comment by glasser** [comment]
I'm not sure what you mean by this: like setting up some sort of proxy?

**Comment by glasser** [comment]
No, I mean, what do you want to use it for.

**Comment by danilobuerger** [comment]
@glasser to be able to inspect outgoing requests. For example I might want to trace outgoing requests but not the ones to the usage reporting api. It would be nice not to hard code the hostname in case it ever changes, so an exported const would be nice.

**Comment by glasser** [comment]
We're going to do our best to ensure that the hostname doesn't change often. We document the URL at https://www.apollographql.com/docs/studio/data-privacy/#where-is-data-sent
