### ISSUE TITLE
v4: VSCode autocomplete broken for AS4 deep imports

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/apollo-server#6899]
Not sure if this is a misconfiguration of the published package or if it's something that's unsupported by VSCode, needs more investigation. It appears that (through a quick manual test) `@apollo/client` suffers from the same problem.

**Comment by glasser** [comment]
Might be helpful to provide a detailed reproduction recipe.

**Comment by trevor-scheer** [comment]
1. Run the following:
```bash
mkdir repro && cd repro && npm init -y && npm i @apollo/server && touch index.js
```
2. Open `repro/index.js` in VS Code
```bash
code index.js # if you've installed VS Code to your PATH
```
3. Start typing `ApolloServer` and note the autocomplete with suggestion to auto import.
4. Start typing `startStandaloneServer` and note that autocomplete doesn't trigger.

The same applies to all deep imports.

**Comment by glasser** [comment]
I know this is about an entirely different feature (typeVersions not exports) but this comment might still be relevant maybe: https://github.com/microsoft/TypeScript/issues/43133#issuecomment-1297773799
