### ISSUE TITLE
Feature request: Provide better dev experience when returning `Promise<Promise<any>>` in a resolver

### ISSUE THREAD

**Issue by tlenex** [apollographql/apollo-server#6934]
**Context:**
Large GraphQL codebase. We were experiencing random unhandled promise errors and app crash on node server with [`unhandledRejection`](https://nodejs.org/api/process.html#event-unhandledrejection) with stack trace pointing out our deep in the code methods.
Node.js: v16.x

**The problem:**
lets take this code
```
const users = {
  async getUser() {
    // of course error might be way deeper in the code
    throw Error('Not found')
  }
}

const resolvers = {
  Query: {
    async user(parent, args, context, info) {
      return users.getUser(args.id);
    }
  }
}
```
Looks fine at first glance, right? Apollo should catch the `Error`, right? You are wrong! It's very misleading. In current solution we are missing `await` keyword just before returned `users.getUser(args.id);`. Without it resolver is returning `Promise<Promise<Error>>` and built-in apollo `.catch()` will only handle the outer `Promise`, the inner one might kill the app with `unhandledRejection`.
To be even weirder, if `getUser()` method resolves, then everything works fine 😮

**The feature:**
Lets handle `Promise<Promise<any>>` situation ahead of time with something like:
- log warning
- throw error
- better type-safety

Any of above would be fine and it would be very useful for everyone to avoid this mistake we did. It can be very time-consuming in large code base.

**Comment by glasser** [comment]
Hmm, I'm not sure that I follow.  In general, JS sorta unwraps nested Promises (eg, returning a value and returning a Promise to a value from a `then` callback is the same).  `.catch` should never only handle one layer of Promise.  What you're showing here certainly should work. It is possible though that some of the intricacies about how async functions are handled in `graphql-js` (or perhaps the way we instrument execution for field observability) messes this up though.

Can you provide a complete reproduction recipe (ie, something starting with `git clone` or using codesandbox.io or something) that lets me see exactly what you're talking about with no creativity required? For example it's really important that you and I be running exactly the same version of `graphql`.

**Comment by glasser** [comment]
I'm going to close this but am happy to reopen with a self-contained reproduction.
