### ISSUE TITLE
Express error handling middleware not invoked

### ISSUE THREAD

**Issue by paymog** [apollographql/apollo-server#6946]
I'm using pino to add an error handler to the instance of express I'm using with apollo server. I have the pino logger working well throughout the app however I'm finding that my express error handler is never invoked. I have the error handler for express set up like so:

```
const errorHandler: ErrorRequestHandler = (err, req, res, next) => {
  // logic
  req.log.error(err)
  next(err)
}
```

and I invoke use it like so: `app.use(errorHandler)`.

However, whenever an error happens in my application, only the `formatError` function of the ApolloServer gets called.

How can I configure apollo to propagate errors to the express error handler? Alternatively, when formatting the error, how can I get access to the express request or the apollo context so which will have the request logger?

I'm trying to correlate errors with specific requests in my app and the standard formatError function doesn't provide a logging instance specific to the request in which the error happened. For example:

```
[11:44:24.985] INFO:
    reqId: "cl8hmriix0005amp2cgj77pzc"
    guides: [
      {
        "_id": "cdmx",
        "count": 12
      },
      {
        "_id": "roatan",
        "count": 10
      }
    ]
[11:44:24.998] ERROR: not implemented
    err: {
      "type": "Error",
      "message": "not implemented",
      "stack":
          Error: not implemented
              at Object.userSubmissions (file:///Users/paymahn/code/lookieloo/backend/src/api/submissions/graphql/queries.js:178:11)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
    }
```

Notice how in the first log line there's a field called `reqId` but that doesn't exist in the error log. This is because the request specific logger isn't available during `formatError`. This logger exists on the `req.log` Express Request object and I've also added it to the `context` object in apollo. 

My custom express request handler would solve my needs but it seems apollo won't propagate errors to it. How can I either get errors in the custom express error handler or get the express request (or apollo context) in the formatError function?

**Comment by glasser** [comment]
I think you're probably looking for the didEncounterErrors plugin API, which does have access to your context value. See eg this recent discussion. https://github.com/apollographql/apollo-server/pull/6918#issuecomment-1251496189
