### ISSUE TITLE
Unexpected errors during usage reporting

### ISSUE THREAD

**Issue by nskarakoc** [apollographql/apollo-server#6958]
Hello,

We have an Apollo server v3.1.1 running in AWS Lambda behind an API Gateway. We are using [Serverless Framework](https://serverless.com). We provided the graph API key and the graph ref to Apollo Server so that we expect [usage reporting plugin is enabled by default](https://www.apollographql.com/docs/apollo-server/api/plugin/usage-reporting/#default-installation). Usage reporting to Apollo Studio works fine mostly but we get two different errors in some rare cases.

Here is the first error:

```
Error sending report to Apollo servers: HTTP status 408, 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>408 Request Timeout</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Request Timeout</h1>
<h2>Your client has taken too long to issue its request.</h2>
<h2></h2>
</body></html>
```

Here is the second one:

```
Error sending report to Apollo servers: request to https://usage-reporting.api.apollographql.com/api/ingress/traces failed, reason: socket hang up
```

The expected behavior is no errors logged. We saw that there is a possibility to increase [max attempts during usage reporting](https://www.apollographql.com/docs/apollo-server/api/plugin/usage-reporting/#maxattempts), but we are not sure if it's the right way to fix the issue since that means we have already been trying for 5 times which is default value for this option.

**Comment by glasser** [comment]
It sounds like there may have been a brief outage either in our usage report ingestion servers or in your network. While we certainly try to avoid outages, it is possible that they occur from time to time. The important part is that an outage in our usage reporting ingress (or a network issue in between) shouldn't impact the behavior of your GraphQL server. If you saw an impact on your server's behavior (or if these errors happen constantly rather than rarely) I'd be happy to look into that further; otherwise, I'm not sure there's much we can do here.

**Comment by delisdeli** [comment]
Hey @glasser thanks for taking a look!

@nskarakoc and I are getting these 408s pretty much every day. It's unclear to me what the side effects are but I am worried we may be losing request traces in Apollo Studio which is the main motivation for creating this issue.

Any chance you can take a deeper look?

**Comment by bpuckhaber** [comment]
Hi @nskarakoc and @delisdeli! Thank you for raising this issue.

We can see there this is a very small percentage of request traces yielding a 408 response code (average of 0.0004% out of several million per hour). While the number of errors is small, a monitor has been added internally which will alert us if these errors increase significantly. A ticket has also been created internally to track and revisit this issue further as needed.

Thank you again for reaching out. If you have any other information or questions on the issue please don’t hesitate to ask. Cheers!
