### ISSUE TITLE
Server doesn't correctly expose gateway defer directives

### ISSUE THREAD

**Issue by paulpdaniels** [apollographql/apollo-server#6966]
Configuring an apollo-server-express instance using the latest package versions of both `gateway` and `apollo-server`. I would expect that the server (which derives it's schema from the underlying gateway) to automatically allow clients to pass in `@defer` enabled requests, since there appears to be support within the gateway for `@defer` (I realize this is seemingly unpublicized behavior so maybe I'm getting ahead of the horse here).

Schema 1
```graphql
type User @key(fields: "id") {
  id: ID!
}

type Query {
  viewer: User
}
```

Schema 2
```graphql
type Query {
  group(id: ID!): Group
}

type User @key(fields: "id") {
  id: ID!
  groups: [Group!]!
}

type Group {
  id
  controls: [Control!]!
}

type Control {
  id: ID!
  label: String!
}
```

Ran `rover supergraph compose --config ./supergraph-config.yaml > supergraph.graphql`

With schema 1 and schema 2 as inputs within supergraph-config.yaml

```typescript
  const supergraphSdl = readFileSync(
    path.resolve(__dirname, '/supergraph.graphql')
  ).toString()

export const gateway = new ApolloGateway({
  supergraphSdl, 
  queryPlannerConfig: {incrementalDelivery: {enableDefer: true}}
})

const server = new ApolloServer({gateway, apollo})
```

Instead queries to the server that include a `@defer` block e.g.

```graphql
query {
  viewer {
    id
    groups {
       ... @defer { id, controls { label } }
    }
  }
}
```

Expected: Processes the query normally (internally deferring calls to the entities)

Actual: results in `"message": "Unknown directive \"@defer\".",`

**Comment by glasser** [comment]
Apollo Server will have experimental support `@defer` in the forthcoming (currently Release Candidate) v4, when combined with a prerelease of `graphql@17`. However, we don't plan to have any support for `@defer` in Apollo Gateway. [Apollo Router](https://www.apollographql.com/docs/router/executing-operations/defer-support/) does have (preview) support for `@defer`; I'd recommend migrating from Gateway to Router.

**Comment by glasser** [comment]
(I am curious where you're getting "since there appears to be support within the gateway for `@defer`" from — perhaps there are some docs we can improve.)

**Comment by paulpdaniels** [comment]
@glasser for one I see the option above `{incrementalDelivery: {enableDefer: true}}` available in the `gateway` in the latest version (2.1.3), and there are merged PRs referencing `@defer` in the gateway repo:

https://github.com/apollographql/federation/pull/1958/files
https://github.com/apollographql/federation/pull/2121
https://github.com/apollographql/federation/pull/2143

> [Apollo Router](https://www.apollographql.com/docs/router/executing-operations/defer-support/) does have (preview) support for @defer; I'd recommend migrating from Gateway to Router.

Does this mean that `gateway` is going to stop getting new feature support soon? We won't be able to migrate anytime soon because we need support for graphql-uploads as well which router doesn't seem to have yet.

**Comment by glasser** [comment]
The TypeScript query planner in that repo is shared by both Gateway and Router; this feature is used by Router but not Gateway.

I'm not the best person to update about the exact plans for the future of Gateway, but I personally believe (and it's [Apollo's current best practice advice](https://www.apollographql.com/blog/backend/file-uploads/file-upload-best-practices/)) that file uploads are a bad fit for a GraphQL API and are best implemented elsewhere. (And that was even before we discovered that including `graphql-upload` in your app made it very likely that you'd be vulnerable to CSRF attacks, a fact [the maintainer still hasn't added to the spec](https://github.com/jaydenseric/graphql-multipart-request-spec/pull/64).)
