### ISSUE TITLE
Apollo Server 4 Release Process

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#7014]
We are in the process of releasing Apollo Server 4!

Full details about AS4 can be found at [the docs](https://www.apollographql.com/docs/apollo-server/v4/) including [the migration guide](https://www.apollographql.com/docs/apollo-server/v4/migration/)

The release process includes:

- [x] Publish `@apollo/server` and other new packages as non-prereleases.
- [x] Update contents of docs to no longer say "release candidate" (and link to the right CHANGELOG.md in the sidebar) @maryelizbeth
- [x] Update federation (v1 and 2) and studio doc sets to show v4 as the example @rkoron007 
  - [x] After GA, we can merge this [Federation PR](https://github.com/apollographql/federation/pull/2186)
  - [x] After GA, we can merge this [Studio PR](https://github.com/apollographql/docs/pull/244)
- [x] Update Apollo-internal servers to final release @glasser 
- [x] Update rover templates to final release @glasser 
- [x] Update dev deps of `@apollo/datasource-rest` to final release @trevor-scheer 
- [x] Get as many of the integrations updated to final release as possible @trevor-scheer 
- [x] Merge `version-4` to main, create `version-3` branch
- [x] Enable renovate on new main, drop v3-specific code
- [x] Ensure changeset workflow runs on `main`
- [x] Unblock TypeScript updates in renovate config
- [x] Make new GitHub PR checks required
- [x] Make v4 the default docs when you go to https://www.apollographql.com/docs/apollo-server
- [x] Finalize and publish support policy for AS2 and AS3 @maryelizbeth
- [x] Close/move old issues and PRs
- [x] Mark old packages as deprecated on npm
- [x] Blog post and other announcements @maryelizbeth

**Comment by hwillson** [comment]
👋 @glasser - are we okay to close?
