### ISSUE TITLE
Add NO_INTROSPECTION to ApolloServerErrorCode and set the code when throwing

### ISSUE THREAD

**Issue by barryhagan** [apollographql/apollo-server#7033]
When introspection is disabled, a `ValidationRule` is added that will throw a `GraphQLError` if an introspection request is received.   If you are logging server errors, there can be a lot of noise if someone is attempting to introspect your production servers.  To date, we have needed to filter these errors by string matching on the error message, which is not great.

Apollo Server v4 introduced the `ApolloServerErrorCode` enum.  It would be nice to see `NO_INTROSPECTION` added to this enum and then used as the error.extensions.code when you throw the `NoIntrospection` validation rule here: 
https://github.com/apollographql/apollo-server/blob/main/packages/server/src/ApolloServer.ts#L77

Perhaps add a concrete NoIntrospectionError to internalErrorClasses as well, although that doesn't help someone who would like to use an exported type to check 
```ts
if (error instanceof NoIntrospectionError)
```

**Comment by glasser** [comment]
That's a nice idea! Would you like to send a PR?

We explicitly don't want instanceof checks — we found that ran into too many problems when npm installed multiple copies of a library.

The only downside is that in theory graphql-js [might implement this natively](https://github.com/graphql/graphql-js/issues/2247) and it might in that case be hard to detect the error.

**Comment by trevor-scheer** [comment]
Fixed via #70355
