### ISSUE TITLE
Allow context functions that directly return the context (and not a promise)

### ISSUE THREAD

**Issue by tobiasdiez** [apollographql/apollo-server#7040]
Currently, the function that constructs the context has to return a promise:
https://github.com/apollographql/apollo-server/blob/256aa937c8a7925f39b20729571c3f3a8780f055/packages/server/src/externalTypes/context.ts#L8-L11

But sometimes generating the context from the request can be done synchronously, and in this it would make sense to allow ` Promise<TContext> | TContext` as return type.

**Comment by trevor-scheer** [comment]
Hey @tobiasdiez, for API simplicity we've intentionally moved away from the `PromiseOrValue` pattern that was sprinkled throughout the server repo. JS users can still return a value (since the function call is `await`ed) and TS users can simply add `async` to their function call.

**Comment by glasser** [comment]
Additionally, the context function is only called by particular particular web framework integrations such as the Express and Standalone integrations. If this issue is a burden for you, you're welcome to ignore these integrations and use the ApolloServer API directly, which could include a non-async context function.

**Comment by glasser** [comment]
To me I find `T | Promise<T>` (where T is an arbitrary type) to be a challenging type to reason about... it basically means "anything at all, or a thing with a `then` that returns anything at all". But why wouldn't a Promise itself qualify as "anything at all" itself?

I'd feel better about this if this concept was built into TypeScript but [the relevant issue](https://github.com/microsoft/TypeScript/issues/31394) has been open for years.

**Comment by tobiasdiez** [comment]
> But why wouldn't a Promise itself qualify as "anything at all" itself?

because it only covers the "a thing with a then"-part?

From a users perspective, which option would you prefer?
```ts
function createContext(req): Promise<MyContext> {
    return Promise.resolve({
        getUser: req => req.user
    })
} 

function createContext(req): MyContext {
     return {
        getUser: req => req.user
    }
}
```

**Comment by glasser** [comment]
Neither:

```
async function createContext(req): Promise<MyContext> {
     return {
        getUser: req => req.user
    }
}
```

**Comment by tobiasdiez** [comment]
...which is against the recommended eslint rule https://typescript-eslint.io/rules/require-await/

**Comment by glasser** [comment]
For what it's worth, we've had this discussion a few times before. (Which certainly may be a sign that we're wrong!) See for example https://github.com/apollographql/apollo-server/pull/6973

I do think that in the specific case of `T = void`, `Promise<void>` makes a lot more sense than `void | Promise<void>` for the reason I mentioned in that thread.  So even if we changed the non-`void` hooks to allow for synchronous return, you'd still need to disable the `require-await` rule.

**Comment by tobiasdiez** [comment]
The case `T = void` makes more sense in the context of listeners, and not for context generators, right?
For what's worth, I've commented on the issue with a solution that handles "async or sync, but no return value" quite well.
