### ISSUE TITLE
Community contribution: server integration for h3 / nuxt

### ISSUE THREAD

**Issue by tobiasdiez** [apollographql/apollo-server#7041]
At https://github.com/JabRef/JabRefOnline/blob/main/apollo/apollo-server.ts you can find an apollo-server v4 integration for https://github.com/unjs/h3 (and thus for https://v3.nuxtjs.org ). I would like to publish this as part of the https://github.com/apollo-server-integrations organization if you like.

Do you prefer that I first create a repo which is then transferred into this organization, or is it easier if you create the repo yourself and then give me writing rights? In the latter case, please use https://github.com/unjs/template as the template.

**Comment by trevor-scheer** [comment]
Great! I've invited you to the org and under the h3 team (should it be named nuxt? I'm not sure what the distinction is). You should have rights to transfer or create a new repo, but if not just let me know. Are you interested in publishing under the `@as-integration` npm scope as well? If so I'll need your npm handle.

**Comment by tobiasdiez** [comment]
Thanks a lot @trevor-scheer! I've now created a repo and it seems to work so far. The only failing integration test seems to be https://github.com/apollo-server-integrations/apollo-server-integration-h3/issues/1. I would appreciate if you could have a look at this issue. Thanks!
Once this is fixed, I indeed would like to publish it under the `@as-integration` scope. Could you please give me the necessary rights: `tobiasdiez`.

---

@pi0 @danielroe @lewebsimple @newbeea Just pinging you to show that this is going on. If you would like to help maintaining, please raise your hand and I'm sure @trevor-scheer will invite you to the h3 team as well.

**Comment by danielroe** [comment]
Yes please 🙏
