### ISSUE TITLE
Studio Sanbox show inline traces not working with Apollo Server v4

### ISSUE THREAD

**Issue by vieira** [apollographql/apollo-server#7063]
When using the Apollo Studio Sanbox landing page in Apollo Server v4.0.1, the setting "Show inline traces" is not working as expected, even tough the `ApolloServerPluginInlineTrace()` is present in the plugins array.

By looking into the `request.http.headers` I see that enabling the toggle does not send the `apollo-federation-include-trace: ftv1` header nor any other header compared with the toggle disabled.

Adding the header manually to the request I see that the response now includes an `extensions.ftv1` string, but the "Traces" dropdown option only shows the message: "Please rerun your operation to get traces".

![Screen Shot 2022-10-20 at 17 34 03](https://user-images.githubusercontent.com/207460/197007155-8a9f44aa-e8ac-4e3b-9e51-8870d57afd24.png)

![Screen Shot 2022-10-20 at 17 34 24](https://user-images.githubusercontent.com/207460/197007178-d2bbb7a2-c400-4f1c-9932-cf1ee42b7f45.png)

**Comment by mayakoneval** [comment]
Hello! Thank you for raising this issue. A fix has been deployed. If you click on the megaphone in the top right & click on the 'update' button at the bottom left of the modal that opens, this should be working for you now. 

Please let us know if you see any other issues.

**Comment by vieira** [comment]
Can confirm it is now working. Thanks a lot. 🙏
