### ISSUE TITLE
[Discussion] Should we switch to versioning packages independently?

### ISSUE THREAD

**Issue by martijnwalraven** [apollographql/apollo-server#709]
We currently version all packages in this monorepo together. A downside of that is that a breaking change to one of the packages, as [recently happened with`apollo-server-hapi`](https://github.com/apollographql/apollo-server/issues/707), would require a major version bump for all packages.

Not only is it confusing to see a package like `apollo-server-express` receive a major version bump without any new features or changes in behavior, it also means users of `apollo-server-express` won't receive any bug fixes unless they manually update their dependency.

A downside of independently versioning packages however, is that there is no shared notion of a version of Apollo Server anymore, which makes documentation and finding answers to questions a lot harder. One person could be using `apollo-server-hapi` v4.5.3 and another `apollo-server-express` v2.3.7, and users would have to manually check the version of `apollo-server-core` they had installed to realize they were running most of the same code.

An alternative might be to have people install  `apollo-server-core` and one of the server-specific packages explicitly, but that would be a breaking change in itself and is a little bit more work. I do feel that would be the cleanest solution long term however. 

What do people think?

**Comment by VladShcherbin** [comment]
Yeah, this will be great. Currently, when you have a version bump and come to see what has changed, you can find out that changes are only for another package. Very confusing 🤔

**Comment by abernix** [comment]
We'll need to address this prior to #800. (Just creating a trail here.)

**Comment by abernix** [comment]
This has been completed and Apollo Server packages now utilize their own, “independent” versioning.
