### ISSUE TITLE
400 error when using fragments?

### ISSUE THREAD

**Issue by Nickersoft** [apollographql/apollo-server#710]
Hi guys,

I'm using this library with Express, and have been importing fragments into certain queries (client-side) using the following approach:

```graphql
import gql from 'graphql-tag';
import { MyFragment } from 'fragments';

export default gql`
    query MyQuery($var1: String!, $var2: String!) {
        myQuery(var1: $var1, var2: $var2) {
            myField {
                ...MyFragment
            }
        }
        
        ${MyFragment}
    }
`;
```

Yet, running this query throws a 400 error message on my server, with no stack trace, no error message, nothing. I noticed on the [express-graphql repo](https://github.com/graphql/express-graphql) it says under the HTTP usage options:

> __operationName:__ If the provided query contains multiple named operations, this specifies which operation should be executed. If not provided, a 400 error will be returned if the query contains multiple named operations.

which would seem to imply the error is being thrown because a fragment is included in the query in addition to the query that needs to be run? Is that the same issue that is happening here? It only happens with queries that utilize imported fragments.

**Comment by martijnwalraven** [comment]
No, you only need to include `operationName` if your document includes multiple operations, which are queries and mutations (and subscriptions). Fragments are not operations.

So I suspect there is something else going on. Could you add `debug: true` to your server options?

**Comment by Nickersoft** [comment]
Hey @martijnwalraven, thanks for the quick response. Yeah, that's what I suspected.. I was just making sure. This is my current setup for Apollo server:

```javascript
app.use(
        '/v1',
        jwt({
            secret: config.secret, // <-- uses global config defined elsewhere
            credentialsRequired: false
        }),
        graphqlExpress(req => {
            return {
                schema, // <-- schema object generated with makeExecutableSchema()
                context: {
                    authToken: req.user || {}
                },
                debug: true, 
                tracing: true,
                rootValue: null
            };
        }
    )
);
 ```

Surprisingly, the `debug` and `tracing` options output _absolutely nothing_. I'm using [morgan](https://npmjs.com/package/morgan) for middleware logging, and all it ever produces is this (with the logger setting set to 'dev'):

```bash
POST /v1 400 10.668 ms - -
```

Client-side, the only error I get is:

```
Network response not successful: Received status code 400
```

I couldn't get any error middleware for Express to output anything, using the `function(err, req, res)` method signature, regardless of where I inserted the middleware. The only thing I could do was compare the response objects for a healthy request (200) and my 400 request. The only non-unique properties I could find that was different was the transfer encoding, where the encoding on the failed request was "chunked", not that it matters all that much. I'm really at a loss here. If I could somehow get a stack trace at the time of the error it might be solvable. Checking the code here it seems that 400 errors are only thrown a handful of times, every time with additional information to help the debug process. I have nothing. 

All I know is that with the omission of fragments in my client-side request, the code works (well, it breaks because it's missing the required fragment.. but at least there isn't a 400 error). I've put console log statements in my resolver for this query as well, and it is never executed. So the error is being thrown before resolution. Any further insight would be great. I'd try reproducing the error and posting it here, though I'm not sure what would be the best way to.

**Comment by Nickersoft** [comment]
Well, seems it was just a matter of my own stupidity. I inserted some console log statements to the apollo-server dependency and was able to hunt down the cause of the 400 error. Had to do with some of my own server-specific stuff that was failing. Weird it never printed anything to the console when it actually errored. Anyway, closing this because for now.
