### ISSUE TITLE
Property 'toJSON' does not exist on type 'GraphQLError'

### ISSUE THREAD

**Issue by gaurav-bothra** [apollographql/apollo-server#7110]
# Description
Hey, I was trying to throw [Custom GraphQLError](https://www.apollographql.com/docs/apollo-server/data/errors/#custom-errors)  as described in Apollo Server Documentation. 

```
// ts code
 export const throwError = (error) => {
  const language = getValueFromNS('lang');
  const errorMessage =
    ErrorResponse[ErrorCode[error.message]] || ErrorResponse['DEFAULT'];
  logging(errorMessage[`${language}_message`], {}, LogLevel.ERROR);
  throw new GraphQLError(
    errorMessage[`${language}_message`],
    undefined,
    undefined,
    undefined,
    undefined,
    error,
    { exception: { code: '400' } }
  );
};
```

But I am getting unexpected error response. 

# Apollo Server Console Error

> Unexpected error processing request: TypeError: graphqlError.toJSON is not a function
TypeError: graphqlError.toJSON is not a function
node_modules/@apollo/server/src/errorNormalize.ts:84:30

# Apollo Studio Error Response
```
{
  "data": {},
  "error": {
    "message": "Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON",
    "stack": "SyntaxError: Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON"
  }
}
```

# Version
I am using @apollo/server 4.0.5

**Comment by glasser** [comment]
What version of `graphql` is installed in your app?

**Comment by gaurav-bothra** [comment]
@glasser graphql version is 15.8.0

**Comment by gaurav-bothra** [comment]
Thanks @glasser - Issue is fixed.
