### ISSUE TITLE
Migrating from Apollo server V2 to V3, Landing page is not showing

### ISSUE THREAD

**Issue by saiteja9177** [apollographql/apollo-server#7120]
I am trying to migrate from Apollo Sever v2 to v3, I imported required plugins but still I am not able to see sandbox page.
Attaching code for reference
`const { ApolloServer, AuthenticationError } = require('apollo-server-express');
const responseCachePlugin = require('apollo-server-plugin-response-cache');
const {
ApolloServerPluginLandingPageProductionDefault, ApolloServerPluginLandingPageLocalDefault } = require('apollo-server-core');
/Apollo Server Initialization/
const apolloServer = new ApolloServer({

typeDefs: [

],

resolvers: [

],
cacheControl: {
defaultMaxAge: CACHE_DEFAULT_MAX_AGE
},
plugins: [responseCachePlugin.default(),
ApolloServerPluginLandingPageLocalDefault({ footer: false })],

dataSources: () => ({

}),`

**Comment by trevor-scheer** [comment]
Hey @saiteja9177, it's hard to diagnose the problem you're running into with just a code snippet. Can you provide us with a runnable reproduction like a CodeSandbox or something we can git clone and run locally?

Also, Apollo Server v4 is out. It's not a bad practice to migrate v2->v3->v4 if that's what you're doing, but I just wanted to make you aware and recommend that try to end up there if it's an option for you.

I'm going to close this for now, but I'm happy to reopen with a reproduction.

**Comment by glasser** [comment]
It would also be helpful to understand what you *are* seeing and at what URL you were looking.

**Comment by saiteja9177** [comment]
I can't provide the link for clone what I am trying to do is while migrating from V2 to V3 I am trying to replace playground with sandbox as per the document if we don't add any plugins for landing page based on the env it should show the landing page, but in my case I tried with providing landing page plugins and without in both cases the landing page is not loading.

getting landing screen as Welcome to Apollo Server
The full landing page cannot be loaded; it appears that you might be offline.
