### ISSUE TITLE
Can't add req to context

### ISSUE THREAD

**Issue by dudo** [apollographql/apollo-server#7131]
Not sure if this is a bug, or if I just have something misconfigured, but I can't seem to get a handle on the `req` object while trying to modify `context`.

Asked [here](https://stackoverflow.com/questions/74341767/forward-request-headers-apollo-federated-gateway). 

Any help is appreciated!

**Comment by trevor-scheer** [comment]
Hey, admittedly the docs for this aren't the most discoverable, but have you gone over this section to check your configuration? This section was written for exactly your use case.
https://www.apollographql.com/docs/federation/building-supergraphs/router#customizing-requests-and-responses

For starters, your section with the comment `// TRYING TO INJECT AUTH HEADERS HERE` should be adding headers but I don't see any code for that. Stripped right from the example in the docs I linked, I'd expect something like:
`request.http.headers.set('user-id', context.userId)`

**Comment by dudo** [comment]
Hey @trevor-scheer! The header injection is working, but the problem is there's nothing to add to the context. `req` is null when configuring the server.

```js
context: ({ req }) => {
  console.log(JSON.stringify(req));
  // req IS NULL
},
```

**Comment by trevor-scheer** [comment]
@dudo that's pretty surprising. It's not immediately obvious to me why that'd be the case just by looking at the snippet. Any chance you could share a minimal reproduction (codesandbox or clonable git repo)?

FWIW I doubt there's a bug here...probably just something misconfigured as you've supposed (which I'm having trouble spotting).
What's logged if you just:
```
context: (reqContext) => {
  console.log(JSON.stringify(reqContext, null, 2));
  return {};
},
```

**Comment by glasser** [comment]
You say you're using Apollo Server v4 (`@apollo/server`) right?

In Apollo Server 4 we moved the `context` function from the `ApolloServer` constructor to the framework-specific connector such as `expressMiddleware`: in AS4, `ApolloServer` has an API that isn't specific to a framework, and the argument to the context function is framework-specific, so separating this out makes sense.

See https://www.apollographql.com/docs/apollo-server/migration/#context-initialization-function for details.

I recommend using TypeScript which would make this error (providing `context` to the wrong function) clear.

**Comment by dudo** [comment]
That did the trick! Thank you, @glasser.
