### ISSUE TITLE
Neo4j driver is not working with any queries

### ISSUE THREAD

**Issue by yaakovyitzchak** [apollographql/apollo-server#7139]
B"H
BH trying to follow this tutorial https://neo4j.com/developer/graphql/ but when I enter the exact query they say to with the exact same nodejs code I get the following error [![enter image description here](https://i.stack.imgur.com/l212C.jpg)](https://i.stack.imgur.com/l212C.jpg) Essentially "expression in call return must be aliased"? Here is the graphql query I made based off of the tutorial, same exact structure:

```
mutation {
  createMovies(
    input: [
      {
        title: "Awtsmoos"
        actors: {
          create: [
            {
              node: {
                name: "Zalman"
              }
            }
          ]
        }
      }
    ]
  ) {
    movies {
      title
      actors {
        name
      }
    }
  }
}


```

And here is the error I get:

```
{
  "errors": [
    {
      "message": "Expression in CALL { RETURN ... } must be aliased (use AS) (line 17, column 16 (offset: 580))\n\"        RETURN collect(NULL)\"\n                ^",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createMovies"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": "Neo.ClientError.Statement.SyntaxError",
          "name": "Neo4jError",
          "retriable": false
        }
      }
    }
  ],
  "data": null
}


```

Here is the nodejs when the credentials removed

```
//B"H
const { gql, ApolloServer } = require("apollo-server"); 
const { Neo4jGraphQL } = require("@neo4j/graphql"); 

const neo4j = require("neo4j-driver"); 

const typeDefs = gql`
  type Movie {
    title: String!
    year: Int
    plot: String
    actors: [Person!]! @relationship(type: "ACTED_IN", direction: IN)
  }
  type Person {
    name: String!
    movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
  }
`;

const driver = neo4j.driver(
  "neo4j+s://myid.databases.neo4j.io",
        neo4j.auth.basic(
                "neo4j",
                "mypassword"
        )
);

const neoSchema = new Neo4jGraphQL({ typeDefs, driver });

neoSchema.getSchema().then((schema) => {
    const server = new ApolloServer({
        schema: schema,
       introspection: true, 
       playground: true
    });

    server.listen({port: process. env.PORT}).then(({ url }) => {
        console.log(`GraphQL server ready on ${url}`);
    });
});
```

Here is my package.json 
```





{
  "name": "hi",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start":"node index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@neo4j/graphql": "^3.12.0",
    "apollo-server": "^3.11.1",
    "graphql": "^16.6.0",
    "neo4j-driver": "^5.2.0"
  }
}
```

I've tried multiple neo4j servers. I have only been able to run nodejs using heroku, and localhost on debian. Tried testing it with a google cloud VM instance but wasn't able to get an https server up.

**Comment by trevor-scheer** [comment]
We really can't offer much help here. This doesn't appear to be a problem with Apollo Server.

The error you're seeing here is related to Neo4j:
`"message": "Expression in CALL { RETURN ... } must be aliased (use AS) (line 17, column 16 (offset: 580))\n\"        RETURN collect(NULL)\"\n                ^"`
The path:
```
"path": [
        "createMovies"
      ],
```
...suggests to me that there's an error happening in your `createMovies` resolver.

And hopefully there's a useful clue for you here in the error extensions:
```
"exception": {
          "code": "Neo.ClientError.Statement.SyntaxError",
          "name": "Neo4jError",
          "retriable": false
        }
```

If you still think this is an Apollo Server bug please provide a minimal reproduction demonstrating the problem you're seeing (ideally one that doesn't include usage of Neo4j unless they somehow aren't playing nice and it's a bug in our code).
