### ISSUE TITLE
"sampleResolver" defined in resolvers, but not in schema

### ISSUE THREAD

**Issue by saiteja9177** [apollographql/apollo-server#7140]
I modularized the schemas and resolvers in application. Now I want add Custom scalars schema

for eg:  sampleResolver.js
```ts
const sampleResolver = {
 Query: {
        async customer(_, {ID}) {
           return await Customer.findById(ID);
        },
        async getCustomers(_, {number}) {
            return await Customer.find().sort({ createdAt: -1}).limit(number)
        }

    }
}

module.exports = {sampleResolver}
```

and in my apollo serverIntialization:

```ts
const apolloServer = new ApolloServer({
    typeDefs: typedefs,
    resolvers: [
     sampleResolver
    ]
)}
```

I didn't get the "sampleResolver" defined in resolvers, but not in schema error with the above syntax.

Now since I am adding custom scalars I am defining resolvers outside initialization and using. Please refer below

```ts
const resolvers = {
  Date: dateScalar,
  sampleResolver
}
```
and using this const in intialization
```ts
const apolloServer = new ApolloServer({
    typeDefs: typedefs,
    resolvers
)}
```
with this syntax I am facing this issue

**Comment by trevor-scheer** [comment]
I think you mean to merge `sampleResolver` into your `resolvers` object via spread like so:

```ts
const resolvers = {
  Date: dateScalar,
  ...sampleResolver,
};
```

If that doesn't resolve your issue, I'll need more information to be helpful. If you have a codesandbox or a github repo I can clone that would be preferable.
