### ISSUE TITLE
Inline trace not getting disabled

### ISSUE THREAD

**Issue by maila-labib** [apollographql/apollo-server#7155]
Hi Team, 

I have disabled inline trace in apollo server by using ApolloServerPluginInlineTraceDisabled() as mentioned in this [document](https://www.apollographql.com/docs/apollo-server/v3/api/plugin/inline-trace). 

Following is the code snippet : 

`const server = new ApolloServer({
  context: getContext,
  gateway,
  plugins: [
    enableTracing
      ? ApolloServerPluginInlineTrace()
      : ApolloServerPluginInlineTraceDisabled(),
  ],
  healthCheckPath: "/ping",
  subscriptions: false,
  introspection: enableIntrospection
});`

However, the traces are still visible in Apollo studio as in following image : 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/101619204/202388849-3dfc1451-a6db-464d-9cc0-4ca001faffc0.png">

The apollo-server version being used here is - "apollo-server": "^3.6.7"

The same was working fine( inline traces were disabled ) for few days but now the traces are not disabled even when there is no change done since the last time it was working. 

Following is the image when it was working fine : 

<img width="1709" alt="image" src="https://user-images.githubusercontent.com/101619204/202390069-fc576e5a-2753-4c7e-ad75-466f31407e6c.png">

Please help me understand why the traces are not getting disabled even when the ApolloServerPluginInlineTraceDisabled() has been set. Also to keep you informed, we are not sending the header `apollo-federation-include-trace: ftv1`. 

Please find the code sample here - https://codesandbox.io/s/weathered-sun-95hixd?file=/index.js

**Comment by glasser** [comment]
The inline trace plugin controls whether traces are included directly inside GraphQL responses (when requested via a specific header). This is used primarily for communication between subgraphs and gateway/router in a supergraph.  (You can also enable it in a gateway or a monograph if you want to be able to see traces when you execute operation inside Explorer in Studio, but this isn't recommended in production.)

However, this doesn't control communication between Apollo Server and Apollo Studio. That's a separate mechanism that aggregates the descriptions of many operations and sends them out-of-band to Apollo Studio, and is controlled by the usage reporting plugin. You can control that in your gateway with ApolloServerPluginUsageReporting.

To turn off the collection of detailed per-field traces in your gateway, use `plugins: [ApolloServerPluginUsageReporting({ fieldLevelInstrumentation: 0 })]`. You'll still get usage reports describing what operations ran, but you won't get any traces (or information on how long individual fields took to execute).

**Comment by maila-labib** [comment]
@glasser... How was this disabled earlier then? If you see the two images attached above, the **Sample Trace** is empty in one while has details in another.

**Comment by glasser** [comment]
Apollo Server does not send traces for every operation (nor does Studio save every trace it receives: lots of sampling at all levels) so it's possible that this was just a coincidence? In any case, ApolloServerPluginInlineTraceDisabled is the default in the gateway.
