### ISSUE TITLE
If tracing is enabled, fieldResolver is not used

### ISSUE THREAD

**Issue by kamranayub** [apollographql/apollo-server#716]
Steps to reproduce:

1. Create a custom field resolver and pass to `fieldResolver`, log a message to indicate its hit
2. Enable `tracing: true`
3. Observe message is never logged

```js
const fieldResolver = (source, args, context, info) => {
  console.log("Hit field resolver")
  return null;
};

graphqlExpress({ schema, fieldResolver, tracing: true })
```

It would be helpful to be able to use our custom resolver alongside tracing.

**Comment by martijnwalraven** [comment]
Yes, you're right, that's currently a restriction of the way we trace resolvers. It would be great to figure out a way to respect custom field resolvers.

**Comment by kamranayub** [comment]
Do you know where I'd look if I wanted to maybe fix this? The Apollo
tracing package?

**Comment by martijnwalraven** [comment]
@kamranayub The code is in `graphql-extensions`, there is [a TODO comment about it at the point where this would need to be fixed](https://github.com/apollographql/graphql-extensions/blob/98f12f5ba1848ca1ce8199a9167b3572cd9b4056/src/index.ts#L152).

**Comment by kamranayub** [comment]
Okay thanks! I may look at that this weekend.

**Comment by kamranayub** [comment]
@martijnwalraven Thanks, I believe I tested it locally and it seems to work! I referenced the PR in graphql and saw they are using `context.fieldResolver`.

**Comment by JacksonKearl** [comment]
Looks like you were able to fix this!
