### ISSUE TITLE
How to serve graphQL api on custom port & path ?

### ISSUE THREAD

**Issue by fadhilsaheer** [apollographql/apollo-server#7176]
I'm using `@apollo/server:4.1.1` for a node js project.

How can I serve a graphql api on custom port & path ?

```typescript
import { startStandaloneServer } from '@apollo/server/standalone';

startStandaloneServer(server, {
  listen: { port: 5000, path: "/graphql" },
})
```

currently this code serves a graphql api at `localhost:5000` not `localhost:5000/graphql` specifically.

I was wondering If there is any way that I can resolve this issue ?

**Comment by trevor-scheer** [comment]
You'll need to switch to `expressMiddleware` if you'd like to customize your configuration at all.

https://www.apollographql.com/docs/apollo-server/api/standalone#swapping-to-expressmiddleware
