### ISSUE TITLE
End-to-end example from the official docs isn't working with graphql versions above 0.11.7

### ISSUE THREAD

**Issue by salhotra** [apollographql/apollo-server#718]
graphql versions 0.12.0, 0.12.1, 0.12.2, 0.12.3 have been released in the past two days since December 15. The End-to-end example on the official apollo site (link below) doesn't work with these versions. Having tried to run this example for some time, I figured it out. It works perfectly with graphql versions 0.11.7 and below. I have created a pull request adding a little note at the top in the docs/source/example.md file, stating "Note: Currently, this example works for graphql version 11.7.0 and earlier."
Until this is resolved, I think it would be really helpful to all the people who are trying to get up and running with apollo-server with this example and save them some time.
The link to the example: https://www.apollographql.com/docs/apollo-server/example.html

**Comment by salhotra** [comment]
This is the pull request in reference to the issue: 
https://github.com/apollographql/apollo-server/pull/719

**Comment by martijnwalraven** [comment]
I believe this has been fixed in 1.3.1.
