### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by ZaninAndrea** [apollographql/apollo-server#720]
The [end-to-end](https://www.apollographql.com/docs/apollo-server/example.html) example showed in the documentation doesn't work.

If I run any query I get this error
```json
{
  "errors": [
    {
      "message": "graphql_1.execute(...).then is not a function"
    }
  ]
}
```

STEPS TO REPRODUCE:
- follow the steps in the example (install module, run code)
- open graphiql
- run any query

POSSIBLE REASON
Implementing resolvers as promises solves the issue, but that's not a good solution, because I cannot reimplement the introspection query

**Comment by salhotra** [comment]
@ZaninAndrea You'd have to use graphql version 0.11.7 or earlier. Graphql released new version which is causing this issue

**Comment by ZaninAndrea** [comment]
Thanks a lot, maybe it's worth changing the install script in the example to
```
npm install --save apollo-server-express graphql-tools graphql@0.11.7 express body-parser
```

**Comment by salhotra** [comment]
Glad to help. BTW issue already open #718 :)

**Comment by martijnwalraven** [comment]
I believe this has been fixed in 1.3.1.

**Comment by jonaskello** [comment]
I get this exact problem with apollo-server-koa 1.3.2.

Getting all tools (server, client, codegen etc.) to agree on a singular version of the graphql package is necessary it has classes that are checked with instanceof. So it would be nice if more versions of the graphql package could be supported in apollo-server.

**Comment by jonaskello** [comment]
Upgraded graphql-tools to 2.16.0 and now it works :-).

**Comment by Mubashir-ali-baig** [comment]
Thanks salhotra, i was stuck for almost 4 hours on this problem
