### ISSUE TITLE
express-session doesn't work with expressMiddleware in apollo-server 4

### ISSUE THREAD

**Issue by JeremyBernier** [apollographql/apollo-server#7212]
[express-session](https://www.npmjs.com/package/express-session) does not seem to work with `expressMiddleware` in apollo-server v4. The `session` object is there, but the session state never updates. This worked in apollo-server v3, and does work with `startStandaloneServer `.

## Packages

```
    "@apollo/server": "^4.2.1",
    "body-parser": "^1.20.1",
    "cors": "^2.8.5",
    "express": "^4.18.2",
    "express-session": "^1.17.3",
    "graphql": "^16.6.0"
```

## Reproducible example

```
import { ApolloServer } from "@apollo/server";
import { expressMiddleware } from "@apollo/server/express4";
import { ApolloServerPluginDrainHttpServer } from "@apollo/server/plugin/drainHttpServer";
import express from "express";
import http from "http";
import cors from "cors";
import bodyParser from "body-parser";
import session from "express-session";

export const typeDefs = `
  type Query {
    hello: String
  }
`;

export const resolvers = {
  Query: {
    hello: (parent, args, context) => {
      const session = context.req.session;

      // session.views is always undefined, so this query always
      // returns 1

      if (session.views) {
        session.views++;
      } else {
        session.views = 1;
      }

      return session.views;
    },
  },
};

const sess = {
  secret: "keyboard cat",
  cookie: {},
};

interface MyContext {
  req?: any;
}

const init = async () => {
  const app = express();

  app.use(session(sess));

  const httpServer = http.createServer(app);

  const server = new ApolloServer<MyContext>({
    typeDefs,
    resolvers,
    plugins: [ApolloServerPluginDrainHttpServer({ httpServer })],
  });

  await server.start();

  app.use(
    "/graphql",
    cors<cors.CorsRequest>(),
    bodyParser.json(),
    expressMiddleware(server, {
      context: async ({ req }) => ({ req }),
    })
  );

  // here the session properly updates
  app.get("/test", (req, res) => {
    if (req.session.views) {
      req.session.views++;
    } else {
      req.session.views = 1;
    }
    res.end(`views ${req.session.views}`);
  });

  await new Promise<void>((resolve) =>
    httpServer.listen({ port: 4000 }, resolve)
  );
  console.log(`🚀 Server ready at http://localhost:4000/`);
};

init();
```

The GraphQL resolver is supposed to return 1, 2, 3, etc, but only returns 1.

The Express API route /test there correctly returns 1, 2, 3, etc.

**Comment by trevor-scheer** [comment]
This is likely a cookie issue. Your server should be responding with a `set-cookie: <your cookie value>` header in the response. If your graphql client doesn't send that cookie in subsequent responses, the session won't be preserved. You can see the browser is behaving correctly - just look at the request and response headers in the network tab.

**Comment by trevor-scheer** [comment]
You're probably using embedded sandbox, where cookies aren't included by default. You'll need to install the plugin manually so you can configure it to send cookies like so:

```ts
import { ApolloServerPluginLandingPageLocalDefault } from "@apollo/server/plugin/landingPage/default";

const server = new ApolloServer({
  // ...
  plugins: [
    ApolloServerPluginLandingPageLocalDefault({ includeCookies: true })
  ]
});
```

**Comment by jcubic** [comment]
Have the same problem, I've added my code into the discussion: [Sharing data with express-session](https://github.com/apollographql/apollo-server/discussions/7485). The problem is that cookies and sessions work currently only data is not persistent.

**Comment by jcubic** [comment]
I suggest to add this to documentation of `@apollo/server-plugin-landing-page-graphql-playground` not sure where this package is located the NPM package to monorepo but I'm not able to find this name in GitHub search (other then package.json dependencies).

I would add this to the README:
```javascript
import { ApolloServer } from '@apollo/server';
import { ApolloServerPluginLandingPageGraphQLPlayground } from '@apollo/server-plugin-landing-page-graphql-playground';

const server = new ApolloServer({
  plugins: [
    ApolloServerPluginLandingPageGraphQLPlayground({
      settings: {
        'request.credentials': 'include'
      }
    })
  ],
  /* other options */
});
```
with a note that this is needed when using sessions with the playground. So it's always using cookies.

**Comment by trevor-scheer** [comment]
@jcubic the playground plugin was published only for migration to v4 purposes, with the explicit intention of not maintaining it or documenting its usage going forward (which is why you can't find it in the repo anywhere).

**Comment by jcubic** [comment]
Ok I understand, but this is confusing and looks like express-session doesn't work if it's not documented that cookies don't work by default. It took me a few days to realize that browser didn't send cookies back to the server and a session was generated on each request.

But at least I hope that people will find this issue and solve their problem if they found a similar problem.

Maybe you can at least check if apolloClient is using a similar option by default. Right now I'm working on the backend so I'm not able to check.
