### ISSUE TITLE
[apollo-server-core] Optionally Skip Query Validation?

### ISSUE THREAD

**Issue by Piefayth** [apollographql/apollo-server#722]
We want to cache the results of parse & validate for queries sent to our service. On subsequent requests, we would like to avoid re-validating the cached parsed query. [This bit of code in `runQuery`](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/runQuery.ts#L155-L173) always runs all the default validation rules, leaving us unable to leverage it on subsequent requests without doing an unnecessary revalidation. The comment above that code snippet describes our desired behavior, but the implementation itself seems to not.

Is there a way to circumvent this? If not, is this something that can be added or adjusted? Happy to submit a PR if needed. Thanks.

**Comment by Piefayth** [comment]
Hi, hoping this can get some traction now that we're past the holiday. I noticed that [this comment](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/runQuery.ts#L64-L65), as well, indicates different behavior than what is actually happening. Again, just let me know what you'd like to see in a PR for this one and I'll get it together. Thank you.

**Comment by abernix** [comment]
This should be implemented by #2111.  Please do try it out!
