### ISSUE TITLE
Get from Database if redis is down

### ISSUE THREAD

**Issue by saiteja9177** [apollographql/apollo-server#7233]
I am using kevy package for wrapping of redis connectivity with Apollo Server3 . The problem I am facing here is if redis server is not reachable I am not getting any response from server, It should get data from Database if redis is down(since we are using for cache purpose only). Attaching sample code just like I am using in my current scenario.

const keyVInstance = new Keyv("redis://localhost:8000",{
    ttl: 1000*60*10
});
const keyVAdapter = new KeyvAdapter(keyVInstance);

/*Apollo Server Initialization*/
const apolloServer = new ApolloServer({

    typeDefs: [

    ],

    resolvers: [
       
    ],
  

    cache: keyVAdapter, 
    
    plugins: [responseCachePlugin(),
        ApolloServerPluginCacheControl({
            defaultMaxAge:CACHE_DEFAULT_MAX_AGE
          })],

   
    dataSources: () => ({
    }),

});

**Comment by saiteja9177** [comment]
Yes, I tried but no luck.

**Comment by glasser** [comment]
What you're describing is the goal of ErrorsAreMissesCache. If you'd like to share with us a complete reproduction recipe that enables us to see precisely what you tried with no creativity required on our part, we'd be happy to reopen this issue and look into it with you. Unfortunately, there isn't much we can do without that.
