### ISSUE TITLE
Apollo graphql with mongodb transaction

### ISSUE THREAD

**Issue by emon-gain** [apollographql/apollo-server#7245]
Is there any way to commit my transactions just before sending the response. Is it possible to do on root level? I do not want to do commit transaction everytime i am calling a resolver.

**Comment by glasser** [comment]
This sounds like a good use for a [`willSendResponse`](https://www.apollographql.com/docs/apollo-server/integrations/plugins-event-reference/#willsendresponse) or [`executionDidStart` end-handler](https://www.apollographql.com/docs/apollo-server/integrations/plugins-event-reference/#executiondidstart) plugin hook.
