### ISSUE TITLE
Apollo Sandbox Persist Information (E.g. Tabs Query) Regardless of the Port

### ISSUE THREAD

**Issue by MrDesjardins** [apollographql/apollo-server#7252]
### Issue Description

In the previous iteration of Apollo, the GraphQL playground (not the Sandbox) was saving the tabs (queries) per running instance. By that, I mean that you could develop several GraphQL servers locally using different ports, and each server (and playground) were isolated.

Since I migrated all servers to use the latest version of Apollo Server `("@apollo/server": "^4.2.2")`, when I open the playground, I see all tabs of all instances. It means that some saved queries do not make sense since they are for a specific server.

Note that it is beyond the visual. There is cross information like a preflight script that contains URL from other instances, causing some fetches to be performed on the wrong instance.

### Link to Reproduction

None

### Reproduction Steps

1) Create two Apollo servers with `ApolloServerPluginLandingPageLocalDefault`. One with port 8081 and one with 8082
2) Go to the playground with port 8081, write a query.
2) Go to the playground with port 8082, you will see the query from the server 8081

Also, open the Dev Console, and you will see the following: 
```
Access to fetch at 'http://localhost:8081/graphql' from origin 
'http://localhost:8082' has been blocked by CORS policy: 
Response to preflight request doesn't pass access control check: 
The value of the 'Access-Control-Allow-Origin' header in the response 
must not be the wildcard '*' when the request's credentials mode is 'include'.
```
That should not happen since 8082 shouldn't be even aware of 8081 instance.

**Comment by glasser** [comment]
I agree that this is surprising! I've passed this over to the Explorer/Sandbox folks to take a look.

**Comment by mayakoneval** [comment]
Hello, thanks so much for the report. I just merged a fix for some of the issues mentioned here. With this change, embedded Sandboxes moving forward will have state stored based on the document.referrer of the parent page. You should be able to have two workspaces on your different ports where you are spinning up Apollo Server instances, now. 

I have a pull request open to address the comment about making stale requests, and will update when that is out as well 🙏🏻

**Comment by mayakoneval** [comment]
Hello! The stale requests you are seeing on embedded Sandboxes should now be fixed if you update your studio version or reload all of your Sandbox instances. 

Please continue to let us know of unexpected behavior 🙏🏻

**Comment by trevor-scheer** [comment]
Thanks for reporting @MrDesjardins and for the fix @mayakoneval! Closing as completed, please follow up on the mentioned PRs (or here) if anything isn't working as expected.
