### ISSUE TITLE
Namespaced mutations throw unexpected error

### ISSUE THREAD

**Issue by okomarov** [apollographql/apollo-server#7263]
### Issue Description

The namespaced mutations described in Apollo's Tech note [Namespacing by separation of concerns](https://www.apollographql.com/docs/technotes/TN0012-namespacing-by-separation-of-concern/) throw  **unexpectedly** a

> "Cannot return null for non-nullable field Mutation.book"

where `book` is the type I am extending. Standard queries behave as expected.

### Link to Reproduction

https://codesandbox.io/s/apollo-server-namespaced-mutations-bug-t4hvnl?file=/src/index.ts

### Reproduction Steps

This example is taken from [here](https://codesandbox.io/s/apollo-server-namespaced-mutations-bug-t4hvnl?file=/src/index.ts) where I extend the [starter Apollo's example](https://www.apollographql.com/docs/apollo-server/getting-started/#complete-example) with a namespaced mutation:

```graphql
type Mutation {
  book: BookMutations!
}
  
type BookMutations {
  create(title: String!, author: String!): [Book!]!
}
```
and resolver:
```ts
BookMutations: {
    create: (_, { title, author }) => {
      books.push({ title, author });
      return books;
    }
  }
```

Then, a simple mutation to add a new book:
```graphql
mutation Mutation($title: String!, $author: String!) {
  book {
    create(title: $title, author: $author) {
      author
      title
    }
  }
}
```
**throws**:
```json
{
  "data": {},
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Mutation.book.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "book"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "Error: Cannot return null for non-nullable field Mutation.book.",
          "    at completeValue (/sandbox/node_modules/graphql/execution/execute.js:594:13)",
          "    at executeField (/sandbox/node_modules/graphql/execution/execute.js:489:19)",
          "    at /sandbox/node_modules/graphql/execution/execute.js:377:22",
          "    at promiseReduce (/sandbox/node_modules/graphql/jsutils/promiseReduce.js:23:9)",
          "    at executeFieldsSerially (/sandbox/node_modules/graphql/execution/execute.js:373:43)",
          "    at executeOperation (/sandbox/node_modules/graphql/execution/execute.js:347:14)",
          "    at execute (/sandbox/node_modules/graphql/execution/execute.js:136:20)",
          "    at executeIncrementally (file:///sandbox/node_modules/@apollo/server/dist/esm/incrementalDeliveryPolyfill.js:21:12)",
          "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
          "    at async execute (file:///sandbox/node_modules/@apollo/server/dist/esm/requestPipeline.js:220:37)"
        ]
      }
    }
  ]
}
```

**Comment by trevor-scheer** [comment]
You're missing a resolver for Mutation.book which is why it's returning null "unexpectedly".

**Comment by okomarov** [comment]
> You're missing a resolver for Mutation.book which is why it's returning null "unexpectedly".

Adding the passthrough resolver (updated the sandbox), as in https://graphql-rules.com/rules/mutation-namespaces:
```ts
  Mutation: {
    book: () => ({})
  },
  ```
keeps throwing the same error.
