### ISSUE TITLE
Apollo Server hangs during upload file with graphql-upload

### ISSUE THREAD

**Issue by NicoSan20** [apollographql/apollo-server#7280]
### Issue Description

Hello, I'm writing to you because I'm having issue when I'm using graphql-upload. Let me explain :

I have successfully implemented graphql-upload with the following documentation [Enabling file uploads in Apollo Server](https://www.apollographql.com/docs/apollo-server/v3/data/file-uploads/)

The issue occurs when I upload a file or multiple files. During the upload, my apollo-server is no longer accessible and the frontend no longer works.

What is strange is that the sending is done correctly (without error) but you have to wait between 3 to 6 minutes for a simple 3MB image (and during this time, my application is no longer available).

I have already opened an issue request at graphql-upload, which you can view here : https://github.com/jaydenseric/graphql-upload/issues/352 But for the moment we can't solve this issue, that's why I come to you :)

For information, the issue occurs with version 3 and 4 of apollo-server.

Thank you in advance for your help. (sorry also for my english, it's not my mother tongue)

### Link to Reproduction

-

### Reproduction Steps

You can simply reproduce the problem with the maintainer example of graphql-upload :
1. Create a VM
2. Simply install Debian or Ubuntu
3. Install NodeJS (https://github.com/nodesource/distributions/blob/master/README.md#deb)
4. Download API and app example provided by @jaydenseric (https://github.com/jaydenseric/apollo-upload-examples)
5. Then go to 'api' directory and run the command npm install, then npm run dev. Do also the same under the 'app' directory.
6. Then try to upload several images of 3 or 5 MB (https://www.sample-videos.com/download-sample-png-image.php)

**Comment by trevor-scheer** [comment]
Uploads are not a thing that we still support directly. Can you demonstrate that this issue is an Apollo Server problem and not a `graphql-upload` problem? Perhaps more generally Apollo Server hangs with large payloads? If you can show that the issue is specific to Apollo Server then we might be able to help.

I'm happy to reopen this issue if you provide a reproduction that provably demonstrates this is specific to Apollo Server.
