### ISSUE TITLE
Apollo Studio Sandbox is missing the "Include Cookies" check box in its connection settings for Apollo Server 4

### ISSUE THREAD

**Issue by nnamdiogbu** [apollographql/apollo-server#7284]
### Issue Description

I cannot set cookies on the browser when using Apollo sandbox after migrating to Apollo Server 4. Unlike v3, which has a "include cookies" checkbox in its connection settings, v4 doesn't have the option and as a result my cookies aren't being set even though I am sending these headers in my server response:

Access-Control-Allow-Origin: https://studio.apollographql.com/
Access-Control-Allow-Credentials: true

### Link to Reproduction

https://github.com/nnamdiogbu/Apollo-studio-sandbox-connection-settings/blob/main/README.md

### Reproduction Steps

Launch gql server and open Apollo sandbox on your browser 
Click the Explorer icon on the left menu bar
Click the settings cog on the Explorer tab
Click the edit connection settings button

**Comment by kicks321** [comment]
@glasser, any update thus far on this?

We cannot authorize any of our developers within the playground after version bumping Monday.

In the mean time, can we opt into another playground?

**Comment by kicks321** [comment]
@glasser, any status on this yet?

**Comment by glasser** [comment]
I don't see any traffic on the internal ticket but I've pinged it again.

**Comment by ISTANBULBEKLE** [comment]
Hi, we are having the same issue in our project. Just want to be sure; will you put some alternative to '"include cookies" checkbox', or an alternative way to include cookies. In our project this issue prevent us using Apollo Sandbox in stead of GraphQL Playground which is not supported anymore.

**Comment by glasser** [comment]
Sorry, I should have mentioned: you can pass `includeCookies: true` to the landing page plugin when setting it up.
https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages/
It's just that you can't choose at runtime with a UI control.

**Comment by trevor-scheer** [comment]
Fixed via https://github.com/apollographql/apollo-server/pull/7358
Releasing `4.4.0` as we speak!
