### ISSUE TITLE
Cannot read properties of undefined (@apollo/usage-reporting-protobuf/generated/protobuf.mjs)

### ISSUE THREAD

**Issue by quinnturner** [apollographql/apollo-server#7297]
### Issue Description

During application start-up, our ESM application (Docker Alpine with Node 16.13.1) halts immediately with the following error:

```
TypeError: Cannot read properties of undefined (reading 'default')
    at file:///usr/src/app/node_modules/@apollo/usage-reporting-protobuf/generated/protobuf.mjs:8:30
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async ApolloServer.addDefaultPlugins (file:///usr/src/app/node_modules/@apollo/server/dist/esm/ApolloServer.js:435:59)
    at async ApolloServer._start (file:///usr/src/app/node_modules/@apollo/server/dist/esm/ApolloServer.js:132:13)
    at async ApolloServer.start (file:///usr/src/app/node_modules/@apollo/server/dist/esm/ApolloServer.js:112:16)
    at async initializeServer (file:///usr/src/app/packages/api/built/src/api.js:229:5)"
```

Unfortunately, this error seems only to occur when deployed in our prod environment. I have yet to reproduce this with the same Dockerfile built locally or while running Node locally. Since I am struggling to reproduce this locally, I understand if this has to be closed as not being reproducible.

### Link to Reproduction

I don't have any, unfortunately.

### Additional info

- Node 16.13.1
- Alpine Docker, deployed on ECS
- Yarn Berry (not Plug'n'Play) with pruning performed by Turborepo

TSConfig:

```json
{
  "compilerOptions": {
    "target": "ES2021",
    "module": "ES2020",
    "lib": ["ES2021"],
    "outDir": "./built",
    "resolveJsonModule": true,
    "allowJs": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "sourceMap": true,
    "declaration": false,
    "declarationMap": false
    "composite": false,
    "esModuleInterop": true,
    "inlineSources": false,
    "isolatedModules": true,
    "moduleResolution": "node",
    "skipLibCheck": true,
    "strict": true,
    "importHelpers": true
  }
}

```

**Comment by trevor-scheer** [comment]
I'm not at my computer right now but look into some of the more current module and moduleResolution options for your TS config. IIRC those are necessary for ESM and TS. Check out some of our smoke tests for an example and let me know what your results are. Agree this is tough for us to help without a reproduction.

**Comment by quinnturner** [comment]
I wasn't able to fix this issue with a Node 16 version of our application. We have a branch with Node 18 and a bunch of other changes. That code works. 🤷🏻 For that reason, you're welcome to close this for now, but I am not sure that it's "solved"

**Comment by trevor-scheer** [comment]
Interesting. I wouldn't expect v16 to v18 to make the difference. Did you try `esnext` in your tsconfig? Do you have a tsconfig or interesting package.json diff from your v16 to v18 branch?

Going to close without a reproduction but if you do narrow down the issue that might help someone else in the future.

Thanks for reporting in any case!
