### ISSUE TITLE
Cannot use a custom executor: Error: You must call start() before getSchemaDerivedData()

### ISSUE THREAD

**Issue by casey-chow** [apollographql/apollo-server#7340]
### Issue Description

I'm trying to install a custom executor in my Apollo Server 4 instance. However, every time I try to run it, I see this error:

```
/project/sandbox/node_modules/@apollo/server/src/utils/schemaManager.ts:171
      throw new Error('You must call start() before getSchemaDerivedData()');
            ^
Error: You must call start() before getSchemaDerivedData()
    at SchemaManager.getSchemaDerivedData (/project/sandbox/node_modules/@apollo/server/src/utils/schemaManager.ts:171:13)
    at ApolloServer._start (/project/sandbox/node_modules/@apollo/server/src/ApolloServer.ts:399:47)
    at async ApolloServer.start (/project/sandbox/node_modules/@apollo/server/src/ApolloServer.ts:359:12)
    at async /project/sandbox/src/index.ts:48:3
```

### Link to Reproduction

https://codesandbox.io/p/sandbox/inspiring-microservice-j9p56m?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A57%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A57%7D%5D&file=%2Fsrc%2Findex.ts

### Reproduction Steps

Run the server attached.

**Comment by glasser** [comment]
There's an expectation that once `gateway.load()` has resolved, it has loaded a schema and called the callback passed to `gateway.onSchemaLoadOrUpdate()`, but yours doesn't. So your server has no schema.

(The `gateway` option isn't super documented; while you can use it yourself if you'd like, it's really designed for integration with `@apollo/gateway`.)

**Comment by casey-chow** [comment]
Great, thanks. I was able to make this work per your instructions and have updated the [sandbox](https://codesandbox.io/p/sandbox/inspiring-microservice-j9p56m?selection=%5B%7B%22endColumn%22%3A10%2C%22endLineNumber%22%3A53%2C%22startColumn%22%3A10%2C%22startLineNumber%22%3A53%7D%5D&file=%2Fsrc%2Findex.ts). Would it make sense to put this information in the upgrade guide, given that this is the default recommended implementation in there?

**Comment by glasser** [comment]
That's a good idea: updating the example in https://www.apollographql.com/docs/apollo-server/migration/#executor, as well as changing the sentence later "You can use the onSchemaLoadOrUpdate hook if you want to receive the schema.". Would you like to submit a PR? The guide is at `docs/source/migration.mdx` in this repo.
