### ISSUE TITLE
Is it possible to install Apollo Server on server only without any code ?

### ISSUE THREAD

**Issue by robinia1200** [apollographql/apollo-server#735]
I am new in graphql, would you please help me, I have a server for myself.  
In my server the  GraphQL queries written with Django . Is it possible to install Apollo Server on server only without any code and get query with Apollo client in ReactNative app? I mean should I write a code in server side?

**Comment by dotspencer** [comment]
Without any code?

**Comment by abernix** [comment]
It's not entirely clear what you're asking here, but this isn't the best place for questions like this.  I'm not sure what an Apollo Server without any code would do as you'd likely want your server to return results to the client, but I encourage you to join the [Apollo Slack](https://www.apollographql.com/slack), where you'll be more likely to get help on questions like this.
