### ISSUE TITLE
Docs: custom scalar example contains invalid types

### ISSUE THREAD

**Issue by sebakerckhof** [apollographql/apollo-server#7351]
### Issue Description

The typescript version of the custom scalar example has errors:
https://www.apollographql.com/docs/apollo-server/schema/custom-scalars/#example-the-date-scalar

### Link to Reproduction

JYWwDg9gTgLgBAbzgcSgQzACwIoBkDKAxmgDZpQAqAnmAKYA0cA0sAHYAmcAvnAGZQQQcAOQBzdFgCOJYQG4AsACglhCKwDO8dmhi0ipcnAC8cVrQDuKCTgLEylGrQAUCJXFNoQtAFwiAIjq0wvRucOy06oRQwGAwwGq

### Reproduction Steps

Paste the example in the typescript online playground (see reproduction link) and observe the errors

**Comment by glasser** [comment]
That does not appear to be a link?

**Comment by trevor-scheer** [comment]
Reproduction:
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgcSgQzACwIoBkDKAxmgDZpQAqAnmAKYA0cA0sAHYAmcAvnAGZQQQcAOQBzdFgCOJYQG4AUPMIRWAZ3js0MWkVLk4AXjitaAdxQScBYmUo1aACgTy4xtCFoAuEQBEttYXoXOHZaVUIoYDAYYBVvYT9tOEIAV3VBOHC9KDgYe0Dg1VpI0mAAL0cAN1IUrzhE2gBKRGDXKFoYFKhWOGqSWoA6UQ6KUEdG2TgAeim4AGEVSuL4CBSYUQg2UXr-XIg4Nm1hnN5oOAApfAB5ADlgriDXMHIigDUaqo-vVhSQACNis1nK42h0uj0TOYGg4+rUJtNZgtWEtYAdWMoQFs0Udinsdtp7o84M8oEVcMBtOgSA40Ooga0Drw4DT1AMANZsTgGbnMTkDACSNwo9JBIJm80WyzgmHI7AAtMpQpwAIL4CiZGCRVjbGD7Q60Y5wNAcXKYWg9XX42gM0GdbrGMxWhwkor81gwFkwAawhhwACMAAZGhMGVwGeK3X1gJwZVB5YraJwfczWBB4MbsQbAQz2naISkSCQFK4HvIuBMgA
