### ISSUE TITLE
schema stitching question. modify initial request and pass it to remoteServer

### ISSUE THREAD

**Issue by lonyele** [apollographql/apollo-server#737]
I don't know if it's right to ask here... but I couldn't find anywhere. 
There is one api gateway graphql/express server(get all the request from clients) and 
multiple microservice graphql/express servers(auth, business logic1 , business logic2, business logic3 etc) that are connected to this gateway using schema stitching.(mergeSchema) 

1. if client requests with Bearer token, normally I can retrieve token from headers and use context to pass down authorization token and use it at the resolvers. But How can I pass this to remote server?
It seems like modifying request object doesn't affect anything.(it only affects the object in gateway server)
It seems like copying graphql specific data only and send it to remoteServer.(Therefore, I couldn't get the Authorization header at my remoteServer)
so far, I couldn't find a way to pass my jwt token from api gateway to other remote servers. 

Am I thinking something wrong?

**Comment by booboothefool** [comment]
I am trying to do the same thing right now and having trouble figuring it out. It's like we need "context stitching" too or something.

**Comment by booboothefool** [comment]
@lonyele I think I was just able to solve this using Apollo Link with `setContext`.

```
  const ContextLink = setContext((request, previousContext) => ({
    headers: {
      authorization: previousContext.graphqlContext.headers.authorization,
    },
  }));
  const AuthLink = new HttpLink({
    uri: 'http://localhost:3001/graphql',
    fetch,
  });
  const AuthSchema = makeRemoteExecutableSchema({
    schema: await introspectSchema(AuthLink),
    link: ApolloLink.from([ContextLink, AuthLink]),
  });

  const ChatLink = new HttpLink({
    uri: 'http://localhost:3002/graphql',
    fetch,
  });
  const ChatSchema = makeRemoteExecutableSchema({
    schema: await introspectSchema(ChatLink),
    link: ChatLink,
  });

  const mergedSchema = mergeSchemas({
    schemas: [AuthSchema, ChatSchema],
  });
```

Now Auth microservice has token available in headers.

**Comment by lonyele** [comment]
I don't know why I couldn't see this earlier, but It seems like It would work with your method. I'll try this soon.  Thanks a lot!!

**Comment by lucasconstantino** [comment]
How about something from the mergedSchemas altering headers on the response from above? @booboothefool any ideas how could I accomplish this?

**Comment by acrogenesis** [comment]
When trying to do this I always get `"message": "Cannot read property 'Authorization' of undefined",` I've tried with caps and without, also just matching all headers `headers: previousContext.graphqlContext.headers,` but it still doesn't pass.

**Comment by sgil-carecloud** [comment]
what if you want to pass in a whole context? For example, authorization server returns policies that are tied to the user, i dont want to send the token down to my stitched serve, i want to pass down the user object i set at my context.

**Comment by patchyj** [comment]
This might sound dumb but where is setContext() coming from?

**Comment by digibeuk** [comment]
> This might sound dumb but where is setContext() coming from?

I struggled with this also, he using `apollo-link-context`

```
import { setContext } from "apollo-link-context";
import { ApolloLink } from 'apollo-link';
```

**Comment by xpolb01** [comment]
How do you use it in the service that you have stitched?
Something like this:
`context: ({ headers }) => {}`
