### ISSUE TITLE
How to correctly throw an Error in Apollo 4 custom plugin hooking into "requestDidStart"? 

### ISSUE THREAD

**Issue by Mika83AC** [apollographql/apollo-server#7375]
In Apollo 3, I was able to throw an Error if there was missing a header I enforce to be present, and the Error got correctly passed into the response to the client:

```typescript
export const gqlPluginServerClientIdentHeader = {
	requestDidStart(gqlServerContext){
		if ((gqlServerContext.context as Ctx).request.body.operationName === 'IntrospectionQuery')
			return;

		if ((gqlServerContext.context as Ctx).request.headers['apollographql-client-name'] === undefined)
			throw new GraphQLError('No \'apollographql-client-name\' header provided! Request not accepted.');
	}
};
``` 

Now while migrating to Apollo 4, I've changed to code to the new structure:

```typescript
export const gqlPluginServerClientIdentHeader: ApolloServerPlugin<BaseContext> = {
	async requestDidStart(gqlServerContext) {
		if ((gqlServerContext.contextValue as Ctx).request.body.operationName === 'IntrospectionQuery')
			return;

		if ((gqlServerContext.contextValue as Ctx).request.headers['apollographql-client-name'] === undefined)
			throw new GraphQLError('No \'apollographql-client-name\' header provided! Request not accepted.', { extensions: { code: ApolloServerErrorCode.BAD_REQUEST } });
	}
};
```

but this leads to the following response to the client:

```
{
  "data": {},
  "errors": [
    {
      "message": "Internal server error",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "Error: Internal server error",
          "    at internalExecuteOperation (/home/node/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:624:15)",
          "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
          "    at async runHttpQuery (/home/node/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)",
          "    at async runPotentiallyBatchedHttpQuery (/home/node/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)",
          "    at async ApolloServer.executeHTTPGraphQLRequest (/home/node/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:525:20)",
          "    at async /home/node/app/node_modules/@as-integrations/koa/dist/index.js:33:47",
          "    at async execute (/home/node/app/app/src/middlewares/lastMiddleware.js:7:5)",
          "    at async check (/home/node/app/app/src/middlewares/dosProtect.js:23:5)",
          "    at async authHandler (/home/node/app/app/src/middlewares/authentication.js:31:5)",
          "    at async check (/home/node/app/app/src/middlewares/xssPrevention.js:9:5)"
        ]
      }
    }
  ]
}
```

response.

Any ideas how to correctly throw an Error in this case? I tried for hours now but can't find a solution for this. The docs don't cover throwing Errors in Plugins (as far as I saw).

**Comment by glasser** [comment]
Is throwing from your context function an option? We made the behavior of doing that well-defined in AS4.

**Comment by Mika83AC** [comment]
@glasser Yes, in this case this would be possible, because it's a error which can be catched before the lifecycle even starts.

But I've also other plugins which might throw errors (query complexity etc.) and can't be catched outside the gql processing. And I'm afraid I'll run into the same issue there, right?

**Comment by glasser** [comment]
I mentioned in https://github.com/apollographql/apollo-server/issues/7278#issuecomment-1370386723 why this is a bit challenging w.r.t. error handling in this particular early handler. On the other hand we do make sure that throwing from `didResolveOperation` is well-supported, and that's the hook you'd want to use for query complexity.

**Comment by Mika83AC** [comment]
Yes, you're right @glasser. The header check issue was resolved by doing it in the context creation function, and as you say, query complexity happens later in `didResolveOperation` which works fine with throwing Errors there.

So my issues are solved. Thx for your support!
