### ISSUE TITLE
Error when following the `getting-started.mdx`

### ISSUE THREAD

**Issue by thekp** [apollographql/apollo-server#7388]
### Issue Description

Hi,

I followed along with the setup guide for [setting up apollo-server with typescript](https://github.com/apollographql/apollo-server/blob/main/docs/source/getting-started.mdx), and I came across an error when trying to execute the server locally...

**See the error below:**
```
$ node ./dist/index.js
(node:86818) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/api-gateway/dist/index.js:1
import { ApolloServer } from '@apollo/server';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1159:20)
    at Module._compile (node:internal/modules/cjs/loader:1203:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.4.0
```

I'm compiling the TypeScript with the exact compilerOptions suggested in the docs.

**My solution:**
I was able to fix it by updating the `index.ts` file to be `index.mts` and then running the code with `ts-node`. Like so: 
`"ts-node --esm ./src/index.mts"`

**My questions?**
- What would be the optimal way of running apollo-server with TypeScript?
- Can anyone else validate if there is an issue with the docs or if it's just my machine? 🙏 

### Link to Reproduction

https://github.com/apollographql/apollo-server/blob/main/docs/source/getting-started.mdx

### Reproduction Steps

1. Following the typescript steps on the documentation: https://github.com/apollographql/apollo-server/blob/main/docs/source/getting-started.mdx
2. Run `node ./dist/index.js` locally to see the errors above (maybe)

My dependencies:

- "typescript": "4.9.4"
- "@apollo/server": "^4.4.0",
- "graphql": "^16.6.0",
- "ts-node": "^10.9.1",
- "@types/node": "18.11.3",

**Comment by trevor-scheer** [comment]
Did you possibly miss step 5 [in this section](https://www.apollographql.com/docs/apollo-server/getting-started#set-up-with-typescript)? The error indicates you haven't set your `package.json` `"type": "module"`. I followed the steps and was unable to reproduce.

I'm going to close preemptively but happy to reopen if my diagnosis is incorrect.

**Comment by thekp** [comment]
Yeah that was the issue 😅

**Comment by trevor-scheer** [comment]
All good, thanks for taking the time to try to improve it!
