### ISSUE TITLE
4.4.0: includeCookies not working anymore since toggle was added to the sandbox

### ISSUE THREAD

**Issue by jlowcs** [apollographql/apollo-server#7391]
### Issue Description

We now have to go to the sandbox settings to explicitely enable the cookies, as `includeCookies: true` seems to be ignored since bumping to 4.4.0.

### Link to Reproduction

N/A

**Comment by jlowcs** [comment]
See also https://github.com/apollographql/apollo-server/pull/7358

**Comment by esilverm** [comment]
Hey! Thanks for bringing this to our attention. For now, a short-term fix would be to clear the cookies for the embedded iframe and reload. I know where the issue lies in sandbox and will try to have a fix for this issue asap.

**Comment by esilverm** [comment]
This should be fixed now. To see the changes, update your version of Sandbox

**Comment by jlowcs** [comment]
> update your version of Sandbox

Not quite sure what you mean by that 🤔

**Comment by esilverm** [comment]
> Not quite sure what you mean by that 🤔

Apologies for the confusion. In the menu bar of the sandbox there should be a bullhorn icon that says "What's new in Studio". If you click on that, a modal should open up and in the bottom left corner there will be a button that says "Update available, click to relaunch".

![Screenshot 2023-02-23 at 3 27 13 PM](https://user-images.githubusercontent.com/24704789/221022424-c19fd91f-b627-4733-b8ac-e46e8f76db2d.png)

Clicking that will update your sandbox to use the latest features.

**Comment by jlowcs** [comment]
I'm still confused. That modal says `You're up to date on version fe03bc`. But I didn't update anything.

The code is using `ApolloServerPluginLandingPageLocalDefault` btw.

**Comment by trevor-scheer** [comment]
@jlowcs that's tied to the version of Studio you're running (the web app itself) which is where the bug fix was landed. It sounds like you're up-to-date. Are you still seeing the issue?

This fix was not a code change in Apollo Server (or the plugin you're referring to) so no update needed there.

Thanks for noting the typo in the date, I actually noted that earlier and it should be resolved shortly (the fix for it is now merged).

**Comment by jlowcs** [comment]
Not seeing the issue anymore even after clearing the localStorage, so I guess it worked. Thank you!
