### ISSUE TITLE
plugin as a function not working

### ISSUE THREAD

**Issue by jlowcs** [apollographql/apollo-server#7396]
### Issue Description

The [documentation](https://www.apollographql.com/docs/apollo-server/api/apollo-server#plugins) says the following:
> An array of plugins to install in your server instance. Each array element can be either a valid plugin object or **a zero-argument function that returns a valid plugin object**.

It appears that passing a function for a plugin doesn't work on @apollo/server v4 (it did work on v3). I looked at the code (e.g. [here](https://github.com/apollographql/apollo-server/blob/d7e9b97595b063f1e796ec4449850a16d19e8b18/packages/server/src/ApolloServer.ts#L412)), and it indeed doesn't seem to be taking into account that a plugin could be a function. Maybe the documentation (and migration guide) should be updated to reflect that?

### Link to Reproduction

N/A

**Comment by trevor-scheer** [comment]
Thanks for reporting @jlowcs. This is called out in the [migration guide](https://www.apollographql.com/docs/apollo-server/migration/#plugins-constructor-argument-does-not-take-factory-functions) but I've filed a PR to fix the API docs.

**Comment by jlowcs** [comment]
Ah, I guess I missed it when I did the migration a few weeks ago :/
