### ISSUE TITLE
Looking for guidance/best way to allow post-processing of GatewayExecutionResult after executor has completed but before plugins are called

### ISSUE THREAD

**Issue by theJC** [apollographql/apollo-server#7399]
In Apollo Server 3, our codebase was able to extend ApolloServer, and in it override the _start function to allow us to wrap the gateway executor with some custom code:

```
   protected async _start(): Promise<void> {
        const result = await super._start();
        this.requestOptions.executor = decorateExecutor(
            this.requestOptions.executor
        );
        return result;
    }
```

With Apollo Server 4, this is no longer possible without disabling typescript's prevention of accessing the private this.internals where the executor is now stored:

```
   public async start(): Promise<void> {
        const result = await super.start();
        // @ts-ignore 
        this.internals.gatewayExecutor = decorateExecutor(
            // @ts-ignore
            this.internals.gatewayExecutor
        );
        return result;
    }
```

Can Apollo restore this capability through having a formal approved interface to allow customers to a post-hook (and potentially even pre-hook) around the executor BEFORE the plugin interface cycle kicks in:

### PRIMARY NEED : POST HOOK - 
The first plugin lifecycle that we have access to after the executor would be `didEncounterErrors`, and all the registered plugins are invoked async, and unfortunately our use case is the decorator above conditionally adding additional errors, so this plugin is not sufficient... we need to add the errors before didEncounterErrors are called
 
### ADDED BENEFIT IF PRE/POST HOOKS WERE AVAILABLE
If we had hook access to pre/post execute() or executor processing, we could also add datadog custom trace spans in place, allowing us to instrument nearly identical to what you have done in the Gateway executor for opentelemetry -- which unfortunately is not leverageable by your customers using dd-trace-js library from Datadog.

**Comment by glasser** [comment]
You could pass your own gateway that wraps another gateway?

**Comment by theJC** [comment]
I looked at that approach, Im trying to remember why I dismissed it.

I then tried creating a subclass of ApolloGateway and tried overriding the executor() method, but then I realized its not a class method but a property that is a method, and although I figured out how to override it through capturing the method and then changing it in the constructor of my subclass, it felt dirty.

Question:  

Could the gateway's [executor()](https://github.com/apollographql/federation/blob/77168fd932a4171bfb88163bcfa98fa0a8c2d48e/gateway-js/src/index.ts#L740) be changed to be a class method instead of a property, or is there specific reasons/benefits to having it defined that way?  

If it can be changed to be a class method, it then becomes extremely clean and simple to extend the class and simply override executor(), and use that to wrap the super.executor().

**Comment by trevor-scheer** [comment]
@theJC frankly, we aren't looking to add features like this into the gateway but I can certainly sympathize with the fact that we broke something that previously worked for you. Since this wasn't really documented / supported behavior to begin with, I don't intend to "fix" it as an API addition to the gateway.

The `executor` _property_ is that way for technical reasons as you've inferred - it's an arrow function which retains its `this` context when called outside of the context of the gateway class (which is how the server uses it). Making it a method would then require server to bind the gateway's context to the call of the executor (which would've been a reasonable decision to do as well, I think, but it doesn't currently). I'm not super inclined to change this implementation detail.

The good news is I've found and validated a workaround which seems pretty reasonable! The `super` approach doesn't work as you noted - but we can still capture the original `executor` another way like so:
```ts
import {
  GatewayExecutionResult,
  GatewayGraphQLRequestContext,
} from "@apollo/server-gateway-interface";
class MyGateway extends ApolloGateway {
  wrappedExecutor: ApolloGateway['executor'];

  constructor(config?: GatewayConfig) {
    super(config);
    this.wrappedExecutor = this.executor;
    this.executor = this.executorWrapper;
  }

  public executorWrapper = async (
    requestContext: GatewayGraphQLRequestContext
  ): Promise<GatewayExecutionResult> => {
    // pre-execution stuff
    const result = await this.wrappedExecutor(requestContext);
    // post-execution stuff
    console.log(result);
    return result;
  };
}
```

Hope this is sufficient for you, if not let me know. FWIW I think your suggestions are reasonable, I'm just generally inclined to steer people towards router and adding new API to gateway only actively locks people into the gateway further / makes router adoption more difficult.

Closing preemptively but happy to reopen if this doesn't solve your problem.

**Comment by theJC** [comment]
I totally appreciate the tension you need to provide re: additional effort/changes/support for gateway vs router.

The code you provided looks very close to one iteration where I had tried (and it worked), but thats what I was talking about above where I said it felt dirty/hacky... maybe thats just because I  have more Java coding experience than Javascript, and doing the below felt more natural to how it would have to be done in Java.

I had intended to let you know how my current solution was accomplished but didn't want to clutter the above.

We went live in PROD today with our migration to AS 4 currently using this pattern:

```javascript
class MyGateway extends ApolloGateway {
    public async load(options?): Promise<{
        schema: GraphQLSchema;
        executor: GatewayExecutor;
    }> {
        const originalLoadResult = await super.load(options);
        return {
            ...originalLoadResult,
            executor: wrapExecutor(originalLoadResult.executor)
        };
    }
}
```


Interested in your thoughts on which way is cleaner/less likely to be broken by any potential changes to ApolloGateway in the future (less maintenance for however long we remain on gateway)

Again, thanks so much for your feedback and examples, they are greatly appreciated!
-Jon

**Comment by trevor-scheer** [comment]
I can't come up with a reason for mine over yours, both seem reasonable. I don't anticipate many changes to gateway in the future that might break a usage like this. Generally speaking, most of our changes going forward will not be related to the gateway itself and I _really_ hope we don't change how it interfaces with Apollo Server (only its query planning etc. internals which are shared by the rust router).

Glad you landed on something that works!
