### ISSUE TITLE
Missing keyword in integration test documentation

### ISSUE THREAD

**Issue by karimmakhloufi** [apollographql/apollo-server#7404]
### Issue Description

We try to access to `body.kind` instead of `response.body.kind`, here is a pull request fixing it: https://github.com/apollographql/apollo-server/pull/7403

### Link to Reproduction

https://github.com/karimmakhloufi/apollo-server-v4-jest/blob/main/src/index.ts

**Comment by trevor-scheer** [comment]
Via #7403
