### ISSUE TITLE
No. of clients connected to a subscription

### ISSUE THREAD

**Issue by gijo-varghese** [apollographql/apollo-server#741]
I'm building a chat widget where the users will be subscribed to the following subscription. For each user, the '`user_id`' will be different
```
subscription {
  newUserMessage(user_id: 123) {
    id
    content
    type
  }
}
```

I want to find whether a user is online or not. So is there any way to find the number of clients connected to a particular subscription?

My subscription's resolver looks like this: 
```
newUserMessage: {
    subscribe: withFilter(
      () => pubsub.asyncIterator("newUserMessage"),
      ({ newUserMessage }, args) => {
        return args.user_id === newUserMessage.user_id;
      }
    )
  }
```

**Comment by pyros2097** [comment]
You can do it using the subsription server's onConnected and onDisconnected methods. So basically when onConnected is fired you will need to increment a counter in a database like redis and when onDisconnected is fired you will need to decrement the same counter and that will give you the no of live users.

**Comment by gijo-varghese** [comment]
@pyros2097 but we can't rely on `onDisconnected` methods. It will be called only if browser properly closes it. It will not be called if there is a sudden disconnection of wifi or network

**Comment by pyros2097** [comment]
Yeah then it gets complicated. You need to build a heartbeat system to check if the connection is still alive for each connection every 30s or so. Something like ping/pong on interval basis. And decrease the counter if a connection doesn't return 2/3 heartbeats.

**Comment by gijo-varghese** [comment]
@pyros2097 exactly. Luckily it was already built inside. I just had to pass `keepAlive` value in the `new SubscriptionServer` options. 

I finally made it. But took some time. Because most of the features were not documented properly. I'm switching to `SocketIO` soon. Fed up!

**Comment by sneko** [comment]
Hi @pyros2097 , long time ago but wondering if you found a proper way for the ping-pong feature into Apollo tools?

See my post https://github.com/apollographql/subscriptions-transport-ws/issues/654#issuecomment-814698666

**Comment by aramisromero89** [comment]
> @pyros2097 exactly. Luckily it was already built inside. I just had to pass `keepAlive` value in the `new SubscriptionServer` options.
> 
> I finally made it. But took some time. Because most of the features were not documented properly. I'm switching to `SocketIO` soon. Fed up!

What happens if you have scaled your deploy to many servers (width graphql redis or amqp subscriptions).
