### ISSUE TITLE
Support `https` server for the `drainHttpServer` plugin

### ISSUE THREAD

**Issue by cliffordfajardo** [apollographql/apollo-server#7414]
Currently it seems like the `drainHttpServer` plugin only works for HTTP servers:

Docs: https://www.apollographql.com/docs/apollo-server/api/plugin/drain-http-server/
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/6743796/222572875-5454b053-55bb-4d5e-882d-8ce154ea7668.png">

Will there be support for passing an `https` server? 
At work I am using an https nodejs server

**Comment by trevor-scheer** [comment]
Have you tried it? `https.Server` extends `http.Server` so it should just work (we even mention it in [a comment in the source code](https://github.com/apollographql/apollo-server/blob/3a4823e0d85afb51b7fb82a9f3a525c1957eab5d/packages/server/src/plugin/drainHttpServer/index.ts#L11)). If you'd like to open a PR to update the docs for clarity that'd be appreciated!

**Comment by cliffordfajardo** [comment]
yes just tried it and it worked - going to open a PR for the docs 🙏
