### ISSUE TITLE
Cannot find module '@apollo/server' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by fbryo21** [apollographql/apollo-server#7422]
Thisi is my **tsconfig.json** corresponding to tutorial on **apolloserver** website:
```
{
    "compilerOptions": {
        "rootDirs": [
            "src"
        ],
        "outDir": "dist",
        "lib": [
            "es2020"
        ],
        "target": "es2020",
        "module": "esnext",
        "moduleResolution": "node",
        "esModuleInterop": true,
        "types": [
            "node"
        ]
    }
}
```
My scripts on package.json:
```
"scripts": {
    "compile": "tsc",
    "start": "npm run compile && node ./dist/index.js"
  },
```

I've done several tips, like restarting vscode

**Comment by trevor-scheer** [comment]
Please send me a repo I can clone with steps to reproduce the issue. Unfortunately code snippets alone are not enough for me to be helpful.

**Comment by trevor-scheer** [comment]
Going to close this, but happy to reopen with a reproduction. Is `@apollo/server` in your `package.json`'s `dependencies`?
