### ISSUE TITLE
Cannot change overall Cache policy

### ISSUE THREAD

**Issue by danielhuntleymclaren** [apollographql/apollo-server#7429]
### Issue Description

After setting `ApolloServerPluginCacheControl.defaultMaxAge` it appears that `overallCachePolicy.maxAge` is still set to 0 (expecting 20) is there another way this can be set so that I can enable writing to the cache?

Below I have included a small example
```
const gateway = new ApolloGateway({
  supergraphSdl: new IntrospectAndCompose({
    subgraphs: [
      { name: "abc", url: ... },
      { name: "cde", url: ... },
    ],
  })
});

const cache = new KeyvAdapter(new Keyv(process.env.REDIS_URI));

const server = new ApolloServer({
  gateway,
  cache,
  plugins: [
    ApolloServerPluginCacheControl({ defaultMaxAge: 20, calculateHttpHeaders: false }),
    responseCachePlugin({}),
    {
      async requestDidStart() {
        return {
          async willSendResponse(requestContext) {
            const { overallCachePolicy } = requestContext;
            console.log(overallCachePolicy.maxAge); // 0
          },
        };
      },
    },
  ],
});
const app = express();
await server.start();

app.use("/graphql", cors(), json(), expressMiddleware(server));

app.listen({ port: 8000 }, () => console.log(`Server ready at http://:8000`));
```

### Link to Reproduction

^

**Comment by trevor-scheer** [comment]
I need a full reproduction to actually be helpful with this. Can you share a codesandbox or something I can `git clone` and run locally?

* Are your subgraphs setting the expected caching headers?
* Are you using `calculateHttpHeaders: false` in your subgraphs too? (I think that would break it)
