### ISSUE TITLE
sandbox: connection settings missing cookies options in Schema tab

### ISSUE THREAD

**Issue by jlowcs** [apollographql/apollo-server#7476]
### Issue Description

When switching to the "Schema" tab, the connection settings modal loses the "Include cookies" option, and its value is actually reset to `false`, which means that I have to set it back to `true` manually when going back to the "Explorer" tab.

### Link to Reproduction

N/A

### Reproduction Steps

1. go to the sandbox url
2. make sure that "include cookies" is enabled in the "connection settings"
3. click on the "Schema" tab on the left
4. go in the "connection settings" => no more "include cookies" option
5. go back to the "Explorer" tab
6. go in the "connection settings" => still no "include cookies" option
7. refresh the page ("Explorer" tab)
8. go in the "connection settings" => "include cookies" option is back, but disabled

**Comment by mayakoneval** [comment]
👋🏻 Hello! You are right, this was a bug. We just deployed a fix. Please let me know if you run into any issues. 

Thank you so much for the report!
