### ISSUE TITLE
ApolloServerPluginLandingPageGraphQLPlayground subscription fail

### ISSUE THREAD

**Issue by itamarshubin** [apollographql/apollo-server#7478]
I am trying to create simple graphQl server using apollo.
I followed Apollo's subscription example and it worked fine.

Now, I have to use apollo's playground, not the sandbox.

So I've added the `ApolloServerPluginLandingPageGraphQLPlayground` plugin to the `AolloServer` when building it.
```
const server = new ApolloServer({
  schema,
  plugins: [
    ApolloServerPluginLandingPageGraphQLPlayground(),
```
 but now I can't use subscriptions. it send me this error: `{
  "error": "Could not connect to websocket endpoint ws://localhost:4000/graphql. Please check if the endpoint url is correct."
}`

this is my full code:
```
import { ApolloServer } from "@apollo/server";
import { expressMiddleware } from "@apollo/server/express4";
import { createServer } from "http";
import express from "express";
import { makeExecutableSchema } from "@graphql-tools/schema";
import { WebSocketServer } from "ws";
import { useServer } from "graphql-ws/lib/use/ws";
import bodyParser from "body-parser";
import cors from "cors";
import { PubSub } from "graphql-subscriptions";
import { ApolloServerPluginLandingPageGraphQLPlayground } from "@apollo/server-plugin-landing-page-graphql-playground";
const pubSub = new PubSub();

const typeDefs = `#graphql
  # Comments in GraphQL strings (such as this one) start with the hash (#) symbol.

  # This "Book" type defines the queryable fields for every book in our data source.
  type Book {
    title: String
    author: String
  }

  # The "Query" type is special: it lists all of the available queries that
  # clients can execute, along with the return type for each. In this
  # case, the "books" query returns an array of zero or more Books (defined above).
  type Query {
    books: [Book]
  }

  type Subscription{
    addBook: String
  }
`;

const books = [
  {
    title: "The Awakening",
    author: "Kate Chopin",
  },
  {
    title: "City of Glass",
    author: "Paul Auster",
  },
];

// Resolvers define how to fetch the types defined in your schema.
// This resolver retrieves books from the "books" array above.
const resolvers = {
  Query: {
    books: () => {
      pubSub.publish("TEST", { addBook: "testing" });
      return books;
    },
  },
  Subscription: {
    addBook: {
      subscribe: () => pubSub.asyncIterator("TEST"),
    },
  },
};

// Create the schema, which will be used separately by ApolloServer and
// the WebSocket server.
const schema = makeExecutableSchema({ typeDefs, resolvers });

// Create an Express app and HTTP server; we will attach both the WebSocket
// server and the ApolloServer to this HTTP server.
const app = express();
const httpServer = createServer(app);

// Create our WebSocket server using the HTTP server we just set up.
const wsServer = new WebSocketServer({
  server: httpServer,
  path: "/graphql",
});
// Save the returned server's info so we can shutdown this server later
const serverCleanup = useServer({ schema }, wsServer);

// Set up ApolloServer.
const server = new ApolloServer({
  schema,
  plugins: [
    ApolloServerPluginLandingPageGraphQLPlayground(),
    // Proper shutdown for the WebSocket server.
    {
      async serverWillStart() {
        return {
          async drainServer() {
            await serverCleanup.dispose();
          },
        };
      },
    },
  ],
});

await server.start();
app.use(
  "/graphql",
  cors<cors.CorsRequest>(),
  bodyParser.json(),
  expressMiddleware(server)
);

const PORT = 4000;
// Now that our HTTP server is fully set up, we can listen to it.
httpServer.listen(PORT, () => {
  console.log(`Server is now running on http://localhost:${PORT}/graphql`);
});

``` 

When I don't use the plugin the subscriptions works. but I need it to work with the plugin.

**Comment by glasser** [comment]
The maintainers of the GraphQL Playground project decided to stop maintaining it several years ago, and as of the start of this year Apollo no longer provides support for our wrapper around it.  We recommend you use a maintained UI for your server, not one that has had major security holes with no maintainers.

I'm curious what makes you inspired to use GraphQL Playground rather than, say, Apollo Explorer/Sandbox?

**Comment by itamarshubin** [comment]
I am working on private network that don't have any connection to do network.(I can get libraries and files to the network put it don't have normal internet connection...) if there is a way to make apollo load the sandbox/explorer via my computer rather then the network it will be fine to.

**Comment by itamarshubin** [comment]
> The maintainers of the GraphQL Playground project decided to stop maintaining it several years ago, and as of the start of this year Apollo no longer provides support for our wrapper around it. We recommend you use a maintained UI for your server, not one that has had major security holes with no maintainers.
> 
> I'm curious what makes you inspired to use GraphQL Playground rather than, say, Apollo Explorer/Sandbox?


I am working on private network that don't have any connection to do network.(I can get libraries and files to the network put it don't have normal internet connection...) if there is a way to make apollo load the sandbox/explorer via my computer rather then the network it will be fine to.

**Comment by glasser** [comment]
The old Apollo Server GraphQL Playground plugin works by loading the Playground code from a CDN (not from your actual server), so I'm not sure how it would work for you in this context...

**Comment by itamarshubin** [comment]
> The old Apollo Server GraphQL Playground plugin works by loading the Playground code from a CDN (not from your actual server), so I'm not sure how it would work for you in this context...

I know, we created cdn than have the playground then we configure the playground to go to that cdn,
this isn't an option in the new sandbox
