### ISSUE TITLE
Error with typegraphql schema in @apollo/server

### ISSUE THREAD

**Issue by sarthak212** [apollographql/apollo-server#7480]
### Issue Description

I previously used TypeGraphQL with Apollo Server and generated the schema using TypeGraphQL’s buildSchema function. However, I needed to implement the subscription functionality, which requires Apollo Server v4. I’ve updated most of the components according to the documentation, but I’m encountering an error related to the schema:

**_“Expected 0 type arguments, but got 1.”_**

The error points to the line where ApolloServer is being initialized.

```
let schema = await buildSchema({
    resolvers: [
      UserResolver
    ],
  });
  const serverCleanup = useServer({ schema: schema }, wsServer);

  const apolloserver = new ApolloServer<RequestContext>({
    schema,
    plugins: [
      // Proper shutdown for the HTTP server.
      ApolloServerPluginDrainHttpServer({ httpServer }),

     // Proper shutdown for the WebSocket server.
      {
        async serverWillStart() {
          return {
            async drainServer() {
              await serverCleanup.dispose();
            },
          };
        },
      },
    ],
  });

  await apolloserver.start();
  app.use(
    "/api",
    expressMiddleware(apolloserver, {
      context: async ({ req, res }: RequestContext) => ({ req: req, res: res }),
    })
  );

  httpServer.listen(PORT, () => {

    console.log("Two link Backend listening on ", PORT);
  });
```
<img width="675" alt="Screenshot 2023-03-30 at 1 59 37 PM" src="https://user-images.githubusercontent.com/33999269/228777273-83708a75-1796-422e-a607-c46804412490.png">

here are my imports

<img width="575" alt="Screenshot 2023-03-30 at 2 01 02 PM" src="https://user-images.githubusercontent.com/33999269/228777580-40ac92b9-56ed-40e7-b295-af07302975f1.png">

here are interface for RequestContent

```
import { Request, Response } from "express";

export interface RequestContext {
  req: Request;
  res: Response;
  payload?: { userId: string };
  client_details?: client_details;
}
```

I removed this content and it still throw this error

**_Expected 0 arguments, but got 1_**

### Link to Reproduction

Let me know if i needed to host it's shorted version somewhere else

**Comment by trevor-scheer** [comment]
As @endroca said this does seem like a TS version problem. If that doesn't resolve it, please share a reproduction.

**Comment by sarthak212** [comment]
Yeah it's resolved,
Thank you @endroca @trevor-scheer
