### ISSUE TITLE
Apollo Server v4 embedded Explorer does not run preflight script for introspection automatic polling.

### ISSUE THREAD

**Issue by tchaffee** [apollographql/apollo-server#7481]
### Issue Description

When running an operation the preflight script runs and our shared Authorization is correctly sent to our server.

However if we turn on the automatic polling, the preflight script does not run, and the Explorer is sending the wrong value for the Authorization header. Introspection fails because of the wrong header value.

This was working fine in Apollo server v3.

### Link to Reproduction

http://localhost:4444/

### Reproduction Steps

1. Set up Apollo v4 server using Express.
2. The default for the server endpoint is to show the Explorer.
3. Create a preflight script to set the value of a token: explorer.environment.set('token', 'some value')
4. Added a shared authorization header using the value of token: Authorization Token {{token}}.
5. Turn on automatic polling. The preflight script does not run and the Authorization header has the wrong value in it.

**Comment by mayakoneval** [comment]
Hello! Thank you for the report. 

You are correct that preflight scripts don't run before introspection. If you are looking to set an environment variable for introspection requests, you have a couple options.

The Sandbox that is shipped with Apollo Server v4.5.0+ includes the option to pass [sharedHeaders](https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages/#sharedheaders). These will be added to every introspection request, and populated in the [shared headers section of your connection settings](https://studio.apollographql.com/sandbox/explorer?overlay=connection-settings). You also have the option to pass `sharedHeaders` variables using `key: "{{token}}"` syntax, and set the value for `token` in your env vars in Explorer settings. They will be interpolated into the headers when introspection requests are sent. 

Does that solve the issue for you, or are you needing to set auth per-request?

Thanks, 
Maya

**Comment by trevor-scheer** [comment]
Closing since I suspect this is resolved, happy to reopen if we hear otherwise. Thanks @mayakoneval!
