### ISSUE TITLE
Can't edit the shared headers in apollo graphql dashboard

### ISSUE THREAD

**Issue by Surya165** [apollographql/apollo-server#7506]
### Issue Description

I can't edit the shared headers field in appollo graphql dashboard after going to settings.

### Reproduction Steps

![masked_screenshot](https://user-images.githubusercontent.com/24978946/231978145-82aef080-b43e-4948-a894-e6c086288a19.jpeg)

**Comment by trevor-scheer** [comment]
Shared headers are configurable in code, but not by users:
https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages#initialstate-options

**Comment by mariuszbeltowski** [comment]
@trevor-scheer is there a way to enable headers management in the graphql dashboard? It was possible earlier using `import { ApolloServerPluginLandingPageLocalDefault } from 'apollo-server-core';` and was very useful for api debugging.

**Comment by trevor-scheer** [comment]
@mariuszbeltowski I'm not sure what you're asking. You can still set headers in Sandbox and Explorer UI, you just can't set _shared_ headers. Does that answer your question?
