### ISSUE TITLE
GraphQL resolvers are called with only 3 arguments

### ISSUE THREAD

**Issue by blissi** [apollographql/apollo-server#752]
Hallo,
according to the documentation in https://www.apollographql.com/docs/graphql-tools/resolvers.html the resolver functions have 4 arguments.

On my setup, they only have 3 arguments, though. The obj-argument is missing.

I have installed the following GraphQL-relevant packages:
```
"apollo-server-express": "^1.3.2",
"graphql": "^0.12.3",
"graphql-resolvers": "^0.2.0",
"graphql-subscriptions": "^0.5.6",
"graphql-tools": "^2.16.0",
"merge-graphql-schemas": "^1.4.0",
"subscriptions-transport-ws": "^0.9.4"
```

Is the documentation up-to-date or is this an issue?

**Comment by slaymance** [comment]
Hey blissi, could you provide a bit more information regarding the context in which you're experiencing this issue?
The _obj_ argument is always passed into a resolver function by default, so my best assumption of what is happening is you are accessing the argument in a top-level Query resolver, in which case the _obj_ arg is defined in your server configuration (see https://www.apollographql.com/docs/apollo-server/setup.html). Typically, you wouldn't define this value, so it would undefined.

**Comment by blissi** [comment]
Sorry, it was my fault: I passed the resolvers as the root value and I didn't merge the resolvers (they are split up into different files) properly.
