### ISSUE TITLE
CORS configuration with startServerAndCreateLambdaHandler 

### ISSUE THREAD

**Issue by nevolgograd** [apollographql/apollo-server#7521]
I was using `apollo-server-lambda` package until saw it's deprecated in favour of `@apollo/server.`
Previously my handler code looked like this: 
```
const server = new ApolloServer({
  typeDefs,
  resolvers,
  csrfPrevention: true,
  context: ({ event, context }) => {
    return {
      headers: event.headers,
      functionName: context.functionName,
      event,
      context
    };
  }
});

const apolloHandler = server.createHandler({
  cors: {
    origin: ['https://localhost', `https://domain-${STAGE}.com`],
    methods: ['OPTIONS', 'POST'],
    credentials: true
  }
});

export const handler = async (event: any, context: any) => {
  return await apolloHandler(
    {
      ...event,
      requestContext: context
    },
    context
  );
};
```

After updating dependencies I managed to run everything except the CORS part. I can't find it anywhere in documentation. How exactly CORS should be configured to use credentials (cookies)  from the client? Here is my code after update: 
```
const server = new ApolloServer({
  typeDefs,
  resolvers,
  csrfPrevention: true,
  context: ({ event, context }) => {
    return {
      headers: event.headers,
      functionName: context.functionName,
      event,
      context
    };
  }
});

export const handler = startServerAndCreateLambdaHandler(
  server,
  handlers.createAPIGatewayProxyEventRequestHandler() // Proxy V1 handler
);
```

Would rreally appreciate some help or advice here. Thanks in advance!

**Comment by glasser** [comment]
I think this question is best asked on the Lambda integration's repository.

Searching for CORS over there, I see a few things. Most notably, @BlenderDude mentions a plan to add a direct cors helper and has a PR in progress for the step before that. https://github.com/apollo-server-integrations/apollo-server-integration-aws-lambda/issues/85#issuecomment-1495279090
