### ISSUE TITLE
Mutation args are returned as null

### ISSUE THREAD

**Issue by NanasArsenal** [apollographql/apollo-server#7522]
### Issue Description

Mutation args are returned as null even when explicitly defined in the schema, and data is passed to the mutation function.

### Link to Reproduction

https://gist.github.com/NanasArsenal/5c726ccfd1ffbba43b78b5daa97eab40

**Comment by trevor-scheer** [comment]
Arguments are the 2nd positional argument in a resolver, you have it in the 1st position. The first positional arg is `parentValue`. [Here's an example from our quickstart](https://www.apollographql.com/tutorials/fullstack-quickstart/05-writing-mutation-resolvers).

```ts
Mutation: {
  setMessage: (parentValue, args) => {
    let message = args.input;
    return message
  }
}
```

**Comment by NanasArsenal** [comment]
Thanks @trevor-scheer
