### ISSUE TITLE
Cant set Shared Headers in Apollo Explorer, embed.

### ISSUE THREAD

**Issue by darkodavidovic** [apollographql/apollo-server#7524]
### Issue Description

When i go to Connection settings in apollo explorer, i cant set shared headers. The button "+ New Header" doesnt exist and all area around headers is gray, like disabled. The image is here https://prnt.sc/HzKVky0s2Evr
Worked before, but from last few days, wont.
Apollo Versions: "apollo-server": "^3.10.1", "apollo-server-core": "^3.10.1", "apollo-server-express": "^3.10.1",

### Link to Reproduction

https://prnt.sc/HzKVky0s2Evr

**Comment by mayakoneval** [comment]
Hi, thanks for the report!

This is a newly introduced bug, and I will update when it is fixed shortly.

**Comment by mayakoneval** [comment]
Hello, this bug should be fixed now. 

Please update us if you still see this issue. Thank you!

Maya

**Comment by darkodavidovic** [comment]
Hi, Maya. I have updated apollo-server, core and express to latest and i cleared the chache/cookies on my localhost:4000
"+ New Shared Header" button is back now.
Thank you... 👍 ;-)
