### ISSUE TITLE
Sandbox Endpoint CSS Box has sliders

### ISSUE THREAD

**Issue by PS1TD** [apollographql/apollo-server#7545]
### Issue Description

If the endoint url does not fit into the box in the Sandbox horizontal and vertical sliders show up, unlike hiding the rest of the url in previous versions.
![image](https://user-images.githubusercontent.com/33327811/235945158-a5296c77-f842-47ad-8e78-a427376ce6eb.png)

Apollo GraphQL Server Version 4.7.1

### Link to Reproduction

.

**Comment by mayakoneval** [comment]
Gross! This should be fixed now 🙇🏻
