### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/esm/plugin/drainHttpServer' is not defined by "exports"

### ISSUE THREAD

**Issue by Starodubenko** [apollographql/apollo-server#7549]
### Issue Description

I tried [Drain HTTP Server documentation](https://www.apollographql.com/docs/apollo-server/api/plugin/drain-http-server/)

and for now I have this error 

`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/esm/plugin/drainHttpServer' is not defined by "exports" in /node_modules/@apollo/server/package.json`

any ideas how to solve it?

also I tried to downgrade version to 4.0.0 and got the same error

### Link to Reproduction

https://www.apollographql.com/docs/apollo-server/api/plugin/drain-http-server/

**Comment by trevor-scheer** [comment]
That subpath is defined in the exports though, so the problem isn't obvious to me. I also can't reproduce this trivially. If you can provide me with a reproduction that I can clone or run without any creativity on my part I'm happy to reopen this issue.
