### ISSUE TITLE
Option to turn off cacheControl

### ISSUE THREAD

**Issue by rizowski** [apollographql/apollo-server#7559]
## Problem
I was looking for a way to turn off `cacheControl` types from being injected into my schema. There isn't any documentation around this from what I could see. So when I dove into the code, I found the only way to turn off `cacheControl` is to create an executable schema instead of passing in `typeDefs`.

### Code in question

https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/ApolloServer.ts#L150-L175

```js
    if (schema) {
      this.schema = schema;
    } else {
      if (!typeDefs) {
        throw Error(
          'Apollo Server requires either an existing schema or typeDefs',
        );
      }


      let augmentedTypeDefs = Array.isArray(typeDefs) ? typeDefs : [typeDefs];


      // We augment the typeDefs with the @cacheControl directive and associated
      // scope enum, so makeExecutableSchema won't fail SDL validation
      augmentedTypeDefs.push(
        gql`
          enum CacheControlScope {
            PUBLIC
            PRIVATE
          }

          directive @cacheControl(
            maxAge: Int
            scope: CacheControlScope
          ) on FIELD_DEFINITION | OBJECT | INTERFACE
        `,
      );
```

## Proposed solution
Can we get a way to turn it off much like uploads? Have a boolean option that can be set to false. I think it would be a little more clear.

### Example

```js
const server = new ApolloServer({ typeDefs, uploads: false, cacheControl: false });
```

## Other stuff

Where can future users find this information in the docs?

**Comment by trevor-scheer** [comment]
The cache control types are no longer installed by default since AS3
