### ISSUE TITLE
apollo-server-lambda Internal error

### ISSUE THREAD

**Issue by ducmaxime** [apollographql/apollo-server#759]
Hello,

Your code sample not woking.

"Internal Server Error" on POST request

```javascript
//MY SCHEMA
const schema = `
type Query {
    hello: String
}
`;

const resolver = {
  Query: {
    hello: () => 'Hello World',
  },
};

const myGraphQLSchema = graphqlTools.makeExecutableSchema({
  typeDefs: schema,
  resolvers: resolver,
});

// MY HANDLERS
exports.graphqlHandler = function(event, context, callback)  {
    const callbackFilter = function(error, output) {
        output.headers['Access-Control-Allow-Origin'] = '*';
        callback(error, output);
    };
    const handler = server.graphqlLambda({ schema: myGraphQLSchema });
    
    return handler(event, context, callbackFilter);
};

exports.graphiqlHandler = server.graphiqlLambda({
  endpointURL: '/Prod/graphql',
});
```

Any idea ?

**Comment by n1ru4l** [comment]
Have you checked your cloud-watch logs?

In my lambda function I also have this line `output.headers = output.header || {}` since headers could be `undefined`. This could also be your issue but I can only assume it 😅 .

**Comment by timellemeet** [comment]
@n1ru4l Been trying to figure out why my lambda's kept crashing for days. Your line fixed it. Tx a lot!

**Comment by n1ru4l** [comment]
I am going to close this.

@ducmaxime If you ares still having any problems you can reopen this issue!
