### ISSUE TITLE
Migration from v3 to v4 leads to CSRF and CSP problems

### ISSUE THREAD

**Issue by hinogi** [apollographql/apollo-server#7607]
### Issue Description

When updating packages and doing all the stuff from the migration guide. I get a CSRF Error when firefox tries to find a favicon.ico.
When I disable CSRF I get a CSP error for the same reason.

### Link to Reproduction

www.example.com

**Comment by sschneider-ihre-pvs** [comment]
CSRF on

![image](https://github.com/apollographql/apollo-server/assets/86342787/1e821c69-17e8-40e4-9029-9cf007ec4753)

CSRF off
![image](https://github.com/apollographql/apollo-server/assets/86342787/5856f169-8f7b-4b9b-a5c5-2f94cf34d9c6)

**Comment by sschneider-ihre-pvs** [comment]
I am only trying to access the endpoint with the browser, not any apollo client or anything

**Comment by trevor-scheer** [comment]
@hinogi Can you share a reproduction? Screenshots of errors don't help me all that much.

**Comment by sschneider-ihre-pvs** [comment]
I am unable to share one. Mainly I have a nestjs app v10 upgraded to v11 of nestjs/graphql following the apollo v3  to v4 migration guide with that being the result.
As far as I understand the nestjs/graphql module it just is an interface for setting up a apollo server express and the server options just get piped through to the apollo server.

**Comment by hinogi** [comment]
https://community.apollographql.com/t/addressing-csrf-from-a-python-service/5707/11
https://community.apollographql.com/t/apollo-4-get-sandbox-causing-csrf-on-server/5603
https://community.apollographql.com/t/this-operation-has-been-blocked-as-a-potential-cross-site-request-forgery-csrf/5676

**Comment by trevor-scheer** [comment]
There really isn't much I can do to help you without a reproduction. Are you using an AS4 compatible integration? You haven't shared the packages/versions you're trying to use so all I can do is guess.

**Comment by sschneider-ihre-pvs** [comment]
<details>
<summary>packages</summary>
    @apollo/client: 3.7.9 => 3.7.15
    @apollo/federation: 0.38.1 => 0.38.1
    @apollo/gateway: 2.3.2 => 2.4.7
    @apollo/query-planner: ^2.3.2 => 2.4.7
    @apollo/rover: 0.12.2 => 0.14.2
    @apollo/subgraph: 2.3.2 => 2.4.7
    @nestjs/apollo: 10.2.0 => 10.2.1
    @nestjs/common: 9.3.9 => 9.4.2
    @nestjs/config: 2.3.1 => 2.3.2
    @nestjs/core: 9.3.9 => 9.4.2
    @nestjs/graphql: 10.2.0 => 10.2.1
    @nestjs/mapped-types: * => 1.2.2
    @nestjs/microservices: 9.3.9 => 9.4.2
    @nestjs/platform-express: 9.3.9 => 9.4.2
    @nestjs/schematics: 9.0.4 => 9.2.0
    @nestjs/testing: ^9.3.9 => 9.4.2
    @nestjs/typeorm: 9.0.1 => 9.0.1
    @nrwl/nest: 15.6.3 => 15.6.3
</details>

**Comment by trevor-scheer** [comment]
@hinogi which integration are you using? I'm closing this issue until you provide a reproduction. I don't mean to rude but if you're literally unable to put one together then the issue does not exist. I cannot possibly make all the correct assumptions about your project to reproduce the error you're seeing.

**Comment by michael-watson** [comment]
This solution is working on my end:

```
const gql = require("graphql-tag");
const { readFileSync } = require("fs");
const { ApolloServer } = require("@apollo/server");
const { expressMiddleware } = require("@apollo/server/express4");
const {
  ApolloServerPluginDrainHttpServer,
} = require("@apollo/server/plugin/drainHttpServer");
const {
  ApolloServerPluginLandingPageDisabled,
} = require("@apollo/server/plugin/disabled");
const { buildSubgraphSchema } = require("@apollo/subgraph");
const resolvers = require("./resolvers");
const cors = require("cors");
const http = require("http");
const express = require("express");
const { json } = require("body-parser");
const port = process.env.PORT ?? 4001;

async function main() {
  const typeDefs = gql(
    readFileSync("schema.graphql", {
      encoding: "utf-8",
    })
  );
  const app = express();
  const httpServer = http.createServer(app);
  const server = new ApolloServer({
    schema: buildSubgraphSchema({ typeDefs, resolvers }),
    plugins: [
      ApolloServerPluginDrainHttpServer({ httpServer }),
      ApolloServerPluginLandingPageDisabled(),
    ],
  });
  await server.start();

  app.use(
    "/graphql",
    cors({ credentials: true }),
    json(),
    expressMiddleware(server, {
      context: async ({ req }) => {},
    })
  );
  await new Promise((resolve) => httpServer.listen({ port }, resolve));
}

main();

```

**Comment by hinogi** [comment]
if you kick out the landingpage plugin and visit the page you should be able to see the error I think

**Comment by trevor-scheer** [comment]
Provided a repro and opened an issue here: https://github.com/apollographql/embeddable-explorer/issues/263
