### ISSUE TITLE
Deployment apollo server v4 in lambda with api gateway

### ISSUE THREAD

**Issue by emon-gain** [apollographql/apollo-server#7616]
When i am trying to deploy the code in lambda in shows me an error: 
```
CREATE_FAILED: ApiGatewayDeployment (AWS::ApiGateway::Deployment)
Resource handler returned message: "The REST API doesn't contain any methods (Service: ApiGateway, Status Code: 400, Request ID: 8934c460-c726-455f-a935-4ea7ae694fcb)" (RequestToken: f***e***96b8-c***37-d4c7-4404-b6649b587***5b, HandlerErrorCode: InvalidRequest)
```

But when i am deploying the same code with same configuration with v2 it is working fine. 

What is the issue here?

**Comment by trevor-scheer** [comment]
Can you share a reproduction? I have no idea how to recreate the error you're seeing with the information you've given me. I need a repo that I can clone and run locally with instructions on how to reproduce the error. Are you using the new `@as-integrations/aws-lambda` package with v4?

**Comment by trevor-scheer** [comment]
Happy to reopen with a reproduction.
