### ISSUE TITLE
Anyone else feel like upgrading Apollo Server to Hapi 17 was a mistake?

### ISSUE THREAD

**Issue by nnance** [apollographql/apollo-server#762]
So the entire Hapi echo system hasn't been upgraded to support version 17 yet.  For examples, the typings are out of date and the entire Good plugin system doesn't support version 17.

**Comment by jeffm13** [comment]
apollo-server-hapi changes in 1.3.0 were breaking changes.  That version should have been named 2.0.0.   Existing, code depending on ^1.x.x breaks unless upgraded to hapi-v17.  Unfortunately, I have production builds that are now breaking because of this change.

**Comment by abernix** [comment]
You're both absolutely right that this wasn't done gracefully.  The Apollo versions are kept in sync and this is a side effect of that configuration, which currently fails when any of the 8 HTTP servers updates their major version.  Obviously, this isn't sustainable and we're making careful consideration to avoid this in the future, while still making sure that each HTTP server is properly tested with its appropriate middleware.  Apologies for that!

**Comment by abernix** [comment]
I think this is close enough to https://github.com/apollographql/apollo-server/issues/707 that we can close it.  Thank you for chiming in though.
