### ISSUE TITLE
Issue with Apollo Server and Apollo Express - Errors in Mutations Validation

### ISSUE THREAD

**Issue by Aloxbro** [apollographql/apollo-server#7621]
Hi everyone,

I hope this message finds you well. I wanted to bring to your attention an issue we've been experiencing recently with Apollo Server Core and Apollo Express in our production environment.

We have been using versions 3.11.1 of both Apollo Server Core and Apollo Express for quite some time without any major problems. However, we have started encountering 400 errors specifically related to mutations. It appears that Apollo is unable to find the received fields in the input validation it possesses. Strangely, when the same request is immediately re-executed, it works without any issues.

Here is a small preview

First call with code `400` :

`extensions: {code: "BAD_USER_INPUT"}
message: "Variable \"$input\" got invalid value { lastName: \"Doe\", firstName: \"John\", chatAuthorName: \"Alox\", variables.input.chatAuthorName: \"Alox\", variables.input.firstName: \"John\", variables.input.lastName: \"Doe\" }; Field \"variables.input.lastName\" is not defined by type \"UpdateMeInput\"."`

Second call with exact same value with statusCode 200 this time

```data:  {,…}
updateMe: 
{__typename: "User", id: "62162f3575b0afa2dfa555e4", email: "john.doe11@gmail.com",…}
accessibleContent: "published"
avatarUrl: "https://lh3.googleusercontent.com/a/AAcHTtdjoCLeZ-Bk9GeWDrL29SJiCsXjoWe0jTQAJYQe=s96-c"
birthdayDate: "1990-01-01T23:00:00.000Z"
cguAccepted: "2022-02-23T12:57:27.750Z"
chatAuthorName: "Alox"
chatBanning: null
email: "john.doe11@gmail.com"
firstName: "John"
gender: "male"
id: "62162f3575b0afa2dfa555e4"
lastName: "Doe"
personalDataShareAccepted: true
__typename: "User"
```

The perplexing aspect is that we haven't made any code modifications related to this specific issue. Therefore, we are unsure why we are facing schema problems despite not having made any recent changes in this regard.

We would greatly appreciate it if anyone could shed some light on this matter or provide any insights on how we could troubleshoot and resolve this issue. Please let us know if there are any logs, error messages, or additional details that could assist in diagnosing the problem.

**Comment by trevor-scheer** [comment]
Why are you sending an input field named "variables.input.x"?

No code changes at all? No dependency updates?

Can you share a reproduction that I can run locally?

It's definitely odd that the first operation fails and subsequent operations don't.

I'll note that v3 is coming up on EOL in the next few months. I'd strongly recommend updating to v4 as soon as possible.

**Comment by Aloxbro** [comment]
Nope, it did occurs suddenly in production and we do struggle to fix it.

Sadly my company doesnt allow me to share a reproduction...

Yes it is quite weird that the same mutation do work and do fail sometimes with the same values...

We do plan on migrating with v4.

**Comment by trevor-scheer** [comment]
Has your client code changed at all?

I can reproduce the error by doing this:
```graphql
    type Mutation {
      test(input: TestInput): Boolean
    }

    input TestInput {
      id: ID!
    }
```
Send a mutation with the following variables:
```json
{
  "input": {
    "id": "1",
    "variables.input.id": "1"    
  },
}
```
And get this error:
```
  "errors": [
    {
      "message": "Variable \"$input\" got invalid value { id: \"1\", variables.input.id: \"1\" }; Field \"variables.input.id\" is not defined by type \"TestInput\".",
      "locations": [
        {
          "line": 1,
          "column": 10
        }
      ],
```

Without a reproduction this is as much help as I can offer. Something is wrong with your variables. Look closely at the client code which sends this mutation. I'm 99% sure this isn't a problem with Apollo Server, something is wrong with the mutation you're sending.
