### ISSUE TITLE
Disable external network requests

### ISSUE THREAD

**Issue by aclarknexient** [apollographql/apollo-server#7623]
Hello,

We're deploying Apollo server for the first time, and we've noticed that the devtools send a lot of calls to external sites like "launchdarkly.com", "*.stripe.com", etc.

I tried setting the APOLLO_TELEMETRY_DISABLED=1 in both the dockerfile for the task, and in the task definition, but neither stopped the external calls.

Is there a way to operate the server without any network requests except those between the browser and the service?

Thank you

**Comment by trevor-scheer** [comment]
That's a rover configuration. The option to disable telemetry is [in the docs](https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages#runtelemetry).

**Comment by Aeolun** [comment]
I have this setting enabled, but the landing page is still happily sending requests to both sentry and `https://graphql.api.apollographql.com/api/graphql`, and an initial call to stripe, though it doesn't look like anything more goes after the first request. I don't think that should be happening?

**Comment by trevor-scheer** [comment]
Thanks @Aeolun, I [opened an issue](https://github.com/apollographql/embeddable-explorer/issues/266) for it.
