### ISSUE TITLE
Queries that can run without csrfPrevention headers

### ISSUE THREAD

**Issue by strongpauly** [apollographql/apollo-server#7665]
I have a node application that is deployed on AWS behind a Application Load Balancer (ALB).  I have configured health checks to send a GET request to the Apollo server and run an arbitrary query defined in the URL.  With `csrfPrevention` enabled, these checks will always fail because the requests will be sent without the specified [headers](https://www.apollographql.com/docs/apollo-server/security/cors#preventing-cross-site-request-forgery-csrf).

I have no control over which headers are sent by the ALB.

I see two possible enhancements that could allow me to solve this problem:

1. Allow interjection via a plugin hook *before* the request is rejected, to allow certain operations to be run without required headers.
2. Allow a list of query operations to be passed in the `CSRFPreventionOptions` which are always allowed without the required headers.

**Comment by trevor-scheer** [comment]
Am I looking at [the right docs for ALB](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html)? Just want to make sure I understand the configuration options available to you.

Are you using the standalone server? I'd suggest moving to the express integration and adding a separate healthcheck endpoint. That gives you the flexibility to conform to ALB's requirements and do whatever you'd like w.r.t. checking the health of your Apollo Server (and possibly other things, like DB connections or other connected APIs).

**Comment by strongpauly** [comment]
Yes, that is the correct documentation link.

Deploying a separate endpoint has indeed been my workaround, however it seems like something that could be handled by the apollo server if the security restrictions were lifted for certain use cases.

**Comment by trevor-scheer** [comment]
Sorry for the delay @strongpauly.

Of the two options, I think the plugin hook is the more viable abstraction. Option 2 is worrisome to me.

Maybe more appropriately, an additional option to `CSRFPreventionOptions` like `bypassCsrfPrevention(request): Promise<boolean>` or something?

```ts
new ApolloServer({
  csrfPrevention: {
    bypassCsrfPrevention(req) {
      return validateHeader(req.headers.get('...'));
    },
  },
});
```

**Comment by strongpauly** [comment]
That would be great!

**Comment by trevor-scheer** [comment]
@strongpauly I'm open to a PR that implements this and includes documentation in the API docs for the configuration option. Security is a legitimate concern with this so I'd like us to provide an example and some explanation to prevent people from opening themselves up to any issues.

For example, in your use case I imagine you might look specifically for the `{__typename}` query in the url params. So that would look like:
```ts
new ApolloServer({
  csrfPrevention: {
    bypassCsrfPrevention(httpGraphQLRequest) {
      return httpGraphQLRequest.method === 'GET' && httpGraphQLRequest.search === 'query=%7B__typename%7D';
    },
  },
});
```
It's important to mention that you specifically look for `GET` here or else you could expose yourself to `POST` requests with a query in the body (that also use include that search param as a bypass).

**Comment by trevor-scheer** [comment]
@strongpauly I'd like to not leave this issue open potentially indefinitely, so I'm going to close it. If you decide you want to implement this I'm happy to reopen this issue and review your PR.
