### ISSUE TITLE
Integration of AS4 with graphql-jit not working

### ISSUE THREAD

**Issue by hiteshbal91dp** [apollographql/apollo-server#7774]
### Issue Description

We are migrating from AS3 to AS4 along with graphql-jit which we used to work with AS3 via `executor` option of ApolloServer(). 

According to migration guide we have to move to `gateway` parameter instead of `executor` which we did using `GatewayInterface` definition.

Now, we are facing an issue like consider query where we need to pass mandatory variable as input for mutation, earlier(AS3+graphql-jit+executor) upon not providing mandatory variable in GQL request it was throwing valid error saying $variable should not be null. And now with new implementation we are not getting any such error instead we are getting following.
```
{
  "data": {},
  "errors": [
    {
      "message": "Internal server error",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
``` 

Upon debugging we identified that with new graphql-jit implementation via gateway option, compliedQuery is resulting into an error during execution but that error is getting suppressed.

Please let me know if there is any resolution to the above problem.

### Link to Reproduction

https://codesandbox.io/p/sandbox/funny-haibt-s4r82s?file=%2Fsrc%2Findex.ts%3A34%2C14

**Comment by glasser** [comment]
Is this a different issue from #7773?

**Comment by hiteshbal91dp** [comment]
Got it @glasser it seems to be same issue.
