### ISSUE TITLE
TypeSafe Custom GQLError

### ISSUE THREAD

**Issue by alessdiimperio** [apollographql/apollo-server#7777]
- Some features can be built as plugins.

  We encourage exploring the plugin API prior to opening a feature request:

  https://www.apollographql.com/docs/apollo-server/integrations/plugins/

  In the event that the plugin API doesn't allow you to build a feature, it
  may be that expanding the plugin API *itself* is the best place for the
  feature to be introduced! Consider this flexible solution when opening a
  new feature request since it also unlocks new opportunities.

- Prior to opening a feature request, please search for existing requests.

  If you find an existing feature that matches your needs, use the 👍 emote
  to show your support for it. If the specifics of your use case are not
  covered in the existing feature request but the idea seems similar enough,
  please take the time to *add new conversation* which helps the feature's
  design evolve.

- If you do not find any other existing requests for the feature you desire,
  you should open a new feature request. Please take the time to help us
  understand your use-case as precisely as possible. Be sure to demonstrate
  that you've evaluated existing features and found them unsuitable and were
  unable to implement the functionality with the plugin API.

  Be flexible in your design and consider slight variations which might
  necessitate a specific API design.  We also hope you'll be willing to engage
  in the on-going design discussion prior to opening a pull-request.

GraphQL is great for type safety but errors are generic GraphQL errors even if subclassing a custom error it spits out a non typesafe payload, why can't errors have a __typename and be typesafe ? 🤷

**Comment by glasser** [comment]
This sounds like a question about GraphQL, not Apollo Server.

The [GraphQL spec](https://spec.graphql.org/draft/#sec-Errors.Error-Result-Format) specifies the fields message, location, path, and extensions for errors, and discourages the addition of more top-level entries.

That said, GraphQL-level errors aren't the only way to represent erroneous behavior in your graph. If an error is "expected" and should be handled explicitly by your client, it often is better to represent them explicitly in your schema. A common approach is to have fields return a `union` type that contains both a "successful result" type and one or more error types, which can be differentiated via `__typename` as you suggest. It's common to use GraphQL-level errors more for "unexpected" issues (eg, schema errors for business logic issues, GraphQL errors for low-level issues).
