### ISSUE TITLE
support for fastify version 4

### ISSUE THREAD

**Issue by Abdel-Monaam-Aouini** [apollographql/apollo-server#7788]
### Issue Description

https://github.com/fastify/fastify/issues/4168

![image](https://github.com/apollographql/apollo-server/assets/52112750/938385d8-ba87-48d0-ba89-b2e9385d0f49)

### Link to Reproduction

https://github.com/fastify/fastify/issues/4168

**Comment by glasser** [comment]
Apollo Server v4 supports Fastify v4 via the [`@as-integrations/fastify`](https://www.npmjs.com/package/@as-integrations/fastify) package.
