### ISSUE TITLE
How to do "context stitching" to share the current user across microservices?

### ISSUE THREAD

**Issue by booboothefool** [apollographql/apollo-server#780]
I currently have an Auth microservice where I can log a user in and get the current user via context:
```
export async function context(headers, secrets) {
  const user = await getUser(headers.authorization, secrets, mongo);
  return {
    headers,
    secrets,
    user,  // <= here
  };
}
```

I have a Gateway, where I do schema stitching:

Gateway = Auth Schema + Chat Schema

How do I do "context stitching" or share that context with the current user across microservices?

For example I can do: Auth: mutation login => query currentUser
But I cannot do: Gateway: mutation login => query currentUser

The login works, but now when I try to query currentUser, it returns null because the context with the current user was moved to the Gateway instead of Auth, if that makes sense.

So Gateway provides the context and Auth provides the schema, where the Auth schema does not have access to the Gateway context.

Am I even approaching auth correctly? An easier way to do this would be to get rid of the Auth microservice entirely, and just handle all auth functionality in the Gateway.

Thanks!
___
EDIT: Actually, it seems to apply the context correctly, but it's losing the headers which is why it can't find a user (checks Authorization header for Bearer token). This kind of makes sense because the request is going from client => Gateway -> Auth now instead of client => Auth, so the headers get lost when it's time to run query currentUser. Any ideas?
___
EDIT: For now I was able to move the query currentUser from Auth to Gateway. This is just a workaround and doesn't really solve the problem (Auth still doesn't get the context/headers). I still need some way to check that a user is actually logged in from Chat. Perrhaps I just need some Express middleware or an Apollo Link to handle auth upon a request to the Gateway?
___
EDIT: Apollo Link with `setContext` works. 🎉

**Comment by JacksonKearl** [comment]
Looks like you got this working with Apollo Link!
