### ISSUE TITLE
Elasticache cluster - CROSSLOT Keys in request don't hash to the same slot

### ISSUE THREAD

**Issue by chandank-nu** [apollographql/apollo-server#7802]
### Issue Description

We're using AWS elasticache cluster redis for GQL response caching which was working fine with V3 server but after migrating to V4 we started getting error "CROSSLOT Keys in request don't hash to the same slot"

### Link to Reproduction

N/A

**Comment by robertzlatarski** [comment]
I am getting this error as well: `Error writing from RESTDataSource to cache: ReplyError: CROSSSLOT Keys in request don't hash to the same slot`. Have you managed to resolve it?

**Comment by robertzlatarski** [comment]
I have found the problem: using `KeyvRedis` without specifying `useRedisSets: false`.
