### ISSUE TITLE
Update `@koa/cors` dependency for AS3 (or why we don't intend to)

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/apollo-server#7816]
### Issue Description

This issue exists for information discovery purposes.

Apollo Server 3 depends on `@koa/cors@4` which just [published a major version with a CVE](https://github.com/koajs/cors/security/advisories/GHSA-qxrj-hx23-xp82). Unfortunately, `@koa/cors@5` drops support for Node 12, which AS3 supports, so this is a breaking change for us.

Additionally, this issue has been mitigated for all Apollo Server 3 versions based on our usage of the package, so this is not a concern for our users.

If you're here due to a security scanner report, we recommend either configuring your tool to filter this vuln or updating to AS4.

### Link to Reproduction

n/a

**Comment by dan753722** [comment]
Thank you @trevor-scheer
