### ISSUE TITLE
how to get ctx from graphqlKoa in resolve

### ISSUE THREAD

**Issue by leinue** [apollographql/apollo-server#782]
``` javascript
import { graphqlKoa, graphiqlKoa } from 'apollo-server-koa';
router.post('/graphql', koaBody(), graphqlKoa({ schema: schemas.UserSchema, formatError }));
```

i want to get ctx using following method:

``` javascript
async resolve (root, params, options, ctx) {}
```

how can i do that?

**Comment by n1ru4l** [comment]
Is resolve a resolver inside your schema? 
I asume that you are using `graphql-tools`, therefore https://www.apollographql.com/docs/graphql-tools/resolvers.html#Resolver-function-signature should be relevant to you.

**Comment by leinue** [comment]
@n1ru4l maybe not

**Comment by leinue** [comment]
i have solved this fucking problem with a fucking strange methods:

``` javascript
router.post('/graphql', koaBody(), (ctx, next) => graphqlKoa({ schema: schemas.EmailSchema, formatError, context: ctx })(ctx, next));
```

**Comment by n1ru4l** [comment]
Oh, I did not know you mean the koa context object 😅
Glad you figured it out!
