### ISSUE TITLE
Error: ApolloServer<BaseContext>' is not assignable to type 'ApolloServer<ExpressContext>

### ISSUE THREAD

**Issue by simpyparveen** [apollographql/apollo-server#7827]
### Issue Description

Type 'Promise<{ my_apolloServer: ApolloServer<BaseContext>; my_httpServer: Server<typeof IncomingMessage, typeof ServerResponse>; }>' is not assignable to type 'Promise<{ apolloServer: ApolloServer<ExpressContext>; httpServer: Server<typeof IncomingMessage, typeof ServerResponse>; }>'.
  Type '{ my_apolloServer: ApolloServer<BaseContext>; my_httpServer: http.Server<typeof http.IncomingMessage, typeof http.ServerResponse>; }' is not assignable to type '{ my_apolloServer: ApolloServer<ExpressContext>; my_httpServer: Server<typeof IncomingMessage, typeof ServerResponse>; }'.
    Types of property 'my_apolloServer' are incompatible.
      Type 'ApolloServer<BaseContext>' is not assignable to type 'ApolloServer<ExpressContext>'.
        Type 'BaseContext' is missing the following properties from type 'ExpressContext': req, rests(2322)
const my_server_instance: Promise<{
    my_apolloServer: ApolloServer<ExpressContext>;
    my_httpServer: http.Server;
}>
I wanted to upgrade Apolloserver from ver3 to ver 4. Following documentation:

Two types in apollo-server-express now have more explicit names exported from @apollo/server/express4. GetMiddlewareOptions is now ExpressMiddlewareOptions and ExpressContext is now ExpressContextFunctionArgument. Ref: https://www.apollographql.com/docs/apollo-server/migration/

### Link to Reproduction

https://www.apollographql.com/docs/apollo-server/migration/

**Comment by trevor-scheer** [comment]
It looks like your types are incompatible based on the error:
```
Type 'Promise<{ my_apolloServer: ApolloServer; my_httpServer: Server<typeof IncomingMessage, typeof ServerResponse>; }>' is not assignable to type 'Promise<{ apolloServer: ApolloServer; httpServer: Server<typeof IncomingMessage, typeof ServerResponse>; }>'.
```
The `my_` prefix you're using is incompatible. Can you provide a reproduction or a code snippet at the very least?

**Comment by simpyparveen** [comment]
@trevor-scheer I added those pre-fixes purposefully when i was posting here, those do not exist in the code.

I have tried to to use the type any everywhere, just like a hack to get through this. But I am not happy with it.

I stumbled into a gateway problem, later https://github.com/apollographql/apollo-server/issues/7828
