### ISSUE TITLE
callback function for onSchemaLoadOrUpdate when upgrading from AS v3 to AS v4

### ISSUE THREAD

**Issue by simpyparveen** [apollographql/apollo-server#7828]
### Issue Description

I have a gateway defined as follows:

```
 const gateway: GraphQLService = {
        load: async () => (await {
            schema: server.systemSchema,
            executor: (args) => execute({
                ...args,
                schema: server.systemSchema,
                contextValue: args.context,
                variableValues: args.request.variables
            })
        } as GraphQLServiceConfig),
        stop: async () => {},
        onSchemaChange: (callback: SchemaChangeCallback) => {
            server.updateSchema = callback;
            return () => {};
        }
    };
```
    
    **What will be the equivalent gateway in AS v4 ??**
    
```
    I made an attempt to do:
    const gateway: GatewayInterface = {
        load: async () => (await {
            schema: server.systemSchema,
            executor: (args) => execute({
                ...args,
                schema: server.systemSchema,
                contextValue: args.context,
                variableValues: args.request.variables
            })
        } as GatewayLoadResult),
        stop: async () => {},
        onSchemaLoadOrUpdate (callback) {
            callback({ apiSchema: schema } as any);
            return () => {};
        }
    };
   
```
    But i get an error thrown when i update the server.  Potentially because I remove the line `server.updateSchema = callback;`. How should I perform server.updateSchema in modified gateway ???
    
    Need aa solution.
    
    
    
    

### Link to Reproduction

https://www.apollographql.com/docs/apollo-server/migration/#executor

**Comment by trevor-scheer** [comment]
Can you provide more details on the error? As far as I can tell, `schema` is undefined in the `onSchemaLoadOrUpdate` function, but there is a fair amount of context missing from the code so I can't be sure of much.

I can really only be more helpful if you provide a reproduction with detailed instructions on how to trigger the error. Happy to reopen this with a reproduction.

**Comment by simpyparveen** [comment]
@trevor-scheer 
https://codesandbox.io/p/devbox/happy-lalande-cyzdyz?file=%2Fsrc%2Findex.ts%3A74%2C26

I tried to add as much as possible. What else is missing
