### ISSUE TITLE
Query validation fails for GraphQLInputObjectType variables

### ISSUE THREAD

**Issue by Dhude** [apollographql/apollo-server#784]
Query validation fails if you try to pass an InputObjectType as a variable.

Given the types in schema: 

```graphql
  type RootQuery {
    TestQuery(input: TestInput!): Test
  }

  input TestInput {
    a: String
  }

  type Test {
    a: String
  }

```

Querying works just fine:

<img width="970" alt="screen shot 2018-01-24 at 8 01 26" src="https://user-images.githubusercontent.com/11332065/35316952-f99e029e-00dc-11e8-89a1-9b0ac04b433f.png">

Passing input type as a variable to the query does not work:

<img width="973" alt="screen shot 2018-01-24 at 8 01 00" src="https://user-images.githubusercontent.com/11332065/35316940-eebb9e40-00dc-11e8-9f12-135ecfa1686f.png">

I've traced this down a bit.  Validation breaks in [graphql-js validation Rule VariablesInAllowedPosition](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/VariablesInAllowedPosition.js#L59) whilst checking for type equivalence with [graphql-js utilities/typeComparators: isTypeSubTypeOf](https://github.com/graphql/graphql-js/blob/master/src/utilities/typeComparators.js#L52). 
There the `superType` and `maybeSubType` are checked for equivalence only by reference (`superType === maybeSubType`). From what I noticed the two types are copies of one another, but not the same object so the referential check fails.

I'm not sure if this is by design (would seem weird if it were), and if not if this is a bug in apollo or graphql-js.

**Comment by JacksonKearl** [comment]
Looks like the error here is that you declared the input var to be a `TestInput`, but it needs to be a `TestInput!` to match the schema. Testing this and it seems to be working with `TestInput!`, this was my setup:
index.js:
```js
const typeDefs = gql`
  type Query {
    TestQuery(input: TestInput!): Test
  }

  input TestInput {
    a: String
  }

  type Test {
    a: String
  }
`;

const resolvers = {
  Query: {
    TestQuery: (a, b, c) => {
      return { a: b.input.a };
    }
  }
};

// Set up Apollo Server
const server = new ApolloServer({
  typeDefs,
  resolvers
});
```

query:
```gql
query withVar($input: TestInput!) {
   TestQuery( input: $input) {
    a
  }
}
```

input:
```json
{ "input": {"a": "hello :)"}}
```

response:
```json
{
  "data": {
    "TestQuery": {
      "a": "hello :)"
    }
  }
}
```
