### ISSUE TITLE
Documentation and dynamic cache control feature of Apollo leverages incompatible GraphQl type interface.

### ISSUE THREAD

**Issue by corbin-mosher** [apollographql/apollo-server#7845]
### Issue Description

The [ApolloServer documentation](https://www.apollographql.com/docs/apollo-server/performance/caching/#in-your-resolvers-dynamic) provides an example of setting cache-control information for a resolver dynamically. This example works in code, but it has a TypeScript error.

```
Property cacheControl does not exist on type GraphQLResolveInfo.
```

The `info` object leverages the type of `GraphQLResolveInfo`. This type does not have a `cacheControl` field defined on it.

I am not sure if this is an error with the `graphql` package and its types, or if its something `@apollo/server` and other third party libraries like `typed-graphql` are just expanding the existing GraphQl object with.

I was hoping a maintainer of `@apollo/server` would be familiar with how this field works and were the hang up is. Is it safe to follow the documentation's example? Should I just be altering the GraphQl libraries `GraphQLResolveInfo` type?

### Link to Reproduction

[Reproduction link](https://codesandbox.io/p/devbox/3w73gz?file=%2Fsrc%2Findex.ts%3A12%2C5&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltevn1ws00063b6eedqp44ol%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltevn1ws00023b6epbe9bcpy%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltevn1ws00043b6e7thrh9dt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltevn1ws00053b6enlpe2r5i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60.94064440741783%252C39.05935559258217%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltevn1ws00023b6epbe9bcpy%2522%253A%257B%2522id%2522%253A%2522cltevn1ws00023b6epbe9bcpy%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltevupml00023b6evboaapys%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltevupml00023b6evboaapys%2522%257D%252C%2522cltevn1ws00053b6enlpe2r5i%2522%253A%257B%2522id%2522%253A%2522cltevn1ws00053b6enlpe2r5i%2522%252C%2522activeTabId%2522%253A%2522cltevnfkq009s3b6e99iywdxu%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522port%2522%253A1234%252C%2522id%2522%253A%2522cltevnfkq009s3b6e99iywdxu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cltevn1ws00043b6e7thrh9dt%2522%253A%257B%2522id%2522%253A%2522cltevn1ws00043b6e7thrh9dt%2522%252C%2522activeTabId%2522%253A%2522cltevnavp00863b6esrdct47y%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltevn1ws00033b6ezfmgzmb5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltevn28e000bdcf82uk83e6w%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522cltevnavp00863b6esrdct47y%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Reproduction Steps

Just launch the repro link and view the fact the type information does not exist for `cacheControl`.

![Screen Recording 2024-03-05 at 1 38 49 PM](https://github.com/apollographql/apollo-server/assets/91292058/51969c0b-06e6-4bb1-a7e0-c39b354e3a25)

**Comment by corbin-mosher** [comment]
Follow up on this. We dug some more and uncovered this [section of the documentation](https://www.apollographql.com/docs/apollo-server/migration/#apollocache-control-types) which mentions:

> Instead, @apollo/cache-control-types provides a GraphQLResolveInfoWithCacheControl interface that you can cast info to (if you don't want run-time validation), or if you do want runtime validation, you can use the maybeCacheControlFromInfo and cacheControlFromInfo functions.

```
import { cacheControlFromInfo } from '@apollo/cache-control-types';

// ...
  someField(parent, args, context, info) {
    cacheControlFromInfo(info).setCacheHint({ maxAge: 100 });
  }
```

So I guess my request would be that the other locations in the Apollo documentation that mention `info.cacheControl` could hopefully be updated to instead use examples with `cacheControlFromInfo`.

If the docs are open source, I could also propose a PR that does that if needed.

**Comment by glasser** [comment]
Good catch — the TS-specific improvements from AS4 didn't make it to that page. If you'd like to submit a PR, the file is https://github.com/apollographql/apollo-server/blob/main/docs/source/performance/caching.md

**Comment by corbin-mosher** [comment]
> Good catch — the TS-specific improvements from AS4 didn't make it to that page. If you'd like to submit a PR, the file is https://github.com/apollographql/apollo-server/blob/main/docs/source/performance/caching.md

Created the following docs PR,

https://github.com/apollographql/apollo-server/pull/7848
