### ISSUE TITLE
Redirect in Context

### ISSUE THREAD

**Issue by DavDeDev** [apollographql/apollo-server#7870]
### Issue Description

Hi!
I would like to redirect to `/auth/login` any time a GraphQl endpoint is called without authorization?
- Route handler - `api/graphql/route.ts`:
```ts
import { ContextValue, apolloServer } from "@/apollo-server/server";
import { auth } from "@/auth";
import db from "@/lib/prisma-client";
import { startServerAndCreateNextHandler } from "@as-integrations/next";
import { redirect } from 'next/navigation';
import { permanentRedirect } from 'next/navigation'

const handler = startServerAndCreateNextHandler(apolloServer, {
  context: async (req): Promise<ContextValue> => {
    const session = await auth();


    console.log("session in context", session);
    console.log("request in context", req.headers.authorization)
    if (!session) {
      console.log("🔴🔴🔴🔴🔴🔴🔴No Permission to run GraphQL Endpoints, be redirected to auth login")
       redirect("/auth/login");
    }
    const user = session.user;
    return {
      user,
      dataSources: {
        prisma: await db.$connect(),
      },
    };
  },

});

export { handler as GET, handler as POST };

```
- output:
![image](https://github.com/apollographql/apollo-server/assets/104097735/bf53323a-a87c-442b-8502-e77d68267157)
![image](https://github.com/apollographql/apollo-server/assets/104097735/889562c9-15af-4eb8-80e5-2975e6c190b0)

This code is pretty much the same as the one provided in [you example](https://www.apollographql.com/docs/apollo-server/security/authentication/#api-wide-authorization), but instead of throwing an Error, I would like to redirect, is it possible?

### Link to Reproduction

https://www.apollographql.com/docs/apollo-server/security/authentication/#api-wide-authorization

**Comment by glasser** [comment]
It seems like this would be best handled at the HTTP level instead of from within your Apollo Server context function? Then whatever auth you set up with your `auth()` function can just be read from within your context function. I'm not enough of a NextJS expert to know how to do that in Next — maybe file this as an issue in https://github.com/apollo-server-integrations/apollo-server-integration-next instead?

**Comment by glasser** [comment]
Although it might in fact work to do what you're trying: the code block you link shows how your error can contain

```
        extensions: {
          code: 'UNAUTHENTICATED',
          http: { status: 401 },
        },
```

to set the HTTP status code to 401, so you probably can set it to 301 or 302 and also set the `location` header ([using the `headers` key)[https://www.apollographql.com/docs/apollo-server/data/errors#setting-http-status-code-and-headers]) to the URL you want to redirect to.
