### ISSUE TITLE
Curly brackets inside string are not properly parsed from variables input in sandbox

### ISSUE THREAD

**Issue by super16** [apollographql/apollo-server#7877]
### Issue Description

Apollo server sandbox can't parse curly brackets inside string from variables input field. When requested from external client, curly brackets are parsed correctly, so I guess how the input is parsed causing the bug.

### Link to Reproduction

https://github.com/super16/apollo-sandbox-bug-reproduction

### Reproduction Steps

Minimal reproduction example with echo server from repo with reproduction.

```graphql
query ExampleQuery($input: String) {
  hello(input: $input)
}
```

## Variables

```json
{
  "input": "{{foo}}"
}
```

## Response

```json
{
  "data": {
    "hello": ""
  }
}
```

## Expected response

```json
{
  "data": {
    "hello": "{{foo}}"
  }
}
```

**Comment by glasser** [comment]
I think this is the [environment variables](https://www.apollographql.com/docs/graphos/explorer/connecting-authenticating/#environment-variables) feature of Explorer, though I'm not sure if there's a way to turn it off (or restrict it only to defined environment variables).

**Comment by super16** [comment]
Thank you, @glasser, for the reference to the documentation, I haven't seen it.

The workaround for reproduction case would be to add the following JSON to Environment variables section at Explorer's Settings tab

```json
{
  "foo": "{{foo}}"
}
```
