### ISSUE TITLE
If the content type is json, data is not going to WebAPI Post action in Angular using Visual Studio IDE

### ISSUE THREAD

**Issue by ShaileshBhatNP** [apollographql/apollo-server#789]
I'm using **Visual Studio IDE** for doing Angular2 project. Now the problem is, if the content-type is json, below code does't able to call WebAPI Post Action. Whereas, If the content-type is **x-www-form-urlencoded**, then able to call post action. But the data in WebAPI Post action parameter is null as shown here in image.

`postEmployee(emp: Employee) {`
        `var body = JSON.stringify(emp);`
        `var headerOptions = new Headers({ 'Content-Type': 'application/x-www-form-urlencoded'});`
        `var requestOptions = new RequestOptions({ method: RequestMethod.Post, headers: headerOptions });`
        `return this.http.post('http://localhost:64925/api/Employee/PostEmployee', body, requestOptions).map(x => x.json());`
   `}`

after posting the data, which is null showing below..
![code](https://user-images.githubusercontent.com/29448807/35325230-1d9e5482-0119-11e8-9c77-01257b8ddf90.png)
So, for this problem I want to send json data from client side. But, if the content-type is json like below, it is not going to Post action method of WebAPI

`postEmployee(emp: Employee) {`
        `var body = JSON.stringify(emp);`
        `var headerOptions = new Headers({ 'Content-Type': 'application/json' });`
        `var requestOptions = new RequestOptions({ method: RequestMethod.Post, headers: headerOptions });`
        `return this.http.post('http://localhost:64925/api/Employee/PostEmployee', body, requestOptions).map(x => x.json());`
    `}`

**Web.config** is 
    
    <httpProtocol>
      <customHeaders>
        <add name="Access-Control-Allow-Origin" value="*" />
         
        <add name="Access-Control-Allow-Methods"
             value="GET, POST, PUT, DELETE, OPTIONS" />
      </customHeaders>
    </httpProtocol>

Any one knows the solution for the above stated problem in **Visual Studio IDE**..?Thanks in Advance..
[Demo Project link from you tube](https://www.google.co.in/search?q=Angular+4+CRUD+With+Web+API&dcr=0&source=lnms&tbm=vid&sa=X&ved=0ahUKEwis0oelj_DYAhVCF5QKHfS5ABIQ_AUICigB&biw=1264&bih=871). In this project, they are using Visual Studio Code..But I need to use same code in Visual Studio IDE.

**Comment by abernix** [comment]
I realize it's been quite some time since you opened this, but if you haven't already figured this out, I'd recommend taking this question to the [Apollo community on Spectrum.chat](https://spectrum.chat/apollo) to discuss it further.  Thanks!
