### ISSUE TITLE
A normal Map doesn't satisfy the conditions for KeyValueCache

### ISSUE THREAD

**Issue by abir-taheer** [apollographql/apollo-server#7990]
### Issue Description

The type definition for KeyValueCache:
```typescript
export interface KeyValueCache<V = string> {
  get(key: string): Promise<V | undefined>;
  set(key: string, value: V, options?: KeyValueCacheSetOptions): Promise<void>;
  delete(key: string): Promise<boolean | void>;
}
```

Are all implemented in the JS `Map` object but a Map doesn't satisfy the requirements for a KV-Cache since a map does not return promises.

For instance:

```typescript
const cacheMap = new Map(Object.entries(persistedDocuments));

export const graphql_server = new ApolloServer({
  schema,
  persistedQueries: {
    
    /*
     * There is a typescript error on the following line because:
     * TS2322: Type Map<string, string> is not assignable to type KeyValueCache<string>
     * The types returned by get(...) are incompatible between these types.
     * Type string | undefined is not assignable to type Promise<string | undefined>
    */
    cache: cacheMap,
  },
});
```

However if the map is wrapped in an like so:
```typescript
const KVC: KeyValueCache<string> = {
  async get(key: string) {
    return cacheMap.get(key);
  },
  async set(key: string, value: string) {
    cacheMap.set(key, value);
  },
  async delete(key: string) {
    return cacheMap.delete(key);
  },
};
```

then typescript will accept it as a valid KeyValueCache. 

We should allow for the KeyValueCache to return non-promise values. Is there any reason against it / anything it would break in the code? Otherwise I think it might be appropriate for me to create a pull request doing so.

### Link to Reproduction

See Above:

**Comment by glasser** [comment]
Interfaces are simpler if they always return the same type than if they sometimes return one type and sometimes return another.

A standard Map is not a great choice for a cache backing these features, as using it will generally leak memory as it grows indefinitely. I don't think changing our type definitions to make it easier to add memory leaks to your server would be a good thing! (We already went the other way by actively changing the default in-memory cache from unbounded to bounded in AS v4.)

**Comment by abir-taheer** [comment]
Hi, my use-case had to do with pre-hashed persisted queries with a gateway preventing unrecognized queries so there's no risk of the memory DoS attack -- all the hashes are generated at build time.

However, I understand your point of view -- I won't press this further.
