### ISSUE TITLE
apollo-server-express graphiql doesn't support markdown and multi-line descriptions

### ISSUE THREAD

**Issue by sethyuan** [apollographql/apollo-server#805]
I'm using graphql 0.12.x and graphql-tools 0.22.x, but still can't have markdown rendered correctly in descriptions as described in the graphql-tools documentation.

![pic](https://user-images.githubusercontent.com/3410293/35839677-a79f23d8-0b2c-11e8-97fb-917a1203f65c.jpg)

**Comment by gavinwilliams** [comment]
@sethyuan what does your markdown look like in your code? What are you expecting as an output? My markdown is displaying fine.

**Comment by abernix** [comment]
@sethyuan Can you provide a simple reproduction of your problem?

**Comment by abernix** [comment]
We believe this is resolved in Apollo Server 2.x which utilizes `graphql-playground` and updated `graphql` dependencies which support more modern GraphQL SDL.

Thanks for reporting this originally!
