### ISSUE TITLE
Update graphql dependency to 0.13

### ISSUE THREAD

**Issue by erayhanoglu** [apollographql/apollo-server#812]
We cannot use latest graphql with apollo server. When will you update graphql dependency from 0.11.7 to latest version? 0.13.0 is now in npm repo.

**Comment by dobesv** [comment]
There is a breaking change in the new version(s) of graphql, execute might return a regular value instead of a promise.

So with apollo you get an error like this:

```
TypeError: graphql_1.execute(...).then is not a function
at doRunQuery (.../node_modules/apollo-server-core/dist/runQuery.js:98:156)
```

**Comment by antstanley** [comment]
So graphql v0.13.0 works for me after a bit of work but the error messages were a bit nonsensical. Just adding my 2 cents to help others. 

My app wasn't working, but thanks to this issue report I reverted to 0.11.7, which then gave me a useful error and I was able to debug my app. I then rolled forward again to 0.13.0 and it worked. I did get the below warning messages in 0.13.0 that I didn't get in 0.11.7

```
(node:63446) [DEP0016] DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
(node:63446) [DEP0016] DeprecationWarning: 'root' is deprecated, use 'global'
(node:63446) [DEP0016] DeprecationWarning: _writeableState.buffer is deprecated, use _writeableState.getBuffer instead
```

This is using Node 8.9.4. Once I had debugged my app in 0.11.7 and rolled forward to 0.13.0 these messages disappeared.

**Comment by sbrichardson** [comment]
Slightly curious how Apollo Engine and Apollo Client move forward with support (graphql 12+ etc) but this library doesn't update. Is apollo-server-express not the recommend/popular server any longer? 

More just curious if users have transitioned to a newer server base I should be aware of, not trying to complain at all!

I also haven't noticed any issues yet by staying on 0.11.7 but didn't want to dive in if this was about to be updated properly by the Apollo team. Otherwise I can debug and submit a pull request.

**Comment by stubailo** [comment]
@sbrichardson hey thanks for the comment -

Actually we updated to 0.12 already, just didn't do a good job with the messaging around it. This week @abernix and I are going to go through and make sure to merge all the PRs and close some old issues.

We're planning on putting a lot more time into the server moving forward, and would really appreciate some help! We'll try to handle the update to 0.13 ASAP, but if you want to go through and help us review some issues or PRs that would be much appreciated!

**Comment by vladshcherbin** [comment]
@stubailo hey, any news with this one or any chance to release a new version of `apollo-server-core` with 0.13 support?

It feels bad when every time you add a package you see this:

![screen shot 2018-03-23 at 20 09 34](https://user-images.githubusercontent.com/6711845/37843524-381f6dd8-2ed6-11e8-9ce7-d7e56496c294.png)

**Comment by abernix** [comment]
@vladshcherbin Yes, this is coming on Monday!

**Comment by vladshcherbin** [comment]
@abernix great news, thank you! :)

**Comment by transcranial** [comment]
Thanks for updating. Peer deps still outdated in downstream packages, though (apollo-cache-control, apollo-tracing, graphql-extensions).

**Comment by vladshcherbin** [comment]
Lets track the progress in one place:

- https://github.com/apollographql/apollo-cache-control-js/pull/19
- https://github.com/apollographql/apollo-tracing-js/pull/10
- https://github.com/apollographql/graphql-extensions/pull/8

**Comment by abernix** [comment]
@transcranial That's correct.

For those that didn't notice already (as the observant @transcranial has! 😄) the `apollo-server-*` packages have been updated with a `peerDependencies` range supporting `graphql@0.13.x`.  This are in place on the `apollo-server-*@1.3.3` packages.

The other packages will be updated and published tomorrow morning after I've completed testing on them!

**Comment by abernix** [comment]
Thanks for linking to those @vladshcherbin.

And yes, I thought it made sense to leave this issue open until all those packages were updated, since the warnings will still persist in one form or other (even though the warnings don't stem from `apollo-server-*` packages anymore) until all those dependencies were done.

**Comment by abernix** [comment]
As of `apollo-server-*@1.3.3` (released this past Monday, as noted in https://github.com/apollographql/apollo-server/issues/812#issuecomment-376260520 above), the peer dependency range for `graphql` has been expanded to include `graphql@0.13.x` (including the latest `graphql@0.13.2` which came out a couple weeks ago).

Additionally, as a stretch goal of this issue, the following transitive dependencies have also been updated, hopefully quelling all peer dependency warnings for `graphql`.  It's worth noting that despite the previously-issued peer dependency warnings for `graphql`, the `0.13.x` package has been known to be completely functional in all these packages, but hopefully this instills a bit more confidence:

* [`apollo-tracing`](//npm.im/apollo-tracing): `0.1.4` (via apollographql/apollo-tracing-js#10)
* [`apollo-cache-control`](//npm.im/apollo-cache-control): `0.0.10` (via apollographql/apollo-cache-control-js#19)
* [`graphql-extensions`](//npm.im/graphql-extensions): `0.0.9` (via apollographql/graphql-extensions#8)
