### ISSUE TITLE
Comment in code is misleading or code is wrong for parsing query if its already AST

### ISSUE THREAD

**Issue by jardakotesovec** [apollographql/apollo-server#833]
This is probably small catch - but maybe useful. Noticed that in [here](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/runQuery.ts#L153) comment says *if query is already an AST, don't parse or validate*, but in fact it just skip the parsing step.

In our case it works as we want. Because we just want to do parse step outside of runHttpQuery to be able to read mutation name from it.  But wanted to bring it up to make sure if it works as intended and the validation steps always happen there also in future.

**Comment by Piefayth** [comment]
See also: #722 - Our use case prefers it works as described, not as written.

**Comment by abernix** [comment]
We're working on providing techniques to control the exact behavior, which has been facilitated by the work done in #1795.  For what it's worth, the confusing comment you'd referred to:

https://github.com/apollographql/apollo-server/blob/5b901204ab216c1c10c76a3d41c70686e3a675e7/packages/apollo-server-core/src/runQuery.ts#L153

...has been removed!

**Comment by abernix** [comment]
We're working on providing techniques to control the exact behavior, which has been facilitated by the work done in #1795.

The confusing comment you'd referred to:

https://github.com/apollographql/apollo-server/blob/5b901204ab216c1c10c76a3d41c70686e3a675e7/packages/apollo-server-core/src/runQuery.ts#L153

...has been removed, so I'll close this.
