### ISSUE TITLE
query with default values in apollo-server-express

### ISSUE THREAD

**Issue by franz-geiser** [apollographql/apollo-server#860]
Hi,
default values in query seems not working.
typeDefs:
```
type Query {
  cars(limit: Int = 10): [Car]
}
```
When i query from the graphiql : 
```
{
  cars() {
    name
  }
}
```
i get this error:
```
{
  "errors": [
    {
      "message": "Syntax Error: Expected Name, found )",
      "locations": [
        {
          "line": 2,
          "column": 17
        }
      ]
    }
  ]
}
```
graphQL definition: http://graphql.org/learn/queries/#default-variables
"When default values are provided for all variables, you can call the query without passing any variables. "

Am i making some mistake?
Thanks :-)

**Comment by gavinwilliams** [comment]
Brackets are not required if you do not pass an argument to a Query.

‘’’
{
  cars {
    name
  }
}
‘’’

**Comment by gavinwilliams** [comment]
Brackets are not required if you do not pass an argument to a Query.

```
{
cars {
name
}
}
```

**Comment by franz-geiser** [comment]
Yes, you are right. 

```
{
  cars {
    name
  }
}
```

Works with the default value.

Thank you!
