### ISSUE TITLE
Type level directives don't seem to be working

### ISSUE THREAD

**Issue by ryall** [apollographql/apollo-server#862]
Given the schema segment
```gql
directive @special on SCHEMA
directive @specialField on FIELD_DEFINITION

type Entity @special {
  id: ID!
  something: String @specialField 
}
```

Directive resolvers are implemented for both directives, however `@special` never fires. I have tried various directive types other than `SCHEMA` but to the same result. 

`@specialField` works without any problems.

**Comment by abernix** [comment]
@ryall 	If this is still an issue for you, could you provide a link to a runnable reproduction on an [CodeSandbox with Apollo Server](https://codesandbox.io/s/apollo-server)?

**Comment by ryall** [comment]
This was for version 1. Haven't tried this specifically in version 2 but I suspect it is fixed as directives seem to have been overhauled with it.
