### ISSUE TITLE
Re-Export out  GraphQLOptions in apollo-server-express

### ISSUE THREAD

**Issue by epicallan** [apollographql/apollo-server#863]
For those who would like to type check their graphql options in the [``graphqlExpress`` function](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-express/src/expressApollo.ts#L25), It would be good to have access to ``GraphQLOptions`` interface. I can submit a PR, thanks.

**Comment by stubailo** [comment]
Please submit a PR!
