### ISSUE TITLE
How to send errors and prevent data from null

### ISSUE THREAD

**Issue by gijo-varghese** [apollographql/apollo-server#872]
I have a query resolver like this:
```
page: (root, args) =>
      DB.page
        .findById(args.id)
        .then((result) => {
          if (result == null) throw Error(`Page not found for ${args.id}`);
          return result;
        })
        .catch((error) => {
          log.error('Error in page query.', error.message);
        }),
```
But when I execute the query, the result is:
```
{
  "data": {
    "page": null
  }
}
```
What I expect:
```
{
  "errors": [
    ...
  ]
}
```

**Comment by gijo-varghese** [comment]
ok. Found the solution from https://stackoverflow.com/questions/49247436/sending-errors-to-apollo-graphql/49247752#49247752

But the still the data would be `null`. Is this ok?

**Comment by abernix** [comment]
According to [the GraphQL specification](https://facebook.github.io/graphql/draft/#sec-Response-Format), if the error happened after execution has began, the `data` property must be included.  If no resolvers resulted in data, then that `data` must be `null`.

If you have any other questions or you're still having problems with this, feel free to ask in the [Apollo community on Spectrum.chat](https://spectrum.chat/apollo).  Thanks!
