### ISSUE TITLE
Azure functions apollo returns string, not JSON, should return real JSON

### ISSUE THREAD

**Issue by PhilAndrew** [apollographql/apollo-server#884]
In azureFunctionsApollo.js line 26:

I had to change from
`               body: gqlResponse,`
to
`               body: JSON.parse(gqlResponse),`

Then it worked correctly. Before this fix the problem was that a string was being returned and not real JSON.

```
    "apollo-cache-control": "0.0.9",
    "apollo-server-azure-functions": "^1.3.2",
    "apollo-server-core": "^1.3.2",

```

Pull request
https://github.com/apollographql/apollo-server/pull/885

**Comment by denisw** [comment]
I have the very same problem. This makes `apollo-server-azure-functions` unusable currently.

**Comment by PhilAndrew** [comment]
This pull request can be automatically merged by project collaborators

**Comment by sachduce** [comment]
Can you please share the code to write azure function, unable to access apollo server using azure functio

**Comment by abernix** [comment]
This should be fixed with https://github.com/apollographql/apollo-server/pull/753.  Thanks for raising this originally!
