### ISSUE TITLE
Error logged to console on resolver promise rejection

### ISSUE THREAD

**Issue by BRMC888** [apollographql/apollo-server#894]
I return a promise in my graphql resolvers, I resolve the promise when the query was successful - which works fine, but whenever I reject a promise, an un-mutable, seemingly un-handleable error is thrown in the server console.

For example, I use a mutation to handle a user Login, if the username does not exist in the db, I call reject with the message "User does not exist"

My console then looks like this:

> Error: User does not exist
    &nbsp;&nbsp;&nbsp;&nbsp;at asErrorInstance (/Users/..project../node_modules/graphql/execution/execute.js:545:43)
    &nbsp;&nbsp;&nbsp;&nbsp;at \<anonymous\>
    &nbsp;&nbsp;&nbsp;&nbsp;at process._tickCallback (internal/process/next_tick.js:188:7)

I expect to be able to reject Promises without this error being printed, or have a way to mute these promise rejection error messages

This is the line that prints the error message:
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/runQuery.ts#L80

This is a repo that demonstrates the problem I'm having:
https://github.com/BRMC888/graphql-error

Edit: Sorry I'm new to GitHub, I think that's the wrong label and now I can't figure out how to change it!

**Comment by Alex-PK** [comment]
It's not very well documented (or not documented at all. I only discovered it reading the source code), but this only happens if `NODE_ENV` is neither `production` nor `test` by default.

You can also pass `debug: false` in the server config to disable it.

**Comment by abernix** [comment]
Thank you for the reproduction you provided originally!  I know it's been a long time since you've reported this, but I suspect this has been fixed for quite some time now.  I can confirm, using the reproduction, that this no longer occurs on `apollo-server-express@2.4.2`.

Thanks again for reporting this!
