### ISSUE TITLE
Hapi example returns "GET query missing" 

### ISSUE THREAD

**Issue by attdona** [apollographql/apollo-server#895]
I'm just evaluating apollo-server Hapi plugin and the `/grapql` query returns:

    {"statusCode":400,"error":"Bad Request","message":"GET query missing."}

I've posted [here](https://github.com/attdona/agallo) the sample code that does not work for me:

Thanks for your support!
Attilio

**Comment by attdona** [comment]
As the error decription suggest my query was wrong. Using something like:

    http://localhost:3000/graphql?query={hello}

gives back the correct result.

I (**wrongly**) expected that the graphql endpoint were a GraphiQL UI.

Reading the [docs](https://www.apollographql.com/docs/apollo-server/graphiql.html#graphiqlHapi) GraphiQL can be enabled with 

    await server.register({
      plugin: graphiqlHapi,
      options: {
        path: '/graphiql',
        graphiqlOptions: {
          endpointURL: '/graphql',
        },
      },
    });

NOTE:  Respect to the docs I needed to substitute `register` property with `plugin` property (hapi version 17.2.3).

**Comment by abernix** [comment]
I'll close this since it seems to be resolved, but let us know if we can do anything to further improve the documentation!

**Comment by MuhammadRaheelFayyaz** [comment]
use playground: true,
`const server = new ApolloServer({
  introspection: true,
  playground: true,
  typeDefs,
  resolvers,
})
`

**Comment by BarretteBanner** [comment]
In case anyone is looking for the answer, I believe the answer is that you need to send a post request not a get request

**Comment by Tibz-Dankan** [comment]
I was facing the same issue and changing from get request to post request solved the problem as @BarretteBanner mentioned it
