### ISSUE TITLE
`npm -i --save apollo-server-hapi` results in warnings of missing peer dependencies.

### ISSUE THREAD

**Issue by ogrotten** [apollographql/apollo-server#896]
```
PS F:\Dev\js\hapi\geomap> npm --save i apollo-server-hapi
npm WARN apollo-server-core@1.3.2 requires a peer of graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-extensions@0.0.8 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-tracing@0.1.3 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-cache-control@0.0.9 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN hapi-ninja@0.4.1 No license field.

+ apollo-server-hapi@1.3.2
added 13 packages, removed 14 packages and updated 2 packages in 11.922s
PS F:\Dev\js\hapi\geomap> npm i --save graphql
```

None of the docs say anything about necessary side-installs. I did however `npm i --save graphql` and received the same cluster of messages.

Done today, so 
v 1.3.2

**Comment by NLincoln** [comment]
You can probably ignore those errors. 

Apollo specifies a strict version range for [graphql-js](https://github.com/graphql/graphql-js), which works great except when graphql-js releases an update 😅. In this case, graphql-js is on `0.13.x`, while `apollo-server` still expects `0.12.x`. However, this is [being worked on](https://github.com/apollographql/apollo-server/commit/d50b6b6fb2b10b972435acdb1c04f5c0c55e90b4#diff-8f5d18badbf08e310b349f6440cfa34f), so this issue will probably be released in the next version of `apollo-server`. 

All that aside, I think you can ignore these errors. I've been using `graphql@0.13.x` for some time now, and haven't encountered any problems.

**Comment by abernix** [comment]
This should be resolved.  Please see the comments in #812 for more information, and thanks for raising this issue originally!
