### ISSUE TITLE
Server doc links wrong

### ISSUE THREAD

**Issue by jonas-arkulpa** [apollographql/apollo-server#904]
The following links in the docs are wrong and redirect to a page not found page:

- Servers
- Features

Both link to https://www.apollographql.com/servers but should link to https://www.apollographql.com/server

![links-down](https://user-images.githubusercontent.com/17269256/37760237-5f3c9ef2-2db6-11e8-8443-f298fc052740.png)

I didn't find it on GitHub, otherwise I would've fixed it with a PR.
You can also just point me to the right repo if its public.

**Comment by jonas-arkulpa** [comment]
I'm closing the issue as it is fixed now.

**Comment by abernix** [comment]
Thanks for reporting this (and following up on it!).

Yes, this was in a private repository and it was fixed yesterday afternoon.  Good catch!
