### ISSUE TITLE
Trouble with graphql orderBy

### ISSUE THREAD

**Issue by kierah** [apollographql/apollo-server#913]
I have a query that works well unordered. 
```
query feedQuery {
  allPostsFromAllBlogs
  {
    id
    blogId
    title
    text
    likes
    createdAt
  }
}
```
I want to sort the results (of type [Post]). This is the query I'm using to do that:
```
query feedQuery {
  allPostsFromAllBlogs( orderBy: {field: createdAt, direction:DESC}) 
  {
    id
    blogId
    title
    text
    likes
    createdAt
  }
}
```
Which produces this output in graphiql:
```
{
  "errors": [
    {
      "message": "Unknown argument \"orderBy\" on field \"allPostsFromAllBlogs\" of type \"Query\".",
      "locations": [
        {
          "line": 2,
          "column": 25
        }
      ]
    }
  ]
}
```

I'm not sure what other information you would need to diagnose the problem, but I assume its a query syntax error. 

Why is it not recognizing orderBy? Is this the right place to ask this question?

**Comment by kierah** [comment]
I was told that apollo does not implement orderBy. So that answers that. Thank you.

**Comment by cyberbeast** [comment]
Well, it doesn't fall within the specifications of GraphQL to be concerned with ordering or other such operations. These operations are external to the GraphQL based representation of your resources (data). I would recommend that you implement _allPostsFromAllBlogs_ to accept a boolean/object type parameter which enforces this behavior within your resolver. The overall effect could be something along the lines of 

> Does my client require _allPostsFromAllBlogs_ in decreasing order? If YES, execute database query with orderBy set to "desc". If NO, execute database query without orderBy set to "desc".
