### ISSUE TITLE
apollo-server-hapi - multiple instances

### ISSUE THREAD

**Issue by MikeSchaap** [apollographql/apollo-server#931]
First off, thanks for all the time and effort you guys (and the community) put into developing Apollo! It's really easy to get started and it works great!

I'm just hitting a few bumps with my specific implementation and i'm just wondering if I miss interpreted the documentation and i'm doing it all wrong or if this is something that hasn't been tried before and documented.

When i'm trying to achieve is having 3 different GraphQL endpoints each with their own set of schemas. Why? Because we want to show a different Model for user type A, B & Admin. I know we can just return different objects back from the business layer and just keep the fields empty for user types which are not allowed to see it. But the company i'm working for doesn't want to expose any information about the models to user types which aren't allowed to see it. (So they don't allow to document each field and show which user type has access it).

This is why i want to run multiple (3 in this case) instances of GraphQL each with their own set of schemas (and different models per endpoint). I haven't found anything about this in the docs and when i tried to register the plugin in hapi.js multiple times it gave an error that the plugin was already registered. I managed to 'fix' this by adding the multiple: true variable to the plugin. But i was wondering if this is 'safe' to do? Will i run into conflicts when running multiple instances of GraphQL on the same hapi.js server?

Would love to hear from you guys.

Kind regards,

Mike

**Comment by tlbignerd** [comment]
I have to agree, setting the default to true would make more sense. It's certainly the standard for the other servers, where we can add graphql endpoints with different routes and options and not be required to configure a global setting that enables this functionality.

**Comment by robmcguinness** [comment]
Running into this same issue with `2.x`. Previously I was running a `/graphql` and `/mockql` endpoint from one server by running two hapi plugins with different configurations, resolvers and schemas. In `1.x`, I would override the plugin name to circumvent this issue:

```js
plugin: {
    name: 'mockql',
    register: graphqlHapi.register,
  },
```

In `2.x`, it doesn't seem possible to override the hapi plugin defaults using `applyMiddleware` without changes to `apollo-server-hapi/ApolloServer` as well.

**Comment by jpgarcia** [comment]
@robmcguinness facing same issue here. Did you find any workaround to get two endpoints? I'm getting the following error:

```bash
New route /.well-known/apollo/server-health conflicts with existing /.well-known/apollo/server-health
```

**Comment by jpgarcia** [comment]
I could workaround the `server-health` error by adding `disableHealthCheck: true,` to the appyMiddleware options. 

Now the error is `Plugin graphql already registered` 🤔

**Comment by robmcguinness** [comment]
@jpgarcia,

I extended the ApolloServer and overrode `applymiddlware` with necessary changes to enable multiple Apollo Hapi plugins. Use at your own risk. Good luck! 😀 

```js
const { ApolloServer } = require('apollo-server-hapi');
const { graphqlHapi } = require('apollo-server-hapi/dist/hapiApollo');

class MockApolloServer extends ApolloServer {
  async applyMiddleware({ app, path, route, cors }) {
    if (!path) path = '/mockql';

    graphqlHapi.multiple = true;

    await app.register({
      plugin: graphqlHapi,
      options: {
        path,
        graphqlOptions: this.createGraphQLServerOptions.bind(this),
        route:
          route !== undefined
            ? route
            : {
                cors: cors !== undefined ? cors : true,
              },
      },
    });

    this.graphqlPath = path;
  }
}
```

**Comment by jpgarcia** [comment]
Awesome! thanks for the snippet!

**Comment by flipxfx** [comment]
This is a real issue for us now after updating to 2. @robmcguinness's work around seems to work but this doesn't seem like the way to go. Makes me feel icky.

**Comment by flipxfx** [comment]
If you wanna live even more dangerously use: 

```js
const hapiApollo_1 = require('apollo-server-hapi/dist/hapiApollo');
hapiApollo_1.graphqlHapi.multiple = true
class MockApolloServer extends ApolloServer {
  async applyMiddleware({ app, cors, path, disableHealthCheck, onHealthCheck }) {
    return super.applyMiddleware({ app, cors, path, disableHealthCheck, onHealthCheck, hapiApollo_1 })
  }
}
```

**Comment by abernix** [comment]
I'm going to close this issue since it hasn't received any activity in quite some time, but I'm sympathetic to re-opening it if it's still a problem.  It's also entirely possible that this is a documentation issue and if anyone feels that way, please do open a PR to the documentation (which lives within this repository in `/docs/source`) to adjust the suggestions for Hapi, as necessary.

Lastly, we're introducing a `getMiddleware` method in Apollo Server 2.7.0 (via #2435) which might help ease the pain here.  If anyone is interested in trying that out, please see the latest `alpha` version of Apollo Server 2.7.0 by consulting the `Publish` commits in the Apollo Server 2.7.0 release PR (#2937).
