### ISSUE TITLE
Response Interceptor?

### ISSUE THREAD

**Issue by gauravmakkar** [apollographql/apollo-server#932]
I need to store every API response somewhere in the logging database. How to intercept GraphQL API response?

**Comment by abernix** [comment]
We may still tweak parts of this API but with Apollo Server `2.2.0-alpha.0`, this should be possible with:

```
const server = new ApolloServer({
  typeDefs,
  resolvers,
  plugins: [
    {
      requestDidStart({ request }) {
        console.log(request);
        return {
          willSendResponse({ response }) {
            console.log(response);
          },
        };
      },
    },
  ],
});
```

Fixed by #1795.

Let us know how it works!

**Comment by kartikjain26** [comment]
@abernix  This works but strips the response headers (null in this case) which contains traceId (as sent from the server) for logging purpose.

**Comment by abernix** [comment]
I don't understand how this would be stripping anything.  If there's a bug, please open a new issue with a _runnable reproduction_, per the instructions when opening the issue.  Thanks!

**Comment by abernix** [comment]
@kartikjain26 	I don't understand how this would be stripping anything.  If there's a bug, please open a new issue with a _runnable reproduction_, per the instructions when opening the issue.  Thanks!

**Comment by kartikjain26** [comment]
@abernix  Thanks, but I was able to extract response headers in `didReceiveResponse` hook.
Also we are actively working on apollo server but I guess the documentation is not very exhaustive. Is that being currently worked upon ?

**Comment by abernix** [comment]
If you find the documentation is specifically lacking on a particular topic, please submit a concrete issue with what information is missing.  Merely stating that the documentation is not exhaustive doesn't give us an idea where we should focus our attention.  Thanks!
