### ISSUE TITLE
`apollo-server-hapi16` mentioned in the CHANGELOG but not on NPM

### ISSUE THREAD

**Issue by dahjelle** [apollographql/apollo-server#937]
I see the [changelog](https://github.com/apollographql/apollo-server/blob/master/CHANGELOG.md#v130) has a reference to a `apollo-server-hapi16` package, but I don't see it on NPM. Is this something that still might be made available?

**Comment by abernix** [comment]
Sorry for the confusion.  We don’t intend on making this available anymore.  To find how to run Apollo Server v1 with Hapi v16, see [this section of the Apollo Server v1 documentation](https://www.apollographql.com/docs/apollo-server/v1/servers/hapi.html#Hapi-16).

**Comment by romanlv** [comment]
There is un-official implementation for hapi 16 - https://github.com/romanlv/apollo-server-hapi16
