### ISSUE TITLE
Incorrect response status for batched queries

### ISSUE THREAD

**Issue by akiran** [apollographql/apollo-server#941]
We are using apollo-link-batch-http link to batch the queries.  apollo-server is returning 200 response even for bad queries.  This is replicated in this [repo](https://github.com/akiran/apollo-server-batch-issue)

When 2 queries are batched, 1 correct and 1 wrong query like this 
```
export default compose(
  graphql(userQuery, {
    props: ({ data: { user, loading } }) => ({ user, loading })
  }),
  graphql(wrongQuery, {
    props: ({ data: { product, loading } }) => ({ product, loading })
  })
)(App);
```

Server is responding with 200 status 
```
POST /graphql 200  - 1.912 ms [
  {
    "operationName": null,
    "variables": {},
    "query": "{\n  product {\n    id\n    name\n    __typename\n  }\n}\n"
  },
  {
    "operationName": null,
    "variables": {},
    "query": "{\n  user {\n    id\n    firstName\n    lastName\n    __typename\n  }\n}\n"
  }
]
```

apollo-server responding with 200 status even if one wrong query is sent in batched mode.

if apollo-link-batch-http link is replaced with apollo-link-http, apollo-server responds with 200 status for correct queries and 400 status for wrong queries.

**Comment by evans** [comment]
@akiran Thank you for opening the issue! That's definitely the case for all batched queries, even if they are all erroring. What behavior would you prefer?

We have the option to change things with #1125

**Comment by abernix** [comment]
Closing as as effectively the same as problems identified in #1709 and as a parallel concept to what I noted within my comments on https://github.com/apollographql/apollo-server/pull/2269#issuecomment-465536880.
