### ISSUE TITLE
Typescript examples

### ISSUE THREAD

**Issue by nikitaulshin** [apollographql/apollo-server#962]
- [ ] has-reproduction
- [ ] feature
- [X] docs
- [ ] blocking
- [ ] good first issue

Hello!
I'm new to Apollo & GraphQL.
Do you have any Typescript examples of using apollo-server & graphql-tools?

Thank you!

**Comment by unicodeveloper** [comment]
@nikitaulshin there are no Typescript examples of using apollo-server and graphql-tools
